### ISSUE TITLE
Issue with "Storage Inspector": mention if there is any option to be seen the stored cookies from all sites

### ISSUE THREAD

**Issue by huc-m** [mdn/content#10014]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Storage_Inspector

#### What information was incorrect, unhelpful, or incomplete?
On Firefox (91esr)  I see only  cookies from the page were the Storage Inspector is opened. I think that there must be clarify that or must be mentioned if there is any option to be seen the cookies from all sites. 

#### Specific section or headline?
"Storage tree"  vs "Table widget"

#### What did you expect to see?
In the section "Storage tree" on the "Cookies" figure a list of cookies from various sites is shown whereas in the section "Table widget" on same page is seen only one cookie. I did not found explanation about that (in my opinion) inconsistency.

#### Did you test this? If so, how?
In the "Storage Inspector" I see only information that is related to the one page, where the Storage Inspector is shown, no matter how many sites are opened simultaneously or how many cookies there are.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/storage_inspector`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Storage_Inspector
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/storage_inspector/index.html
* Last commit: https://github.com/mdn/content/commit/fad91e3372896d71e7eb8c437079f9064283ba8c
* Document last modified: 2021-08-09T14:50:22.000Z

</details>

**Comment by ddbeck** [comment]
Hi, I'm closing this issue because [Firefox DevTools User Docs](https://firefox-source-docs.mozilla.org/devtools-user/index.html#firefox-devtools-user-docs) have moved off of MDN (see https://github.com/mdn/content/pull/14140 for details on content moved). If this issue is still applicable to the relocated documentation, please see the Firefox Source Docs site for details on raising bugs and contributing. Thanks for your understanding!
