### ISSUE TITLE
Issue with "Inline elements": incorrect statement that you can't put block elements inside inline elements

### ISSUE THREAD

**Issue by ShanjithR** [mdn/content#10070]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Inline_elements

#### What information was incorrect, unhelpful, or incomplete?
You can't put block elements inside inline elements.

#### Specific section or headline?
Conceptual differences-> Content model

#### What did you expect to see?
HTML5 allows you to put block elements inside inline elements. (OR something that says there is an option to use block elements inside inline elements in HTML5).

#### Did you test this? If so, how?
yes
I tested the code and it worked fine on html5.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/inline_elements`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Inline_elements
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/inline_elements/index.md
* Last commit: https://github.com/mdn/content/commit/775662998e66813a612e3ff27e02f2ada867bc17
* Document last modified: 2021-10-03T00:01:51.000Z

</details>

**Comment by cw118** [comment]
Hello, I realize I'm a bit late here, but I believe the docs mean that it's considered invalid HTML markup to have a block-level element within an inline element. (**TL;DR: Yes, it can be done, but it should be avoided.**)

With HTML5, an exception was added so that anchor tags (`<a>`) can nest "block-level elements"—also note that HTML5's content model redefines categories of elements rather than having only "inline" and "block", which makes it slightly more difficult to explain. I'll stick with inline and block here, but I've included links concerning new/current element categories at the end. So while modern browsers may render your HTML properly even with a block element nested within an inline one, it's not exactly good practice.

If you'd like to try it out, paste some code like the example below into an HTML validator (such as https://validator.w3.org/), and you'll get an error saying that `<span>` (an inline element in older versions of HTML) cannot contain a `<div>` element (a block-level element in previous versions of HTML):

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Invalid markup test</title>
  </head>

  <body>
    <span>
      <div></div>
    </span>
  </body>
</html>
```

You should also find that changing the `<span>` to an anchor element (`<a>`) will "remove" this error (this is the exception mentioned above).

To read more about "block", "inline", and the new content categories in HTML5:
- HTML5 element categories: https://html.spec.whatwg.org/multipage/dom.html#kinds-of-content
- There's also a page about content/element categories in the MDN Web Docs: https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories
- Article on block-level links in HTML5: https://html5doctor.com/block-level-links-in-html-5/
