### ISSUE TITLE
Issue with "d": missing  "Bearing path commands" `b` and `B`

### ISSUE THREAD

**Issue by Sheraff** [mdn/content#10076]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/d

#### What information was incorrect, unhelpful, or incomplete?
I believe the `b` and `B` parameters are missing: https://www.w3.org/TR/svg-paths/#PathDataBearingCommands

#### Specific section or headline?
It would probably be its own subsection of [path commands](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/d#path_commands), maybe "Bearing path commands"

#### What did you expect to see?
An explanation of how the B / b arguments work in SVG bezier path definition. They are not that common, but we do come across them, so some documentation would be helpful.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/svg/attribute/d`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/d
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/attribute/d/index.md
* Last commit: https://github.com/mdn/content/commit/bd3f490ef78b600a1435dfe3611a27f3f2fbf4ef
* Document last modified: 2021-09-23T21:22:12.000Z

</details>

**Comment by Josh-Cena** [comment]
As it turned out, the spec you quoted is discontinued, and neither bearing nor Catmull-Rom curves made it into SVG2. See https://github.com/w3c/svgwg/issues/818. No browser actually implements it, from my experiment using the spec's example:

```svg
<svg xmlns="http://www.w3.org/2000/svg"
     width="300" height="100" viewBox="0 0 300 100">

  <path fill="#eee"
        stroke="deeppink" stroke-width="8px" stroke-linejoin="round"
        d="M 150,10
           B 36 h 47
           b 72 h 47
           b 72 h 47
           b 72 h 47 z"/>

</svg>
```

Please correct me if that's wrong.

> They are not that common, but we do come across them, so some documentation would be helpful.

I'm not sure where you've come across them; if it's part of a non-browser SVG renderer, then that's out of scope of MDN, unfortunately.
