### ISSUE TITLE
Issue with "XMLHttpRequest: loadend event": …

### ISSUE THREAD

**Issue by ronchristie52** [mdn/content#1024]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/loadend_event

#### What information was incorrect, unhelpful, or incomplete?
The file referenced in the example - https://mdn.mozillademos.org/files/16553/DgsZYJNXcAIPwzy.jpg appears not to exist.

#### Specific section or headline?
Live example - JS

#### What did you expect to see?
Example log should show more than zero bytes transferred in the loadstart and/or loadend sections. 

#### Did you test this? If so, how?
Clicked the button in the example dialog.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/xmlhttprequest/loadend_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/loadend_event
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/xmlhttprequest/loadend_event/index.html
* Report started: 2021-01-07T04:29:47.634Z

</details>

**Comment by chrisdavidmills** [comment]
The file does exist — if you load its URL directly in a new tab, you'll see it.

However, looking at the console, loading of the image is being blocked because of a CORS error.

I think whoever fixes this would need to recreate the example in one of our GitHub demo repos (maybe in a new xhr folder inside https://github.com/mdn/dom-examples/?) and then embed it in the page using the [EmbedGHLiveSample](https://github.com/mdn/yari/blob/master/kumascript/macros/EmbedGHLiveSample.ejs) macro.

**Comment by ronchristie52** [comment]
Many thanks for the quick response to all who replied. Kudos!

**Comment by sideshowbarker** [comment]
> Many thanks for the quick response to all who replied. However, the problem as originally described still occurs in the example originally referenced. :-(

The https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/loadend_event production version doesn’t get updated immediately after we merge a fix to the sources. Instead it can take up to 48 hours before the production version gets updated.

At the time I am writing this, that change was merged 10 hours earlier. So that means it might not show up on the production site until some time on Sunday.

**Comment by ronchristie52** [comment]
Good to know. Thanks!
