### ISSUE TITLE
Could I ask a little question?

### ISSUE THREAD

**Issue by logic-finder** [mdn/content#10271]
Hello, I'm a contributor of mdn/translated-content/ko. The reason I decided to ask a question here is I found a single word which I couldn't understand the meaning of it while I had translated [this document](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Using_AudioWorklet). The sentence is as follows:

> If the returned value, newProcessorNode, is non-null, we have a valid audio context with its **hiss** processor node in place and ready to use.

According to an English dictionary and google searching, 'hiss' is a kind of sound, which seems not relevant to the context of the sentence at all. Does the word hiss have another meaning? If it does, please let me know. I really want to know the meaning of it!

In advance, I apologize if this repository is not a right place to ask a question like this.
Thank you very much.

**Comment by wbamberg** [comment]
Hi @logic-finder !

> According to an English dictionary and google searching, 'hiss' is a kind of sound, which seems not relevant to the context of the sentence at all. Does the word hiss have another meaning? If it does, please let me know. I really want to know the meaning of it!

That's correct and it doesn't really have another meaning. It's an onomatopoeic word that sounds like you going _SSSSSSS_.

But "hiss" is sometimes also used to refer to "white noise" because that's a similar kind of sound. In this example we're using an audio processor to add white noise to a sound, so the "hiss processor" is the processor that's adding  the white noise.

It's referred to as "white noise" in https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Using_AudioWorklet#high_level_overview, but referred to as "Hiss" in the example: https://mdn.github.io/webaudio-examples/audioworklet/.

So if you have already translated "white noise" in the earlier section you could use the same term here.

I hope that helps!

**Comment by logic-finder** [comment]
Thank you very much!!! If there is a mathematical sequence that expresses my gratitude to you, this sequence will diverge to `POSITIVE_INFINITY`.
