### ISSUE TITLE
Issue with "Fetching data from the server": (code issue in step 4, XMLHttpRequest section)

### ISSUE THREAD

**Issue by buttermilkcake** [mdn/content#10296]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Fetching_data

#### What information was incorrect, unhelpful, or incomplete?
I saved all my verse files with a .txt extension (ex verse1.txt). When I tried to make it run in the local testing server, I received this error:  
Failed to load resource: the server responded with a status of 404 (File not found) verse1.txt:1. 

After some weeping and gnashing of teeth and scrutinizing the code line by line, I thought that maybe in the 3rd line below, having the + '.txt'; was redundant and was adding an extra .txt in addition to the .txt I added in my file names. I removed the + 'txt'; so that the 3rd line below read  
let url = verse; 
doing that made it work - which made me happy.  

code on website
verse = verse.replace(" ", "");
verse = verse.toLowerCase();
let url = verse + '.txt';

my code
verse = verse.replace(" ", "");
verse = verse.toLowerCase();
let url = verse;

#### Specific section or headline?
Step 4 in the XMLHttpRequest

#### Did you test this? If so, how?
Yes, I made the change, refreshed my web page and it worked.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/client-side_web_apis/fetching_data`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Fetching_data
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/client-side_web_apis/fetching_data/index.md
* Last commit: https://github.com/mdn/content/commit/07453ac2b659a397b0fee921fa71db5488e9ca62
* Document last modified: 2021-10-08T14:43:33.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing!

As I read this example, the code here:

```js
verse = verse.replace(" ", "");
verse = verse.toLowerCase();
let url = verse + '.txt';
```

...is converting the text contents of the selected `<option>` element (that is, from here: https://github.com/mdn/learning-area/blob/master/javascript/apis/fetching-data/ajax-start.html#L50-L53) into the filename.

So for example it's converting "Verse 1" into "verse1.txt":

```js
verse = verse.replace(" ", "");     // "Verse 1" -> "Verse1"
verse = verse.toLowerCase();        //              "Verse1" -> "verse1"
let url = verse + '.txt';           //                          "verse1" -> "verse1.txt"
```

...it's then using the result to load the resource. So it's not adding  an extra ".txt", because there isn't one in the initial "Verse 1" string. So if the file on disk is called "verse1.txt" it should work. In fact removing the `+ '.txt'` line here should _only_ make it work if the file on disk is just "verse1" with no extension.

I just tried running through it (Firefox, macOS, and Python's http.server) and it works like that. Could you perhaps share the exact code you have that's giving the error, and double-check the names of your verse files?

**Comment by sideshowbarker** [comment]
Closing for lack of response.
