### ISSUE TITLE
Issue with "Using dynamic styling information": …

### ISSUE THREAD

**Issue by fbstj** [mdn/content#1034]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CSS_Object_Model/Using_dynamic_styling_information#modify_a_stylesheet_rule_with_cssom

#### What information was incorrect, unhelpful, or incomplete?
the first example does not work

#### Specific section or headline?
Modify a stylesheet rule with CSSOM

#### What did you expect to see?
the background should tur blue

#### Did you test this? If so, how?
I debugged it and found that the examples `document.styleSheets[0]` is not actually the same as the `<script>` tag in the example text above it. I found I could access the style tag with `document.querySelector('script').previousElementSibling'` (amongst the other array-based methods) and the example worked when I did it manually

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/css_object_model/using_dynamic_styling_information`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CSS_Object_Model/Using_dynamic_styling_information
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/css_object_model/using_dynamic_styling_information/index.html
* Report started: 2021-01-07T15:22:44.923Z

</details>

**Comment by mfuji09** [comment]
This issue is occurred because {{EmbedLiveSample}} inserts the code in `<pre>` into a `<body>` element of a template which has another `<style>` element.

So this example has two issues:
- The `<style>` element in the code is treated as the second `<style>` element in {{EmbedLiveSample}}, unlike using the code standalone.
- `<html>` element (and below) has been inserted in the `<body>` incorrectly.

In order to work this example correctly, it will work in both standalone and {{EmbedLiveSample}}, if the first line in the script element is replaced with the code below:
> `var stylesheet = document.styleSheets[document.styleSheets.length - 1];`

However the second issue won't resolved.

**Comment by mfuji09** [comment]
I have created a PR #1169 to fix the first (and the original) issue, but it still produces an incorrect code when it is used in {{EmbedLiveSample}}.

**Comment by rachelandrew** [comment]
I think a better thing to do would be to move the example to the css-examples repo and embed it from there as I think that will fix the issue. I've assigned this to myself to look into it.

**Comment by mfuji09** [comment]
@rachelandrew I agree with you, so I close the PR.
