### ISSUE TITLE
Issue with "structuredClone()": (short summary here please)

### ISSUE THREAD

**Issue by schulzf** [mdn/content#10378]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/structuredClone

#### What information was incorrect, unhelpful, or incomplete?
Compatibility was added on Node v17
https://nodejs.org/en/blog/release/v17.0.0/

#### Specific section or headline?
Compatibility
https://developer.mozilla.org/en-US/docs/Web/API/structuredClone#browser_compatibility

#### What did you expect to see?
Updated compatibility table

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/structuredclone`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/structuredClone
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/structuredclone/index.md
* Last commit: https://github.com/mdn/content/commit/2a10b35c098e474dc1c9c7b4d669aa55ac8c6368
* Document last modified: 2021-10-12T08:42:00.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks very much @schulzf ! Just FYI, stuff in that browser compatibility table is maintained separately in a data repository - this one is fixed in https://github.com/mdn/browser-compat-data/pull/13382. It doesn't matter if you post it here, but even better to post this kind of issue against that repository.
