### ISSUE TITLE
[Prettier] Create automation for reviewers to apply code format to PRs

### ISSUE THREAD

**Issue by ddbeck** [mdn/content#10406]
This is part of https://github.com/mdn/content/issues/10402. It's **blocked** by https://github.com/mdn/content/issues/10405.

Many PRs come through GitHub's web editor. Such edits won't get the benefit of automatic code formatting. It's unlikely that such contributors will fix the formatting themselves (since they'll have to clone the repo and such). Reviewers will be able to apply code formatting after the fact, but they'll have to check out the PR branch, adding considerable overhead to routine reviews.

Instead, we should create a GitHub Actions workflow to apply our Prettier config to files changed in a PR, which is triggered by adding a special label to the PR.

**Comment by tlylt** [comment]
Hi there, since #10405 has been resolved, curious if this issue is still relevant and needs work? (I'm happy to lend a hand 😃)

**Comment by teoli2003** [comment]
We have taken a different approach here: we add tests that indicate if it is compliant with Prettier and Markdown, as well as run Husky on PRs to automatically run linter (currently only Markdownlint, but likely Prettier in the future).

So adding this feature is likely to be unnecessary. I will go forward and close this issue. If, once Prettier is activated everywhere, we notice we need this feature, we will anyway open a new issue because we will have forgotten about this one 🤣 

Thanks for proposing your help, though. Much appreciated.
