### ISSUE TITLE
Link element - title attribute - broken link

### ISSUE THREAD

**Issue by moniuch** [mdn/content#10437]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link
The link that describes how an improper usage of title can disable it is broken

![Kitchen Sink 2021-11-10 22-07-51](https://user-images.githubusercontent.com/681956/141193686-46fc5c48-eba8-4fd1-949e-92cfcf5ae5a7.png)

**Comment by hamishwillee** [comment]
Thanks @moniuch - you will find lots of broken links in the docs - either caused by removed topics (archived in this case) or unwritten topics we'd like someone to be created.

I have simply removed the link sentence as I think it isn't useful - there is another link in this section which talks about alternate stylesheets and that covers how title is used.
