### ISSUE TITLE
Issue with "AsyncFunction": (code in example generates only errors)

### ISSUE THREAD

**Issue by Pdzoc** [mdn/content#10507]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncFunction

After running this code I received only errors (depends on place where I pasted code).

In playcode.io:

`error: Uncaught SyntaxError: await is only valid in async functions and the top level bodies of modules`

In Chrome (ver. 95.0.4638.69) console: 

`Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src chrome://resources chrome://test 'self' 'unsafe-inline' https:".

    at new AsyncFunction (<anonymous>)
    at <anonymous>:11:9`

In stackblitz there were either no errors nor results in console.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/asyncfunction`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncFunction
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/asyncfunction/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by anushkacreates** [comment]
Hey,

I think this is because using 'new' in `a = new AsyncFunction()` violates the Content Security Policy (CSP) of the extensions.

If you run this code in a webpage (like an html file having script.js and this code inside script.js), it runs perfectly fine.

#### Check out these links: 
- [https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_Security_Policy#eval_and_friends](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_Security_Policy#eval_and_friends)
- [https://developers.google.com/web/fundamentals/security/csp](https://developers.google.com/web/fundamentals/security/csp)

Hope this helps!

**Comment by Pdzoc** [comment]
Yes, you are right. When I read more info from this error I noticed that exactly this line with "new AsyncFunction(...)" caused the problem. It is interesting that when I open any web or even html file from my machine and then I paste code in console this problem does not appear. Any way, thank you for advices.
