### ISSUE TITLE
Content bug: Handling pages with incorrect and/or incomplete information

### ISSUE THREAD

**Issue by tannerdolby** [mdn/content#10594]
## What page(s) did you find the problem on?
> exception is en-US/docs/Learn/Common_questions/HTML_features_for_accessibility. Information is incomplete and not fully correct, so please keep draft on that page as well.

Currently found on:
- en-US/docs/Learn/Common_questions/HTML_features_for_accessibility

mentioned in this [comment](https://github.com/mdn/content/pull/10504#issuecomment-971811094) by @wbamberg 

Related to #10504

## What is the problem?
Pages with incorrect and/or incomplete information should be tracked in a separate bug to be handled accordingly.

## What did you expect to see?
TBD

## Did you test this? If so, how?
N/A

**Comment by sideshowbarker** [comment]
@tannerdolby From the issue description, it’s not clear to me at least what problem is being described here, or how we might be able to resolve this. Maybe @wbamberg remembers something about the context

**Comment by tannerdolby** [comment]
@sideshowbarker I think this was related to the `{{ Draft }}` macro removal that was going on which is now completed. Looking back at my issue description above, its not entirely clear what the problem was but from what I remember this issue should be resolved. Just to be safe, probably best to wait for @wbamberg for the final say.

**Comment by wbamberg** [comment]
I asked for this bug because in https://github.com/mdn/content/pull/10504#issuecomment-970624479, @estelle asked to keep `{{draft}}` for https://developer.mozilla.org/en-US/docs/Learn/Common_questions/HTML_features_for_accessibility. because the page needs updating.

In a case like that I thought it would be better to have a bug on file to update the page. I don't know exactly what updates are needed, but @estelle might. But if we can't elaborate exactly what updates are needed, we can just close this bug.

**Comment by estelle** [comment]
That page should be deleted and point to the accessibilty section. It's kind of all worst practices: tabindex other than 1 or 0 should never be used, title attributes don't make anything more accessible for screen reader users. 

OK, so I started a rewrite. Still want to add labels, aria-* attributes, viewport meta tag, and links to a11y information, but https://github.com/mdn/content/pull/19338 is a huge improvement.
