### ISSUE TITLE
Issue with "Content-Location": for 201 Created, use Location instead

### ISSUE THREAD

**Issue by stiiin** [mdn/content#10809]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Location

#### What information was incorrect, unhelpful, or incomplete?
`Content-Location` is used for content negotiation purposes, meaning "you can find the same content of this response at this other URL". However, one of the examples in this article shows a `201 Created` response using this header to mean "you can find the created resource at this other URL".

The article about [the `Location` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Location) explicitly points out `201` as of the statuses where the `Location` header has meaning, and summarises the difference as follows (though the wording is a bit cryptic):

> `Location` is a header associated with the response, while `Content-Location` is associated with the entity returned.

#### Specific section or headline?
Pointing to a new document (HTTP 201 Created)

#### What did you expect to see?
I expected this example to be on the article about `Location` instead, and optionally a caveat in the `Content-Location` article that you should use Location for this purpose.

#### Did you test this? If so, how?
I did not test this.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/headers/content-location`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Location
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/content-location/index.md
* Last commit: https://github.com/mdn/content/commit/46234997b6257b619423a11ce31154afa336143f
* Document last modified: 2021-08-13T16:17:49.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks!

This is all very confusing, but what is clear from the spec is that a `201 created` response can contain either or both headers.

The description of the difference needs to be refined a bit. The main difference is that
- `Location` is essentially a response that tells you that you can get the resource you just asked for or created at a particular URL. So you asked for a resource but it has moved, this tells you were you can go to get it. Or you created a new resource, perhaps in multiple formats, this tells you were you can go to get it.
- `Content-Location` tells you that you requested a resource of a specific type(s)  at what was probably a generic endpoint. It tells you that you have the file in the response (so you don't need to download it again) and gives you a direct URL for getting that same time of format for that same resource in future. 

So a POST might have created a whole bunch of resources. The `Location` in the response just lists the primary one. There is no proper definition of "primary resource" but I expect this will generally mean an endpoint which you can request for any format of the resource

So consider a client with data it uploads but does not understand - e.g. a special file format. It uploads the file and get's `Location` back. It might then need to re-request the file in a MIME type it does understand.

However it might be that you get back `Location` and `Content-Location`. In this case I'd expect the URLs to match and the payload to contain the resource you just uploaded. IF the client understands the file format it would not have to re-request the resource - it would know it has the latest version and also have the URL it can goto to get it again.

So what does this all mean?
1. We could duplicate this for `Location`, replacing the `Content-Location` header with `Location`
2. The example in `Content-Location` is definitively wrong for that header because it needs to contain a payload and should also include a `Location` header. 

Does this make sense? If so I can update appropriately. @teoli2003 make sense to you too?

**Comment by stiiin** [comment]
Hi @hamishwillee, thank you for your extensive reply.

In my understanding, `Location` points to another resource with a meaning specific to the response status, while `Content-Location` points to a resource that, when applying GET to it, should yield the same response body as the current response body (basically telling the User-Agent that the response is cacheable under another key).

I think your analysis boils down to the same interpretation, so it makes sense to me, as do your suggestions.
