### ISSUE TITLE
Issue with "Contributing to MDN": Grammatical Error (Correct punctuation)

### ISSUE THREAD

**Issue by iamreynatgithub** [mdn/content#10817]
MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Contribute

#### What information was incorrect, unhelpful, or incomplete?
1. I think there seems to be a missing comma, between the word "easy" and "to"? 
2. I think the comma between the word "with" and the dependent clause marker "if" is not necessary.
3. I think the adjective "entire", must be "entirely"? because it modifies the adjective "new".

#### Specific section or headline?
At the bottom, under the "Where is everything on MDN? A guide to our repos" heading.
1. 2nd sentence of the paragraph.
2. 2nd sentence of the paragraph.
3. 3rd and last sentence of the paragraph.

#### What did you expect to see?
Correct punctuation:

"MDN is a complex project with lots of moving parts. Contributing to the site is easy, to begin with if you have a bit of GitHub knowledge and are starting out on some simple typo fixes or code snippet improvements. However, when you start making more significant contributions such as adding entirely new pages, you'll notice that there are quite a few bits of the content that aren't stored in the page sources and instead come from somewhere else."

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mdn/contribute`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Contribute
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/index.md
* Last commit: https://github.com/mdn/content/commit/32f6335487194aa8c3a9fb5c90eeba5e95be6224
* Document last modified: 2021-10-15T15:32:38.000Z

</details>

**Comment by AnilSeervi** [comment]
> Keep in mind that MDN contains technical documentation; you should not report merely basic improvements in the grammar but only cases where the grammar is incorrect.

README - https://github.com/mdn/content#pull-request-etiquette

**Comment by hamishwillee** [comment]
@iamreynatgithub Just to add a little flavour to the comment above ^^^. In the past we've had enthusiastic contributors create numerous grammar-only issues and pull requests, often creating by pumping the page through Grammarly.

That was a problem because:
- the technical domain we're in uses a vocabulary that is not well understood by Grammarly. It is easy to modify a single word and unintentionally change the intended meaning. This is in particular true of CSS and anywhere we use terminology with a precise definition from a specification.
- We have limited review resources - many of the suggestions were particularly nitpicky and time consuming to review.

So, 
- I personally prefer PRs over issues - i.e. you make the change and we can see it in place.
- Ambiguous and confusing punctuation and typographic errors are worth fixing. Nitpick fixes not worth it unless you're already working on the page. 

Hope that makes sense? I haven't honestly read your proposal. If think it is likely to cause confusion among reasons, a pull request is welcome.

**Comment by AnilSeervi** [comment]
Totally agree with @hamishwillee .

I think that the thing about contributors piping MDN's technical content into grammar checking tools should be added to the README.

There will be many contributors who will start out Open Source contribution this way and some others might overwhelm the maintainers. Adding a point about this in the README might save you some time by being able to quote it and close issues/PR if they are unnecessary.

**Comment by hamishwillee** [comment]
@AnilSeervi IMO probably not. Most people are just trying to help. I normally just ask for a PR for any grammar fix. That makes it easy to review, and which point I'd make the nitpick comment if the fix was more hassle than it was worth my time to parse.

**Comment by AnilSeervi** [comment]
That's very generous of you! @hamishwillee :)
