### ISSUE TITLE
[HTML] Option to Unhide Entry of Password

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#10855]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
or
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

Not entirely sure why this bug has `dev-doc-needed` without reading the long thread. So this requires a read of the bug itself and a judgement on whether any doc updates are actually needed for it. Possibly something we mention in BCD?

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=502258

**Comment by hamishwillee** [comment]
This adds support for  show password icon in [`<input type="password">`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/password) inputs behind the preference `layout.forms.input-type-show-password-button.enabled`.
![image](https://user-images.githubusercontent.com/5368500/145744437-d4e55bed-92dc-40f9-80ab-6fde2ac5d49d.png)

This is not defined in a spec - the closest thing is this issue: https://github.com/whatwg/html/issues/7293
There is some concern about the interaction with sites that implement this feature themeselves, and how this might interact with the other "sub controls" that might appear on some browsers.

My feeling is that it is too early to document this "properly". In #11171 what I have done is added experimental feature and also noted that it is a possible that this kind of behaviour might exist for a browser.

IMO No BCD yet. I don't necessarily see this any kind of "compatibility" issue yet, since the the behaviour is not specced and the concerns about how other browsers might work with this are still in discussion.

Upshot, this this is done.
