### ISSUE TITLE
[WebAPI] Web Share: Implement canShare() method

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#10852]
## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [ ] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

[Web Share] Implement canShare() method

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1666203

**Comment by hamishwillee** [comment]
Hi @Rumyra 

FYI, this is not a release because the share API is still behind a preference.

Fortunately I did most of the work for [Navigator.canShare()](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/canShare) in https://github.com/mdn/content/pull/8381. 

Mostly this is just a release note and an update to BCD.

**Comment by Rumyra** [comment]
Going to close in light that BCD will eventually be merged - I can check at the end of the project 👍
