### ISSUE TITLE
Content bug: Network request list docs are missing a column and contain an outdated image

### ISSUE THREAD

**Issue by adamthedog** [mdn/content#10930]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/request_list

## Specific page section or heading?

https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/request_list#network_request_columns
(In the list of columns)

## What is the problem?

The document is missing a description of the column `Initiator` and the included image shows a now-removed `Timeline` option in the context menu for selecting visible columns.

## What did you expect to see?

A description of the column `Initiator` and no `Timeline` column in the screenshot.
To fix:
- Initiator should have at the least a simple description. Perhaps a new docs page may be created for more in-depth information, as the field is somewhat complex. As an example, Sebastian Zartner's comment in [a bug report/feature request related to the `Initiator` field](https://bugzilla.mozilla.org/show_bug.cgi?id=1230922) has some information about the different values possible.
- A new screenshot of the context menu for selecting visible columns should be added to reflect the actual current menu.

## Did you test this? If so, how?

N/A

**Comment by ddbeck** [comment]
Hi, I'm closing this issue because [Firefox DevTools User Docs](https://firefox-source-docs.mozilla.org/devtools-user/index.html#firefox-devtools-user-docs) have moved off of MDN (see https://github.com/mdn/content/pull/14140 for details on content moved). If this issue is still applicable to the relocated documentation, please see the Firefox Source Docs site for details on raising bugs and contributing. Thanks for your understanding!
