### ISSUE TITLE
Issue with "Classes": redeclaration error

### ISSUE THREAD

**Issue by Amitdey13** [mdn/content#10976]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes

## This is the line 
Uncaught SyntaxError: Identifier 'ClassName' has already been declared at <anonymous>:1:1.

Another line above it have same issue which is also a syntax error line. 

Specifications

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/classes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/classes/index.md
* Last commit: https://github.com/mdn/content/commit/3c3c390d4b364e21851ff26ecae4ee3c7901a6c6
* Document last modified: 2021-11-09T17:33:20.000Z

</details>

**Comment by AnilSeervi** [comment]
Support for let and class redeclarations in the Console - [Added in Chrome 80](https://developer.chrome.com/blog/new-in-devtools-80/)

**Comment by hamishwillee** [comment]
@Amitdey13 Thanks for posting, but this is not enough information to debug.  *Exactly* what section and code are you trying that gives this error?

It is possible that the problem is that you're using an old version of Chrome (or at least that is what @AnilSeervi is suggesting. Can you try again with the latest version.

**Comment by sideshowbarker** [comment]
Closing for lack of response
