### ISSUE TITLE
Content bug: channelCountMode

### ISSUE THREAD

**Issue by TheSlowGrowth** [mdn/content#11119]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/API/AudioNode/channelCountMode

## Specific page section or heading?

The table at the top of the page

## What is the problem?

1. The `channelCountMode` of a `ChannelMergerNode` is documented as `max` while [the spec](https://webaudio.github.io/web-audio-api/#dom-audionode-channelcountmode) states it should always be `explicit`
2. The value of `max` is documented to consider the maximum across all connections, while [the spec states it should only consider the input connections](https://webaudio.github.io/web-audio-api/#enumdef-channelcountmode).

**Comment by tilltonystark** [comment]
Hey there! I'm a beginner and wanted to contribute in MDN Web Docs. So, can you please guide me through this.

**Comment by hamishwillee** [comment]
Hi @tilltonystark ,
Welcome, and thank for offering to help! I've assigned to you. 

For this case the first thing to do is read the issue and see if you agree with it. That means looking at the page and looking at the spec. 

What they are saying is that this element should move in the table. 
![image](https://user-images.githubusercontent.com/5368500/147421413-7c366c01-a945-47e8-bb34-9a3ba000711e.png)

I think it should, but you should check this yourself!

As this is a little change, you can just edit in the github UI. Easy enough, at the bottom of the page that has been reported there is this link shown below. If you select that you'll be take to the page for editing and making a pull request (PR). 

![image](https://user-images.githubusercontent.com/5368500/147421436-9db34dcb-1295-4462-8ce5-b34bea0cffc3.png)

--- 

An aside ...

Many issues, like this one, can be fixed in  github. If you start helping with bigger issues - where you ever need to add images or move pages for example, you will need to read up on the instructions here: https://github.com/mdn/content#making-contributions

**Comment by moflaky** [comment]
Hello, not sure if this is relevant anymore, but the original issue seems to make sense to me.  I would love to contribute to mdn docs on this issue. Thanks!
