### ISSUE TITLE
Issue with "Element.requestPointerLock()": Isn't listed as returning a Promise

### ISSUE THREAD

**Issue by Vanilagy** [mdn/content#11282]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/requestPointerLock

#### What information was incorrect, unhelpful, or incomplete?
In newer versions of Chromium, this method actually returns a promise that will visibly throw in the console whenever the pointer lock doesn't go through. Would be good to add that to the page so users can catch this error.

Here's an example:

![image](https://user-images.githubusercontent.com/1696106/146578855-c9063bf6-7e03-4867-9765-bc066b578d24.png)

#### Specific section or headline?
Return value, I guess?

#### What did you expect to see?
An explanation that it returns a Promise on **some** browsers. (On Safari, for example, it doesn't)

#### Did you test this? If so, how?
Yes, verified in Chrome that it returns a Promise; using Browserstack I verified that it doesn't in Safari.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/element/requestpointerlock`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/requestPointerLock
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/requestpointerlock/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by hamishwillee** [comment]
@Vanilagy Thanks for posting.

Chromium has gone and implemented some non-spec behaviour. They are trying to get it made part of the spec in [Add lock options to requestPointerLock - spec PR](https://github.com/w3c/pointerlock/pull/49). That's why it isn't documented yet, and why it may be too early still to do so. 

Either way though this API needs more work, which I have highlighted in https://github.com/mdn/content/issues/11327.

@Rumyra What's your take on this - do we record the non-spec behaviour of Chrome here, or in BCD, or do we "wait and see"?  My leaning is wait and see.

Some more background here:

- [Intent To Ship: Pointer Lock Unadjusted Movement](https://groups.google.com/a/chromium.org/g/blink-dev/c/cQn7OwcMQ64) -
- [Unadjusted Pointer Lock Movement Explained](https://github.com/slightlyoff/unadjusted_pointer_lock_explainer)

**Comment by Vanilagy** [comment]
I'd actually argue you record the (albeit non-spec) change. There are many such Chromium-only API features in the web already, and for my website at least, having the console suddenly be full of uncought error messages and having to figure out the changed signature myself instead of looking it up on MDN was a bit confusing.

Maybe just state Chromium's behavior to be non-spec.

**Comment by Rumyra** [comment]
This is defo something for BCD @hamishwillee - if the spec is going to change then we'll update the docs, but until then we document what the spec says 👍

**Comment by Vanilagy** [comment]
I'm not experienced with writing documentation, but shouldn't MDN reflect what browsers do instead of what the spec says they should do? 🤔

**Comment by Rumyra** [comment]
@Vanilagy I'll elaborate a bit - BCD is browser compatibility data, which is displayed on the relevant MDN pages for each feature. This holds information about any variations browsers have on spec implementations. The data is held in a [separate repository here](https://github.com/mdn/browser-compat-data). So this information will be available on the page, it just doesn't require an update to the 'content', which is what this repository handles 👍

**Comment by hamishwillee** [comment]
Thanks. So never quite sure how to record these things - but started the ball rolling in https://github.com/mdn/browser-compat-data/pull/14091

**Comment by hamishwillee** [comment]
Closing, as BCD now indicates the non-spec behaviour
