### ISSUE TITLE
Issue with "KeyboardEvent": Section order inconsistency

### ISSUE THREAD

**Issue by AgentSam** [mdn/content#11325]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent

#### What information was incorrect, unhelpful, or incomplete?

Section ordering in the article is inconsistent.

In particular, the section "Obsolete properties", is oddly placed below "Obsolete methods".

If current/valid properties are presented in the order:
- Properties
- Methods

Why would obsolete properties/methods be presented in the reverse order:
- Obsolete Methods
- Obsolete properties

#### Specific section or headline?

The article CURRENTLY has the following sections (in this order):
- Properties
- Methods
- Obsolete methods
- Obsolete properties

#### What did you expect to see?

I would expect these sections to be ordered as follows:
- Properties
- Properties (Obsolete)
- Methods
- Methods (Obsolete)

#### Summary

I cannot see the logic in the current order. It's propably just an oversight by whoever edited those "obsolete" sections previously.

My reasoning for the fix is, that all "properties" and "methods" should be "grouped together", as shown above.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/keyboardevent`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/keyboardevent/index.md
* Last commit: https://github.com/mdn/content/commit/a7261cd6aebb479bcc359216fe55f9267fa3a865
* Document last modified: 2021-11-16T02:32:25.000Z

</details>

**Comment by hamishwillee** [comment]
The fact that order is prop/method/ob. method/ob. property grates a little because it is inconsistent. But there isn't any standard way we do the ordering or naming of obsolete things. Further different people have different expectation -  I am keen not to use obsolete properties, so I would much prefer them at the end rather than immediately following the valid properties.

Upshot, if you would like to change it to your taste that would be fine as a PR, preferably if it was associated with some technical improvements as well. 

But it isn't a defect so I am closing this.

**Comment by AgentSam** [comment]
> But there isn't any standard way we do the ordering or naming of obsolete things.

Can we devise a "standard way" of naming such sections? (I do have some ideas on that.)

What would be the appropriate place to discuss this?

> Upshot, if you would like to change it to your taste that would be fine as a PR, preferably if it was associated with some technical improvements as well.

Assuming that there is currently no "standard way" of naming or ordering the sections in the Web API docs, I foresee a strong possibility that I will encounter similar *inconsistencies* as I continue reading/using the documentation.

So far I haven't noticed anything to improve on the *technical side* of the docs. But yea, obviously, if I do spot something I'll be sure to submit a fix.

**Comment by hamishwillee** [comment]
@AgentSam Have a look at the template pages in https://developer.mozilla.org/en-US/docs/MDN/Structures/Page_types as that is what we're supposed to copy for most stuff. Then you can raise general suggestions for discussion in https://github.com/mdn/content/discussions

For this particular case the inconsistency is greater than we have discussed.
1. The term obsolete is no longer used broadly in MDN. We use deprecated instead to globally mean "do not use".
2. We don't commonly remove the deprecated methods and properties into their own sections, though there are cases (like this one). Instead the `{{deprecated_inline}}` macro is used to mark up the properties in place.

But we haven't gone and fixed that up, because the inconsistency does not great harm, and we're busy trying to work on the technical content. Which is NOT to discourage you - consistency is important - but to let you know not to expect people to treat this as their highest priority.
