### ISSUE TITLE
Issue with "Reason: CORS request not HTTP": (short summary here please)

### ISSUE THREAD

**Issue by EddieRich** [mdn/content#11338]
"This new behavior is enabled by default using the privacy.file_unique_origin preference."
Well, unfortunately that "preference" does not exist and you provide no instructions on how to set it to false.
I am writing my own html and javascript but I can't even open this in the browser.

MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/cors/errors/corsrequestnothttp`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/cors/errors/corsrequestnothttp/index.md
* Last commit: https://github.com/mdn/content/commit/46234997b6257b619423a11ce31154afa336143f
* Document last modified: 2021-08-13T16:17:49.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks for reporting @EddieRich 

The preference was a bit of a hack to get developers through the first phase when local files started violating CORS - it has since been removed. There are a number of ways to get around the problem for different browsers, but the right way is to serve your files locally using a local testing server. See https://developer.mozilla.org/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server for how.

This works because if you serve from localhost over HTTPS then CORS is not violated - all the resources come from the same origin. 

I'll tidy up this and a few other related docs.

**Comment by EddieRich** [comment]
Thank you for the response @hamishwillee.
I did follow that link and tried the python server, I had the same problem.
In case someone else finds this issue, I'm including my resolution.
After hours of searching I found that firefox has another hidden setting.
security.fileuri.strict_origin_policy must be set to false.
After setting that and restarting the browser, everything worked fine.

**Comment by hamishwillee** [comment]
@EddieRich Thanks. It shouldn't be possible to have that same problem, so something else might be going on. Would be be possible to provide the files that are causing you problems so I can try it out?

I'm going to hit reopen so I don't forget this.

**Comment by EddieRich** [comment]
@hamishwillee It's a kids card game called 'war'. I'm just starting to learn web programming.
The public repository is at https://github.com/EddieRich/war

**Comment by hamishwillee** [comment]
@EddieRich Thanks. You've got a 404 issue on a missing favicon, but the local server workaround definitely works (`py -3 -m http.server`) served from the root of your repo.

![image](https://user-images.githubusercontent.com/5368500/147429573-0192cdf2-58eb-4956-af57-b945c0030bce.png)

I am therefore going to close this because the solution works, and it should work for all browsers not just Firefox.
