### ISSUE TITLE
[WebAPI] OffScreenCanvas on by default

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#11591]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

There's a lot of bugs around this implementation, so worth checking related bugs, but `offScreenCanvas` should be on by default in 97

## Notes

The preference for enabling this is `gfx.offscreencanvas`. This is mentioned in the following files:

- `files/en-us/mozilla/firefox/releases/44/index.md`
- `files/en-us/mozilla/firefox/releases/44/index.md`
- `files/en-us/mozilla/firefox/experimental_features/index.md`

## Related issues and PRs

- [x] BCD https://github.com/mdn/browser-compat-data/pull/17512
- [x] Dom examples: https://github.com/mdn/dom-examples/pull/159
- [x] Content additions: https://github.com/mdn/content/pull/20089
- [x] New canvas context additions: https://github.com/mdn/content/pull/19859

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1746110

Also Implement AnimationFrameProvider for dedicated workers is related https://bugzilla.mozilla.org/show_bug.cgi?id=1738971

**Comment by hamishwillee** [comment]
Status. This is behind a pref, so not a "release". 

- [ ] BCD - need to check the version on which this became disabled so we can update when it became re-enabled. 
- [ ] Docs - [ScreenOrientation.lock()](https://developer.mozilla.org/en-US/docs/Web/API/ScreenOrientation/lock) updates - in progress  https://github.com/mdn/content/pull/11684
- [ ] dev-doc-complete
- [ ] Experimental features addition

**Comment by hamishwillee** [comment]
Status:

This is nightly-only enabling of the preference `gfx.offscreencanvas.enabled`. This just got backed out, so right now there might be nothing to do. In any case, it is not a "release" item.

If it goes back in, this is in [experimental features](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features#graphics_canvas_webgl_and_webgpu) so that would need to be updated. The docs appear to be done: [OffscreenCanvas](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas)

I still need to look at https://bugzilla.mozilla.org/show_bug.cgi?id=1738971

**Comment by Rumyra** [comment]
Thanks @hamishwillee - I've done some stuff with offscreencanvas, so I can take a look at the dedicated worker stuff.

I also need to check through bugzilla again as I created these issues for 97 earlier than usual, so I was wondering whether something would get backed out

**Comment by hamishwillee** [comment]
@Rumyra That would be great! My assumption, unless you say otherwise, is that you are taking this over? That means creating the new docs and examples?
You could proceed with this documentation either way because it all works on Chrome.

I've updated the BCD for the [Implement AnimationFrameProvider for dedicated workers](https://bugzilla.mozilla.org/show_bug.cgi?id=1738971) bug in https://github.com/mdn/browser-compat-data/pull/14454 since that is in and unlikely to be backed out. This would need a docs link added in BCD once you have created those. 

Happy to take this back if needed, but I am sure you will do a better job.

**Comment by hamishwillee** [comment]
@Rumyra Note, there is also this response related to this discussion: https://bugzilla.mozilla.org/show_bug.cgi?id=1738971#c17

**Comment by Rumyra** [comment]
Yeh I've been saving this for last because it's my favourite 😂 I don't think I'll get the docs done before release on Tues, but I'm not stressing about it. (We're missing a prominent function in the implementation for my demo to work anyway) If BCD is up to date and I'll add to rel notes, I think this is cool

**Comment by Rumyra** [comment]
Yeh this is the bit that is needed for the demo `HTMLCanvasElement.transferControlToOffscreen` and is mentioned. Because `OffScreenCanvas` is still behind a pref for 97, that relaxes me further for doc updates. I'll add a rel note about `AnimationFrameProvider` tho

**Comment by Rumyra** [comment]
Making a note for when I come back to this:

- [ ] Check requestAnimFrame & cancelAnimFrame pages
- [ ] Check offscreencanvas page
- [ ] Add link to bcd
- [ ] Move offscreencanvas ex rel note to release

**Comment by Rumyra** [comment]
Some related bugs:

- https://bugzilla.mozilla.org/show_bug.cgi?id=1746750
- https://bugzilla.mozilla.org/show_bug.cgi?id=1745984
- https://bugzilla.mozilla.org/show_bug.cgi?id=1756186
- https://bugzilla.mozilla.org/show_bug.cgi?id=1751721

**Comment by hamishwillee** [comment]
@Rumyra This requires some urgent attention. Released in nightly on in 104: https://bugzilla.mozilla.org/show_bug.cgi?id=1746110 and shipping in FF105: https://bugzilla.mozilla.org/show_bug.cgi?id=1779009

For FF104 I have updated BCD to include the preview in https://github.com/mdn/browser-compat-data/pull/17512 - note however that all this does is update things that have the matching preference. I haven't gone through the IDL yet and made sure that it all matches the spec.

FYI, got to this through https://github.com/mdn/content/issues/18772 which is an example of something that is behind that pref but was not documented.

**Comment by Rumyra** [comment]
Thanks @hamishwillee - yes shipped to release next month https://bugzilla.mozilla.org/show_bug.cgi?id=1779009

**Comment by hamishwillee** [comment]
@bsmth FYI, I've done the work for `CanvasRenderingContext2D.fontKerning` in #18772. However the same feature is present if you do `OffscreenCanvasRenderingContext2D.fontKerning`. Since that is part of "this" job I was wondering if you have a rough ETA?

Note that and`OffscreenCanvasRenderingContext2D.fontKerning` is almost identical, except it doesn't implement `CanvasUserInterface` (see [here](https://github.com/mdn/content/issues/18772#issuecomment-1221925452)) which means that you can copy the `CanvasRenderingContext2D` property docs as a start. THe work then being to write a live example that you can use to demo this and also  to work out what is implemented in different browsers.

Anyway, let me know if you need me to help. I suspect you'll be more capable, but you look like a lot is assigned to you right now.

**Comment by bsmth** [comment]
Hi @hamishwillee , thanks a lot for checking in. The current state of my branch is here: https://github.com/mdn/content/compare/main...bsmth:content:11591-OffScreenCanvas

I have removed the experimental flags and the notes stating it's behind a pref.

>Note that andOffscreenCanvasRenderingContext2D.fontKerning is almost identical, except it doesn't implement CanvasUserInterface (see https://github.com/mdn/content/issues/18772#issuecomment-1221925452) which means that you can copy the CanvasRenderingContext2D property docs as a start.

OK very good, I'll get going on that shortly. As I see it, that leaves the following outstanding:

* work out what is implemented in different browsers (for `OffscreenCanvasRenderingContext2D`)
* live example for `OffscreenCanvasRenderingContext2D.fontKerning`

Let me know if I've missed anything!

**Comment by hamishwillee** [comment]
Just in the context of `OffscreenCanvasRenderingContext2D` - I'm not commenting about any of the rest of the offscreen API.
- all of OffscreenCanvasRenderingContext2D needs to be documented. 
- YOu can mostly copy `CanvasRenderingContext2D` but you will need to do something about the live examples because they are not offscreen. And of course you might want to do something that shows them with a worker, which won't work "live".
- Yes, the BCD needs to be extended for OffscreenCanvasRenderingContext2D to show what is supported in more detail. It is insufficient.
-

**Comment by hamishwillee** [comment]
Hi @bsmth ,

FYI, discovered that we didn't do the BCD for the 105 final release. I can see the release note so I assume everything else required for the release was done though.
