### ISSUE TITLE
`window.navigator` documentation  different letter case are used in header and code.

### ISSUE THREAD

**Issue by khairnarsaurabh23** [mdn/content#11640]
https://developer.mozilla.org/en-US/docs/Web/API/Window/navigator page in MDN docs has header as - 
'Window.navigator' 
But when this property actually used in code as
'navigatorObject = window.navigator' 

Is this a typo or I'm getting something wrong?

**Comment by sideshowbarker** [comment]
The header should rightly not have `Window.navigator` but instead be formatted in some way that doesn’t make it look like `navigator` is a static property of the `Window` object.

See the discussion at https://github.com/mdn/content/discussions/5121

But in the specific case of `Window`, since there is actually a global `window` object, we arguably should instead just re-title all the `Window` articles to just be `window` instead.

Regardless, whatever ends up being decided about it will be done as part of resolving https://github.com/mdn/content/discussions/5121

So I’m going ahead and closing this as being a known issue that we’re already tracking in https://github.com/mdn/content/discussions/5121
