### ISSUE TITLE
WeakSet and WeakMap are weak references. Why can they not be enumerated?

### ISSUE THREAD

**Issue by PaulMing** [mdn/content#11665]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap

WeakSet and WeakMap are weak references. Why can they not be enumerated? The document only describes the relationship with the garbage collection mechanism. Can it be described in more detail? Because readers don't know much about garbage collection mechanism
![image](https://user-images.githubusercontent.com/40627394/147873550-d50c3f6f-267f-41a8-850f-4588d1d5bacb.png)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mdn/contribute/feedback`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Contribute/Feedback
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/feedback/index.md
* Last commit: https://github.com/mdn/content/commit/32f6335487194aa8c3a9fb5c90eeba5e95be6224
* Document last modified: 2021-10-15T15:32:38.000Z

</details>

**Comment by bakkot** [comment]
"Because the references are weak" isn't quite right; it's really "because the references are weak _and_ we don't want to expose details of garbage collection".

If WeakSet (e.g.) were enumerable, then you could observe whether an object `o` had been garbage collected by doing e.g. `let set = new WeakSet([o]); /* other stuff happens */; console.log([...set].length > 0 ? 'o has been collected' : 'o has not been collected');`.

Garbage collection is nondeterministic and its precise mechanics vary between engines and versions of engines, which means it's difficult to write interoperable programs when their behavior depends on how garbage collection happens. So the language tries to avoid exposing information like "has this thing been garbage collected" unless absolutely necessary (as it is for WeakRefs and FinalizationRegistry).

**Comment by mhofman** [comment]
WeakMap and WeakSet are actually not weak references at all, they're ephemerons. I though MDN used to talk about them, but I must have dreamt it. The v8 blog post on [weak references](https://v8.dev/features/weak-references) does a pretty good job of explaining the difference.

**Comment by sideshowbarker** [comment]
OK, I’ve opened #11765 with some changes that attempt to clarify how `WeakMap` differs from a true weak reference, and why that means it can’t be enumerated. Review of those changes would be very welcome.

Rendered output with the changes incorporated is at:

* https://pr11765.content.dev.mdn.mozit.cloud/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap
* https://pr11765.content.dev.mdn.mozit.cloud/en-US/docs/Web/JavaScript/Guide/Keyed_collections#weakmap_object

The diff is at https://github.com/mdn/content/pull/11765/files.
