### ISSUE TITLE
Officials docs refer to a missing setting

### ISSUE THREAD

**Issue by scannerdarkly** [mdn/content#11674]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/about:debugging

#### What information was incorrect, unhelpful, or incomplete?
This part is incomplete:
<li>Enable <strong>Remote Debugging via USB</strong> in the Advanced Settings in Firefox on the Android device.</li>

#### Specific section or headline?
On my Samsung Galaxy Tab SM-T280 running Android 5.1.1, current Firefox (including Nightly) doesn't have a “Remote Debugging via USB” item in Advanced Settings, or anywhere else in the Settings menu. This setting only exists in <code>about:config</code> as <code>devtools.debugger.remote-enabled</code>, which defaults to <code>false</code> and <em>seems</em> to need to be set back to <code>true</code> <strong>each time the browser is restarted</strong>.

This user's query (which was never answered) may have been caused by the same documentation issue: https://support.mozilla.org/en-US/questions/1282265

I would suggest editing the official documentation, to append the following to the text I quoted above:

(For certain older Android OS versions, Settings does not include a <strong>Remote Debugging via USB</strong> option. For these older systems, navigate to <code>about:config</code> and set <code>devtools.debugger.remote-enabled</code> to <code>true</code>. <em>This setting will need to be refreshed with each browser restart.</em>)

#### Did you test this? If so, how?
In Firefox Nightly on Android 5.1.1, I went to <code>about:config</code> and set <code>devtools.debugger.remote-enabled</code> to <code>true</code>. I left all other settings alone. Once I made this change on the Android, Firefox for Desktop would let me connect to the Android in <code>about:debugging</code>.

To be absolutely sure this was the correct setting, I set <code>devtools.debugger.remote-enabled</code> back to <code>false</code> on the Android, and Firefox for Desktop instantly lost the connection.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/about_colon_debugging`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/about:debugging
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/about_colon_debugging/index.html
* Last commit: https://github.com/mdn/content/commit/b00ac6cb4e40cbce64dc506c7fad5e85a66bfaea
* Document last modified: 2021-11-05T11:07:32.000Z

</details>

**Comment by sideshowbarker** [comment]
The relevant document has since moved to https://firefox-source-docs.mozilla.org/devtools-user/about_colon_debugging/, so please re-raise this issue at https://bugzilla.mozilla.org/enter_bug.cgi?product=Developer+Infrastructure&component=Firefox+Source+Docs%3A+Content&short_desc=Documentation+issue+on+devtools-user/about_colon_debugging/index&comment=URL+=+https://firefox-source-docs.mozilla.org/devtools-user/about_colon_debugging/index.html&bug_file_loc=https://firefox-source-docs.mozilla.org/devtools-user/about_colon_debugging/index.html

I’m going ahead and closing this issue, since there’s no change we could make to MDN now to resolve it.
