### ISSUE TITLE
Content suggestion: Add year to browser_compatibility

### ISSUE THREAD

**Issue by arunachaleshwaran** [mdn/content#11779]
## What is the new suggestion?
Every documentation page has a Browser Compatibility section. 
In the section, it would be helpful to add the year in which the min compatible version is released.

## Why is it important or useful?
When I see the documentation of a feature i can't able to know whether it will work on most of the browser or not.
So if have the year of the feature released then i can able to guess whether my most of the people can able to utlize the feature or not. without referring more website.
  
when newly some come to the industry. they can't able to know the feature is widely adopted or not. so they won't use it.

How much time do you think this work should take? A few hours? A week? A month?
one  month  will enough

Does it address critical needs in the web industry?
New feature we can use is always better. if that feature is not supported. writing compatibility is very hard.
before using the feature we can able to predict the feature won't be an issue for most people.

## Other supporting information

[web browsers version vs time of release](https://en.wikipedia.org/wiki/Timeline_of_web_browsers)

**Comment by NiedziolkaMichal** [comment]
This is currently implemented. You can check it by hovering mouse over browser version in Browser Compatibility Table.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/11779#issuecomment-1079918861

**Comment by hamishwillee** [comment]
@sideshowbarker This is not the first time that someone has asked about this though. To me this indicates that the compatibility table in the new skin provides a poorer UX than the old one. Or am I missing something (if it isn't just me I'll search for/create a yari bug)

**Comment by sideshowbarker** [comment]
> @sideshowbarker This is not the first time that someone has asked about this though. To me this indicates that the compatibility table in the new skin provides a poorer UX than the old one.

But this issue was raised before the redesign, right? The old design didn’t expose the year at all. The new design does now expose it as a tooltip on hover at least. So that seems like a significant improvement, and it does seem to resolve this issue — unless/until anybody has a specific suggestion for how better to expose the year.

I guess only exposing it on hover isn’t the ideal UX for discoverability —  but it’s hard to see how else it could be made more discoverable without just showing it all the time by default (inline next to the version number).

**Comment by hamishwillee** [comment]
OK. I'll just shut up then :-)
