### ISSUE TITLE
Issue with "Operator precedence": Precedence of Postfix Increment/Decrement vs Function Call

### ISSUE THREAD

**Issue by simonkcleung** [mdn/content#11926]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence

#### What information was incorrect, unhelpful, or incomplete?
Precedence of 'Postfix Increment/Decrement' is lower than 'Function Call'

#### Specific section or headline?
Table

#### What did you expect to see?
Precedence of 'Postfix Increment/Decrement' is higher than 'Function Call'

#### Did you test this? If so, how?
var o ={i:2, m:function(){return this.i}}

o.m()++;
shows "Uncaught ReferenceError: cannot assign to function call"

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/operator_precedence`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/operator_precedence/index.md
* Last commit: https://github.com/mdn/content/commit/680c881dc13b26f561bd9a35678e66c7b95f1e87
* Document last modified: 2021-12-28T17:25:57.000Z

</details>

**Comment by sideshowbarker** [comment]
The error cited in the question has nothing to do with operator precedence. The same error is reported if the (highest-precedence) grouping operator is added to force the evaluation order:

```js
(o.m())++
```

So operator precedence isn’t the problem.

Instead, the actual reason for the error is, `o.m()++` is equivalent to `o.m() = o.m() + 1`. It’s asking for a value to be assigned to `o.m()`. And that doesn’t work, because — as the error message says — nothing can be assigned to a function call.
