### ISSUE TITLE
Issue with "Network Security Services": Brocken Link

### ISSUE THREAD

**Issue by rolandbaer** [mdn/content#12005]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS

#### What information was incorrect, unhelpful, or incomplete?
The links under "NSS is built on top of Netscape Portable Runtime (NSPR)" point to pages that do no more exist.

#### Specific section or headline?
NSS is built on top of Netscape Portable Runtime (NSPR)

#### What did you expect to see?
NSPR project page / documentation

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/projects/nss`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/projects/nss/index.html
* Last commit: https://github.com/mdn/content/commit/7ce080a8d79c3ba23048cb7e28655818d6e49efb
* Document last modified: 2021-08-23T21:16:18.000Z

</details>

**Comment by sideshowbarker** [comment]
Sorry about this but it’s a known issue and there’s no plan to fix it — because all the NSS content is supposed to have been removed from MDN already. See #10904 and #10903 and #8215, and see the archive at https://github.com/mdn/archived-content/tree/main/files/en-us/mozilla/projects/nspr — and https://web.archive.org/ may also have archived copies.
