### ISSUE TITLE
Issue with "<iframe>: The Inline Frame element": (short summary here please)

### ISSUE THREAD

**Issue by Nyco11** [mdn/content#12053]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe

#### What information was incorrect, unhelpful, or incomplete?
The one about deprecated attributes.

#### Specific section or headline?
Here is the link to that section: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe?retiredLocale=it#deprecated_attributes.

#### What did you expect to see?
I expected to see a few lines about the [`seamless`](https://stackoverflow.com/questions/4804604/html5-iframe-seamless-attribute) attribute, which is covered in Jon Duckett's _HTML & CSS: Design and build website_ (2011): "In HTML5, a new attribute called `seamless` can be applied to an iframe where scrollbars are not desired" (p. 190).
I guess that, actually, it cannot even be considered deprecated since it has never become part of HTML5 recommendations.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/iframe`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/iframe/index.md
* Last commit: https://github.com/mdn/content/commit/775662998e66813a612e3ff27e02f2ada867bc17
* Document last modified: 2021-10-03T00:01:51.000Z

</details>

**Comment by sideshowbarker** [comment]
Yeah, the biggest reason we don’t mention anything at all about `seamless` in MDN is that it was never actually even implemented in any browsers. So it was never really usable in practice by web developers.

Anyway, given that we’re intentionally excluding it (that is, it’s not an oversight), I’m going ahead and closing this. But if it turns out there’s any new information that does actually seem to merit adding it, this issue could be revisited.
