### ISSUE TITLE
Issue with "IndexedDB API": Missing Support Table

### ISSUE THREAD

**Issue by mangelozzi** [mdn/content#12314]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API

Firstly the MDN documentation is firstclass, well done to the team!
PS In fact I have set my browser to hide w3schools results, so they pop up first.

#### What information was incorrect, unhelpful, or incomplete?
Wheres the lovelt red/green table showing support? 

#### Specific section or headline?
Missing the support table

#### What did you expect to see?
Support table

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/indexeddb_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/indexeddb_api/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for your kind words, @mangelozzi !

This is a tricky problem. You can read all about it here: https://github.com/mdn/content/discussions/4920 :). I suggest closing this bug, since it's tracked in that discussion. If we ever resolve the general question, we'll fix IndexedDB along with all the other API pages.

I'd encourage you to add your thoughts to that discussion, if you would like to.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/12314#issuecomment-1018792695
