### ISSUE TITLE
Add documentation for record/tuple error messages

### ISSUE THREAD

**Issue by catamorphism** [mdn/content#12391]
https://phabricator.services.mozilla.com/D134822 adds the following new error messages related to records and tuples in JavaScript:

MSG_DEF(JSMSG_BAD_TUPLE_LENGTH,        0, JSEXN_TYPEERR, "attempted to create excessively long tuple")

MSG_DEF(JSMSG_BAD_TUPLE_INDEX,        0, JSEXN_RANGEERR, "index out of range for tuple")

MSG_DEF(JSMSG_BAD_TUPLE_OBJECT, 0, JSEXN_TYPEERR, "value of TupleObject must be a Tuple")

MSG_DEF(JSMSG_EMPTY_TUPLE_REDUCE, 0, JSEXN_TYPEERR, "reduce of empty tuple with no initial values")

MSG_DEF(JSMSG_RECORD_TUPLE_TO_NUMBER,        0, JSEXN_TYPEERR, "can't convert Record or Tuple to number")

MSG_DEF(JSMSG_BAD_RECORD_TUPLE_WEAKMAP_KEY, 0, JSEXN_TYPEERR, "a Record or Tuple WeakMap key must contain a Box")`

These error messages should be documented.

Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1744975

**Comment by hamishwillee** [comment]
Cool, but premature. We have no docs on tuples, so there is nowhere to put this.

This is part of https://bugzilla.mozilla.org/show_bug.cgi?id=1658309 , which is the firefox implementation of https://github.com/tc39/proposal-record-tuple

There is no documentation on any of that because it is only at stage 2. We normally wouldn't start documentation on MDN until there was a really solid proposal and a good implementation that we could work against. That would likely come at stage 3, probably when the development team told us this was going to be live in nightly.

@catamorphism Any idea when that might be? If not, this can wait until one of the above triggers.

**Comment by catamorphism** [comment]
Yes, it's a bit early. Should this bug be closed, or tagged for later work?

**Comment by hamishwillee** [comment]
Hi @catamorphism 
Given the time for this to land is a bit open ended I'm going to close it. 
Appreciate you posting - I'm looking forward to the feature landing.
