### ISSUE TITLE
Issue with "Guidelines to the MDN editor UI": Mention that MDN WYSIWYG editor is no longer available

### ISSUE THREAD

**Issue by ML-Chen** [mdn/content#1240]
MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Editor and pages linked from that page

I was confused why I couldn't find the WYSIWYG edit button anymore on MDN, so I stumbled across this page (through Google) about the MDN Editor. It should mention that the WYSIWYG editor has been removed, according to https://hacks.mozilla.org/2020/12/welcome-yari-mdn-web-docs-has-a-new-platform/. 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mdn/editor`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Editor
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/mdn/editor/index.html
* Report started: 2021-01-13T00:52:50.258Z

</details>

**Comment by sideshowbarker** [comment]
It looks like in 93ccb49 the https://developer.mozilla.org/en-US/docs/MDN/Editor article was actually already deleted, on January 5th.

Certainly the source for it is no longer in the repo: https://github.com/mdn/content/tree/main/files/en-us/mdn.

But given that the source was deleted on January 5th, the https://developer.mozilla.org/en-US/docs/MDN/Editor article should be 404 at this point. Alerting @mdn/core-yari-content for insight on whether some necessary step got missed.

**Comment by chrisdavidmills** [comment]
Yup, I removed this, so it should definitely not still be showing up. Pinging @peterbe , so he can check if there is anything holding up these changes getting put into production.

**Comment by peterbe** [comment]
Unfortunately, it's "bug" in Yari. https://github.com/mdn/yari/issues/2224
Not really a bug because it simply was never implemented. Seems here is the first time we get bitten by it. The good news is that the URL isn't linked to from anywhere. It's not in the Sitemap XML files. And ideally there shouldn't be any links to it with the ("surviving") pages.

There's a quick-n-dirty fix for now. We can create a redirect in the `files/en-us/_redirects.txt` that links the URI to something else. Then, instead of the 404 it should be, it comes a 301.

**Comment by sideshowbarker** [comment]
Fixed by https://github.com/peterbe/yari/commit/ab30d964e1fcc34811ddda270d821006e86704fb
