### ISSUE TITLE
Issue with "Introduction to the DOM": example doesn’t work

### ISSUE THREAD

**Issue by m-lambo** [mdn/content#12415]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Introduction

#### What information was incorrect, unhelpful, or incomplete?
I wouldn't say any of the information was incorrect or unhelpful and I could be wrong but I think there's a bug in the code example.

#### Specific section or headline?
Example + Result using the Document API

#### What did you expect to see?
The colors of the associated elements to always change according to the selection.

#### Did you test this? If so, how?
It does this most of the time but noticed there's a few cases when it doesn't and the issue is tied to the chosen selection of a different element. I figured this wasn't intentional but I could be wrong. Checking some of the permutations helped me find the bug. I changed the link selection to green then after no change I kept the text color as black but changed the background color back and forth. The color for the link never changed so I don't think the background color is the culprit. Next I changed the color of the text to red and noticed the link's color changed. So I changed the background color one more time to see if the link remained green and it did. Then I changed the text color back to black and the link became blue again despite not changing its selection.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/document_object_model/introduction`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Introduction
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/document_object_model/introduction/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by Rajasimhan** [comment]
**notes:** issue reproducible in chrome while it works as expected in firefox.

**Comment by ibrahim-301** [comment]
This issue can also be reproduced both in Chrome and Edge by making a page with just an `<a>` element and then trying to set the `link` attribute in console through `document.body.link = 'red'` or `document.body.setAttribute('link', 'red')`. And for some reason, it works when you have the `<a>` highlighted or clicked on at least once inside the devTools elements inspector.

The example could instead demonstrate how `element.setAttribute()` is used on any element other than `<body>` since the docs already [mention here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/body#attributes) that those attributes are "non-conforming". The [HTML checker](https://validator.w3.org/nu/#textarea) also shows errors when setting those attributes on `body`.

![obs](https://user-images.githubusercontent.com/75935539/151143045-16201a1f-8464-4c44-a421-4de8068ec223.png)

**Comment by hamishwillee** [comment]
Then there is no bug in the code "as such". 

From an MDN perspective this example is broken in that:
1. It uses deprecated elements.
2. You would change the colours using HTML attributes like this unless you had absolutely no choice - CSS is used for styling now. Changing to another element would not fix this problem.
3. Use of inline event handlers is deprecated (use `addEventListener`,)

A simple fix might be as simple as having a button and a log textarea, and adding text to the log when the button is pressed.

If you wanted something like what is there now, you could use [classList](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList) to add classes to the body (or your own element), and then use the CSS class to change appearance.

Someone interested in doing either of these?
