### ISSUE TITLE
[WebAPI] ftp protocols added to registerProtocolHandler

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#12581]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [ ] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

Add protocols to `registerProtocolHandler()`

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1705202

**Comment by hamishwillee** [comment]
Status
- [ ] BCD - will require addition of versioning for a supports ftp schemes subfeature. 
- [ ] Docs
  - [ ] Initial tidy up: #12790
  - [ ] Add ftp, sftp, ftps to docs - only happens if these are "in" spec. 
- [ ] Release note - TBD
- [ ] dev-doc-complete - TBD

This is on hold "for now" because .... 

Currently the addition of these protocols is non-spec, pending https://github.com/whatwg/html/pull/6584#issuecomment-1031042596 . The docs and BCD will depend on whether or not this is in spec at release, and whether the release depends on it being "on spec" (see query https://bugzilla.mozilla.org/show_bug.cgi?id=1705202#c10 ).
