### ISSUE TITLE
Issue with "Intl.DisplayNames() constructor": fallback not actually working

### ISSUE THREAD

**Issue by badunius** [mdn/content#12585]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames/DisplayNames

#### What information was incorrect, unhelpful, or incomplete?

Constructor's option `fallback`

#### Specific section or headline?

`fallback` option is irrelevant, since `DisplayNames` will not even try to fallback, throwing an error instead

#### What did you expect to see?

I expected to see a warning that providing an invalid language code will throw an error

#### Did you test this? If so, how?

```js
{
  const displayNames = new Intl.DisplayNames(['en'], {type: 'language'})
  console.log(displayNames.of('asd-QWE')) // Error: Uncaught RangeError: invalid value "asd-QWE" for option language
}
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/intl/displaynames/displaynames`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames/DisplayNames
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/intl/displaynames/displaynames/index.md
* Last commit: https://github.com/mdn/content/commit/4a901874a4a5b68af1e2b8f39b53d16aabca8311
* Document last modified: 2022-01-24T11:10:03.000Z

</details>

**Comment by Josh-Cena** [comment]
<img width="506" alt="image" src="https://user-images.githubusercontent.com/55398995/169657484-f6e548aa-6e59-42d4-9470-8b3be8e02943.png">

Interesting because Safari and Firefox both throw errors, but Chrome doesn't...

Also, it's still relevant, for "structurally valid" language:

<img width="506" alt="image" src="https://user-images.githubusercontent.com/55398995/169658012-228966e3-ab11-4cb9-a9b5-b5d5f91fa36c.png">

(Firefox)

<img width="506" alt="image" src="https://user-images.githubusercontent.com/55398995/169658016-4e51e6af-6c54-4b44-8121-641cd17462dc.png">

(Safari)

Relevant spec, in case someone wants to bite the bullet and see if which implementation violates the spec: https://tc39.es/ecma402/#sec-canonicalcodefordisplaynames

**Comment by badunius** [comment]
@Josh-Cena It's like walking the minefield
Firefox:
asd -> snz (apparently a valid language code)
geo -> Georgian
qwe -> qwe (fallback?)
qw-DS -> qw-DS (fallback)
none -> RangeError
unknown -> unknown

**Comment by Josh-Cena** [comment]
Lol, yeah 😄 I, like most averagely-intelligent people, find the spec unreadable, so I can't fully appreciate what's going on, but https://unicode.org/reports/tr35/#Unicode_locale_identifier seems to define what "structurally valid" means...
