### ISSUE TITLE
Content bug: Undocumented behavior when using Array.prototype.find() on an array of objects

### ISSUE THREAD

**Issue by Duplicated** [mdn/content#12643]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find

## Specific page section or heading?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find#return_value

## What is the problem?

The text here reads: The **value** of the **first element** in the array that satisfies the provided testing function. Otherwise, `undefined` is returned.

This is correct in the sense that it would return a copy of the value in the array that matches the provided testing function, _if said value is one of the primitive types_. However, for an array of objects, _the returned value is actually a memory reference to the object in the original array_, and not just a shallow copy of the original object.

## What did you expect to see?

The text for section `return_value` should denote as such for the case where one deals with an array of object. Also, for [this example](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find#find_an_object_in_an_array_by_one_of_its_properties), there should be another example to show how mutating the result from `Array.prototype.find()` actually mutates the object in the original array as well.

## Did you test this? If so, how?

I tested this on the internal console of Google Chrome Version 97.0.4692.99, which runs on Ubuntu 18.04.6

![Screenshot_20220203_004813](https://user-images.githubusercontent.com/3392880/152209036-7bd1a787-16d4-49e6-9439-df0e0d41dcc7.png)

If I were to consume this object functionally, I would need to create a copy of this first before updating any value:
```js
const newCopy = { ...foundBananas };
newCopy.quantity = 30;
```
`newCopy` will then refers to a new object, with a different memory reference, that I am free to modify.

**Comment by hamishwillee** [comment]
Thanks @Duplicated 

@sideshowbarker My concern here is that (in English) returning the "value" of something implies that you're returning something separate than the thing itself the something itself. In other words it is reasonable that someone might interpret this to mean "return a copy", at which point we should clarify deep or shallow copy?

Do you think it would be better to simply say:

> `find()` returns the first element in the array that satisfies the provided testing function.

IMO most javascript users will read that as returning a (unique) value for a primitive and a reference for an object. 
I don't "think" we need to worry about the fact someone might think we mean "index of the first element.

Alternatively we might spell this out:

> `find()` returns the **value* of the first element in the array that satisfies the provided testing function. If an object is returned, this is effectively a shallow copy of the element in the array.

Otherwise, is there a better way of referring to "value"?

**Comment by sideshowbarker** [comment]
> Do you think it would be better to simply say:
> 
> > `find()` returns the first element in the array that satisfies the provided testing function.

Yes, it seems to me it’d be better to just say that. I can’t see any good reason to mention “value”.
