### ISSUE TITLE
Issue with "Window.scrollTo()": “behavior” param: “instant” vs “auto”

### ISSUE THREAD

**Issue by joe-azps** [mdn/content#12666]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollTo

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/window/scrollto`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollTo
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/scrollto/index.md
* Last commit: https://github.com/mdn/content/commit/aa5314cfa0d52b26a806d46cac5937113c6e18f8
* Document last modified: 2022-01-18T02:37:48.000Z

</details>

The description of Behavior is as follows:

Specifies whether the scrolling should animate smoothly (smooth), or happen instantly in a single jump (auto, the default value).

Its missing the value for instantly which is 'instant'

Ideally it should read as the following page:

MDM URL:https://developer.mozilla.org/en-US/docs/Web/API/Window/scroll

Specifies whether the scrolling should animate smoothly (smooth), happen instantly in a single jump (instant), or let the browser choose (auto, default).

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #12668 with a fix.

But note that the fix is to change the https://developer.mozilla.org/en-US/docs/Web/API/Window/scroll article. Per-spec, the https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollTo is actually correct.

That’s because:

Per https://drafts.csswg.org/cssom-view/#changes-from-2013-12-17:

> The `instant` value of scroll-behavior was renamed to `auto`.

Per https://drafts.csswg.org/css-overflow/#propdef-scroll-behavior:

> Value: `auto` | `smooth`

UA requirements: https://drafts.csswg.org/cssom-view/#scrolling

**Comment by wbamberg** [comment]
See also https://github.com/mdn/content/pull/12101 I guess?
