### ISSUE TITLE
Issue with "Django Tutorial Part 11: Deploying Django to produ…": (short summary here please)password/token issues git repository.

### ISSUE THREAD

**Issue by ucantbethatgit** [mdn/content#12778]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Deployment

#### What information was incorrect, unhelpful, or incomplete?
_Django Tutorial Part 11: Deploying Django to production_

#### Specific section or headline?
_[_Creating an application repository in Github_]_
 6.         git push origin main
#### What did you expect to see?
 files being pushed to the git repository
However instead of a password a token has to be entered. However the generated token does not complete the task!

Specifically the mozilla tutorial has to be revised.

#### Did you test this? If so, how?
macbook pro  -- terminal  

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/django/deployment`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Deployment
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/django/deployment/index.md
* Last commit: https://github.com/mdn/content/commit/601a273d856ee11aa32dd9ac42d1e84f441c8b58
* Document last modified: 2022-02-03T11:27:16.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks for posting.

The tutorial does not suggest how you enter credentials because this depends on how you have set up _your_ github account. If the user has never used github before then this defaults to the username and password; the user will be prompted so I did not feel the need to add information about this. If they have set up to use application tokens or SSH instead then I expect them already to know how to use github.

Personally I use a token on some computers and my login on others. If your token is not working then I think you have a problem with github. 

Upshot, I am closing because I don't think this is something that should be fixed in the documentation.

**Comment by ucantbethatgit** [comment]
hello:

Thanks for the timely response. Much appreciated.

very truly
P.S.  Mozilla tutorials are a beauty. Instructions are so good websites can be deployed effortlessly. Kudos to the tutorials.
