### ISSUE TITLE
Issue with "Operator precedence": ternary operator precedence is likely 2

### ISSUE THREAD

**Issue by dy** [mdn/content#12916]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence

#### What information was incorrect, unhelpful, or incomplete?

Ternary operator has precedence 3, but in reality that is rather 2.
(As discussed in [pipeline proposal](https://github.com/tc39/proposal-pipeline-operator/issues/262#issuecomment-1036374279)).

```js
let a, b, c
c = 1 ? a : b = 3
c // undefined

// if ?: had higher precedence than assignment, it'd evaluate as
c = (1 ? a : b) = 3  // invalid syntax
// but it evaluates as
c = 1 ? a : (b = 3)
```

Spec also defines it of the same precedence as assignment: https://tc39.es/ecma262/#sec-assignment-operators

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/operator_precedence`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/operator_precedence/index.md
* Last commit: https://github.com/mdn/content/commit/680c881dc13b26f561bd9a35678e66c7b95f1e87
* Document last modified: 2021-12-28T17:25:57.000Z

</details>

**Comment by js-choi** [comment]
Cross-posting from https://github.com/tc39/proposal-pipeline-operator/issues/262#issuecomment-1036411528:

The weirdness here is that `=` is not really a binary operator in the usual sense. It is a weird operator: it is kind of like a prefix operator that operates on its RHS. Its LHS is not an ordinary expression but rather more like a parameter list.

To the extent that ternary operators can even be considered to have precedence, it binds less tightly than `yield` and `=` because `yield a ? b : c` is `yield (a ? b : c)` and `x = a ? b : c` is `x = (a ? b : c)`. (Examples from @bakkot.)

**Comment by dy** [comment]
Addition. Partially precedence is applicable to `=` operator in combination with `()`, `.`, `[]`, `,` from the list:

```js
a = 1
a.b = 1
((a.b)) = 1
a['b'] = 1
a['c', 'b'] = 1
a?.b = 1 // breaks
(a,b) = 1 // breaks
```
Sort-of LHS in `=` should not include anything calculable.

**Comment by js-choi** [comment]
The whole concept of “precedence” breaks down at the level of `? :`, `=`, `=>`, and `yield`. For example, the following pairs of lines are equivalent:

```js
1 ? x = 2 : 3
1 ? (x = 2) : 3

a = b ? c : d
a = (b ? c : d)
```

In the first pair of lines, `? :` acts “looser” than `=`. But in the second pair of lines, `? :` acts “tighter” than `=`.

So I think it would be a good idea to merge these all together into one “precedence” level, and say, “These don’t really have more or less ’precedence’ than one another; they have special rules; see the following examples.”
