### ISSUE TITLE
Issue with "Navigator.doNotTrack": What was this deprecated tech replaced with?

### ISSUE THREAD

**Issue by andypillip** [mdn/content#12912]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/doNotTrack

#### What information was incorrect, unhelpful, or incomplete?

The deprecation-note is quite unhelpful, since it does not state what it was replaced with.

#### Specific section or headline?

The deprecation note.

#### What did you expect to see?

Some explanation of what the DnT setting was replaced with.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/navigator/donottrack`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/doNotTrack
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/navigator/donottrack/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by himanshugarg** [comment]
Thanks for reporting. Without really addressing the issue reported, these are the Request Headers on FF 91:-

Do Not Track OFF  | [Do Not Track ON](https://support.mozilla.org/en-US/kb/how-do-i-turn-do-not-track-feature#firefox:linux:fx91)
--- | ---
![image](https://user-images.githubusercontent.com/2392803/153690596-8e5d6db4-9a71-4531-8081-cc37db29a14a.png) | ![image](https://user-images.githubusercontent.com/2392803/153690712-c631d68b-0179-4036-8885-9fec22667a50.png)

**Comment by teoli2003** [comment]
Unfortunately, nothing has replaced DNT. DNT has never worked because it was not a browser feature it was a browser feature AND a website developer one, more precisely a cooperative feature where _advertisement_ companies had to abide too.

They never did and decided not to.

The feature is therefore useless. Moreover, it is harmful as it increases the entropy of the headers (read the likelihood of sending unique headers that can be used to track you).

Browser makers abandoned the project and decided to fight tracking by other means, like fine an alternative to cookies (Chrome if I remember well), or limitation to non-first-party cookies (like Safari and Firefox if I remember well). None of these alternatives became universally recognized until now. Maybe in the future.

Hope this helps. Maybe we should add some text explaining this, but this would need some research to find sources for what I just summarized (that are my remembering of the situation), or we can just leave it as is until an alternative is agreed upon.

What do you think?

**Comment by hamishwillee** [comment]
@teoli2003 IMO it is worth confirming your memory and adding the additional information that this is pointless to implement. Otherwise developers may choose to implement this even if deprecated, on the assumption that it is reasonable to use now given fairly broad browser support.

**Comment by Pomax** [comment]
A counter to "the feature is therefore useless": I don't care about huge advertisers or megacorp websites. They're going to abuse the web as much as money lets them. I _do_ care about making sure _my websites_ respect DNT and don't load things like google analytics when the client says not to do so.

Just because the giants refuse to abide doesn't mean it wasn't, and still is, a good idea that good people can use to do the right thing.
