### ISSUE TITLE
Issue with "Intl.Locale.prototype.calendar": incorrect short description of the 'roc' Calendar

### ISSUE THREAD

**Issue by MohsenAlyafei** [mdn/content#12953]
The short description of the `roc` calendar is currently stated incorrectly on the page as:

`roc`
`Civil (algorithmic) Arabic calendar`

This should be corrected to:

`roc`
`Republic of China calendar`

**Comment by teoli2003** [comment]
@romulocintra Can you help us here?

`roc` is likely the Republic of China calendar (and the error would be in both [`Intl.Locale.prototype.calendar`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/calendar) and [`Intl.Locale.prototype.calendars`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/calendars), but I wasn't able to locate the canonical source for this list (and its support in Chrome). Can you help me here, so that we can maintain this in the future?

**Comment by MohsenAlyafei** [comment]
I confirm that `roc` is the Republic of China calendar.
some information here:

https://unicode-org.github.io/icu-docs/apidoc/dev/icu4j/com/ibm/icu/util/TaiwanCalendar.html
and here:
https://en.wikipedia.org/wiki/Republic_of_China_calendar

It is a typo on the page: It cannot be the Civil Arabic Calendar written under it with exact duplicated text.

**Comment by romulocintra** [comment]
> Intl.Locale.prototype.calendars

Hi @teoli2003 definitely a typo/mistake the full list of calendars[ it's here](https://github.com/unicode-org/cldr/blob/62c90a357dc25911db60fcdf7d5a80119df27963/common/main/en.xml#L1304) and the value should be something in between The Republic of China calendar or Minguo calendar, wondering where this information it's replicated. Would be really nice to have kind of a macro or centralized table to be shared across pages that need those references.

**Comment by sideshowbarker** [comment]
> Hi @teoli2003 definitely a typo/mistake the full list of calendars[ it's here](https://github.com/unicode-org/cldr/blob/62c90a357dc25911db60fcdf7d5a80119df27963/common/main/en.xml#L1304) and the value should be something in between The Republic of China calendar or Minguo calendar, wondering where this information it's replicated. Would be really nice to have kind of a macro or centralized table to be shared across pages that need those references.

Based on that, wouldn’t it be that the right (= most-precise) change to the article source would be:

```diff
 - `roc`
-  - : Civil (algorithmic) Arabic calendar
+  - : Minguo Calendar
```

**Comment by teoli2003** [comment]
I think so, or _Minguo Calendar (Republic of China)_.

**Comment by teoli2003** [comment]
Sorry, it slipped out of my radar. I just opened a PR to fix this.
