### ISSUE TITLE
Issue with "Object": Misleading wording in intro text

### ISSUE THREAD

**Issue by Jumace** [mdn/content#13020]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object

#### What information was incorrect, unhelpful, or incomplete?
In the intro it says "The Object class represents one of..."
To use Object and class here in that sentence can be misleading for devs, especially since ES6.
Something like 'type' or 'data-type' seems more fitting.

#### Specific section or headline?
Intro text

#### What did you expect to see?
"The Object type represents one of..."

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/object`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/object/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by Josh-Cena** [comment]
I don't think it's all that confusing, since `Object` is a class in every way.

- It can be constructed with `new Object()`.
- It can be subclassed with `class Something extends Object` (and in fact all classes implicitly extend `Object`).
- `something instanceof Object` is a legal and non-vacuous statement, because `Object.create(null)` produces a non-`Object`... object.
- `Object.prototype` has some methods inherited by all objects.
- `Object.keys`, etc. can be seen as static methods of the `Object` class.

It's just that ECMAScript has a special syntax for making POJOs without explicitly calling the `Object` constructor. In what way is it _not_ a class?

**Comment by Jumace** [comment]
First of all thanks for taking the time to answer.

To bei fair my description of what I see as the issue was not the best.
Factual the statement is totally right, I just had more than one person which just started to get into web development getting confused by it.

For new people getting into JavaScript and for that into writing software, there are a lot of new terms to learn and putting too many of those terms into the first sentence of the description of probably the most important data type in JavaScript can make the article harder to understand then necessary.

I agree "'Object' object" is probably even worse. With this ticket I wanted to spark a conversation if it is possible to formulate the introduction of this article in a way that makes it easier to digest for new people to the language.

That is way I suggested "'Object' type" as a still valid and more understandable alternative.

Happy to hear your thoughts.

**Comment by Josh-Cena** [comment]
I don't know if the goal of the "references" section is to care for new learners—if you aren't familiar with classes, you may be better off starting with the JavaScript guide. The References section is organized by syntax and does not assume any order of reading.

That said, I do agree "Object type" doesn't sound _wrong_, and probably less loaded for new learners.

**Comment by Jumace** [comment]
> "I don't know if the goal of the "references" section is to care for new learners"
That is a fair point but I also think it is fair to assume that we don't know the level of knowledge of the people reading the article.
If there is a chance to make it easier to understand without compromising the information gained from the article I think it is worth to give it a shot.

**Comment by sideshowbarker** [comment]
@Josh-Cena Given the discussion here, it’s not clear to me whether there are any changes needed to resolve this. So I’ve gone ahead and unassigned myself from it.

If in fact nothing further is needed here, please feel free to close it. Or otherwise, I guess minimally we should probably update the issue title to more precisely state what change might be needed.

**Comment by Josh-Cena** [comment]
I think the resolution is to change "class" to "type"? I don't have objection to making that change.

**Comment by sideshowbarker** [comment]
> I think the resolution is to change "class" to "type"? I don't have objection to making that change.

OK, thanks — opened #18349 with that change
