### ISSUE TITLE
Issue with "Function.prototype.call()": (using .call() without parameter no longer bound to global object)

### ISSUE THREAD

**Issue by AndyPham1394** [mdn/content#13199]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/call

#### What information was incorrect, unhelpful, or incomplete?
var sData = 'Wisen';

function display() {
  console.log('sData value is %s ', this.sData);
}

display.call();  // sData value is Wisen 

#### Specific section or headline?
Using call to invoke a function and without specifying the first argument

#### What did you expect to see?
As mention above, display.call() should return 'sData value is Wisen' but the result is 'sData value is undefined' instead 

#### Did you test this? If so, how?
I pasted example code to Javascript Demo runtime and received: 'sData value is undefined'
but when run example-code on console, I received :   'sData value is Wisen'

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/function/call`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/call
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/function/call/index.md
* Last commit: https://github.com/mdn/content/commit/303a6c3b8ec6658d2956c191c50aee0a0e9e4da5
* Document last modified: 2022-02-18T09:30:25.000Z

</details>

**Comment by sideshowbarker** [comment]
The difference is due to the fact that if you run something in the console, it doesn’t run with `'use strict'` by default.

But if you do the following in the console:

```js
'use strict';
var sData = 'Wisen';
function display() {
  console.log('sData value is %s ', this.sData);
}
display.call();
```
…then it’ll throw with an error message logged to the console like the following:

> TypeError: can't access property "sData", this is undefined

The difference with `'use strict'` is explained already in the existing article, so I’m going ahead and closing this. But if I’ve misunderstood what problem you’re describing, then this issue could be revisited.
