### ISSUE TITLE
Various "Firefox internals" sidebar links are 404 “Page not found”; developer.mozilla.org/en-US/docs/Mozilla/Gecko etc

### ISSUE THREAD

**Issue by dipikabh** [mdn/content#13228]
#### What information was incorrect, unhelpful, or incomplete?

Starting from https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases, I clicked on various links under "Firefox internals" menu on the left TOC.

1. "Page not found" error for most of the links under "Firefox internals" menu on the left TOC. Also no way to report the problem for those pages because no "Found a problem with this page?" section at the bottom.

For example, these pages (and more) were not found:
- https://developer.mozilla.org/en-US/docs/Mozilla/Gecko
- https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Headless_mode
- https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules

2. "Firefox internals" > "Mozilla project" link works but on https://developer.mozilla.org/en-US/docs/Mozilla page, the TOC on the left suddenly disappears. Is that intentional?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/index.html
* Last commit: https://github.com/mdn/content/commit/cbe151a06d6e5b4d1fbb46081bd16e69ef4c1630
* Document last modified: 2020-09-15T15:48:51.000Z

</details>

**Comment by dipikabh** [comment]
Also, there are two mentions of `Mozilla Project`/`Mozilla Projects` under `Firefox internals`. The second link does not work.
![Screenshot 2022-03-04 at 12 27 29 PM](https://user-images.githubusercontent.com/23019147/156755681-9ef215f9-90cb-4891-970b-aab4634bbfb4.png)

**Comment by caugner** [comment]
Related issue: https://github.com/mdn/yari/issues/5484

If I understand it correctly, this is a side-effect of moving the Mozilla documentation off MDN, see: https://github.com/mdn/content/issues/10928#issuecomment-985085551

**Comment by caugner** [comment]
I believe @Rumyra was referring to this issue: https://github.com/mdn/yari/issues/5096

**Comment by dipikabh** [comment]
> I believe @Rumyra was referring to this issue: [mdn/yari#5096](https://github.com/mdn/yari/issues/5096)

Yes, thanks @caugner. My issue here in mdn/content is precisely the same that @Rumyra raised (thats in mdn/yari)!! I can mark this one duplicate and close.

**Comment by dipikabh** [comment]
Duplicate of #5096

**Comment by ernstki** [comment]
Hi! Those links are still broken, and I'm confused about the relationship between this and #5096, which doesn't seem pertinent at first glance.

I'm trying to find information on headless mode, based on [old Mozilla Hacks articles](https://hacks.mozilla.org/2017/12/using-headless-mode-in-firefox/), blog posts, [Mozilla Wiki articles](https://wiki.mozilla.org/Firefox/CommandLineOptions#-headless), and [Stack Overflow answers](https://stackoverflow.com/questions/46753393/how-to-make-firefox-headless-programmatically-in-selenium-with-python#comment86883839_46753393). Many or most of them link to <https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Headless_mode>.

Understood that there's [some justification](https://discourse.mozilla.org/t/issues-with-firefox-headless/38553/2) for no longer maintaining this particular reference as part of MDN, but it seems like an important thing to mention in a repository of web development documentation, even if it's just a link to some other document. After all, [links don't break, people break links](https://www.w3.org/Provider/Style/URI.html).

I'm going to open a discussion because I don't really know where to start with this, but if I were to find (or create) a resource to replace the old page, would someone be able to create a redirect?
