### ISSUE TITLE
Issue with "What’s in the head? Metadata in HTML": …

### ISSUE THREAD

**Issue by mohannad8** [mdn/content#1336]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML

#### What information was incorrect, unhelpful, or incomplete?
In Active Learning : applying CSS & JS to a page , the js <script></script> element should have been written inside the <body></body> of meta-example.html page   instead of <head></head>.

There for, the script content did not load to the meta-example.html page when opened with the browser. 

#### Specific section or headline?
The <script> element should also go into the head, and should include a src attribute containing the path to the JavaScript you want to load, and defer, which basically instructs the browser to load the JavaScript at the same time as the page's HTML. This is useful as it makes sure that the HTML is all loaded before the JavaScript runs, so that you don't get errors resulting from JavaScript trying to access an HTML element that doesn't exist on the page yet. There are actually a number of ways to handle loading JavaScript on your page, but this is the most foolproof one to use for modern browsers (for others, read Script loading strategies). 

#### What did you expect to see?
i expected to see  a dialog box to  pop up asking me to enter some text for a new list item.

#### Did you test this? If so, how?
yes, i wrote  <script src="script/my-js-file.js"></script>  inside the <body>  of html   instead of <head> which resulted in HTML page loading correctly showing the dialog box.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html/the_head_metadata_in_html`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/html/introduction_to_html/the_head_metadata_in_html/index.html
* Report started: 2021-01-14T23:14:07.800Z

</details>

**Comment by chrisdavidmills** [comment]
@mohannad8 I'm a bit confused here, as some of the HTML elements you included in the comments have been rendered out, so I'm not sure what your first sentence is supposed to say (you can avoid this by wrapping your HTML elements in backticks (`)).

The exact instructions given in the article are "The `<script>` element should also go into the head, and should include a `src` attribute containing the path to the JavaScript you want to load, and `defer`, which basically instructs the browser to load the JavaScript at the same time as the page's HTML."

Did you include the `defer` attribute? If you don't, then the script executes immediately, and fails because the HTML it is manipulating hasn't loaded yet.

**Comment by sideshowbarker** [comment]
Closing for lack of response
