### ISSUE TITLE
When I plugin the same type of physical device, the groupId is wrong.

### ISSUE THREAD

**Issue by BusHeroVER** [mdn/content#13402]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaDeviceInfo/groupId

Chrome version: 98.0.4758.102
Windows 10 Pro version: 20H2 19042.631

![image](https://user-images.githubusercontent.com/41776140/156286252-c731ba5d-67f7-46fe-ae17-cefa4b06845e.png)
![image](https://user-images.githubusercontent.com/41776140/156286266-86b6cec2-b18d-4fd3-9527-cbb2968067c4.png)

When I plug in second device (HD Webcam C525), the groupId is changed.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/mediadeviceinfo/groupid`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaDeviceInfo/groupId
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/mediadeviceinfo/groupid/index.md
* Last commit: https://github.com/mdn/content/commit/89c8199b06e7fb2b76da4087cb9eedef065b2506
* Document last modified: 2022-02-18T09:24:31.000Z

</details>

**Comment by sideshowbarker** [comment]
This seems like something that should either be reported at in the Chrome issue tracker at https://bugs.chromium.org/p/chromium/issues/entry, or else maybe as a question a site like Stack Overflow.

Since the scope of this issue tracker is the content of the MDN site, and this issue doesn’t seem to be describing a problem with any content in the MDN site, I’m going ahead and closing this. But the issue can be revisited if further information is provided.
