### ISSUE TITLE
Ask a question：i want to use setTimeOut in setInterval, but is not my excepted

### ISSUE THREAD

**Issue by chenhongliu** [mdn/content#13411]
setInterval(function() {
  setTimeout(function() {
    console.log(1)
  }, 2000)
}, 1000)

like this, i would like to console after  two sconds in this timer， but it console in a scond, how can i solve this question

**Comment by sideshowbarker** [comment]
This seems like a question that’s better suited for a site such as Stack Overflow.

The scope of this issue tracker is limited to problems with the content of MDN articles. Since this issue doesn’t seem to be pointing out any specific problem in a particular MDN article, I’m going ahead and closing it.
