### ISSUE TITLE
Issue with "Online and offline events": Broken nav, missing compatibility, orphaned

### ISSUE THREAD

**Issue by lobsterkatie** [mdn/content#13505]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/Online_and_offline_events

#### What information was incorrect, unhelpful, or incomplete?

- No LH sidebar
- No link to this page from parent page
- No browser compatibility table
- Clicking on "Overview" in RH TOC nav has no result (scroll position doesn't change)

#### Specific section or headline?

n/a

#### What did you expect to see?

All of the above problems not to be there.

#### Did you test this? If so, how?

Other RH TOC links work. "Overview" doesn't because there's no section with that `id` to scroll to. As for the rest, it's consistent with or without and ad blocker, and in an incognito window. I also tested it in Safari (I was originally looking at it in Chrome), and everything is the same.

No error messages show up in the console, so presumably not a broken react component or something like that. (Besides, looking at the actual source on GH, I don't see it included anywhere.) I did note that the the GH source has a `NeedsUpdate` tag, so maybe that's why things are wonky?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/navigator/online_and_offline_events`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/Online_and_offline_events
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/navigator/online_and_offline_events/index.md
* Last commit: https://github.com/mdn/content/commit/b7aafea1ab7cfee11a7e854a4b5c83a6e6d329d4
* Document last modified: 2022-02-02T09:11:35.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing!

This page doesn't have a sidebar because it's missing the macro call that adds the sidebar, that's just a content problem.

It should not have a browser compat table, because that's only for pages that document specific web platform features. For example, the pages for the [`offline` event](https://developer.mozilla.org/en-US/docs/Web/API/Window/offline_event), [`online` event](https://developer.mozilla.org/en-US/docs/Web/API/Window/online_event), and [`onLine` property](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/onLine) have them, because they document concrete bits of the web platform. But this page is a kind of guide page about offline in general.

> Clicking on "Overview" in RH TOC nav has no result (scroll position doesn't change)

That's weird. The source has an ["Overview" H2](https://github.com/mdn/content/blob/d3953594fd4328553ed3e27dbb73c0c71671b08c/files/en-us/web/api/navigator/online_and_offline_events/index.md?plain=1#L15), which is showing up in the ToC, but the H2 doesn't seem to be making it into the rendered page. I would very much like to know what's happening here!

All that said, this is a really out of date page. It talks a lot about ancient versions of Firefox, has an example that doesn't work in Chrome, is full of broken links and talks about things like XHR when we'd rather talk about Fetch these days.

So I think there are a couple of options:
* update this page for 2022 move it from under https://developer.mozilla.org/en-US/docs/Web/API/Navigator/, to somewhere it fits better as a guide page about offline. Maybe https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps ?
* if the page isn't adding value, delete the page and make the URL redirect to https://developer.mozilla.org/en-US/docs/Web/API/Navigator/onLine

**Comment by sideshowbarker** [comment]
> * if the page isn't adding value, delete the page and make the URL redirect to [developer.mozilla.org/en-US/docs/Web/API/Navigator/onLine](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/onLine)

Given the serious problems with the content of that article, I think deleting and redirecting it would be best.

**Comment by wbamberg** [comment]
This issue with "Overview" is tracked at https://github.com/mdn/yari/issues/5476 and has an open PR to fix. Thanks for filing this, @lobsterkatie ! I'm surprised noone found this before. For the rest, I filed https://github.com/mdn/content/pull/13511 to delete this old page.
