### ISSUE TITLE
Issue with "Touch events": hyperlink is broken

### ISSUE THREAD

**Issue by OnkarRuikar** [mdn/content#13566]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Touch_events

#### What information was incorrect, unhelpful, or incomplete?
> If your browser supports it, you can [see it live](https://yari-demos.prod.mdn.mozit.cloud/en-US/docs/Web/API/Touch_events/_sample_.Example.html)

the link https://yari-demos.prod.mdn.mozit.cloud/en-US/docs/Web/API/Touch_events/_sample_.Example.html
is broken.

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/API/Touch_events#convenience_functions

#### What did you expect to see?
fix the hyper link

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/touch_events`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Touch_events
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/touch_events/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks for posting!

@sideshowbarker I tried this and it does fail as suggested - attempts to open the example in a new window but this is shown as a broken link. When I added `{{EmbedLiveSample("Example")}}` to the same section the link "works" but open the sample in the current page. The new page does not appear to work properly (i.e. touch events are not being logged) but it isn't a broken link.

The [macro docs](https://developer.mozilla.org/en-US/docs/MDN/Structures/Live_samples#live_sample_macros) don't seem to indicate that both are required on a page. I this perhaps both a yari and an example issue?

**Comment by sideshowbarker** [comment]
> The [macro docs](https://developer.mozilla.org/en-US/docs/MDN/Structures/Live_samples#live_sample_macros) don't seem to indicate that both are required on a page. I this perhaps both a yari and an example issue?

We should update the docs to explicitly state it, but yeah the `LiveSampleLink` macro needs for the `EmbedLiveSample` macro to be in page too.

I don’t know why the `LiveSampleLink` macro was chosen for the demo in this page to begin with — rather than only using the `EmbedLiveSample`  macro — but if there’s some good reason for it, then I guess we could make it work by using something wording lke what I did in https://github.com/mdn/content/pull/12671/files:

```diff
- Open the {{LiveSampleLink('Demo', 'Demo Link')}} in a new browser window and resize it to see the result.
+ {{EmbedLiveSample('Demo')}}
+ 
+ You can also {{LiveSampleLink('Demo', 'view the results of the demo code in a separate page')}}.
```
> The new page does not appear to work properly (i.e. touch events are not being logged) but it isn't a broken link.

So then I guess we should actually try to get the demo working — but maybe we want to get the fix merged for this issue first, and then open a new “help wanted” issue for getting the demo working.

**Comment by hamishwillee** [comment]
Good advice thanks @sideshowbarker #13589 and #13590
