### ISSUE TITLE
Touch live example doesn't work

### ISSUE THREAD

**Issue by hamishwillee** [mdn/content#13590]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Touch_events

This is a follow on to https://github.com/mdn/content/pull/13589 , which is first part of fixing #13566

#### What information was incorrect, unhelpful, or incomplete?

The live example at https://developer.mozilla.org/en-US/docs/Web/API/Touch_events#showing_whats_going_on doesn't work - i.e. if you click the window in the result the touch events are not logged (at least on Chrome/FF recent versions).

Note also that on local testing the link to open the live sample in separate page opens the example in the current window.

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/API/Touch_events#convenience_functions

#### What did you expect to see?

Example works

**Comment by dubeyji10** [comment]
it works well on phone / mobile devices
and enable touch simulation in firefox 
I couldn't see any changes in log in desktop mode.

![touchEvents](https://user-images.githubusercontent.com/45308951/157415933-efc6fa72-6029-4255-bc51-813f1cb32547.png)
![firefox_TouchEvents](https://user-images.githubusercontent.com/45308951/157416498-4185377b-83f2-418a-92f9-d153627acc18.png)

**Comment by hamishwillee** [comment]
Thanks, but touching the window at https://developer.mozilla.org/en-US/docs/Web/API/Touch_events#result does absolutely nothing for me on android - for chrome or firefox. @wbamberg Does it work for you?

**Comment by wbamberg** [comment]
I'm confused about this page. It looks like the argument to both `EmbedLiveSample` and `LiveSampleLink` is `"Demo"` , which doesn't identify a section in the current page.

What happens then is that for`EmbedLiveSample` Yari "falls back" to the (Auto)EmbedLiveSample algorithm (https://github.com/mdn/content/issues/3548#issuecomment-854067354).

That algorithm will select all the code blocks in the same section as the macro call, which in this case is everything under the H3#Convenience functions heading. So half the JS and all the HTML are missing.

If you use "Example" as the argument it's less broken, (you can see the HTML, although the iframe is much too small to fit it).

I haven't tested on mobile, but given the above fix to the `EmbedLiveSample` macro it can be made to work in Firefox Desktop if you:
1. open the page
2. enable touch event simulation using the devtools responsive design mode
3. reload the page

You have to reload the page I think because it adds the event listeners on `DOMContentLoaded`, so the first time the page is loaded, without touch event simulation, that fails.

This problem does not apply with the [jsfiddle version](https://jsfiddle.net/Darbicus/z3Xdx/10/) version, because that's got an "Initialize" button that adds the event listeners, so the steps there are a more intuitive:
1. open the page
2. enable touch event simulation using the devtools responsive design mode
3. click "Initialize"

**Comment by wbamberg** [comment]
What I recommend we do here is:
* fix the argument to `EmbedLiveSample` and fix the size of the iframe so it's big enough for the example
* remove the `LiveSampleLink` macro call and the JSFiddle link
* update the example to have an "Initialize" button, like the JSFiddle version
* update the code to be modern JS style
* add a note about how to enable touch event simulation for desktop browsers

**Comment by wbamberg** [comment]
Oh and the reason (Auto)EmbedLiveSample selects the wrong code blocks is that the heading level for "Result" is semantically wrong - it should be an H3 so it sits under "Example", not an H4.

**Comment by hamishwillee** [comment]
Fixed by #13993, exactly as suggested by @wbamberg . Thanks @wbamberg for the detailed advice.
