### ISSUE TITLE
Issue with "getter": Browser Compatibility Table Not Rendering

### ISSUE THREAD

**Issue by Darker21** [mdn/content#13644]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get

#### What information was incorrect, unhelpful, or incomplete?
The browser compatibility table was encountering a 'TypeError' when trying to render the table. (Log File [developer.mozilla.org-1646738932124.log](https://github.com/mdn/content/files/8205702/developer.mozilla.org-1646738932124.log))

#### Specific section or headline?
Browser Compatability

#### What did you expect to see?
Table detailing which browser supports the _getter_ methods

#### Did you test this? If so, how?
N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/functions/get`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/functions/get/index.md
* Last commit: https://github.com/mdn/content/commit/426485595b1be50e2af91764fbfd94c04c3c36a5
* Document last modified: 2022-02-18T11:38:26.000Z

</details>

**Comment by Darker21** [comment]
The issue is still appearing, I've tried Firefox, Chrome and Edge including clearing my browsing data and disabling browser extensions

**Comment by sideshowbarker** [comment]
I can reproduce this — I’m also seeing the _“Unfortunately, this table has encountered unhandled error and the content cannot be shown”_ error message in https://github.com/mdn/content/issues/13644, rather than the expected table.

I’ve run into this same error today with other pages as well — for example, https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/sidebarAction#browser_compatibility.

 I can’t reproduce it locally; it seems to be a problem only with the production site.

**Comment by schalkneethling** [comment]
@Darker21 and @sideshowbarker, this should be resolved now.

**Comment by Darker21** [comment]
Has been resolved on my end, many thanks
