### ISSUE TITLE
Issue with "browsingData.remove()": browser compatibility should be at end

### ISSUE THREAD

**Issue by OnkarRuikar** [mdn/content#13650]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browsingData/remove

#### What information was incorrect, unhelpful, or incomplete?
Browser compatibility table is not at the end.

#### What did you expect to see?
For sake of consistency browser compatibility table should be at the end.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/browsingdata/remove`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browsingData/remove
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/browsingdata/remove/index.md
* Last commit: https://github.com/mdn/content/commit/934fa5fcedcbd1855c45782424b9ff6e6a04e89a
* Document last modified: 2022-02-18T09:16:12.000Z

</details>

**Comment by suryanva** [comment]
would love to work on this issue,
The task is about shifting browser compatibility to last and the Example extension to just above the Compatibility Section right?

the output would look something like this right?

```
## Examples

Remove download history and browsing history for the last week:

```js
function onRemoved() {
  console.log("removed");
}

function onError(error) {
  console.error(error);
}

function weekInMilliseconds() {
  return 1000 * 60 * 60 * 24 * 7;
}

let oneWeekAgo = (new Date()).getTime() - weekInMilliseconds();

browser.browsingData.remove(
  {since: oneWeekAgo},
  {downloads: true, history: true}).
then(onRemoved, onError);
```

Remove all download and browsing history:

```js
function onRemoved() {
  console.log("removed");
}

function onError(error) {
  console.error(error);
}

browser.browsingData.remove({},
  {downloads: true, history: true}).
then(onRemoved, onError);
```
{{WebExtExamples}}

## Browser compatibility

{{Compat}}

```

**Comment by OnkarRuikar** [comment]
No need to ask. 🙂
Just submit a pull request when you want to fix an issue.

Also, see if the page needs updates as per these guidelines.
https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Code_guidelines/JavaScript#declaring_variables
https://developer.mozilla.org/en-US/docs/MDN/Structures/Page_types/API_method_subpage_template

**Comment by suryanva** [comment]
Good, I will look into this issue.

**Comment by suryanva** [comment]
@sideshowbarker 
Hi, could you review the below PR, I have fixed the issue
https://github.com/mdn/content/pull/16718
