### ISSUE TITLE
Issue with "Grammar and types": tagged template snippet unhelpful

### ISSUE THREAD

**Issue by kerteszgab** [mdn/content#13701]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types

#### What information was incorrect, unhelpful, or incomplete?
I find the code snippet for tagged templates unhelpful.

#### Specific section or headline?
Under String Literals, see the 4 line code snippet beginning with "let myTag ="

#### What did you expect to see?
This particular example does not motivate the use of tagged templates. If you remove the first line and the tag expression from the third line, you get the same result:

```
let [name, age] = ['Mika', 28];
`Participant "${ name }" is ${ age } years old.`;
// Participant "Mika" is 28 years old.
```

Please use an example which explains why and when tagged templates are useful.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/guide/grammar_and_types`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/grammar_and_types/index.md
* Last commit: https://github.com/mdn/content/commit/426485595b1be50e2af91764fbfd94c04c3c36a5
* Document last modified: 2022-02-18T11:38:26.000Z

</details>

**Comment by gullapalli9482** [comment]
Do give a proper explanation of why it needs to be replaced, in case you feel they aren't represented in an understandable format do give a proper example for explanation's sake.

**Comment by hamishwillee** [comment]
@kerteszgab I agree both this intro and the linked item do not really explain why this is "useful" .The benefit seems to be that you can parse a template literal and separate the static and dynamic content. That then allows you to reformat content into whatever you like. I'm not going to attempt to fix this one because I don't full understand the use cases:
- seems to be useful for styled components. https://www.freecodecamp.org/news/a-quick-introduction-to-tagged-template-literals-2a07fd54bc1d/
- [This article](https://patelhemil.medium.com/magic-of-tagged-templates-literals-in-javascript-e0e2379b1ffc). I see that it can be be used for that, but I don't understand why you would want to do it this way.

For whoever takes this on, other problems:
1. The link is broken to the internal anchor (has an extra S
   ![image](https://user-images.githubusercontent.com/5368500/158082734-06401bab-9185-436f-9a2d-7dceb63950de.png)
2. The deconstruction syntax `let [name, age] = ['Mika', 28];` feels a bit "advanced" here to have without at least a link about it.
3. The description here is about passing in a template literal, which you can do. But the function gets this as an array of strings, and that is worth noting.
