### ISSUE TITLE
Issue with "Animating textures in WebGL": doesn't work on iOS

### ISSUE THREAD

**Issue by aatishb** [mdn/content#13775]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Animating_textures_in_WebGL

The demo at the bottom of the page works on desktop but not on mobile (iPhone iOS 14.8, tested on Safari, Chrome, and Firefox)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/webgl_api/tutorial/animating_textures_in_webgl`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Animating_textures_in_WebGL
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/webgl_api/tutorial/animating_textures_in_webgl/index.md
* Last commit: https://github.com/mdn/content/commit/f1fc79652a89d34a311948238580f2459f0e357d
* Document last modified: 2022-01-22T00:33:01.000Z

</details>

**Comment by vlwkaos** [comment]
I can confirm this. I just checked console and the error shows:
<img width="494" alt="image" src="https://user-images.githubusercontent.com/44766242/157891033-24734707-8bb7-45d0-9d9b-81e42d47b002.png">

I searched few relevant posts [here](https://stackoverflow.com/questions/57504122/browser-denying-javascript-play) and [here](https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery/cross_browser_video_player)

My guess is that webkit(iOS) takes permission to control the device hardware rather strictly. Maybe fulfilling the condition(as in first link above, e.g put volume down to 0...) in the demo will ensure it to work.

**Comment by sideshowbarker** [comment]
I tried setting `playsinline` on the `video` element but it didn’t make any difference — still no video is textured over the WebGL cube in the live sample.

**Comment by sideshowbarker** [comment]
https://stackoverflow.com/questions/73236080/texturing-webgl-with-frames-from-video-element-not-working-in-ios-safari is a Stack Overflow question I just now raised in the hope of getting some additional help with this.

**Comment by sideshowbarker** [comment]
After some trial-and-error, I discovered that the following combination causes the demo to work in all browsers:

* omit the `autoplay` attribute
* set the `playsInline` attribute

Specifically:

* On iOS, the demo will not work as expected if the `autoplay` attribute, but will work as expected if the the `playsInline` attribute is specified (as long as the `autoplay` attribute is _not_ specified).
* In all other browsers, the demo works as expected even if the `autoplay` attribute is specified, and still works as expected if the `playsInline` is specified.

In other words, omitting the `autoplay` attribute and setting the `playsInline` attribute makes the demo work as expected on iOS _without_ regressing the expected behavior of the demo in other browsers..

https://stackoverflow.com/a/73244068/441757 has a live version of the demo code that works as expected in all browsers.

I opened https://github.com/mdn/content/pull/19178 to fix the inline code in the “Animating textures in WebGL” article itself; but that’s not live-sample code — the live sample is run from the source in the https://github.com/mdn/dom-examples repo — so I opened https://github.com/mdn/dom-examples/pull/142 to fix the actual source for the demo.

Once that https://github.com/mdn/dom-examples/pull/142 PR is merged, this issue will automatically be marked as resolved, and closed.
