### ISSUE TITLE
Issue with "Array.prototype.every()": it always returns true if the array is empty, no matter what the condition function is

### ISSUE THREAD

**Issue by jienaliu** [mdn/content#13773]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every

#### What information was incorrect, unhelpful, or incomplete?
If the array is empty, every() returns true.

#### What did you expect to see?
I would expect false

#### Did you test this? If so, how?
Yes, 

[].every(t => t>10) // return true
[].every(t => t==10) // return true
[].every(t => t<10) // return true

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/every`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/every/index.md
* Last commit: https://github.com/mdn/content/commit/d1cf821b44eefd824cde6f6b5b71393caddc3271
* Document last modified: 2022-02-24T08:18:07.000Z

</details>

**Comment by vlwkaos** [comment]
The specification indicates otherwise. See [Array.prototype.every](https://tc39.es/ecma262/multipage/indexed-collections.html#sec-array.prototype.every).

 By the design, if there is no element to check the condition, it has to either return true or false. In this case, the specification made chose the former.

The document is correct.

**Comment by wbamberg** [comment]
Closed given https://github.com/mdn/content/issues/13773#issuecomment-1065196367.
