### ISSUE TITLE
dead link on Access-Control-Max-Age page

### ISSUE THREAD

**Issue by enolan** [mdn/content#1381]
The link at "Firefox caps this at 24 hours (86400 seconds)." goes to an error page. Not sure what happened to original target, it's in the wayback machine.

**Comment by chrisdavidmills** [comment]
Thanks for reporting @enolan !

Yes, this is broken because the dxr site has been discontinued. I've fixed it in https://github.com/mdn/content/commit/8284e9146cdde0d735196af4545e1ceb4201f0a4

It is not really a good idea to point directly at the exact line number, as of course the link becomes inaccurate as the code gets updated, but at least they can find and search the correct file.
