### ISSUE TITLE
Mark deprecated/unrecommended differently

### ISSUE THREAD

**Issue by erosman** [mdn/content#14017]
It would improve the readability if deprecated/unrecommended/poor-practice are marked differently..

Example:
https://developer.allizom.org/en-US/docs/Learn/JavaScript/Building_blocks/conditionals

![image](https://user-images.githubusercontent.com/6458876/158758246-23dccb41-f9a8-45cc-b245-97b65dd53f54.png)

Phrasing it differently, would also emphasis the point e.g.

 "While the code is valid, using it is not recommended ....."

**Comment by schalkneethling** [comment]
@Rumyra @dipikabh Please have a look at the recommendation/request here. I believe this is a content decision to be made. I believe the community member feels like the pseudo-code snippet should be styled a bit differently from the rest as it is said to not be a recommended practice.

I believe we still have the ability to mark code snippets as "good" and "bad".

**Comment by hamishwillee** [comment]
Thanks @schalkneethling
Yes, you can markup examples as bad by adding markup as shown (this is documented) in https://developer.mozilla.org/en-US/docs/MDN/Contribute/Markdown_in_MDN#example_code_blocks

![image](https://user-images.githubusercontent.com/5368500/159206455-c5d6b8ed-ffc2-467e-b893-8c59a54d8485.png)

I have done this in https://github.com/mdn/content/pull/14110

BUT, @schalkneethling I think perhaps a new issue for this, because I'm not sure it is obvious that this means "example bad"
![image](https://user-images.githubusercontent.com/5368500/159206612-1d7ab9f7-e373-4cc4-9367-93e3c3b8795c.png)

Thoughts?

**Comment by hamishwillee** [comment]
PS @Rumyra Are you guys updating https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Code_guidelines/General#highlight_good_and_bad_practice_examples as part of the guideline fixes? That mentions the feature, but is still in HTML land.

**Comment by Rumyra** [comment]
Thanks @hamishwillee - yes I think the original issue is fixed here with `example-bad` - the next issue is the styling which isn't clear at all that the code isn't recommended. I'm going to open an issue on yari about it 👍

**Comment by schalkneethling** [comment]
Thank you, @Rumyra
