### ISSUE TITLE
Element: compositionstart, compositionupdate, and compositionend should not be marked as cancelable

### ISSUE THREAD

**Issue by davezoo** [mdn/content#14062]
MDN URL: 
https://developer.mozilla.org/en-US/docs/Web/API/Element/compositionstart_event
https://developer.mozilla.org/en-US/docs/Web/API/Element/compositionupdate_event
https://developer.mozilla.org/en-US/docs/Web/API/Element/compositionend_event

#### What information was incorrect, unhelpful, or incomplete?
These pages state that these events are cancelable but they are not.

#### Did you test this? If so, how?
Operating System: macOS 12.3
Browsers: Firefox 98.0.1, Firefox Developer Edition 99.0, Safari 15.4, Safari Technology Preview 15.4

I copied the example codes from these pages and added event.preventDefault(); to the handleEvent function. On macOS I set the input source to Korean and it does not prevent me to type in text into the text field.
Out of curiosity I tried both stoppropagation and stopimmediatepropagation, same result.

In the console Firefox shows cancelable: false, Safari shows cancelable: true but they both have the same behavior.

https://user-images.githubusercontent.com/76746210/159130960-73eee33f-4eac-423c-9011-60e8b4094f31.mov

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/element/compositionstart_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/compositionstart_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/compositionstart_event/index.md
* Last commit: https://github.com/mdn/content/commit/b6502bee0963713643e73bc486422e383c8902c2
* Document last modified: 2022-03-06T12:51:51.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #14066 to fix the docs for the `compositionend` and `compositionupdate` events.

However, I’ve not changed the documentation for the `compositionstart` event, because at https://w3c.github.io/uievents/#event-type-compositionstart the spec defines `compositionstart` as "Cancelable: Yes".

If you’re finding that `compositionstart` is not cancelable in one or more browsers, then if you can post a reproducible test case which demonstrates that, we could open an issue for it at https://github.com/mdn/browser-compat-data/issues/new/choose
