### ISSUE TITLE
"Cache-Control" doc: “if the response with Cache-Control: max-age=604800 was generated more than 3 hours ago” but 604800 is 7 days, not 3 hours

### ISSUE THREAD

**Issue by BSarmady** [mdn/content#14095]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control

under header `max-age` mentioned

> [max-age](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#max-age_2)
>
>The max-age=N request directive indicates that the client allows a stored response that is generated on the origin server within N >seconds — where N may be any non-negative integer (including 0).
>Cache-Control: max-age=604800
>
>In the case above, if the response with Cache-Control: max-age=604800 was generated more than 3 hours ago (calculated from >max-age and the Age header), the cache couldn't reuse that response.

The number 604800 (which is equal to 7 days) is used in multiple places

It is confusing that why client will not use the cached version 3 hours after it is created even though it is valid for 7 days after it is created.

I'm guessing it is a miss-copy miss-paste?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/headers/cache-control`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/cache-control/index.md
* Last commit: https://github.com/mdn/content/commit/5f3cacbf4db23d0656aa3d231b7181ba2fc5743e
* Document last modified: 2022-03-16T02:50:06.000Z

</details>

**Comment by sideshowbarker** [comment]
summoning @Jxck

**Comment by hamishwillee** [comment]
The `max-age`  can be set in either requests or in responses. If it is in a request, it is the maximum age the client will accept, and if it is in a response, it is the maximum age that the server wants the cache to hold the resource for.
Whether or not it is sent to the client depends on both the client and the original server desired max-age.

In this case the text is for the request so the client will accept a cached resource that is 3600seconds old = 60 minutes = 1 hour.
```
Cache-Control: max-age=3600
```
If the original response was sent with  `Cache-Control: max-age=604800` (7 days), and that was set 2 hours ago (>1 hour), then the server might be be OK with the cache returning the resource, but the client won't. 

So I'm not sure that this is a typo, but it is still confusing:
- I don't understand from this how the `Age` header works.
- Referring to 3 hours when the 3600 is 1 hour is confusing.
- I assume that if a cache gets a request from a client that won't accept the current version, it automatically just re-requests the resource.

**Comment by Jxck** [comment]
> It is confusing that why client will not use the cached version 3 hours after it is created even though it is valid for 7 days after it is created.

because it's the aim for `max-age` on *Request* from client.
if client intend to get fresh-er response, `max-age=N` indicates that "fetch response which generated less than N sec is acceptable". One use-case is `max-age=0` ("please give me newest") on browser reloading.

`max-age=N` directive means "if age is less than N".

for example, server generates response 00:00

```
HTTP/1.1 200 OK
Date: Tue, 22 Mar 2022 00:00:00 GMT
Cache-Control: max-age=604800
```

and proxy cache stored it.

client request as below few time later

```
GET / HTTP/1.1
Cache-Control: max-age=3600
```

Proxy cache resolve this request based the time past since store response.

```
// on proxy
Age = time since store response in sec
isFresh = res.cache-control.max-age < Age

if (isFresh) {
  if (Age =< req.cache-control.max-age) {
     return stored response
  } else {
     return through to origin
  }
} else {
     return through to origin
}
```

So current sentence is correct.
And I'll add more explanation of "Age" on https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching later.

**Comment by bobsort** [comment]
My Intention from posting this issue was the clear the use of same 7 days in max-age header in both response and request sections, which doesn't explain it is actually 7 days and how it is related to request and responses in discussion that are in `hour` and `minute` range.

In response header it says;

> Indicates that caches can store this response and reuse it for subsequent requests while it's [fresh].`

Which actually could say something like:

*Indicates that caches can store this response for **up to** 7 days and reuse it for subsequent requests while it's [fresh].*

Same goes with `s-maxage` and `immutable`, 

Also in this example (a few paragraph below)

> Note that max-age is not the elapsed time since the response was received; it is the elapsed time since the response was generated on the origin server. So if the other cache(s) — on the network route taken by the response — store the response for 100 seconds (indicated using the Age response header field), the browser cache would deduct 100 seconds from its [freshness lifetime].

>Cache-Control: max-age=604800
>Age: 100`

Which doesn't specify that Age header is added by cache server and not the server itself and it is to indicate that the response was in the cache for 100 seconds at the moment it was sent to client (or secondary cache server).  It is also the clients decision to how long they keep the cached version, it can be **up to** 604800-100 but not more. I also think `max-age` is only added by originating server and not cache servers on the route hence the existence of age header.

As for max-age in request, it says:

>The max-age=N request directive indicates that the client allows a stored response that is generated on the origin server within N seconds — where N may be any non-negative integer (including 0).
>
>Cache-Control: max-age=3600
>
>In the case above, if the response with Cache-Control: max-age=604800 was generated more than 3 hours ago (calculated from max-age and the Age header), the cache couldn't reuse that response.

I guess better way of saying it would be something like

*With this request, client is asking for a response not any older than 1 hour. In this case response that is generated 3 hours ago with  Cache-Control: max-age=604800 and stored in middle cache server,  will not be valid for this specific client even though it is still might be valid for other clients and will stay in cache server for another 7 days minus 3 hours and is valid.*





`

**Comment by Jxck** [comment]
Request header only affects for itself. not for others, and no side effects like removing stored response from cache.
It's general thing not only for here, but also for other request.

**Comment by Jxck** [comment]
> It sounds like the cache just pass the request through to the server, which responds with a new resource, and the cache might simply pass this response back without replacing whatever value it currently stores. Is that right?

Yes It can be.

Note that: It's the one way to implementation, and also do noting, ignore completely etc is also fine.
because according to the cache spec.

> This section defines cache request directives. They are advisory; caches may implement them, but are not required to.
> --- https://httpwg.org/http-core/draft-ietf-httpbis-cache-latest.html#cache-request-directive


> That 3 hours is really unhelpful - because there is no relationship between "3 hours", and the other examples of server max age, client max age or the Age header. It's just some number picked out of the air as "no longer fresh".

Yes, every N < 7days(604800) are fine here.

**Comment by Jxck** [comment]
FYI: I'm not tech writer, so if it's an editorial issue and someone sends PR for bushing up sentences without changing it meaning. I don't against if @sideshowbarker merging it.

**Comment by sideshowbarker** [comment]
Yeah I pinged @Jxck for technical review of the issue. A related change to the issue can be made by anybody, so I’m going ahead and updating the labels here.
