### ISSUE TITLE
addAttribute or setAttribute

### ISSUE THREAD

**Issue by KelvinPaul** [mdn/content#1410]
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Alert_Role

**Function contains wrong method**
the above documentation says HTMLParagraphElement have addAttribute function. 
_function triggerAlert() {
	var alertEl = document.querySelector('.alert');
	alertEl.addAttribute("role", "alert");
}_

**wrong way of inline function listening**
I think, we need to use onclick="triggerAlert()" instead of onclick="triggerAlert"
&lt;button type="button" onclick="triggerAlert">Trigger alert&lt;/button>

**Comment by chrisdavidmills** [comment]
To whoever fixes this, it looks like the following is needed:

1. Fixed the referenced example.
2. We would rather it got fixed by removing the event handler attribute altogether, and instead using `addEventListener()` on a reference to the element, as per our style guide, and modern best practices.
