### ISSUE TITLE
JavaScript Decorators: <JAVASCRIPT DECORATORS>

### ISSUE THREAD

**Issue by lv2lrn4lf** [mdn/content#14106]
What is the new suggestion?
So mdn don't contain any reference of knowledge about javascript decorators.

Why is it important or useful? Tell us why the idea is important or useful. Include any information you
can think of that would be useful, for example:
Need someone to make this page for no reason other than to have it on mdn in cause some want to learn directly from mdn.

How many pages are likely to be needed?
1 page will needed to just give a over view and a little depth than you can just point to some other resource that is validated by MDN to learn more from.

How much time do you think this work should take? A few hours? A week? A month?
I don't know.... I could do it in a hour by copying from some site and pasting in than editing a little to put in my own words and than throw in a few reference including the site that I copy from.

Will the work enable learners or professionals to achieve their goals better?
I honestly don't know.... since it's not up there now, and I never ever had to use it... to the point of not knowing about it until now.

Does it address critical needs in the web industry?
if you ask me... maybe if it made sense to me... seem to shorten key stroke to get what you want done but seem a bit confusing as well.

Is the work an operational necessity, i.e. is not having it a security risk?
no.

Does the content help make the web more ethical?
.... not sure

Other supporting information

if this is a stupid post by all means please delete it.. i just through the site that taught my javascript didn't list a feature of javascript was strange enough to even tell a dev streamer who also found it weird... own another weird note for those who don't know you can have HTML comments in your javascript file.. which make sense if you dev back in the earliest days of javascript.

**Comment by hamishwillee** [comment]
Thanks @lv2lrn4lf 

We won't document these yet, because it is too early - they are  not yet part of the standard ("stage 2") and there is still no final agreement on how they will look. For the same reason the feature isn't delivered in Firefox yet either: https://bugzilla.mozilla.org/show_bug.cgi?id=1435869

MDN does have one comment about them at the end of https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Class_static_initialization_blocks#description - "A static initialization block may not have decorators (the class itself may)."> Arguably we should strip this until they are introduced, but I think it does no harm.

If this goes to stage 3 it is likely Firefox and others will provide an implementation, and at that point we will provide documentation.
