### ISSUE TITLE
"Adding 2D content to a WebGL context": “mat4’ isn't real code. Apparently we're supposed to use some external library glmatrix.js?

### ISSUE THREAD

**Issue by SephReed** [mdn/content#14148]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Adding_2D_content_to_a_WebGL_context

#### What information was incorrect, unhelpful, or incomplete?
`mat4` isn't real code.   Apparently we're supposed to use some external library `glmatrix.js`?  

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Adding_2D_content_to_a_WebGL_context#rendering_the_scene

#### What did you expect to see?
Functional code on making webgl render stuff

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/webgl_api/tutorial/adding_2d_content_to_a_webgl_context`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Adding_2D_content_to_a_WebGL_context
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/webgl_api/tutorial/adding_2d_content_to_a_webgl_context/index.md
* Last commit: https://github.com/mdn/content/commit/b7aafea1ab7cfee11a7e854a4b5c83a6e6d329d4
* Document last modified: 2022-02-02T09:11:35.000Z

</details>

**Comment by SephReed** [comment]
Just looked into it, and the glmatrix library adds over 7000 lines of code (https://github.com/toji/gl-matrix/blob/master/dist/gl-matrix.js) to a project.  If there's any way to explain webgl without the inclusion of such a massive library, that would definitely be more applicable for what mdn is supposed to teach.  Why wouldn't someone just use a full framework at that point?

**Comment by sideshowbarker** [comment]
I’m going ahead and closing this issue because we are very intentionally using glMatrix and we have no plan to re-write all the WebGL tutorial code to do vector and matrix operations manually without using that library.

---

The “Adding 2D content to a WebGL context” page — at the very top of the page — explicitly states:

> This project uses the [glMatrix](https://glmatrix.net/) library to perform its matrix operations, so you will need to include that in your project.

So the page makes it clear from the beginning that the code examples rely on that library.

>  If there's any way to explain webgl without the inclusion of such a massive library, that would definitely be more applicable for what mdn is supposed to teach.

Programming with WebGL is complex, and the tutorials are designed to break the complexity down into user-friendly parts. And in order to do that, the scope of the tutorials does not include explaining how to do performant vector and matrix operations. Instead, the tutorials use a library, glMatrix, which is designed to do that work for developers so that they don’t have to manage it manually. And that library is very widely used by developers.

> #### What did you expect to see?
> 
> Functional code on making webgl render stuff

The code in the article is functional. It works. And like most real-world WebGL code, it makes use of an external library to handle some of the related chores. So it’s actually modeling real-world WebGL usage in that regard.
