### ISSUE TITLE
"Ignore a source": I expect an option to UNIGNORE console debugger statements

### ISSUE THREAD

**Issue by maxgrass** [mdn/content#14177]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Ignore_a_source

#### What information was incorrect, unhelpful, or incomplete?

Executing a code from the Console with `debugger;` in it, opens a "virtual" file "SOURCE" as a tab when the `debugger;` breakpoint is triggered.

You can "ignore" this SOURCE as the article suggests. 

Then close the SOURCE tab.

It's not in the file list in the file/script browser (on the left / in the left pane).

Now Console `debugger;` statements will be ignored.

#### What did you expect to see?

I expect an option to UNIGNORE console `debugger;` statements.

#### Did you test this? If so, how?

See information in the first paragraph.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/debugger/how_to/ignore_a_source`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Ignore_a_source
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/debugger/how_to/ignore_a_source/index.html
* Last commit: https://github.com/mdn/content/commit/426485595b1be50e2af91764fbfd94c04c3c36a5
* Document last modified: 2022-02-18T11:38:26.000Z

</details>

**Comment by ddbeck** [comment]
Hi, I'm closing this issue because [Firefox DevTools User Docs](https://firefox-source-docs.mozilla.org/devtools-user/index.html#firefox-devtools-user-docs) have moved off of MDN (see https://github.com/mdn/content/pull/14140 for details on content moved). If this issue is still applicable to the relocated documentation, please see the Firefox Source Docs site for details on raising bugs and contributing. Thanks for your understanding!
