### ISSUE TITLE
Content bug: Auto-generated Anchors

### ISSUE THREAD

**Issue by erosman** [mdn/content#14196]
## What page(s) did you find the problem on?
MDN [tabs.onUpdated](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/onUpdated)

## Specific page section or heading?
addListener syntax -> Parameters -> changeInfo

## What is the problem?
Script auto-generates  ids for:
```html
<dt id="changeinfo"><code>changeInfo</code></dt>

<h3 id="changeinfo_2"><a href="#changeinfo_2" title="Permalink to changeInfo">changeInfo</a></h3>
```

Repo [tabs.onUpdated](https://github.com/mdn/content/edit/main/files/en-us/mozilla/add-ons/webextensions/api/tabs/onupdated/index.md) line 51-52
```
    - `changeInfo`
      - : [`object`](#changeinfo). Contains properties for the tab properties that have changed. See [`changeInfo`](/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/onUpdated#changeinfo) below.
```

While on the surface it looks correct, above anchor links to its own ```<dt>```
:pushpin:  Although the edit is trivial, repetitions of auto-generated anchors on MDN should be looked into as this probably is not an isolated instance.

## What did you expect to see?

Although the edit is trivial, 
```
    - `changeInfo`
      - : [`object`](#changeinfo). Contains properties for the tab properties that have changed. See [`changeInfo`](/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/onUpdated#changeinfo_2) below.
```

## Did you test this? If so, how?

n/a

**Comment by erosman** [comment]
Another example _(it would appear that the issue is widespread)_

[webRequest.onCompleted](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onCompleted)

```html
<dl>
  <dt id="details"><code>details</code></dt>
  <dd>
    <p><a href="#details"><code>object</code></a>. Details about the request. See <a href="#details"><code>details</code></a> below.</p>
  </dd>
</dl>

<!-- ......  -->

<h3 id="details_2"><a href="#details_2" title="Permalink to details">details</a></h3>
```

**Comment by OnkarRuikar** [comment]
I think instead of changing the anchor, which may break again when the backend implementation changes, it's better to list the object contents directly below it, instead of creating a separate section and providing link to it.

For example refer https://developer.mozilla.org/en-US/docs/Web/API/FetchEvent/FetchEvent page. Many WebAPI pages have massive parameters lists. We don't have to break the list in multiple sections.

**Comment by iSatVeerSingh** [comment]
I found a page with this bug. I am working on it.

**Comment by kylewcode** [comment]
@erosman @OnkarRuikar Is this issue still open because it's a recurring issue on other pages or because this page is being considered to be redesigned so that instead of anchor tags to content on the same page, use links to the content on a separate page?

**Comment by erosman** [comment]
@kylewcode I reported the issue which required a change to the way MDN code works (beyond a simple PR). It is up to the engineers to confirm the outcome.

**Comment by OnkarRuikar** [comment]
People have fixed some of those simple link issues in content. I have no idea if all of them have been fixed or there exist more.

HTML pages don't have such issue related to definition list IDs e.g. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-autofocus
There use of [{{htmlattrdef}}](https://github.com/caugner/yari/blob/main/kumascript/macros/htmlattrdef.ejs) macro generates IDs like `attr-*`.
We could make the macro generic and use it everywhere. But if we change the way def list ids are generated now, then a lot of existing internal links will break. It is a massive change.

Simple workaround, on content side, could be to add a custom markdownlint rule [to flag cases](https://github.com/mdn/content/blob/main/.markdownlint-cli2.jsonc#L162) where def list and headers(`##`) have same text. This way authors will be forced to used different header. @teoli2003, @wbamberg WDYT?

**Comment by wbamberg** [comment]
The history of this: originally only headings got generated IDs. Then in https://github.com/mdn/yari/pull/5190, Mike updated Yari to generate IDs for `<dt>` elements as well. We discussed this possible issue in https://github.com/mdn/yari/pull/5190#issuecomment-1024411333 , and decided it wasn't likely to cause problems, but only from the perspective of live samples.

The obvious suggestion, back then, would have been for `<dt>` IDs to "defer to" heading IDs, so if a value is already taken be a heading, then the `<dt>` gets the suffixed version, and existing links to the heading still work. But apparently that was really hard to do, because the code where we could generate these things didn't have the context of the whole document (or something like that). And as you say:

>  if we change the way def list ids are generated now, then a lot of existing internal links will break

I guess _now_, we should try to deal with this by changing as few IDs as possible. It would be good to know how many pages on MDN have the same (normalized) text in a `<dt>` and in a heading. Maybe we can just fix it in content as well as possible, by updating any links we can find where it is a problem.

> add a custom markdownlint rule [to flag cases](https://github.com/mdn/content/blob/main/.markdownlint-cli2.jsonc#L162) where def list and headers(##) have same text. This way authors will be forced to used different header

I don't think it is necessarily bad to have a headings and a `<dt>` with the same normalized text. We account for that with the suffix (just like we do for headings that have the same text). What's bad is that when we started generating them we broke some existing links.

Or maybe we should change `<dt>`-id generation to generate ID values like `dt-thing`, and find and update all internal links to them. We might end up in a better place then. But we'd also of course break any external links to dt-fragments.

**Comment by OnkarRuikar** [comment]
> It would be good to know how many pages on MDN have the same (normalized) text in a <dt> and in a heading. 

There are 40 such pages as per regex ```- `(.*)`[\s\S]+#+ \1$```.

> Maybe we can just fix it in content as well as possible, by updating any links we can find where it is a problem.

I've created a PR for the ones I've found https://github.com/mdn/content/pull/22331.

> Or maybe we should change `<dt>-id` generation to generate ID values like dt-thing, and find and update all internal links to them. We might end up in a better place then. But as you say it's a lot of work and we'd also of course break any external links to dt-fragments.

Changing id generation now may break some stuff in third party websites and software. For example in IDEs, documentation references may break:
> ![references](https://user-images.githubusercontent.com/87750369/202111629-e8219d0c-4299-4bb5-a506-de0cd0f9f841.png)

Here, the ['src' on developer.mozilla.org](https://developer.mozilla.org/en-US/docs/web/html/element/img#attr-src) link uses the `<dt> id` as fragment. And looks like the tooltip content is also obtained(as it is) from the mdn/content repo.

There is small inconsistency, HTML documents use `attr-` prefix for definition list IDs, but other documents do not use any prefix.  I think bigger discussion is needed on whether we want to change the IDs, if yes then what should be the prefix, how we want to  approach the change etc.

**Comment by majidzeno** [comment]
@wbamberg I found that this file issue got resolved [here](https://github.com/mdn/content/pull/22388) so we might close this issue 🙏

**Comment by teoli2003** [comment]
Thank you!
