### ISSUE TITLE
Issue with "<input type="file">": Properties anchor link does not exist

### ISSUE THREAD

**Issue by mzur** [mdn/content#14209]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file

#### What information was incorrect, unhelpful, or incomplete?
The properties description points to: <https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement#properties_file>.
However, the `#properties_file` anchor does not exist on this page.

#### Specific section or headline?
properties

#### What did you expect to see?
The linked page should open and scroll to the section "Properties that apply only to elements of type `file`".

#### Did you test this? If so, how?
Click on the link and the page will be opened at the top.

I couldn't find the referenced achor in the commit history. I'd be happy to add it in a PR if you give your ok.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/input/file`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/file/index.md
* Last commit: https://github.com/mdn/content/commit/358158b18ad8c2b90b83fe4dc03bdd7fd2e423da
* Document last modified: 2022-03-19T16:52:08.000Z

</details>

**Comment by wbamberg** [comment]
Thank you for filing!

The minimal fix here I guess is just to add the anchor to the relevant table under https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement#properties, which is easy because this is all HTML.

But there seem to be a couple of other issues too:

* I can't see a similar link in any of the other `input` types, and it's quite misleading: it isn't actually a list of all the properties, only those that only apply to this type. I'm not sure how that is helpful. I would just remove this line and rely on the earlier link to `HTMLInputElement`, which should be able to provide all the nuance about which properties apply when.
* I don't like all those HTML tables in `HTMLInputElement`. It's very conventional for us to use `<dl>` for things like this, and we have a Markdown syntax for `<dl>`. We could keep the existing categorization, but instead of tables, divide up "Properties" with H3 headings for each category and have a separate `<dl>` for each category. But honestly looking at the categories it might be better just to have one `<dl>` and note for each (`<dt>/<dd>`) property which types it applies to. Or even just a general note that ` HTMLInputElement` properties that reflect attributes only apply to element types that actually support the underlying attribute. It should be rather obvious that if an element doesn't have a `checked` attribute, then a `checked` property that reflects that attribute won't apply to it.

Does that make sense?

**Comment by mzur** [comment]
Thanks for your response! Then I suggest to just leave the "DOM interface" link to `HTMLInputElement` and remove the "Properties" row. I could add "DOM interface" rows for all other input element types as well. What do you think?

As to the HTML tables: You mean `<dl>` as it is used for the `align` and `useMap` properties on that page? I think it's quite useful to list which properties apply to which element type. But listing this for each property separately would be quite verbose IMO. I'd rather keep the categories as `<h3>`. Any objections?

**Comment by wbamberg** [comment]
> Thanks for your response! Then I suggest to just leave the "DOM interface" link to `HTMLInputElement` and remove the "Properties" row. I could add "DOM interface" rows for all other input element types as well. What do you think?
> 

Yes, I suppose so. It seems quite repetitive, and we already describe this at the `<input>` level, but I guess it would be OK. To be honest the input types are a nightmare to document and despite many attempts it feels like it's still not quite right.

> As to the HTML tables: You mean `<dl>` as it is used for the `align` and `useMap` properties on that page? I think it's quite useful to list which properties apply to which element type. But listing this for each property separately would be quite verbose IMO. I'd rather keep the categories as `<h3>`. Any objections?

Yes, I think that would be fine - to keep H3 headings for the categories, but then within each category have a (Markdown) `<dl>` instead of a `<table>`. That would improve this page a lot IMO.

**Comment by mzur** [comment]
Alright, I will send PRs soon!
