### ISSUE TITLE
Content suggestion: Add Rust to glossary

### ISSUE THREAD

**Issue by MrBrain295** [mdn/content#14333]
## What is the new suggestion?

Adding [Rust](https://www.rust-lang.org/) to the glossary.
## Why is it important or useful?

I think Rust should be added to the glossary because it’s a language that is often compiled to web assembly and used websites that take advantage of web assembly.
## Other supporting information
[Rust’s website](https://www.rust-lang.org/)

**Comment by hamishwillee** [comment]
If the argument is that the MDN glossary should be the canonical reference for all things web-ish then you would have an entry. I don't think that is the case.

I add things to the glossary when there is a term in the text that is not well understood or might be ambiguous. Looking through MDN (just a quick scan) I can't find a single case where things would be improved by linking Rust to a glossary item instead of the Rust website.

Don't know what others think though.

**Comment by sideshowbarker** [comment]
I’m going ahead and closing this because I think it’s likely we have general agreement that it doesn’t seem like we have a compelling need to add a Rust term to the glossary (for the reasons articulated in https://github.com/mdn/content/issues/14333#issuecomment-1080037473).

The statement given in the issue description could equally be used to assert we should add C and C++ to the glossary; e.g.:

> I think C++ should be added to the glossary because it’s a language that is often compiled to web assembly and used websites that take advantage of web assembly.
