### ISSUE TITLE
[WebAPI] Enable writableStream & pipeTo()

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#14408]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

`writableStream` & `pipeTo()` now default - looks like this is a BCD & rel update

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1759597

**Comment by hamishwillee** [comment]
Docs already exist but need review. These were added in FF99 behind `dom.streams.writable_streams.enabled` and `dom.streams.pipeTo.enabled`, respectively.

Status: 

- [ ] BCD - https://github.com/mdn/content/issues/14408
- [ ] Experimental Features - not present
- [ ] Release notes
- [ ] Docs
- [ ] dev-doc-complete

**Comment by hamishwillee** [comment]
@Rumyra This is pretty much done. 
FYI Because the docs already existed all that was required is a simple BCD update and release note. I did tidy the docs around these because some of the tagging (e.g. experimental) was off, but that is about it.
We could do more - e.g. interactive examples, but there are some excellent examples already linked.

**Comment by Rumyra** [comment]
Yeh we tend to do external examples for Web APIs - in page examples for them tend to be a pain (depending on the api)
