### ISSUE TITLE
"Silly story generator": The newStory = newStory.replace(':insertx:',xItem); statement is listed twice within the result() function.

### ISSUE THREAD

**Issue by blazzII** [mdn/content#14549]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Silly_story_generator

#### What information was incorrect, unhelpful, or incomplete?
The newStory = newStory.replace(':insertx:',xItem); statement is listed twice within the result() function.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/silly_story_generator`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Silly_story_generator
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/first_steps/silly_story_generator/index.md
* Last commit: https://github.com/mdn/content/commit/358158b18ad8c2b90b83fe4dc03bdd7fd2e423da
* Document last modified: 2022-03-19T16:52:08.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing! To be sure, you're referring to this bit: https://github.com/mdn/learning-area/blob/b69c281cb2adf30063e667a392411a2ad3cedc5e/javascript/introduction-to-js-1/assessment-finished/main.js#L24-L25 of the finished example?

**Comment by mikoMK** [comment]
This is intentional. There are two occurrences of `:insertx:` in the source text and this `replace()` code only changes one per call. Therefore this code is correct.
Alternatively we could use `replace()` with regex and global flag or `replaceAll()` in the solution, but maybe the current version helps to understand that `replace()` doesn't change every occurrence by default.

**Comment by wbamberg** [comment]
Oh yes, you're right of course @mikoMK . I think it would be good to use `replaceAll()` here. I think it didn't exist when this course was written. What do you think about using `replaceAll()` for all three cases? That's surely the intention of the code - to replace all placeholders - it just happens that in two cases there's only one occurrence.

**Comment by mikoMK** [comment]
> I think it didn't exist when this course was written.

Yes, that's true.

> What do you think about using replaceAll() for all three cases?

Agreed. All modern browsers support `replaceAll()` since a while now. I think it's a good idea to use this function. In the learning area itself we also have a short section about `replace()` (https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Useful_string_methods#updating_parts_of_a_string). It would make sense to mention `replaceAll()` there, too.

If you like I can prepare two PRs for the assessment solution and the learning section.

**Comment by wbamberg** [comment]
> > I think it didn't exist when this course was written.
> 
> Yes, that's true.
> 
> > What do you think about using replaceAll() for all three cases?
> 
> Agreed. All modern browsers support `replaceAll()` since a while now. I think it's a good idea to use this function. In the learning area itself we also have a short section about `replace()` (https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Useful_string_methods#updating_parts_of_a_string). It would make sense to mention `replaceAll()` there, too.
> 
> If you like I can prepare two PRs for the assessment solution and the learning section.

That would be awesome. Thank you @mikoMK ! Please ping me for a review.
