### ISSUE TITLE
Content bug: Mark Unimplemented API

### ISSUE THREAD

**Issue by erosman** [mdn/content#14562]
## What page(s) did you find the problem on?

[menus.overrideContext()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/overrideContext)

MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/overrideContext

## What is the problem?

Although there is no **Browser compatibility** table (not a clear indication though), it would be beneficial if the page would clearly mark the state of the API e.g.  unimplemented/under-development/deprecated/removed etc.

### Also
Parent page [Functions](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus#functions) should also mark the API the same way experimental/deprecated are marked

:pushpin:  A new Under-dev icon could be good

### Reference
[Support contextMenus API / menus.overrideContext in the extensions' devtools panels](https://bugzilla.mozilla.org/show_bug.cgi?id=1659433)

**Comment by hamishwillee** [comment]
Thanks @erosman - I've added browser compatibility for this in the linked items. As far as I can tell it is only supported by firefox, from FF64

**Comment by rebloor** [comment]
Now we need to note that this only works in moz-extension:-pages

**Comment by rebloor** [comment]
After reviewing the MDN documentation, release notes, and various blog posts, I determined that my note of 24 May was incorrect. [`menus.overrideContext()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/overrideContext) use is not limited to `moz-extension:`-pages. This comment relates to [Bug 1498896](https://bugzilla.mozilla.org/show_bug.cgi?id=1498896) Always use documentUrlPatterns to match the document URL in extension views, even when menus.overrideContext is used. This change means that you can restrict a custom context menu to your sidebar/popup panel, by the combination of `viewTypes` and `documentUrlPatterns` options in `menus.create`. As this would be the expected behavior there seem is no need for a documentation update to `documentUrlPatterns`. However, I've created a new issue to update [Context menu items](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Context_menu_items) with relevant information.
