### ISSUE TITLE
MediaTrackConstraints.displaySurface: there is no way to restrain surface type via javascript; can only detect surface type for a current stream already going

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#1456]
@simajzenman commented on [Tue Nov 10 2020](https://github.com/mdn/sprints/issues/3878)

# Request type

- [ ] Correction or update

# Details

Hello Mozilla,

I've seen in the page about MediaTrackConstraints.displaySurface (https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints/displaySurface) that in the first paragraph, it says "is used to specify the type or types of display surfaces which getDisplayMedia() will let the user select among for sharing purposes.". As far as I know (and tested) there is no way to restrain the type of surface you want to allow in javascript on client side; displaySurface (as it is written in the same page) can be used to detect the type of surface for a current stream already going.

If I am wrong, I first apologies for wasting your time and would be happy to have more info.
I also tried to edit it myself but couldn't for that paragraph

In the meantime, if you know where I could find in the doc a way to identify the stream name(meaning if I share facebook tab browser, I should find "facebook" in the name of the current stream), it would really help me.

Have a great one,
Simon

**Comment by sideshowbarker** [comment]
Given that this issue has been open for more than a year without anybody picking it up and creating a PR, it seems likely it would just continue to remain open for much longer without any activity.

Therefore, I’m making a judgement call and going ahead and closing it. If it turns out that anybody feels strongly otherwise, it could be re-opened.

**Comment by teoli2003** [comment]
I don't mind closing issues that are unclear, or so imprecise that it is difficult to know if they are solved or not, but it seems to me that this one raises an actual error in our docs.

I don't have the time to check it, nor to fix it. But we should keep it.

@Rumyra or @schalkneethling Maybe you can find a subject matter expert who could assess, and eventually fix this one?

**Comment by dscotese** [comment]
I don't think the documentation is wrong.  "...to specify" does not identify who is doing the specifying, and I think that is where the confusion lies.  If the word "specify" were changed to "identify", that might help, but to be explicit, the sentence should be:
"This is used by the user agent to identify the type or types of display surfaces...", because it isn't up to us.  The user agent gets to decide.  That is how I read it and in a while, if no one objects and no one else does it, I will make that change and add a pull request.

**Comment by Josh-Cena** [comment]
@dscotese Yes, "identify" sounds better than "specify". I think most developers assume that "we are specifying things to the browser" rather than "the browser specifies things to us". To be more explicit you can even add a sentence saying you can't change this in JS.

**Comment by dscotese** [comment]
** might close the issue.
