### ISSUE TITLE
"Changing the Priority of HTTP Requests": mention new Fetch API priority option and/or Priority Hints

### ISSUE THREAD

**Issue by Eccenux** [mdn/content#14561]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/1.5/Changing_the_priority_of_HTTP_requests

#### What information was incorrect, unhelpful, or incomplete?

The page above popups up in the search result. I found it when searching for priority.

You should probably mention new Fetch API priority option there 🙂
https://web.dev/priority-hints/#the-fetchpriority-attribute

Maybe link to Fetch API priority:
https://developer.mozilla.org/en-US/docs/Web/API/Request/priority

Or a link to Priority Hints if that will be created.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/firefox/releases/1.5/changing_the_priority_of_http_requests`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/1.5/Changing_the_priority_of_HTTP_requests
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/firefox/releases/1.5/changing_the_priority_of_http_requests/index.md
* Last commit: https://github.com/mdn/content/commit/e703747a072adc736f7a1931d2993250f81f70aa
* Document last modified: 2022-01-18T23:06:03.000Z

</details>

**Comment by hamishwillee** [comment]
@sideshowbarker This page is an addendum to a Firefox 1.5 release note, which talks about messing with priority through a non-standard property that requires elevated privileges to use via [`XMLHttpRequest.channel`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/channel). Generally people should use `Fetch` over `XMLHttpRequest`, and this just another reason why.

The problem here is that if you search for priority on google this is what you get (if you search on MDN it doesn't show, but you get the equally lovely "MDN documentation priority list"). I'm not sure just adding notes about those hints is enough (?)

So how about we first of all rename this to something like "Firefox 1.5 HTTP Request Priority (Non-Standard)" so that it is obviously not the final answer. We can then add links to fetch and client hints in a warning up the top.

The general topic on setting priority of resource requests appears to be quite an interesting one. Seems to be you can use priority hints, or this Request priority, and in future maybe the [Priority](https://tools.ietf.org/id/draft-ietf-httpbis-priority-01.html) header. There are also some ideas ([from here](https://calibreapp.com/blog/critical-request)), some of which may be relevant (e.g. marking the non-critical ones as `async`):
- Mark non-critical scripts as async
- Consider inlining @font-face declarations directly into HTML
- Avoid using CSS background images or @import
- Use preload to retreive critical resources earlier

Anyway, if we decided to have a dedicated topic, where would be the best place for it to live?

**Comment by teoli2003** [comment]
"Firefox 1.5 HTTP Request Priority (Outdated)" + the note ?

**Comment by sideshowbarker** [comment]
> So how about we first of all rename this to something like "Firefox 1.5 HTTP Request Priority (Non-Standard)"
>
>"Firefox 1.5 HTTP Request Priority (Outdated)" + the note ?

Either of “Non-Standard” or “Outdated” SGTM

> so that it is obviously not the final answer. We can then add links to fetch and client hints in a warning up the top.

👍  SGTM

> Anyway, if we decided to have a dedicated topic, where would be the best place for it to live?

I guess either directly under https://developer.mozilla.org/en-US/docs/Web/Performance or else directly under  https://developer.mozilla.org/en-US/docs/Web/API/fetch ?

**Comment by hamishwillee** [comment]
Thanks guys. I've created a fix for this page and an issue for the new page.
