### ISSUE TITLE
"DOMTimeStamp": renamed to EpochTimeStamp

### ISSUE THREAD

**Issue by simonvarey** [mdn/content#14667]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/DOMTimeStamp

#### What information was incorrect, unhelpful, or incomplete?
This page has a link to specification of DOMTimeStamp, but the linked page https://webidl.spec.whatwg.org no longer has a specification of DOMTimeStamp (as of 21 Mar 2022). I believe EpochTimeStamp has replaced DOMTimeStamp.

#### Specific section or headline?

Specification

#### What did you expect to see?

A page specifying DOMTimeStamp

#### Did you test this? If so, how?

Followed the link and searched the page.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/domtimestamp`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/DOMTimeStamp
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/domtimestamp/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it.

Given https://github.com/whatwg/webidl/pull/1021: To whoever fixes this, what needs to happen is:

- Create a new `EpochTimeStamp` article, based on https://w3c.github.io/hr-time/#the-epochtimestamp-typedef, or else rename the `DOMTimeStamp` article
- Add the `Deprecated_Header` macro to the `EpochTimeStamp` article
- Add `EpochTimeStamp` to https://github.com/mdn/browser-compat-data, marked as deprecated
- Make sure the current MDN article `DOMTimeStamp` ends up resolving to the `EpochTimeStamp` article instead (either due to renaming or else because you set up a redirect)

**Comment by hamishwillee** [comment]
@sideshowbarker @simonvarey It isn't this simple, as you will see from this discussion: https://github.com/mdn/content/pull/11675 - and in particular https://github.com/mdn/content/pull/11675#discussion_r782557463 :

>  DOMTimeStamp originally referred to itself as a timestamp definition where specific details were covered in other specs (I think this was in WebIDL spec). It was removed from that spec. It was separately redefined in the high resolution time spec to be this epoctimestamp, with precise meaning. So my concern was that the redefinition might only work for this specific spec definition and not the definition in other specs.

In other words it is good to create `EpochTimeStamp`, which I did in https://developer.mozilla.org/en-US/docs/Web/API/EpochTimeStamp , but we were unsure if the DOMTimeStamp should simply redirect because it is mentioned in other specs which have their own definitions that do NOT map to `EpochTimeStamp` (at least yet).

Thoughts?

**Comment by sideshowbarker** [comment]
> In other words it is good to create `EpochTimeStamp`, which I did in [developer.mozilla.org/en-US/docs/Web/API/EpochTimeStamp](https://developer.mozilla.org/en-US/docs/Web/API/EpochTimeStamp) , but we were unsure if the DOMTimeStamp should simply redirect because it is mentioned in other specs which have their own definitions that do NOT map to `EpochTimeStamp` (at least yet).

Thanks — OK I now see https://github.com/whatwg/webidl/pull/1021#issuecomment-947510725

I don’t really have a good suggestion about what to do here. I can see now that this problem was created for us due to `DOMTimeStamp` having been removed prematurely from the WebIDL spec — despite the fact that other specs are still referencing it. That was a spec mistake that should not have been made. But we can’t fix that.

But given all that, I don’t think we should remove or change the spec URL in our `DOMTimeStamp` article, because it’s actually the correct spec link: It points to where `DOMTimeStamp` should still exist in the WebIDL spec — until such time as there are no other specs referencing `DOMTimeStamp`, at which point we can be confident that we don’t need it in MDN any longer, and somebody can do the steps listed in https://github.com/mdn/content/issues/14667#issuecomment-1088097755

**Comment by hamishwillee** [comment]
I don't think we should change the URL, but we might add some context in https://developer.mozilla.org/en-US/docs/Web/API/DOMTimeStamp ?

For example a note 

> `DOMTimeStamp`  has been removed from the IDL in the linked specification, but is referenced in other specifications.  In the High performance timer specification `DOMTimeStamp` has been redefined as `EpochTimeStamp`.

**Comment by sideshowbarker** [comment]
> I don't think we should change the URL, but we might add some context in [developer.mozilla.org/en-US/docs/Web/API/DOMTimeStamp](https://developer.mozilla.org/en-US/docs/Web/API/DOMTimeStamp) ?
> 
> For example a note
> 
> > `DOMTimeStamp`  has been removed from the IDL in the linked specification, but is referenced in other specifications.  In the High performance timer specification `DOMTimeStamp` has been redefined as `EpochTimeStamp`.

Yes, adding that note would mitigate the problem and be sufficient for resolving this issue, I think

**Comment by hamishwillee** [comment]
Done in https://github.com/mdn/content/pull/14675
