### ISSUE TITLE
Issue with "border-left-color": Link to -moz-border-left-colors broken

### ISSUE THREAD

**Issue by simonvarey** [mdn/content#14748]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/border-left-color

#### What information was incorrect, unhelpful, or incomplete?

The link to `-moz-border-left-colors` under Firefox compatibility implementation notes is broken.

#### Specific section or headline?

Browser Compatibility

#### What did you expect to see?

A page for `-moz-border-left-colors`. Perhaps this should link to https://developer.mozilla.org/en-US/docs/Web/CSS/Mozilla_Extensions#b as there is no page for `-moz-border-left-colors` (and making a page for a deprecated property doesn't seem worth it) but I wasn't sure that was the right move.

#### Did you test this? If so, how?

Following the link.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/border-left-color`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/border-left-color
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/border-left-color/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks @simonvarey 

There are lots of broken links in the docs/BCD, created because eventually we hope they will be created. As you say though, it is unlikely that this one ever will be fixed, and I think it is useful to link to somewhere that shows it is deprecated.

Can you please [create a redirect](https://github.com/mdn/content#redirecting-a-document) to the location you suggested? 

The reason I suggest redirect over changing the link is that it is theoretically possible (though unlikely) that the doc might be created in future. In that case fixing the redirect is easier.

**Comment by simonvarey** [comment]
Redirect created! Thanks for the help @hamishwillee
