### ISSUE TITLE
Issue with "Base64": consider to add base62x 

### ISSUE THREAD

**Issue by wadelau** [mdn/content#14771]
MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Base64

#### What information was incorrect, unhelpful, or incomplete?

Base64 has a enhanced version from Base62x which has no-symbol in output. 

#### Specific section or headline?

[The "Unicode Problem"](https://developer.mozilla.org/en-US/docs/glossary/base64#the_unicode_problem) , it is considerable to replace Base64 with with Base62x as an alternative solution.  

#### What did you expect to see?

Add Base62x as an alternative for the Unicode problem. 

#### Did you test this? If so, how?

Yes, we have tested and deployed in some web applications.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/glossary/base64`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Base64
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/base64/index.md
* Last commit: https://github.com/mdn/content/commit/51721f92b2413f89f83633be8d0f3ccbde10411a
* Document last modified: 2022-04-02T03:33:57.000Z

</details>

**Comment by Josh-Cena** [comment]
Thanks for the suggestion! However, I don't think this encoding solves any practical issue that base64 cannot in principle remedy. After reading the paper, I have the following observations:

- Its motivation is weak: your examples of encoding formulae like "1 + 62 = 63" only encode each individual number instead of the string as a whole, which is jarring. The claim that "Both of these examples are hard to understand and not acceptable for deployment" is irrelevant because encoded data is not for human consumption. "Some symbols cause conflicts" is legitimate but that's why different "flavors" of base64 exist for different purposes, and `-`, `_`, `=` generally work well everywhere.
- Its worst-case length increase is much bigger than base62, and for no reason.
- To date, we haven't seen major adoption of base62x: the citation number is low, the repo doesn't have much traction. If we include this, there's no point to not include other encoding schemes like base62, but then this completely drives this glossary entry off-topic.

Base64 is already battle-tested and generally works well. I've seen little criticism of its utility. JS programmers enjoy the built-in `btoa` and `atob` functions. I personally don't see base62x being useful on the web, so I'll be closing this.
