### ISSUE TITLE
HTMLMediaElement deprecated properties

### ISSUE THREAD

**Issue by ashleedawg** [mdn/content#14892]
### MDN URL

/en-US/docs/Web/API/HTMLMediaElement

### What specific section or headline is this issue about?

Properties

### What information was incorrect, unhelpful, or incomplete?

List of properties needs to be updated to reflect deprecations.

### What did you expect to see?

For example, `HTMLMediaElement.controller` does not have a `🗑` trashcan icon even though following [it's link](https://developer.mozilla.org/docs/Web/API/HTMLMediaElement/controller) warns that the property is deprecated.

On the other hand, according to the chart, it's still supported by Safari... so if that's enough to count as "not deprecated" then perhaps the [deprecation notice](https://developer.mozilla.org/docs/Web/API/HTMLMediaElement/controller) should be removed/updated.

This probably also applies to other properties.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/htmlmediaelement`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlmediaelement/index.md
* Last commit: https://github.com/mdn/content/commit/f31cca642ae5a8f5c6ebb7d35bc692bf0afd79d2
* Document last modified: 2022-03-23T07:01:05.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks @ashleedawg 

Generally the compatibility table should be treated as the canonical place to check whether something is deprecated or not, but in this case it is wrong. I will fix that. 

FYI the information does get out of sync in the table, the page, the parent page and the sidebar (particularly the parent page). That's because each of those things is updated separately. We're looking at various ways of automating this so that the data comes from browser compatibility "first".

In any case, feel free to fix this kind of thing when you see it.
