### ISSUE TITLE
“Recording a media element” example logs obscure “NotFoundError: The object can not be found here” error

### ISSUE THREAD

**Issue by 89z** [mdn/content#15030]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API/Recording_a_media_element

### What information was incorrect, unhelpful, or incomplete?

NotFoundError: The object can not be found here.

### What did you expect to see?

Click the "Start Recording" button

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/mediastream_recording_api/recording_a_media_element`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API/Recording_a_media_element
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/mediastream_recording_api/recording_a_media_element/index.md
* Last commit: https://github.com/mdn/content/commit/ac7a7a70f78363ad8b1196e6a938a60bbb8952ff
* Document last modified: 2022-04-01T08:08:22.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing!

This example works fine for me in recent Firefox (101) and Chrome (100), on a MacBook. May I ask which browser+computer you are using?

**Comment by 89z** [comment]
I am using Firefox 88 with Windows.

It seems `captureStream` should work with Firefox 15 (2012):

https://developer.mozilla.org/docs/Web/API/HTMLMediaElement/captureStream

**Comment by 89z** [comment]
I think the problem is this code:

~~~js
navigator.mediaDevices.getUserMedia({
   video: true,
   audio: true
});
~~~

On my system, I get this:

~~~
Uncaught (in promise) DOMException: The object can not be found here.
~~~

I am on a regular computer, so I dont have a camera or microphone. I think its bad to assume a user has that, better would be to just use an actual video, like this:

https://webrtc.github.io/samples/src/video/chrome.webm

**Comment by sideshowbarker** [comment]
@89z Thanks much for raising this. It’s an interesting case, because I can’t recall seeing any `getUserMedia()` code examples anywhere (or even actual code) that’s written to gracefully handle the case where a system has no camera or microphone — or the camera or microphone have been completely disabled in the OS system settings — and report a useful message to the user (rather then just failing with that arcane _“NotFoundError: The object can not be found here”_ message).

I’ve raised #15038 with a fix. After that fix is merged, this issue will automatically be marked as resolved, and closed.

**Comment by 89z** [comment]
Thanks @sideshowbarker, you seem like a good dude.
