### ISSUE TITLE
Embracing consistency in mentioning variations of Variable Fonts in a text

### ISSUE THREAD

**Issue by lildeadprince** [mdn/content#15085]
### MDN URL

https://developer.mozilla.org/en-US/docs/web/CSS/font-variation-settings

### What information was incorrect, unhelpful, or incomplete?

Recently, while filing a typo-fix PR in the repo on the `font-stretch` page, I've also noticed that mentions of the variable font variation just go plainly in text.

First, I wanted to just wrap them in a `code` format, but then I've performed a search through all the docs to check is there actually any consistency around it already — "Maybe I'm wrong?"

### In code
||`wght`|`wdth`|`slnt`|`ital`|`opsz`|`GRAD`|`XHGT`||Total|
|-|-------|------|------|-----|------|-|-|-|-|
|'single'| 3| 4|1|1|2|2|0||13|
|"double"|0|0|0|0|0|0|2||2|

No other variables are mentioned in the code snippets.
_You can also notice an inconsistency in letter case: GRAD and XHGT are mentioned in capitals, which actually matters. Majority of fonts seem to follow the "caps for non-basic props" rule, so I guess it's up to a reader to find out about the variations available in their fonts._

### In text
||`wght`|`wdth`|`slnt`|`ital`|`opsz`|`GRAD`||Total|
|-|-------|------|------|-----|------|-|-|-|
|`"code with doubles"`|0|1|1|1|0|0||3|
|`code`|2|1|1|1|1|1||7|
|"double"|3|2|1|1|1|0||8|
|as plain text|1|0|1|0|0|0||2|

No other variations are mentioned in the text.

## In code
I'm not sure (didn't find a specific rule), but I guess we can change all quotes to `'single'` just to reduce discrepancy and not to confuse readers (double qoutes are only used with custom variations in the articles right now).

## In text

Here it looks more convoluted.

I'm thinking about the variations as 
- a part of the code, when mentioned using 4-character keyword;
- a text, when mentioned using actual name (weight, slant, etc.).

Therefore, I assume **all the 4-character mentions of a font variation should be treated as code and wrapped accordingly.**

#
Next about whether there should be also `"quotes"` used in addition to the `code` notation.
Here I'm still indecisive.

Reasons to use them:
- in a code variations are always used with quotes;
- reader will immediately understand what it is (as with the `function()` mentions)

Reasons not to use them:
- it unnecesarily pollutes the text;
- reader most often already knows what it is, because (compared to functions) variation names are quite limited.

Therefore **I'd personally try to pursue the non-quoted variation mentioning (i.e., `wght`) by default, with only using quotes in some excpetional cases,** where variation name may be confused with other code entity mentioned along the article (e.g., `grad` variation and Gradians angle measure are used in the same article). No such articles exsist to date, to my knowledge.

But I'm not sure what would fit MDN the best

### Do you have any supporting links, references, or citations?

Some codepen with some more available variations (also showcasing lowercase-named variations): https://codepen.io/leaverou/pen/vWLXYW

### Do you have anything more you want to share?

Granted a decision is made on the topic, I can provide a PR with according changes to font variation mentions, if that's necessary.

**Comment by Josh-Cena** [comment]
Thanks for the extensive study! It has been open for two years without further activity, so I'll assume that maintainers aren't interested in this work, unfortunately. Here's some more thought:

- In general we don't have "micro-consistency", that is telling people how to format one specific code entity. We found that this is not enforceable because people come from all backgrounds and not everyone reads or remembers the style guide.
- Quotes are a really minor part of the text and as you've realized it often neither helps nor helps with understanding. For example, JavaScript examples would also refer to string content sometimes with `"` and sometimes without—it's all up to the writer's discretion.
- We now use Prettier and it formats all CSS strings with double quotes.

I understand that it may look non-ideal when you compare across lots of occurrences, but when you put it in the context of the gigantic MDN documentation corpus, it really is just a tiny inconvenience that doesn't really both readers.
