### ISSUE TITLE
Intl.ListFormat() constructor article: Instructions for object containing style and type are combative with the example

### ISSUE THREAD

**Issue by StephenLespron** [mdn/content#15167]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat/ListFormat

### What specific section or headline is this issue about?

Parameters

### What information was incorrect, unhelpful, or incomplete?

The length of the formatted message. Possible values are: "long" (default, e.g., "A, B, and C"); "short" (e.g., "A, B, C"), or "narrow" (e.g., "A B C"). **When style is "short" or "narrow", "unit" is the only allowed value for the type option.**

and this example

const list = ['Motorcycle', 'Bus', 'Car'];

 console.log(new Intl.ListFormat('en-GB', { style: 'long', type: 'conjunction' }).format(list));
// > Motorcycle, Bus and Car

 **console.log(new Intl.ListFormat('en-GB', { style: 'short', type: 'disjunction' }).format(list));
// > Motorcycle, Bus or Car**

 console.log(new Intl.ListFormat('en-GB', { style: 'narrow', type: 'unit' }).format(list));
// > Motorcycle Bus Car

### What did you expect to see?

The example shows the style 'short' will give a list that excludes the Oxford comma while 'long' will include the comma. This is the preferred behavior, however, it seems the code actually works as the parameters suggest in that 'short' only works with the type 'unit'. As it currently stands, you cannot generate a list formatted as "one, two and three". The only three outputs possible are:

"one, two, and/or three"
"one, two, three"
"one two three"

### Do you have anything more you want to share?

Use the formatter with all 9 combinations and see the variety of outputs. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/intl/listformat/listformat`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat/ListFormat
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/intl/listformat/listformat/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #15191 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.

The statement _“When `style` is "`short`" or "`narrow`", "`unit`" is the only allowed value for the type option”_ — which doesn’t align with the spec nor with implementations (that wording/restriction was in the original proposal but ultimately didn’t make its way into the spec. So #15191 removes it.

> As it currently stands, you cannot generate a list formatted as "one, two and three". The only three outputs possible are:
> 
> "one, two, and/or three"
> "one, two, three"
> "one two three"

You can get `"one, two and three"` by doing the following, right?

```js
 console.log(new Intl.ListFormat('en-GB', { style: 'long' }).format(["one", "two", "three″"]))
```

Specifically, you need to use `en-GB` rather than `en-US` or just `en`.

But if you use `en-US` then there is no way to get `"one, two and three"` — because the `en-US` locale implies use of the Oxford comma, and it’s not separately configurable.

For some background, see https://unicode-org.atlassian.net/browse/CLDR-11648 and https://github.com/tc39/proposal-intl-list-format/issues/31
