### ISSUE TITLE
repeat() CSS Function Documentation

### ISSUE THREAD

**Issue by S-Bowen** [mdn/content#15212]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/repeat

### What specific section or headline is this issue about?

Main section, code block

### What information was incorrect, unhelpful, or incomplete?

Apologies in advance if the page reads clearly to others, I'm on the autism spectrum and struggle with understanding implied contexts!

---

I'm having difficulty understanding what is meant to be conveyed by the code block under the main page heading (see snippet below):
```
/* <track-repeat> values */
repeat(4, 1fr)
repeat(4, [col-start] 250px [col-end])
repeat(4, [col-start] 60% [col-end])
repeat(4, [col-start] 1fr [col-end])
repeat(4, [col-start] min-content [col-end])
repeat(4, [col-start] max-content [col-end])
repeat(4, [col-start] auto [col-end])
repeat(4, [col-start] minmax(100px, 1fr) [col-end])
repeat(4, [col-start] fit-content(200px) [col-end])
repeat(4, 10px [col-start] 30% [col-middle] auto [col-end])
repeat(4, [col-start] min-content [col-middle] max-content [col-end])
```

Specifically, I am confused as to:
1. What the section titles `/* <track-repeat> values */`, `/* <auto-repeat> values */`, and `/* <fixed-repeat> values */` are referring to & how to learn more about those different contexts.
2. What the bracketed content within the `repeat` lines mean (e.g. `[col-start]`) - to me, it's unclear whether they are placeholder text for input values, are part of the input given to the function, or whether they are meant as inline documentation for the reader to clarify preceding or following values.

Thing I was confused about from this article but figured out independently:
1. What "track list" means ([Basic Concepts of grid layout#Grid tracks](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Basic_Concepts_of_Grid_Layout#grid_tracks) helped significantly)

### What did you expect to see?

I expected clear connections between content and labels & glossary/ learn-more links for keywords used in the article.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/repeat`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/repeat
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/repeat/index.md
* Last commit: https://github.com/mdn/content/commit/56da604e4fc9c926015751a990496f0284bf4e41
* Document last modified: 2022-03-18T17:18:24.000Z

</details>

**Comment by wbamberg** [comment]
> Apologies in advance if the page reads clearly to others

If something is unclear to you it's extremely likely it will be unclear to lots of other people, so we appreciate you taking the time to file an issue about it.

And I agree, this is unclear to me too!

> What the section titles `/* <track-repeat> values */`, `/* <auto-repeat> values */`, and `/* <fixed-repeat> values */` are referring to & how to learn more about those different contexts.

The comments like `/* <track-repeat> values */` are supposed to refer to the different syntax forms that this notation can take. [The spec is much more helpful here](https://drafts.csswg.org/css-grid/#repeat-notation):

> Thus the precise syntax of the repeat() notation has several forms:> 
>
>     <track-repeat> = repeat( [ <integer [1,∞]> ] , [ <line-names>? <track-size> ]+ <line-names>? )
>     <auto-repeat>  = repeat( [ auto-fill | auto-fit ] , [ <line-names>? <fixed-size> ]+ <line-names>? )
>     <fixed-repeat> = repeat( [ <integer [1,∞]> ] , [ <line-names>? <fixed-size> ]+ <line-names>? )
>     <name-repeat> = repeat( [ <integer [1,∞]> | auto-fill ], <line-names>+)> 
>
> The `<track-repeat>` variant can represent the repetition of any `<track-size>`, but is limited to a fixed number of repetitions.
>
> The `<auto-repeat>` variant can repeat automatically to fill a space, but requires definite track sizes so that the number of repetitions can be calculated. It can only appear once in the track list, but the same track list can also contain `<fixed-repeat>`s. 
>
> The `<name-repeat>` variant is for adding line names to subgrids. It can only be used with the subgrid keyword and cannot specify track sizes, only line names.

So this page ought to list these different forms in the "Syntax" section, so the comments in that code block have something to refer to. For example, we have something roughly analogous in the [`flex` page](https://developer.mozilla.org/en-US/docs/Web/CSS/flex), where the comment says things like "/* One value syntax */" but then we explain below what that means.

> What the bracketed content within the repeat lines mean (e.g. [col-start]) 

I think `col-start` here is an example line name (so it could be any identifier). I think it's in square brackets because the line name is optional in the syntax.

One confusing thing here is that the syntax in the spec, like `<track-repeat> = repeat( [ <integer [1,∞]> ] , [ <line-names>? <track-size> ]+ <line-names>? )` is a [formal syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax) in which the elements have a precise meaning (for example, the question mark after `<line-names>` means that it's optional). We list this formal syntax for CSS properties (e.g. [`flex`](https://developer.mozilla.org/en-US/docs/Web/CSS/flex#formal_syntax)) but usually don't for functions.

But the code block in the page should really just be examples, so it should not use things like `[]` to indicate optionality, when there's no real way to tell that this is what is meant. It would perhaps be better just to list out all the options, like:

```
/* <track-repeat> values */
repeat(4, 1fr)
repeat(4, 250px)
repeat(4, col-start 250px)
repeat(4, 250px col-end)
repeat(4, col-start 250px col-end)
```
...although I think it would be impractical to list all the permutations.

**Comment by wbamberg** [comment]
I was totally wrong about the square brackets round things like `[col-start]`. It seems that they are part of the syntax.
