### ISSUE TITLE
Issue with "word-break": …

### ISSUE THREAD

**Issue by ramyareye** [mdn/content#1534]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/word-break
also here: https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap

#### What information was incorrect, unhelpful, or incomplete?

I was trying to break with break-words also having a break-all rule. Searched and found the solution [here](https://stackoverflow.com/a/48830291/3197080) not in MDN

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/word-break`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/word-break
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/css/word-break/index.html
* Report started: 2021-01-20T18:38:23.074Z

</details>

**Comment by rachelandrew** [comment]
Hi @ramyareye I'm not too sure what the problem was you were having that wasn't solved - you have mentioned the solution you found, but what were you searching for?

The `word-break` property has a `break-all` value, but you have linked to that page so I'm assuming you found it.

I recently put together a document on the different ways of breaking text, it's here: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Text/Wrapping_Text

**Comment by ramyareye** [comment]
@rachelandrew thanks as you see in link I needed to use break-words with hyphens
maybe we can add it  in docs as an related example

**Comment by Ryuno-Ki** [comment]
Would that be `hyphens: auto;` perhaps?

**Comment by ramyareye** [comment]
yes, also `hyphens: manual;`
