### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Dean-NC** [mdn/content#1541]
On the page:
https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API/Drag_operations

On the left-side nav menu under the "Events" section, the link "Drag Exit" is broken; it points to:
https://developer.mozilla.org/en-US/docs/Web/API/Document/dragexit_event

**Comment by escattone** [comment]
@Dean-NC Thank you. Yes, that document has not yet been written.

**Comment by Ryuno-Ki** [comment]
@chrisdavidmills Can we have a label to mark issues which highlight missing documents?

**Comment by chrisdavidmills** [comment]
@Ryuno-Ki I think this could be useful, but I'm a bit concerned about the term "missing document", because to me it implies that there's an expectation that we should have created it, whereas in reality we just do what we've got time for, and there are lots of things not written. I dunno, after writing it that sounds really pedantic, but that's how I feel ;-)

I think there are a few cases we could add labels for:

* broken-link-external: The external doc we want to link to exists, but the link href is incorrect. It'd be nice if someone could fix it.
* broken-link-internal: The internal doc we want to link to exists, but the link href is incorrect. It'd be nice if someone could fix it.
* document-not-written: The linked document does not exist, and it'd be nice to if some could add it if they could find the time.

I think these cases are worth calling out, although I'm not 100% taken with the actual wording.

Thoughts?

**Comment by Ryuno-Ki** [comment]
:100:

Let's do this!

> because to me it implies that there's an expectation that we should have created it, whereas in reality we just do what we've got time for, and there are lots of things not written

… but … but … MDN is the most comprehensive set of documentation (in an approachable manner) I'm aware of on the Interwebz!
You sure must have written _everything_!!1

(I'm kidding. Thanks for sharing your thoughts. I haven't considered it this way before)

**Comment by hamishwillee** [comment]
Just went [around this here](https://github.com/mdn/yari/issues/2289).  

FYI only
- the link checker currently spots broken internal links and internal anchors. I think the broken link internal that it knows about is fixed as a flaw (and would be nice if highlighted too). 
- The highlighting of missing docs seems to be partially implemented - i.e. you can see it in  https://developer.allizom.org/en-US/docs/Web/JavaScript/Reference/Global_Objects#control_abstraction_objects but not in many other places where docs are missing.
- External link checking will be done as a flaw check but that is currently broken (known issues). 

@chrisdavidmills Upshot, there may be issues here, but IMO much better fixed by toolchain rather than something we fix in content. 

Perhaps @peterbe could comment on why [some](https://developer.allizom.org/en-US/docs/Web/JavaScript/Reference/Global_Objects#control_abstraction_objects) "doc not written" links are highlighted as docs required 
![image](https://user-images.githubusercontent.com/5368500/105648175-34794900-5efe-11eb-8f4b-4e415d71a17c.png)


and some not? 

![image](https://user-images.githubusercontent.com/5368500/105648208-67bbd800-5efe-11eb-9689-8d3b1ed053d3.png)

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills Upshot, there may be issues here, but IMO much better fixed by toolchain rather than something we fix in content.

I agree entirely, but even when running optimally, the toolchain will only really be able to fix broken internal links reliably. So I think these labels will be usefully, some of them for a long time. I'll add them and see how we go with them. We can always change things up if they are not working for us.

**Comment by chrisdavidmills** [comment]
> (I'm kidding. Thanks for sharing your thoughts. I haven't considered it this way before)

Re-reading it this morning, I'm not convinced I really have a point here. More needless pedantry, or a real concern? ;-)

I'll create the labels anyhow.

**Comment by peterbe** [comment]
> Perhaps @peterbe could comment on why [some](https://developer.allizom.org/en-US/docs/Web/JavaScript/Reference/Global_Objects#control_abstraction_objects) "doc not written" links are highlighted as docs required

The `broken_link` flaw detection stuff happens on the HTML *after* the Kumascript macros have done their stuff. 
So what the flaw detection code gets is this:
```html
<ul>
 <li><a href="/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise"><code>Promise</code></a></li>
 <li><a href="/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator"><code>Generator</code></a></li>
 <li><a href="/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction"><code>GeneratorFunction</code></a></li>
 <li><a href="/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncFunction"><code>AsyncFunction</code></a></li>
 <li><a class="page-not-created" title="The documentation about this has not yet been written; please consider contributing!" data-flaw-src="{{JSxRef(&quot;Global_Objects/AsyncGenerator&quot;, &quot;AsyncGenerator&quot;)}}"><code>AsyncGenerator</code></a></li>
 <li><a class="page-not-created" title="The documentation about this has not yet been written; please consider contributing!" data-flaw-src="{{JSxRef(&quot;Global_Objects/AsyncGeneratorFunction&quot;, &quot;AsyncGeneratorFunction&quot;)}}"><code>AsyncGeneratorFunction</code></a></li>
</ul>
```

(I know it's confusing that the Kumascript macro expansion does its own flaw stuff, and even injects `data-flaw-src="..."` attributes)

The `broken_link` flaw checker can only scrutinize things like:
```html
<a href=/inter/nal/links>
or
<a href=#anchor>
or
<a href=/inter/nal/links#anchor>
```

So there's a difference and its subtle. The `JSxRef` is smart in that it can help you highlight which pages haven't been created. It's the authors problem that you shouldn't be using `{{JSxRef('blabla')}}` if the page `blabla` hasn't been created. But it's arguably better, for a reader, to know what methods or properties or whatever are available even if they haven't all be written about yet. 

But it does help you highlight where the writers have missing documents. See:
<img width="1144" alt="Screen Shot 2021-01-27 at 8 57 31 AM" src="https://user-images.githubusercontent.com/26739/106001238-b479ed00-607d-11eb-8565-3cf9b86deb8e.png">

This can be improved. I.e. it's weird that it's called `MacroBrokenLinkError`. It should arguably be called "NotYetCreatedError` :)
But mind you, they might actually be *broken* because they *used* to work and now they no longer do.

**Comment by dontcallmedom** [comment]
hmm… there is no such a thing as a `dragexit` event defined [in the HTML spec](https://html.spec.whatwg.org/multipage/dnd.html#event-dnd-dragend); given that `dragexit` is only mentioned as a link in the sidebar, it looks like the correct fix is to remove the link, not to create new content.

**Comment by Dean-NC** [comment]
@dontcallmedom Yes, it's confusing, but it looks the spec did have this event at one time, and MDN also had a dedicated page here: https://developer.mozilla.org/en-US/docs/Web/Events/dragexit.
Maybe it started out in the spec and then got removed.

But some browsers did have the event:
https://stackoverflow.com/questions/42775095/dragexit-vs-dragleave-which-should-be-used
https://chrissainty.com/investigating-drag-and-drop-with-blazor

**Comment by dontcallmedom** [comment]
Nowadays, it's only implemented in Firefox, with an [open bug for removing it](https://bugzilla.mozilla.org/show_bug.cgi?id=1635018) following its [removal from the spec](https://github.com/whatwg/html/pull/5809). So it's feels like scrubbing it from MDN remains the best path forward.

**Comment by Dean-NC** [comment]
@dontcallmedom You're correct, good catch. I verified Chrome and Edge don't have this event anymore.
