### ISSUE TITLE
primitives?

### ISSUE THREAD

**Issue by shyamraosmile** [mdn/content#157]
# Content Issue

- [x] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ ] Correction or update

# URL of page you are seeing the problem on:

# Details

hello sir,
i hope your doing well.
        i read the content of your website about primitives. 
 there is a sentence that primitives has no methods...
but string has metods like Toupper(),Tolower()..
then what are they?

**Comment by sideshowbarker** [comment]
What’s the MDN article which has the sentence you’re asking about?

Is it the https://developer.mozilla.org/en-US/docs/Glossary/Primitive article? That article says this:

> In JavaScript, a primitive (primitive value, primitive data type) is data that is not an object and has no methods.

If so, that statement is accurate — because while `String` objects have methods, string primitives don’t.

However, also note the following:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#String_primitives_and_String_objects

> Note that JavaScript distinguishes between <code>String</code> objects and <a href="/en-US/docs/Glossary/Primitive">primitive string</a> values. (The same is true of <a href="/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean"><code>Boolean</code></a> and <a href="/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number"><code>Numbers</code></a>.)
> …
> JavaScript automatically converts primitives to <code>String</code> objects, so that it's possible to use <code>String</code> object methods for primitive strings. In contexts where a method is to be invoked on a primitive string or a property lookup occurs, JavaScript will automatically wrap the string primitive and call the method or perform the property lookup.

So that explanation in the https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String article seems quite clear — but IMHO it’s too much information to also add to the https://developer.mozilla.org/en-US/docs/Glossary/Primitive (assuming that’s the article this issue is about).

**Comment by sideshowbarker** [comment]
Closing for lack of response, and resolved by https://github.com/mdn/content/issues/157#issuecomment-740437041
