### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/bindFramebuffer

### ISSUE THREAD

**Issue by EricPendergast** [mdn/content#1578]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The documentation page for `gl.bindFramebuffer` ([here](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/bindFramebuffer)) does not make it clear that in order to bind the default framebuffer (to render to the screen), you would do `gl.bindFramebuffer(gl.FRAMEBUFFER, null)`. This is an important use case of this function, and it should be documented.

**Comment by dominiccooney** [comment]
There's this bit: "If framebuffer is null, then the canvas (which has no WebGLFramebuffer object) is bound." Sounds like that needs to be more explicit.

One problem with referring to drawing to the screen is you might have an OffscreenCanvas.

**Comment by himanshugarg** [comment]
This looks like a low hanging fruit but still out of my reach. Any hints or links that might help?

**Comment by sideshowbarker** [comment]
@monfera I see that you edited this page a few months back. Any chance you might be interested in taking a shot a writing up a PR that would resolve this?

**Comment by monfera** [comment]
@sideshowbarker Sure thing, happy to draft this small change

**Comment by sideshowbarker** [comment]
> @sideshowbarker Sure thing, happy to draft this small change

🎉 Thanks much — I’ve gone ahead and assigned you

**Comment by Rumyra** [comment]
@monfera do you have a status update for this? If you're unable to make the change we'll un-assign you from the issue 👍

**Comment by monfera** [comment]
Hi @Rumyra I'm back from vacation, can do it now

**Comment by monfera** [comment]
I pushed the PR ^ 

I'm not currently clear on this apparent, more general contradiction:
1. The WebGL2 spec, for example [here](https://registry.khronos.org/webgl/specs/latest/2.0/#3.7.1) for `bindFrameBuffer`, uses question mark in the parameter list to indicate optionality(?). I'd think optionality means that it's OK to either omit the parameter, or supply `undefined`, but it wouldn't admit other values such as `null`, zero or general falsey values. At least I haven't run across a clarification in the WebGL2 spec
2. However, the WebGL2 spec draws sporadic, unexplained relationship between some question marked parameters and null (or zero), eg. "If no WebGLTexture is bound (e.g., passing null or 0 to bindTexture)" [here](https://registry.khronos.org/webgl/specs/latest/2.0/#3.7.6)
3. In the most common browsers (current Chrome, Safari, Firefox), the `framebuffer` arg passed to `bindFramebuffer` can be `null` or `undefined`, but it can't be zero, and it can't be omitted, otherwise they throw an error. The TypeScript `lib.dom.d.ts` type doc file also asks for a `null` (it doesn't even allow an explicitly passed `undefined`, though browsers work with it too) 

Can someone point to a reference that clarifies the meaning of the (to me, apparently unspecified) `?` question mark postfixed parameters? Depending on the answer, further changes might be needed to this and other pages

**Comment by sideshowbarker** [comment]
@greggman Apologies in advance for pinging you out of the blue, but having learned most of what I know about WebGL from reading your Stack Overflow answers, I thought you might be able to help answer the question in https://github.com/mdn/content/issues/1578#issuecomment-1220947377.

**Comment by greggman** [comment]
The meaning of ? is specified in the WebIDL spec. `Type?` means you can pass `Type` or `null`

https://webidl.spec.whatwg.org/#es-nullable-type

`bindFramebuffer` requires 2 parameters and the 2nd parameter can either be a `WebGLFramebuffer` or `null`.  JavaScript will convert `undefined` to null but not (`0`, `false`, `""`, etc...)  I'm guessing that's defined in the ECMAScript spec but I'm too lazy to go look

passing `null` to `gl.bindFramebuffer` binds the canvas. Even for an OffscreenCanvas, an OffscreenCanvas is still a canvas, hence the name Offscreen**Canvas**

I'd suggest the docs should start with the case of passing a framebuffer because the purpose of calling `bindFramebuffer` is to "bind a framebuffer". The fact that passing `null` rebinds the canvas is important there'd be no reason to ever call `gl.bindFramebuffer(??, null)` if you didn't first bind something else.

If it's not clear what's happening maybe [this diagram](https://webgl2fundamentals.org/webgl/lessons/resources/webgl-state-diagram.html?exampleId=draw-cube-on-cube) will help

**Comment by monfera** [comment]
Thank you @greggman, I'll add a PR with the kind of reordering and minor wordsmithing in the doc based on your comments

**Comment by Rumyra** [comment]
Thank you @sideshowbarker @monfera and @greggman !

**Comment by bsmth** [comment]
Thanks all for the coordination on this, it looks like I can close the issue 🙌🏻 
If I've missed something, feel free to comment or reopen. 
Thank you :)
