### ISSUE TITLE
Add Codepen liks to Introduction to HTML getting started assessments

### ISSUE THREAD

**Issue by schalkneethling** [mdn/content#15928]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Test_your_skills:_HTML_text_basics

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Test_your_skills:_HTML_text_basics

### What information was incorrect, unhelpful, or incomplete?

Adding links to MDN Web Docs Codepen starter pens.

### What did you expect to see?

N/A

**Comment by wbamberg** [comment]
Is this issue part of a bigger project? I'm concerned that this is adding another place to keep the sample code in sync. It's already in two places: the page and a separate GitHub repo. It looks like this will add a third copy to maintain, in CodePen, where we won't have the ability to file or track PRs, view history, run CI tooling for consistent formatting, or any of those other things.

**Comment by teoli2003** [comment]
I don't believe we should create additional codepens. cc/ @rumyra here.

**Comment by schalkneethling** [comment]
I run into this a lot on the Learn Discourse platform, where learners are unsure how to use these tools and share their work. As a result, they paste the code into the Discourse thread, making it hard for people to review and help with the assessments. Providing them with a link to a starter Codepen and a short explanation of how to use it makes this much easier for everyone involved.

Another option could be, as part of the repo cleanup, to set these up in such a way that we can simply connect the repos to Codesandbox.io - That way, we can link to the sandbox, and it will pull the latest from the repository.

**Comment by wbamberg** [comment]
Yeah, I appreciate that it is confusing, especially with the interactive/test your skills/assessments bits. I often don't understand the intention in learn pages, and they're often not very consistent in terms of how they show start/end points.

But I do think it's important to update it carefully and in an organized way, or we will make it worse rather than better. I have spent a bunch if time updating all the JS modules earlier this year and I can say it's hard to update code samples consistently across the two places they are currently kept, and I really don't want to add another copy.

So I'd like an update to:
- be planned and resourced, so we know we can do it across the entire area, rather than end up with something half-done
- reduce (preferably) the number of moving parts in the infra, and definitely not increase them

At the moment we often use these hacky live samples for this (like the one here: https://developer.mozilla.org/en-US/docs/Learn/Forms/Test_your_skills:_Advanced_styling#advanced_form_styling_1 ) . These are bad in a variety of ways, and if we could replace them with a codepen, that would be great. But I think it's critical for the codepen's source to come from a GitHub repo, either mdn/content or mdn/learning-area. Ideally we'd only have mdn/learning-area and power everything from there.

I don't know if you can plug a GitHub repo into CodePen, but I saw Codesandbox.io can. But you can power a CodePen from code in the page, because that's what https://wbamberg.github.io/codepen-demo/demo.html is doing.

For a more limited project: if we could just replace the EmbedLiveSample hacks with embedded pens that were initialized from code in the page, that would be a substantial win IMO.

Also cc @mikoMK who might have opinions here :).

**Comment by mikoMK** [comment]
> Also cc @mikoMK who might have opinions here :).

Thanks! Indeed, I have some opinions :-)

Schalk is right about a lot of learners pasting code directly into Discourse. What I'm not sure about is what the reasons are: Not understanding the instructions? Unwillingness to create another account (e. g. CodePen)? Avoiding additional work after solving the exercise in the live sample or locally?
What makes this problem bigger is the fact that we often have two versions of the given code: A complete version to download (or use in an online editor) and a special version we use in the live sample where some code is hidden from the learners. See for example: https://github.com/mdn/css-examples/blob/main/learn/tasks/grid

Generally, I think integrating an online code editor would be a major improvement for the learners workflow and a chance to simplify our code base. When choosing the right online code editor for MDN, these are the points to consider in my opinion (with decreasing importance):
* Are we able to maintain a single code base?
* Can a learner create a link to their (forked) solution without creating an account?
* How are additional files like images handled when a learner forks the code? (See below)
* Can the code in the embedded editor be edited directly on MDN or do you need to open it in its own tab to edit?

Another thing to consider when redesigning live code samples: How to handle embedded images? A lot of learners struggle with the relative paths. They put the downloaded code on CodePen and are surprised that the images aren't there. Then, they either have to find the absolute paths via GitHub or use a code editor that allows file upload or they just post their exercise with broken images. As you may guess, the last option is the most common.

I hope I could give you some additional insights.

By the way: Thanks for mentioning me in the Q1 impact report. It made my day when I suddenly saw my name while reading 😍
