### ISSUE TITLE
Host name is not defined in file

### ISSUE THREAD

**Issue by vipul2774** [mdn/content#1593]
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/development_environment#adding_dependencies

in code of step 5, hostname is not defined and saying to run script and test it on http://127.0.0.1:8000 but it will not work because host is not defined.

**Comment by hamishwillee** [comment]
It does not need to define the host because _by default_ it uses the localhost address (i.e. 127.0.0.1 ).
This works - I have tested it many times. If you tried it and it does not work, then I suggest you start by comparing your code to https://github.com/mdn/express-locallibrary-tutorial

Closing, as I know this is correct. Reopen with additional information - e.g. console output, pointer to your code on github etc. if needed.
