### ISSUE TITLE
Misleading text about srcset attribute

### ISSUE THREAD

**Issue by and3k5** [mdn/content#16136]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/srcset

### What specific section or headline is this issue about?

#value

### What information was incorrect, unhelpful, or incomplete?

To indicate that the image resource specified by the image candidate string should be used when the image is being rendered with a particular width in pixels, provide a width descriptor comprised the number giving that width in pixels followed by the lower case letter "w". **_For example, to provide an image resource to be used when the renderer needs a 450 pixel wide image, use the width descriptor string 450w. The specified width must be a positive, non-zero, integer, and must match the intrinsic width of the referenced image._**

### What did you expect to see?

Some text that would describe a more practical example. The text (set with bold) can give the wrong idea about how to use the `srcset` attribute.

The thing about the "width descriptor" is that it doesn't care about the actual rendered width of the image. The rule seems more to specify the width of the whole page than the actual rendered width of the image.

This is unless you specify the `sizes` attribute. Then you can specify a media condition followed by which width of the image you want to display. But this means, that it's possible to make rules about screen sizes, not rules to the actual rendered image size. 

The text can be misleading making people think that the `srcset` is for network optimization in general when it actually (more or less) just seems more relevant for responsiveness.

A practical way of proving this is by the following.
```html
<style>
    img {
        width: 50px;
    }
</style>
<img src="https://placehold.jp/50x50.png" 
     srcset="https://placehold.jp/150x150.png 50w,
             https://placehold.jp/150x150.png 150w,
             https://placehold.jp/2000x2000.png">
```
[View it on jsfiddle](https://jsfiddle.net/eL68vzns/)

This very simple example will show a image that won't be wider than 50px at any time. But when this sample is viewed in a browser where the page is more than 150px wide, the 2000 x 2000 image will be the current source.
This has been tested on both Chrome 101 and Firefox 100.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/htmlimageelement/srcset`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/srcset
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlimageelement/srcset/index.md
* Last commit: https://github.com/mdn/content/commit/754920839bd673d5203e08b6e85f2572b6d86137
* Document last modified: 2022-05-07T03:03:53.000Z

</details>

**Comment by bsmth** [comment]
Hi @and3k5, thanks a lot for raising this one. Would you like to open a PR that includes your suggested changes?

**Comment by tlylt** [comment]
Hi @and3k5, thank you for this issue that led me down a rabbit hole of `srcset` 😂

First of all, I would like to highlight this [point ](https://html.spec.whatwg.org/multipage/embedded-content.html#attr-img-srcset:~:text=If%20the%20srcset%20attribute%20is%20present%20and%20has%20any%20image%20candidate%20strings%20using%20a%20width%20descriptor%2C%20the%20sizes%20attribute%20must%20also%20be%20present%2C%20and%20is%20a%20sizes%20attribute.%20The%20sizes%20attribute%20contributes%20the%20source%20size%20to%20the%20source%20set%20(if%20no%20source%20element%20was%20selected).)  in the HTML specs:
> If the [srcset](https://html.spec.whatwg.org/multipage/embedded-content.html#attr-img-srcset) attribute is present and has any [image candidate strings](https://html.spec.whatwg.org/multipage/images.html#image-candidate-string) using a [width descriptor](https://html.spec.whatwg.org/multipage/images.html#width-descriptor), the sizes attribute must also be present, and is a [sizes attribute](https://html.spec.whatwg.org/multipage/images.html#sizes-attribute). The [sizes](https://html.spec.whatwg.org/multipage/embedded-content.html#attr-img-sizes) attribute contributes the [source size](https://html.spec.whatwg.org/multipage/images.html#source-size-2) to the [source set](https://html.spec.whatwg.org/multipage/images.html#source-set) (if no [source](https://html.spec.whatwg.org/multipage/embedded-content.html#the-source-element) element was selected).

So when you said that:
> This is unless you specify the sizes attribute. 

It's expected that developers **should** specify the sizes attribute if srcset with width descriptor is used!

---

Next, as to why:
> The thing about the "width descriptor" is that it doesn't care about the actual rendered width of the image. The rule seems more to specify the width of the whole page than the actual rendered width of the image.

This is actually because of the browser implementation, which defaults the sizes attribute to `100vw` if not specified. This effectively says that the image will take up "the width of the whole page" (which in this case, is the same as "the actual rendered width of the image", at least that's what was told to the browser)... and hence your observation.

---

Lastly, to your point that:
> The text can be misleading making people think that the srcset is for network optimization in general when it actually (more or less) just seems more relevant for responsiveness.

Well, I think it depends on how you define "responsiveness'. From MDN, ["Responsive Web Design"](https://developer.mozilla.org/en-US/docs/Glossary/Responsive_web_design) is:
> a Web development concept focusing on **making sites look and behave optimally** on all personal computing devices, from desktop to mobile.

To me, both network optimization and proper display are part of responsiveness.
And arguably, srcset (+ sizes) does help to optimize the network calls as the browser may intelligently choose a more suitable and smaller sized image.

---

If you are interested, the following resources go in depth about this topic:
- (this is actually on MDN): [Responsive images](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images)
- and the articles in the "see also" section of the above

---

### Summary (What's next)

I want to emphasize that the long response above is not meant to criticize what you have raised, I just want to add the context so that we all learn more about this topic (please correct me if anything mentioned above is wrong). And here's what I am going to do to help make this topic less confusing to others:
- follow-up with the HTML spec's [issue](https://github.com/whatwg/html/issues/7116) to hopefully help add a warning that mentions the browser behavior of making "sizes" equal to "100vw"
- raise a PR in the MDN repo to add a note that "the sizes attribute must also be present" when srcset with width descriptor is used.

Cheers!
