### ISSUE TITLE
Disable IDBMutableFile by default

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#16151]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

Again looks like check docs, bcd & rel ntoe

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1764771

**Comment by hamishwillee** [comment]
This change puts [IDBMutableFile](https://developer.mozilla.org/en-US/docs/Web/API/IDBMutableFile), [IDBFileHandle](https://developer.mozilla.org/en-US/docs/Web/API/IDBFileHandle) , [IDBFileRequest](https://developer.mozilla.org/en-US/docs/Web/API/IDBFileRequest) and the method [IDBDatabase.createMutableFile()](https://developer.mozilla.org/en-US/docs/Web/API/IDBDatabase#idbdatabase.createmutablefile) behind the preference `dom.fileHandle.enabled`.
None of them are in BCD and the method is undocumented (but linked).

No point creating BCD for this case since the plan is to delete them. I'll add a release note. The pages already have a note about them being deprecated. I'll add the compatibility info into that, and add a note in the compatibility section.

Status:

- [ ] BCD - no doing - no point for removed/deprecated non-standard interface.
- [ ] Docs
- [ ] Release note
- [ ] dev-doc-complete
