### ISSUE TITLE
storage.sync docs expansion

### ISSUE THREAD

**Issue by swpease** [mdn/content#1622]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

I think that it would be useful to expand the `storage.sync` docs. I recently received a critical review for an add-on: 

> The sync feature is broken. I had 12 hours on desktop and 8 hours on laptop. It became 8 hours in both device after sync!

I want to address it, but cannot (quickly) find an explanation of things like:
  - Is syncing automatic, or does a user click something?
  - Is the sync-origin computer's data used to replace the other computer's data? Does it only overwrite shared keys? Something else?

I've been looking through sync-related pages on wiki.mozilla.org, but am having difficult figuring out what's what and what's up-to-date. It looks like syncing is either done by the user, or automatically periodically with certain triggers like password storage?

I presume I cannot customize the sync write behavior, and that the best decision is probably to just switch from sync storage to local storage to avoid accidental overwrites.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync

**Comment by rebloor** [comment]
@mhammond are you able to help with any information to answer these queries?

**Comment by mhammond** [comment]
Sorry for the delay here. The syncing of addon data is done at the same rate as all other sync data. In general, this will be every 10 minutes or whenever the user selects "sync now". For webext storage, the last device to update a particular key will generally win, although we do merge data where we can.

> I presume I cannot customize the sync write behavior, and that the best decision is probably to just switch from sync storage to local storage to avoid accidental overwrites.

It's certainly true that if you don't need data synced between devices you should use localstorage. If you do want data synced then obviously localstorage is not an option. So these options really are mutually exclusive.

FWIW, the sync implementation is at https://github.com/mozilla/application-services/tree/main/components/webext-storage/src/sync

**Comment by rebloor** [comment]
Thanks for getting back to me, and sorry for the delay in responding. With regard to:

> The sync feature is broken. I had 12 hours on desktop and 8 hours on laptop. It became 8 hours in both device after sync!

Do you have any guidance on how sync works across multiple devices and deals with precedence/conflicts?

**Comment by mhammond** [comment]
In general, each sync does something like:

1) look at the what's actually on the server now, and compare it to what was on the server last time we checked. Any differences must be changes made by different devices so are applied locally.
2) any changes that were made by us since the last sync are sent up to the server.
* If (1) and (2) have conflicting changes (ie, we saw some other device make a change, but we also made a local change with different values) we will tend to drop the local change and take the incoming change.
* 

> The sync feature is broken. I had 12 hours on desktop and 8 hours on laptop. It became 8 hours in both device after sync!

I've no idea what these times relate to, but if the desktop changed it to 12, then we'd expect both the desktop and laptop to have 12. Later, if the laptop changed it to 8, then we'd expect both to end up on 8. It's certainly the intent that all devices end up with the same value - that's the point.

**Comment by mhammond** [comment]
Do you listen for "change" events? I can imagine the following scenario:
* Desktop wrote 8 hours, synced, went to sleep or shutdown.
* Laptop wrote 12 hours, synced.
* Desktop started, but before first sync the user started a stream, read "8 hours" and used it.
* Desktop synced - saw incoming "12 hours" but because the stream was being watched, ignored it and continued to count from 8.
* Desktop wrote the "8 and a bit" back to sync.
* Laptop saw incoming 8 hours, written after it wrote 12, so it took the 8.

The "change" event would let you see an incoming value of 12 was seen, even after you started using the old value.

**Comment by swpease** [comment]
Ohh, that sounds spot on. Thank you for the help!

**Comment by rebloor** [comment]
@mhammond sorry for the delay on my side, I'm back from a break. Can I clarify a couple of things:

> we will tend to drop the local change and take the incoming change
What circumstances affect this decision?

> The "change" event would let you see an incoming value of 12 was seen
What "change" event are you referring to?

**Comment by mhammond** [comment]
The [onChanged](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/onChanged) event works for the storage.sync area and should be emitted when Sync changes a value.

**Comment by mhammond** [comment]
Oops, I didn't answer this:

> we will tend to drop the local change and take the incoming change
> What circumstances affect this decision?

The "tend to" part is inaccurate - on conflict we always will take the incoming change.
