### ISSUE TITLE
HTMLInputElement.showPicker example cross-domain security error

### ISSUE THREAD

**Issue by brookjordan** [mdn/content#16582]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/showPicker

### What specific section or headline is this issue about?

#result

### What information was incorrect, unhelpful, or incomplete?

The snippet throws a security error, which I’m not sure will ever work:
```
SecurityError: Failed to execute 'showPicker' on 'HTMLInputElement': HTMLInputElement::showPicker() called from cross-origin iframe.
```

### What did you expect to see?

The pickers should be shown.

### Do you have anything more you want to share?

I’m not sure if there is a way to create a snippet that works non-cross-domain, but it seems like as security and sandboxing gets tighter, this will start happening for more and more APIs.

**Comment by hamishwillee** [comment]
Thanks @brookjordan . You're correct. I tested this locally and it worked (not cross origin), and also the first couple live (which happen to work). But I didn't tell all of them on the live server.

Most of these security errors occur because of the spec comments (which are even captured in https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/showPicker#securityerror):

> If [this](https://webidl.spec.whatwg.org/#this)'s [relevant settings object](https://html.spec.whatwg.org/multipage/webappapis.html#relevant-settings-object)'s [origin](https://html.spec.whatwg.org/multipage/webappapis.html#concept-settings-object-origin) is not [same origin](https://html.spec.whatwg.org/multipage/origin.html#same-origin) with [this](https://webidl.spec.whatwg.org/#this)'s [relevant settings object](https://html.spec.whatwg.org/multipage/webappapis.html#relevant-settings-object)'s [top-level origin](https://html.spec.whatwg.org/multipage/webappapis.html#concept-environment-top-level-origin), and [this](https://webidl.spec.whatwg.org/#this)'s [type](https://html.spec.whatwg.org/multipage/input.html#attr-input-type) attribute is not in the [File Upload](https://html.spec.whatwg.org/multipage/input.html#file-upload-state-(type=file)) state or [Color](https://html.spec.whatwg.org/multipage/input.html#color-state-(type=color)) state, then throw a ["SecurityError"](https://webidl.spec.whatwg.org/#securityerror) [DOMException](https://webidl.spec.whatwg.org/#dfn-DOMException).

@schalkneethling Is there any way to allow this to work cross-origin with the live sample?
If not, the solution is to turn all those other examples into "not live samples". I'd rather we got this to work though because live samples are a great demo and way of easily testing cross browser support for features.

**Comment by schalkneethling** [comment]
> @schalkneethling Is there any way to allow this to work cross-origin with the live sample?
> If not, the solution is to turn all those other examples into "not live samples". I'd rather we got this to work though because live samples are a great demo and way of easily testing cross browser support for features.

We might be able to. Thoughts, @mdn/core-dev?

**Comment by caugner** [comment]
If I understand [showPicker's specification](https://html.spec.whatwg.org/multipage/input.html#dom-input-showpicker) correctly, the only way for this example to work would be to serve it from `developer.mozilla.org`, but that's either a no-go from a security point of view (if the example were to remain in mdn/content or mdn/interactive-examples) or requires a non-trivial amount of engineering time (which I'm afraid we don't really have available right now) to treat the example differently in yari / add it to yari.

Ideally Content-Security-Policy would allow to define exceptions, so that `yari-demos.prod.mdn.mozit.cloud` accepts `developer.mozilla.org` as same-origin, but I don't think that's possible. 😕

**Comment by hamishwillee** [comment]
Thanks guys. I'll strip them out, at least as "live examples" then.
