### ISSUE TITLE
Content suggestion: Error.prototype.cause

### ISSUE THREAD

**Issue by Josh-Cena** [mdn/content#16682]
## What is the new suggestion?

https://github.com/mdn/content/pull/7316 added docs for `options.cause` in `Error` constructor, but we don't have a dedicated page for `Error.prototype.cause`.

## Why is it important or useful?

Better discoverability of this feature, more use-cases of error-cause.

For example, we can also showcase the pattern:

```ts
try {
  someOperation();
} catch (err) {
  throw new Error("someOperation failed.", { cause: err });
}
```

## Other supporting information

https://github.com/tc39/proposal-error-cause

**Comment by Josh-Cena** [comment]
Yep, I actually do have the intention to send one myself😁 I'm mostly just keeping it for my own backlog. But now you've beaten me to it, it means I don't have to do it myself, which is also great!

**Comment by hamishwillee** [comment]
Sounds good. 

FWIW In general I wouldn't usually create issues for a missing page. There are so many that I don't see them as bugs/issues - more opportunities. Creating a bug for each one if you don't plan on fixing it creates churn. Obviously that doesn't affect the case where you plan on fixing the problem yourself (i.e. no judgement, just making an observation)

That said, this is a special case (at least for me) because the top level document was missing the property. Also because that was my fault :-(. Had that been present I probably would have ignored this.

**Comment by Josh-Cena** [comment]
I've worked on a lot of repos where contributors are expected to send significant PRs with an accompanying issue approved by maintainers, so they don't waste their time (e.g. if there's already a work-in-progress by someone, or if it's intended). While I can almost be certain that's not the case here, I still uphold this workflow. I also manage my own issue backlog across OSSes because I'm not always able to spare time right away.

**Comment by hamishwillee** [comment]
All good :-)
