### ISSUE TITLE
I tried the example but it is not working, reference error. 

### ISSUE THREAD

**Issue by Stehlampe2020** [mdn/content#16767]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/onChanged

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

Maybe the definition of the code example is faulty? 

### What did you expect to see?

It should spit out a report of the cookie change(s) to the console. 

### Do you have any supporting links, references, or citations?

I inserted the example into my browser console on https://www.lampe2020.de/seiteninfos/cookies/anzeigen and hoped that it would work. 

### Do you have anything more you want to share?

When it said `referenceError: browser is not defined` I changed `browser` in the example code to `window`, then got the error `referenceError: window.cookies is not defined` and changed it to `window.cookie` and got the error `referenceError: window.cookie.onChanged is not defined`. Then I changed it to just `cookies` and got the error `referenceError: cookies is not defined`.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/cookies/onchanged`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/onChanged
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/cookies/onchanged/index.md
* Last commit: https://github.com/mdn/content/commit/17f1582dc23b7d4f6ce017b3939b348ddafc81b0
* Document last modified: 2022-05-03T04:49:07.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing, @Stehlampe2020 ! Web extensions code won't work in the browser console, because web extensions use special APIs that aren't available to normal web pages. You need to package the code as an extension and install it.

The ["Example extensions" section](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/onChanged#example_extensions) points to an extension that you can [install](https://github.com/mdn/webextensions-examples#installing-an-example) to try out this API.
