### ISSUE TITLE
How to disable native datepicking pop-up window in Firefox?

### ISSUE THREAD

**Issue by o771e** [mdn/content#16783]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

### What information was incorrect, unhelpful, or incomplete?

There is no way to Inspect datepicker in Firefox, if you move the focus from the site to the Dev Tools, the datepicking pop-up window dissapears. I don't need this functionality, how do I disable it?

### What did you expect to see?

More info about controlling of datepicker's pop-up

### Do you have any supporting links, references, or citations?

https://stackoverflow.com/questions/48113091/how-to-hide-native-datepicker-in-mozilla-firefox - no answers

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/input/date`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/date/index.md
* Last commit: https://github.com/mdn/content/commit/25234d74a532e77beca08052c884933b57eb3ac6
* Document last modified: 2022-05-26T00:53:07.000Z

</details>

**Comment by sideshowbarker** [comment]
The scope of this issue tracker is limited to specific issues with the actual content of MDN articles. So because the question in this issue’s description is outside the scope of this issue tracker, I’m going ahead and closing this.

https://bugzilla.mozilla.org/ is probably a more suitable place to raise an issue for this.
