### ISSUE TITLE
As a reader 👁️ I should know the total ➕ rows in a table 🔠 looking at the last row number 🔟

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/content#1683]
In this table
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Properties_Reference
i should know how many properties are there.

**Comment by Ryuno-Ki** [comment]
The source for it is in https://github.com/mdn/content/blob/21e72af0578091c8015ff46ec4426697ebf43210/files/en-us/web/css/css_properties_reference/index.html

You could use a [`<caption>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/caption) to summarise the number of rows (but that could be prone to updates missing to increase the number). I'm not sure, whether it should be visually hidden (and only exposed to crawlers and screen readers).

**Comment by mattiapontonio** [comment]
Discovered 43 Min ago
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Lists_and_Counters/Using_CSS_counters

**Comment by mattiapontonio** [comment]
> The source for it is in https://github.com/mdn/content/blob/21e72af0578091c8015ff46ec4426697ebf43210/files/en-us/web/css/css_properties_reference/index.html
> 


From a CI / CD point of view you should always refer to the main because things could change while discussing this issue, without anyone noticing it, perhaps from the ina merge of someone who has not seen this issue.

**Comment by Ryuno-Ki** [comment]
From a DevOps point of view, this is something, that could be automated away (counting the number of rows at build-time).

It could also be a feature in TalkBack (landmark exploration):
https://media.dequeuniversity.com/courses/generic/testing-screen-readers/2.0/en/docs/talkback-images-guide.pdf

I don't have the time right now to check for myself.

**Comment by mattiapontonio** [comment]
I'm interested in accessibility but if we don't release an inaccessible feature we can't open accessibility issues

**Comment by hamishwillee** [comment]
I'm closing this because it is never going to be a priority for docs, and would be better off if automated:
- This is not a requirement for any consumer who isn't visually impaired. 
- It may be useful as an accessibility feature but then I'd say it is one for the screen readers to automate "This is a table with XXX rows".
- If you can find an accessibility expert who says it is a content issue then I agree @Ryuno-Ki that this would be something you'd automate (https://github.com/mdn/content/issues/1683#issuecomment-766406975).


@mattiapontonio I'm closing this. If it is important to you then I suggest you verify that screen readers do not tell you the number of items in a table for this table. If they do then create a PR to fix it as you'd like and we'll review. After that we can perhaps create another PR in yari repo explaining the problem and suggested automation changes.

**Comment by mattiapontonio** [comment]
I was thinking about using
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Lists_and_Counters/Using_CSS_counters
In all tables in all doc.
I Will Try call minimalist 📞
