### ISSUE TITLE
Document Bluetooth requestLEScan

### ISSUE THREAD

**Issue by Ryuno-Ki** [mdn/content#1684]
I'm currently experimenting with Web Bluetooth API and discovered that the Scanning API is absent from MDN.

Spec: https://webbluetoothcg.github.io/web-bluetooth/scanning.html

Demo: https://reelyactive.github.io/web-ble-demo/
Its code: https://github.com/reelyactive/web-ble-demo/blob/abd3df565cffc775ee2e12bd3f4b3f94c9b958ec/js/webble.js

**Comment by sideshowbarker** [comment]
I’m going ahead and closing this without prejudice as not planned for now, given that:

- it’s been open for more than a year with no updates and no signs that anybody’s planning to work on it
- none of the https://webbluetoothcg.github.io/web-bluetooth/scanning.html APIs are in BCD either
- it’s unclear if or where any of the scanning APIs have been implemented in any engines at all — but it is at least clear that they’ve not been implemented in Safari or Firefox, and as with the Web Bluetooth API itself, they’ll never be implemented in Safari or Firefox because both projects are on record as stating they will not implement them

But the issue can still be revisited if we ever have anybody show up with interest in working on it.
