### ISSUE TITLE
Update Container Queries reference, and remove warning box

### ISSUE THREAD

**Issue by jensimmons** [mdn/content#16862]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Container_Queries

### What specific section or headline is this issue about?

The whole page

### What information was incorrect, unhelpful, or incomplete?

> Note: This document is an explanation of an early stage specification that is attracting a lot of interest from web developers. The examples and syntax below should be seen as an explainer to an evolving specification, in order to encourage experimentation and feedback. Once the specification matures, this will be the location of the full MDN documentation for container queries.

The specification is mature now. Browsers are shipping Container Queries. This warning box makes it seem like Container Queries are too experimental to use — that the spec is likely to radically change. Which was true. It's no longer true. 

>Last updated on 15 September 2021 to add details of the new properties container-type, container-name, and container.

This was 9 months ago. Could we update this documentation (if needed) and re-publish — giving the impression that Container Queries are here, it's time. Learn this. Consider using it in an upcoming project.

### What did you expect to see?

I expect to see updated information, accurate to mid-to-late 2022.

### Do you have any supporting links, references, or citations?

I've talked to browser engineers and developer relations folks at Apple and Google. I'm a member of the CSS Working Group. I don't have links to references, but you can confirm that the spec is mature by talking to Miriam Suzanne.

**Comment by jensimmons** [comment]
As a first step, the warning box could simply be removed.

**Comment by dipikabh** [comment]
Hi Will, I can take this on as part of the work of the larger container query doc update work.

**Comment by estelle** [comment]
> Hi @wbamberg, I can take this on as part of the work of the larger container query doc update work.
@dipikabh 
Can you address https://github.com/mdn/content/pull/20872

**Comment by dipikabh** [comment]
> @dipikabh Can you address #20872 I don't think the warning box can be removed without being replaced by a BCD.

Thanks for bringing this to my attention @estelle. Since this is a guide page and the warning at the top is a manually added note, it looks like it can be removed without a BCD update. The BCD sections will be added to the new property pages that'll be created for `@container`, `container-name`, etc.

However, the note should not be removed yet without also updating the information on the page. This is part of the larger planned work on [Container Queries](https://github.com/mdn/content/issues/20987).

To avoid more activity on this topic, I'll close this issue as well as the PR to fix it.
