### ISSUE TITLE
Hoisting glossary entry needs to be much more succint

### ISSUE THREAD

**Issue by hamishwillee** [mdn/content#16923]
### MDN URL

https://developer.mozilla.org/en-US/docs/Glossary/Hoisting

### What specific section or headline is this issue about?

The whole thing

### What information was incorrect, unhelpful, or incomplete?

This is  way too long for a glossary entry. 

### What did you expect to see?

It should be short and succint. 

Either:
- the whole doc should be moved to guide, possibly leaving a stub summary in glossary
- the glossary should be cut back to a summarized version, linking out to relevant docs for each type "i.e. you might have a topic "let and hoisting" in the let doc.

I lean towards the first option, as much simpler. 

### Do you have any supporting links, references, or citations?

https://github.com/mdn/content/issues/16882#issuecomment-1145106021

**Comment by teoli2003** [comment]
Yes, I agree about this: _hoisting_ is a fundamental concept nowadays and deserve its own guide. 

Where should it live? Between _Grammar types_ (which introduces _var_, _let_, and _const_) and _Control flow and error handling_ ?

![Capture d’écran 2022-06-03 à 07 12 58](https://user-images.githubusercontent.com/1466293/171790572-75878cf1-0430-4df9-94a9-7c6224827fc7.png)

**Comment by wbamberg** [comment]
Tricky because this hoisting page talks about:
- variable hoisting
- function hoisting
- class hoisting 

The guide talks about variables in [chapter 2](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_Types) - where it already covers variable hoisting, functions in [chapter 5](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions), and doesn't talk about classes at all!!

The easy thing from a structure point of view is thus to break it up and talk about var hoisting in one place, function hoisting in another, and class hoisting in a third. Then this glossary page could give an overview of the concept and summarise the rules, and point to those other pages for the details?

That's leaving aside the scary fact that the guide doesn't talk about classes at all and therefore probably needs a serious update. (relatedly the "reintroduction to JS" page should probably be retired, and it would be great to think about how the Guide and the LEarn area ought to complement one another)

**Comment by hamishwillee** [comment]
Sounds like a reasonable plan. I don't see any urgency. 

As an aside, I wish we could work out a way to "deprioritize" the concept of hoisting. It seems so silly to spend time arguing about whether let and const and classes are hoisted or not, when actually we just want people to be careful to initialize variables before they read them.
