### ISSUE TITLE
Issue with "Express Tutorial Part 2: Creating a skeleton websi…": …

### ISSUE THREAD

**Issue by mohith563** [mdn/content#1699]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/skeleton_website

#### What information was incorrect, unhelpful, or incomplete?
For windows, only the instructions for how to start the server on command prompt was present and not for powershell

#### Specific section or headline?
[Enable server restart on file changes](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/skeleton_website#enable_server_restart_on_file_changes)

#### What did you expect to see?
$ENV:DEBUG = "express-locallibrary-tutorial:*"; npm run devstart

#### Did you test this? If so, how?
I ran it on powershell and the server started. The instructions were present earlier in the [Creating the project](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/skeleton_website#creating_the_project) and I adapted it for this case

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/skeleton_website`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/skeleton_website
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/server-side/express_nodejs/skeleton_website/index.html
* Document last modified: 2021-01-15T08:25:52.000Z

</details>

**Comment by hamishwillee** [comment]
Hi @mohith563 

Thanks for reporting, but I am not going to fix this. What I have done is created https://github.com/mdn/content/pull/1601 which adds a note for the powershell instruction in the skeleton website and a statement that all future windows instructions are  expected to be windows cmd prompt commands.

Why? Because CMD is easier, requires no extra installation, and the work required to make sure this is properly rolled out could be better spent.
