### ISSUE TITLE
Content suggestion: JavaScript reduce() example and syntax

### ISSUE THREAD

**Issue by WilliamEJBaldwin** [mdn/content#17003]
## What is the new suggestion?
As a new learner, I think the form of reduce in the example (which works) should be reflected in the syntax. The closest syntax entry is this:

reduce((previousValue, currentValue, currentIndex, array) => { /* ... */ }, initialValue)

However, in the syntax, the array is not listed as optional.

My suggestion is to clarify what is and is not optional... maybe even italicizing optional values in the syntax of ALL code in ALL of the webpages would be helpful to early learners, but updating the reduce page's optional content would be a start.

## Why is it important or useful?
It is very hard to understand reduce and every encounter I have had so far is more like the example and not the syntax.

One, or a boatload of pages depending on the chosen course of action, are required to fix this.

If only the reduce page is updated that would take less than an hour. If italicizing all optional content is adopted, that would probably take over a month. 

It would be great for learners and teachers.

It is not a critical need, but helps more students become developers.

No new pages would be needed.

It is not a security risk.

It is not an ethical issue.

The url for the page in question:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce

**Comment by Josh-Cena** [comment]
Do we necessarily need to write this?

```js
reduce((previousValue, currentValue) => { /* ... */ } )
reduce((previousValue, currentValue, currentIndex) => { /* ... */ } )
reduce((previousValue, currentValue, currentIndex, array) => { /* ... */ } )
reduce((previousValue, currentValue, currentIndex, array) => { /* ... */ }, initialValue)
```

Because in actual "syntax" (here it's more like API type definition), we use BNF instead:

```js
reduce((previousValue, currentValue[, currentIndex[, array]]) => { /* ... */ }[, initialValue])
```

Which _could_ be slightly confusing to new learners. What about a more TypeScript-like syntax?


```js
reduce((previousValue, currentValue, currentIndex?, array?) => { /* ... */ }, initialValue?)
```

**Comment by WilliamEJBaldwin** [comment]
BNF? I just had to google that. I like the idea as long as what is optional is clearly defined because many boot camps and other learning places are using forms that aren't recognized as in the syntax and thus confusion sets in as to what forms actually work.

When you are extremely new, the example tells me the syntax, or what I perceive as the syntax, is wrong because I believe the syntax reads as this:

If you are using an arrow function of reduce, you cannot have a initial value UNLESS you have a current index and array variable in your structure... I imply this because initial value only appears on the 4th arrow function syntax.

**Comment by wbamberg** [comment]
We do mark optional parameters as optional: they get a little `Optional` badge after them in the "Parameters" section.

You can see for example that `initialValue` is marked as optional in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce#parameters.

But I think you are talking about the arguments that are passed into the reducer callback function. In this case it's not really appropriate to talk about "optional": "optional" means you may omit a parameter when _calling_ a function, while in this case you are _providing_ the function and it is always passed all four arguments. However, the callback is totally free to ignore any or all of the arguments it is passed, as all functions are always:

```js
function f(x, y, x) :
  console.log("hello!");
}
```

For the case of `reduce()` here, it sounds like your case would be met by adding some more lines to the Syntax section, like:

```js
reduce((previousValue, currentValue) => { /* ... */ } , initialValue)
reduce((previousValue, currentValue, currentIndex) => { /* ... */ } , initialValue)
reduce((previousValue, currentValue, currentIndex, array) => { /* ... */ }, initialValue)
```

Is that right?

With respect to the BNF suggestion, our JavaScript syntax used to do exactly that, but we changed it to list the options, because the BNF was confusing for too many people.

**Comment by WilliamEJBaldwin** [comment]
Yes, this would solve it. I am in favor of some marker like the previously provided ? in the syntax, but I understand I can't always get what I want. 

I don't always read every last bit, but I do read the descriptions for the parameters. It just threw me that currentIndex and array were not *optional* since an initialValue was being used in the example. 

Is there somewhere in the syntax literature that describes the syntax is ONLY for the calling of instead of other usage? Because I am not one to intuit something like that without some notice.

Again, thanks for addressing the issue at least.

**Comment by wbamberg** [comment]
> Yes, this would solve it. I am in favor of some marker like the previously provided ? in the syntax, but I understand I can't always get what I want.
> 

We have thousands of pages on MDN, and if we want to make changes like that we really have to think about how it would work across the whole site, and whether it would make sense to people.

> I don't always read every last bit, but I do read the descriptions for the parameters. It just threw me that currentIndex and array were not _optional_ since an initialValue was being used in the example.
> 
> Is there somewhere in the syntax literature that describes the syntax is ONLY for the calling of instead of other usage? Because I am not one to intuit something like that without some notice.

As far as I know, formally, there is in general not a requirement that you use any of the arguments that are passed into a callback function you provide. So in this case for instance, all the arguments to the reducer are optional:

```js
const initialValue = 0;
const result = [1, 2, 3, 4].reduce(
  () => "hello!",
  initialValue
);

console.log(result);
// "hello!"
```

This isn't a very sensible usage, but formally, it's totally fine.

So there's not much point in marking callback arguments optional, because in that sense, they all are.

**Comment by Josh-Cena** [comment]
May be relevant: https://github.com/mdn/content/pull/14388
