### ISSUE TITLE
Unclear description of keywords in justify-content.

### ISSUE THREAD

**Issue by SergeVDev** [mdn/content#17064]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content

### What information was incorrect, unhelpful, or incomplete?

> normal
>     The items are packed in their default position as if no justify-content value was set. This value behaves as stretch in grid and flex containers.

What's the difference between “normal” and “unset” then? Between “normal” and “stretch”?

> /* Normal alignment */
> justify-content: normal;

No comment.

> left
> If the property's axis is not parallel with the inline axis, this value behaves like start.

What about transform: rotate(120deg); ? The axis is not parallel, but the value doesn't behave like start. If I got it wrong, an explaining would be nice.

> Note: stretch is not supported by flexible boxes (flexbox).

Does it mean it's applied to the Grid model only?

>causing data loss

Is it still CSS-related? I'm kind of scared.

### What did you expect to see?

More clear explaining on “normal”, “stretch”, “baseline first baseline last baseline” (is this just one value? two values? three values?), “left/right” (what's “parallel axis” exactly?).

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/justify-content`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/justify-content/index.md
* Last commit: https://github.com/mdn/content/commit/0a4c76e8e225fa23b6398f3ee1b9c2daae6ea5b9
* Document last modified: 2022-05-22T11:57:55.000Z

</details>

**Comment by lyndipc** [comment]
I would like to work on this

**Comment by estelle** [comment]
There are a few other issues with the page: 

* Formal definition list only states flex. it's supported on grid. the spec also indicates it should be supported on multicol.
*  `flex-start` and `flex-end`, defined in flexbox, but not in alignment, are synonyms for start and end. Should they be listed as such, rather than as positional? Side note: they do work as synonyms in grid.
*  As `justify-content` does not take baseline values, the Baseline alignment mentions should be removed.
