### ISSUE TITLE
Optional Chaining page should explain the chaining aspect

### ISSUE THREAD

**Issue by cben** [mdn/content#17099]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

### What specific section or headline is this issue about?

Most of the doc, but "Syntax" is crucial starting point

### What information was incorrect, unhelpful, or incomplete?

The current page presents `?.` as an operator similar to `.` that takes a single `?.prop` / `?.[expr]` / `?.(args)` on the right side, and may safely return `undefined` instead of error.

Under that model, a long chain of `?.` followed by `.` sounds like separate operators, and if the first `?.` returns undefined the latter `.` should error.  But that's not how it works!

```
> undefined?.split(',').slice().map().reduce()
undefined
```
Contrast this with forcing evaluation as separate operators:
```
> t = (undefined)?.split(',').slice()
undefined
> t.map().reduce()
Uncaught TypeError: Cannot read properties of undefined (reading 'map')

> ((((undefined)?.split(',')).slice()).map()).reduce()
Uncaught TypeError: Cannot read properties of undefined (reading 'slice')
```

IIUC the ECMA spec syntax productions, `?.` actually begins an `OptionalChain`, with following `.prop`, `.method()` etc. all being part of it:
```
OptionalChain :
    ?. Arguments
    ?. [ Expression ]
    ?. IdentifierName
    ?. TemplateLiteral
    ?. PrivateIdentifier
    OptionalChain Arguments
    OptionalChain [ Expression ]
    OptionalChain . IdentifierName
    OptionalChain TemplateLiteral
    OptionalChain . PrivateIdentifier
```
If the left side is null/undefined, _the whole chain is skipped_!

### What did you expect to see?

- [ ] Syntax section covering the concept OptionalChain as a _syntactic_ construct.
    Without understanding this parsing, you can't form a correct model of what it does.

- [ ] Take care with misleading word "operator".

- [ ] Examples of longer chains and explanation that the whole chain is skipped.

    - [ ] Examples contrasting `foo?.bar.baz` vs `foo?.bar?.baz` and explanation why you might want one of the other.
    - [ ] Explanation that `foo?.bar?.baz` does parse as 2 chains `(foo?.bar)?.baz`.

- [ ] Can a chain be explained by rewriting to equivalent logic?
    Something like `isNullish(foo) ? undefined : foo.bar.baz`?  If yes, I think this'd be helpful to understanding.

### Do you have any supporting links, references, or citations?

the spec already linked on the page, https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#prod-OptionalExpression

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/optional_chaining`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/optional_chaining/index.md
* Last commit: https://github.com/mdn/content/commit/d83d0a726583cb808beade63bae9c173c43144f6
* Document last modified: 2022-04-26T02:34:14.000Z

</details>

**Comment by Josh-Cena** [comment]
Agree there's some nuance that's not captured on this page, but not sure how to frame it better.

> Take care with misleading word "operator".

"Operators" are always part of a syntactic construct. For example, `a + b` forms an `AdditiveExpression`, while `a?.b` forms an `OptionalChain`. I think it's fair to draw comparison.

> Examples of longer chains and explanation that the whole chain is skipped.

This doc uses the idea of "short-circuiting" in multiple places. I think that's a quite common analogy, because it behaves just like `p && p.a`, especially when the right arm has side-effects: `p?.[x++]`.

> > IIUC the ECMA spec syntax productions, `?.` actually begins an `OptionalChain`, with following `.prop`, `.method()` etc. all being part of it:

That doesn't mean it has any significance in actual parsing. That's just a BNF norm, because in order to build repetitive patterns you have to define them recursively. `MemberExpression` is also recursively defined as

<pre>

<i>MemberExpression</i> :
    <i>MemberExpression</i> [ <i>Expression</i> ]
    <i>MemberExpression</i> . <i>IdentifierName</i>
    <i>MemberExpression</i> <i>TemplateLiteral</i>
    <i>SuperProperty</i>
    <i>MetaProperty</i>
    new <i>MemberExpression</i> <i>Arguments</i>
    <i>MemberExpression</i> . <i>PrivateIdentifier</i>

</pre>

I'm not aware of an AST that, with the introduction of `?.`, drastically changes the AST structure—e.g. Babel just changes a `MemberExpression` node to an `OptionalMemberExpression`.

**Comment by cben** [comment]
You're right, the central behavior here is "short-circuiting".  But the current MDN page demonstrates short-circuiting only with a chain of depth 1: `potentiallyNullObj?.[x++];` and seems to focus on the side-effect aspect.
With longer chains like `foo?.bar.baz.bug` it matters even without side effects, because you avoid "Cannot read property" risk from `.baz` and `.bug`.

There no longer chains anywhere.

Additional reference: https://github.com/tc39/proposal-optional-chaining#long-short-circuiting :
> In fact, short-circuiting, when triggered, skips not only the current property access, method or function call, but also the whole chain of property accesses, method or function calls directly following the Optional Chaining operator.

(see also Prior Art section there, distinguishing languages that short-ciruit the whole chain vs just one step)

About parsing and "operator":  Current MDN text says near the top:

> The `?.` operator is like the `.` chaining operator ...

AFAIK, regular `foo.bar.baz` is exactly equivalent to `(foo.bar).baz`.  
`foo[bar][baz]` is exactly equivalent to `(foo[bar])[baz]`.  
`foo.bar(2).baz(3)` is exactly equivalent to `(foo.bar(2)).baz(3)`.  
Each `.` or `[]` or method can be understood as a separate operator, which returns a value ant that value is what the next operator operates on.

No so with optional chaining!  
- `foo ?.bar.baz` is a single chain, behaves differently from `(foo ?.bar) .baz`.  In the latter case, only `.bar` gets short-circuited and then `(undefined) .baz` raises an error.
- `foo ?.bar.baz ?.qux.quux` IIUC parses as 2 chains `(foo ?.bar.baz) ?.qux.quux`.  But it cannot be further broken into 4 steps `(((foo ?.bar) .baz) ?.qux) .quux`, that would behave differently.

**Comment by Josh-Cena** [comment]
Ah, I see the point here.

`?.` is an operator, but it's not a _binary_ operator. `foo?.bar.baz` doesn't have a `?.` and a `.` work in isolation—rather, they form a continuous chain, and we'd rather see `?.` and `.` being part of the same operator. Maybe we can draw comparison with Haskell's tuples: `(a, b, c, d)` is constructed by the operator `(,,,)`.

I agree that's not adequately described by the term "short-circuiting" because this specific behavior of chaining is only observed with a series of property accesses.👍
