### ISSUE TITLE
Difficult to understand a sentence in Private Cache section

### ISSUE THREAD

**Issue by aakashsardana** [mdn/content#17199]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching

### What specific section or headline is this issue about?

Private Caches

### What information was incorrect, unhelpful, or incomplete?

In the [Private Caches](https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching#private_caches) section there is a sentence 

> If the response has an Authorization header, it cannot be stored in either the private cache or the shared cache, even if it has max-age — and public can be used to allow such a case

The first half of the sentence is clear but  I am not able to understand this-:

> — and public can be used to allow such a case

Does it means that if we specify public when there is Authorization header then the response would be stored in a shared cache?

### What did you expect to see?

Not able to understand the sentence mentioned above. A bit more clarity on this would be helpful

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/caching`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/caching/index.md
* Last commit: https://github.com/mdn/content/commit/4a43f2f9af30db0721b0150909615f5fe9b041a4
* Document last modified: 2022-06-01T06:37:19.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks, yes it is confusing. Fixed by #17214

In summary, the text means that you can use `public` to make a response be stored in a shared cache even if the Authorization header is set.
IMO the problem with all this text is that it is irrelevant to using the `private` directive, which is what the section is about. I stripped it out and moved the comment on using `public` to where the information on `public` is located.

**Comment by aakashsardana** [comment]
Yes now it is pretty much clear. Thanks @hamishwillee 👍
