### ISSUE TITLE
Is it appropriate to state "overflow" in this case?

### ISSUE THREAD

**Issue by krave1986** [mdn/content#17253]
Hi, I was reading this article.

https://github.com/mdn/content/blob/bde5129e885064a7c89929c8a1f7d921e5a6219e/files/en-us/web/javascript/reference/global_objects/bigint/asintn/index.md?plain=1#L44-L51

As far as I know, `2n ** (64n - 1n) - 1n` in binary should be: 0...(63 1s)...

If we add by 1 as in the example `max + 1n` and turn it into binary. The result would be: 1...(63 0s)...
And it still fits into 64 bit without overflow.

If we read 1...63 0s in a integer view, that would just be -9223372036854775808n .
I don't see it is overflow out of the 64 bits.
Also `BigInt.asIntN(64, max + 1n)` does not modify (or clamp) the BigInt value but just verifies it is in the 64bits range.

So, is it appropriate to state 
> negative because of ***overflow***

in this case?

**Comment by Josh-Cena** [comment]
> If we read 1...63 0s in a integer view, that would just be -9223372036854775808n .
> I don't see it is overflow out of the 64 bits.

Out of the 64 bits, the highest bit is used for the sign, and only 63 bits are used to store the magnitude. So the representable values of 64bit integers range from -9223372036854775808 to 9223372036854775807. 9223372036854775808 would _overflow_ that range. Because negative integers are stored as 2's complement, the overflow "wraps" and the final result is -9223372036854775808.

It doesn't "overflow" in the sense that there are bits being discarded, but "overflows" in the sense that the actual value is greater than what can be represented with this width.

**Comment by krave1986** [comment]
But isn't `BigInt.asIntN()` function more related with bits discarding and integer decoding? For example, `BigInt.asIntN(2, 6n)` would output `-2n` in both ways. `0b110` discards the most significant 1 with `0b10` left. Which in turn results in `-2n` through 2's complement convertion.

**Comment by Josh-Cena** [comment]
Mmmm—I see the point. Yes, using "overflow" here makes it lose the focus.
