### ISSUE TITLE
Issue with "ResizeObserver.observe()": …

### ISSUE THREAD

**Issue by ydaniv** [mdn/content#1733]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver/observe

#### What information was incorrect, unhelpful, or incomplete?

Spec link and status are incorrect.

#### What did you expect to see?

Correct status and link.

#### Did you test this? If so, how?

Went here: https://www.w3.org/TR/resize-observer/

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/resizeobserver/observe`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver/observe
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/resizeobserver/observe/index.html
* Document last modified: 2021-01-09T13:41:23.000Z

</details>

**Comment by sideshowbarker** [comment]
The specification table is correct here. We intentionally link to the latest, actively maintained version of the spec, at https://drafts.csswg.org/resize-observer/. We intentionally do not link to the https://www.w3.org/TR/resize-observer/ document, which is out of date and obsoleted by the https://drafts.csswg.org/resize-observer/ version.

**Comment by ydaniv** [comment]
@sideshowbarker OK, now it shows a proper spec doc, before that it was something broken and useless, perhaps on CSSWG's side 🤷

**Comment by sideshowbarker** [comment]
> @sideshowbarker OK, now it shows a proper spec doc, before that it was something broken and useless, perhaps on CSSWG's side 🤷

Ah yes, sorry, that happens sometimes with the https://drafts.csswg.org/ server. I also ran into that problem recently. Maybe @plinss can comment here with some guidance for us about what we should do if/when we run into that problem again.

(Meanwhile I’m gonna go ahead and close this for now, but we can all still comment here.)

**Comment by plinss** [comment]
Yes, the CSSWG draft server is routinely getting hit by very aggressive crawlers these days (generally trying to scrape email addresses). It has several defenses, but the bots are getting smarter. Sometimes under heavy load (like hundreds of hits/second) the DB server runs out of connections and a rebuild process crashes leaving the DB in a bad state until I kick it.

It's a known issue and while we have a long-term fix planned, I'm also looking at short-term workarounds due to limited cycles to work on it (if someone is able to sponsor the work, I'd be able to take time off my paying job and do it sooner, instead of waiting for me to eventually get some free time). 

If you see the server is down, or not serving a proper spec, best thing for now is to ping me on IRC in #css.
