### ISSUE TITLE
Issue with styles of glossary links

### ISSUE THREAD

**Issue by Torhuo** [mdn/content#1735]
Page with the problem - a lot of pages, for example - https://developer.mozilla.org/en-US/docs/Learn

There are three glossary terms links on the page: HTML, CSS, JavaScript. At the start of 2020, links on glossary terms pages had dotted/dashed underline and had tooltips while hover with short definition from glossary page. Then it was broken (even before migration to Yari), at least at /Learn page, but worked in some other places. At this moment I don't see underline dotted/dashed links and tooltips at all.

Perhaps not an issue and you just removed this feature.

**Comment by peterbe** [comment]
@chrisdavidmills I don't know if this is important enough worry about but it's a fair point that some links even go to the Glossary. For example, you might sit down to read about learning web dev, and then you follow the link and you're now on a Glossary page. As per the screenshot there, the `CSS` link should either go to `/en-us/docs/web/css` or not be a link and instead be something like:
```html
...
learn <abbr title="Definitiona of the word HHTML here">HTML</abbr> and <abbr title="Definition of the word CSS here">CSS</a> in detail:
```

MDN came from being a Wiki which originates a certain style, where every word that can be a link becomes a link. But I think it's a poor thing to have in a section like the "Learn" page which is meant to navigate you in the right (deeper) direction.

**Comment by chrisdavidmills** [comment]
I don't really have time to think about this right now, but ... we ended up removing title tooltips in places where they were used (like xrefs and glossary entries) because of their inherent accessibility issues. At this point, the glossary links just link through to the glossary pages, which is OK — you still get the definition.

I think all I'd do here is to perhaps remove the glossary links from this page. There are already other links that take the reader down the right path to learning these technologies.

Or maybe even do nothing — the definitions ares still helpful...?

**Comment by peterbe** [comment]
Tooltips or not, I think the links are distracting. We're not a wiki anymore. We need to avoid peppering the pages with too many links because a little portion of your brain is losing concentration when you have to make microdecision ("Do I have to click to read more about at what CSS means?? I can't decide. Maybe. I'll just open it in a new tab for now").
I think the prose would read better if it was something like this:

```html
<p>If you have a bit of knowledge already, the next step is to learn HTML and CSS in detail: start 
with our Introduction to HTML module and move on to our <a href="/Learn/CSS/FIrst_step">CSS 
first steps module</a>. (To read more about what CSS means see the <a href="/Glossary/css">glossary 
page for CSS</a>.</p>
```

@chrisdavidmills No action required. Just various interesting thoughts and opinions here about deep linking and style.

**Comment by chrisdavidmills** [comment]
Agreed. OK, so I think we should get rid of the three glossary links.

**Comment by peterbe** [comment]
Yari lost the functionality of formatting links to the Glossary pages. Sorry, didn't notice that. 
But @Ryuno-Ki makes a good point about the in-accessibility of relying on tooltips. Plus the problem with mobile devices. 
And I made the argument that just because have a Glossary page about some term, there are a whole of times where a link to it might just be distracting from a "learning perspective". Points to which @chrisdavidmills agreed. 
So can we close this now? How do you feel about that summary @Torhuo ?

**Comment by Ryuno-Ki** [comment]
> But @Ryuno-Ki makes a good point about the in-accessibility of relying on tooltips. Plus the problem with mobile devices

Today I filled https://github.com/mdn/yari/issues/2705 regarding tooltips.

**Comment by Torhuo** [comment]
@peterbe Well, the main reason for creating this issue was to understand is a missing underline and a tooltip bug or not. Looks like not a bug, so the main problem solved.

About changing glossary links. I like this decision.
> I think the prose would read better if it was something like this:
> ```
> <p>If you have a bit of knowledge already, the next step is to learn HTML and CSS in detail: start 
> with our Introduction to HTML module and move on to our <a href="/Learn/CSS/FIrst_step">CSS 
> first steps module</a>. (To read more about what CSS means see the <a href="/Glossary/css">glossary 
> page for CSS</a>.</p>
> ```

But the main page of the learning area was just an example. What about other HTML, CSS, JavaScript glossary links on other pages?

For example:
- On this page ( https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Getting_started ) `HTML` also a glossary link
- And on this page ( https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/JavaScript_basics ) `JavaScript` also a glossary link.
- Here ( https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML ) `CSS` is a glossary link. And even `head` (not element, just head of the page) glossary link.

And so on. I just want to know what to do in such cases. Remove unnecessary glossary links, change text like you (for me unavailable, because of my poor knowledge of english language) or do nothing?

Because at this moment, there are A LOT of unnecessary glossary links, in my opinion. I can understand glossary links for rare terms or things that not explain in the article. But why, for example, in the article ( https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML ) about `<head>`,  exist glossary links for `metadata`, `head` if it explains inside this article below? I think such glossary links should be removed.

**Comment by peterbe** [comment]
It's hard to get everything right but we can set our minds on the same track. 
Sometimes, in certain documents, it's very appropriate to have a link to the glossary. I'm too lazy to find a good example but there could very well be pages where a much more complicated term is mentioned but one that we don't have a page for. For example, image some page that talks about using background images in CSS and it might mention "PNG" and there it would be appropriate to link to the glossary page for PNG. 

Let's not mass-fix anything now. But we've all learned some interesting stuff about glossary links, reading-flow, accessibility concerns, etc. 

Close?

**Comment by Torhuo** [comment]
Yes, I think we can close this issue now.
