### ISSUE TITLE
[CSS] Implement :modal pseudo-class

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#17470]
## Acceptance Criteria

- [X] The listed features are documented sufficiently on MDN
  https://github.com/mdn/content/pull/18892
- [X] BCD is updated
  https://github.com/mdn/browser-compat-data/pull/17144
- [ ] Interactive example and data repos are updated if appropriate - NA
- [X] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [X] Set bugs to `dev-doc-complete`
- [X] Add entry to Firefox release notes if feature is enabled in release
  https://github.com/mdn/content/pull/18899
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release - NA

## Features to document

Looks like new page & updates to pseudo-classes needed for this one, as well as bcd et al

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1768535

**Comment by NiedziolkaMichal** [comment]
On chrome it's shipping in 103: [https://chromestatus.com/feature/5192833009975296](https://chromestatus.com/feature/5192833009975296)
On safari it's available since 15.6: [https://developer.apple.com/documentation/safari-release-notes/safari-15_6-release-notes](https://developer.apple.com/documentation/safari-release-notes/safari-15_6-release-notes)
