### ISSUE TITLE
Issue with RegExp literal notation parameter explanation

### ISSUE THREAD

**Issue by DanielS6** [mdn/content#17641]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp

### What specific section or headline is this issue about?

Literal notation and constructor

### What information was incorrect, unhelpful, or incomplete?

> **The literal notation's parameters** are enclosed between slashes and do not use quotation marks.

```javascript
let re = /ab+c/i; // literal notation
```

### What did you expect to see?

The `i` for case insensitivity is a "parameter" but is not enclosed between the slashes. Rather, only the pattern to match is enclosed between the slashes, the flags (if there are any) go after the second slash. Perhaps

> **The literal notation's parameters** are ~~enclosed between~~ <ins>specified using</ins> slashes and do not use quotation marks.

instead?

### Do you have anything more you want to share?

Happy to send a pull request if this is approved, but since it would be my first contributions to mdn docs I figured I should file a report.

**Comment by sideshowbarker** [comment]
@DanielS6, Thanks for raising this. You’re right that the wording here leaves quite a lot to be desired.

> Happy to send a pull request if this is approved, but since it would be my first contributions to mdn docs I figured I should file a report.

When you run into something like this that’s poorly written, there’s nothing wrong with just going ahead and putting together a pull request with a proposed fix — even if it’s your first contribution.

So if you want to take a shot a making a pull request for this one, that’d be great. But that said, I think the wording here has other problems beyond just the “enclosed between” part.

@Josh-Cena Would be helpful to have your insight/suggestions on this one.

I’ve actually started to write up a patch for it myself, but after reading it and the similar section in the constructor article at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/RegExp#literal_notation_and_constructor, I stalled at the point of noticing that the articles as currently written make this weird and unhelpful binary distinction between the “literal notation's parameters” and the “constructor function's parameters” — wrongly saying this:

> The constructor function's parameters are not enclosed between slashes but do use quotation marks.

…which seemingly ignores that among the examples which follow that statement is one which shows the constructor being called with a RegExp literal as its first argument.

The distinction it really seems to be struggling to make here is between a string — _“use quotation marks”_ — and a RegExp literal. And since you can of course pass in a string variable rather than a string literal , the whole _“use quotation marks”_ wording is misleading and unhelpful anyway.

So it seems like the underlying fix we really need here is, minimally, some statement that the first argument to the constructor can be either a string or RegExp, period. (Not just a  _“use quotation marks”_ string literal nor just RegExp literal but instead possibly also a RegExp object.)

But then that leads me to think we really should also be adding some explanation of why the constructor lets you pass in a string rather than only allowing a RegExp object.

It currently says, _“Use literal notation when the regular expression will remain constant”_ and _“Use the constructor function when you know the regular expression pattern will be changing”_ but that’s pretty useless guidance unless you already understand what’s actually happening well enough to glean what they’re actually trying to say.

Anyway, I’m not trying to rope you in to picking this one up. I’ve just been kind of thinking out loud here while wondering if you might have any good ideas about how we could properly re-word all this — while still (hopefully) keeping it fairly simple.

**Comment by Josh-Cena** [comment]
Indeed, I don't even know why the docs went with the confusing wording of "slashes" and "quotation marks" instead of simply pointing out that it's an overload of

```ts
interface RegExpCtor {
  // RegExp is an exotic object and it has an internal slot
  // so this can be distinguished on the language level
  new (pattern: RegExp, flags: string): RegExp;
  // Normal case: anything else is coerced to a string
  new (pattern: string, flags: string): RegExp;
}
```

It's not a syntax requirement, just a type requirement, since you can do `new RegExp(new RegExp("foo"))` as well.

So I would start from there, say "you can pass either a string or a RegExp as the first argument; RegExp can provide both the source and flags for the new RegExp, while string can only provide the source." (i.e. `new RegExp(regex, flags)` is equal to `new RegExp(regex.source, regex.flags ?? flags)`) And then we can say "literals make your life easier by allowing you to provide source and flags in a more compact way". (I don't know any _very_ compelling use-case of using literals over the `RegExp` constructor; I only prefer the former because I get better editor syntax highlight. I don't know if a runtime always caches `new RegExp` results because there are a lot of optimizations around regexps already, which makes it hard to benchmark.)

Does that make sense? 🤔 I'm just thinking out loud as well.

**Comment by sideshowbarker** [comment]
> And then we can say "literals make your life easier by allowing you to provide source and flags in a more compact way".

Yeah, that’d be nice simple addition of something concrete that developers can see some clear value in.

As far as the case of why you’d want to use a string, the Stack Overflow answer at https://stackoverflow.com/questions/36911960/javascript-regexp-constructor-vs-regex-literal/36912102#36912102 points out the kind of example of a real-world case that would clearly mean something to a developer who sees it.

But I wonder if we really want to go into that much more detail here at this particular point in the article. On the one hand, what’s most useful for developers is to have concrete examples rather than vague hand-wavy stuff like _“Use literal notation when the regular expression will remain constant”_. On the other hand, there’s value in keeping the intro section as short and simple as possible.

Maybe a good tradeoff would be to add an example to the Examples section and then link to that with a sentence like _“Use a string as the first argument to the RegExp constructor when you want to <ins>build the regular expression from dynamic input</ins> (for example, from the elements of an array)_” (with the underlined part as the hyperlink to the example in the Examples section).

> Does that make sense? 🤔 I'm just thinking out loud as well.

Yeah, makes sense.

@DanielS6 Any chance you might be interested at all in writing up a pull request that makes some changes along the lines of what we’ve been spitballing on here? If not, that’s fine — we can leave this open until either somebody else shows up who feels like giving it try, or one of us decides we have a clear enough idea of what to write, and make time to do it.

**Comment by Josh-Cena** [comment]
Yeah, I clearly see the reason to use the `RegExp` constructor (can be easily refactored, for example, to accept dynamic import, or even spliced together and make the code more readable), but not sure about the literal syntax... I don't know if changing `/foo/g` to `new RegExp("foo", "g")` has any downside at runtime (optimizability?), apart from that it's longer and has less pretty syntax highlighting.

**Comment by galopyz** [comment]
Hello, I would like to fix this issue if nobody else is working on it. 
I can fix the description and add an example to the article.

**Comment by sideshowbarker** [comment]
> Hello, I would like to fix this issue if nobody else is working on it. I can fix the description and add an example to the article.

@galopyz Thanks much — I’ve gone ahead and assigned it to you

**Comment by galopyz** [comment]
Please let me know if this is still not clear or has any issue. I am very new to this. 
If this looks good, can I also work on RegExp constructor? 
Thanks.

**Comment by Josh-Cena** [comment]
The current change in https://github.com/mdn/content/pull/18015 looks good to me @galopyz 👍 Do you want to work on RegExp constructor in the same PR?

**Comment by galopyz** [comment]
Sure. I can also make changes to RegExp constructor as they have very similar issues. :+1:

**Comment by Josh-Cena** [comment]
Thanks @galopyz!
