### ISSUE TITLE
Different between raw data, binary raw data and binary data 

### ISSUE THREAD

**Issue by CwjXFH** [mdn/content#17664]
Hi,
When I read documents on MDN, I found some descriptions like **raw data**, **binary raw data** and **binary**, so what's the difference between these words?
![image](https://user-images.githubusercontent.com/11468733/175805162-4edfb3ae-08e9-4977-ad7f-972d2a459e74.png)

![image](https://user-images.githubusercontent.com/11468733/175805180-d2d1c990-e723-421f-9e83-52cbee2f1966.png)

![image](https://user-images.githubusercontent.com/11468733/175805207-3930d456-c18c-4f76-9073-ed6de750239c.png)

**Comment by Josh-Cena** [comment]
I think "raw" means "binary" right? (I could be wrong.) "Cooked" is things like UTF-16 or floating-point numbers.

**Comment by sideshowbarker** [comment]
Yeah, in the cases cited in the issue description, we could (probably should) just use _“binary data”_ rather than _“raw data”_.

_“raw data”_ in those cases is imprecise and ambiguous, while _“binary data”_ is more precise and less ambiguous.

That said, we have in total about 24 cases of _“raw data”_ in MDN articles, and only some of them mean binary data.

For example:

https://github.com/mdn/content/blob/85e526f765521133b837e2465b02bc05432a0934/files/en-us/learn/javascript/first_steps/arrays/index.md?plain=1#L237

…and there are probably at least 5 other articles that use “raw data” without it meaning binary data.

Otherwise, it might be worthwhile to change the other 15+ instances of _“raw data”_ to _“binary data”_.

As far as the “a binary _ArrayBuffer_” case mentioned in the issue description, the _“binary”_ part there is redundant but IMHO it’s not really worth changing it. Whoever added it presumably did it for emphasis of a sort.

Similarly, I guess it should also be noted here that we have 16 case of _“raw binary data”_ in existing articles. The “raw” part there is arguably redundant — but again, whoever added it in those cases did it for emphasis of a sort. So I don’t think we should change those — because they don’t seem to cause and confusion in context.
