### ISSUE TITLE
WebAssembly.Exception | stack behaviour is completely Mozilla-specific

### ISSUE THREAD

**Issue by ghost** [mdn/content#17660]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Exception

### What information was incorrect, unhelpful, or incomplete?

The article is written in a fairly assertive manner, yet all the behaviour surrounding the exception's stack trace/tracing is very specific to Firefox.

### What did you expect to see?

The article could be written in an inclusive manner to document general behaviour, yet leaving room for Firefox's current behaviours exhibited.

Alternatively, the full nuances of current implementations could be explained, which may over-complicate the topic.

### Do you have anything more you want to share?

Although Chromium [supports the parameter](https://github.com/v8/v8/blob/3f616f6358c4960207d4d7e8a585d89216a7a5e1/src/wasm/wasm-js.cc#L1850-L1874), it seems to quite often attach the full stack trace regardless. This can be confusing, as the article doesn't differentiate between engines or available possible behaviours.

Some files that you can run in Chromium vs. Firefox to confirm differences:
[0.mjs](https://github.com/mdn/content/files/8985989/0.mjs.txt)
[1.mjs](https://github.com/mdn/content/files/8985990/1.mjs.txt)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/webassembly/exception`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Exception
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/webassembly/exception/index.md
* Last commit: https://github.com/mdn/content/commit/d8ea09d4c0a355edcae618b41208366d79bb59c0
* Document last modified: 2022-06-23T04:51:25.000Z

</details>

**Comment by hamishwillee** [comment]
@Phosra Are you sure that the behaviour is not correct according to the spec? Or to put it another way, I tried to write this according to the spec. It may well be that the difference in behaviour in the browser are because Chromium is not compliant with the spec, not because this is Firefox specific. Further, not that the explainer is "ahead" of the spec, and this matches that where there were discrepancies (I was informed the differences would be updated in the spec in a short timeframe).

If I am correct, the solution is to add a note in the BCD about the Chromium incompatibility with the current spec in particular versions.

**Comment by hamishwillee** [comment]
Yes "note" not "not". Sorry, typing too fast.

> I take it that the use of "generally" here technically does allow Chromium's behaviour, it is just not obvious as to the implications of that, or what it really means - it is very open-ended.

Yes, the text here allows Chromiums behaviour - but it should not. 

That's one reason for the update in https://github.com/mdn/content/pull/15640/ - to make it clear that the stack should not be included by default. My understanding is that chromium implemented this early and are now off spec.

**Comment by hamishwillee** [comment]
PS My point is that the intent was to match the spec. So the first test of inaccuracy should be to check the spec, not some discrepancy between browsers. If there is an issue between the browser and the spec, this should be captured in BCD. MDN documents spec behaviour.

Which is not to say that there aren't errors here, and that questioning this is not appreciated. I am not an expert in WASM and I found writing this extremely challenging.

**Comment by hamishwillee** [comment]
@Phosra No apologies necessary! Seriously, I've screwed up enough times I value the input as it forces me to consider why I did something.

To answer your questions.

If there is an absolutely massive difference between compatibility then I would normally add a note box up the top of the page making a comment and pointing to the BCD. I don't see this particular case of the stack being included as worthy of such a note because it would be better if users assume the stack won't be there.

We try discourage anything off spec outside of the BCD. Not only is it unmaintainable, but the BCD is used in many places, so if we put it there we make sure that people who are refering to this outside of MDN still get the info.
So this should move into BCD:

![image](https://user-images.githubusercontent.com/5368500/177898924-6da484d5-568a-477a-971c-72a4da20369a.png)

And so should the issue about stack being included.

Would you be willing to create that?

**Comment by hamishwillee** [comment]
If not, let me know and I'll take care of it.
