### ISSUE TITLE
CSS.registerProperty seems useless

### ISSUE THREAD

**Issue by ygoe** [mdn/content#17670]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/CSS/RegisterProperty

### What specific section or headline is this issue about?

Example

### What information was incorrect, unhelpful, or incomplete?

The example claims to demonstrate how this method call is useful and the colour gradient only works when using the method.

### What did you expect to see?

A difference that the method makes, as explained. But there isn't one. Both gradients work just fine. What's the use of this method?

### Do you have anything more you want to share?

Also, the page says that the method is experimental, but that note is missing from the CSS overview page and also the method list in the left side panel. This seems inconsistent.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/css/registerproperty`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CSS/RegisterProperty
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/css/registerproperty/index.md
* Last commit: https://github.com/mdn/content/commit/66af01dc764631c0fdcb3fc22c197f897a7ca80a
* Document last modified: 2022-06-03T21:07:24.000Z

</details>

**Comment by Josh-Cena** [comment]
> Both gradients work just fine.

I can see that only the first one has a smooth transition when you hover over it; the second one is an instant change. This is pointed out in the content:

> We can now use that property to transition a gradient on hover or focus. Notice that with the registered property the transition works, but that it doesn't with the unregistered property!

This is because only `registerProperty` allows you to opt-out of inheritance, so that `--my-color` defined in `.registered` and `.registered:hover` are actually two properties and they don't shadow each other.

> that note is missing from the CSS overview page and also the method list in the left side panel.

This part is fixed because we now auto-sync between BCD and content metadata.

As such, I'll close this issue unless there's further clarification needed.
