### ISSUE TITLE
Shallow copy wording in arrays and TypedArrays slice method is incorrect.

### ISSUE THREAD

**Issue by ColtHands** [mdn/content#17889]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice

### What specific section or headline is this issue about?

shallow copy wording

### What information was incorrect, unhelpful, or incomplete?

1. `Array.prototype.slice` does not really create a shallow copy
2. The wording lower in article describing that the objects that are present in `slice`'d array are shallow copies, not an array itself
3. The wording already changed for TypedArrays

Talkin about 2nd point, it states lower that _`slice` does not alter the original array. It returns a [shallow copy](/en-US/docs/Glossary/Shallow_copy) of elements_

**element** not the array itself

### What did you expect to see?

Same wording as the most recent changes in `TypedArrays` article.

_The **`slice()`** method returns a new array, that contains a copy of a portion of
the original, selected from `start` to `end`
(`end` not included) where `start` and `end` represent
the index of items in that array. The original array will not be modified._

### Do you have any supporting links, references, or citations?

https://github.com/mdn/content/issues/5035

### Do you have anything more you want to share?

The discussion at https://github.com/mdn/content/issues/2529 is completely incorrect, the `.slice()` method creates a new array, with elements shallow copied.
```js
let arr = [1, 'hello', 3, { ping: 'pong' }]
let shallowCopy = arr // [1, 'hello', 3, { ping: 'pong' }]
shallowCopy[0] = 'is it shallow, yes it is'

console.log(shallowCopy) // ['is it shallow, yes it is', 'hello', 3, { ping: 'pong' }]

let deepCopyWithShallowObject = arr.slice()
deepCopyWithShallowObject[0] = 'not really a shallow copy is it'

console.log(deepCopyWithShallowObject) // ['not really a shallow copy is it', 'hello', 3, { ping: 'pong' }]
console.log(shallowCopy) // ['is it shallow, yes it is', 'hello', 3, { ping: 'pong' }]

deepCopyWithShallowObject[3].ping = 'now this is deep'

console.log(deepCopyWithShallowObject) // ['not really a shallow copy is it', 'hello', 3, { ping: 'now this is deep'}]
console.log(shallowCopy) // ['is it shallow, yes it is', 'hello', 3, { ping: 'now this is deep'}]
```

I've also talked about it [Here](https://github.com/mdn/content/issues/2529#issuecomment-1172891720)

**Also.**

The wording in TypedArray description is just flat out incorrect.

It says _As typed arrays only store primitive values, the copy the slice method returns is always a [shallow copy](https://developer.mozilla.org/en-US/docs/Glossary/Shallow_copy)._ It should state that it returns a **deep copy**.

**I think we should have clearer wording on what is shallow and what is deep**

Please correct me if I'm wrong.

Also I'm working on it ahead of time, if we all agree on that the wording should be more clearer and correct.

**Comment by Josh-Cena** [comment]
Here's a "shallow copy":

```js
function shallowCopy(anything) {
  const anotherThing = {};
  Object.entries(anything).forEach(([k, v]) => anotherThing[k] = v);
  return anotherThing;
}
```

A "shallow copy" means the returned object is referentially different from the original one, but each individual value is the same as the original. "Shallow copy" does not imply anything about changing the original array. Here's proof that `slice()` shallow-copies:

```js
const arr = [{}, {}];
const another = arr.slice();
console.log(another[0] === arr[0]);
```

All elements are still referentially equal—`slice` does not copy each individual element; the underlying value is the exact same one.

> It says _As typed arrays only store primitive values, the copy the slice method returns is always a [shallow copy](https://developer.mozilla.org/en-US/docs/Glossary/Shallow_copy)._ It should state that it returns a **deep copy**.

Primitive arrays don't really have the concept of shallow/deep copying; it just returns a new array. You can't _mutate_ a primitive.

**Comment by ColtHands** [comment]
@Josh-Cena I agree and disagree at the same time.

Here I'd like to demonstrate to you a simple example _I'd want to make it as simple as i can so everyone could participate in the discussion_

```
arr = [1, 2, { hello: 'world' }]
arrSliced = arr.slice()
arrReference = arr

console.log(arrSliced == arr) // false
console.log(arrReference == arr) // true
```

So, if you are saying that slicing a basic array where objects have reference and primitives do not creates a _shallow copy_.

Ok that seems a little counterintuitive, but logical.

But then the line in `TypedArray`'s artice description _As typed arrays only store primitive values, the copy the slice method returns is always a [shallow copy](https://developer.mozilla.org/en-US/docs/Glossary/Shallow_copy)._ should be changed or not.

So, the question for me here is that:

**Do we consider `Array` and `TypedArray`'s `.slice()` to be the same thing, or are we treating slice differently depending on whether in can return an object as reference or only primitives?**

**Comment by Josh-Cena** [comment]
I don't understand that😅 TypedArray and Array's `slice()` function in the same way.

The idea of a shallow copy is "each element is referentially equal, but the entire array is different". BUT, there's no such thing as "a reference to a primitive value"—primitives are values themselves. It simply doesn't make sense to ask if an array of primitives is shallow-cloned or deep-cloned, because it can only ever be cloned to one level. If you do `[1, 2, 3].slice()`, it's neither shallow-cloned nor deep-cloned—it's just _cloned_. OTOH, if we adopt the definition that "shallow-clone == clone depth of 1", then it's indeed a shallow clone, but making that distinguishment is, at the end of the day, not very useful.

**Comment by hamishwillee** [comment]
A shallow copy is one in which modifications to the copy affect the original. A deep copy is one in which that is not true.

Generally we see shallow copies when any of the contents are _references_ to the elements of the original object. I suspect there are other cases too - i.e. it might be possible that an object property or array element is handle to a resource such that the copied object is not a javascript reference, but still points to the same resource. In this case I'd consider a copy to be shallow (which is why you want to transfer resources when you do a structured clone).

Anyway, the [TypedArray.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/slice#description) description is nonsensical - assignment of a primitive always creates a new value/reference, so saying that because the typed array only has primitives it must be a shallow copy is not logical. I think "shallow copy" is just a typo. Fixed in #17932

**Comment by teoli2003** [comment]
If I understand well, this is fixed by #17932. Feel free to reopen if I'm mistaken.

**Comment by Josh-Cena** [comment]
Mmm, I would consider it resolved as well.

**Comment by hamishwillee** [comment]
It is closed IMO. I left it open in case the explanation did not satisfy @ColtHands . I suspect it will, because it cleans up the inconsistency that was causing confusion.
