### ISSUE TITLE
Issue with "<input type="number">": partials are not included, source code shown

### ISSUE THREAD

**Issue by pavelloz** [mdn/content#1819]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number

#### What information was incorrect, unhelpful, or incomplete?

There are some bugs, looks like code that should include partials

#### Specific section or headline?

<img width="730" alt="image" src="https://user-images.githubusercontent.com/546845/106034766-98a13600-60d3-11eb-8c69-c5cf0ebb235e.png">

#### What did you expect to see?

I dont know, but not source code for incude

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/input/number`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/html/element/input/number/index.html
* Document last modified: 2020-12-20T22:23:38.000Z

</details>

**Comment by chrisdavidmills** [comment]
@escattone another {{ page }} macro fail.

**Comment by escattone** [comment]
Thanks @pavelloz and @chrisdavidmills. I noticed this yesterday as well, and created #1774 (which was fixed by #1775). However, it can take up to 48 hours for changes to be seen at https://developer.mozilla.org (due to our build schedule and CDN caching) so the changes were only visible today. This is resolved.
