### ISSUE TITLE
No formal syntax found in DB

### ISSUE THREAD

**Issue by Ryuno-Ki** [mdn/content#182]
Today, I noticed an „error” message in https://developer.mozilla.org/en-US/docs/Web/CSS/@media/-ms-high-contrast#Formal_syntax I believe.

It says

> Syntax not found in DB!

The respective file is

https://github.com/mdn/content/blob/c79bf8d3b1566b444a255527603a304bf6d3624d/files/en-us/web/css/%40media/-ms-high-contrast/index.html#L43-L45

**Comment by sideshowbarker** [comment]
I went ahead and removed that heading and the `{{CSSSyntax}}` macro.

The problem is `-ms-high-contrast` isn’t in that https://github.com/mdn/data/blob/master/css/properties.json, so the backend has no data from which it can expand that `{{CSSSyntax}}`.

And I guess the reason `css/properties.json` doesn’t have `-ms-high-contrast` is, it’s not standard, and there’s no specification for it from which we can copy the formal syntax.

That said, `css/properties.json` does seem to contains syntax definitions for some properties that aren’t standard, but maybe those are just the exceptions to the rule (where the rule is that we have no spec that provides the formal syntax for some property, `css/properties.json` won’t contain any entry for it.

**Comment by Ryuno-Ki** [comment]
Thanks, @sideshowbarker.

I wonder, whether we could make Yari flag instances like this as flaw. Shall I fill an issue against the Yari repo?

**Comment by sideshowbarker** [comment]
> I wonder, whether we could make Yari flag instances like this as flaw. Shall I fill an issue against the Yari repo?

Yeah, would be good to raise an issue for it
