### ISSUE TITLE
Express Author_list_page has unnecessary populate() method

### ISSUE THREAD

**Issue by mateuszkowalke** [mdn/content#1827]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

There is an unnecessary populate() method called on Author model in authorController code in [Express_Nodejs/Displaying_data/Author_list_page](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Author_list_page)

**Comment by hamishwillee** [comment]
There is no use of `populate()` in the current version of the docs or [tutorial example code](https://github.com/mdn/express-locallibrary-tutorial/blob/master/controllers/authorController.js). I suspect this issue was fixed when the tutorial was reviewed late last year. 

Closing. Thanks for posting this.
