### ISSUE TITLE
Add Notes for combining <sup> and <a> for reference 

### ISSUE THREAD

**Issue by esdnm** [mdn/content#18329]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/sup

### What specific section or headline is this issue about?

Notes

### What information was incorrect, unhelpful, or incomplete?

Add a Notes section that provides guideline on using `<sup>` and `<a>` for pointing to a reference. A general question comes up about which one should warp which one.

Like for `<code>` there is a Notes sections that tell to warp ` <code>` element within a `<pre>` for multiple lines of code → https://developer.mozilla.org/en-US/docs/Web/HTML/Element/code#notes

### What did you expect to see?

Notes on using `<sup>` and `<a>` for pointing to a reference.

### Do you have any supporting links, references, or citations?

Like https://developer.mozilla.org/en-US/docs/Web/HTML/Element/code#notes

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/sup`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/sup
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/sup/index.md
* Last commit: https://github.com/mdn/content/commit/672bace59f60c4931e5cdde8eb32919c924bd191
* Document last modified: 2022-03-14T00:26:56.000Z

</details>

**Comment by Josh-Cena** [comment]
Waiting for someone to comment on this. My personal feeling is it doesn't matter since they are both phrasing content in whichever order. `code` cannot have `pre` as children because `pre` is not phrasing content. `sup` and `a` doesn't constitute a special combination unlike `pre` + `code`, so I personally don't see the point in documenting this. But I'm not HTML expert either.

**Comment by Josh-Cena** [comment]
Closing per https://github.com/mdn/content/issues/18329#issuecomment-1204255568
