### ISSUE TITLE
Writeable streams page missing assets

### ISSUE THREAD

**Issue by ChrisBFusion** [mdn/content#1833]
https://developer.mozilla.org/en-US/docs/Web/API/Streams_API/Using_writable_streams

CSS and JavaScript assets aren't loading.

**Comment by Ryuno-Ki** [comment]
Thanks for bringing it to our attention, @ChrisBFusion.
Since I can see multiple code snippets (but none interactive ones) on that page, I'd like to ask you to share

1. Which code snippet fails to load assets.
2. A screenshot of the error message you observed.
3. Which browser and operating system you use.

This will help us triage the issue :-)

**Comment by ChrisBFusion** [comment]
It's looking correct now. I'm closing the issue.
