### ISSUE TITLE
Formal syntax is on one single line

### ISSUE THREAD

**Issue by yukulele** [mdn/content#1835]
The text of formal syntax is on one single line (as if `white-space: nowrap` was applied)

The problem occurs on many pages (all?) Only the English version seems to be affected.

Example:
https://developer.mozilla.org/en-us/docs/Web/CSS/background#formal_syntax

![MDN/docs/Web/CSS/background#formal_syntax](https://user-images.githubusercontent.com/347244/106059524-1de81300-60f3-11eb-9b1a-33660291cf13.png)

**Comment by Ryuno-Ki** [comment]
@rachelandrew It looks like this is defined using a macro in

https://github.com/mdn/content/blob/234ed36e767531a6c562787f90632c61031c1c47/files/en-us/web/css/background/index.html#L102

@nschonni Is it something, mdn-minimalist should take into account?

**Comment by nschonni** [comment]
I haven't really looked at the minimalist stuff. I think the current behaviour is correct, since I think the grammar is based off of https://en.wikipedia.org/wiki/Backus%E2%80%93Naur_form and isn't supposed to split across lines
I think this is the default in general for `<pre>` tags as you're indicating that space is significant in the block

**Comment by nschonni** [comment]
Oh, I think I see it looking at the German page, as it seems to have some `where` that may make it a multi-line statement

**Comment by rachelandrew** [comment]
Closing as this doesn't seem to be the case anymore.
