### ISSUE TITLE
Links in the XUL documentation on the MDN website point to the non-archived versions of the pages

### ISSUE THREAD

**Issue by chris4000** [mdn/content#1837]
XUL documentation on the MDN website is archived, since XUL is deprecated. However, there are still many uses for UI customization through XUL, so this documentation is still important.

The issue: when you follow a link from an archived XUL documentation page, it takes you to the unarchived version of that page. This page contains no documentation except a warning that the page cannot be found. The URL can be changed to point to the archived version, but this must be done manually. Since the page was linked from an archived page, it would make sense to have the link point to the archived page, so it can actually be used by people.

For example, this is the main, archived page of the XUL documentation:

https://developer.mozilla.org/en-US/docs/Archive/Mozilla/XUL

If I click the "XUL Reference" link on this page, it brings me to:

https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/XUL_Reference

This is the original, unarchived page, on which it says the page cannot be found. The correct page should be:

https://developer.mozilla.org/en-US/docs/Archive/Mozilla/XUL/XUL_Reference

As can be seen, by removing /Tech/ from and adding /Archive/ to the URL, the archived version of the page is loaded. Since this page was linked from an archived page, the link should point to the archived page (in order to be useful).

**Comment by Ryuno-Ki** [comment]
@peterbe I think, these cases should be considered flaws by Yari. Do you agree?

**Comment by peterbe** [comment]
> @peterbe I think, these cases should be considered flaws by Yari. Do you agree?

We don't use flaws in the archived content.

**Comment by peterbe** [comment]
The best solution would be to copy down all the redirects for archived content so that `/en-US/docs/Mozilla/Tech/XUL/XUL_Reference` becomes a redirect to `/en-US/docs/Mozilla/Archive/XUL/XUL_Reference`. Then the link clicks would work. 
Unfortunately, we're a bit stretched thin for time to go back to the original migration code to retrofit these redirects. 

One thing you could is to add these to https://github.com/mdn/content/blob/main/files/en-us/_redirects.txt
Use the tool: 
```
yarn content add-redirect /en-US/docs/Mozilla/Tech/XUL/XUL_Reference /en-US/docs/Mozilla/Archive/XUL/XUL_Reference
```
But there might be many more. 
Another option is to edit the rendered HTML within https://github.com/mdn/archived-content and make  PR.
E.g. https://github.com/mdn/archived-content/blob/c336d6aba607dfa8aa2ab6ed07f561f537acde3b/files/en-us/archive/mozilla/xul/index.html#L70

**Comment by himanshugarg** [comment]
The Archive links reported no longer work. Is their removal as designed? Either way, anything more required for this issue?

- https://developer.mozilla.org/en-US/docs/Archive/Mozilla/XUL
- https://developer.mozilla.org/en-US/docs/Archive/Mozilla/XUL/XUL_Reference
