### ISSUE TITLE
Issue with "String.prototype.slice()": incorrect paragraph

### ISSUE THREAD

**Issue by theonlypwner** [mdn/content#1838]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice

#### What information was incorrect, unhelpful, or incomplete?
> If `endIndex` is specified and `beginIndex` is negative, `endIndex` should be negative, otherwise an empty string is returned. (For example, `slice(-3, 0)` returns `""`.)

#### Specific section or headline?
Syntax > Parameters

#### What did you expect to see?
This paragraph should be removed or rewritten.

#### Did you test this? If so, how?
The same article provides this example, which I confirmed in a browser console:
```js
let str = 'The morning is upon us.'
console.log(str.slice(-11, 16)) // => "is u"
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/string/slice`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/global_objects/string/slice/index.html
* Document last modified: 2021-01-09T13:41:23.000Z

</details>

**Comment by chrisdavidmills** [comment]
Yeah, after some testing, it looks to me like endIndex just behaves the same regardless of the value of startIndex. It's just that nothing will be returned when the index selected by endIndex is smaller than the index selected by startIndex, so you need to make sure it is greater.

I'd probably rewrite it something like 

"If endIndex is omitted or undefined, or greater than str.length, slice() extracts to the end of the string.

If negative, it counts backwards from the end of the string.

Regardless of whether beginIndex and endIndex are positive or negative, you need to make sure the index value selected by endIndex is greater than the one selected by beginIndex, otherwise an empty string is returned. (For example, slice(-1, -3) or slice(3, 1) returns "".)"

What do you think?

**Comment by theonlypwner** [comment]
I've rewritten this by merging the last two old paragraphs and submitted a pull request.

new:
> **endIndex** _Optional_
> The zero-based index _before_ which to end extraction. The character at this index will not be included.
>
> If negative, `endIndex` is treated as `str.length + endIndex`. If omitted or undefined, or greater than `str.length`, `slice()` extracts to the end of the string.  (For example, if `endIndex` is `-3`, it is treated as `str.length - 3`.) If it is not undefined, and `Number(endIndex)` is not positive, an empty string is returned.
>
> If `endIndex` is specified, `endIndex` should be greater than `beginIndex`, otherwise an empty string is returned. (For example, `slice(-3, 0)`, `slice(-1, -3)`, or `slice(3, 1)` returns `""`.)

old:
> **endIndex** _Optional_
> The zero-based index _before_ which to end extraction. The character at this index will not be included.
>
> If `endIndex` is omitted or undefined, or greater than `str.length`, `slice()` extracts to the end of the string. If negative, it is treated as `str.length + endIndex`. (For example, if `endIndex` is `-3`, it is treated as `str.length - 3`.) If it is not undefined and not a number after `Number(endIndex)`, an empty string is returned.
>
> If `endIndex` is specified and `beginIndex` is negative, `endIndex` should be negative, otherwise an empty string is returned. (For example, `slice(-3, 0)` returns `""`.)
>
> If `endIndex` is specified, and `beginIndex` and `endIndex` are both positive or negative, `endIndex` should be greater than `beginIndex`, otherwise an empty string is returned. (For example, `slice(-1, -3)` or `slice(3, 1)` returns `""`.)
