### ISSUE TITLE
incomplete command

### ISSUE THREAD

**Issue by tari-w** [mdn/content#18417]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Package_management

### What specific section or headline is this issue about?

Building our code for production

### What information was incorrect, unhelpful, or incomplete?

> Run the following command:
>
> parcel build index.html

### What did you expect to see?

npx parcel build index.html

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/tools_and_testing/understanding_client-side_tools/package_management`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Package_management
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/understanding_client-side_tools/package_management/index.md
* Last commit: https://github.com/mdn/content/commit/73ea2b0f8ebfab23630b86e64b14a7b1f7577679
* Document last modified: 2022-05-13T04:41:50.000Z

</details>

**Comment by Josh-Cena** [comment]
There's already a note:

> Note: If you have trouble with the terminal returning a "command not found" type error, try running the above command with the `npx` utility, i.e. `npx parcel index.html`.

The tutorial kind of assumes you have a global installation of the parcel CLI, which is a fair assumption (you'll sooner or later find it very convenient). I'm okay to remove that assumption and use `npx parcel` everywhere. Better still, is to add a `"build": "parcel"` to your package.json's `scripts` and invoke it with `npm run build`. (This is recommended because it builds an abstraction over the tool you are using.)

If anyone wants to contribute to this, I'm fine with either adding `npx` or adding a `scripts`, depending on how deep you want to go into :)

**Comment by tari-w** [comment]
@Josh-Cena My mistake I accidentally skipped a few lines in the tutorial. Don't know how that happened.
