### ISSUE TITLE
Notecard missing macro usage

### ISSUE THREAD

**Issue by tannerdolby** [mdn/content#1844]
Wondering if the second notecard was supposed to be styled with the macro `{{Note('stuff')}}` on [What is a URL?](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_URL). I'm asking because the first notecard is utilizing the macro which adds the little notecard icon.

First notecard (uses macro)
<img width="729" alt="Screen Shot 2021-01-27 at 10 25 10 PM" src="https://user-images.githubusercontent.com/48612525/106098840-93051980-60ee-11eb-9b43-1f99463bfbf2.png">

Second notecard (doesn't use macro)
<img width="736" alt="Screen Shot 2021-01-27 at 10 25 15 PM" src="https://user-images.githubusercontent.com/48612525/106098855-97c9cd80-60ee-11eb-80c7-560bec95af2a.png">

**Comment by Ryuno-Ki** [comment]
@nschonni Can you help answering this?

**Comment by chrisdavidmills** [comment]
In can answer this. Ideally we should be moving away from using note macs because eventually we want to get rid of all macros as we prepare to move to markdown for mdn content.

This doesn't mean you should start going about trying to delete as many macros as possible; we'd prefer to do it in a coordinated way with proper tooling.

But at the same time, it would be nice for them to at least be consistent in the same article ;-)

In this case, the second macro instance is not looking right because it doesn't have the clas of `notecard` on it — it needs `note` and `notecard`.

When inserting new notes in a page, you should be using the updated syntax we decided on a little while ago:

```
<div class="notecard note">
  <h4>Note</h4>
  <p>This is how we usually present a note in an MDN article.</p>
</div>
```

We haven't get got this into the official guidelines, as the PRs are still being worked through...but soon ;-)

**Comment by hamishwillee** [comment]
PS. FYI only Chris did actually update the official notes on using notes :-) : https://developer.mozilla.org/en-us/docs/MDN/Guidelines/CSS_style_guide#.note.notecard

@tannerdolby I have assigned to you to fix. If you don't want to then handball back to me.

**Comment by hamishwillee** [comment]
Thanks @tannerdolby. Great.

> Want me to look for other spots throughout the codebase for notecards that need updating as apart of this issue/PR as well?

Personally I am not going out of my way to systematically fix these; instead I am fixing all of them on the pages that I touch. My thinking is that while this is a good thing to do, it isn't as valuable as "information fixes". 
Upshot I think your time could be better spent, but if you fix them, we'll be happy :-)

**Comment by tannerdolby** [comment]
Your welcome @hamishwillee !

Ok got it. I agree with you, it's probably not the best use of time as they aren't extremely valuable "information fixes". That being said, I will fix the notes on pages I touch as well. In my free time (weekends) I will slowly chip away at all the notes without the updated syntax and submit PRs to update them :-)

**Comment by Ryuno-Ki** [comment]
If we could break them down to specific pages / subtrees, those could make up „Good first issue” items to invite more people to contribute. Just sayin'
