### ISSUE TITLE
Issue with "204 No Content": …

### ISSUE THREAD

**Issue by jeannieism** [mdn/content#1856]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204

#### What information was incorrect, unhelpful, or incomplete?
Typo

#### Specific section or headline?
"In this case *an* PUT request would be used.."

#### What did you expect to see?
"In this case *a* PUT request would be used..."

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/status/204`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/http/status/204/index.html
* Document last modified: 2021-01-19T20:29:06.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks very much @jeannieism - will be fixed by #1865

Just FYI, for changes like this that you are sure of, feel free create a pull request on github with the fix. There is a link at the bottom of every page that takes you to the source for editing:
![image](https://user-images.githubusercontent.com/5368500/106207406-cbebde00-6215-11eb-83cb-24f179c2e074.png)

**Comment by jeannieism** [comment]
I am so sad I did not take this opportunity... 🥲

**Comment by Ryuno-Ki** [comment]
@hamishwillee Would it be possible to outline the steps needed so contributors could pick up an issue?
Especially for tickets marked as „good first issue”.

@jeannieism I'm confident another chance will raise up :) Please be patient.

**Comment by hamishwillee** [comment]
> Would it be possible to outline the steps needed so contributors could pick up an issue?

Probably :-)

@chrisdavidmills is there already and instruction on how to pick up issues, and what types there are? I had a quick scan - was expecting to see it here: https://github.com/mdn/content/blob/main/README.md

Further, as an aside, looking at the [section on simple changes](https://github.com/mdn/content/blob/main/README.md#simple-changes) it assumes you have to navigate to the page via github. OK for me to update this to say "press this link? 

![image](https://user-images.githubusercontent.com/5368500/106207406-cbebde00-6215-11eb-83cb-24f179c2e074.png)

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills is there already and instruction on how to pick up issues, and what types there are? I had a quick scan - was expecting to see it here: https://github.com/mdn/content/blob/main/README.md

This is covered at https://developer.mozilla.org/en-US/docs/MDN/Contribute/Fixing_MDN_content_bugs. I am happy to receive suggestions for improving it.

> Further, as an aside, looking at the [section on simple changes](https://github.com/mdn/content/blob/main/README.md#simple-changes) it assumes you have to navigate to the page via github. OK for me to update this to say "press this link?

I'm not sure it does, does it? It talks about using the GitHub UI to fix simple changes, but it doesn't particularly specify how to get to finding a page that needs fixing? In any case, I think it would be good to update that section to mention that you can press this link to find the page source to edit.

**Comment by Ryuno-Ki** [comment]
> but it doesn't particularly specify how to get to finding a page that needs fixing

Exactly. That's why I expected to see as an answer.
Issues I marked as „good first issue” show the production site, the source file and outline what exactly needs to be changed.
That should be enough information to get started.
I offer help if there are technical problems, too (like: how do I get the code locally etc.). We have that in the README, too, but there's so much to read (I was looking for a CONTRIBUTING.md originally).

**Comment by hamishwillee** [comment]
OK, so I'm now pretty much "set in motion" the simple things that can be done with this - better links at bottom of every page, improvements to the "what docs should I fix", and cross linking between readme and the MDN docs. I haven't created a CONTRIBUTING.md because all of the contributing docs are in the README of this repo - it does not make sense to have both.

@chrisdavidmills There is a lot more that can be done, but it requires more analysis and work, and you might not consider it sensible or worth the effort at this point. Let's discuss offline, but in summary:
1. There are effectively two independent guides to contribution in the docs - [README.md](https://github.com/mdn/content#contributing-to-the-content-of-mdn-web-docs) and the docs on MDN itself below [/MDN/Contribute](https://developer.mozilla.org/en-US/docs/MDN/Contribute). These are only loosely linked together.
2. The mdn docs are not navigable. Specifically https://developer.mozilla.org/en-US/docs/MDN/Contribute should really have its own sidebar so that if there are useful docs, they can be found from the top level easily.

IMO the way to fix this is to merge the two sources into the MDN, add a sidebar. From the README and/or contributing we'd then have just the mimimal link through to getting started etc.
