### ISSUE TITLE
Content suggestion: everything but the code

### ISSUE THREAD

**Issue by estelle** [mdn/content#18783]
## What is the new suggestion?

Add some content that developers need to know to get started that few teach, such as:

- How (and why) to select an IDE
- basic command line (git) commands for committing to MDN
- basic command line commands (cd, pwd, history | grep) to navigate to help with the above.
- bash file: 
   - creating a bash file; 
   - changing permissions
   - accepting user input, like Y/N
   - Example, maybe automating the updating of MDN forks/directories 
- We have a js guide to regex, but adding a link to regex, and showing it in non js format.
- open to other ideas....

## Why is it important or useful?

Few teach these things, but learning them improves productivity

**Comment by Josh-Cena** [comment]
It's been two years and I don't think the community has reacted positively to this issue. The content is also spread across many learning articles, such as https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Command_line. Other things like IDEs and git are better off taught by an external tutorial because they evolve all the time and it's not the area we focus on.

As much as I love the idea of MDN being the training ground for new devs to practice tooling, I don't think we have the bandwidth to maintain documentation beyond web technologies, given the number of open issues regarding anything slightly less native, such as client-side frameworks.
