### ISSUE TITLE
HTML Cheatsheet doc is missing an explanation of <div> element

### ISSUE THREAD

**Issue by Sethsg7** [mdn/content#18823]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Cheatsheet

### What specific section or headline is this issue about?

The HTML Cheatsheet.

### What information was incorrect, unhelpful, or incomplete?

There is no explanation of `<div>` whatsoever.

### What did you expect to see?

An example of how `<div>` is used.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/html/cheatsheet`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Cheatsheet
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/cheatsheet/index.md
* Last commit: https://github.com/mdn/content/commit/6d890b9e01cf7b8511a147387e013fee8b072e0a
* Document last modified: 2022-05-05T03:09:52.000Z

</details>

**Comment by EndiyaKelvintaGinting09** [comment]
> ;lkjnhbvcx

**Comment by Andrew-Cottrell** [comment]
The [HTML Cheatsheet](https://developer.mozilla.org/en-US/docs/Learn/HTML/Cheatsheet) appears to focus on elements that are useful for creating accessible rich text snippets.

> That's the whole purpose of the cheatsheet, to give you some quick accurate ready to use code snippets for common usages.

It specifically calls out the requirement that HTML tags be used for their semantics.

> HTML tags must be used for their semantic, not their appearance.

The `div` element is devoid of semantics and those who are aware of it can always refer to its page

> As a "pure" container, the [`<div>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/div) element does not inherently represent anything.

I suggest `div` not be added to the HTML Cheatsheet.

---

The example for the `wbr` element uses a `div` element rather than a `p` element; I suggest it be changed to

```html
<p style="width: 200px">
  Llanfair<wbr>pwllgwyngyllgogerychwyrngogogoch.
</p>
```

---

The HTML Cheatsheet does include the `span` element, which is also devoid of semantics. However, it is useful for inline styling of rich text (e.g. fonts & colors).

> Used to group elements: for example, to `<span style="color:blue">style them</span>`.

**Comment by sideshowbarker** [comment]
@Andrew-Cottrell Thank, agreed

@Sethsg7 Thanks for raising this — as alluded to in https://github.com/mdn/content/issues/18823#issuecomment-1196396290, it seems that the `div` element is intentionally not included in the cheatsheet , because it’s not an element that  represents a specific structure or that has special semantics.

Given that, I’ve opened #18849 for adding a note with an explanation of why the `div` element isn’t included.
