### ISSUE TITLE
Hoisting of let and const

### ISSUE THREAD

**Issue by vmeet24** [mdn/content#18901]
### MDN URL

https://developer.mozilla.org/en-US/docs/Glossary/Hoisting

### What information was incorrect, unhelpful, or incomplete?

![Screenshot 2022-07-28 125439](https://user-images.githubusercontent.com/47553376/181594659-58c0a3e8-9b9d-4545-8c05-2dd507a2f1ac.png)

### What did you expect to see?

Although the accessing of let and const variable before initializing throws the error, still they are initialized with the default placeholder value undefined, the exact issue is they are created in a different memory than global memory (window)

![example](https://user-images.githubusercontent.com/47553376/181595343-042c52f6-c6fc-405d-92b2-8931c4a270a2.png)
.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/glossary/hoisting`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Hoisting
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/hoisting/index.md
* Last commit: https://github.com/mdn/content/commit/b06d0695cf809707b421f5202495209928e3519d
* Document last modified: 2022-04-27T05:45:53.000Z

</details>

**Comment by hamishwillee** [comment]
No, the information is correct. When you run the code you get the reference error. 

![image](https://user-images.githubusercontent.com/5368500/181655051-340c99e4-f32d-409b-bd47-b4c84e8135a6.png)

I don't know why the script variable x is shown as `undefined`. Perhaps @Josh-Cena might know.

**Comment by vmeet24** [comment]
I am not saying that it won't throw an error, but they are also initialized with the default `undefined` value just like the `var` variable it's just `let` and `const` are created in a different scope.

**Comment by hamishwillee** [comment]
@vmeet24 If the value was initialized to `undefined` you would not get _any_ error, as `undefined` is a valid value to log or access. 

The fact you get a `ReferenceError` tells you that the value is uninitialized or does not exist. That's what [ReferenceError](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError) means.

Are you basing your thinking on anything else other than the value shown in your screenshot above? I ask because the definitions used here come from the relevant specifications. So it is far more likely that the browser simply chooses to use the term "undefined" for an uninitialized value.

Let's see what @Josh-Cena says.

**Comment by Josh-Cena** [comment]
Hi @vmeet24 

It's often unclear to me what "hoisting" means. It's only meant to be a mental model, not rigorous terms used in the spec. I've expressed the same concern here: https://github.com/mdn/content/pull/18571

Basically, you are right: lexical declarations are hoisted. If they aren't hoisted, there's no way to implement temporal dead zone at all! Consider this code:

```js
function foo(x) {
  {
    console.log(x);
    let x = 1;
  }
}

foo(2);
```

If `let x` is not hoisted, then `x` should only be `1` after that line, and the first `console.log` should log `2`. However, because `let x` is _actually_ hoisted to the top of the scope, the engine knows that the `console.log` is logging the `x` value to be defined later instead of the `x` being shadowed in the upper scope, and will throw an error here. TDZ is a separate thing to be enforced by the engine, separate from its lexical scoping rules. (And it actually causes `let` to be slightly slower than `var` due to the extra runtime check.)

However, my question is, is that information really helpful? Quoting https://github.com/mdn/content/pull/18571#pullrequestreview-1045925734:

> When we say "hoisting", we really mean that "a variable can be safely used anywhere in this scope because the interpreter has already declared it as undefined". Otherwise, if accessing a variable always throws a reference error, I personally wouldn't care if it's because I'm in the TDZ, or because it's undeclared at all.

From a pragmatic point of view, I'll argue it's much simpler for us to say "it's not hoisted". The fact that the debugger says it's `undefined` before its actual declaration is largely an implementation detail—they can well say its value is `<In TDZ>` and prevent that confusion. I didn't read the V8 source and I don't know if it's literally `undefined` or just conveniently represented that way in the debugger.

As for your second question about "in a different memory than global memory", it's mentioned in [our docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let#description). `let` and `const` are "lexically scoped". `var` can only be in two scopes: "Global" or "Function". But for `let`, 
"Block" and "Script" can be scopes as well. This means if you have a `var`-declared variable in a script's top scope, you can reference that variable in a module imported later; the same isn't true for `let` because the module doesn't have access to the script's scope.

Does that make sense? I plan to rewrite that glossary entry anyway, and I'll likely remove the note that "`let` and `const` are hoisted" at all, since that's not quite useful.

**Comment by vmeet24** [comment]
>As for your second question about "in a different memory than global memory", it's mentioned in [our docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let#description). let and const are "lexically scoped". var can only be in two scopes: "Global" or "Function". But for let, "Block" and "Script" can be scopes as well. This means if you have a var-declared variable in a script's top scope, you can reference that variable in a module imported later; the same isn't true for let because the module doesn't have access to the script's scope.

ahh, maybe I missed this part from the docs.


>However, my question is, is that information really helpful? Quoting https://github.com/mdn/content/pull/18571#pullrequestreview-1045925734:
When we say "hoisting", we really mean that "a variable can be safely used anywhere in this scope because the interpreter has already declared it as undefined". Otherwise, if accessing a variable always throws a reference error, I personally wouldn't care if it's because I'm in the TDZ, or because it's undeclared at all.

From the pragmatic point of view, this information looks correct, but however still JavaScript, as we saw that it does hoist the let and const variable, so a more proper way would be to stick to the part `let and cost are hoisted too` because somewhere down the road again someone will come shouting that the doc is incorrect and `let and const are hoisted too` 🤣

**Comment by Josh-Cena** [comment]
As I said, it largely depends on how you interpret "hoist". If accessing it always throws a `ReferenceError` I personally don't feel like it's hoisted.

**Comment by hamishwillee** [comment]
MDN has wasted endless time on this point. I am pretty sure that whatever we do someone will complain.

I _think_ the right way to address this might be to remove almost all mentions of hoisting in the docs and replace them with explicit explanation of the declaration being moved to global scope vs where initialization happens. 

Then the hoisting article could be updated to explain that it was historically used to explain why you could call functions before they were declared etc. Cut it way back.

Upshot make the argument about whether something is hoisted or not irrelevant.

**Comment by hamishwillee** [comment]
Option one would be desirable to me if I thought it would work. Essentially it relegates hoisting to be "a useful way of describing a particular set of behaviours for functions". But the fact is that this won't work. If we define it this way we will be back where we started.

I lean towards the second, in particular if the "all" is true. Separating the declaration from the initialization part of the story is a good thing. It would be even better to describe all of these things without using the word hoisting - just the declaration and initialization.
