### ISSUE TITLE
“see the source code too” link in “From object to iframe” doc is 404 (the “gh-pages” branch part of the URL should be “main”)

### ISSUE THREAD

**Issue by alirezahs1** [mdn/content#19018]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Other_embedding_technologies

### What specific section or headline is this issue about?

Security Concerns

### What information was incorrect, unhelpful, or incomplete?

A quick example first though — try loading the previous example we showed above into your browser — you can [find it live on GitHub](https://mdn.github.io/learning-area/html/multimedia-and-embedding/other-embedding-technologies/iframe-detail.html) ([see the source code](https://github.com/mdn/learning-area/blob/gh-pages/html/multimedia-and-embedding/other-embedding-technologies/iframe-detail.html) too.)
-----
Source code link is a not-found link.

### What did you expect to see?

changing link's href to appropriate url.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/html/multimedia_and_embedding/other_embedding_technologies`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Other_embedding_technologies
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/multimedia_and_embedding/other_embedding_technologies/index.md
* Last commit: https://github.com/mdn/content/commit/586a27ce15c9be3fdf6aa8abfab40f2224947bd6
* Document last modified: 2022-07-11T05:24:25.000Z

</details>

**Comment by sideshowbarker** [comment]
There’s no 404 response shown when I follow the _“you can [find it live on GitHub](https://mdn.github.io/learning-area/html/multimedia-and-embedding/other-embedding-technologies/iframe-detail.html)”_ link indicated in the issue description.

Instead a page is shown; and in Firefox at least there’s a message similar to what the paragraph in the MDN article that link’s in states will be shown — which is, _“some kind of message to the effect of "I can't open this page"”_.

And in all browsers, a message is logged to the console — just at the paragraph in the MDN article says — stating the that browser refused to display the content of the iframe (due to `X-Frame-Options` being set to `DENY`.

**Comment by Josh-Cena** [comment]
@sideshowbarker The link the OP is referring to is the GitHub source link: https://github.com/mdn/learning-area/blob/gh-pages/html/multimedia-and-embedding/other-embedding-technologies/iframe-detail.html

**Comment by sideshowbarker** [comment]
> @sideshowbarker The link the OP is referring to is the GitHub source link: [https://github.com/mdn/learning-area/blob/gh-pages/html/multimedia-and-embedding/other-embedding-technologies/iframe-detail.html](https://github.com/mdn/learning-area/blob/gh-pages/html/multimedia-and-embedding/other-embedding-technologies/iframe-detail.html?rgh-link-date=2022-08-01T14%3A04%3A49Z)

Ah, OK yeah, I see now I didn’t read the issue description carefully enough. Thanks for catching it
