### ISSUE TITLE
Document.execCommand()

### ISSUE THREAD

**Issue by fusunyu** [mdn/content#1905]
Hi

I am new to web design. When I google Document.execCommand() I get links to the pages listed below. 

https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard

One page says Document.execCommand() is deprecated and this feature is no longer recommended. The other page is normal with the explanation.

What page has the correct information? 

Regards,

fu.

**Comment by Ryuno-Ki** [comment]
Hi @fusunyu.

Short answer: both :)

I've asked Chris the very same question the other day. You can find his answer in https://github.com/mdn/content/issues/1807#issuecomment-768971712

If that helps you, please close the issue :)

**Comment by jpmedley** [comment]
This is a fact of web development. There's often a newer version created because it's safer or more performant. To be interoperable, a script using a particular capability has to feature detect for the new version and provide a fallback for older browsers. Here's another article that covers clipboards, including feature detection. https://web.dev/async-clipboard/

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/1905#issuecomment-770276900
