### ISSUE TITLE
Add example in Promise.all section which indicates to use parentheses when using function inside Promise.all

### ISSUE THREAD

**Issue by MubashirWaheed** [mdn/content#19261]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all

### What specific section or headline is this issue about?

Add example showing you are supposed to add parenthesis with function inside promise.all()

### What information was incorrect, unhelpful, or incomplete?

In the `promise.all()` section there is no example which indicates that you are supposed to add parenthesis to the function that is passed to the `Promise.all()` 
After reading docs I thought I was not supposed to add parenthesis (similar to when function passed to `addEventListnere`) like 
`await Promise.all([addItems, addCategories])` 

### What did you expect to see?

Docs should clarify that you have to use parenthesis with the function that returns a promise otherwise it won't work. 
eg 
```js 
const addItems = async ()=>{
  // add data to the database 
  await item.save()
}

const addCategories = async ()=>{
  // add category to database 
  await category.save()
}
const seed = async ()=>{
  await Promsie.all([addItems(), addCategories()])
}
``` 

### Do you have any supporting links, references, or citations?

The answer to this question 
https://stackoverflow.com/questions/57981712/function-call-inside-promise-all

**Comment by wbamberg** [comment]
Thanks for filing, @MubashirWaheed !

> the function that is passed to the Promise.all()

Promise.all doesn't take an array of functions as parameters. It takes an array of promises. So by doing something like `Promise.all([addItems(), addCategories()])`, you're not "add[ing] parenthesis to the function that is passed". You're calling the functions yourself, and then passing the promises that they return into the function.

So I don't think this clarification is needed.

**Comment by Josh-Cena** [comment]
For context: we had been discussing this on another Discord server. I think there are several reasons why we should add this:

- `Promise.all()` is a good way to parallel several async functions. With async functions becoming the new standard, it's far too common for people to `await` everything and cause unnecessary blocking time.
- We don't demonstrate how async functions are used with `Promise.all` at all. It may be apparent that it's used to "parallel a series of promises", but frankly I think `Promise.all([addItems, addCategories])` reads quite naturally as well.
- We probably need to use async functions in more places in general, since that's how people write code in real life.
