### ISSUE TITLE
spellcheck attribute example does not work

### ISSUE THREAD

**Issue by AJamesPhillips** [mdn/content#19285]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck

### What specific section or headline is this issue about?

Try it

### What information was incorrect, unhelpful, or incomplete?

The example does not work.  No spell checking error is shown:

<img width="791" alt="image" src="https://user-images.githubusercontent.com/526509/183413259-3fc6f510-985b-49d4-a617-4b64747e2d4e.png">

### What did you expect to see?

The misspelt words should be underlined in red.

### Do you have anything more you want to share?

Using Firefox 103.0.1 on Mac 12.2.1

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/global_attributes/spellcheck`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/global_attributes/spellcheck/index.md
* Last commit: https://github.com/mdn/content/commit/d8b91c1b8d11694135ffa9722bd8fb1fb0eb06ea
* Document last modified: 2022-05-25T00:50:39.000Z

</details>

**Comment by teoli2003** [comment]
Note that the article explicitly says that browsers are "free" to choose to allow it on some elements or not.

It would be nice to have:
1. Examples that work everywhere (with `<textarea>`?)
2. In the article, a list of elements it works on.

**Comment by MasterInQuestion** [comment]
What about linking this issue in the original page?

**Comment by teoli2003** [comment]
Not sure, what is the original page?

**Comment by MasterInQuestion** [comment]
I mean adding the link of this issue [ [https://github<i>.</i>com/mdn/content/issues/19285](https://github.com/mdn/content/issues/19285) ] in [ [https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck) ] (the original page).

    Also, please review this [ [https://github<i>.</i>com/mdn/content/pull/19494](https://github.com/mdn/content/pull/19494) ].

**Comment by hanzl035** [comment]
https://github.com/mdn/content/issues/19285#issuecomment-1208151418 the spellcheck and contenteditable attributes work on 'p' elements in Firefox and Chrome on my computers (just not in the way the example author intended). The example appears to be broken because most browsers won't check the spelling of content unless that content is provided by the user.

>This specification does not define the user interface for spelling and grammar checkers. A user agent could offer on-demand checking, could perform continuous checking while the checking is enabled, or could use other interfaces.

If a word is edited by the user and misspelled in the example; a red underline will appear in both Chrome and Firefox. In Chrome, it appears the entire element is checked for spelling if any content is edited by a user. In Firefox, it appears only the words that were edited are checked for spelling (unless the element is a textarea).

It may be possible that the content will load with red underlines upon refresh (because the attribute trigger is supposed to be sticky I think). However, I haven't been able to get red underlines without a user edit (even if the element is a textarea).

The existing example could be rephrased, prompting a user to input incorrectly spelled words into a contenteditable p element. There should probably be a note that most browsers have opted to check spelling on-demand. Spellchecking for textarea elements is turned on by default; another good example would be using this attribute to turn off spellchecking in a textarea element.

**Comment by AJamesPhillips** [comment]
Thanks @hanzl035 .  I tried deleting all the text and replacing with mispelt words but it still did not highlight any spelling mistakes:

<img width="787" alt="image" src="https://user-images.githubusercontent.com/526509/192270065-5e6292bd-d3da-45e6-ba32-d6f19bb9fa4b.png">

**Comment by Nickel-sudo** [comment]
Has anyone figured out how to fix it meanwhile or is there a solution for it? I face the same issues regarding spellCheck in Firefox as described above. Spell Check is not triggered at all when using either `<textarea>` or `<p>`.

**Comment by Nickel-sudo** [comment]
I don't know if it matters, but I am using React for my current project. I have not found any informations up so far that this is  an React issue.
