### ISSUE TITLE
box-shadow on 'ugly' styled example — specifically mentioned for the text, datetime-local, and color inputs but it doesn't appear and dev tools states “invalid property value” with a line through the entry

### ISSUE THREAD

**Issue by jakemadash** [mdn/content#19375]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Forms/Advanced_form_styling

### What specific section or headline is this issue about?

What can be done about the "ugly" elements?

### What information was incorrect, unhelpful, or incomplete?

Box shadow is applied and specifically mentioned for the text, datetime-local, and color inputs in this section, but it doesn't appear and dev tools states invalid property value with a line through the entry.

### What did you expect to see?

Box shadow

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/forms/advanced_form_styling`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/Advanced_form_styling
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/forms/advanced_form_styling/index.md
* Last commit: https://github.com/mdn/content/commit/05324ee8658ea78ab284a736511581effbaf784b
* Document last modified: 2022-07-22T04:34:33.000Z

</details>

**Comment by Josh-Cena** [comment]
It's valid on the latest Chrome and Firefox in both mac and Windows.

<img width="498" alt="image" src="https://github.com/mdn/content/assets/55398995/45de6ee0-f616-4cdf-8961-a31510797973">

(Changed to red for visibility)

So if it didn't show it was probably a browser bug. In any case there's nothing the content can do since at least _some_ browsers support it and it's a standard thing.
