### ISSUE TITLE
The term *(a)synchronous callback* is used to suggest the execution of a callback function after a (a)synchronous operation

### ISSUE THREAD

**Issue by rounakcodes** [mdn/content#19522]
### MDN URL

https://developer.mozilla.org/en-US/docs/Glossary/Callback_function

### What specific section or headline is this issue about?

Callback function

### What information was incorrect, unhelpful, or incomplete?

The above example is a [synchronous](https://developer.mozilla.org/en-US/docs/Glossary/Synchronous) callback, as it is executed immediately.
...
Note, however, that callbacks are often used to continue code execution after an [asynchronous](https://developer.mozilla.org/en-US/docs/Glossary/Asynchronous) operation has completed — these are called asynchronous callbacks.

### What did you expect to see?

The above example is a callback executed after a [synchronous](https://developer.mozilla.org/en-US/docs/Glossary/Synchronous) operation.
...
Note, however, that callbacks are often used to continue code execution after an [asynchronous](https://developer.mozilla.org/en-US/docs/Glossary/Asynchronous) operation has completed.

### Do you have any supporting links, references, or citations?

Not applicable since the same document starts with the contradiction when it defines the meaning of a callback function.

### Do you have anything more you want to share?

The section starts with *A callback function is a function passed into another function as an argument*. 
Hence, `greeting` is a callback function.
This callback function is being called after synchronous operations in `processUserInput` function.

*Note, however, that callbacks are often used to continue code execution after an [asynchronous](https://developer.mozilla.org/en-US/docs/Glossary/Asynchronous) operation has completed — these are called asynchronous callbacks.*

So, I don't understand why the callback function is being called synchronous or asynchronous when the intent is to refer to the synchronous or asynchronous behavior of the code executing before the callback function.  

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/glossary/callback_function`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Callback_function
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/callback_function/index.md
* Last commit: https://github.com/mdn/content/commit/6caf2ef2cd8b610e6fe9dfc94059b835560a3af5
* Document last modified: 2022-08-10T09:35:15.000Z

</details>

**Comment by Josh-Cena** [comment]
I think you're right. `prompt` is a terrible example because it's actually blocking so it's synchronous after all. `setTimeout` would be much better.

**Comment by rounakcodes** [comment]
@Josh-Cena Seems like I have not been able to express myself correctly. I will try again.

The document starts with *A callback function is a function passed into another function as an argument.*
In the example, *greeting* is the function passed into another function. So, *greeting* is the callback function.

*The above example is a [synchronous](https://developer.mozilla.org/en-US/docs/Glossary/Synchronous) callback, as it is executed immediately.*

What I understand from reading the above statement:
*greeting* is a synchronous callback because the code preceding the execution of the callback is executing synchronously.
What I think:
We have agreed that *greeting* is the callback function earlier. I am not able to understand why the code preceding the callback function (`function processUserInput(callback) {
  const name = prompt('Please enter your name.');`) gets to decide whether the callback should be called *synchronous* or *asynchronous*.

**Comment by Josh-Cena** [comment]
Ah. There are two kinds of callbacks: _synchronous_ and _asynchronous_. Whether the callback is synchronously and asynchronously called depends on the caller, not the user. For example:

```js
let i = 0;
doSomething(() => {
  i = 1;
});
console.log(i);
```

Can you tell me what the value of `i` is when `console.log()` happens? You generally can't without `doSomething` telling you if it's synchronously or asynchronously calling the `() => i = 1` callback. If it's sync, then by the time `doSomething()` returns, `i` is already `1`. But if it's async, then the callback is actually enqueued and won't be executed after the main loop is emptied, and it will log `0` instead.

Distinguishing between sync and async callbacks is very important because it influences control flow analysis. A famous ["state of Zalgo"](https://blog.izs.me/2013/08/designing-apis-for-asynchrony/) is when a callback can be _both_ async and sync—this basically destroys all expectations of the user.

You are asking why `function processUserInput(callback) { const name = prompt('Please enter your name.');` decides whether it's sync or async. Remember JS is always sync, so the only way to "break out" of the main loop is by invoking some async machinery, such as the use of promises, async-await, or `setTimeout`. There's none here, so it's a sync callback. What I'm suggesting is we should have another async callback example, like `setTimeout(callback)`.

**Comment by rounakcodes** [comment]
Thanks for the explanation. I guess this issue can be closed as far as the original intention of opening it is concerned. 
You (or someone) can decide whether the discussion for your suggestion needs to be continued here or in a new issue.

**Comment by Josh-Cena** [comment]
I think we need to improve that glossary entry here, since it's hand-wavy about what async and sync callbacks actually are.
