### ISSUE TITLE
performance information regarding `.hasOwnProperty()` in `Object.hasOwn()`

### ISSUE THREAD

**Issue by rafael-lucas-rlns** [mdn/content#19775]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn

### What information was incorrect, unhelpful, or incomplete?

...
Note: [`Object.hasOwn()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn) is recommended over `hasOwnProperty()`, in browsers where it is supported.
...

### What did you expect to see?

although the recommendation to use `Object.hasOwn(OBJECT, KEY)` instead of `OBJECT.hasOwnProperty(KEY)` is preferable to use `.hasOwnProperty()` because its performance is better. As the intent here usually resorts to iterations, `Object.hasOwn()` should only be recommended in specific situations.

At least that information should be reported on the page so people can get the best performance.

### Do you have any supporting links, references, or citations?

simple tests were performed with `console.time()` and `console.timeEnd()` showing that on average `.hasOwnProperty()` will perform better than `Object.hasOwn()`

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/object/hasown`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/object/hasown/index.md
* Last commit: https://github.com/mdn/content/commit/ae586f9996f622b40379283f727febe94258b8c0
* Document last modified: 2022-08-09T05:43:41.000Z

</details>

**Comment by Josh-Cena** [comment]
This has nothing to do about performance. The reason is explained further down the line: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn#description

> It is recommended over [`Object.hasOwnProperty()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty) because it works for objects created using `Object.create(null)` and with objects that have overridden the inherited `hasOwnProperty()` method. While it is possible to workaround these problems by calling `Object.prototype.hasOwnProperty()` on an external object, `Object.hasOwn()` is more intuitive.

Calling `x.hasOwnProperty()` is virtually never safe and will be flagged by linters. People always use `Object.prototype.hasOwnProperty.call()`, making the perf point moot. Also, these kinds of micro-optimizations on constant time are pretty minute.

**Comment by rafael-lucas-rlns** [comment]
the point I am referring to is that I believe performance information should be present in the note as it is an inferior method. The difference doesn't appear to be very small in scale, but the percentages have always been that way. 1/3 is already a good margin, but compared to others like Spread Operator, which is one of the worst iterators, it's really very little in my opinion.

I don't understand the security issue, because JavaScript itself has never been secure. I see no difference in accessing the object itself or the constructor as a whole if everything is easily tampered with. I always think that if I'm worrying about making sure something doesn't get tampered with, maybe I shouldn't be going through JavaScript.

**Comment by Josh-Cena** [comment]
_Rewriting_ global properties is always a code smell; _overriding_ built-in properties is okay and hard to detect. For example, this will be instantly called out, and is safe to assume that it doesn't happen:

```js
Object.hasOwn = () => 42;
```

This cannot be assumed to never happen:

```js
const obj = { hasOwnProperty: () => 42 };
```

`Object.create(null)` will make a naïve `x.hasOwnProperty(y)` fail as well. Every linter will tell you to change it to `Object.prototype.hasOwnProperty.call` instead. I encourage you to check the proposal motivation for more details: https://github.com/tc39/proposal-accessible-object-hasownproperty

Re: performance, 1e9 ops/s is fairly instant. If you look at the absolute value, you have to check a million times to notice a 1ms difference. At that scale your program probably runs for seconds anyway. The difference is probably because `hasOwn()` is newer: all new methods take time to be optimized. Hard to tell there's anything inherent about `hasOwn()` that can make it slower.

**Comment by Josh-Cena** [comment]
Premature optimization is out of scope for MDN. We tell you to prefer `for...of` over `for(;;)` because we think readability is far, far more important than a few milliseconds' perf improvement. We tell you to use `let` over `var` because it prevents many programmer mistakes, even when it comes at a worse performance due to the TDZ check. We don't even think there's a tradeoff in any normal-scale app. It cannot be said more: "optimize at the bottleneck; optimize at the hotspot". I haven't heard of anyone complaining about the perf of `hasOwn`.

**Comment by teoli2003** [comment]
Yes, the saying is "Premature optimization is the root of all evil" (which doesn't mean you shouldn't think about the complexity of algorithms).

Thank you for your interest, but we'll not add such information.

**Comment by rafael-lucas-rlns** [comment]
> Premature optimization is out of scope for MDN. We tell you to prefer `for...of` over `for(;;)` because we think readability is far, far more important than a few milliseconds' perf improvement. We tell you to use `let` over `var` because it prevents many programmer mistakes, even when it comes at a worse performance due to the TDZ check. We don't even think there's a tradeoff in any normal-scale app. It cannot be said more: "optimize at the bottleneck; optimize at the hotspot". I haven't heard of anyone complaining about the perf of `hasOwn`.

I also believe that readability is important, and I like to write things that are simple and easy to understand, but it still depends on the cost x benefit. When you get to the point of writing code that saves a few characters but takes double or triple the time, maybe it's time to rethink what readability is. Who am I to say anything, but I just agree with Crockford on this point.

> Yes, the saying is "Premature optimization is the root of all evil" (which doesn't mean you shouldn't think about the complexity of algorithms).
> 
> Thank you for your interest, but we'll not add such information.

I understand. thanks for your attention and time.
