### ISSUE TITLE
[Not Release] [CSS] Support for @font-face src: descriptor's "tech(...)" syntax

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#19833]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN - NA
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate - NA
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

Support for @font-face src: descriptor's "tech(...)" syntax

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1715546

**Comment by hamishwillee** [comment]
This is behind a pref, mostly because there is still discussion around some of the syntax. Because of that there is no point doing docs for this yet. Just BCD and an update to experimental features.

Status

- [ ] BCD https://github.com/mdn/browser-compat-data/pull/17815
- [ ] Docs - NA
- [ ] Experimental features
- [ ] Dev-doc-complete
