### ISSUE TITLE
Archive flexbox mixins page

### ISSUE THREAD

**Issue by rachelandrew** [mdn/content#1997]
While searching MDN for references to interface mixins, I came across this page: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Mixins

This is pretty irrelevant information at this point, if a person really needs to support very old browsers they are probably better to use Autoprefixer, we also document fallback techniques here https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Backwards_Compatibility_of_Flexbox

I suggest we remove the mixins page.

**Comment by chrisdavidmills** [comment]
I'd be happy for you to remove it outright, and then add a redirect to the backwards compat section you cite.

**Comment by hamishwillee** [comment]
@rachelandrew Awesome.

FWI only I had a chat about archiving with Chris last night. I'm pushing for:
1. Archive-specific link markup
1. Deletion of archive links if possible. 
1. Deletion rather than archive if possible. If archive, "reason" added to doc metadata so that someone later can work out whether it is reasonable to delete.

I hate throwing away information, but unless there is a certain ruthlessness you eventually end up with more crap than good content.

**Comment by rachelandrew** [comment]
@hamishwillee yeah I think deleting it is probably the way to go, it is probably more of a distraction than a help to anyone who finds it.

**Comment by Ryuno-Ki** [comment]
> I hate throwing away information, but unless there is a certain ruthlessness you eventually end up with more crap than good content.

Given you are using git now, that information isn't lost even if „thrown away” (you can dig up the git history to look up what it was).

So … for developers, there's the recommendation to _delete_ code instead of comment it. Because version control.
