### ISSUE TITLE
Issue with "Test your skills: Strings": (Strings 1 exercise)

### ISSUE THREAD

**Issue by peaktemplate** [mdn/content#2004]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Test_your_skills:_Strings

#### What information was incorrect, unhelpful, or incomplete?
para1   displays a SyntaxError: Unexpected identifier

#### Specific section or headline?
Problem is the declaration of the string variable.

let quoteStart = 'Don't judge each day by the harvest you reap ';

The word Don't creates the error... and it doesn't go away even if you get the answer corrrect.. I tried in VS Code as well.

The line should be written like this..

let quoteStart = "Don't judge each day by the harvest you reap "; (Double Quotes works - because of the single quote in the word Don't)

#### Did you test this? If so, how? Yes using VS Code.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/test_your_skills_colon__strings`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Test_your_skills:_Strings
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/javascript/first_steps/test_your_skills_colon__strings/index.html
* Last commit: https://github.com/mdn/content/commit/88b8dc61828f0c111b5eda4197921dcf153f3b0f
* Document last modified: 2020-12-15T16:53:05.000Z

</details>

**Comment by chrisdavidmills** [comment]
Hi @peaktemplate !

You are right that there is an error with `quoteStart`. This is part of the exercise.

There is a line in the exercise that says "You'll find that you get an error at this point. Can you fix the problem with `quoteStart`, so that the full quote displays correctly?" This is the error that the line is referring to.

I think we can close this one now, but feel free to reach out if you have any further thoughts.
