### ISSUE TITLE
api.HTMLSelectElement - write page for 'autocomplete'

### ISSUE THREAD

**Issue by XX-J** [mdn/content#2016]
`HTMLSelectElement.autocomplete` appears to be undocumented on MDN: it's not mentioned in the body of the `HTMLSelectElement` page and the `autocomplete` page does not yet exist.

<details><summary>Screenshots:</summary>

![1](https://jpegshare.net/images/a0/34/a0349a202038bb6fc33b08d32f3cce04.png)
----------
![2](https://jpegshare.net/images/a0/73/a073a8150829205ea446aa0dceba5635.png)
</details>

<details>
<summary>MDN page report details</summary>

* Query: `api.HTMLSelectElement`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement
* Report started: 2021-01-18T17:09:42.254Z

</details>

**Comment by dscotese** [comment]
I asked Google Bard to do this and it basically took [the autocomplete attribute documentation](https://developer.mozilla.org/docs/Web/HTML/Attributes/autocomplete) and removed all the pieces that don't apply to SELECT elements.  I didn't know that page existed and I didn't realize that there are two different things here which we call "autocomplete", an attribute and a property.  It might be a good idea for MDN to establish a standard operating procedure for items that are both attributes and properties.  The fact that I was aware of the existence of both attributes and properties and never really bothered to distinguish between them until now suggests that the page for the documentation of either should have a link to the other.

An example is "multiple" which, at least on an input element, is both [a property](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/multiple) and also [an attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/multiple).  Is there a programmatic way to identify all pages that document something which is both, and add a note to each of them like "See the [whatever property/attribute](#)"?

I also looked at how this worked for the attributes of HTML elements and the properties of the API objects.  For the API objects, I checked [input elements](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement), [textarea elements](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement), and [form elements](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement), all of which suffer from the same issue (having "autocomplete" in the BCD point to a nonexistent page).

For HTML elements, I checked [input elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#autocomplete) and [textarea elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea) and [form elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#autocomplete), all of which include the documentation for the autocomplete attribute in the page itself.

@ddbeck  pointed out that we don't usually link from properties to their reflected attributes.  This is a good idea because we don't want to promote confusion between them.  However, rather than avoiding making the link, it makes more sense to me to be explicit that the API uses properties while HTML uses attributes, and then provide readers with a handy way to get from one to the other.  Our presentation of the semantics of anything that might be both may change over time, and when the attribute really is a reflection of the property (as usual), this requires us to make those updates in two places.  For this reason, I think the next step for this issue is to establish some kind of policy around items that are both attributes and properties, and start to tighten the interdependence between the API documentation and the HTML documentation with an explicit distinction between attributes and properties.

I propose that the basic functionality of something like autocomplete be presented in the HTML documentation and any more nuanced explanation be presented in the API docs, and for each of them to rely on the other.  For example, the HTML docs for multiple would explain that an input can provide several values, and having "multiple" or "multiple='true'" in the opening tag is how you enable that, with a note pointing to the API page for multiple like "for more information, see the [multiple property](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/multiple)", and most of the nuance explained in the current [multiple attribute page]() would be presented in the property page instead.  They are currently reversed, and maybe that is better.  Right now, the property documentation doesn't link to the attribute which explains some stuff that the reader of the property documentation might want to know.

**Comment by Josh-Cena** [comment]
Hi! I'm closing this in favor of https://github.com/mdn/mdn/issues/520 so it can be done in a more organized way.
