### ISSUE TITLE
XMLHttpRequest withCredentials option has an impact on same-site/cross-origin requests

### ISSUE THREAD

**Issue by AtofStryker** [mdn/content#20441]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials

### What specific section or headline is this issue about?

XMLHttpRequest withCredentials

### What information was incorrect, unhelpful, or incomplete?

Setting withCredentials has no effect on same-site requests.

### What did you expect to see?

Setting withCredentials has no effect on same-origin requests.

### Do you have any supporting links, references, or citations?

I believe that setting withCredentials **does** have an effect on same-site requests, in particular `same-site` requests that are cross origin.

If I am on origin `https://app.testme.com:3506`, and have cookie `foo=bar; Domain=.testme.com; SameSite=Strict` set in my browser, and make a request via `XMLHttpRequest` to `https://www.testme.com:3507` (same-site/cross-origin), the cookie is not sent with the request, nor can the response from `https://www.testme.com:3507` set cookies. However, if I follow the same exact flow, but the `XMLHttpRequest` to `https://www.testme.com:3507` has `withCredentials` set to `true`, cookie `foo=bar` is sent with the request and the response is able to set 1st/3rd party cookies. Based on this, I believe setting `withCredentials` has an impact on `same-site` requests, but does not have an impact on `same-origin` requests. 

This behavior seems to be consistent in firefox and chromium browsers. Not sure if it is entirely useful but I have created a reproduction repository [here](https://github.com/AtofStryker/understanding-cookie-behavior).

### Do you have anything more you want to share?

If we are all in agreement that the documentation is incorrect, I have no issues opening a PR to fix the issue 😃

**Comment by sideshowbarker** [comment]
Thanks much for catching this and reporting it.

I think the existing statements _“Setting `withCredentials` has no effect on same-site requests”_ and _“This never affects same-site requests”_ at https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials are just wrong and need to be removed.

Per-spec, the behavior relates only to whether a request is cross-origin. And a same-site request from one origin to a different origin is still a cross-origin request — whether it’s same-site or not is irrelevant to the handling of credentials.

And at https://xhr.spec.whatwg.org/#ref-for-dom-xmlhttprequest-withcredentials① the spec says:

> True when [credentials](https://fetch.spec.whatwg.org/#credentials) are to be included in a cross-origin request. False when they are to be excluded in a cross-origin request and when cookies are to be ignored in its response. Initially false.

That is, the spec itself only cites cross-origin requests — and doesn’t say anything at all about same-site requests.

If fact “same-site” isn’t mentioned anywhere at all in the XHR spec. And while the Fetch spec does define some requirements related to same-site behavior, it doesn’t define any special requirements for handling of credentials in the same-site case.

> If we are all in agreement that the documentation is incorrect, I have no issues opening a PR to fix the issue 😃

Please do go ahead and open a PR — given that those  _“Setting `withCredentials` has no effect on same-site requests”_ and _“This never affects same-site requests”_ statements in the MDN article don’t conform to the actual spec requirements, nor to actual browser behavior.

**Comment by sideshowbarker** [comment]
It occurs to me that whoever made the change that added the _“Setting `withCredentials` has no effect on same-site requests”_ and _“This never affects same-site requests”_ statements probably didn’t intend “same-site” in the strict technical as defined at https://html.spec.whatwg.org/multipage/origin.html#same-site — that is, two sites with the same registrable domain https://url.spec.whatwg.org/#host-registrable-domain — but instead intended it to mean just “same-origin”.

So I guess rather than removing those statements completely, we could just change them to  _“Setting `withCredentials` has no effect on **same-origin** requests”_ and _“This never affects **same-origin** requests”_.

And anyway I guess this is a good data point to highlight that in MDN docs we should avoid using the term “same-site” unless it’s a hyperlinked citation to https://html.spec.whatwg.org/multipage/origin.html#same-site or to wherever in MDN itself we might have a corresponding definition for “same-site” with the meaning “having the same registrable domain”.

And otherwise in general we should use the terms “same-origin” and “not cross-origin” when we refer to two sites with the same origin.

**Comment by AtofStryker** [comment]
> So I guess rather than removing those statements completely, we could just change them to “Setting withCredentials has no effect on same-origin requests” and “This never affects same-origin requests”.

Thank you for triaging this so quickly @sideshowbarker! I created a PR #20486 that has this suggestion in it, which is a nice and simple change.
