### ISSUE TITLE
XMLHttpRequest Synchronous Mode - Missing Compatibility Table

### ISSUE THREAD

**Issue by Retsam** [mdn/content#20602]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Synchronous_and_Asynchronous_Requests

### What specific section or headline is this issue about?

Synchronous request - deprecation notice

### What information was incorrect, unhelpful, or incomplete?

The deprecation notice refers (and links to) a compatibility table which no longer exists.

### What did you expect to see?

A compatibility table, or else the references to it removed in the deprecation notice.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/xmlhttprequest/synchronous_and_asynchronous_requests`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Synchronous_and_Asynchronous_Requests
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/xmlhttprequest/synchronous_and_asynchronous_requests/index.md
* Last commit: https://github.com/mdn/content/commit/073f70e052ff92ab715df3c20678c11c9b51747f
* Document last modified: 2022-09-09T05:23:40.000Z

</details>

**Comment by Josh-Cena** [comment]
That deprecation banner created by a macro, which doesn't have the context of whether the page actually has a compat table... I don't know what to do here.

**Comment by sideshowbarker** [comment]
@Retsam Thanks for raising this — I’ve opened #21038 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.

> Maybe we should just use a regular `Warning` callout.

I think we don’t even need that — because the first paragraph of the section already says this:

> Synchronous XHR requests often cause hangs on the web. But developers typically don't notice the problem because the hang only manifests with poor network conditions or when the remote server is slow to respond. Synchronous XHR is now in deprecation state. The recommendation is that developers move away from the synchronous API and instead use asynchronous requests.

…which seems pretty clear. It doesn’t seem like putting it into a `Warning` callout would make it any more clear (and we’ve had some debates in the past about whether in general some articles overuse such callouts to the point that readers might be more likely to ignore them — due to banner blindness — than they would normal prose).
