### ISSUE TITLE
Issue with "super": …

### ISSUE THREAD

**Issue by smallscript** [mdn/content#208]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/super

#### What information was incorrect, unhelpful, or incomplete?
Incomplete

#### Specific section or headline?
`super` does not work as expected with `extends` when designing "mixin" composition. It does not follow traditional dynamic language semantics for `super`; especially in respect to Smalltalk definition of `super`.

#### What did you expect to see?
See comments IN:
https://stackoverflow.com/questions/64395149/how-is-the-value-of-super-determined-compared-to-this/65298925#65298925

#### Did you test this? If so, how?
See comments and details in:
https://stackoverflow.com/questions/64395149/how-is-the-value-of-super-determined-compared-to-this/65298925#65298925

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/super`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/super
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/operators/super/index.html
* Report started: 2020-12-15T02:18:19.476Z

</details>

**Comment by sideshowbarker** [comment]
Along with the Stack Overflow answer cited in the issue description — which has since been deleted, and so now is only readable by people who have a 10,000+ reputation score on Stack Overflow — the accepted answer at https://stackoverflow.com/questions/64395149/how-is-the-value-of-super-determined-compared-to-this/64433115#64433115 may also be an enlightening to anybody who’s interested in refining the https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/super to make it more clearly explain how `super` is determined, and whether it’s affected by execution context, etc.

**Comment by Josh-Cena** [comment]
I have a feeling this is fixed by https://github.com/mdn/content/pull/16291 already.
