### ISSUE TITLE
Misleading note below provided example code

### ISSUE THREAD

**Issue by andrejs-ps** [mdn/content#20830]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String

### What specific section or headline is this issue about?

Comparing strings

### What information was incorrect, unhelpful, or incomplete?

There's a code snippet and a comment:

> function isEqual(str1, str2) {
>   return str1.toUpperCase() === str2.toUpperCase();
> }
> 
> Upper case is used instead of lower case in this function, due to problems with certain UTF-8 character conversions.

In the context of the presented function above, there should be no difference in using between `toUpperCase()` and  `toLowerCase()`. 

Yes, given e.g. German character `ß`, the code `'ß'.toUpperCase().toLowerCase()` would fail to make the round trip - `ß` would be converted to upper `SS` and then to lower `ss`. However, if we just do a one-off comparison, then both `toUpperCase()` and  `toLowerCase()` should yield the same result with all UTF-8 characters. (or I'm not aware of such characters)

### What did you expect to see?

Suggestion to change the comment to something like below:

Be aware that a small group of characters, when they are converted to lowercase, cannot make a round trip. For example, a German  `"ß".toUpperCase()` results in `SS`, however "SS".toLowerCase() results in "ss".

### Do you have any supporting links, references, or citations?

https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1308

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/string`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/string/index.md
* Last commit: https://github.com/mdn/content/commit/9b38f886d21c5d0a428f58acb20c4d0fc6c2e098
* Document last modified: 2022-09-12T13:06:56.000Z

</details>

**Comment by Josh-Cena** [comment]
Interesting—if we factor in `ß`, then `toLowerCase` should be a better choice than `toUpperCase`, because it's showing how `toUpperCase` is not an injection (while `toLowerCase` may be). In other words, we want an algorithm that does not treat strings that are apparently not equal as equal—e.g. `isEqual("ß", "ss")`. I'm wondering if this note is referencing `"I".toLowerCase()` vs. `"I".toLocaleLowerCase("tr")`, but it's so handwavy that it's impossible to tell at this point. If you want to send a PR with the suggested reword, I can take a look. In general, neither `toUpperCase` nor `toLowerCase` is an injection so neither can guarantee roundtripping.

**Comment by andrejs-ps** [comment]
Could you please clarify what you mean by "not an injection"? Thanks.

**Comment by Josh-Cena** [comment]
An [injective function](https://en.wikipedia.org/wiki/Injective_function) $f$ is one such that if $A\neq B$ then $f(A)\neq f(B)$, i.e. it's one-to-one, not many-to-one. However it's possible for two distinct sequences to map to the same sequence under `toUpperCase`, hence the latter is not an injection.
