### ISSUE TITLE
Box Shadow generator has no box shadow properties at all.

### ISSUE THREAD

**Issue by b-hayes** [mdn/content#20983]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Backgrounds_and_Borders/Box-shadow_generator

### What specific section or headline is this issue about?

This is not a box shadow genorator

### What information was incorrect, unhelpful, or incomplete?

There is no shadow properties here.

### What did you expect to see?

something more like this
https://html-css-js.com/css/generator/box-shadow/

### Do you have any supporting links, references, or citations?

I arrived at the site from a link supplied as a typhint for the box-shadow property in PhpStorm.

### Do you have anything more you want to share?

nope

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/css_backgrounds_and_borders/box-shadow_generator`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Backgrounds_and_Borders/Box-shadow_generator
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_backgrounds_and_borders/box-shadow_generator/index.md
* Last commit: https://github.com/mdn/content/commit/f4f8e2f18ccf19a0bee59e1fe78753e276b98232
* Document last modified: 2022-09-09T07:06:10.000Z

</details>

**Comment by wbamberg** [comment]
If you click the "+" button at the top-left, it adds a shadow to the element:

<img width="591" alt="Screen Shot 2022-09-22 at 7 26 00 PM" src="https://user-images.githubusercontent.com/432915/191881710-8e890416-f1e4-4c53-ad51-bce1b44a6a0e.png">

In what way is this not a box shadow?

It is unfortunate that the layout is rather broken ever since the redesign (https://github.com/mdn/yari/issues/5392) but that's a separate issue.

**Comment by b-hayes** [comment]
Ohhh right. I was just seeing this:
<img width="739" alt="image" src="https://user-images.githubusercontent.com/30540495/191887427-f952f7fa-b93c-4350-815e-968bce20d45d.png">
And thinking wtf, none of these sliders is for box shadow.

User error my bad.
