### ISSUE TITLE
Chrome Etag not working

### ISSUE THREAD

**Issue by truongnc1** [mdn/content#21279]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag

### What specific section or headline is this issue about?

Chrome Etag not working

### What information was incorrect, unhelpful, or incomplete?

Chrome Etag not working, not show status 304.

### What did you expect to see?

Chrome Etag not working

### Do you have any supporting links, references, or citations?

Chrome Etag not working

### Do you have anything more you want to share?

Chrome Etag not working

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/headers/etag`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/etag/index.md
* Last commit: https://github.com/mdn/content/commit/36001a269f4d7b2b3ac6de79e942a5f849bb87d8
* Document last modified: 2022-09-09T05:53:39.000Z

</details>

**Comment by sideshowbarker** [comment]
There doesn’t seem to be anything actionable for MDN in the issue description.

If the problem is that something is not working as expected in Chrome, then see https://support.google.com/chrome/answer/95315?hl=en&co=GENIE.Platform%3DDesktop for instructions on how to report that.

Otherwise, a site such as Stack Overflow might be a suitable place to ask.
