### ISSUE TITLE
Redundant sentence on Crypto.getRandomValues() page

### ISSUE THREAD

**Issue by bitboxx** [mdn/content#21385]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues

### What specific section or headline is this issue about?

Crypto.getRandomValues()

### What information was incorrect, unhelpful, or incomplete?

This sentence below is now redundant, as there's `randomUUID()` in the insecure context.

_`getRandomValues()` is the only member of the Crypto interface which can be used from an insecure context._

### What did you expect to see?

This sentence is redundant and can be removed.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/crypto/getrandomvalues`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/crypto/getrandomvalues/index.md
* Last commit: https://github.com/mdn/content/commit/da88b2f3a23b9d93f083003f13c06f9d96073f6a
* Document last modified: 2022-09-13T05:21:27.000Z

</details>

**Comment by sideshowbarker** [comment]
> This sentence below is now redundant, as there's `randomUUID()` in the insecure context.

Per the IDL in the spec at https://w3c.github.io/webcrypto/#ref-for-dfn-Crypto-2, the  [`randomUUID()`](https://w3c.github.io/webcrypto/#dfn-Crypto-method-randomUUID) method is marked with the [`SecureContext`](https://webidl.spec.whatwg.org/#SecureContext) attribute — which indicates that it does in fact requires a secure context.

And the interface has only three members: [`subtle`](https://w3c.github.io/webcrypto/#dfn-Crypto-attribute-subtle), [`getRandomValues()`](https://w3c.github.io/webcrypto/#dfn-Crypto-method-getRandomValues), and [`randomUUID()`](https://w3c.github.io/webcrypto/#dfn-Crypto-method-randomUUID) — and since both `subtle` and `randomUUID()` are marked as needing a secure context, then that does seem to mean the _“`getRandomValues()` is the only member of the Crypto interface which can be used from an insecure context”_ statement is correct.

So I’m going ahead and closing this — but if there’s some new information that we’ve somehow missed, this issue can be revisited.
