### ISSUE TITLE
The description of two-value border syntax is confusing

### ISSUE THREAD

**Issue by DomOBU** [mdn/content#21628]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/border-width

### What information was incorrect, unhelpful, or incomplete?

Hello,

Am I making a logical mistake?

In border-style it is written in the topic Syntax:
_/* top and bottom | left and right */ 
border-style: dotted solid;
When two values are specified, the first style applies to the top and bottom, the second to the left and right._

In border-width it is written in the topic Syntax:
_/* vertical | horizontal */ 
border-width: 2px 1.5em;
When two values are specified, the first width applies to the top and bottom, the second to the left and right._

Logically, isn't top and bottom equal to horizontal and left and right to vertical?
This would be consistent between the 2 descriptions.
In addition, in the CSS example #bival confirms my remark.

If my remark is relevant, it will also be necessary to update the French page.

### What did you expect to see?

/* horizontal | vertical */ 
border-width: 2px 1.5em;

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/border-width`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/border-width
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/border-width/index.md
* Last commit: https://github.com/mdn/content/commit/44439c7254c9da1797e4438bade0f8e8984cbc35
* Document last modified: 2022-09-27T22:38:41.000Z

</details>

**Comment by wbamberg** [comment]
I see how this is confusing!

I think the idea is that border is part of the basic box model properties, along with [`margin`](https://developer.mozilla.org/en-US/docs/Web/CSS/margin) and [`padding`](https://developer.mozilla.org/en-US/docs/Web/CSS/padding), and they all have the same syntax: with two-value syntax
- the first value  syntax sets margin, padding, border on the top and bottom
- the second value sets them on the left and right.

"Top and bottom" are called "vertical" I suppose because they contribute to the height occupied by the item. But I can totally see how the top/bottom borders run horizontally, and the left/right ones run vertically.

Perhaps (for border especially) it would be clearer to avoid "vertical" and "horizontal" and do the same thing as `border-style already does

```
/* top and bottom | left and right */
border-width: 2px 1.5em;
```

?

**Comment by DomOBU** [comment]
Thank you for your answer which allows to see this point in a different way.
Indeed, to avoid confusion, it is better to use the recognized terms top/bottom/right/left
