### ISSUE TITLE
Minor typo in Javascript - Test your skills: Loops

### ISSUE THREAD

**Issue by nvidyala** [mdn/content#21763]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Test_your_skills:_Loops

### What specific section or headline is this issue about?

Loops 1

### What information was incorrect, unhelpful, or incomplete?

The text under this heading starts off as `In our first looping task we want you start by creating`.

### What did you expect to see?

We can modify this to `In our first looping task, we want you to start by creating`.

**Comment by hamishwillee** [comment]
Thanks, this will be fixed by #21768

FWIW @nvidyala - for this kind of thing it is probably just as easy for you to create a PR with the fix. There's a button to make that easy at the bottom of every page.

![image](https://user-images.githubusercontent.com/5368500/197422183-64c93660-c585-480c-9fe7-a159e37dee6f.png)
