### ISSUE TITLE
Consistent title for instance properties

### ISSUE THREAD

**Issue by senocular** [mdn/content#21789]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/length

### What specific section or headline is this issue about?

Title, breadcrumb, side panel, more?

### What information was incorrect, unhelpful, or incomplete?

String length

### What did you expect to see?

String.prototype.length

### Do you have any supporting links, references, or citations?

https://github.com/mdn/content/issues/16325

### Do you have anything more you want to share?

It's wrong, but to be consistent.

**Comment by Josh-Cena** [comment]
Frankly, I think "String length" would be strictly better than "String.prototype.length". This needs more discussion, but I don't think converting everything to `String.prototype.length` is a better way to go.

**Comment by wbamberg** [comment]
For the Web/API docs we are intending to be clearer and more consistent about distinguishing instance and static members.

It looks like this will have a few pieces:
- new titles, along the lines described in https://docs.google.com/spreadsheets/d/1AqiTcnQa74Dq-pAJKq1LLo3iple2MN1NoWAAGQlorIA/edit#gid=0
- a new front matter item, `short-title`, that we will use in places (like sidebars) where the context would make a complete title redundant
- updates to the sidebar to separate static and instance fields (merged as https://github.com/mdn/yari/pull/7335) and to render short titles where they are defined
- different URLs for static and instance fields https://github.com/mdn/mdn-community/discussions/264). This is needed for Web APIs because it's possible to have static and instance members with the same name (https://github.com/openwebdocs/project/issues/104)

I'm in favour of the JS and Web/API docs being aligned as far as possible. I like the proposed changes to the Web/API docs and think in many ways they will be clearer than the way JS handles this at present (not just the title, but the sidebar too) but appreciate that there might be good reasons why the JS docs should be different. It would be good to know what these are.

The pressure for the change is all on the Web/API docs rather than the JS docs, because the JS docs already (usually) distinguishes static and instance members in the title via `.prototype`.

**Comment by Josh-Cena** [comment]
I'm all for the `.prototype.` convention and think it's much clearer than other alternatives, especially when the inheritance chain gets long. The only thing awkward about this is instance properties. I think it's better if we can propagate either the "String length" or "RegExp: lastIndex" formats.

**Comment by Ahmed-Hakeem** [comment]
We should split instance properties themselves to:

   1.   properties created directly inside the instance itself by the engine.
   2.   properties accessed from its constructor's prototype.

We have cases here that lead us to do so:

- case 1 : instances can have the same property with different values (one created inside the object itself, and one created inside its constructor's prototype), and the property's value in the constructor's prototype acts as a fallback (see message property in the provided example).

- case 2 : there are properties created directly in the instance and have no fallback inside its constructor's prototype (see cause property in the provided example).

for ex: 
```js 
const Err  = new Error("custom message", { details : "HTTP error" } );
console.dir( Err ); 
/*
{
   message:"custom message",
   cause:"HTTP error",
   [[Prototype]]: {
        name:"Error",
        message:"" 
   }  
*/
```
