### ISSUE TITLE
This is not deprecated

### ISSUE THREAD

**Issue by wadih** [mdn/content#21848]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/event

### What specific section or headline is this issue about?

This is not deprecated

### What information was incorrect, unhelpful, or incomplete?

This is not deprecated. 

What is the evidence that this is "fragile" ? Where is the evidence that it's not a web standard anymore? 

Where's the evidence that this will be removed any time? 

This is complete nonsense, and is propagating the myth that this is bad for some reason, without explaining why, citing references or citations of any sort. 

The burden of proof is on you to justify breaking years of functioning web standard and backwards compatibility.

Actually I have many reasons of the opposite and how it has been a key part of how I build my user interfaces.

I have been building javascript UX for years and that's the method I use for my user interactions, and I've never had an issue with it in 20 years. 

I call the function from an onclick= attribute for example, and I access event.target inside the function, without passing "e", "event", or evaluating "if (e)", or whatever else, as simple as that, and has worked flawlessly. 

This has been practical and eases the wiring information and function signatures from a purely pragmatic standpoint. 

I always build my sites from scratch to never have to deal with new arbitrary premises and new levels of abstraction that frameworks create, and having "event" and "event.target" inside my functions readily and painlessly available has always worked perfectly. 

The only issues I've ever seen with this is when frameworks come and mess with the natural behavior and flow of things.

But I've never had a single issue when developing sites from scratch, which is 100% of what I do.

I don't use frameworks, and I'm not planning to. One level of abstraction is enough for me. 

There is no need to touch that. 

### What did you expect to see?

Remove the misleading deprecation messages, including the top message in red, the fragility comment, and the misleading claim that it could be removed at any time.

### Do you have any supporting links, references, or citations?

Actually I would like to see links, references or citations for the offending information, burden of proof is on you to suggest breaking years of functioning web standard and backwards compatibility.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/window/event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/event/index.md
* Last commit: https://github.com/mdn/content/commit/f7dae62645a2c735ed6f6ed63f664bf279fdfc4b
* Document last modified: 2022-09-09T05:19:45.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi! Deprecation on MDN always means spec status, not by will of the MDN authors. This is explicitly stated in the [spec](https://dom.spec.whatwg.org/#dom-window-event):

> Web developers are strongly encouraged to instead rely on the [`Event`](https://dom.spec.whatwg.org/#event) object passed to event listeners, as that will result in more portable code. This attribute is not available in workers or worklets, and is inaccurate for events dispatched in [shadow trees](https://dom.spec.whatwg.org/#concept-shadow-tree).

The reason has been clearly explained. It doesn't matter if your page keeps working or not; we are simply telling you what spec authors think and what future might lie ahead of the API. Honestly, I don't see this API ever going away—it would break too many websites, so if you want to use it, just keep using it. There's no point in arguing with MDN authors because we aren't the ones making prescriptive claims.

**Comment by wolfbeast** [comment]
>  I don't see this API ever going away—it would break too many websites

As a data point from our browser that has not had the ambiguous `window.event` implemented, it is not "many websites" at all that break - in fact it's become a rarity that this is the cause of breakage. What's more, webmasters are often easily informed how to fix this and often do respond after a little bit of standards evangelism since it's officially deprecated -- of course our project is small so large sites are unlikely to be very responsive. It ultimately is "a few important sites" that would break, not "a large number of websites".

As such I agree with not removing the deprecated status, and in fact would love to see Mozilla actually taking more steps to deprecate it officially (console warnings, etc.). MSIE is well and truly gone, so there's no reason to retain this.
