### ISSUE TITLE
The instructions on how to set up a site permission add-on are obsolete

### ISSUE THREAD

**Issue by gabrielesvelto** [mdn/content#21951]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Web_MIDI_API

### What specific section or headline is this issue about?

The second note just above the Interfaces title

### What information was incorrect, unhelpful, or incomplete?

The link to the instructions on how to set up a site permission add-on is broken because that functionality has been removed and the WebMIDI API is now gated by an add-on that is auto-generated by Firefox itself directly on the user machine. See https://bugzilla.mozilla.org/show_bug.cgi?id=1778959.

### What did you expect to see?

The entire note about WebMIDI being add-on-gated can be removed.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/web_midi_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_MIDI_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/web_midi_api/index.md
* Last commit: https://github.com/mdn/content/commit/f7dae62645a2c735ed6f6ed63f664bf279fdfc4b
* Document last modified: 2022-09-09T05:19:45.000Z

</details>

**Comment by hamishwillee** [comment]
@gabrielesvelto Thanks very much.

**Comment by hamishwillee** [comment]
@gabrielesvelto Thanks very much. I've deleted the note in https://github.com/mdn/content/pull/21953, but I am not sure that is sufficient.

From your response in https://bugzilla.mozilla.org/show_bug.cgi?id=836897#c137:

> The add-on is not required anymore, Firefox generates one on-the-fly, as web page authors you shouldn't have to do anything else.
> The MDN page is outdated, I'll make sure it gets updated. In the meantime WebMIDI in the latest nightly builds should work out-of-the-box on your pages, it will just prompt users to install the auto-generated add-on once, and then will work transparently.

I interpret this as:
- Previously if you were a web page author who wanted to use WebMidi you would have to go to the website and create request a site permission add-on. The user would then have to install it to use the page - though I presume there was some magic so they could easily find the right plugin.
- What is changed is that now Firefox generates the add-on automatically. If the user goes to this page it will ask them if they want to use the feature, and if they do, it will install the add-on.

Is that correct? If so, what's the point? I mean if the user is going to be asked permission anyway why not just use the [permissions API](https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API) to gate access rather than all this add on stuff?

I still need to update the browser compatibility data, [which also says](https://github.com/mdn/browser-compat-data/blob/main/api/Navigator.json#L3793) that the add on is required from version 100. So what happens between versions 100 and 107 - you can't use those interim versions anymore because you can't get the add on?

Lastly, webmidi is available in nightly and gated behind `dom.webmidi.enabled`. It looks like this site permission feature is gated by  `dom.sitepermsaddon-provider.enabled`, which is default `false` (not nightly  as far as I can see). So what does that mean? By default you will just get an ordinary user permission request and nothing happens with the addon?

Hope that last part clear?

**Comment by gabrielesvelto** [comment]
> Is that correct? If so, what's the point? I mean if the user is going to be asked permission anyway why not just use the [permissions API](https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API) to gate access rather than all this add on stuff?

The WebMIDI API is considered potentially harmful because of how it lets web pages manipulate hardware and software MIDI devices which might not be hardened against hostile input. As such we've placed it under more strict control than what the permission API would allow. I'm CC'ing @rpl and @nchevobbe who implemented the add-on gating so they can give you more details on how it works.

> I still need to update the browser compatibility data, [which also says](https://github.com/mdn/browser-compat-data/blob/main/api/Navigator.json#L3793) that the add on is required from version 100. So what happens between versions 100 and 107 - you can't use those interim versions anymore because you can't get the now defunct add on and the dom.sitepermsaddon-provider.enabled doesn't exist yet?

Yes, in those versions there's no way to use WebMIDI since we removed the ability to generate permission add-ons. Before version 100 it was sufficient to enable the `dom.webmidi.enabled` preference to enable WebMIDI, between version 100 and 104 included you needed the add-on that we generated, there's no other way to enable WebMIDI in those versions. Starting with version 105 one could disable the `dom.webmidi.gated` preference and use WebMIDI without the add-on. I know this is a bit confusing but this functionality has been very much in-flux and we've also introduced some regressions along the way (such as not honoring the `dom.webmidi.gated` preference between versions 100 and 104).

**Comment by hamishwillee** [comment]
Thanks @gabrielesvelto - really appreciate the detailed summary. I'm not blocked now.

@rpl and @nchevobbe would be great to have a summary of the add on gating feature so that this can be properly documented "generically". If this is still very much in flux then we could wait, but if we expect either developers or end users to do or understand anything special this will need something sooner rather than later.

**Comment by nchevobbe** [comment]
> @rpl and @nchevobbe would be great to have a summary of the add on gating feature so that this can be properly documented "generically". If this is still very much in flux then we could wait, but if we expect either developers or end users to do or understand anything special this will need something sooner rather than later.

There's not a much more than what you said previously 

> What is changed is that now Firefox generates the add-on automatically. If the user goes to this page it will ask them if they want to use the feature, and if they do, it will install the add-on.

Those potentially harmful API calls will follow a specific path which will prompt the user to "install" an addon, with a message highlighting the potential harmfulness (current message will be updated BTW, see https://bugzilla.mozilla.org/show_bug.cgi?id=1790313).
Once they agree to install the addon, under the hood we'll grant the permission, using the regular permission API.
The "addon" will appear in about:addons, in a dedicated "Site Permissions" section, where it can then be uninstalled (it can also be directly from the page, clicking on the permission icon).

As you noted, `dom.sitepermsaddon-provider.enabled` is only enabled on Nightly for now, but we plan to have it enabled everywhere soon (hopefully in 108, see https://bugzilla.mozilla.org/show_bug.cgi?id=1790621)

For the API using this, we will automatically deny the permission if:
- the URL is not `https` (this excludes `file://` scheme)
- the URL is a public etld
- the URL is a plain IP address

an error message will be printed to the Developer Tools console when one of those case is met.

Let me know if you have any question

**Comment by hamishwillee** [comment]
@nchevobbe Thanks very much. 

It sounds like this is essentially the way that Firefox has chosen to layer a better UI for permissions prompting and revocation - i.e. a particular implementation of the common meanings for "secure context" and user permissions. Not entirely sure how/if this would be documented. My first impression is that this should be documented in the firefox documentation rather than MDN - ie. in a topic "Site Permissions". We might then link to that from the compatibility data.

**Comment by hamishwillee** [comment]
Note, closing this as the actual issue has been addressed in docs and browser compatibility data. Still hoping for an answer to the above question ^^^^

**Comment by nchevobbe** [comment]
> @nchevobbe Thanks very much.
> 
> One question, re "under the hood we'll grant the permission, using the regular permission API.". Is there a standard web-midi permission in the spec that you are granting? I.e. would some other browser require the user permission too "as standard".

We are granting `midi` and `midi-sysex` permission. I'm not sure how this plays with the spec though (https://webaudio.github.io/web-midi-api/#permissions-integration). FWIW Chrome isn't asking any permission to the user and always grant the access

**Comment by hamishwillee** [comment]
@nchevobbe - thanks. FYI only We capture that kind information in the respective permissions:

- [Permission Policy (Feature Policy)](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy) - From FF74, but behind a pref for the whole header
- [Permissions API](https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API) - `midi` fully support from FF79. 

Chrome indicates support for these as well.

The permission API data is a bit unhelpful. in that just because you "support" a permission doesn't mean the user will be prompted; it just means that this will be set/unset. So both Firefox and Chrome support the midi permission, but FF prompts and chrome just grants it.
