### ISSUE TITLE
RegExp.hasIndices() - more examples and named capture groups

### ISSUE THREAD

**Issue by hamishwillee** [mdn/content#21957]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/hasIndices

### What specific section or headline is this issue about?

Examples and Description

### What information was incorrect, unhelpful, or incomplete?

From engineer in [this bugzilla post](https://bugzilla.mozilla.org/show_bug.cgi?id=1519483#c14):

> The only thing I would consider adding is a more prominent description (maybe on the hasIndices page?) of the structure of the output, similar to the examples [here](https://github.com/tc39/proposal-regexp-match-indices#examples).

> In particular, it might be nice to document the interaction between /d and named capture groups.

### What did you expect to see?

Any information about interaction between /d and named capture groups.

### Do you have any supporting links, references, or citations?

https://github.com/tc39/proposal-regexp-match-indices#examples

### Do you have anything more you want to share?

Once resolution of this is determined and done (or not done) we should remove `dev-doc-needed` from https://bugzilla.mozilla.org/show_bug.cgi?id=1519483

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/regexp/hasindices`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/hasIndices
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/regexp/hasindices/index.md
* Last commit: https://github.com/mdn/content/commit/8db2031e46de297b9a02dca59eb8d8767fe6c61e
* Document last modified: 2022-10-23T08:06:12.000Z

</details>

**Comment by hamishwillee** [comment]
FYI @Josh-Cena

**Comment by Josh-Cena** [comment]
FWIW, this feature has never seemed that exciting to me—you know to reach for it when you need it, but otherwise it's just... there. https://github.com/mdn/content/issues/3337 was in the same vein, which I closed by adding an example here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Groups_and_Backreferences#using_groups_and_match_indices As for the "structure of the output", it's documented in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec#return_value. I agree we can probably link to these pieces from the `hasIndices` page, though.

**Comment by hamishwillee** [comment]
I've made the corresponding bugzilla bug "dev doc complete" following PR by Josh.
