### ISSUE TITLE
Misleading/wrong note on id stability.

### ISSUE THREAD

**Issue by github-nilsson** [mdn/content#21977]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/XPath/Functions/generate-id

### What specific section or headline is this issue about?

Notes

### What information was incorrect, unhelpful, or incomplete?

Second note states that the "generated id may not be the same in subsequent transformations". This is not true as it can be the same.

### What did you expect to see?

"The generated id can be different in subsequent transformations."

### Do you have any supporting links, references, or citations?

Spec reference is on the page.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/xpath/functions/generate-id`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/XPath/Functions/generate-id
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/xpath/functions/generate-id/index.md
* Last commit: https://github.com/mdn/content/commit/f22e42182591e38590c9add80de91a51bce3cde2
* Document last modified: 2022-09-09T05:38:45.000Z

</details>

**Comment by Josh-Cena** [comment]
How are "may not be the same" and "can be different" semantically different?

**Comment by github-nilsson** [comment]
https://www.lawinsider.com/dictionary/may-not

**Comment by Josh-Cena** [comment]
The modal verb "may not" has two meanings. In a prescriptive context, it means "not allowed to"; in a descriptive context, it means "maybe not". The overall tone of MDN is unambiguously descriptive, since we are not a specification. When you see sentences like "he may not have seen this", you understand that it means we are making an assumption about a fact, not a rule about what ought to happen. Law terms and colloquial usage often differ, and it doesn't make sense to expect our wording to be as precise as legal terms.
