### ISSUE TITLE
The new URL object detects http://www true.

### ISSUE THREAD

**Issue by Seung-hwan285** [mdn/content#22536]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/URL/URL

### What specific section or headline is this issue about?

The new URL object detects http://www true.

### What information was incorrect, unhelpful, or incomplete?

While using the new URL, I found that it became true even at https://www.

```js
function isHttpUrl(string) {
    let url;
    try {
        url = new URL(string);
    } catch (e) {
        return false;
    }
    return url.protocol === "http:" || url.protocol === "https:";
}
console.log(isHttpUrl("https://www")); // true
console.log(isHttpUrl("google.com")); // false
```

### What did you expect to see?

This is a new URL object found while looking for alternatives other than regular expressions while creating a function for checking urls.
But it returns true even for http://www.
I'm curious if this is how it works.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/API/URL/URL

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/url/url`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/URL/URL
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/url/url/index.md
* Last commit: https://github.com/mdn/content/commit/e1353ccd3ea46598308e5208667f276df115e8e3
* Document last modified: 2022-10-25T22:36:36.000Z

</details>

**Comment by Josh-Cena** [comment]
Why wouldn't it? A domain name can have only one "part", since all the dot-separated paths are only by convention. The URL format looks like `<scheme>//<user>:<password>@<host>:<port>/<url-path>`; `www` is definitely a valid `host`. Microsoft seems to call it a [_single label domain_](https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/single-label-domains-support-policy), and it's usually used with an internal resolver.

**Comment by Seung-hwan285** [comment]
For example, "www.naver.com" is a regular web address.
"naver" seems to have a definition for a single label domain.

What I want is not a single label domain.

As far as I know, the basic structure of a URL is Protocol Sub Domain , Root Domain and TLD.

In the current new URL object https://www i.e.
Returns true if only the protocol and subdomain structure are given. I'm wondering if this is the correct behavior.

**Comment by sideshowbarker** [comment]
I’m going ahead and closing this because it doesn’t seem to be calling out any specific problem in MDN content. The relevant MDN content here is simply documenting what’s in the spec and what browsers have implemented.

If this is a “why” question about why the behavior is such as it is, then that’s better suited for asking on site such as Stack Overflow.

But if I’ve misunderstood and this issue is instead suggesting some change to existing MDN content, then if some statement about what needs to be changed in MDN can be added here, this issue could be revisited.

**Comment by Josh-Cena** [comment]
@Seung-hwan285 TLD, subdomain, etc. are not URL concepts. They are parts of the DNS. The URL structure's granularity only specifies the "hostname"; how the "hostname" is structured and managed is irrelevant to the URL. As soon as you have any valid string after the protocol, that string will be seen as the hostname.

**Comment by Seung-hwan285** [comment]
@Josh-Cena  thank you I misunderstood the concept

**Comment by Seung-hwan285** [comment]
@sideshowbarker  Well noted with thanks, I think I made a mistake because I was in a hurry. Thank you for answer.
