### ISSUE TITLE
BigInt replacer/reviver example is not generic

### ISSUE THREAD

**Issue by aral** [mdn/content#22573]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#use_within_json

### What specific section or headline is this issue about?

Use Within JSON

### What information was incorrect, unhelpful, or incomplete?

The given code sample would only work if the JSON has BigInt values in a key named `big`. This is almost never how you’d do it (you’d check the type of the value instead and make the replacer/reviver generic functions).

```js
const replacer = (key, value) => key === "big" ? value.toString() : value;

const data = {
  number: 1,
  big: 18014398509481982n,
};
const stringified = JSON.stringify(data, replacer);

console.log(stringified);
// {"number":1,"big":"18014398509481982"}
```

Ditto for the reviver. 

### What did you expect to see?

A generic replacer that people can copy/paste and use. e.g.,

```js
const data = {
  small: -9223372036854775808n, 
  large: 18446744073709551615n
}
const replacer = (_key, value) => typeof value === 'bigint' ? value.toString() : value
const stringified = JSON.stringify(data, replacer)

console.log(stringified)
// { "small": "-9223372036854775808", "large": "18446744073709551615" }
```

Ditto for the reviver.

**Comment by Josh-Cena** [comment]
I suppose this issue is only about the replacer? The replacer can be generic but the reviver, very often, cannot, because serialization is necessarily lossy.

Frankly, I've never seen how people use replacers in real life. Do they actually have a "generic replacer"? That sounds risky because you may serialize unexpected data types in the wrong place. I'm okay to change the replacer example to make it aligned with the `toJSON` one, though.

**Comment by aral** [comment]
@Josh-Cena Given the replacer/reviver are for JavaScript only (not general JSON), you should be able to have a generic replacer/reviver if you serialise the BigInt instance using the `n` notation.

Here’s a gist someone created earlier that should do the trick:

https://gist.github.com/jordanbtucker/d48b826aa9f4e868f8d406d84fa10526

This would, however, require the use of the replacer and reviver everywhere as a plain JSON parse would otherwise fail on the `n` notation.

**Comment by Josh-Cena** [comment]
My concern is this: if you say, all BigInts should be serialized to `"10000n"`, and you decide that all strings that look like `/^[-+]?\d+n$/` should be parsed to BigInt values, then what about JSON containing actual strings in this format? (For example, if you are deserializing user data, and someone gives themselves a username called "10000n") Because serialization is lossy (i.e. two different data types may map to the same output; it's not bijective), it's not possible to recover the full semantics without introducing ambiguities.

**Comment by aral** [comment]
Entirely valid concern and I agree :) (In my project I’m thankfully serialising to an append-only JavaScript log, so I’m not hit by this issue and I just needed to implement a replacer at one point in the tests where I was using JSON serialisation/deserialisation to test my JavaScript deserialisation method) :)
