### ISSUE TITLE
Issue with "Sizing": stub page from wiki migration

### ISSUE THREAD

**Issue by nschonni** [mdn/content#2269]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Sizing

#### What information was incorrect, unhelpful, or incomplete?

Looks like a stub generated from the old Wiki setup. Not sure if it should just be deleted till content is added

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/svg/sizing`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Sizing
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/svg/sizing/index.html
* Last commit: https://github.com/mdn/content/commit/cbe151a06d6e5b4d1fbb46081bd16e69ef4c1630
* Document last modified: 2020-09-15T15:48:51.000Z

</details>

**Comment by Ryuno-Ki** [comment]
@nschonni Thanks for pointing this out.

If I get the spec right: https://svgwg.org/specs/integration/#svg-css-sizing
`sizing` refers to `height` and `width` attribute.

I could also imagine some cross-referencing to https://developer.mozilla.org/en-US/docs/Web/CSS/Scaling_of_SVG_backgrounds#automatic_sizing_using_auto_for_both_dimensions

That being said, I couldn't find a reference to this page, so it could also be just outright deleted. (Which is what I'm going for, I think).

@peterbe Would it make sense to check for orphaned pages like this?

**Comment by peterbe** [comment]
Someone just created this page so that they can create a sub-page. I think in Yari you can have sub-folders without a "parent" index.html. 
But it's not even possible to test that since there are no sub-folders in https://github.com/mdn/content/tree/main/files/en-us/web/svg/sizing

I think this page can simply be deleted. I'm not familiar with [that macro](https://github.com/mdn/content/blob/89b781abf1093d108f0fba926286c5b9eac59923/files/en-us/web/svg/sizing/index.html#L7) but I suspect we can recycle that macro since it's only used in two en-US pages. If we do that, it would make the page entirely empty. And it shoudl NOT included in the build.

**Comment by peterbe** [comment]
The other page to scrutinize is files/en-us/web/svg/replaced_element/index.html if someone wants to take a look. 

Perhaps @escattone has some better/stronger opinions of what to do with pages like this.

**Comment by Ryuno-Ki** [comment]
> The other page to scrutinize is files/en-us/web/svg/replaced_element/index.html if someone wants to take a look.

=> #2270 

I'm going to delete this one tomorrow morning (CET).

**Comment by Ryuno-Ki** [comment]
#2280 is going to delete this page.

@nschonni catched some more in #2271
