### ISSUE TITLE
[SVG] Remove SVGGraphicsElement.getTransformToElement

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#22737]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

We don't have a page for this, but worthy of rel note and bcd check

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1803790

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [x] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by Rumyra** [comment]
For however taskes this - please also check https://bugzilla.mozilla.org/show_bug.cgi?id=1133174 (same topic)

**Comment by hamishwillee** [comment]
Review/proposal:

- `SVGGraphicsElement.getTransformToElement` removed from FF109.
  - removed from SVG (2) spec in 2015 and from Chrome at a similar long time ago.
  - Not in BCD or documented in MDN. 
  - I proposed we do nothing at all to record this removal in MDN - not even a release note.
  - Action would be to simply add dev-doc-complete and a note for this in the but report.

- `SVGGraphicsElement.{nearest,farthest}ViewportElement` in nightlies and early beta
  - As it says, features disabled in nightly - but presumably still present in release.
  - Not documented in BCD or in MDN
  - Proposed again to do nothing other than add dev-doc-complete.
  - But since this is still present I will ask the engineer.
