### ISSUE TITLE
"promisedFunction" is confusing

### ISSUE THREAD

**Issue by Worldwidebrine** [mdn/content#22785]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await#handling_rejected_promises

### What specific section or headline is this issue about?

Handling rejected promises

### What information was incorrect, unhelpful, or incomplete?

`A sync function returns a Promise` is also a "promisedFunction", right?
```js
function promisedFunction() {
  [](); // throws error
  if (true) {
    return Promise.reject();
  }
  return Promise.resolve();
}
(async () => {
  const response = await promisedFunction().catch((err) => {
    console.error(err);
    return "default response";
  });
  console.log(response);
})();
```
Can't assume there will never be error, otherwise the error could be ignored (not every interpreter logs uncaught rejection).

### What did you expect to see?

Can't we just use `promise`?
```js
const response = await promise.catch((err) => {
  console.error(err);
  return "default response";
});
// response will be "default response" if the promise is rejected
```

### Do you have anything more you want to share?

https://learn.microsoft.com/en-us/minecraft/creator/scriptapi/minecraft/server/player#runcommandasync

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/await`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/await/index.md
* Last commit: https://github.com/mdn/content/commit/0ad08fe1d8830f11e0314733f56e391affc1fe94
* Document last modified: 2022-11-17T13:58:24.000Z

</details>

**Comment by Josh-Cena** [comment]
This does look ambiguous. There's a convention that if you have a promise-returning function, you should never synchronously throw errors, but that's not always enforceable. At the same time, the idea is that you don't have to do:

```js
let response;
try {
  response = await promisedFunction();
} catch (err) {
  console.error(err);
  response = "default response";
}
```

And surely, no one in this case would first call `promisedFunction()` and then `await` the returned promise. I think we just need to provide an implementation of `promisedFunction`, noting that it never synchronously throws, and then add a caveat that this error-handling doesn't work if the error is synchronous (and how rare that should happen).

**Comment by pchelpre4** [comment]
Negative, several meetings and communications took place which we can reasonably assume meant they were working towards performance of a solution and at the final meeting terms were established with reservation to the negotiation not being in the best interest of both parties to the contract. This demonstrates an attempt at mutual assent and acceptance of terms by multiple agents of the firm and the client. Since all parties were engaged and the terms were accepted, the contract was reasonably well formed however the material wasn't delivered  and a substitute  was tried to negotiate with the early agreement of the obligations of both parties which would cause the customer to file a breach and counter claim that was never heard which means the promise to perform was damaged and therefore we can not even reasonably assume that the company would even fulfill their obligations in the future or to others. and since verbal contracts are binding in the jurisdiction and venue which would claim the subject matter without express agreement toward arbitration, indemnification and otherwise, the entity itself can't legally substantiate its business but the claims against them for IRS, FCC, FDA, Department of Commerce, Department of Weights and Measures as well as the Department of Labor and Industry across state lines cause a serious problem of that jurisdiction which the interstate compacts can't even claim thus alleviating the county of a civil burden or criminal with the UCC still governing which was adopted alongside other legislation largely incorporated into the state as the federal code did and registers handle as well as several other major efforts in a class action causing a dissolution of the corporation due to insolvency and enforcement  actions from the executive branch and under the powers granted under the commissioner of the respective departments granted from that incorporation. That should be enough information to get the current powers to negotiate options more easily by collaboration. This has largely left the private industry alone in terms of considerations which are civil and don't need to be included.
