### ISSUE TITLE
Not applicable code

### ISSUE THREAD

**Issue by AlkisPis** [mdn/content#22872]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

### What specific section or headline is this issue about?

Preflighted requests and Requests with credentials

### What information was incorrect, unhelpful, or incomplete?

Neither of the two examples of using XMLHttpRequest() works. They are both blocked by CORS policy. Yet, they are suposed to handle this exact problem! So, what's the used of providing such codes if the don'y hande the CORS policy problem?

**Code #1:**
`const xhr = new XMLHttpRequest();
const url = "https://bar.other/resources/public-data/";

xhr.open("GET", url);
xhr.onreadystatechange = someHandler;
xhr.send();`

**Code #2:**
`const invocation = new XMLHttpRequest();
const url = "https://bar.other/resources/credentialed-content/";

function callOtherDomain() {
  if (invocation) {
    invocation.open("GET", url, true);
    invocation.withCredentials = true;
    invocation.onreadystatechange = handler;
    invocation.send();
  }
}`

They both produse the following error:
_Access to XMLHttpRequest at 'https://www.google.com/' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource._

### What did you expect to see?

Well, it's rather what I expect **not to see**!  I expect not to see any error at all.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/cors`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/cors/index.md
* Last commit: https://github.com/mdn/content/commit/185d871fd1c78b6c762d4a703b269dafb3167bbb
* Document last modified: 2022-12-05T10:13:20.000Z

</details>

**Comment by sideshowbarker** [comment]
> They both produse the following error:
> _Access to XMLHttpRequest at '`https://www.google.com/`' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource._

It doesn’t seem like the examples could produce that error, since the examples use the URLs `https://bar.other/resources/public-data/` and `https://bar.other/resources/credentialed-content/` — not `https://www.google.com/`

The article isn’t claiming that _any_ URL you use in for a cross-origin request will just work — whether it’s  a `https://www.google.com/` URL or some other URL. The server at the URL the request is being sent to must be CORS enabled; otherwise, browsers block access to the response, as explained in the article.

Do you have any specific suggestions about how to make the article and its examples more clear about that?

**Comment by AlkisPis** [comment]
Thanks for your reply @sideshowbarker. You are right. I have posted the code exactly as I found it by copy-pasting it, as an an example only. One must replace _https://bar.other/resources/public-data/_ and  _someHandler_ with and actual (existing) URL and a an actual function (a dummy one ). 

I run the code using _https://www.google.com/_ as URL, and that's why I presented the error, which refers to that URL. But the same error is produced using any URL (Except URLs directing to webpages containing text data, e.g. _https://raw.githubusercontent.com/itsfoss/text-files/master/agatha.txt_)

Please do that yourself and let me know about the results.

**Comment by sideshowbarker** [comment]
Respectfully, I’m going ahead and closing this question — because in this issue so far no suggestions have been presented on how to make the article and its examples more clear, and the issue discussion does not appear to be headed toward uncovering any specific problems for any useful changes could be made.
