### ISSUE TITLE
Docs say attach shadow root in connectedCallback, example has it in constructor

### ISSUE THREAD

**Issue by foobarbecue** [mdn/content#22887]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements

### What specific section or headline is this issue about?

autonomous_custom_elements

### What information was incorrect, unhelpful, or incomplete?

Due to PR #19035 , tutorial text in the very first example for Web Components does not match the example. Tutorial refers to [this js](https://github.com/mdn/web-components-examples/blob/main/popup-info-box-web-component/main.js), where shadow root is attached in the constructor. However, the text says the shadow root should be attached inside connectedCallback.

PR #19035 was well-intentioned, but incorrect (it says `this.getAttributes` fails in the example; presumably that was supposed to read `this.getAttribute`, but that works fine). The "bug" that is claimed in the PR does not happen in the example because the script tag has the `defer` attribute.

I reccomend that #19035 be reverted. In its place, maybe add note that `defer` is used in the example.

A less satisfactory solution would be to update the example to match the tutorial text, but this would unnecessarily complicate the example, introducing lifecycle methods before they have been taught.

### What did you expect to see?

I expect the explanation to correspond to the example. I also expect lifecycle callbacks should be discussed in their own section, not in the shadow dom section.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/web_components/using_custom_elements`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/web_components/using_custom_elements/index.md
* Last commit: https://github.com/mdn/content/commit/3afc4a9557e0c71cbcf5491975d8edec38422247
* Document last modified: 2022-10-20T19:29:00.000Z

</details>

**Comment by wbamberg** [comment]
From what I can tell the correct thing here really is to use `connectedCallback`, rather than rely on the script being marked `defer`.

So I filed https://github.com/mdn/web-components-examples/pull/62 to make that change.

- https://stackoverflow.com/questions/42251094/cannot-access-attributes-of-a-custom-element-from-its-constructor
- https://github.com/mdn/content/issues/5022

But I don't know much about web components. @sideshowbarker , do you know about this?

**Comment by sideshowbarker** [comment]
> But I don't know much about web components. @sideshowbarker , do you know about this?

No, I also don’t have much insight to offer here

**Comment by foobarbecue** [comment]
> From what I can tell the correct thing here really is to use connectedCallback, rather than rely on the script being marked defer.

As I explained above, I think it's really better to use defer in this case, because this is a tutorial that hasn't introduced connectedCallback yet. Otherwise you need to restructure the material.

**Comment by wbamberg** [comment]
Yes, we should move the stuff about lifecycle events before this example if we go this way.

Do you have a reason to believe that doing this work in the constructor is better practice than doing it in `connectedCallback`? What I've seen suggests the opposite, and I think we should follow good practices in our examples even if it means we have to explain a little more. It seems better to present an example that will work no matter how the script is included, than one that has this dependency.

Also, if we do the work in the constructor, we have to explain that this only works because of `defer`, and explain what `defer` is doing to make it work, which seems much more incidental to custom components than the lifecycle events, which we are already teaching in this page.

**Comment by foobarbecue** [comment]
> Do you have a reason to believe that doing this work in the constructor is better practice than doing it in connectedCallback?

No, I don't. I think your remaining points are valid.
