### ISSUE TITLE
Triggering "onload" when image is potentially already loaded.

### ISSUE THREAD

**Issue by andre-caldas** [mdn/content#23038]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Pixel_manipulation_with_canvas

### What specific section or headline is this issue about?

A color picker

### What information was incorrect, unhelpful, or incomplete?

I believe that
```
img.src = "./assets/rhino.jpg";
```
should be executed only after the `load` event is properly set.

### What did you expect to see?

```
const img = new Image();
img.crossOrigin = "anonymous";
const canvas = document.getElementById("canvas");
const ctx = canvas.getContext("2d");
img.addEventListener("load", () => {
  ctx.drawImage(img, 0, 0);
  img.style.display = "none";
});
img.src = "./assets/rhino.jpg";
```

### Do you have anything more you want to share?

I did look for, but I didn't find any reference that says, for example that `load` is always triggered even if the object was already loaded. Although I doubt this is the case, please close the issue and forgive me if it is.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/canvas_api/tutorial/pixel_manipulation_with_canvas`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Pixel_manipulation_with_canvas
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/canvas_api/tutorial/pixel_manipulation_with_canvas/index.md
* Last commit: https://github.com/mdn/content/commit/6e5f4aefd9650f20bb0b4a6cbf0c4e1e2d105b64
* Document last modified: 2022-12-06T09:20:17.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi! I assume you mean that the request is fired as soon as `src` is set. This is correct. However, because of how the JavaScript job queue works, it's not possible for this async job to complete until all sync code has finished executing. Therefore, the `load` event can only be fired when the event listener is already attached.

**Comment by andre-caldas** [comment]
So, we are opting for a design that depends on "how the job queue works" instead of opting for a design that is correct regardless of how the job queue works.

We are motivating people to write code that are not obviously correct. But code that you can see that it is (probably) correct as soon as we make some (possibly) correct inference about how something works internally...

**Comment by Josh-Cena** [comment]
> that depends on "how the job queue works" instead of opting for a design that is correct regardless of how the job queue works.

This is the basis of JavaScript's execution and not some obscure internal detail. JavaScript is designed in a way that is race-condition-free.

We'd rather educate people why surprising-looking code works as intended than to cater to possible misunderstandings. Both orders are perfectly fine, and when we've settled on one, it's better that we stick to it than to change it just because of readers' own misunderstanding.
