### ISSUE TITLE
Broken interactive example

### ISSUE THREAD

**Issue by MrBrain295** [mdn/content#23083]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/:root

### What information was incorrect, unhelpful, or incomplete?

I added an interactive example that I made but it gives a 404 error.

### What did you expect to see?

A working example.

**Comment by wbamberg** [comment]
CSS pseudo-classes use the "tabbed" editor instead of the "css" one, so it gets served from https://interactive-examples.mdn.mozilla.net/pages/tabbed/pseudo-class-root.html, and you need something like:

`{{EmbedInteractiveExample("pages/tabbed/pseudo-class-root.html", "tabbed-shorter")}}`.

Also though, there are two spelling errors in the example ("skateing" and "rollerbladeing"), and it doesn't seem to work in Firefox or Chrome:

<img width="831" alt="Screen Shot 2022-12-20 at 4 16 01 PM" src="https://user-images.githubusercontent.com/432915/208791313-522df8e3-6059-40aa-8484-7861fb0b532d.png">

Am I missing something, or should the paragraph text be purple?
