### ISSUE TITLE
IteratorResult interface has no docs page

### ISSUE THREAD

**Issue by achingbrain** [mdn/content#23131]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols

### What specific section or headline is this issue about?

The iterator protocol

### What information was incorrect, unhelpful, or incomplete?

`IteratorResult` is referred to as a type in several places.  I'd like to be able to link to a canonical definition of it from generated documentation such as [TypeDoc](https://typedoc.org/) but from what I can see there's nowhere to link to.

E.g. the highlighted word below (the image is from the TypeDoc output) would be a hyperlink to the relevant MDN docs page in the same way `Promise` links [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) and `Uint8Array` links [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array):

<img width="361" alt="image" src="https://user-images.githubusercontent.com/665810/209138445-9025ab82-d2fe-4a04-b3df-f2f42a74886d.png">

### What did you expect to see?

A page available somewhere to link to like https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/IteratorResult

### Do you have any supporting links, references, or citations?

The interface is defined here: https://tc39.es/ecma262/#sec-iteratorresult-interface

This is a related issue: https://github.com/mdn/content/issues/21478 but the OP was just looking for a definition and the issue was closed but hopefully trying to link up documentation like this is more compelling case!

**Comment by Josh-Cena** [comment]
We never document interfaces, especially abstract ones (i.e. doesn't correspond to any intrinsic, global or hidden). What about linking to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_iterator_protocol?

**Comment by Josh-Cena** [comment]
Closing, because we most definitely will not create a separate page for a type alias. If you want to make `IteratorResult` linkable, you can update https://github.com/Gerrit0/typedoc-plugin-mdn-links/blob/main/src/globalObjects.ts with something like:

```js
const knownTypeDefs: Record<string, string> = {
    IteratorResult: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_iterator_protocol",
};

export function resolveGlobalName(name: string) {
    if (Object.hasOwn(knownTypeDefs, name)) {
        return knownTypeDefs[name];
    }
    // ...
}
```

**Comment by achingbrain** [comment]
> What about linking to https://developer.mozil...

I considered something like this but linking through to a big block of exposition like that doesn't feel like the greatest developer experience.  The phrase `IteratorResult` isn't even mentioned until a few paragraphs down so the developer will have to scan through the text to find anything useful.

If a dedicated page is out of the question, could the `IteratorResult` part of that section could have a sub-heading that could then be linked to?

**Comment by Josh-Cena** [comment]
`IteratorResult` doesn't make sense as a standalone type—you would only use it as a return type of `next()`. MDN has the opinion that types are second-class citizens in JS (which may be reconsidered these days, since a fair proportion of the readers are using TS anyway), which means they are always collocated with the values (function parameters, return values) they represent. The fact that I mentioned the `IteratorResult` name at all on that page is already partially because TS users may need it (and partially to illustrate that `next()`, `return()`, `throw()` should have the same signature). I do believe inserting the `IteratorResult` type def in the middle of the section best helps with the section's flow, but if you can find a way to reasonably reorder that section, PRs are welcome.
