### ISSUE TITLE
Uninterpreted "IncludeSubNav"

### ISSUE THREAD

**Issue by Thiht** [mdn/content#235]
Hi,

There's a raw `{{IncludeSubNav("/en-US/docs/MDN")}}`on this page: https://developer.mozilla.org/en-US/docs/MDN/About
See: https://github.com/mdn/content/blob/main/files/en-us/mdn/about/index.html#L15

I don't know if it's still relevant or if it can just be removed

Edit: here too https://developer.mozilla.org/en-US/docs/MDN/Tools and probably at otherplaces too

**Comment by edent** [comment]
![Screenshot of the error](https://user-images.githubusercontent.com/837136/102220871-4d431780-3ed9-11eb-9b4c-de41658517ce.png)

**Comment by sideshowbarker** [comment]
Thanks for raising this. I believed it’s already fixed in the sources here, by #210. So it’ll get deployed to the production site soon. So I think this issue can probably be closed. Or else if you prefer to keep it open until the change is actually deployed to the production site — and you can confirm the fix — that would be fine too.

**Comment by Thiht** [comment]
If it's already fixed I can close the issue, I didn't see the PR :) 

Thanks @sideshowbarker
