### ISSUE TITLE
An article doesn't appear in the table of contents of CSS tutorial

### ISSUE THREAD

**Issue by 3-2** [mdn/content#23538]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_layers

### What information was incorrect, unhelpful, or incomplete?

<img width="711" alt="Snipaste_2023-01-11_12-48-45" src="https://user-images.githubusercontent.com/25643218/211722416-2c70afe9-2b4f-403e-82df-6160eb9f3f73.png">

### What did you expect to see?

This article should appear in the top level of table of contents according to its URL.

**Comment by hamishwillee** [comment]
@estelle To your mind, is this the correct place for the topic (it is to mine, but I wanted to make sure this topic wasn't removed for a reason)?

I have partially fixed by adding to the sidebar in  https://github.com/mdn/yari/pull/8024 as a peer (next item) after "Cascade, specificity, and inheritance). If you disagree, then please add note against the PR.

To properly fix this we will need to also add this link to the `## In this module` section in every document in the module.
