### ISSUE TITLE
Remove one link to the spec (there are two)

### ISSUE THREAD

**Issue by dipikabh** [mdn/content#23618]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Web_MIDI_API

### What specific section or headline is this issue about?

Specifications

### What information was incorrect, unhelpful, or incomplete?

There are two links to the same specification document

### What did you expect to see?

Only one link to the specific section on the API

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/web_midi_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_MIDI_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/web_midi_api/index.md
* Last commit: https://github.com/mdn/content/commit/60f3727f5e6f25e7aa6c7bca24823f5b0055767a
* Document last modified: 2022-10-31T06:34:15.000Z

</details>

**Comment by wbamberg** [comment]
This is isn't just a typo, it's because we don't know what we're doing wrt spec URLs and BCD, especially in Web API overview pages.

This is a [Web API overview page](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types#api_landing_page), which ought to have one or more spec links, and for which we don't have a good answer to what it should have wrt BCD: https://github.com/mdn/content/discussions/4920.

For BCD, what people do in some cases is, add a BCD query for the main entry point to the API, which the person writing this API has deemed to be [`Navigator/requestMIDIAccess`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/requestMIDIAccess). But because spec URLs are tied to BCD, that means we get a spec URL for `Navigator/requestMIDIAccess`, (https://webaudio.github.io/web-midi-api/#dom-navigator-requestmidiaccess), while we wanted one for the whole spec (https://webaudio.github.io/web-midi-api/). So the author has solved that by _also_ including a `spec-urls` front matter key, that has the whole-spec link.

Meaning we get a spec URL through `browser-compat` and another through `spec-urls`. In a case like this Yari decides to render both URLs.

****

What should we do here?

Personally I think that in a perfect world:
- we would have a clear answer to [How should "API pages" represent BCD?](https://github.com/mdn/content/discussions/4920). I'm not sure what that would look like. Maybe we would not show BCD. Or maybe we would have some way for BCD to represent higher-level things like APIs.
- we would not include spec URLs in BCD, but only in front matter. It's very confusing for authors to have both. I think that might be controversial though. But at least, we could change Yari so if `spec-urls` is set, we ignore spec URLs from `browser-compat`.

**Comment by teoli2003** [comment]
` But at least, we could change Yari so if spec-urls is set, we ignore spec URLs from browser-compat.`

I think we may reach a consensus for this, and it doesn't look like too much work on mdn/yari.
