### ISSUE TITLE
Issue with "Using Promises": (short summary here please)

### ISSUE THREAD

**Issue by steveja42** [mdn/content#2377]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises

#### What information was incorrect, unhelpful, or incomplete?
Instead of running immediately, the passed-in function is put on a microtask queue, which means it runs later when the queue is emptied at the end of the current run of the JavaScript event loop, i.e. pretty soon:

#### Specific section or headline?
Timing

#### What did you expect to see?
Instead of running immediately, the passed-in function is put on a microtask queue, which means it runs later, just before control is returned to the event loop, i.e. pretty soon:

#### Did you test this? If so, how?
No, this is per https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API/Microtask_guide

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/guide/using_promises`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/guide/using_promises/index.html
* Last commit: https://github.com/mdn/content/commit/2ef7bb784bf1036ad7886b64e6451a68e573a44b
* Document last modified: 2021-01-15T08:25:52.000Z

</details>

**Comment by NegiAkash890** [comment]
According to `https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API/Microtask_guide` .

It says as follows :
" A micro- task is a short function which is executed after the function or program which created it exits and only if the JavaScript execution stack is empty, but before returning control to the event loop ..."

I think if above statement is correct then it should be JavaScript execution stack which should be emptied as well as caller of the function has finished it's execution before the execution of the micro-task begins  .

So I would be good if we update the statement as  :

" Instead of running immediately, the passed-in function is put on a micro-task queue, which means it runs later (only after the function which created it exits and when JavaScript execution stack is empty.), just before control is returned to the event loop, i.e. pretty soon: "

Thank You

**Comment by chrisdavidmills** [comment]
Thanks for the input, @NegiAkash890 — do you fancy raising a PR for this? ;-)

**Comment by amyrlam** [comment]
Was looking through some starter issues, and I think this was closed by https://github.com/mdn/content/pull/2418

**Comment by sideshowbarker** [comment]
@amyrlam — Yup, thanks for catching that. Will go ahead and close this out

**Comment by sideshowbarker** [comment]
Fixed by https://github.com/mdn/content/commit/2812703fe5f905cbbb7aa5eaee2c2026d53af508
