### ISSUE TITLE
Issue with "<details>: The Details disclosure element": …

### ISSUE THREAD

**Issue by edent** [mdn/content#239]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

#### What information was incorrect, unhelpful, or incomplete?

Doesn't include the CSS for detecting if the element is open. `details[open]`

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details#Customizing_the_appearance

#### What did you expect to see?

Some text about how to use `details[open]`

#### Did you test this? If so, how?

I wrote some CSS, saw it worked in FF and Chrome.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/details`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/html/element/details/index.html
* Report started: 2020-12-15T13:29:29.638Z

</details>

**Comment by vkWeb** [comment]
@chrisdavidmills as you know I'm taking a break from open source, I won't be available for some months. So I was taking a round of assigned tasks. This issue came up. 

https://github.com/mdn/content/pull/965/ has fixed this issue I believe. If the changes look satisfactory we can close this. 

See you all soon!

**Comment by chrisdavidmills** [comment]
@vkWeb yup, that looks good. Let's close!

And thank you for all your help in the last few months. Good luck with all your exams and everything!
