### ISSUE TITLE
Web/Api/PublicKeyCredentialRequestOptions doesn't have specification link

### ISSUE THREAD

**Issue by Regenhardt** [mdn/content#23935]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredentialRequestOptions

### What specific section or headline is this issue about?

specifications

### What information was incorrect, unhelpful, or incomplete?

There's no content there

### What did you expect to see?

A link to the specification (https://w3c.github.io/webauthn/#dictdef-publickeycredentialrequestoptions).

### Do you have anything more you want to share?

I'd do it myself but I don't really know how, since in the file (https://github.com/mdn/content/edit/main/files/en-us/web/api/publickeycredentialrequestoptions/index.md) there's just a placeholder for specification, as in other files that have a specification link, and I don't know where to edit that.

**Comment by wbamberg** [comment]
Hi @Regenhardt , and thanks for filing!

The issue here is that the spec URL usually lives in the browser compat entry for the feature, but `PublicKeyCredentialRequestOptions` is a dictionary, and dictionaries don't have BCD.

That's why the BCD section is also an error.

The fix in this case is to use the `spec-urls` front matter key to name the specification, as we do here, for instance: https://github.com/mdn/content/blob/5b4c35651c308f0aa9058ea716f6bee118a3db93/files/en-us/web/api/cryptokeypair/index.md?plain=1#L11 (`CryptoKeyPair` is also a dictionary).

We should also remove the `browser-compat` key and the corresponding "Browser compatibility" section.

Let me know if you still want to do this, or I can take care of it otherwise.

**Comment by Regenhardt** [comment]
Like that? Haven't figured out how to actually preview/test this yet.

**Comment by wbamberg** [comment]
Yes, that ought to work! If you file a PR it will build a preview of the page, so we can check.
