### ISSUE TITLE
querySelectorAll(): “User notes” section is inaccurate

### ISSUE THREAD

**Issue by robonzo23** [mdn/content#24302]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll

### What specific section or headline is this issue about?

User Notes

### What information was incorrect, unhelpful, or incomplete?

Apologies if this is inaccurate, but under the section user notes, it states:

"In this example, when selecting .outer .inner in the context of the < div > with the class select, the element with the class .inner is still found, even though .outer is not a descendant of the base element on which the search is performed (.select). By default, querySelectorAll() only verifies that the last element in the selector is within the search scope."

### What did you expect to see?

I thought it should say "the element with the class.outer is still found, even though .outer is not a descendant of the base element..."

### Do you have any supporting links, references, or citations?

N/a

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/document/queryselectorall`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/document/queryselectorall/index.md
* Last commit: https://github.com/mdn/content/commit/77b8cdb3a05999ade4a269d0ef2443618bb7cd66
* Document last modified: 2022-09-13T13:39:19.000Z

</details>

**Comment by wbamberg** [comment]
I think `.inner` is correct here, isn't it?

It selects `.inner`: https://codepen.io/willbamberg/pen/XWBLPrY?editors=1111, so if "found" means "selected" then `.inner` is right.

But I can see this might be confusing, because we might think "found" means something like "looked for elements in". Perhaps we can clarify the text here.

**Comment by TheNewsYorkTime** [comment]
I think what's not clear here is what the example code is trying to do. If so, I don't think it is articulated well in the explanation. I think what the code is meant to do is select all elements inside the div with BOTH of the classes, but it doesn't check for the first class, so the div with only the "inner" class is returned. Correct me if I'm wrong, but that is what I got from it.

**Comment by wbamberg** [comment]
> I think what's not clear here is what the example code is trying to do. If so, I don't think it is articulated well in the explanation. I think what the code is meant to do is select all elements inside the div with BOTH of the classes, but it doesn't check for the first class, so the div with only the "inner" class is returned. Correct me if I'm wrong, but that is what I got from it.

No, it's selecting elements with `.inner` that have an ancestor of `.outer`. The selector used is `.outer .inner`, in which the space represents the [descendant combinator](https://developer.mozilla.org/en-US/docs/Web/CSS/Descendant_combinator). If we wanted to select elements that had both classes, we would just concatenate the class names, like `.outer.inner` - and if you do that the `querySelector` in this example will return an empty list, because there are no elements with both classes.

The surprising behavior that this example is trying to demonstrate is that we are calling `querySelector` not on the whole document but on the `select` element, in this markup:

```html
<div class="outer">
  <div class="select">
    <div class="inner"></div>
  </div>
</div>
```

Since `.select` does not contain `.outer`, one might have thought that asking it for `.outer .inner` would not find `.inner`. That is, one might have thought that `querySelector` is scoped to the element is is called on. But apparently it isn't, it considers the whole document when applying the selector, although it only returns matched elements that were actually inside the element it was called on.

Still, it seems clear enough that this example is confusing! Actually it's doubly confusing because this page is for `**Document**.querySelectorAll`, and this is AFAICT showing behavior specific to `**Element**.querySelectorAll`.

**Comment by robonzo23** [comment]
Thanks for clarifying @wbamberg I just misunderstood what the paragraph was trying to say

**Comment by TheNewsYorkTime** [comment]
Thanks @wbamberg my brain was broken when I wrote that probably. Now I understand what it's trying to do better.
