### ISSUE TITLE
[ON HOLD] [Behind Pref] [Web API] Sanitizer implement namespace handling

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#24400]
## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [ ] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1784040

## Other

- [ ] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [ ] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [ ] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by hamishwillee** [comment]
Status: 

- This feature generalizes the [HTML Sanitizer API](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Sanitizer_API), which currently allows you to sanitize HTML elements and attributes, to allow you to specify a namespace in the [`Sanitizer()` constructor](https://developer.mozilla.org/en-US/docs/Web/API/Sanitizer/Sanitizer).
  This allows you to sanitize SVG etc if you so wish in the same definition.
- In FF the feature is still behind a preference `dom.security.sanitizer.enabled`, so this is all hidden.
- The proposal is linked from here https://github.com/WICG/sanitizer-api/issues/181#issuecomment-1403361554

The problem is that it is not clear how this will progress to spec - or whether this is "stable". So it might be too early to document. I have asked for clarification on stability of this here: https://bugzilla.mozilla.org/show_bug.cgi?id=1784040
