### ISSUE TITLE
Incorrect note about `list-style-position` behaviors across browers

### ISSUE THREAD

**Issue by yarusome** [mdn/content#24502]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-position

### What specific section or headline is this issue about?

Try it

### What information was incorrect, unhelpful, or incomplete?

The last paragraph in the "Try it" [section](https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-position#try_it) claims different behaviors across browsers for `list-style-position: inside` if a block element is placed first in the list element:

 - Chrome and Safari place the block element on the first line;
 - Firefox, Opera, Internet Explorer place the block element on the second line.

However, according to [Comment 38](https://bugzilla.mozilla.org/show_bug.cgi?id=36854#c38) of Mozilla Bug 36854, Chrome also places the block element on the second line in this case, but Safari *may* still places it on the first line.

### What did you expect to see?

The note be corrected.

### Do you have any supporting links, references, or citations?

Mozilla Bug 36854: https://bugzilla.mozilla.org/show_bug.cgi?id=36854
WebKit Bug 227000: https://bugs.webkit.org/show_bug.cgi?id=227000

**Comment by Tunzeki** [comment]
I want to work on this.

**Comment by wbamberg** [comment]
From https://bugzilla.mozilla.org/show_bug.cgi?id=36854 it seems like Firefox and Chromium implement the specced behavior and Safari doesn't.

So I think we should document the specced behavior in the page, and document Safari's divergence with a note in BCD, something like:

> In Safari, if a block element is the first child of a list element declared as `list-style-position: inside`, then the marker box is placed on the same line as the block element.

But also, I don't think we should have extensive text after "Try it". In cases like this we should have a "Description" H2 heading after "Syntax", as we do here: https://developer.mozilla.org/en-US/docs/Web/CSS/perspective#description. So I think we should do this for the `list-style-position` page, and include all the current content after "Try it" in there.

But we should also reorg this content a bit, and have three paragraphs (or maybe just two), like this:

para 1: - I would remove the "Note" styling from the second para, and make it the first para

para 2: - then I would have a version of the current third para, but only talking about the specced behavior, like:
> If a block element is the first child of a list element declared as `list-style-position: inside`, then the block element is placed on the line after the marker box.
...although tbh I would probably just delete this para since it seems obvious? @yarusome wdyt?

para 3: - what's currently para 1

@Tunzeki , if that makes sense to you, please go ahead and take this issue.

**Comment by yarusome** [comment]
@wbamberg Sorry for the late reply.

Actually, I digged deeper through WebKit's release notes and blogs and found in the [release blog](https://webkit.org/blog/11989/new-webkit-features-in-safari-15/) of Safari 15 that Webkit *claims* to have aligned its implementation with Firefox and Chrome. To quote:

> We also updated WebKit’s implementation of `list-style-position:inside` to match the updated [CSS specification](https://drafts.csswg.org/css-lists-3/#marker-pseudo), creating interoperability after a [22 year old debate](https://bugzilla.mozilla.org/show_bug.cgi?id=36854).

(I updated the issue at BCD but forgot to update here.)

---

I have no particular preference for deleting or keeping the third paragraph, though.

**Comment by wbamberg** [comment]
> @wbamberg Sorry for the late reply.
> 
> Actually, I digged deeper through WebKit's release notes and blogs and found in the [release blog](https://webkit.org/blog/11989/new-webkit-features-in-safari-15/) of Safari 15 that Webkit _claims_ to have aligned its implementation with Firefox and Chrome. To quote:
> 
> > We also updated WebKit’s implementation of `list-style-position:inside` to match the updated [CSS specification](https://drafts.csswg.org/css-lists-3/#marker-pseudo), creating interoperability after a [22 year old debate](https://bugzilla.mozilla.org/show_bug.cgi?id=36854).
> 
> (I updated the issue at BCD but forgot to update here.)
> 
> I have no particular preference for deleting or keeping the third paragraph, though.

That's curious, because I tried with Safari 16 and saw the different behavior: https://codepen.io/willbamberg/pen/GRXwWdm

Safari:

<img width="370" alt="Screen Shot 2023-03-24 at 10 02 31 AM" src="https://user-images.githubusercontent.com/432915/227592469-33b0c37b-72b0-4ca6-88fb-433497a2afea.png">

Chrome:

<img width="424" alt="Screen Shot 2023-03-24 at 10 04 13 AM" src="https://user-images.githubusercontent.com/432915/227592855-50c3c39b-dc62-4ea8-bad9-eedb35d92f55.png">
