### ISSUE TITLE
Improve lastmodified example with regex

### ISSUE THREAD

**Issue by bsmth** [mdn/content#24513]
https://developer.mozilla.org/en-US/docs/Web/API/Document/lastModified

__Background:__
The example is a little hard to read, we can make some minor rewrites for readability with something like:

```js
const pattern = /(?:(?:^|.*;)\s*last_modif\s*=\s*([^;]*).*$)|^.*$/
// ...
document.cookie.replace(pattern // etc.
```

_Originally posted by @bsmth in https://github.com/mdn/content/pull/24162#discussion_r1109769650_

**Comment by postmeback** [comment]
Hi @bsmth ,

I would like to help on this regex issue

**Comment by bsmth** [comment]
Thanks @postmeback - go ahead if you'd like to open a PR, feel free to add me as a reviewer 👍🏻

**Comment by postmeback** [comment]
`(?:.*;)?\s*last_modif\s*=\s*([^;]*)` is the simplified version of above regex.

**Explanation**

(?:^(?:.*;)\s*last_modif\s*=\s*([^;]*).*$) is simplified to (?:.*;)?\s*last_modif\s*=\s*([^;]*):
Removed the ^ and $ anchors: Since we don't have specific input context, it's unnecessary to anchor the pattern to the start and end of the string.
Replaced (?:^|.*;) with (?:.*;)?: The (?:^|.*;) part was looking for the start of the string or any characters followed by a semicolon. The .*; is made optional using ?, meaning it can match zero or one occurrence of any characters followed by a semicolon.
Removed the .*$ at the end: The .*$ was matching any remaining characters until the end of the string, but it's not necessary for simplification since we are only interested in the last_modif= part.

**Comment by bsmth** [comment]
Hi @postmeback thanks for taking a look. I don't think your example performs the same matching as the example intends, given the string:

```
last_modif=1685961978070; expires=Fri, 31 Dec 9999 23:59:59 GMT
```

the original will match the entire line, but the one you have posted only extends to the  semicolon. I think the example in general is a bit hard to understand and should be simplified or annotated with some comments

**Comment by postmeback** [comment]
Okay, I was  actually trying to achieve a simplified regex. But, it seems that we should keep the original regex with commenting

**Comment by Josh-Cena** [comment]
```js
Date.parse(document.lastModified) >
  (parseFloat(document.cookie.match(/last_modif\s*=\s*([^;]*)/)?.[1]) || 0)
```

Should work already :)
