### ISSUE TITLE
CSP sources no URL scheme is specified note

### ISSUE THREAD

**Issue by swilliamsui** [mdn/content#2460]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-src#sources

#### What information was incorrect, unhelpful, or incomplete?
How protocols without a scheme are treated is unclear. The [frame-ancestors#sources](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors#sources) note in yellow is much more clear.

![image](https://user-images.githubusercontent.com/5958078/108410252-2ebd0d80-71f5-11eb-87a6-d986543954ef.png)

#### Specific section or headline?
"Sources" -> "< host source >"

#### What did you expect to see?
Yellow box should be applied to all relevant locations.

#### Did you test this? If so, how?
N/A

**Comment by NegiAkash890** [comment]
Can someone please explain the issue further ? I think that I can fix the issue .

**Comment by CreaTorAlexander** [comment]
> Yellow box should be applied to all relevant locations.

@swilliamsui what would you expect to have as relevant locations?

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/3899 with a fix.

**Comment by sideshowbarker** [comment]
To whoever works on this:

The root cause of this is that the source of https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-src#sources is transcluded from https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/default-src#sources using the `page()` macro mechanism described in https://developer.mozilla.org/en-US/docs/MDN/Structures/Macros/Other#transclusion.

So a possible solution is to remove that `page()` macro call, and replace it with actual content in the source of the https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-src article itself.

The downside of that is that we end up duplicating quite a bit of content.

**Comment by bsmth** [comment]
Hi all, the most recent comment regarding the `page()` macro is no longer relevant as the page content has been restructured recently. What's outstanding here is a note on what the spec calls "schemeless host-source expressions" similar to the frame ancestors note.

If no scheme is provided as `<scheme-source>`:

* the same scheme as the origin is used
* upgrades are allowed (i.e., if the origin uses `HTTP`, then `HTTPS` is valid)
* downgrades are not allowed (i.e., `HTTP` will not match if the origin loads over `HTTPS`)

See https://www.w3.org/TR/CSP3/#match-url-to-source-expression
