### ISSUE TITLE
Minimum and maximum mixup in clamp()

### ISSUE THREAD

**Issue by Discostu36** [mdn/content#24833]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/clamp

### What specific section or headline is this issue about?

min, max, and clamp comparison

### What information was incorrect, unhelpful, or incomplete?

If I am not mistaken, this chapter mixes up minimum and maximum. These sentences are wrong:

> min() allows you set a maximum value.

No, a minimum value.

> max() allows you set a minimum value, which in cases like this is useful for accessibility purposes.

No, a maximum value and this does not help with accessibility.

> This means that the font-size will be set at 1.8rem, until the computed value of 2.5vw becomes greater than that of 1.8rem

No, unless it becomes smaller than 1.8rem

### What did you expect to see?

See above

### Do you have anything more you want to share?

I just learned above min(), max() and clamp() today, that is why I didn't feel confident enough to make the changes myself.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/clamp`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/clamp
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/clamp/index.md
* Last commit: https://github.com/mdn/content/commit/42c1bb8c259f3f57de9f38600776cf273e3addda
* Document last modified: 2023-02-21T06:27:49.000Z

</details>

**Comment by wbamberg** [comment]
It's confusing, and we could maybe explain this better, but I think it is correct.

You can see the example at https://mdn.github.io/css-examples/min-max-clamp/, and see the effect by changing the window width.

These examples are really all about setting sizes with a combination of:
- a value that's relative to the viewport width (`vw`)
- a value that's fixed as the viewport width changes (`px` or `rem`)

1. Say you start with a very narrow window and gradually drag the window to increase width The line length (controlled by the width of the body element) will increase as the window width increases, but only up to a certain point (1000px), and beyond that point it won't increase any more. So we're setting a **maximum** line length: it can go under 1000px, but won't go over. This is helpful because long lines are harder to read, so we often want to limit how long a line can be.

2. Say you start with the window full-width and gradually drag the window to decrease width. The size of the body text, controlled by `p { font-size}`, gets smaller as the window gets narrower, but only up to a certain point, and beyond that point (the point where `1.2vw` is less than `1.2rem`) it doesn't get any smaller: it stays at `1.2rem`. On my display this effect is hard to see: it would be easier with a smaller `rem` value, like `1rem`. So we're setting a **minimum** font size: the font can grow above `1.2rem` but will never go below it. This is helpful of course because really small text is hard to read.

3. "the font-size will be set at 1.8rem, until the computed value of 2.5vw becomes greater than that of 1.8rem" - this is correct although again could maybe be expressed more clearly. The "preferred" value here is `2.5vw`. But the minimum value is `1.8rem`. So if the computed value of `2.5vw` is less than `1.8rem`, then `1.8rem` will be used. Again, say you start out with a narrow browser window, such that `2.5vw` is less then `1.8rem`. So `1.8rem` is used for the heading. Now as you  drag to increase browser width, at some point the computed value of `2.5vw` will become more than `1.8rem`, so at the point `2.5vw` will be used. As you continue to increase the width of the window, the heading size will increase (since `vw` is computed as a fraction of the width) until the computed value exceeds `2.8rem`, and then it will be stuck at `2.8rem`.

Does that help? Do you think some words like this in the page would help?

**Comment by Discostu36** [comment]
Sorry, you are correct. It's funny that I was thinking about this enough to create an issue here and still didn't see that the mistake was on my side. Maybe it would be helpful if the examples stated something like “max() returns the highest of a list of values” and “min() returns the lowest of a list of values”. I think that the sentences with “minimum” and “maximum” are a bit misleading because you are (if I am not mistaken again) not setting “a maximum value” or “a minimum value” but two (or more). One of them is relative, the other one is absolute.

So, I'm not sure. You may just close this issue, or you may dumb the text down a bit for people like me ☺

**Comment by wbamberg** [comment]
I don't see it like "dumbing down" at all. Even if a page is technically correct, our job is to explain things as clearly as we can, and if people file issues because an explanation is not clear, then there's usually scope for us to improve it, and doing that adds value for everyone. Although I think it's a very nice example, I found the explanation confusing too and it took me some time to think it through to write my answer. So if I can find the words, I would like to try to improve it.
