### ISSUE TITLE
Incorrect image format used to demonstrate pixel quality

### ISSUE THREAD

**Issue by billmeier** [mdn/content#24854]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio

### What specific section or headline is this issue about?

Correcting resolution in a <canvas>

### What information was incorrect, unhelpful, or incomplete?

The example with writing "I love MDN" on a green box is blurry.

### What did you expect to see?

A high-quality image. You can't display a quality simple two-color image using jpeg lossy compression! This should be png format instead.

### Do you have any supporting links, references, or citations?

Adobe and many others says about using png

**They’re often the default format for screenshot images since they can provide a highly accurate representation of your desktop and don’t compress pixels together. A huge color palette and lossless compression ensure they retain plenty of detail — making them a popular choice for illustrations and charts.**

### Do you have anything more you want to share?

Here is an example zoomed in Photoshop. You can see the typical jpeg "fuzz" around the letters and the general noise in the image. The image on the right, if png, would be razor sharp! Or at least with png at most would be some anti-aliasing edges. Be sure to view this full-size, not the size in the box shown here (click on it with a big terminal window)

Given it's a graphic, and I'm new to MDN, I don't feel comfortable providing an alternate png file.

![mdn](https://user-images.githubusercontent.com/33092591/221318900-1f7e39f4-8fb7-412a-90fc-789c0d105725.png)
full-size

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/window/devicepixelratio`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/devicepixelratio/index.md
* Last commit: https://github.com/mdn/content/commit/bb8221e061bba27dbdbe5a3698b6c69febf0bc70
* Document last modified: 2023-02-19T07:19:47.000Z

</details>

**Comment by ferdnyc** [comment]
I don't think this is really accurate. While it's true that PNG preserves detail better than JPEG, for the purposes of demonstrating what it means to be demonstrating, the JPEG used is adequate.

I don't have a retina display, but I can fake it by just using the sample code (to which I added a display of the scaling factor directly inside the canvas) and hardcoding the scaling factors to 2.0 and 1.0, then increasing the page zoom to 200% in the browser. Here's a PNG screenshot of the results:

![Screenshot from 2023-03-29 11-08-05](https://user-images.githubusercontent.com/538020/228586860-5ca22696-085a-408b-9538-018895ae3c60.png)

And here it is converted into a JPEG:

![Screenshot from 2023-03-29 11-08-05](https://user-images.githubusercontent.com/538020/228586951-ff77c9a0-c4b4-42b3-93ba-d5f395d80477.jpg)

There _are_ differences, I'm not denying that, but they're mostly in details that require close inspection to make out.

A detail from the PNG, at 800% zoom:

![image](https://user-images.githubusercontent.com/538020/228588095-31f6a6a7-5622-40b8-bdbd-fa556d8486bf.png)

And the same section of the JPEG, also at 800%:

![image](https://user-images.githubusercontent.com/538020/228588252-f97df1f5-d32b-4379-ae93-7eead59bfe96.png)

Yes, at _severe_ enlargement, the details of the JPEG are **slightly** "fuzzier", and you can see haloing around the characters in the green background. With the PNG, every pixel of the green field is identical. But all of that pales in comparison to the difference in sharpness caused by the resolution bump, which is the central point of the demonstration. Any other lack of sharpness is primarily due to font antialiasing, which affects both encodings.

**Comment by Josh-Cena** [comment]
Yes, I believe the current image format is okay, for the purpose of a quick demonstration. Even if JPG is slightly blurred, both images are blurred to the same degree and their relative difference is still visible.

Further discussion on this is welcome, though.

**Comment by Josh-Cena** [comment]
Well actually, since I have Retina, won't be hard for me to fix this anyway :)

**Comment by billmeier** [comment]
The other reason is just to demonstrate by example the appropriate image format for the example! This is a demonstration and should use "best practices" for the choice of image format. You are attempting to show the quality and you should use an image format that best represents this, even if under some cases the difference can't be seen.
