### ISSUE TITLE
Autocomplete Article is INVALID for CHROME

### ISSUE THREAD

**Issue by jaseinatl** [mdn/content#24875]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

### What specific section or headline is this issue about?

Autocomplete=Off does not work in Chrome

### What information was incorrect, unhelpful, or incomplete?

Currently, even in your example where you have autocomplete=off for email, Chrome refuses to honor the request. 

Not only does Chrome refuse to turn Autocomplete off under almost any circumstance, it determines how it will style the list and that often conflicts with the form element.

For example, the rather extensive autocomplete list cannot be closed, moved, or minimized in Chrome. 
If scrolling the page when the autocomplete suggestions are present, the field will move but the autocomplete remains stationary. You can scroll the field off the screen and still see Chrome's autocomplete suggestions.

This creates numerous security concerns. People's login IDs are regularly exposed by this feature on public computers. People's account numbers are often disclosed. Private information about people gets disclosed and there is no recourse.

There are numerous trouble tickets open for Chrome that have remained unaddressed for at least 5 years.

You cannot style the elements other than by overriding the user-agent stylesheet on your own private version of Chrome. You cannot change the appearance of this broken feature on remote computers.

This needs to be made clear whenever autocomplete is mentioned regarding chrome. The existing workarounds keep failing with each new Chrome update. 

This is especially compounded when using the list attribute on an element. It refuses to only show the list elements, but rather adds the list items to the autosuggestion options.

UPDATE: As I was taking screenshots to demonstrate how it is impossible use AUTOCOMPLETE="off" , I found out for the first time by accident how to turn this nast feature off. Set autocomplete to some random value like "AUTOCOMPLETE="NOSHOW"  I still don't trust it, but for the purposes of getting screenshots, it appears to work. 

![image](https://user-images.githubusercontent.com/755697/221389975-7fca8dbb-9daa-4c4d-bc6a-65065096bdac.png)
figure 1 - shows how Chromes suggestion list obscures the content and is not prevented by automcomplete=off 

![image](https://user-images.githubusercontent.com/755697/221389997-248c0768-4a3a-491d-a94a-d7a8723fa6be.png)
Another example of the weird placement of the suggestion list by chrome with autocomnplete=off

![image](https://user-images.githubusercontent.com/755697/221390018-9ac64297-4b65-4f14-b6ba-5d4de3c59d0a.png)
final screenshow shows nonsense in the autocomplete field actually works for the first time in years.

### What did you expect to see?

Look at any of your pages with Autocomplete to see examples of this problem first-hand.

Chrome could resolve this issue by providing the ability to style the elements (including display:none).
They could solve the issue by following the existing web suggestions.
They could solve this issue by providing a close-box or minimize control on the popuplist so you can see the content it currently obscures.
They could solve this issue by allowing the user to move the autocomplete suggestions

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/attributes/autocomplete`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/attributes/autocomplete/index.md
* Last commit: https://github.com/mdn/content/commit/ba96f2f183353872db6d9242c7d2dffe2dbc0c35
* Document last modified: 2023-02-24T05:52:35.000Z

</details>

**Comment by Josh-Cena** [comment]
This is already in the [browser compatibility table](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#browser_compatibility):

> Chrome does not accept `off` as a value. See [bug 587466](https://crbug.com/587466).

In general, our policy is to not document browser incompatibilities in the main content, unless the implementor has explicitly stated disinterest in implementing the spec. Because we don't control Chrome's development, I see nothing actionable on our side. MDN's duty is only to faithfully document the web.

**Comment by jaseinatl** [comment]
Except that you give a table below that shows full support in Chrome. The bug itself is clearly indicative of the fact that Chrome does not support it and never has. In effect, you are lying to us and we just have to accept it.

I can't help but wonder why you have little notes in other articles that DO outline incompatibilities and workarounds or links to other content. Isn't that what those notes are for?

**Comment by jaseinatl** [comment]
![image](https://user-images.githubusercontent.com/755697/221522162-0ef77629-763a-4926-ab1d-32c27f574920.png)

You don't seem to have a problem with pointing out incompatibilities with Firefox:

**Comment by Josh-Cena** [comment]
We don't have a strict policy saying "X cannot appear in prose", and traditionally people find it more convenient to edit prose than the browser compatibility data. However, the baseline is that "if something appears in BCD already, don't add it to prose".

cc @queengooborg do you think Chrome should be marked as partial support because of the lack of `autocomplete="off"`?

**Comment by hamishwillee** [comment]
> We don't have a strict policy saying "X cannot appear in prose", and traditionally people find it more convenient to edit prose than the browser compatibility data. However, the baseline is that "if something appears in BCD already, don't add it to prose".

@Josh-Cena I'd say we have a policy that X _should not_ appear in prose. Where possible compat info should go in the compat data, and be maintained there. 

It's _should_, not _must_ though. BCD is pretty limited about the size of info you should include.

**Comment by queengooborg** [comment]
> BCD is pretty limited about the size of info you should include.

Not really!  Although we encourage notes to be kept short, it's not a hard limitation or anything we strictly enforce!

In the end, I would _love_ for all compatibility notes to live within BCD, both to keep all compatibility info in one place and to make these notes accessible to other parties (ex. JetBrains' IDEs, VSCode, etc.).  Back in the wiki era, browser compatibility data lived within the content itself as HTML tables, meaning that anyone could update the data without awaiting review.  As BCD was the first to transition to a Git codebase and required review, contributors wanted to stick with the convenience of editing the wiki pages directly and quickly, thus compatibility notes were added directly to the pages rather than to BCD.

In regards to marking partial support for the feature, that's a good question.  Normally speaking, if a single value wasn't supported in a specific browser engine, I'd say that a simple note like what we have is sufficient -- or if it's multiple engines, AKA both Chrome and Firefox, I'd aim for a subfeature.  `"off"` seems like a core value...hmm.  I'll give this some thought!  (Ultimately, this does seem like a BCD issue in the end, rather than a content issue!)
