### ISSUE TITLE
Double reference to KeyframeEffect on AnimationEffect page

### ISSUE THREAD

**Issue by sophiebits** [mdn/content#24969]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/AnimationEffect

### What information was incorrect, unhelpful, or incomplete?

The page says:

> The AnimationEffect interface of the Web Animations API defines current and future animation effects like **KeyframeEffect**, which can be passed to Animation objects for playing, and **KeyframeEffect** (which is used by CSS Animations and Transitions).

(emphasis mine)

### What did you expect to see?

I'm not sure exactly what was intended but I imagine one of the KeyframeEffect mentions was meant to be something else.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/animationeffect`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/AnimationEffect
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/animationeffect/index.md
* Last commit: https://github.com/mdn/content/commit/bca8d1ab2bc4f5a1ef6b39c454b0229539178e98
* Document last modified: 2023-02-18T07:09:59.000Z

</details>

**Comment by wbamberg** [comment]
Thank you for filing!

It looks like what happened here is:
- there used to be another interface, called `KeyFrameEffectReadyOnly`, but it was dropped from the spec: https://www.w3.org/TR/2018/WD-web-animations-1-20181011/#changes-since-last-publication
- we deleted the old page for that, and set up a redirect to `KeyFrameEffect`, but never updated this page, so the link here still had the text `KeyFrameEffectReadyOnly`)
- some time later, [in an automated PR to fix redirects](`KeyFrameEffect`), we changed this link to so it went directly to `KeyFrameEffect`

...so now we have this weird text.

So there used to be 2 concrete interfaces based on `AnimationEffect`: `KeyFrameEffect` and `KeyFrameEffectReadyOnly`. Now there's only `KeyFrameEffect`.

Perhaps we could say something like:

> The AnimationEffect interface of the [Web Animations API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Animations_API) is an abstract interface representing animation effects. The [KeyframeEffect](https://developer.mozilla.org/en-US/docs/Web/API/KeyframeEffect) interface, which inherits from this interface, can be passed to [Animation](https://developer.mozilla.org/en-US/docs/Web/API/Animation) objects for playing, and is also used by [CSS Animations](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Animations) and [Transitions](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Transitions).

?

**Comment by sophiebits** [comment]
Good sleuthing. Thanks for the fix!
