### ISSUE TITLE
[HTTP] Fetch client certificates workaround

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#2500]
## Acceptance criteria

1. - [ ] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated
3. - [x] Interactive example and data repos are updated if appropriate
4. - [ ] The content has been reviewed as needed

## Features to document

1. Add a preference to enable sending client certificates when Fetch's credentials mode would exclude them, even though the spec says not to

## Related Gecko bugs

1. - [ ] [Add a preference to enable sending client certificates when Fetch's credentials mode would exclude them, even though the spec says not to](https://bugzilla.mozilla.org/show_bug.cgi?id=1511151). This is an interesting one — kind of a weird spec bug workaround. This probably needs a rel note, plus a useful note explaining this on a few pages (e.g. Fetch credentials property page, CORS, etc.)

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by hamishwillee** [comment]
Overview of what needs to be done following review: 
- [ ] Add release note
- [ ] Add dev-doc-complete
- [ ] BCD - Not required
- [ ] Interactive example - note required
- [ ] Docs updates
- - [ ]  Add a section or note in [Cross-Origin Resource Sharing (CORS) > Requests with credentials](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#requests_with_credentials) to outline the exception here.
- - [ ]  Tidy up [Using Fetch > Sending a request with credentials included](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#sending_a_request_with_credentials_included). I think we should NOT mention the preference here because this is an exception. But cross link to more CORS information (above link) to make it clear would be useful

Note also that [bugzillla 1019603](https://bugzilla.mozilla.org/show_bug.cgi?id=1019603#c36) indicates that in future release this might flip over to default enabled rather than default disabled.
