### ISSUE TITLE
possible incorrect explanation of deleteCount parameter in splice()

### ISSUE THREAD

**Issue by Careless-Whisper999** [mdn/content#25070]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice

### What specific section or headline is this issue about?

Syntax-Parameters-deleteCount

### What information was incorrect, unhelpful, or incomplete?

The second paragraph mentioned that "If deleteCount is omitted, or if its value is greater than or equal to the number of elements after the position specified by start, then all the elements from start to the end of the array will be deleted". However, if we pass in undefined as deleteCount (in this case, deleteCount is omitted) to the splice function, nothing is deleted. This might be a mistake.

### What did you expect to see?

I expect to see that when deleteCount is omitted, nothing should be deleted.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/splice`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/splice/index.md
* Last commit: https://github.com/mdn/content/commit/194d3e00cb93a6e5ea44812548f4131cb17f0381
* Document last modified: 2023-02-21T00:33:25.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi, `undefined` and omitted are different.

<img width="171" alt="image" src="https://user-images.githubusercontent.com/55398995/222939890-0163865c-29c5-426c-a8bf-34697504bfff.png">

`undefined` is coerced to `0` when going through [integer conversion](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number#integer_conversion), while omitted explicitly goes down a different code path. See [spec](https://tc39.es/ecma262/multipage/indexed-collections.html#sec-array.prototype.splice):

> 9. Else if deleteCount is not present, then
>   a. Let actualDeleteCount be len - actualStart.
> 10. Else,
>   a. Let dc be ? [ToIntegerOrInfinity](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-tointegerorinfinity)(deleteCount).

This paragraph in fact already explicitly says what happens when `deleteCount` is omitted vs. `undefined`, so I don't think we need to change any text here.
