### ISSUE TITLE
[WebAPI] ClipboardItem

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#2514]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated
3. - [x] Interactive example and data repos are updated if appropriate
4. - [x] The content has been reviewed as needed

## Features to document

1. `ClipboardItem`

## Related Gecko bugs

1. - [x] [Implement ClipboardItem](https://bugzilla.mozilla.org/show_bug.cgi?id=1619947)

This is already documented for the most part, but the docs are not quite finished. The whole lot could do with checking. Also the BCD needs updating.

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by Rumyra** [comment]
OK so... 😅 ClipboardItem...

The spec has changed since I last published the initial docs in June-ish time. There are a few extra properties and methods. These are: 

- ClipboardItem.createDelayed()
- item.presentationStyle
- item.lastModified
- item.delayed

However these are not implemented in either FF or Chrome, apart from item.presentationStyle in FF. Now I'm happy to whip up a page for this, however none of the above have any explainer within the spec https://www.w3.org/TR/clipboard-apis/#clipboard-interface

Presentation style seems to represent whether an item is to be pasted as an attachment or inline. This is quite difficult to explain without an example, which is also quite difficult to create as there is no other functionality around pasting something as an attachment.

However BCD looks up to date so there is that :)

**Comment by jpmedley** [comment]
I can't even find that any work is being done on these in Chrome. By the way, presence of an item in draft spec is no guarantee that it will survive in that form (or at all) into a production version of any browser. In fact the last proposed enhancement to this API made it (if I remember correctly) nearly to an origin trial before being killed on security grounds. This is why I never document anything until we're very close to having product in the can.

In spite of that, I went ahead and reviewed the draft. (Not really thinking things through today, but oh well.) In the review I poked one of the spec authors on a few items. This should start a dialog that will get us some clarity on where this is heading. (See if these features don't also get tied up in security issues.)

**Comment by Rumyra** [comment]
Last thing:

Removing members that haven't been implemented as they are not added to BCD. It's easy enough to add them back in when they are 👍 https://github.com/mdn/content/pull/2934

**Comment by jpmedley** [comment]
👍

**Comment by chrisdavidmills** [comment]
OK, this is all looking good, so I think we're done here!
