### ISSUE TITLE
[CORE] Let CTAP2 support ride the trains (Web Auth)

### ISSUE THREAD

**Issue by bsmth** [mdn/content#25361]
## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [ ] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

`security.webauthn.ctap2` true by default

Check experimental notes, this should be removed if we have an entry for this.
Some release notes exist for this already, linked below.

>Release Note Request (optional, but appreciated)
[Why is this notable]: This adds support for USB security keys that use version 2 of the FIDO Client to Authenticator Protocol. The new implementation also handles version 1 of the protocol through a backwards compatibility layer. Users will find that some sites provide them with new authentication options, such as a fully passwordless login using a public key credential stored on their security key. Obviously we were not able to test with every make and model of security key, so we might get reports of broken U2F flows from users with older or unusual models.
[Affects Firefox for Android]: No
[Suggested wording]: Users on macOS, Linux, and Windows 7 can now use FIDO2 / WebAuthn authenticators over USB. Some advanced features, such as fully passwordless logins, require a PIN to be set on the authenticator.
[Links (documentation, blog post, etc)]:

> Relnote for beta 112 is now available at https://www.mozilla.org/en-US/firefox/112.0beta/releasenotes/

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1814487

## Other

- [ ] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [ ] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [ ] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by hamishwillee** [comment]
Status:
1. There are no instances of `security.webauthn.ctap2` in BCD or in our docs
2. There is a description of the [underlying technology here](https://duo.com/blog/webauthn-passwordless-fido2-explained-componens-passwordless-architecture#:~:text=What%20is%20FIDO2%3F,Web%20Authentication%20API%20(WebAuthn).)
3. The Firefox [beta release note](https://www.mozilla.org/en-US/firefox/112.0beta/releasenotes/) says:
   > Users on macOS, Linux, and Windows 7 can now use FIDO2 / WebAuthn authenticators over USB. Some advanced features, such as fully passwordless logins, require a PIN to be set on the authenticator.
4. The summary of this looks like you can now plug in a USB authenticator stick, if you match the biometrics (say thumbprint) then it will authenticate you with the browser, via the remote server that has registered the stick. The stick must contain a unique public key so that the remote end can verify that this key + this person are intimately matched.

The question for MDN though, is what APIs are affected - we're not interested in broad features that don't impact developers.
This possibly has an impact on https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API.
Asking here: https://bugzilla.mozilla.org/show_bug.cgi?id=1814487#c9

NOTE, not assigning to me. I think this probably requires a bit of expertise in the domain.

**Comment by hamishwillee** [comment]
The developers [responded to query about this](https://bugzilla.mozilla.org/show_bug.cgi?id=1814487#c9) with:

> I don't think we need to update the MDN documentation for CTAP2. We'll be adding more web developer-facing WebAuthn features that depend on CTAP2 through [Bug 1765549](https://bugzilla.mozilla.org/show_bug.cgi?id=1765549) and [Bug 1802863](https://bugzilla.mozilla.org/show_bug.cgi?id=1802863). We can update the documentation as those changes are made.

So in essence this particular set of changes is not particularly developer-facing, so there is no story. I'm closing this with no action at all other than to remove the dev-doc-needed.

**Comment by bsmth** [comment]
Thanks for the research, Hamish, much appreciated 🙏🏻
