### ISSUE TITLE
declarativeNetRequest WebExtensions API is missing the expected entries in the sidebar

### ISSUE THREAD

**Issue by rpl** [mdn/content#25396]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/declarativeNetRequest

### What specific section or headline is this issue about?

properties, methods and events of the declarativeNetRequest API namespaces are missing from the sidebar

### What information was incorrect, unhelpful, or incomplete?

The WebExtensions API reference page related to declarativeNetRequest is currently missing the expected entries in the sidebar:

![image](https://user-images.githubusercontent.com/11484/225758352-388b6d71-da6e-4fed-8032-6c64e24e04c5.png)

### What did you expect to see?

The list of properties, methods and events part of the declarativeNetRequest to be listed in the related sidebar entry, e.g. like the cookies WebExtensions API shown in the screenshot below:

![image](https://user-images.githubusercontent.com/11484/225758764-05a631f5-b914-4ebb-8bed-d2a611f1a992.png)

**Comment by rpl** [comment]
@rebloor would you mind to take a look into this?

**Comment by wbamberg** [comment]
The problem is that the pages need `page-type` values for the sidebar to work properly, now that we are not using tags for this any more. I neglected to document page type values for WebExtensions when we added them, but just did so: it's not live yet but you can see the values at the preview URL: https://pr25397.content.dev.mdn.mozit.cloud/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types/Page_type_key#webextensions_page_types.
