### ISSUE TITLE
Role of definition and aria-labelledby

### ISSUE THREAD

**Issue by ssimo3lsuhsc** [mdn/content#25393]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/definition_role

### What specific section or headline is this issue about?

Description

### What information was incorrect, unhelpful, or incomplete?

The definition ARIA role can be included on an element that is a definition of a term or concept, similar to the native [<dfn>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dfn) element. To associate the definition with the term being defined, and to provide an accessible name, reference the term being defined with role="term", using [aria-labelledby](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby).

<p>
  <span role="term">Mansplaining</span>,
  <span role="definition"
    >a portmanteau of "man" and "explain", is the patronizing act of explaining
    without being asked to do so, to someone already learned on the topic, often
    after someone has already explained it</span
  >.
</p>

### What did you expect to see?

Let me re-quote the second sentence above:
To associate the definition with the term being defined, and to provide an accessible name, reference the term being defined with role="term", using [aria-labelledby](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby).

I expect that the code block demonstrates just this.

The correct code block is one of the following options. I trust that the editors of the Mozilla documentation are knowledgeable enough to tell me whether option A or B is correct.

Choice A

```
<p>
  <span role="term" id="mansplaining">Mansplaining</span>,
  <span role="definition"
    aria-labelledby="mansplaining">a portmanteau of "man" and "explain", is the patronizing act of explaining
    without being asked to do so, to someone already learned on the topic, often
    after someone has already explained it</span
  >.
</p>
```

Choice B
```
<p>
  <span role="term" aria-labelledby="mansplaining">Mansplaining</span>,
  <span role="definition" id="mansplaining"
    >a portmanteau of "man" and "explain", is the patronizing act of explaining
    without being asked to do so, to someone already learned on the topic, often
    after someone has already explained it</span
  >.
</p>
```

### Do you have anything more you want to share?

I'm working on a project where the items I want with `role="term"` and `role="definition"` are adjacent siblings, but the `role="list"` is more than one step up the tree. That's why I can't use `ul`, `li`, `dl`, `dt`, or `dd`

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/accessibility/aria/roles/definition_role`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/definition_role
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/accessibility/aria/roles/definition_role/index.md
* Last commit: https://github.com/mdn/content/commit/a12fb8f2612fbdc6635b68c1dcd3c2fce212c10c
* Document last modified: 2023-02-23T10:50:32.000Z

</details>

**Comment by Andrew-Cottrell** [comment]
References from [WAI-ARIA 1.3](https://w3c.github.io/aria/) (W3C Editor's Draft 10 March 2023)
- https://w3c.github.io/aria/#definition
- https://w3c.github.io/aria/#term
- https://w3c.github.io/aria/#aria-details

Both `role="definition"` and `role="term"` prohibit `aria-labelledby` and

> If there is an existing [definition](https://w3c.github.io/aria/#definition), or a form or form control to enter a definition, authors **SHOULD** set [aria-details](https://w3c.github.io/aria/#aria-details) to point to the related element.

Unfortunately, there is no [ARIA design pattern example](https://www.w3.org/WAI/ARIA/apg/example-index/) for either `role="definition"` or `role="term"`.

The WAI-ARIA 1.3 specification for `aria-details` includes

> Definition: `aria-details` is applied to an element with role [term](https://w3c.github.io/aria/#term) and refers to an element with role [definition](https://w3c.github.io/aria/#definition).

I think it would be less distracting to change the example to be about the term "The Pythagorean Theorem" rather than the pejorative term "[Mansplaining](https://en.wikipedia.org/wiki/Mansplaining)".

Assuming WAI-ARIA 1.3 may be followed, the description and example could be

> The `definition` ARIA role can be included on an element that is a definition of a term or concept, similar to the native [`<dfn>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dfn) element. To associate the `term` being defined with the definition, reference the definition using [aria-details](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-details).

```html
<p>
  <span role="term" aria-details="pythagorean-theorem-details">The Pythagorean Theorem</span>,
  <span role="definition" id="pythagorean-theorem-details">
    a relationship in Euclidean Geometry between the three sides of a right triangle,
    where the square of the hypotenuse is the sum of the squares of the two opposing sides.
  </span>.
</p>
```

```html
<p>
  <dfn>The Pythagorean Theorem</dfn>,
    a relationship in Euclidean Geometry between the three sides of a right triangle,
    where the square of the hypotenuse is the sum of the squares of the two opposing sides.
</p>
```

**Comment by estelle** [comment]
The first rule of ARIA](https://www.w3.org/TR/using-aria/#rule1) use is "If you can use a native HTML element or attribute with the semantics and behavior you require already built in, instead of re-purposing an element and adding an ARIA role, state or property to make it accessible, then do so."

For this reason, many of the examples in the in the ARIA roles and properties pages explain how the role or aria-* attribute can be used properly, and then provide a preferred semantic alternative that doesn't use any ARIA. This is why there are two examples on this page: the way it can be done with ARIA, and the better alternative that respects the first rule of ARIA.
