### ISSUE TITLE
Banging heads

### ISSUE THREAD

**Issue by Ryuno-Ki** [mdn/content#2545]
Our writing guidelines recommend not to use banging heads:
https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Writing_style_guide#Heading_dos_and_donts

These are headlines (of different levels) which follow directly on each other.
I could find one example in #2532 and have seen some others.

In fact, `ack -A2 \<h2 files/en-us/ | ack \<h3 | wc -l` reports 3491 occurences.

What shall we do with them? Letting go of the guideline rule? Edit the articles?

**Comment by chrisdavidmills** [comment]
There are a lot of them about, and in some cases they are probably unavoidable.

I think you should take the recommendation to mean "don't do this where possible", rather than "don't do this ever". It is more important for guides/tutorials than reference articles, although I'd prefer to avoid it if we can.

I don't think we need to do anything here. It is a still a recommendation that we want to make, but the headings that don't follow this recommendation are not a big enough problem that we need to spend a bunch of time tracking down and removing all instances. There are move important things to fix right now.
