### ISSUE TITLE
Issue with "Django Tutorial Part 8: User authentication and pe…": (short summary here please)

### ISSUE THREAD

**Issue by pocockcb** [mdn/content#2555]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Authentication

#### What information was incorrect, unhelpful, or incomplete?

This is such a small problem and it may be of my own making but in part 8  of the tutoria when I updated 
 'DIRS': [os.path.join(BASE_DIR, 'templates')], in  setting .py. I got an error because I had not included  "import os".

This was quickly resolved but as a nephyte Django person, it did take a couple of minutes to figure out. I did a quick search to see if the "import os" was included in precious sections but could not find it. (Yes it is a minor problem but perhaps it could be a stumbling block for someone)

This tutorial is FANTASTIC - it is so much better and more inclusive then anything on Utube or udemy and allows you to go at your own pace.  Being able to cut and paste eliminates stupid typing errors and enables you to concentrate on the code and what it is doing.  

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/django/authentication`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Authentication
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/django/authentication/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by hamishwillee** [comment]
@pocockcb Good catch - you're definitely correct. It's been a while, but I suspect that we changed to using the OS import in the section relatively recently and at that point the import code from development section was already present.

Glad you like the tutorial - I was pretty pleased with it. The one on Django site also really good, but possibly requires a little more Python experience. 

This is fixed by https://github.com/mdn/content/pull/2919
