### ISSUE TITLE
'express-validator' .escape() function could have been explained better, or with an example at least

### ISSUE THREAD

**Issue by hrHVN** [mdn/content#25568]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_genre_form

### What specific section or headline is this issue about?

Create genre form

### What information was incorrect, unhelpful, or incomplete?

whilst testing the XSS filter it sort of works, but it creates a new Genre with the formatted script tag as the new genre

The new genre: "<script></script>" ==  [&#x27;&lt;script&gt;&lt;&#x2F;script&gt;]

This could perhaps have been emphasized with examples at the end of the document, since it is partially mentioned in the "Controller - POST route" section. **Quote:**
> and then uses escape() to remove any dangerous HTML characters).

### What did you expect to see?

I really expected the POST to fail with an error message as I only passed a script tag to the form.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/forms/create_genre_form`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_genre_form
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/forms/create_genre_form/index.md
* Last commit: https://github.com/mdn/content/commit/4def230f85756724b59660e3cd9de363db724ef8
* Document last modified: 2023-02-24T00:05:28.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks. I'm closing this because it is your expectation that was wrong. The article does what it says, which is reformat the string so it is not dangerous. That script should be changed to `&lt;script&gt;&lt;&#x2F;script&gt;`

Consider that an application has no idea of what you're going to input - all it knows is that this might be dangerous and that there are a lot of clever people out there who are trying to work particular ways around the security. So we don't look for "script" in the input and create an error, we just remove all the input that might contain potentially executable code, and change into something that can be rendered in a UI that is aware of the character codes.
