### ISSUE TITLE
Incomplete example

### ISSUE THREAD

**Issue by DomOBU** [mdn/content#25666]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/flex

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/CSS/flex#examples

### What information was incorrect, unhelpful, or incomplete?

Hello,

It seems that :
- the CSS is incomplete
- the JS is missing

(see the fr page)

### What did you expect to see?

that the example be completed

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/flex`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/flex
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/flex/index.md
* Last commit: https://github.com/mdn/content/commit/66944f622b6b51bc9c24bebbbea242138d910600
* Document last modified: 2023-02-21T05:45:53.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi, the fr page should be updated to hide the JS code. English version is always the source of truth.

**Comment by wbamberg** [comment]
I think we should do the opposite, and update the en-US page to show the code. As a rule I think we should discourage `hidden` in live samples, because it's always confusing when the example has behavior that's not visible in the code.

Someone was confused about this just the other day: https://github.com/mdn/content/issues/25552.

There are legit use cases for hiding code, sometimes, probably, but I think they are quite rare.

**Comment by Josh-Cena** [comment]
The idea is that the JS is implementation detail—much like the interactive example implementation. Readers only need to understand that "an element disappears when the box is clicked", not how it's implemented. This makes the example focused on what's being illustrated, rather than trying to be a standalone functional application.

**Comment by wbamberg** [comment]
I think it's really unclear what this example is doing, actually. Yes, the element disappears. Why? What happened to make it disappear? What is this showing? What does "toggle" mean here? What is a raw box?

> not how it's implemented

It is important to know what happened. Maybe it disappeared because we somehow set its flex to occupy no width? 

I would be OK with hiding the code if there were some explanatory text, something like:

> This example shows how a flex item with `flex: auto` grows to absorb any free space in the container.
>
> Initially the flex container contains two flex items, labeled "Flex box" and "Raw box". The "Flex box" item has `flex:auto;` and the "Raw box" item has the default value of `flex`. The "Raw box" takes up as much space as its `width` requires, but does not expand to take up any more space. All the remaining space is taken up by "Flex box".
>
> When you click "Flex box", we set "Raw box" to `display: none`, removing it from the layout. The "Flex box" item then expands to occupy all the available space in the container.

But even then I think we should show the code here. If it were a lot of code, I would agree, but it's a tiny bit, and the explanatory value of adding it outweighs the cognitive load we impose on the reader.

**Comment by Josh-Cena** [comment]
Mmm, fair enough. Let's show the code in this case.
