### ISSUE TITLE
Issue with "Tutorial: Set a breakpoint": Obsolete info on this page about Scratchpad

### ISSUE THREAD

**Issue by mian-lu** [mdn/content#2578]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Debugger-API/Tutorial-Breakpoint

#### What information was incorrect, unhelpful, or incomplete?
The section about "enabling Scratchpad" are obsolete, since Firefox 70 deprecated, and 72 removed the "Scratchpad" functionality.
https://developer.mozilla.org/en-US/docs/Tools/Deprecated_tools
This page above mentions that the new alternative is the "Run (multi-line Javascript code)" widget available within the Console tab. I believe this "Run" widget should replace references to "Scratchpad" on this breakpoint tutorial page.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/debugger-api/tutorial-breakpoint`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Debugger-API/Tutorial-Breakpoint
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/debugger-api/tutorial-breakpoint/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by Ryuno-Ki** [comment]
Lesson learned: GitHub cannot handle multiple people assigning labels m(

**Comment by Ryuno-Ki** [comment]
The edit would happen on

https://github.com/mdn/content/blob/f4b133613b01bbf5e700d42317ece3fd6dceeac2/files/en-us/tools/debugger-api/tutorial-breakpoint/index.html

**Comment by mian-lu** [comment]
> Lesson learned: GitHub cannot handle multiple people assigning labels m(

Good one 😂

**Comment by ayushi19031** [comment]
I want to work on this. Thank you!!

**Comment by Ryuno-Ki** [comment]
Great to hear!

Assigned this issue to @ayushi19031.
Let us know if you need help with something.

**Comment by ayushi19031** [comment]
Okayy thank you so much ! Have started working on it.

**Comment by ayushi19031** [comment]
Hello! I realised that the JS code given on this link:
https://developer.mozilla.org/en-US/docs/Tools/Debugger-API/Tutorial-Breakpoint
for using the debugger API is broken because Components object is deprecated. 

I searched a lot for the alternatives to Component, but I am not able to find any working solution for a web browser. 

I am a newbie here, so it will be really helpful if you can give me some suggestions on how to move forward with this. 

Thank you!

**Comment by ddbeck** [comment]
Hi, I'm closing this issue because [Firefox DevTools User Docs](https://firefox-source-docs.mozilla.org/devtools-user/index.html#firefox-devtools-user-docs) have moved off of MDN (see https://github.com/mdn/content/pull/14140 for details on content moved). If this issue is still applicable to the relocated documentation, please see the Firefox Source Docs site for details on raising bugs and contributing. Thanks for your understanding!
