### ISSUE TITLE
Status Code 304 does not mention that requests should not contain a body, as per RFC specification

### ISSUE THREAD

**Issue by TheYuriG** [mdn/content#26040]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/304

### What information was incorrect, unhelpful, or incomplete?

The RFC guidelines state the following:
> A 304 response is terminated by the end of the header section; it cannot contain content or trailers.

[Source](https://www.rfc-editor.org/rfc/rfc9110.html#status.304)

### What did you expect to see?

The MDN documentation makes no mention of this, other than a slight nudge when mentioning the status code `200 OK`.

The major backend frameworks will NOT send a response body when this code is set, even if you provide one, as they abide by the specifications. This can cause confusion when trying to use this status code and constantly seeing the response body is always empty.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/status/304`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/304
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/status/304/index.md
* Last commit: https://github.com/mdn/content/commit/45d4569a5f7c2a4e614b8e950b9e56fa890b9fed
* Document last modified: 2023-03-03T04:42:31.000Z

</details>

**Comment by hamishwillee** [comment]
I agree. This is relevant information.

The text is also a little unclear that it says "The equivalent [200](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/200) OK response would have included ..." BUT doesn't clearly state that this set of headers must be included in the 304. 

It might also be worth pulling some of the compatibility note detail across from https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204 instead of cross linking.

Would you like to create a PR to update the page?

**Comment by TheYuriG** [comment]
> Would you like to create a PR to update the page?

Yeah, i would actually love to be able to give something back after spending so many weeks just taking the information.

Walk me through what you need. I'm not used to writing for people, only technical documentation for other developers, but I'll probably be fine... probably...

**Comment by hamishwillee** [comment]
Hi @TheYuriG 

Thank you. You can't screw this up because either me or some other reviewer will make sure it is OK :-).

This is a fairly constrained change, so you don't really need to install the docs toolchain or read the [comprehensive guidelines](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines). Instead, for this case you can edit the page on github - there is a link at the bottom of the page: 
![image](https://user-images.githubusercontent.com/5368500/231027592-41b1bb81-63d7-4577-8606-e0856a85fa8e.png)

I would modify the first paragraph

> The equivalent [200](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/200) OK response would have included the headers....

TO

> The response must include the headers that would have been sent in an equivalent [200](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/200) OK response:

Then after that add your note about there being no payload. 

Then in the compatibility note section, copy across some of the relevant docs from the same section in the linked doc

Make sense? If not I can do it.

**Comment by TheYuriG** [comment]
> Thank you. You can't screw this up because either me or some other reviewer will make sure it is OK :-).

I was more worried about being unable to write human-readable language since all I see all day is code, code, code...

> I would modify the first paragraph
> 
> > The equivalent [200](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/200) OK response would have included the headers....
> 
> TO
> 
> > The response must include the headers that would have been sent in an equivalent [200](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/200) OK response:
> 
> Then after that add your note about there being no payload.
> 
> Then in the compatibility note section, copy across some of the relevant docs from the same section in the linked doc

Sounds good to me!

> Make sense? If not I can do it.

That makes sense, leave it to me, you guys must have more serious/important/difficult things to do instead. I'll create the PR later today at lunch time.

**Comment by hamishwillee** [comment]
Thanks very much! Looks good.
