### ISSUE TITLE
Regarding cache priority, the content expression is not rigorous enough.

### ISSUE THREAD

**Issue by bigbigDreamer** [mdn/content#26064]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching#expires_or_max-age

### What information was incorrect, unhelpful, or incomplete?

<img width="786" alt="image" src="https://user-images.githubusercontent.com/39019913/230753257-ef22e446-c203-4f60-927a-784fd7dffc5a.png">

### What did you expect to see?

> `ETag` takes precedence.

I think whether this is a priority or not depends on the implementation mechanism of the server. Assuming I implement a static resource server using Node, I can completely set `Last-Modified` as a priority.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/caching`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/caching/index.md
* Last commit: https://github.com/mdn/content/commit/eb9eef29f1ccdaf1c8a464dbe4483c78f7a13b2a
* Document last modified: 2023-03-03T04:45:34.000Z

</details>

**Comment by bigbigDreamer** [comment]
In fact, I have read [HTTP2616](https://www.ietf.org/rfc/rfc2616.txt), strong entity caching, according to the specification recommendations, it is true that 'Etag' has a higher priority, but I think the description here should be improved: the specific implementation rules still depend on how the cache server handles them.

**Comment by hamishwillee** [comment]
Thanks @bigbigDreamer. MDN documents the spec, which is how the cache server is _supposed_ to implement things. By that measure the current text is correct.

Further, if you look at the note, it is only peripherally about priority. That's just a mechanism to explain that it is worth including `Last-Modified` even though it won't be used during  during cache revalidation:

> So considering the overall HTTP ecosystem, it is preferable to provide both ETag and Last-Modified.

Upshot, this seems to be correct to me.

@teoli2003 - got any thoughts on this one? Perhaps I'm missing something.

**Comment by bigbigDreamer** [comment]
> if both ETag and Last-Modified are present, ETag takes precedence.

I have my own opinions on the expression of this sentence. While reviewing the specifications, I also took a look at the implementation of `express`, so I think:
**The specific priorities depend on how the server implements them, and the specification is only a guidance in terms of document meaning.**

<img width="807" alt="image" src="https://user-images.githubusercontent.com/39019913/230808414-45abdbb4-37c4-4f7a-96bd-ffe962111382.png">
@hamishwillee

**Comment by hamishwillee** [comment]
The way I read the [relevant part of the spec](https://www.ietf.org/rfc/rfc2616.html#section-13.3.4.), a server should sent both the entity tag/last modified tags unless it is not feasible to generate one - and a strong entity tag and a Last-Modified value are preferred. A client _must_ use an entity tag if provided and should use both entity tag/last modified if provided.

If the server sends both, which is the only case where you can discuss preference/priority, how is it up to the server to decide the priority of these headers? It is up to the consumer - either a client or a caching server. To me that means the implementation of the origin server, such as express, is not relevant - only the consumer, and only in the case where both headers have been set.

But even aside from that, what does it matter/how will it change the point of the note? Which is that there is a preference for both headers to be sent.

I'm not an expert, which is why I'll defer to @teoli2003 !

**Comment by hamishwillee** [comment]
@teoli2003 If I'm missing the point, and I may be, it would be easy to remove the discussion of priority, because it really is irrelevant to the note:

> **Note:** It is preferrable for origin servers to provide both `ETag` and `Last-Modified` headers.
> While only one header is required for cache validation, and `ETag` is preferred in the specification, `Last-Modified` is used for other purposes such as: content-management (CMS) systems to display the last-modified time, crawlers to adjust crawl frequency, and so on.

**Comment by teoli2003** [comment]
My understanding of the [latest spec](https://www.rfc-editor.org/rfc/rfc9110.html) (and RFC9111 for the cache itself) is that:
- servers should send both headers
- clients control the caches and decide the priority.
So it sounds like a good plan.

**Comment by bigbigDreamer** [comment]
> My understanding of the [latest spec](https://www.rfc-editor.org/rfc/rfc9110.html) (and RFC9111 for the cache itself) is that:
> 
> * servers should send both headers
> * clients control the caches and decide the priority.
>   So it sounds like a good plan.

I think this explanation should be mutual. When the response responds to both headers at the same time, the client should also send `If_None_Matched` or `If-Modify-Since` at the same time. As for negotiating this process, it should be sent on the server side (including cache servers), because they decide whether to send a `304` status code to tell the client whether to continue reusing cached resources or reload resources.
> * clients control the caches and decide the priority.

I don't quite understand which specific type of object the client you are referring to here represents.

------

Thank you for your replies despite being busy. If there are any mistakes or omissions in my understanding, I hope to receive criticism and correction.

**Comment by hamishwillee** [comment]
The only message of relevance to most readers is "send both headers if you can". That is the only point of the note. 

It says that the 



That said I suspect if both 


 @bigbigDreamer Wants to clarify the priorities - I don't see the value to readers of this document because we have given them a very clear message


. Let's ask the big guns.

@Jxck This is related to the note in https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching#expires_or_max-age

This makes a hand-wavy statement that ETag takes precedence if both headers are sent.


A client that suspects it might have

**Comment by Jxck** [comment]
In Latest HTTP spec (Please make sure to discuss based on latest spec RFC 9xxx)

> In 200 responses to GET or HEAD, an origin server SHOULD send any available validator fields (Section 8.8)
> for the selected representation, with both a strong entity tag and a Last-Modified date being preferred.
> --- https://www.rfc-editor.org/rfc/rfc9110#section-15.3.1-5

But spec also saids that 

> A recipient MUST ignore If-Modified-Since if the request contains an If-None-Match header field; the condition in If-None-Match is considered to be a more accurate replacement for the condition in If-Modified-Since, and the two are only combined for the sake of interoperating with older intermediaries that might not implement If-None-Match.
> --- https://www.rfc-editor.org/rfc/rfc9110#section-13.1.3-5

So if you only focus on "Caching", it seems that there are no benefit for Server to send both ETag & Last-Modified since Last-Modified will be ignored when Client sends back it with If-Modified-Since.
But it's not, since Last-Modified is not only for caching but also other use-cases which requires "when this resources modified last ?".

- Sever should sends (strong) ETag & Last-Modified on 200 for GET/HEAD if possible
- Client should use ETag in If-None-Match as validator instead of Last-Modified in If-Modified-Since

For Server implementation, there are tons of implementation and that (server implementations spec compatibility) is out of scope of MDN. MDN should based on Spec (and sometimes mentioning about  browser implementation).

And finally, I think the Note can be fixup like below

> Note: When evaluating how to use ETag and Last-Modified, consider the following: During cache revalidation, if both If-Modified-Since and If-None-Match are present, If-None-Match takes precedence for validator. Therefore, if you are only considering caching, you may think that Last-Modified is unnecessary. However, Last-Modified is not just useful for caching; instead, it is a standard HTTP header that is also used by content-management (CMS) systems to display the last-modified time, by crawlers to adjust crawl frequency, and for other various purposes. So considering the overall HTTP ecosystem, it is preferable to provide both ETag and Last-Modified. Therefore, RFC9110 prefers that Server should send both ETag & Last-Modified for 200 response if possible.

**Comment by hamishwillee** [comment]
Thanks very much @Jxck
I have updated the note in https://github.com/mdn/content/pull/26108/ - This turns the note around a bit, because generally it is better in docs to provide instructions then reasons - in this case the instruction is "best to send both tags". Hope I got it right.

@bigbigDreamer @teoli2003 Thanks for this. I've learned a bit too :-).

**Comment by bigbigDreamer** [comment]
#https://github.com/jshttp/fresh/pull/38
