### ISSUE TITLE
navigator.getAutoplayPolicy example is incomplete

### ISSUE THREAD

**Issue by MissedWarrior** [mdn/content#26179]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/getAutoplayPolicy

### What specific section or headline is this issue about?

Test autoplay policy for media element type

### What information was incorrect, unhelpful, or incomplete?

In the example there is no check for the `allowed` policy so you can get `Autoplay policy for media elements is allowed. Video has been muted to allow it to autoplay.`(see [pic](https://i.gyazo.com/ab6c7a9ead4c337b043340321ed1e091.png)). Also if the policy is `disallowed` you can get `Autoplay policy for media elements is disallowed. Video has been muted to allow it to autoplay.` while the video is not muted

### What did you expect to see?

It would be nice if there will be statements about `allowed` and `disallowed` policies. Examples:
`allowed`: `Autoplay policy for media elements is allowed. Video should be running right now`
`disallowed`: `Autoplay policy for media elements is disallowed. Video can't be played`

(there might be mistakes in grammar, sorry for that 😅)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/navigator/getautoplaypolicy`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/getAutoplayPolicy
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/navigator/getautoplaypolicy/index.md
* Last commit: https://github.com/mdn/content/commit/ef75c1741b450c2331204be5563ee964ad5f4c48
* Document last modified: 2023-04-07T06:16:45.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks very much. IN https://github.com/mdn/content/pull/26194  I have fixed the bug so that examples only state that the video is muted if it has been muted, which is in the disallowed case (and not in the other cases).

I haven't added explicit text for the allowed and disallowed cases about what will  happen with the video. The main reason is that what happens in these cases is obvious :-). I would have documented them as you suggest if I had done something to handle those cases.
