### ISSUE TITLE
What is asyncHandler?

### ISSUE THREAD

**Issue by danbraun** [mdn/content#26239]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/BookInstance_list_page

### What specific section or headline is this issue about?

bookinstanceController code

### What information was incorrect, unhelpful, or incomplete?

asyncHandler does not exist.

### What did you expect to see?

The method shouldn't be wrapped in this function which is not defined.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/displaying_data/bookinstance_list_page`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/BookInstance_list_page
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/displaying_data/bookinstance_list_page/index.md
* Last commit: https://github.com/mdn/content/commit/0586fbecaf6683f5e793cd9510397b630fb43e61
* Document last modified: 2023-04-14T05:20:55.000Z

</details>

**Comment by hamishwillee** [comment]
Hi @danbraun

The handler is set up when you set your routes in an earlier part of the tutorial: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/routes#bookinstance_controller

The purpose of the handler is covered in the earlier section https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/routes#handling_exceptions_in_route_functions. Note you should read the section before this too - they "tell a story in order".

The handler is then described again in the first tutorial for setting up a page: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Home_page#controller
I haven't duplicated this explanation in every tutorial, because it would be boring, and should not be necessary.

You may have missed this because you did the routes and earlier parts of the tutorial last week and then took a few days break. The documentation was just updated late last week so you would have missed this information. If so, many apologies.

I'm, going to close as "not a defect", but if I'm missing something feel free to reopen.

**Comment by danbraun** [comment]
Thanks for taking the time to explain that. It is very helpful.

**Comment by hamishwillee** [comment]
Great. Sorry you got caught in the docs update. I had to add this because mongoose no longer supports a callback API - only promises. The tutorial is much better for moving to await/async though, because you no longer have to include boilerplate for the error handling in every function. Good luck with the tutorial, and thanks for taking the time to raise issues.
