### ISSUE TITLE
A first splash into JavaScript assumes too much prior knowledge

### ISSUE THREAD

**Issue by Dan-Essin** [mdn/content#26608]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/A_first_splash

### What specific section or headline is this issue about?

As a beginner tutorial, assumes facts not in evidence

### What information was incorrect, unhelpful, or incomplete?

This first tutorial neglects to explain the "." in the querySelector statements. After much searching, I discovered that the example had assigned each element to a class and that the "." was a class selector as opposed to a "#" (also not mentioned which is an ID selector.

For a beginner these kind of omissions and assumptions are very distracting and disconcerting. It would have been better to assign ID's and use ID selectors for a first lesson unless you were going to take the trouble to explain all of this in the tutorial (which wouldn't be a bad idea)

### What did you expect to see?

What did I expect to see - a tutorial, not a guessing game.

### Do you have anything more you want to share?

I flunked mind-reading in school and, after 50 years of programming, have gotten very literal (like a compiler). I do not understand things intuitively, only if they are declared. The material is quite good, but obviously written by people who have no clue how little novices really know.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/a_first_splash`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/A_first_splash
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/first_steps/a_first_splash/index.md
* Last commit: https://github.com/mdn/content/commit/7ff26ceb6c6f1400d4297b22cb92e3786e35eac7
* Document last modified: 2023-02-26T18:57:36.000Z

</details>

**Comment by postmeback** [comment]
Considering it a complete beginner's guide, the point you noted out is valid. 

I would like to contribute over here. :smiley:

**Comment by Josh-Cena** [comment]
Unfortunately first steps in any language (or even, first steps in programming) faces the eternal dilemma of "useful vs. confusing". We could well provide a dumbed-down example like `const a = 1; const b = 2;` but we'd rather not do that, because our goal is to produce some cool results in the end. As a result, as you read through the instructions, you must take things at face value: for example, the syntax `document.querySelector(".guesses")` altogether fetches one HTML element. At this stage you are not supposed to know any of the syntax like dot access, function call, or string literals just yet, but only accept that `const x = ...` declares a variable with a value. You will learn more about how everything works in the following sections; we cannot and should not try to explain every bit when our goal is only to get a taste of a real-world program.

**Comment by postmeback** [comment]
To summarize, this issue does not stand "worthy" anymore. I believe it is good to close.
