### ISSUE TITLE
Document value argument to URLSearchParams's has() and delete()

### ISSUE THREAD

**Issue by annevk** [mdn/content#26604]
This was the most-requested feature in the URL Standard backlog.

Standard: https://github.com/whatwg/url/pull/735.

WPT: https://github.com/web-platform-tests/wpt/pull/39865.

**Comment by hamishwillee** [comment]
@Rumyra We don't document until there is at least one working implementation - tracking bugs copied from the linked items above indicate none yet:

* Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1442916
* Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1831587
* WebKit: https://bugs.webkit.org/show_bug.cgi?id=256369
* Deno: [Add value argument to URLSearchParams's has() and delete() denoland/deno#19000](https://github.com/denoland/deno/issues/19000)
* Node.js: [Add value argument to URLSearchParams's has() and delete() nodejs/node#47883](https://github.com/nodejs/node/issues/47883)

1. Which project would you like them added to for the backlog?
2. What's the best mechanism to track this so that we get a ping when one of the linked items goes live? Would be great to be able to put these in draft or something and make them "pop up" automatically when we're at the point documentation makes sense.
