### ISSUE TITLE
[Web API] Enable WebTransport for release

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#26684]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1831073

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [x] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by bsmth** [comment]
Relates to https://github.com/mdn/content/issues/26153

**Comment by hamishwillee** [comment]
Status

Yes, follow on to https://github.com/mdn/content/issues/26153. Essentially it is BCD update to remove the preffed version AND make some of the APIs no-longer-experimental, and corresponding updates to docs. Also release note.

- [ ] BCD
- [ ] Docs
- [ ] Release note
- [ ] dev-docs-complete

**Comment by hamishwillee** [comment]
Note, just got more information about what is not supported in https://bugzilla.mozilla.org/show_bug.cgi?id=1818754#c17 from the engineers. Useful resources being https://wpt.fyi/results/webtransport?label=experimental&label=master&aligned

The BCD changes done in https://github.com/mdn/browser-compat-data/pull/19983

The release notes still OK. The docs should theortically remove the sendorder options (such as https://developer.mozilla.org/en-US/docs/Web/API/WebTransport/createBidirectionalStream#sendorder) but since these are planned https://bugzilla.mozilla.org/show_bug.cgi?id=1816925 I think probably worth leaving them in docs so don't have to re-add them later.
