### ISSUE TITLE
[Web API] Ship module workers

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#26695]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1812591

Plus, from #26149:

- Support "import" in worklet scripts: https://bugzilla.mozilla.org/show_bug.cgi?id=1572644
- Implement Dynamic import for workers: https://bugzilla.mozilla.org/show_bug.cgi?id=1540913

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [x] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by hamishwillee** [comment]
Status

- [ ] BCD
  - [ ] https://github.com/mdn/browser-compat-data/pull/19835
- [ ] Docs
- [ ] Release notes/Experimental features
- [ ] dev-doc-complete

**Comment by eliot-akira** [comment]
I have a related question - please excuse me if this is the wrong place to ask.

I'm waiting for the feature release of **module support for service workers**. The progress is being tracked on Bugzilla here:

- Implement "module" service workers https://bugzilla.mozilla.org/show_bug.cgi?id=1360870

It is also described in the web.dev article linked in the previous comment, _Threading the web with module workers_, under the section "What about service worker?"

> The service worker specification [has already been updated](https://w3c.github.io/ServiceWorker/#service-worker-concept) to support accepting a JavaScript module as the entry point, using the same `{type:"module"}` option as module workers, however this change has yet to be implemented in browsers.

- https://web.dev/module-workers/#what-about-service-worker

I'm searching for a suitable GitHub issue that I can subscribe to, so that I can be informed of the progress of this feature when it ships in Firefox/Gecko. I'm hoping this current issue is close to it, or maybe this one in MDN Browser Compat Data.

- mdn/browser-compat-data#19391

**Comment by hamishwillee** [comment]
@eliot-akira The right issue to follow for service worker module support on Firefox is the one you found above https://bugzilla.mozilla.org/show_bug.cgi?id=1360870. Firefox does not support it. This issue delivers import and import() support on shared and dedicated workers, and import support on worklets. 

The best issue to track would probably be the BCD one you found: https://github.com/mdn/browser-compat-data/issues/19391
I might look at that this week and at least add chrome support info.

**Comment by eliot-akira** [comment]
@hamishwillee Great, thank you for the information. I'll keep an eye on those links and will let others know when there's progress.
