### ISSUE TITLE
HTTP Range request documentation doesn't specify how to deny Multipart range requests

### ISSUE THREAD

**Issue by mikkorantalainen** [mdn/content#26733]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests

### What specific section or headline is this issue about?

Multipart ranges

### What information was incorrect, unhelpful, or incomplete?

The documentation describes how to respond to multipart range query. However, if the server only wants to support single part range requests which do not require multipart handling, the documentation should describe the expected way to declare this.

The closest one can guess from the MDN documentation is responding HTTP 416 and explaining the situation in message body. However, this doesn't allow user agent to automatically convert the multipart request to repeated single part requests to fetch all the required ranges without blindly trying it.

### What did you expect to see?

MDN documentation should explain how the server should opt out of a multipart feature while still supporting simple range requests.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/range_requests`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/range_requests/index.md
* Last commit: https://github.com/mdn/content/commit/0880a90f3811475d78bc4b2c344eb4146f25f66c
* Document last modified: 2023-04-10T19:47:15.000Z

</details>

**Comment by bsmth** [comment]
Thanks for reporting, @mikkorantalainen. I think it's not that common for the major server implementations to support only single-part range requests without multi-part support. There are limits for security reasons, where some servers say a max of N parts can be requested to avoid excessive compute / CPU usage on the server, and in these cases, they send a 416 if that threshold is met AFAIK. In the `206` status:

>a server might want to send only a subset of the data requested for reasons of its own, such as temporary unavailability, cache efficiency, load balancing, etc. Since a 206 response is self-descriptive, the client can still understand a response that only partially satisfies its range request.

Does that make sense?

Have you encountered a case like this or are you building a custom implementation? What is the motivation for only supporting single part ranges?

Note that it may be more efficient to transmit the entire resource in a 200 rather than repeated single-part range requests.

- https://httpwg.org/specs/rfc9110.html#rfc.section.15.3.7

**Comment by bsmth** [comment]
I'm going to close this for now, but if I've misunderstood or made a mistake, feel free to reply and we can reopen if necessary.
