### ISSUE TITLE
German and English <img> element pages differ

### ISSUE THREAD

**Issue by flowl** [mdn/content#2683]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [X] Correction or update
- [ ] New documentation

The German and the English version of the HTML `img` tag differ.

On the German page, it explicitly mentions `%` to be valid in `width` or `height`.
On the English page, there is nothing about that.
Please be very clear about which types / units are valid across all languages of the documentation.

https://developer.mozilla.org/de/docs/Web/HTML/Element/img

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img

Edit; examples with my assumption:

    <img width="50"... valid, represents pixels
    <img width="50px"... strictly speaking, it's invalid, the only valid suffix is `%`
    <img width="50%"... valid but not mentioned to be valid on the english page
    <img width="50em"... invalid, not explicitly mentioned

**Comment by chrisdavidmills** [comment]
@flowl OK, reopened, and moved to the new content repo ;-)

Are you interested in submitting a pull request to fix this?

**Comment by dorward** [comment]
The English version is correct. The current version of HTML does only allow an integer value that represents pixels.

HTML 4.x allowed percentage values, but that is no longer supported. The German version of the page mentions the difference, but I think that should be de-emphasised as it is only of historical interest.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/2683#issuecomment-853784836 and also because correcting the German-language is not a current option, per the following:

https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ documents the MDN course of action with regard to translations, which is that the set of locales for which changes can be made is the following:

* Simplified Chinese (zh-CN)
* Traditional Chinese (zh-TW)
* French (fr)
* Japanese (ja)

All locales other than those are frozen unless/until someone submits a proposal for maintaining them going forward, “including evidence of an active team willing to be responsible for the work associated with that locale”.

If/when someone comes forward with such a proposal and evidence, we can revisit this issue.
