### ISSUE TITLE
Prevent exposure of MongoDB URI

### ISSUE THREAD

**Issue by josephrmartinez** [mdn/content#26873]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/deployment

### What specific section or headline is this issue about?

Save changes to GitHub

### What information was incorrect, unhelpful, or incomplete?

Current instructions will expose the MongoDB uri to the GitHub repo:

// Set up mongoose connection
const dev_db_url =
  "mongodb+srv://your_user_name:your_password@cluster0.lz91hw2.mongodb.net/local_library?retryWrites=true&w=majority";
const mongoDB = process.env.MONGODB_URI || dev_db_url;

### What did you expect to see?

Can this section be expanded to explain how to best handle API keys and the MongoDB URI during development and production? People following the tutorial should be able to follow each step in order without exposing their MongoDB URI at any point, correct?

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/deployment`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/deployment
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/deployment/index.md
* Last commit: https://github.com/mdn/content/commit/0586fbecaf6683f5e793cd9510397b630fb43e61
* Document last modified: 2023-04-14T05:20:55.000Z

</details>

**Comment by hamishwillee** [comment]
The section on [database configuration](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/deployment#database_configuration) does "almost" exactly this - it essentially says that you need to set your production details using an env variable. I guess we do expose our development URL, but that isn't such a concern.

Upshot, strictly speaking I don't see this as necessary, but perhaps we can be more clear on "why" using environment variables is a good idea.

**Comment by hamishwillee** [comment]
I'll check out the linked PR

**Comment by josephrmartinez** [comment]
Would it be good practice to move the development db url to a .env file during production? This may require some brief instruction on installing the dotenv package and properly formatting env variables. 

This would simplify the mongoose connection from:
// Set up mongoose connection
const dev_db_url =
  "mongodb+srv://your_user_name:your_password@cluster0.lz91hw2.mongodb.net/local_library?retryWrites=true&w=majority";
const mongoDB = process.env.MONGODB_URI || dev_db_url;

to: 
const mongoDB = process.env.MONGODB_URI 

It would have been helpful for me to know that it isn't such a concern to expose development credentials. I get it now, I'm just thinking that someone working through the tutorial for the first time might be apprehensive about why they are being instructed to commit this line with their username and password; they may have chosen a password that they use for other projects and not realized that it would later be an issue.

**Comment by hamishwillee** [comment]
> Would it be good practice to move the development db url to a .env file during production? This may require some brief instruction on installing the dotenv package and properly formatting env variables.

Please answer questions here: https://github.com/mdn/content/pull/26884#issuecomment-1556432931

It is important to hide credentials, in particular on production as once you can access that database you can do anything with any user data you are passed. But IMO it doesn't matter how you do it - I used an environment variable because there is no way for someone to access the interface unless they already have the password. 
I don't see any benefit in the .env file approach - you still have to protect and deploy that file somehow, and whether that's a good thing to do probably depends on the service you are using.

So there is benefit in stating in deployment that 
- the reason we're doing this is to protect credentials.
- There is benefit in stating that in some setups using .env files that are not in public repos. But unless you can work out how to deploy these to our service in a way that doesn't complicate this tutorial we might as well just mention that it can be done and avoid the detail.
- Here we can also mention we're not so worried about the development keys being leaked because someone might trash our server, but we can always restore it. No data or trust is lost. I guess they might use up some of our credit storing something we don't want too. Again, we can point out risk, but we don't have to solve the problem here.

If .env files were the defacto standard and safest way to share private keys I'd be all for it; but they are just another alternative. Key point is to let people know what they have to worry about and provide one good way. The key we set is the right way for this tutorial.

**Comment by hamishwillee** [comment]
Replaced by https://github.com/mdn/content/pull/26977  for reasons given in https://github.com/mdn/content/pull/26884#issuecomment-1563760710

Closing. Thanks very much!
