### ISSUE TITLE
Why animatable CSS properties reference was removed?

### ISSUE THREAD

**Issue by Vallek** [mdn/content#27042]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_animated_properties

### What specific section or headline is this issue about?

Animatable CSS properties reference

### What information was incorrect, unhelpful, or incomplete?

This page contained full list (reference) of animatable CSS properties. Which was obviously helpful. It's gone now. 

### What did you expect to see?

Full list of animatable CSS properties

### Do you have any supporting links, references, or citations?

You can still see it in [french version](https://developer.mozilla.org/fr/docs/Web/CSS/CSS_animated_properties) for example. And in [archive](https://web.archive.org/web/20230131022559/https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_animated_properties).

### Do you have anything more you want to share?
Please bring it back.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/css_animated_properties`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_animated_properties
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_animated_properties/index.md
* Last commit: https://github.com/mdn/content/commit/c9cc38c3c3c342e2e952c1acd57f55e104c5bb06
* Document last modified: 2023-05-18T13:31:57.000Z

</details>

**Comment by yarusome** [comment]
I made #26364 and the reasons for the revamp are:

  1. The [Web Animations](https://drafts.csswg.org/web-animations-1/#animating-properties) spec explicitly mentions that:

     > Unless otherwise specified, all CSS properties are ***animatable***.

     Thus exceptions are far less than the normal ones. This means even if the catalog were to be kept, it would make more sense to document the exceptions instead.

  2. Given that there're more and more new properties invented constantly, it's quite difficult to maintain the accuracy of the list.
  3. The original list only differentiated animatable and non-animatable properties, without any useful descriptions on each animation type.

If you find the list useful, could you elaborate why there's a need in the first place to see the complete list of animatable properties?

**Comment by Vallek** [comment]
Thanks for a quick answer!

This makes sense. Then I think there at least should be the list of exceptions.

The list was useful for a quick check if I'm trying to animate something that's not animatable) I know you can check property page, but this could be more convenient for multiple properties. And also for education (i gave this link to my students).

I also don't know how MDN is build but maybe you can just pick up properties with right animation type and put them on this page?

**Comment by Josh-Cena** [comment]
> I also don't know how MDN is build but maybe you can just pick up properties with right animation type and put them on this page?

We used to do that, but any kind of programmatic text generation requires a macro and we are generally moving away from macros. I personally don't see how we can achieve this without macros, so we are just refactoring our content to get around the limitation.

@yarusome Do you have plans on addressing this? The point about educational value seems reasonable. A list of exceptions should work.

**Comment by yarusome** [comment]
@Josh-Cena I can make a PR to list non-animatable properties on that page, but it somewhat contradicts one of the original goals, i.e. eliminate the need to maintain a list all along. :thinking:

Other question before opening a PR:

  - I'd like to only list specced properties since non-specced ones are hard to verify and update their statuses.
  - @Vallek Do you want to check for non-animatable properties or [discretely-animatable](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_animated_properties#discrete) ones? The former group only contains a few properties such as `animation-*` and `transition-*`, which can be mentioned as a note on that page instead. (I want to make sure if we're talking about the same concept.)

**Comment by Vallek** [comment]
@Josh-Cena 
> we are generally moving away from macros

Can I ask  why? Just out of curiosity)

@yarusome
>Do you want to check for non-animatable properties or [discretely-animatable](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_animated_properties#discrete) ones?

You know thinking about this now: my personal case was to check if property/properties (it could be any) is animatable. I just preferred one page list. So I'm not even sure if I would use non-animatable properties list. I guess it will be easier now to just check on each property page instead. 

But that's just me. I'm not sure what would be better universal solution (outside of initial one page).

**Comment by Josh-Cena** [comment]
> Can I ask why? Just out of curiosity)

I dunno; I wasn't the one making the decision. My guesses are:

1. Some macros' implementations are very complicated and negatively impact build performance.
2. Macros aren't supported by other Markdown renderers and don't work for every contributing workflow (e.g. if you are editing through the GitHub interface).
3. Macros are maintained with the platform (Yari) instead of the content, so updates to the content may require another commit to update the macro.

I'll leave it to you folks to decide what we should do. My personal take is that an overview of some sort is valuable but not necessary, and if @Vallek doesn't feel strongly any more, we can close it until someone else asks for it.

**Comment by Vallek** [comment]
>My personal take is that an overview of some sort is valuable but not necessary

Yeah I think I agree. Would be nice to have it, but as longs as you can just check each page it's not crucial.

**Comment by Josh-Cena** [comment]
Sure, let's close this for now.

**Comment by yarusome** [comment]
@Vallek FWIW, latest statuses can be extracted from [@webref/css](https://www.npmjs.com/package/@webref/css).

**Comment by Vallek** [comment]
> FWIW, latest statuses can be extracted from [@webref/css](https://www.npmjs.com/package/@webref/css).

@yarusome Decided to try it out) If it's not too much to ask could you help a little with that? 

I manage to get properties from specific spec json (like 'https://w3c.github.io/webref/ed/css/css-overflow.json'). Is there a combined one for all css properties? Or do I have to go through each of them?

**Comment by Vallek** [comment]
Ok, so I made a page with lists of animatable and not animatable CSS properties. Here it is: [vallek.github.io/animatable-css/](https://vallek.github.io/animatable-css/)

It updates once in a day and generates static html so minimum strain on api or client)
