### ISSUE TITLE
Section called "Specifications" displays code, instead of intended text.

### ISSUE THREAD

**Issue by OnkarHonge** [mdn/content#27085]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_box_model/Introduction_to_the_CSS_box_model

### What specific section or headline is this issue about?

The content under section called "Specifications"

### What information was incorrect, unhelpful, or incomplete?

Seems like a JS object name is being printed on the page: {{Specifications}}

### What did you expect to see?

Links to the corresponding W3C or other specifications.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/css_box_model/introduction_to_the_css_box_model`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_box_model/Introduction_to_the_CSS_box_model
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_box_model/introduction_to_the_css_box_model/index.md
* Last commit: https://github.com/mdn/content/commit/883b021c97375f872d0702f0d0747b1373155cef
* Document last modified: 2023-05-24T20:30:20.000Z

</details>

**Comment by Josh-Cena** [comment]
This page doesn't have browser-compat metadata and probably shouldn't have one. I think we can safely remove this section.

**Comment by 21553066** [comment]
Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

________________________________
De: Omya ***@***.***>
Enviado: Wednesday, May 31, 2023 9:18:42 PM
Para: mdn/content ***@***.***>
Cc: Subscribed ***@***.***>
Assunto: [mdn/content] Section called "Specifications" displays code, instead of intended text. (Issue #27085)


MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_box_model/Introduction_to_the_CSS_box_model

What specific section or headline is this issue about?

The content under section called "Specifications"

What information was incorrect, unhelpful, or incomplete?

Seems like a JS object name is being printed on the page: {{Specifications}}

What did you expect to see?

Links to the corresponding W3C or other specifications.

Do you have any supporting links, references, or citations?

No response

Do you have anything more you want to share?

No response

MDN metadata
Page report details

  *   Folder: en-us/web/css/css_box_model/introduction_to_the_css_box_model
  *   MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_box_model/Introduction_to_the_CSS_box_model
  *   GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_box_model/introduction_to_the_css_box_model/index.md
  *   Last commit: 883b021<https://github.com/mdn/content/commit/883b021c97375f872d0702f0d0747b1373155cef>
  *   Document last modified: 2023-05-24T20:30:20.000Z

**Comment by hamishwillee** [comment]
Thanks. Section will be removed by https://github.com/mdn/content/pull/27147
