### ISSUE TITLE
no mention what the default is for ShadowRoot mode

### ISSUE THREAD

**Issue by Zectbumo** [mdn/content#27110]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Element/attachShadow

### What specific section or headline is this issue about?

#parameters

### What information was incorrect, unhelpful, or incomplete?

what is the default if no mode is specified? it is not mentioned in this document
https://developer.mozilla.org/en-US/docs/Web/API/Element/attachShadow
nor this document
https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot/mode

### What did you expect to see?

what mode defaults to, open or closed or ??

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/element/attachshadow`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/attachShadow
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/attachshadow/index.md
* Last commit: https://github.com/mdn/content/commit/bbf7f25f9cf95fb154e2740a9fdc9c02818981bf
* Document last modified: 2023-04-07T05:55:26.000Z

</details>

**Comment by Zectbumo** [comment]
sorry, I now see that some "options" are labeled "optional". So, I have an issue with this because "options" means... optional. So labeling the options as optional is redundant and not labeling options meaning required is the opposite of great. It would better to label the required-options (an oxymoron) as "required" because it would be better to flag the oxymoronic options than to redundantly point out optional options.

**Comment by wbamberg** [comment]
I don't think we will invert `optional` for arguments (or parts of arguments) but if it helps we could rename `options` to `init` here (which is what the spec calls it).

**Comment by Josh-Cena** [comment]
It would be useful to point out that `mode` is required if it is, but I don't think "required option" is oxymoronic. An "options bag" in JS API design merely means an object where each key corresponds to one configuration, as opposed to accepting multiple parameters.

@wbamberg I think we are generally avoiding the name `init` because it sounds rather opaque (I still don't know what it means in this context).

**Comment by Josh-Cena** [comment]
See for example: https://github.com/mdn/content/pull/18330

> If we additionally point out that `mode` is required, that is going to add confusion for all the other places we only omit `optional`.

It does sound unusual when an API accepts an options bag but it contains mandatory fields. Usually, mandatory fields are passed as separate arguments, for example `fetch(url, options)`. It can be a single sentence like "omitting `mode` or `options` causes a `TypeError`".

**Comment by Zectbumo** [comment]
@wbamberg 
> but if it helps we could rename options to init here (which is what the spec calls it).

Okay, that makes more sense that the spec uses `init` and not `optional`. I think the mdn docs should do the same.

> I also had never thought of options properties as being inherently optional

If you search the spec you previously linked you will find several occurrences of `optional` sugar coating the argument named `options` such as:
```
optional GetRootNodeOptions options = {}
```
also, you will see that `options` will always default to an empty object. So, to name the `init` argument `options` was a misleading mistake.

@Josh-Cena 
> It does sound unusual when an API accepts an options bag but it contains mandatory fields. Usually, mandatory fields are passed as separate arguments

Well, it turns out it's not an options bag. It's an initializing object. I too agree that mandatory fields are typically passed as arguments. It appears some anti-positional-anti-unnamed argument spec writer held the reigns for one day.

**Comment by wbamberg** [comment]
We've discussed this a bit internally, and I'm closing this issue, because the page is correct per our current conventions.

Our current practice is to document when parameters are optional, making it implicit that when this is omitted, they are required (which is the inverse of IDL).

I think actually it would be better for us always to indicate `required` or `optional`, and have started a discussion to see if there is appetite for this: https://github.com/orgs/mdn/discussions/452.

However, I'm against us adding "required" on an ad hoc basis, because it is confusing: if we sometimes mark parameter required and sometimes say nothing, how are people expected to understand this?

**Comment by wbamberg** [comment]
> We've discussed this a bit internally, and I'm closing this issue, because the page is correct per our current conventions.
> 
> Our current practice is to document when parameters are optional, making it implicit that when this is omitted, they are required (which is the inverse of IDL).
> 
> I think actually it would be better for us always to indicate `required` or `optional`, and have started a discussion to see if there is appetite for this: https://github.com/orgs/mdn/discussions/452.
> 
> However, I'm against us adding `"required"` on an ad hoc basis, because it is confusing: if we sometimes mark required parameters `"required"` and sometimes say nothing, how are people expected to understand this?
