### ISSUE TITLE
Throwing a string or number (instead of an Error) is generally problematic

### ISSUE THREAD

**Issue by btangmu** [mdn/content#27151]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/throw

### What specific section or headline is this issue about?

Description

### What information was incorrect, unhelpful, or incomplete?

throw "Error2"; // generates an exception with a string value
throw 42; // generates an exception with the value 42
throw true; // generates an exception with the value true
throw new Error("Required"); // generates an error object with the message of Required

### What did you expect to see?

throw new Error("Required"); // generates an error object with the message of Required

### Do you have any supporting links, references, or citations?

https://stackoverflow.com/questions/11502052/throwing-strings-instead-of-errors

### Do you have anything more you want to share?

The current documentation conveys the false impression that throw("message") might be a valid shorthand for throw new Error("message"). While it's not technically an error, it's extremely unhelpful, misleading, and unconventional. Conventionally catch statements expect e.message to be defined.

If you're going to present examples of the alternatives with string/number/boolean instead of Error, don't put them before the conventional example with Error, and do add a cautionary note that those examples are unconventional.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/statements/throw`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/throw
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/statements/throw/index.md
* Last commit: https://github.com/mdn/content/commit/0f3738f6b1ed1aa69395ff181207186e1ad9f4d8
* Document last modified: 2023-02-21T00:33:34.000Z

</details>

**Comment by hamishwillee** [comment]
@Josh-Cena I'm not sure about the solution, but I agree with the thinking here. Specifically this is "pure JavaScript" and therefore documents what you _can_ do. But in practice there are certain things that debugging code in browsers expect and "can do more with", such as the exception including name and message properties, and ideally stack

So rather than just having [Error](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error) in the see also, it might be worth stating explicitly here that the JavaScript error will generally throw errors of these types (link to error), web APIs might throw DomExcepions, and that while you can throw any kind of object or string, generally you will throw Error with a string, or some  object you have derived from error. 

I can do that if you think it is a good idea, or we can make as a "good first issue".

**Comment by Josh-Cena** [comment]
Sure, sounds good to me.

I will be doing this—there are several additions I want to do to this page anyway.
