### ISSUE TITLE
[HTML] Implement link rel="modulepreload"

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#27177]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1425310

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [x] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by hamishwillee** [comment]
@bsmth Do you want me to take this one? I am touching it already for the work on prefetch links.

FYI, note that there is already a doc for this here: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/modulepreload, but that it is insufficient because it doesn't make clear some of the nuances in https://html.spec.whatwg.org/multipage/links.html#link-type-modulepreload or related to the use of the `as` attribute at the same time in https://html.spec.whatwg.org/multipage/semantics.html#attr-link-as.

**Comment by bsmth** [comment]
Hi @hamishwillee - please go ahead, I'll assign it to you, thank you!

**Comment by hamishwillee** [comment]
Status

- [ ] BCD https://github.com/mdn/browser-compat-data/pull/20259
- [ ] Docs
- [ ] Release note
- [ ] dev-doc-complete
