### ISSUE TITLE
Web Component attributes and  attributeChangedCallback()

### ISSUE THREAD

**Issue by StephanLuis** [mdn/content#27236]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Web_components

### What specific section or headline is this issue about?

Life cycle callbacks

### What information was incorrect, unhelpful, or incomplete?

Shouldn't the text say that the method attributeChangedCallback() is called when an attribute is coded in html? For example in this fiddle (not mine) https://jsfiddle.net/czo1355c/ attributeChangedCallback() is called twice.

### What did you expect to see?

This method is triggered on setting the value of an attribute coded in HTML ex <bobs-control value='bob'></bobs-control>

### Do you have any supporting links, references, or citations?

https://stackoverflow.com/questions/41718254/why-is-attributechangedcallback-called-twice?rq=3 (and related questions)
https://jsfiddle.net/czo1355c/

### Do you have anything more you want to share?

In my opinion, these kinds of omissions have a real impact on speed of web development.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/web_components`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_components
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/web_components/index.md
* Last commit: https://github.com/mdn/content/commit/ffc61f406a5968f522df6ef9e4973fc17f981ea3
* Document last modified: 2023-04-24T05:43:06.000Z

</details>

**Comment by Josh-Cena** [comment]
What is the current text that you are proposing to modify and how is it incorrect?

**Comment by StephanLuis** [comment]
The text is incomplete, not incorrect.  

There is no reference to which of the **lifecycle** triggers the custom element methods.  Ex. no indication that attributes for custom elements **hard coded in html** are updated through `attributeChangedCallback()`  .  The method's name doesn't indicate that aspect of what it does either.

The[ page lifecycle callbacks](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements#using_the_lifecycle_callbacks)  page is lengthy and there are references to the attributeChangedCallback() but that too doesn't mention the initial setting of **attributes coded in HTML**.

I gave SO questions relating to the issue of clarity on this.  Coders of HTML aren't as concerned when the attributes are set but people writing custom elements are ... so I think that at least it should be mentioned on the custom elements page.

**Comment by wbamberg** [comment]
I wonder if it would be better to have a separate page on "Handling attribute changes" or something, that can talk in more depth about `attributeChangedCallback()`, including this issue, but also extracting part of https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements - mainly the example at https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements#lifecycle_callbacks, which although it says it is about "lifecycle callbacks", is mostly about attribute changes specifically.

As you say, this page is already pretty long and splitting it like this might make things more discoverable. See also https://github.com/mdn/content/issues/29448, which is asking for documentation of the form-related callbacks, which would also need to be quite extensive, and might also be well handled in a separate page rather than an extension to the "using custom elements" page.

**Comment by StephanLuis** [comment]
Super ! Much more clear.  Thanks.
