### ISSUE TITLE
window.open() has a partial list of features

### ISSUE THREAD

**Issue by rotu** [mdn/content#27357]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/open

### What specific section or headline is this issue about?

Parameters -> windowFeatures

### What information was incorrect, unhelpful, or incomplete?

The list of features that can be passed to `window.open` is incomplete. It currently includes popup, width, innerWidth, height, innerHeight, left, screenX, top, screenY, noopener, noreferrer.

### What did you expect to see?

It omits the features mentioned at the linked spec: location, toolbar, menubar, resizable, scrollbars, status.

### Do you have any supporting links, references, or citations?

https://html.spec.whatwg.org/multipage/nav-history-apis.html

### Do you have anything more you want to share?

It's not clear to me which of these features are respected and which are legacy and should not be used. If these are mostly disregarded and *only* affect whether the browser treats a window as a popup, it should say so.

Also, the page does not communicate that innerwidth, innerheight, screenx, screeny aliases that exist only for legacy purposes.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/window/open`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/open
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/open/index.md
* Last commit: https://github.com/mdn/content/commit/39bb7174af0862fe3ef557562e720b5943f2fc06
* Document last modified: 2023-05-26T20:53:23.000Z

</details>

**Comment by Anthony888889** [comment]
Can you help me recover information I need for tickets stocks, bonds, Robinhood, and wiki

**Comment by Anthony888889** [comment]
Find out winning tickets sweepstakes

**Comment by Anthony888889** [comment]
June 11. 2023. Ticket between. 3:00  3:30

**Comment by postmeback** [comment]
I would like to contribute here, provided I will be requiring guidance

**Comment by dscotese** [comment]
I reviewed this issue and see that some other changes might be useful.  The note under "popup" isn't strictly correct because adding the WindowFeature "status=true" opens a tab in Brave, even when menubar, location, and toolbar are added as features (and there is apparently no way to programmatically open a tab in Safari, which is the other browser I can use).  It requires some testing, but I believe the menubar, toolbar, and location features (parts of the UI the command used to allow you to control) are useless.  Brave follows the popup rule (If both location and toolbar are false, then it's a popup, and if either is true, and a bunch of other requirements, then it will be a tab), but only blocks the address bar (supposedly controlled by "location" feature) and the toolbar, if it is a popup window, regardless of the settings.  I think testing may show that at some point, most of the WindowFeatures not mentioned in the article stopped doing anything.
