### ISSUE TITLE
Inconsistent promise fulfillment order in populatedb.js script

### ISSUE THREAD

**Issue by CutlerSheridan** [mdn/content#27368]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose

### What specific section or headline is this issue about?

Testing — create some items

### What information was incorrect, unhelpful, or incomplete?

Users are told to run the pre-written js file populatedb.js to fill their database with sample books, authors, genres, and bookInstances.

These methods work like this:

```
async function createGenres() {
  console.log("Adding genres");
  await Promise.all([
    genreCreate("Fantasy"),
    genreCreate("Science Fiction"),
    genreCreate("French Poetry"),
  ]);
}

async function genreCreate(name) {
  const genre = new Genre({ name: name });
  await genre.save();
  genres.push(genre);
  console.log(`Added genre: ${name}`);
}
```

In addition to creating a new instance of the appropriate model, each `<model>Create()` method is also meant to push its newly-created model to a global array tracking all created instances of that model (e.g. the code above might result in `genres = [‘Fantasy’, ‘Science Fiction’, ‘French Poetry’]`).  These arrays are then referenced in fields of other model instance constructors (e.g. `createBooks()` calls `bookCreate('The Name of the Wind', authors[0], genres[0])`).

The problem is that the `create<model>()` methods all use `await Promise.all()` to create all desired instances of the appropriate model.  This is an issue as, given its asynchronous nature, `Promise.all()` does not guarantee the written order of instance creation methods will be the actual order in which the instances are created.

For example, after the above code is run, when `createBooks()` is called and attempts to create a fantasy `Book` by passing `genres[0]` to its constructor, `genres[0]` could actually refer to any of those three genres despite "fantasy" being the first one written in the code.

### What did you expect to see?

Given the importance the model instance arrays are populated in the order in which the instance creation methods are written, I would expect each `create<model>()` method, instead of using `await Promise.all()`, to simply call `await <model>Create()` however many times it is needed.

### Do you have any supporting links, references, or citations?

The script is linked on the MDN page, but here is the direct link to [the `populatedb.js` file](https://raw.githubusercontent.com/mdn/express-locallibrary-tutorial/main/populatedb.js).

### Do you have anything more you want to share?

I did my best to describe this issue concisely; please let me know if further clarification is needed.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/mongoose`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/mongoose/index.md
* Last commit: https://github.com/mdn/content/commit/b12def31533da2de2079296d67185d54371f93c9
* Document last modified: 2023-05-17T22:56:35.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks, but this is invalid.

All of the _independent_ parts are run asynchronously together only once their dependencies have already been created. So the genres and authors, which depend on nothing are created first. 
Then the books, are created together, but the genres and authors they depend on have already been created ... and so on.

Also,  this works, which is a pretty good but not absolute indication that it is correct :-).

**Comment by dscotese** [comment]
Please consider re-opening this issue because the code in populatedb.js does, in fact, imply that promise.all completes running the elements of its argument in order, and this is not the case.  They are run asynchronously.  As the creation of a genre includes saving it, which may take an unknown amount of time, the order of the genres in the genres array is not guaranteed.  I assume that @hamishwillee is correct that the code works, but it still misleads the astute reader regarding the indeterminate order of execution completion for the elements of an array passed to promise.all.

I propose to increase the educational value of populatedb.js and also resolve this issue by:
A) changing the note from "You don't need to know how populatedb.js works; it just adds sample data into the database." to "The code in populatedb.js may be useful in learning Javascript, but understanding it is not necessary for this tutorial."

B) Updating the code thus:
* adding one argument to the beginning of each create... function, "index", so that, for example, creategenres() would look like this:
```
async function createGenres() {
  console.log("Adding genres");
  await Promise.all([
    genreCreate(0,"Fantasy"),
    genreCreate(1,"Science Fiction"),
    genreCreate(2,"French Poetry"),
  ]);
}
```
* updating the ...create() functions to use `genres[index] = genre;` instead of `genres.push(genre)`.

Part of the issue here, for me at least, is that the populatedb.js code as it is does not honor the marriage of intent to code construction.  The code uses the indices of the arrays, but it also assumes them rather than specifying them.  If you're going to use genres[0], then genres[0] should be set somewhere.  That genres[0] means the Fantasy genre requires ignorance of the fact that promise.all's arguments can be completed out of order, so it reinforces that misunderstanding.  The note does mitigate that problem, but we prefer education over avoidance, right?

**Comment by hamishwillee** [comment]
Thanks @dscotese.

The order of creation doesn't matter because the file is not considered part of the tutorial. I really don't care if it selects a different genre in one iteration than another, since that doesn't affect anything that I intended to be part of the tutorial.

That said, if we can make it better then I'm all for it. Are you interested in making the change? If so I am happy to reopen the issue.

**Comment by dscotese** [comment]
I was going to make the change, but the raw.githubusercontent.com file is not in github in a way I know how to edit it as part of the repo, and I don't know where to add the file to the repo.  If you test with https://gist.github.com/dscotese/47e9ad49233f09ea30ab48efc4b6cea5 and it works well, let me know and I will update the index file to point to that version instead of the one you made.

**Comment by hamishwillee** [comment]
The file is here: https://github.com/mdn/express-locallibrary-tutorial/blob/main/populatedb.js in the demo project.

The raw.prefix gets you a downloadable file.

**Comment by hamishwillee** [comment]
FYI @dscotese Made the changes discussed above in https://github.com/mdn/express-locallibrary-tutorial/pull/195

**Comment by CutlerSheridan** [comment]
Oh awesome, thanks @dscotese for making the changes and thanks @hamishwillee for the update!
