### ISSUE TITLE
Javascript switch statement skill test unreasonable?

### ISSUE THREAD

**Issue by JamesC01** [mdn/content#27511]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Test_your_skills:_Conditionals

### What specific section or headline is this issue about?

Conditionals 3

### What information was incorrect, unhelpful, or incomplete?

I'm not sure if I'm going crazy or not, but the conditionals 3 task asks you to take this code:

```
  if (score >= 0 && score <= 19) {
    response = "That was a terrible score — total fail!";
  } else if (score >= 20 && score <= 39) {
    response = "You know some things, but it\'s a pretty bad score. Needs improvement.";
  } else if (score >= 40 && score <= 69) {
    response = "You did a passable job, not bad!";
  } else if (score >= 70 && score <= 89) {
    response = "That\'s a great score, you really know your stuff.";
  } else if (score >= 90 && score <= 100) {
    response = "What an amazing score! Did you cheat? Are you for real?";
  } else {
    response = "This is not possible, an error has occurred.";
  }
```

And turn in into a switch statement. I'm not sure if I'm mis-interpreting it or not, but that sounds absurd. Does it expect something like this?:

```
switch (score) {
  case 0:
  case 1:
  case 2:
  case 3:
  case 4:
  ...
}
```

I read through the switch documentation, and figured out you could do something like this:

```
switch (true) {
    case score >= 0 && score <= 19:
      response = "That was a terrible score — total fail!";
      break;
    case score >= 20 && score <= 39:
      response = "You know some things, but it\'s a pretty bad score. Needs improvement.";
      break;
    case score >= 40 && score <= 69:
      response = "You did a passable job, not bad!";
      break;
    case score >= 70 && score <= 89:
    response = "That\'s a great score, you really know your stuff.";
      break;
    case score >= 90 && score <= 100:
      response = "What an amazing score! Did you cheat? Are you for real?";
      break;
    default:
      response = "This is not possible, an error has occurred.";
  }
```

But there is no mention of that at all in the [Conditionals Article](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/conditionals), and as far as I know, I've never seen this style of switch statement being used in any other languages. It feels like a hack and seems less readable than the "if" counterpart.

### What did you expect to see?

A normal task that uses things you read about in the article.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/building_blocks/test_your_skills_colon__conditionals`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Test_your_skills:_Conditionals
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/building_blocks/test_your_skills_colon__conditionals/index.md
* Last commit: https://github.com/mdn/content/commit/ea93a07864f36d64ad68f7c57c5d54a99111b4c7
* Document last modified: 2023-03-29T03:27:54.000Z

</details>

**Comment by wbamberg** [comment]
Yes, that is what it expects: https://github.com/mdn/learning-area/blob/main/javascript/building-blocks/tasks/conditionals/marking.md. Personally, I agree with you, this seems a bit niche. I also wonder why the answer for (2) isn't:

```js
  if (score < 0 || score > 100) {
    response = 'This is not possible, an error has occurred.';
  } else if(score < 20) {
    response = 'That was a terrible score — total fail!';
  } else if(score < 40) {
    response = 'You know some things, but it\'s a pretty bad score. Needs improvement.';
  } else if(score < 70) {
    response = 'You did a passable job, not bad!';
  } else if(score < 90) {
    response = 'That\'s a great score, you really know your stuff.';
  } else {
    response = 'What an amazing score! Did you cheat? Are you for real?';
  }
```

...since the bottom end is covered by the previous block, along with the `else` in this condition.

**Comment by 21553066** [comment]
Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

________________________________
De: wbamberg ***@***.***>
Enviado: Friday, June 23, 2023 5:18:29 PM
Para: mdn/content ***@***.***>
Cc: Subscribed ***@***.***>
Assunto: Re: [mdn/content] Javascript switch statement skill test unreasonable? (Issue #27511)


Yes, that is what it expects: https://github.com/mdn/learning-area/blob/main/javascript/building-blocks/tasks/conditionals/marking.md. Personally, I agree with you, this seems a bit niche. I also wonder why the answer for (2) isn't:

  if (score < 0 || score > 100) {
    response = 'This is not possible, an error has occurred.';
  } else if(score < 20) {
    response = 'That was a terrible score — total fail!';
  } else if(score < 40) {
    response = 'You know some things, but it\'s a pretty bad score. Needs improvement.';
  } else if(score < 70) {
    response = 'You did a passable job, not bad!';
  } else if(score < 90) {
    response = 'That\'s a great score, you really know your stuff.';
  } else {
    response = 'What an amazing score! Did you cheat? Are you for real?';
  }

...since the bottom end is covered by the previous block, along with the else in this condition.

**Comment by 21553066** [comment]
Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: ***@***.***>
Enviado:sexta-feira, 23 de junho de 2023 17:18
Para: ***@***.***>
***@***.***>
Assunto: Re: [mdn/content] Javascript switch statement skill test unreasonable? (Issue #27511)


Yes, that is what it expects: https://github.com/mdn/learning-area/blob/main/javascript/building-blocks/tasks/conditionals/marking.md. Personally, I agree with you, this seems a bit niche. I also wonder why the answer for (2) isn't:

  if (score < 0 || score > 100) {

    response = 'This is not possible, an error has occurred.';

  } else if(score < 20) {

    response = 'That was a terrible score — total fail!';

  } else if(score < 40) {

    response = 'You know some things, but it\'s a pretty bad score. Needs improvement.';

  } else if(score < 70) {

    response = 'You did a passable job, not bad!';

  } else if(score < 90) {

    response = 'That\'s a great score, you really know your stuff.';

  } else {

    response = 'What an amazing score! Did you cheat? Are you for real?';

  }

...since the bottom end is covered by the previous block, along with the else in this condition.

**Comment by Josh-Cena** [comment]
> I also wonder why the answer for (2) isn't:

While I agree you could reduce each conditional to one comparison, I think the best pattern is still to put the error condition last, after all valid cases have been narrowed out.

I don't know why this tutorial recommends the `switch (true)` pattern—I always treated it as a brain teaser.
