### ISSUE TITLE
Add page-types for the Learn Area

### ISSUE THREAD

**Issue by teoli2003** [mdn/content#27620]
As part of openwebdocs/project#91, we want to adde page-types to the Learn Area.

I propose to add 6 different page types:

Page type | meaning
-- | --
learn-topic | Overview of a section, or a topic (that is, a collection of modules)
learn-module | Overview of a module (with prerequisites, list of guides, …)
learn-module-chapter | A part of a module (explanations) (Such a guide has a prerequisite table and an overview table)
learn-module-assessment | The assignment at the end of a module or a guide
learn-faq| Specific page about a question

The complete list of the 350+ pages of the LA and the proposed page-view attribution is [here](https://docs.google.com/spreadsheets/d/1NWk8rEmVgNrLLn4QVMwgQYjqZHaol9dx6EqPAc9AHbA/edit#gid=0).

cc/ @wbamberg. What do you think?

**Comment by wbamberg** [comment]
Thanks for this, @teoli2003 ! It looks great, but I had a few suggestions.

> learn-section-overview

In the existing docs, these tend to be called "topics", so perhaps `learn-topic-overview`? Or even just `learn-topic`?

> learn-module-overview

Similarly perhaps just `learn-module`??

> learn-module-guide

Perhaps `learn-module-chapter` expresses the fact that this is a piece of a module and that the pieces are ordered?

> learn-module-assessment

I like this but in the sheet they are called `learn-module-assignment` which I like less :).

> learn-faq-landing

We haven't generally "subtyped" landing pages like this. Put another way, why does this get its own type and, say, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects does not?

> learn-faq-question

Since "q" in "faq" is question this is like `learn-frequently-asked-question-question` which bothers me. Just `learn-faq` maybe?

**Comment by teoli2003** [comment]
They all sound like good suggestions to me. I will update the proposal and prepare a PR. More feedback is of course welcomed (by anybody).
