### ISSUE TITLE
Confusion between html and xml syntax in documentation

### ISSUE THREAD

**Issue by Judekeyser** [mdn/content#27661]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/HTML_basics

### What specific section or headline is this issue about?

all document

### What information was incorrect, unhelpful, or incomplete?

Most examples are phrased with XML syntax for HTML5, but do not contain XML preamble. In addition, nothing is made to warn the reader about the requirement to serve those documents as XML.

### What did you expect to see?

Could examples be phrased using html syntax, to avoid ambiguity? Or could there be a section that explains that for self-closing elements (void elements), the two syntaxes are possible?

In pages like:
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled
for example, the two syntaxes coexist, which might give the feeling that something is wrong.

### Do you have any supporting links, references, or citations?

> The other syntax that can be used for HTML is XML. This syntax is compatible with XHTML1 documents and implementations. Documents using this syntax need to be served with an XML media type (such as application/xhtml+xml or application/xml) and elements need to be put in the http://www.w3.org/1999/xhtml namespace following the rules set forth by the XML specifications. [[XML]](https://www.w3.org/TR/html5-diff/#refsXML) [[XMLNS]](https://www.w3.org/TR/html5-diff/#refsXMLNS)

Source: https://www.w3.org/TR/html5-diff/#syntax

**Comment by yarusome** [comment]
About using XML syntax for HTML codes:

This is because [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1826063) and [MDN](https://github.com/mdn/content/pull/20674) now officially endorse the use of [Prettier](https://prettier.io) to format every type of codes, including HTML, and Prettier keeps refusing using the HTML-native syntax for HTML (see prettier/prettier#5246) :sweat_smile: (I guess they don't bother to implement namespace-scoped linting.)

About coexistence of both syntaxes:

If you're referring to the [Try it](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled#try_it) section using no trailing slashes for void elements, it's because the code there lives in [mdn/interactive-examples](https://github.com/mdn/interactive-examples/blob/main/live-examples/html-examples/form-attributes/attribute-disabled.html), which hasn't been manipulated by Prettier yet.

**Comment by Josh-Cena** [comment]
Right, code here is valid HTML. Trailing slashes don't make them XML. We don't plan to deviate from Prettier style here. See https://github.com/orgs/mdn/discussions/242

**Comment by Judekeyser** [comment]
@Josh-Cena I understand. Couldnt there at least be a section that stresses the two variations and refers to the "void element" page?

How is a beginner supposed to get in touch with the two alternatives?
