### ISSUE TITLE
Show version of spec that introduces feature

### ISSUE THREAD

**Issue by mehulkar** [mdn/content#2787]
It would be nice for MDN not just to link to the spec for a JS feature, but to note which version of the spec it was approved in. The reason is that sometimes tools will say that they are compatible with a spec version, but I can't tell what features that includes. 

Real world example:

SonarQube's JS plugin says it supports ES 2019: https://github.com/SonarSource/SonarJS/tree/6.5.0.13383#features. But it's failing to parse optional chaining syntax. I go to MDN to see if I can figure out if optional chaining was from ES2018 or 2019 or 2020: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining, but don't see anything.

**Comment by jpmedley** [comment]
A tool like SonarJS has to account for what's supported in browsers. The spec that it was defined in seems beside the point. Since this feature is [supported in all the majors](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#browser_compatibility) and SonarJS seems to have [added support](https://github.com/SonarSource/SonarJS/pull/2022), assuming I interpreted that correctly, I think what you're looking at is a regression, not lack of support. Have you filed an issue with SonarJS?
