### ISSUE TITLE
Suggestions to improve the Top Layer page: add examples, specify browser support, and clarify information

### ISSUE THREAD

**Issue by DanKaplanSES** [mdn/content#27914]
### MDN URL

https://developer.mozilla.org/en-US/docs/Glossary/Top_layer

### What specific section or headline is this issue about?

Top layer

### What information was incorrect, unhelpful, or incomplete?

1. In Firefox, I couldn't find the top layer shown in the screenshot. I think this is because Firefox developer tools don't show it, only Chrome developer tools? Or, maybe, `#top-layer` hasn't been implemented in Firefox yet?
2. Can you interact with the top layer, or is it purely conceptual? Can you refer to it with a CSS selector (e.g., `#top-layer`) like the screenshot implies? Is there a way to, for example, hide all the elements within the top layer with CSS? With JavaScript?
4. The "See also" section doesn't link to the [dialog element page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog).
5. This page says, "The top layer is a specific layer in the [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_positioned_layout/Understanding_z-index/Stacking_context)", but I don't see it mentioned on the stacking context page, not even in the stacking context "See also" section. 

For context, I'm experimenting with `dialog.showModal()`. 

### What did you expect to see?

1. IMHO, the page should explicitly state that the top layer can't be seen in Firefox developer tools. If this is due to Firefox not supporting the feature/concept, a browser support table might be a good way to illustrate this information.
2. I think the article could be expanded to answer these questions, ideally with examples. If `#top-layer` is purely conceptual, maybe that could be explicitly mentioned.
3. Link to the dialog element page in the "See also."
4. I suppose I expected to see the top layer mentioned in lesser detail on the [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_positioned_layout/Understanding_z-index/Stacking_context) page--a single sentence may suffice. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/glossary/top_layer`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Top_layer
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/top_layer/index.md
* Last commit: https://github.com/mdn/content/commit/ada5fa5ef15eadd44b549ecf906423b4a2092f34
* Document last modified: 2023-06-08T13:19:16.000Z

</details>

**Comment by wbamberg** [comment]
Thank you for filing, @DanKaplanSES !

Dragging in @chrisdavidmills , who wrote this page, and who also wrote the Popover API docs, which is where I came across this thing.

I'm not sure of the answers here, but:

> Can you interact with the top layer, or is it purely conceptual? Can you refer to it with a CSS selector (e.g., #top-layer) like the screenshot implies? Is there a way to, for example, hide all the elements within the top layer with CSS? With JavaScript?

I believe it is just conceptual: there's certainly nothing in https://drafts.csswg.org/css-position-4/#document-top-layer that suggests web developers can interact with it, and it even says: _"The [top layer](https://drafts.csswg.org/css-position-4/#document-top-layer) is managed entirely by the [user agent](https://infra.spec.whatwg.org/#user-agent); it cannot be directly manipulated by authors."_

> In Firefox, I couldn't find the top layer shown in the screenshot. I think this is because Firefox developer tools don't show it, only Chrome developer tools? Or, maybe, #top-layer hasn't been implemented in Firefox yet?

Most likely, Firefox devtools just don't implement this yet. Since Firefox implements `<dialog>`, for instance, I expect it does implement top layer.

> IMHO, the page should explicitly state that the top layer can't be seen in Firefox developer tools. If this is due to Firefox not supporting the feature/concept, a browser support table might be a good way to illustrate this information.

I don't think we should document any browser devtools features in these docs. I wonder even if the Chrome screenshot is potentially misleading here.

Also I'm not sure this falls in the domain of browser compat: browser compat describes features, and top layer as we said seems more like a concept underpinning some concrete features (which do get compat tables).

> I think the article could be expanded to answer these questions, ideally with examples. If #top-layer is purely conceptual, maybe that could be explicitly mentioned.

Probably, yes. But we have a bigger problem here on MDN, in that we have no real place to talk about conceptual things like this. Glossary articles are supposed to be short, they're not guide pages. But unless/until we could fix this in the information architecture, we should probably expand this page a bit. We could certainly say that it is only conceptual and can't be directly interacted with.

> Link to the dialog element page in the "See also."

+1

> I suppose I expected to see the top layer mentioned in lesser detail on the [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_positioned_layout/Understanding_z-index/Stacking_context) page--a single sentence may suffice.

Probably, yes.

**Comment by chrisdavidmills** [comment]
+1, thanks for filing, @DanKaplanSES. I created this page pretty quickly as I wanted somewhere to point to that defined the top-layer term, but I appreciate that it could've been better.

I'll create a PR to update it now.
