### ISSUE TITLE
Issue with "Django Tutorial Part 8: User authentication and pe…": …

### ISSUE THREAD

**Issue by ChrisClaude** [mdn/content#283]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Authentication

#### Local Library App Templates Not Found
I was going through the tutorial from the beginning to this current point. I noticed that you didn't guide us to add 'locallibrary' under INSTALLED_APPS. Also, giving guidance that 'locallibrary' should come before the 'django.contrib.admin' app can help avoid this confusion of why we still see the admin log out page after creating the logged_out.html page under project_root/locallibrary/registration/. I spent a while figuring out why my templates were not found and why the logout link kept redirecting to the admin logout page.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/django/authentication`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Authentication
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/server-side/django/authentication/index.html
* Report started: 2020-12-16T09:44:57.572Z

</details>

**Comment by hamishwillee** [comment]
@ChClaude Thanks for posting. However I haven't added the locallibrary because you don't need to. 

Locallibrary is the **project** that is loaded. It _contains_ the settings including `INSTALLED_APPS` so it wouldn't make sense to add itself. 

However we do need to add the catalog application, and that is done in https://github.com/mdn/django-locallibrary-tutorial/blob/master/locallibrary/settings.py#L44 (covered in the doc https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/skeleton_website)

> Also, giving guidance that 'locallibrary' should come before the 'django.contrib.admin' app can help avoid this confusion of why we still see the admin log out page after creating the logged_out.html page under project_root/locallibrary/registration/. I spent a while figuring out why my templates were not found and why the logout link kept redirecting to the admin logout page.

So given that you don't need to add locallibrary, this suggestion is invalid. 

I'll leave this open for a day or two in case you wish to discuss further.

**Comment by ChClaude** [comment]
I understand that the locallibrary is the project that contains the INSTALLED_APPS. But the thing is the templates for registration are placed in that directory which is locallibrary/templates/registration. In my case, Django could not find those templates unless I specified the locallibrary app itself in the INSTALLED_APPS

**Comment by hamishwillee** [comment]
@ChrisClaude That works because in the [settings](https://github.com/mdn/django-locallibrary-tutorial/blob/master/locallibrary/settings.py#L64) we have:
```
TEMPLATES = [
    {
        ...
        'APP_DIRS': True,
```
As documented in the tutorial the APP_DIRS ensures that django looks for templates subdirectory in your applications. So adding the locallibrary as an application simply makes that directory now something that gets searched.

But I don't think that this is particularly intuitive. To solve this problem I explicitly added the directory templates in the root. This is where I put the templates:
```
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
```
Which you can see here: https://github.com/mdn/django-locallibrary-tutorial/tree/master/templates/registration


This approach is what is documented https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Authentication#Template_directory - and if you try out https://github.com/mdn/django-locallibrary-tutorial/ you will see it works.

Hope that helps. I'm closing this.
