### ISSUE TITLE
Show Spec Feature List

### ISSUE THREAD

**Issue by say25** [mdn/content#2831]
I would love a way to browse MDN by features added in ESXX.

This way I can see what new features were launched in each different version of ES.

**Comment by acdvs** [comment]
This is something I've wanted for a very long time as well. Surprisingly, none of the top JS reference resources out there have this info, so looking it up has always been extremely tedious in my opinion. I honestly don't know how we've come this far without this feature.

**Comment by sideshowbarker** [comment]
I think the feature list proposed in the issue description could be created as a separate community project of some kind — in its own repo — that is, a project driven by the people who really want this.

As far as I can see, there’s nothing preventing that from happen. Certainly the fact that MDN lacks this doesn’t prevent it from being created and made available somewhere else.

Regardless, the necessary info this would need to be built on should rightly exist as data in some specific form — as JSON data or whatever. And since we don’t maintain JSON data like that in MDN itself, it would need to be in some other repo anyway.

So maybe the best next step here would be for somebody who wants this to take the initiative on setting up a repo for the data, and building a community of people around it who can work together to begin populating that repo with the necessary data.

Otherwise, short of something like that happening, I suspect this issue is just going to hang around forever as a perpetually-open issue in this issue tracker.

**Comment by acdvs** [comment]
@sideshowbarker I think you're missing the point of the discussion. There are already several good resources for this outside of MDN (e.g., https://node.green), so no need to start yet another project for this. The point is that the info would be far more **discoverable** and **accessible** via MDN. What features are available in an ES version is one of the most basic pieces of info a JS developer could need. This info _absolutely_ needs to live on MDN if it's going to call itself a top JS resource.

**Comment by sideshowbarker** [comment]
> What features are available in an ES version is one of the most basic pieces of info a JS developer could need. This info _absolutely_ needs to live on MDN if it's going to call itself a top JS resource.

OK, I hear you. So it would be great if you could make time to put together a concrete proposal for how to make that happen — a plan that includes things such as a description of what specific tasks it would require people to do, and some ideas about how to recruit people to work on those tasks together, and some maybe mockups of what you imagine the presentation of the information in an MDN article would actually look like, and so on.

**Comment by acdvs** [comment]
I simply don't have time to build an entire change proposal. Someone needs to look into this though. As I said before, "what features are available in an ES version is one of the most basic pieces of info a JS developer could need." MDN ***needs*** this feature. There's simply no way to argue that it doesn't.

**Comment by teoli2003** [comment]
The main disagreement here is on this:

> "what features are available in an ES version is one of the most basic pieces of info a JS developer could need."

MDN has taken the stance that developer needs to know if they can use a feature or not depending on its availability in the browsers they want to support. For this, they need the info that is in the mdn/browser-compat-data repository (and stored in the _Browser compatibility_ section).

There may be a good reason why the actual ES version is needed, but this has not yet been demonstrated.

Bringing such a demonstration may help change the position of MDN towards what you want. Ideally, concrete use cases should be surfaced, especially as this would be a significant amount of work to create, and maintain. It will be important to show why the current bcd information doesn't solve the problem.

I think we should close this issue in a few days. If such use cases would be surfaced afterward, we can reopen the issue and revisit this decision.

**Comment by Josh-Cena** [comment]
https://github.com/mdn/content/issues/18631 looks like less infrastructure work, so we may discuss that instead (although that one shall be converted to a discussion as well). The notion of ES version is on a constant decline—you should really not care about ES versions these days, but focus on specific feature support. For example, despite public class fields only landing in ES2022, its support dates back to early 2019. Closing per https://github.com/mdn/content/issues/2831#issuecomment-1175885476.
