### ISSUE TITLE
Retry-After doesn't suggest what to do for `Retry-After: 0`

### ISSUE THREAD

**Issue by jsoref** [mdn/content#28330]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After

### What specific section or headline is this issue about?

Directives

### What information was incorrect, unhelpful, or incomplete?

```
<delay-seconds>
  A non-negative decimal integer indicating the seconds to delay after the response is received.
```

Ok, so it could be `0`, or it could be `>=1`.

### What did you expect to see?

Prose that suggests how to handle `Retry-After: 0`

### Do you have any supporting links, references, or citations?

https://github.com/github/docs/issues/16683

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/headers/retry-after`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/retry-after/index.md
* Last commit: https://github.com/mdn/content/commit/0880a90f3811475d78bc4b2c344eb4146f25f66c
* Document last modified: 2023-04-10T19:47:15.000Z

</details>

**Comment by kemilbeltre** [comment]
Referring to the sharing link: "It's generally safe to assume that it will be a non-rational number with a value of 0 or greater. Instead, users should write defensive code in the case that the return value does not meed the expected format (e.g. due to a system error on our part)".

I think we could remember this scenario, but I don't see a specific reason to show how to handle such an open-ended edge case.

**Comment by Josh-Cena** [comment]
I agree with @kemilbeltre and I don't see the reason why it should be handled specially. All resources would say that `0` is legal, and it just means you can immediately retry without any waiting. (In fact, factoring in network delays, I don't think `Retry-After: 1` and `Retry-After: 0` are significantly different to the server anyway.)
