### ISSUE TITLE
Broken image links

### ISSUE THREAD

**Issue by flosacca** [mdn/content#28341]
https://github.com/mdn/content/pull/28233 removed files in `/files/en-us/web/svg/tutorial/paths` that are actually used. https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths is broken now.

cc @queengooborg

**Comment by rimjhp-06** [comment]
Hi,
Can you assign this issue to me?

**Comment by Ryuno-Ki** [comment]
These images are affected:

https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths/cubic_b%C3%A9zier_curves_with_grid.png
https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths/quadratic_b%C3%A9zier_with_grid.png
https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths/shortcut_cubic_b%C3%A9zier_with_grid.png
https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths/shortcut_quadratic_b%C3%A9zier_with_grid.png

They're in fact listed in the PR for removal.

The file in need of an update is https://github.com/mdn/content/blob/6f9c88d96588ea1690300d97efdf87d13a5be7e9/files/en-us/web/svg/tutorial/paths/index.md

(The reference of the files is structurally the same - my assumption is that the script fails over the accent in `bézier` because it is encoded)

**Comment by Ryuno-Ki** [comment]
I've filled https://github.com/mdn/yari/issues/9445 as I believe this is a bug in Yari (which runs the file checks) in addition to restoring the images.

**Comment by wbamberg** [comment]
This is fixed by https://github.com/mdn/content/pull/28540, isn't it? I know the Yari issue is outstanding, but that's tracked in Yari as https://github.com/mdn/yari/issues/9445.
