### ISSUE TITLE
globalCompositeOperation lacks list of operations

### ISSUE THREAD

**Issue by bitbof** [mdn/content#28465]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation

### What specific section or headline is this issue about?

Operations, which disappeared.

### What information was incorrect, unhelpful, or incomplete?

There used to be a list of all operations on this page which was very illustrative. Because a) it lists the possible values and b) it demonstrates them. Now it just says it's a "string", which is unhelpful. Which string values exactly?

### What did you expect to see?

this https://web.archive.org/web/20230201054214/https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/canvasrenderingcontext2d/globalcompositeoperation`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/canvasrenderingcontext2d/globalcompositeoperation/index.md
* Last commit: https://github.com/mdn/content/commit/bda6da832e5682d6247e1c20790e7b0aa0ec45e1
* Document last modified: 2023-08-03T20:27:59.000Z

</details>

**Comment by sideshowbarker** [comment]
cc @queengooborg — this is one of the sections that was deleted in https://github.com/mdn/content/commit/bda6da832e5682d6247e1c20790e7b0aa0ec45e1#diff-212f8a5f651c0b9f83de4c9ff29c1b470912eabddd0a3604235c2fac76019a72

**Comment by wbamberg** [comment]
Thanks for filing, @bitbof !

So this was removed as part of deprecating the feature in live samples where a live sample can be embedded in a different page. This feature was deprecated for good reasons and there's almost always a good alternative, but in this case, yes, it definitely regressed the page.

The example was being transcluded from https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Compositing/Example, which only contains that one example.

The example is only linked from one other place, which was https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Compositing#globalcompositeoperation.

Part of the problem is that the example was doing double duty - as a textual list of the values and a description of each one, and a code demo. It would be better of these were separated out.

So I think we should do this:

- add the text out of the example into https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation#value , so we have a normal `<dl>` listing values and descriptions of them
- move the example at https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Compositing/Example under https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation#examples
- correspondingly, update the link at https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Compositing#globalcompositeoperation - or even just delete the link, since we are linking to https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation from there anyway.

Does that sound like a good plan?
