### ISSUE TITLE
“Child combinator” article: Spaces not needed around '>'

### ISSUE THREAD

**Issue by David263** [mdn/content#28460]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/Child_combinator

### What specific section or headline is this issue about?

Syntax, Examples

### What information was incorrect, unhelpful, or incomplete?

The syntax and examples always show spaces surrounding the angle bracket ("direct child"). Just as with the period, spaces are not required around angle brackets in selectors. It might be interesting to see how many other MDN articles fail to mention the actual syntax of the CSS language. The CSS Standards mix examples using spaces and omitting spaces, for clarity.

### What did you expect to see?

Either a BNF-like specification of actual CSS syntax, a link to a BNF-like specification of actual CSS syntax, or mixing possibilities in the examples.

### Do you have any supporting links, references, or citations?

https://www.w3.org/TR/selectors-3/#child-combinators

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/child_combinator`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Child_combinator
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/child_combinator/index.md
* Last commit: https://github.com/mdn/content/commit/42c1bb8c259f3f57de9f38600776cf273e3addda
* Document last modified: 2023-02-21T06:27:49.000Z

</details>

**Comment by OnkarRuikar** [comment]
> The syntax and examples always show spaces surrounding the angle bracket ("direct child").

Because it is easier to read. It is automatically done by [using the code formatter Prettier](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEATAlgNwHwGcAOAhlMAEaFgDWA5gE4QCuUqAtJADYS1IAEtcqANwBfEABoQEfDHTRcyUIVr0A7gAUlCeSkLsVhAJ7yJpWhUpwYAZUIBbOABl0UOMgBmu3HBNmqlq0RgztTIMLQM3iBetuih4ZG4wexwAIoMEPDunpEAVrgAHlZJqemZSB7sXhIAjqVwavT42iCEuCwuAgLiIGGE6OzBAMIQtraEyC3s7N2JUNTJAIIwYeikDPBqcLROLlmVkQAWMLbsAOoH6PAEFHBWWpdYlwYTYLjGIJgRAJLMCNZgtHQ0gWzCsMAMyT2VRA+HoXlOZnwE1hcC8tEwrgkzjRMAahGoYyhkSItDRLze3Vhzhgp3QqBgB2QAA4AAwSfi1dD8PEE8blbISGCEUi0+mMpAAJgkDC8ABVhdoKtC4LZSAJUAIHMRqAx8XAAGJcMbLYITQjrCAgYTCIA).
