### ISSUE TITLE
Listing enumerated values for deprecated attributes

### ISSUE THREAD

**Issue by estelle** [mdn/content#28684]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table

### What specific section or headline is this issue about?

Deprecated attributes

### What information was incorrect, unhelpful, or incomplete?

In some deprecated attributes we list the enumerated values. In others we don't. @EzioMercer made a very valid point in a PR to add the enumerated values for the deprecated `frame` attribute. 

See https://github.com/mdn/content/pull/28399#issuecomment-1685318105

Section: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table#deprecated_attributes

### What did you expect to see?

consistency

should we list all the deprecated values? Should we omit them all. If some and not others, do we have a rationale?

**Comment by EzioMercer** [comment]
In my opinion, if something is deprecated but still widely supported, it should be described as if it weren't deprecated, but if something is deprecated and not widely supported, it should be removed or described very shortly for historic reasons

**Comment by bsmth** [comment]
This could be converted to a discussion, but adding new content about deprecated features doesn't seem useful beyond historical reasons, so from an editorial perspective I would freeze any additions to these, even for the sake of consistency. I'd lean more towards what we're doing with others ('described very shortly for historic reasons'):

```md
- `deprecated_attr` {{Deprecated_inline}}

  - : Description of this attr. To achieve a similar effect, use the {non-deprecated alternative}.
```

**Comment by hamishwillee** [comment]
Yes, I would move to a discussion. FWIW I don't think it makes sense to invest in deprecated content. So yes, you might add a short description to the non-deprecated alternative but I wouldn't pad out a full document.

Content removal has a policy that derives from BCD. Essentially it happens 2 years after a deprecated feature is removed from all browsers in our supported set.

**Comment by EzioMercer** [comment]
@hamishwillee How can I found the discussion of this issue?

**Comment by hamishwillee** [comment]
@EzioMercer It hasn't been moved. If it had, it the issue would "become" a discussion. I think it would be up to @estelle to do so if  she thinks it worthwhile.

I would not feel forced to put much effort into something that was deprecated, for consistency or otherwise. 
- I would ensure there was a BCD entry and possibly also an interface entry so that there is some record on MDN that people shouldn't use the property/method/class.
- I wouldn't create a full page, for a property though. It is valid to do so, but simply not a priority.
- For the same reason I wouldn't delete such a page. It does no harm to have and choosing to remove it would not be a priority.
