### ISSUE TITLE
Contradicting information about Multi threads in two different pages of the site.

### ISSUE THREAD

**Issue by 7777chaitanya** [mdn/content#28719]
### MDN URL

https://developer.mozilla.org/en-US/docs/Glossary/Thread

### What information was incorrect, unhelpful, or incomplete?

Read the below line. I copied it from the page that I am having issue with.

> However, modern [JavaScript](https://developer.mozilla.org/en-US/docs/Glossary/JavaScript) offers ways to create additional threads, each executing independently while possibly communicating between one another. This is done using technologies such as [web workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API), which can be used to spin off a sub-program which runs **concurrently** with the main thread in a thread of its own.

It implies that the sub-program spun off by the Web worker will run **concurrently/simultaneously** with the programming running in the main thread.

### What did you expect to see?

The below line is an extract from [this page](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Introducing_workers) of the site,

> But there's a price to pay for this. With multithreaded code, **you never know when your thread will be suspended and the other thread will get a chance to run**. So if both threads have access to the same variables, it's possible for a variable to change unexpectedly at any time, and this causes bugs that are hard to find.

It conveys the information that we can't be sure of when one thread will be suspended to give chance for the other thread to run. Isn't it contradictory with the point I highlighted in [this page](https://developer.mozilla.org/en-US/docs/Glossary/Thread)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/glossary/thread`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Thread
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/thread/index.md
* Last commit: https://github.com/mdn/content/commit/ada5fa5ef15eadd44b549ecf906423b4a2092f34
* Document last modified: 2023-06-08T13:19:16.000Z

</details>

**Comment by Josh-Cena** [comment]
I'm not super expert in execution model (yet; I am learning so I can write a page for it), but I think the second statement is wrong: specifically the word "suspended" is inaccurate because threads don't suspend unless they specifically request to be (via `Atomics.wait`). I find this entire second statement's purpose unclear, because you can't easily share variables between threads: only things like `SharedArrayBuffer` can be "shared" in the real sense such that reading it would cause race conditions. I wonder if this entire statement is talking about async instead of multithreading.

**Comment by hamishwillee** [comment]
@Josh-Cena Both of these are glossary entries, so the terminology can't assumed to be JavaScript specific, unless in a JavaScript section. 

W.r.t. suspended I think this terminology is overloaded. When referring to execution models you'll see discussions of an active thread and suspended threads, where suspended just means "not the thread that is currently being executed on the CPU". This differs from other usages where we mean "shut the thread down until some interrupt happens". 

I think we probably should:
- Update variable to be "data" - more broadly correct. 
- Remove discussion of suspending - the point here is to talk about managing concurrent access to data, and suspending has nothing to do with that.

**Comment by Josh-Cena** [comment]
Aha, the entire "With multithreaded code, you never know when your thread will be suspended and the other thread will get a chance to run. So if both threads have access to the same variables, it's possible for a variable to change unexpectedly at any time, and this causes bugs that are hard to find." is under the context of "how multithreading is done in other languages", because the next paragraph directly starts with "To avoid these problems on the web". I think we need to make this clear.

> Both of these are glossary entries

The second one is from JS learning area so it's definitely about JS. The first one is also heavily JS-based.

> - Update variable to be "data" - more broadly correct.
> - Remove discussion of suspending - the point here is to talk about managing concurrent access to data, and suspending has nothing to do with that.

Agreed.

**Comment by hamishwillee** [comment]
OK, then hopefully this is fixed by https://github.com/mdn/content/pull/28745

**Comment by 7777chaitanya** [comment]
I realized after reading the discussion between @hamishwillee & @Josh-Cena  that I was not clear very clear about the differences between concurrent and parallel execution of thread at the time of creating this issue which I am now. Thanks to both of you.

I also raised the above [PR](https://github.com/mdn/content/pull/28746) to add more clarity to [Threads page in glossary](https://developer.mozilla.org/en-US/docs/Glossary/Thread)
