### ISSUE TITLE
Missing example for CSS.supports() selector support (supportCondition not defined properly)

### ISSUE THREAD

**Issue by 1jj** [mdn/content#28801]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/CSS/supports_static

### What information was incorrect, unhelpful, or incomplete?

Hello!
It is not immediately clear that `CSS.supports()` can check for support for a CSS property as well as a CSS selector.

`supportCondition` isn't defined properly. It can be something like "selector(:is(b))"  (checking support for the `:is()` selector).

### What did you expect to see?

I propose to add something like this to the introduction:
The CSS.supports() static method returns a boolean value indicating if the browser supports a given CSS feature, or not. **It can check properties, values and selectors**.

`supportCondition`  needs better explanation and more examples, including selectors, like:
`CSS.supports("selector(:is(b))")`

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/css/supports_static`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CSS/supports_static
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/css/supports_static/index.md
* Last commit: https://github.com/mdn/content/commit/acfe8c9f1f4145f77653a2bc64a9744b001358dc
* Document last modified: 2023-07-07T07:19:19.000Z

</details>

**Comment by wbamberg** [comment]
>  It is not immediately clear that CSS.supports() can check for support for a CSS property as well as a CSS selector.

I'm not sure I understand. The "Syntax" section describes checking property-value pairs (and actually doesn't talk about selectors). Did you mean: "It is not immediately clear that CSS.supports() can check for support for a CSS **selector** as well as a CSS **property**"?

> supportCondition isn't defined properly. It can be something like "selector(:is(b))" (checking support for the :is() selector).

supportCondition is defined by reference to [`@supports`](https://developer.mozilla.org/en-US/docs/Web/CSS/@supports) which I think makes sense, because it is quite complicated. [`@supports`](https://developer.mozilla.org/en-US/docs/Web/CSS/@supports) does talk about `selector()`.

> I propose to add something like this to the introduction:
> The CSS.supports() static method returns a boolean value indicating if the browser supports a given CSS feature, or not. It can check properties, values and selectors.

I don't think we should do exactly this, as it will get out of date as things are added to `@supports`. According to https://developer.mozilla.org/en-US/docs/Web/CSS/@supports we can use it to check for font formats as well, for example.

But maybe we could have a "Description" in this page which can go into things in more detail.

>  more examples, including selectors, like: CSS.supports("selector(:is(b))")

This is definitely a good idea.
