### ISSUE TITLE
[WebAPI] CSS Nesting - Make CSSStyleRule a CSSGroupingRule

### ISSUE THREAD

**Issue by dipikabh** [mdn/content#28853]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1846251

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [x] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by hamishwillee** [comment]
This basically makes FF match the spec so [`CSSStyleRule`](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleRule) inherits from [`CSSGroupingRule`](https://developer.mozilla.org/en-US/docs/Web/API/CSSGroupingRule) instead of directly from  [`CSSRule`](https://developer.mozilla.org/en-US/docs/Web/API/CSSRule).

The docs are all up to date. What is missing is that `CSSStyleRule` will now support the `CSSGroupingRule` properties  `cssRules`, `deleteRule`, `insertRule`. The docs action here is to update BCD with links to those rules, and note they are supported in FF.

Status:
- [ ] BCD - link  `CSSGroupingRule` items and mark them as supported.
- [ ] Docs
- [ ] Release note
- [ ] dev-doc-complete

**Comment by Elchi3** [comment]
See https://github.com/mdn/browser-compat-data/pull/20928#issuecomment-1767735350 this shipped in 117 apparently and not in 118.

See also https://hg.mozilla.org/mozilla-central/rev/62534bac9235 where it says:  "(it's already enabled everywhere in 117)".

**Comment by hamishwillee** [comment]
Thanks very much @Elchi3. Glad you've got so much automation in the collector because I trusted the issue label.  Fixed by https://github.com/mdn/content/pull/29891
