### ISSUE TITLE
CSS Attributes: widows and orphans 

### ISSUE THREAD

**Issue by NoloContend** [mdn/content#28871]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/widows

### What specific section or headline is this issue about?

Formal Definition; Browser compatibility

### What information was incorrect, unhelpful, or incomplete?

The Mozilla page says widows and orphans are attributes of block container elements.  But those attributes do not work in Chrome browser at the block container level.  In Chrome, those attributes work when widows and orphans is set in the @page   According to the HTML 5 standard (https://www.w3schools.com/jsref/prop_style_orphans.asp), those attributes are set in the @media 
@media print {
  .orphans {
    orphans:2;
  }
}
The W3 standard does not agree those attributes can be set in separate block container elements.

### What did you expect to see?

widows and orphans properly controlled in the Chrome browser

### Do you have any supporting links, references, or citations?

https://www.w3schools.com/jsref/prop_style_orphans.asp

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/widows`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/widows
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/widows/index.md
* Last commit: https://github.com/mdn/content/commit/c77cfcd17e85db6c1b93160c70668f2ff6c2809c
* Document last modified: 2023-07-20T07:38:29.000Z

</details>

**Comment by NoloContend** [comment]
Also find through the Mozilla inspector that widows and orphans set in the <body> element are dropped.

Unknown property ‘widows’.  Declaration dropped. [cstyles.css:34:12](file:.../cstyles.css)
Elements matching selector: body.black

**Comment by OnkarRuikar** [comment]
@NoloContend The w3scools website [does not publish web standards](https://en.wikipedia.org/wiki/W3Schools). In order to easily locate web standards you can refer ["Specifications" section](https://developer.mozilla.org/en-US/docs/Web/CSS/orphans#specifications) on each page of the MDN website.

These properties are [part of the CSS Fragmentation module](https://drafts.csswg.org/css-break/#widows-orphans). The fragmentation can occur not only in print medium but also [in multi column layouts](https://developer.mozilla.org/en-US/docs/Web/CSS/orphans#setting_a_minimum_orphan_size_of_three_lines) and [CSS regions](https://webplatform.github.io/docs/tutorials/css-regions).

> Unknown property ‘widows’. Declaration dropped. cstyles.css:34:12

This means Firefox doesn't support these properties. So [the browser compatibility table](https://developer.mozilla.org/en-US/docs/Web/CSS/orphans#browser_compatibility) at the end of the pages are correct.

**Comment by NoloContend** [comment]
Understood about Mozilla not supporting it.  Grateful for the link.  It looks like Mozilla has the documentation correct and Chrome has implemented it, though not standardly.  Welcome to the real word of tech.

**Comment by Josh-Cena** [comment]
Closing since it appears the content is right
