### ISSUE TITLE
 Does the file match the text of the page?

### ISSUE THREAD

**Issue by DomOBU** [mdn/content#28901]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Sizing_tasks

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Sizing_tasks#task_1

### What information was incorrect, unhelpful, or incomplete?

Hello,

The text for task 1 refers to a height of 100px.

In the file "Download the starting point for this task" there is a value of 400px for min-height.
The CSS also refers to a .preview class which does not appear in the HTML.

Does the file match the text of the page?

Thank you for your reply.

### What did you expect to see?

An answer to my questions.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/sizing_tasks`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Sizing_tasks
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/sizing_tasks/index.md
* Last commit: https://github.com/mdn/content/commit/751d58669499de0c6ea0d5b356e0e1448418c5d3
* Document last modified: 2023-06-30T06:21:35.000Z

</details>

**Comment by wbamberg** [comment]
It's a bit complicated. With these tasks, there are two different ways you are invited to complete it.

1. you can complete it in the interactive editor in the page
2. you can download the starting point and work in it in your own editor

The "interactive editor in the page" version is implemented as a separate web page that gets embedded in an iframe in the MDN page. The separate web page is at https://mdn.github.io/css-examples/learn/tasks/sizing/height-min-height.html, and the source for that is at https://github.com/mdn/css-examples/blob/main/learn/tasks/sizing/height-min-height.html. That version does include a `.preview` element, which is part of the interactive editor, and its `min-height` is set to `400px`: https://github.com/mdn/css-examples/blob/6e6fd622cda1e51ba66d10e92789f75de93dce9a/learn/tasks/sizing/height-min-height.html#L15.

The "download the starting point" version is downloaded from https://github.com/mdn/css-examples/blob/main/learn/tasks/sizing/height-min-height-download.html. This one does not have a `.preview` element, because it doesn't contain an interactive editor. But we mistakenly left in the CSS for the `.preview` element, probably in a copy/paste error.

So, short answer:
- we should remove the `.preview` CSS from the "download the starting point" version at https://github.com/mdn/css-examples/blob/6e6fd622cda1e51ba66d10e92789f75de93dce9a/learn/tasks/sizing/height-min-height-download.html#L23
- this has nothing to do with the 100px min-height (although it is confusing!).

**Comment by wbamberg** [comment]
Fixed in https://github.com/mdn/css-examples/pull/148.
