### ISSUE TITLE
infinite loop in example code

### ISSUE THREAD

**Issue by jamesblacklock** [mdn/content#28954]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/ReadableStreamBYOBReader

### What specific section or headline is this issue about?

"Examples"

### What information was incorrect, unhelpful, or incomplete?

```js
while (offset < buffer.byteLength) {
  // THIS LOOP IS INFINITE!
  // offset never changes because `readStream` is not async and
  // we do not `await` the result of `reader.read(...).then(...)`
  reader
    .read(...)
    .then(...);
}
```

Also the loop will not terminate when the stream is `done`. It only terminates if the buffer runs out of room.

### What did you expect to see?

```js
async function readStream(reader) {
  ...
  while (offset < buffer.byteLength) {
    await reader
      .read(...)
      .then(...);
  }
}
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/readablestreambyobreader`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ReadableStreamBYOBReader
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/readablestreambyobreader/index.md
* Last commit: https://github.com/mdn/content/commit/d41c5446d4ef257280fae9b78e2298ced8954a95
* Document last modified: 2023-05-09T20:58:09.000Z

</details>

**Comment by hamishwillee** [comment]
I don't think this is correct:

>   // THIS LOOP IS INFINITE!
>  // offset never changes because `readStream` is not async and
>   // we do not `await` the result of `reader.read(...).then(...)`

It is true that `readStream()` is not asynchronous, but it does not have to be. 
In the code you highlight (see below) the `read()` returns a promise. The `then` part does not execute until the `read()` has returned - so it is doing the same thing as awaiting.

```js
    reader
      .read(new Uint8Array(buffer, offset, buffer.byteLength - offset))
      .then(function processBytes({ done, value }) {
```

As soon it gets the bytes the `processBytes()` is executed, and that is what updates the offset.

What am I missing?

**Comment by jamesblacklock** [comment]
Well, the loop condition is based on `offset` and `buffer.byteLength`, and neither of these two values can possibly change within the synchronous context of the loop. They are updated when the promise resolves, which will be blocked by the loop never completing.

Am I the one missing something?

**Comment by hamishwillee** [comment]
They can change: methods that return a promise return immediately, so the sync nature of the loop doesn't block anything. After some time the promise fulfills (when you get data). The offset etc then get updated and would be evaluated next time the loop iterates.

Unfortunately I am now confused. Firstly, the loop falls through after returning a promise, so I wonder that we aren't just calling the reader multiple times/creating multiple promises. Secondly, even if that doesn't happen, it feels like that loop is unnecessary.

I've asked for some advice from someone who should be back at the end of the week. If not, I'll prototype this and verify exactly what is going on.

**Comment by jamesblacklock** [comment]
The JS environment is single threaded, so if there is a busy waiting loop, it will spin forever and block the promise handler even if it resolves in the background. I am fairly certain about this, though I have not tried to actually test on my machine.

**Comment by Josh-Cena** [comment]
Yes, this is wrong. Until the loop exits, asynchronous tasks can never complete.

```js
let x = 1;
while (x === 1)
  Promise.resolve().then(() => x = 2);
```

This never completes

**Comment by hamishwillee** [comment]
Thanks! It's not you it's me :-). I'll rewrite.

**Comment by hamishwillee** [comment]
FYI
- The code in question [comes from this live example](https://developer.mozilla.org/en-US/docs/Web/API/Streams_API/Using_readable_byte_streams#result_2), which appears to work and will also need to be fixed.
- The behaviour is even more odd than you might think.
  - The first read returns a promise and the `then` is queued.  In theory this should never run.
  -  Execution then drops to the end of the loop at which point the while loop exits.
  - Why, because the buffer length is zero. WHaaaaat???? I think that the read operation is passing ownership of that buffer back to the other size for the zero-copy transfer, so at this point the reader is holding nothing.
  - So the while loop exits 
  - The `then` completes transferring all the data in one go.
  - The process loop is called again with `done`.

We can certainly remove the while loop as it is pointless. I'm not sure how to fix this though (yet) to make it meaningful, since all data is read in one go to fill the buffer. I guess we can either provide smaller buffers from the source so that it doesn't all get satisfied in one go.

**Comment by hamishwillee** [comment]
OK, I think this is fixed by https://github.com/mdn/content/pull/29242
