### ISSUE TITLE
Issue with "Intl.DateTimeFormat": problem with "pt-PT" format

### ISSUE THREAD

**Issue by roni6chabra** [mdn/content#2909]
Hi,
 theres a problem with Intl.DateTimeFormat library converting "pt-PT" dateRegionalSettingsLocale

printing this one in the console: 

`var dateRegionalSettingsLocale = "en-US";
var formatter = new Intl.DateTimeFormat(
     dateRegionalSettingsLocale,
      {
        day: 'numeric',
        month: 'short',
        year: 'numeric',
        timeZone: "Asia/Jerusalem",
      },
    );
formatter.format(new Date("2021-03-07T20:30:00Z"));`

will print “Mar 7, 2021", but if ill change dateRegionalSettingsLocale to "pt-PT" (Portuguese (português) - Portugal) then ill receive a different format: 7/03/2021 

can you please fix it?
Thanks!

**Comment by hamishwillee** [comment]
Closing because this does not look like an issue with the **MDN content** - i.e. I can't find any example that looks like this in the docs. IF this is a documentation bug then please reopen and show the specific page where the incorrect text is listed.

What I think you may be reporting is some issue with the execution of this API on your browser - but you don't say which one.
If this is a browser bug, please post it in the issue tracker for the browser concerned, along with information about what you expect the output to look like.  Thanks!
