### ISSUE TITLE
Possible misleading description of History method

### ISSUE THREAD

**Issue by Gergely713** [mdn/content#29138]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/History/replaceState

### What information was incorrect, unhelpful, or incomplete?

"This method is asynchronous. Add a listener for the popstate event in order to determine when the navigation has completed. The state parameter will be available in it."

### What did you expect to see?

replaceState method on it's own should not be described as an asynchronous function.

### Do you have anything more you want to share?

You can execute the following example to validate it is synchronous:

```
(() => {
    let oldReplaceState = history.replaceState;
    history.replaceState = function replaceState() {
        let ret = oldReplaceState.apply(this, arguments);
        console.log(arguments)
        return ret;
    };
})();

console.log('beginning')
history.replaceState({}, '', '#asd')
history.replaceState({}, '', '#asd1')
history.replaceState({}, '', '#asd2')
console.log('after asd2')
history.replaceState({}, '', '#asd3')
history.replaceState({}, '', '#asd4')
history.replaceState({}, '', '#asd5')
history.replaceState({}, '', '#asd6')
history.replaceState({}, '', '#asd7')
history.replaceState({}, '', '#asd8')
history.replaceState({}, '', '#asd9')
history.replaceState({}, '', '#asd10')
history.replaceState({}, '', '#asd11')
console.log('end') 
```

**Comment by Josh-Cena** [comment]
You did not do anything async within your new function, so surely it "executes synchronously". Consider the following:

```js
(() => {
    let oldFetch = fetch;
    window.fetch = function fetch() {
        let ret = oldFetch.apply(this, arguments);
        console.log(arguments);
        return ret;
    };
})();
```

And using the same approach you would claim that `fetch` is synchronous, while you know that isn't the case—it's only because you didn't await the `oldFetch.apply` call.

`replaceState` is indeed async, but because it doesn't accept a callback or return a promise, you can't await it. The only way to "wait until replaceState is complete" is to use an event listener, so the current text is accurate
