### ISSUE TITLE
Grammar errors on this page

### ISSUE THREAD

**Issue by zoedarkweather** [mdn/content#29226]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Performance/business_case_for_performance

### What specific section or headline is this issue about?

Key Performance Indicators section

### What information was incorrect, unhelpful, or incomplete?

There are several sentences that have grammar errors, mainly wrong verb form.  These are the 3 errors I noticed: 
1. helps performance proponent advocates for good user experience against competing interests --- I'm actually not clear on what this is trying to say.  Maybe it should be proponents plural and advocate without an s at the end?

2. When a site performance slowly, users are more likely to abandon the site  ---should be perform not performance

3. Poor user performance experiences can equation to poor brand reputation.  ---should be equate not equation

### What did you expect to see?

I just wanted to let you guys know about this.  These errors make it a bit hard to read and might be making a poor impression.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/performance/business_case_for_performance`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Performance/business_case_for_performance
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/performance/business_case_for_performance/index.md
* Last commit: https://github.com/mdn/content/commit/bb026bcb88b7f45374d602301b7b0db5a49ff303
* Document last modified: 2023-07-03T10:12:35.000Z

</details>

**Comment by wbamberg** [comment]
Thank you for filing!

> helps performance proponent advocates for good user experience against competing interests --- I'm actually not clear on what this is trying to say. Maybe it should be proponents plural and advocate without an s at the end?

Yes it looks like you are right. Also I think it would be fine to say "...helps you advocate".

Would you like to file a PR to fix these errors?

**Comment by ferdnyc** [comment]
Also:

1. The top-of-page navigation has a "Next:" link to the "Web Performance Basics" page. 

    Which is a bit confusing, as that page doesn't appear in the sidebar. (It's a "See Also" labeled "Web performance resources", at the bottom of [Learn/Performance](https://developer.mozilla.org/en-US/docs/Learn/Performance#see_also).) So, following the link makes the sidebar go all... generic.
2. The bottom-of-page navigation, OTOH, has no "Next:" link.

**Comment by ferdnyc** [comment]
@zoedarkweather 
> These errors make it a bit hard to read and might be making a poor impression.

Agreed. Another contributing factor is the page's tendency to use overlong, jargon-heavy sentences. Like this one:

> KPIs can be both a set of important business metrics in measuring the impact of user experience and performance on the business's top line, and a way of demonstrating the benefits of prioritizing performance.

Technically that CAN be just one long, incredibly dense sentence, grammatically — it's perfectly _valid_ that way. But that doesn't mean it **_should_** be.

**Comment by wbamberg** [comment]
> Also:
> 
> 1. The top-of-page navigation has a "Next" link to the "Web Performance Basics" page.
>        Which is a bit confusing, as that page doesn't appear in the sidebar. (It's a "See Also" labeled "Web performance resources", at the bottom of [Learn/Performance](https://developer.mozilla.org/en-US/docs/Learn/Performance#see_also).) So, following the link makes the sidebar go all... generic.
> 
> 2. The bottom-of-page navigation, OTOH, has no "Next" link.

Sigh. Yes. It looks like what happened is that https://developer.mozilla.org/en-US/docs/Learn/Performance/Web_Performance_Basics was moved from https://developer.mozilla.org/en-US/docs/Web/Performance/ (in which it was outside the Learn module, thus a "See also" page and not present in the sidebar) into https://developer.mozilla.org/en-US/docs/Learn/Performance, but noone thought to update the nav consistently. I wish keeping the Learn nav consistently up to date wasn't so error-prone.

So I guess the simplest solution would be something like:
- add https://developer.mozilla.org/en-US/docs/Learn/Performance/Web_Performance_Basics to the Learn sidebar
- move its entry in https://developer.mozilla.org/en-US/docs/Learn/Performance from "See also" to "Guides"
- add a "Next" link to https://developer.mozilla.org/en-US/docs/Learn/Performance/Web_Performance_Basics at the bottom of https://developer.mozilla.org/en-US/docs/Learn/Performance/business_case_for_performance

However! The order of articles then looks quite incoherent. Why is "Web performance resources", which reads like an introductory group of tips and introductory things, now the last article in the module? Perhaps it could be repurposed as a kind of "summary of what we have covered"? Anyway that's a deeper problem than just fixing a few links.

Either way though, this is getting outside the scope of fixing the grammar of https://developer.mozilla.org/en-US/docs/Learn/Performance/business_case_for_performance, so it ought to be a separate issue.

> Another contributing factor is the page's tendency to use overlong, jargon-heavy sentences. Like this one:
> 
> > KPIs can be both a set of important business metrics in measuring the impact of user experience and performance on the business's top line, and a way of demonstrating the benefits of prioritizing performance.
> 
> Technically that CAN be just one long, incredibly dense sentence, grammatically — it's perfectly _valid_ that way. But that doesn't mean it **_should_** be.

Yeah, in general I'm not all the keen on stylistic rewrites (as opposed to rewrites that fix actual grammatical errors) because they tend to end up being quite subjective and take a lot of review time. But I agree that this page could use a writing style update.

**Comment by mighty-odewumi** [comment]
> Thank you for filing!
> 
> > helps performance proponent advocates for good user experience against competing interests --- I'm actually not clear on what this is trying to say. Maybe it should be proponents plural and advocate without an s at the end?
> 
> Yes it looks like you are right. Also I think it would be fine to say "...helps you advocate".
> 
> Would you like to file a PR to fix these errors?


Hi, I would like to contribute to fix these errors.

**Comment by wbamberg** [comment]
> > Thank you for filing!
> > > helps performance proponent advocates for good user experience against competing interests --- I'm actually not clear on what this is trying to say. Maybe it should be proponents plural and advocate without an s at the end?
> > 
> > 
> > Yes it looks like you are right. Also I think it would be fine to say "...helps you advocate".
> > Would you like to file a PR to fix these errors?
> 
> Hi, I would like to contribute to fix these errors.

Please go ahead, @mighty-odewumi !

**Comment by mighty-odewumi** [comment]
Okay. Thanks.

**Comment by hamishwillee** [comment]
Fixed by @mighty-odewumi in https://github.com/mdn/content/pull/29237 !!!

**Comment by wbamberg** [comment]
Thanks! I filed https://github.com/mdn/content/issues/29240 for the issues reported in https://github.com/mdn/content/issues/29226#issuecomment-1729892916, since ISTM that they are also worth addressing (but they are separate from this issue).
