### ISSUE TITLE
The "Navigator: languages property" documentation is missing some browser quirks

### ISSUE THREAD

**Issue by dylanmccall** [mdn/content#29371]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/languages

### What information was incorrect, unhelpful, or incomplete?

The MDN page for [Navigator.languages](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/languages) implies that the `navigator.languages` property and the `Accept-Language` header are always the same:

> The `Accept-Language` HTTP header in every HTTP request from the user's browser uses the same value for the `navigator.languages` property except for the extra `qvalues` (quality values) field (e.g. `en-US;q=0.8`).

Indeed, this is implied by [the specification](https://html.spec.whatwg.org/#navigatorlanguage). However, it has never been the behaviour in WebKit, as evidenced by the thread in which the feature was first implemented:

https://bugs.webkit.org/show_bug.cgi?id=163220

Instead, `navigator.languages` always returns an array with a single value. The relevant change to `Source/WebCore/page/NavigatorBase.cpp` is still standing in WebKit's most recent release.

Chrome exhibits similar behaviour on mobile devices, although not that I have noticed on the desktop: https://bugs.chromium.org/p/chromium/issues/detail?id=1345416.

There is also a relevant experiment the Chrome developers did to reduce fingerprinting by limiting what gets included in both the `Accept-Languages` header and in `navigator.languages`: https://developer.chrome.com/blog/origin-trial-for-accept-language-reduction/. Although if they did that for real (sigh), at least the text here would be correct.

### What did you expect to see?

I have to admit, I'm confused and frustrated by all of this, but I think MDN could improve here by explaining that `navigator.languages` probably can't be trusted to provide a list of fallback languages in _at least_ Chrome and Safari.

My suggestion is to completely remove the paragraph I quoted, since it is not true in a majority of cases, and add more implementation notes under Chrome, Safari, and Android WebView.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/navigator/languages`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/languages
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/navigator/languages/index.md
* Last commit: https://github.com/mdn/content/commit/ef75c1741b450c2331204be5563ee964ad5f4c48
* Document last modified: 2023-04-07T06:16:45.000Z

</details>

**Comment by Josh-Cena** [comment]
@dylanmccall It has been quite a while! I was looking at this but I don't think there's _divergence_ between `Accept-Language` and `navigator.languages`. Here's Chrome:

<img width="264" alt="image" src="https://github.com/mdn/content/assets/55398995/fe3e91f4-8955-4af5-aeee-a11480dc069c">

<img width="614" alt="image" src="https://github.com/mdn/content/assets/55398995/2c773925-eb45-4174-99cd-4ed982e9195f">

And here's Safari:

<img width="161" alt="image" src="https://github.com/mdn/content/assets/55398995/df5a6914-7c8b-47cd-93a2-6438e916629e">

<img width="223" alt="image" src="https://github.com/mdn/content/assets/55398995/e07382c9-c163-4d5d-b52f-b02bacd1a719">

And here's Firefox:

<img width="303" alt="image" src="https://github.com/mdn/content/assets/55398995/12f7a48f-92cc-46d5-a997-23e8c3bebd5c">

<img width="321" alt="image" src="https://github.com/mdn/content/assets/55398995/54dd7cc2-520c-4dad-92cb-a17a59cabd88">

In my OS settings as well as each browser's settings, I have en-US, zh-CN, and fr-FR as preferred languages. It seems:

- Chrome always includes all languages, but has language-without-region fallback in `Accept-Language` only (I can also explicitly select en in preferred languages, in which case `en` is also included in `navigator.languages`)
- Safari always only includes one language, but has language-without-region fallback in `Accept-Language` only (and macOS settings doesn't have generic "en" it seems)
- Firefox always includes all languages, and doesn't have language-without-region fallback

Is the `en-US` vs `en-US, en` discrepancy significant enough to say that they are "different"? To me that's the browser trying to be helpful because some servers might not recognize `en-US`.
