### ISSUE TITLE
Error in example code

### ISSUE THREAD

**Issue by mirthmgr** [mdn/content#29458]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_nesting/Using_CSS_nesting

### What specific section or headline is this issue about?

Example - Nesting and compound selectors

### What information was incorrect, unhelpful, or incomplete?

The CSS for the example is missing the '&' before the 'h2:before' elements, which breaks the nested CSS.

### What did you expect to see?

The example should show three divs with different appearances. As written, it shows three divs with identical styling. Adding the '&' before the 'h2:before' elements fixes the problem.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/css_nesting/using_css_nesting`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_nesting/Using_CSS_nesting
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_nesting/using_css_nesting/index.md
* Last commit: https://github.com/mdn/content/commit/bb652aaf3e38f3c7fef970a62f813047dffac879
* Document last modified: 2023-10-02T11:11:40.000Z

</details>

**Comment by zfox23** [comment]
Hi @mirthmgr :)

I'm seeing three divs with different appearances in the linked example:
![image](https://github.com/mdn/content/assets/3409031/dbf1e290-6776-449e-b1ec-a9d1fd4572b8)

I also notice that adding `&` before `h2:before` (i.e. `&h2:before`) breaks the examples by incorrectly modifying the content of the headers:
![image](https://github.com/mdn/content/assets/3409031/ccfe62e2-bb40-479d-898c-8d47610fb90b)

Could you please help me understand (perhaps with screenshots) the error that you're seeing? Thank you!

**Comment by mirthmgr** [comment]
Hi, Zach!

I've attached screenshots of what I'm seeing in Edge and Chrome. I had not
realized that Firefox needed an update, and once I updated it, it shows the
example correctly (prior to update it behaved the same as the other
browsers). I did include a space between the & and h2:before, which fixes
the issue in both of the Chromium browsers and does not appear to break
anything in Firefox.

Thanks!

-Kevin

**Comment by zfox23** [comment]
Hi again :) Thanks for your patience between your latest reply and this one.

You mentioned that you "attached screenshots," and I noticed that you replied to this GitHub issue via email. I can't see email attachments on the GitHub issue - could you please try re-attaching your screenshots via the GitHub Issue UI?

I'm also very interested in seeing what the result looks like when you say "I did include a space between the & and h2:before, which fixes the issue...", because I might not be seeing the same thing.

Also related: [The CSS Nesting Selector `&` is only "partially supported" on all browsers except for Firefox.](https://developer.mozilla.org/en-US/docs/Web/CSS/Nesting_selector#browser_compatibility) So perhaps what you're seeing is a result of such partial support?

**Comment by mirthmgr** [comment]
My bad! I am not very familiar with GitHub yet, so I didn't realize that email attachments wouldn't go through. 

Here's what it looks like in up-to-date Chromium browsers on my system before adding "& " in front of the h2:before selectors:
<img width="1076" alt="Before Edit" src="https://github.com/mdn/content/assets/109144669/954e13ab-83d1-492e-b728-4fddeed1ae3f">

And after adding the "& ":
<img width="1087" alt="After Edit" src="https://github.com/mdn/content/assets/109144669/cdfdd2e2-324b-4b5a-a9ea-8b94164e001f">

The partial support note indicates that Chrome/Edge do not support nested type rules that start with a selector, so I guess that explains why the example doesn't work as written. I don't know if the addition of "& " would be considered a dirty hack or break anything in other contexts, but it seems to work in this case.

Thank you!

**Comment by zfox23** [comment]
Thank you for the additional information and screenshots! I totally see what you mean now, and have verified your suggested solution locally.

You are right to call out the cross-browser compatibility note, with a minor addition to what you mentioned: Chrome/Edge do not support nested rules that start with a _type_ selector, which is exactly the limitation we're seeing here.

The following two CSS rules **are functionally equivalent in Firefox, but are not functionally equivalent across all browsers**, exactly because of that limitation:

```css
.notice {
  h2:before {
    content: "ℹ︎ ";
  }
```

```css
.notice {
  & h2:before {
    content: "ℹ︎ ";
  }
```

However, if we modify the example HTML code to assign a class to each `<h2>` element, i.e. `<h2 class='graphic'>`, and _then_ change our CSS from `h2:before` to `.graphic:before` where relevant, you'll see the nested selector work properly.

It's not a dirty hack to be **specific** here by adding `& ` in the selectors, but it certainly does change the way this educational information is presented.

I think it would be useful to call out this cross-browser limitation in the example code. I'll put together a PR soon. Please let me know if all of this makes sense to you!
