### ISSUE TITLE
Invalid oklab() values?

### ISSUE THREAD

**Issue by rennex** [mdn/content#29503]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/oklab

### What specific section or headline is this issue about?

Adjusting opacity with oklab()

### What information was incorrect, unhelpful, or incomplete?

The `a` and `b` coordinates in the CSS colors `oklab(50% 130 20)` and `oklab(50% 130 20 / 0.4)`

### What did you expect to see?

Something like `oklab(50% 0.13 0.2)` or `oklab(50% 130% 20%)`.

I don't know why it would be over 100%, but that would be closer to reasonable than `130` without a percent sign.

### Do you have anything more you want to share?

I tried changing the numbers up and down in the playground. It seems that my browser makes different guesses about how to interpret the numbers, when I add the percent sign to `130` or `20`, or both, or neither. Now I'm not sure what kinds of values are actually valid, or if they only work due to some compatibility quirk.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/color_value/oklab`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/oklab
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/color_value/oklab/index.md
* Last commit: https://github.com/mdn/content/commit/8cb896db41ef17577941067991a2a805d7f661e4
* Document last modified: 2023-07-17T08:05:41.000Z

</details>

**Comment by OnkarRuikar** [comment]
@rennex [Valid value range ](https://drafts.csswg.org/css-color/#specifying-oklab-oklch) is `-0.4` to `0.4`. And percentages are corresponding to these values. Looks like values outside the range are not clamped and create undesired results due to underlying formulas.

> Now I'm not sure what kinds of values are actually valid, or if they only work due to some compatibility quirk.

The 3-D color space oklab is not linear it is very similar to CIELAB space:
![1](https://github.com/mdn/content/assets/87750369/7eade1d4-14b8-403e-b382-eb997ff3c618)

You can play with the [oklab color wheel](https://observablehq.com/@shan/oklab-color-wheel) to get better understanding.
