### ISSUE TITLE
srcset attribute sizes accepts any <length>

### ISSUE THREAD

**Issue by Amer-Adel** [mdn/content#29589]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images

### What specific section or headline is this issue about?

Resolution switching: Different sizes

### What information was incorrect, unhelpful, or incomplete?

Note: For the slot width, rather than providing an absolute width (for example, 480px), you can alternatively provide a width relative to the viewport (for example, 50vw) — but not a percentage.

### What did you expect to see?

A mention to the `em` value also, So we don't think that these two are just the available values.

### Do you have any supporting links, references, or citations?

https://www.dofactory.com/html/img/sizes#using

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/html/multimedia_and_embedding/responsive_images`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/multimedia_and_embedding/responsive_images/index.md
* Last commit: https://github.com/mdn/content/commit/751d58669499de0c6ea0d5b356e0e1448418c5d3
* Document last modified: 2023-06-30T06:21:35.000Z

</details>

**Comment by caugner** [comment]
The issue is about this note box in the [How do you create responsive images?](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images#how_do_you_create_responsive_images) section:

![Image](https://github.com/mdn/content/assets/495429/c0214c11-5e29-44df-a385-600324239f8b)

A solution could probably be to reference the [<length>](https://developer.mozilla.org/en-US/docs/Web/CSS/length) data type in the note box, and possibly also where [srcset](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#srcset) is defined on the `img` page.

Technically, the specification [mentions](https://html.spec.whatwg.org/multipage/embedded-content.html#attr-img-srcset) the [`sizes` attribute](https://html.spec.whatwg.org/multipage/images.html#sizes-attribute) whose value must be a `<source-size-list>` which includes a `<source-size-value>` which can be a `<length>`.

Overall, since this page is a Learn chapter module, I would say it doesn't need to be that comprehensive, but the reference page that defines `srcset` could mention this.
