### ISSUE TITLE
Mention that `headers` attribute can also be used for `<th>`

### ISSUE THREAD

**Issue by Amer-Adel** [mdn/content#29654]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Advanced

### What specific section or headline is this issue about?

The id and headers attributes

### What information was incorrect, unhelpful, or incomplete?

2. You add a `headers` attribute to each `<td>` element.

This attribute can also use for the `<th>` if it was a subheading.

### What did you expect to see?

1. Mention that in a complex example that have headings group, subheadings, cells to make things clear.
2. Also what the cells will have in its `headers` attribute just the subheading for it or its parent also?

### Do you have any supporting links, references, or citations?

[headers Attribute on W3S](https://www.w3schools.com/TAGS/att_headers.asp)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/html/tables/advanced`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Advanced
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/tables/advanced/index.md
* Last commit: https://github.com/mdn/content/commit/bda6da832e5682d6247e1c20790e7b0aa0ec45e1
* Document last modified: 2023-08-03T20:27:59.000Z

</details>

**Comment by caugner** [comment]
I agree that the [The id and headers attributes](https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Advanced#the_id_and_headers_attributes) section could mention how `headers` would be used on `<th>`s, but I'm not sure if it needs a dedicated example.

Note that the `headers` attribute is already mentioned on the [`<th>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/th#attributes) page.

**Comment by dipikabh** [comment]
Thank you for your suggestion, @Amer-Adel. You're correct – the `headers` attribute can be used with `<th>` elements. In fact, both `id` and `headers` are valid attributes for [`<th>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/th) and [`<td>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/td) elements.

We should definitely update and clarify these details on the page as well as update the example right after to demonstrate the use of `id` and `headers` with `<th>` and `<td>`. This update is particularly important because we're talking about making tables more accessible.

We always welcome contributions, so if you or anyone else would like to submit an update, please feel free to open a pull request.

**Comment by glmvc** [comment]
We are working on the table element reference pages in https://github.com/mdn/content/pull/27958, where this issue is addressed.
