### ISSUE TITLE
beforeunload demo not work at all

### ISSUE THREAD

**Issue by xgqfrms** [mdn/content#29655]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event

### What information was incorrect, unhelpful, or incomplete?

the `beforeunload` demo not work at all

### What did you expect to see?

display the `dialog`

### Do you have any supporting links, references, or citations?

https://iframe.xgqfrms.xyz/Web-APIs/beforeunload.html

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/window/beforeunload_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/beforeunload_event/index.md
* Last commit: https://github.com/mdn/content/commit/26f68076bcd8e3d5893cffcd9c1c01ff949318a9
* Document last modified: 2023-10-12T17:28:48.000Z

</details>

**Comment by xgqfrms** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event#examples

**Comment by wbamberg** [comment]
Which browser and browser versions are you seeing this with?

The example works for me in Firefox and Chrome Canary (120) but not in Chrome release (118). That's as expected I think given that this way of launching the confirm dialog is only supported from Chrome 119. This will be documented in the browser compat table but isn't yet because https://github.com/mdn/browser-compat-data/pull/20964 isn't merged and deployed.

I probably should have held off on merging https://github.com/mdn/content/pull/29595 until the BCD was updated.

At this point the best thing to do is probably just try to get the BCD PR merged asap. @chrisdavidmills , any thoughts?

**Comment by chrisdavidmills** [comment]
> At this point the best thing to do is probably just try to get the BCD PR merged asap. @chrisdavidmills, any thoughts?

Yup, I think so. I tried to merge it on Friday, but it got reverted because of some errors in the note content. I've submitted a new BCD PR today (see https://github.com/mdn/browser-compat-data/pull/20964)

I'm not sure if it is worth updating the content to show non-best-practice examples at this point. 119 will be the stable version as of next week. And we do list the other ways of doing it.

**Comment by caugner** [comment]
As far as I understand the BCD table, setting the `returnValue` seems redundant when returning a truthy value.

Since `preventDefault()` isn't fully supported yet, wouldn't it make sense to keep the `return` for now?

```js
const beforeUnloadHandler = (event) => {
  // Recommended.
  event.preventDefault();
  // Legacy support (Chrome/Edge < 119, Opera).
  return "true";
};
```

**Comment by chrisdavidmills** [comment]
@caugner Hrm, I see what you are saying. Do both, in case of anyone still using a browser that doesn't support the `preventDefault()` method?

I could raise a PR to fix this up pretty quickly.

**Comment by caugner** [comment]
Correct, until `preventDefault()` is baseline, I would say it's good practice to include the `return` statement. Or to put it differently, I don't think it's best practice to drop deprecated legacy behavior immediately as soon as an alternative is implemented in all browsers, to give people time to adopt the new browser versions.

**Comment by Josh-Cena** [comment]
Seems like this is fixed

**Comment by andreighh** [comment]
It doesn't work for me: `Firefox 130.0.1`
