### ISSUE TITLE
Window.open features are ignored

### ISSUE THREAD

**Issue by AlkisPis** [mdn/content#2992]
Re: https://developer.mozilla.org/en-US/docs/Web/API/Window/open

Using `var windowFeatures = "menubar=yes,location=yes,resizable=yes,scrollbars=yes,status=yes";` as the suggested code is or totally the opposite, `var windowFeatures = "menubar=no,location=no,resizable=no,scrollbars=no,status=no";` makes absolutely no difference, i.e. the result is exactly the same:

![image](https://user-images.githubusercontent.com/17760857/110610373-4ee94800-8175-11eb-9125-d8b2b72e3776.png)

**Comment by Rumyra** [comment]
To whoever fixes this issue, it looks like the following is needed:

* This is due to different browsers and different platforms - see the section: https://developer.mozilla.org/en-US/docs/Web/API/Window/open#popup_condition
* Add a note which links to this information further up the page: https://developer.mozilla.org/en-US/docs/Web/API/Window/open#window_features possibly expanding on the note here

**Comment by AlkisPis** [comment]
Thank you, Rumyra. I know already about the first of these references. And I have come to the conclusion that window features have been sacrificed in the name of "security". (As is our peacefulness disturbed by all the annoying popup windows, CAPTCHA's  and all kind of other security checks and privacy "protections".) It is very pity for me, because I used these features a lot in the past as parts of my HTML pages! 

Another question arises, though: Why the all the HTML and JS references do not mention this "censure" of the window features, but they continue using them as nothing has changed?! (This is a  rhetorical question. You don't have to answer to it! :))
