### ISSUE TITLE
Explain how multiple src values work on @font-face reference page

### ISSUE THREAD

**Issue by AlGantori** [mdn/content#3006]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face

#### What information was incorrect, unhelpful, or incomplete?

How specifying multiple url() for the src  means?

Do I have to have @font-face for each font I would like to use?

Thank you.

**Comment by chrisdavidmills** [comment]
Hi @AlGantori ! This is to provide the browser with multiple options as to what font file to download. It will choose the first one it is able to use, if I remember correctly, which is why you always write the "best" format first, e.g. WOFF2, and then write older formats later, e.g. TrueType. Browsers that don't understand WOFF2 can then fall back to TrueType.

I suppose it would be good to make it clear how this works on the page! I'll update this issue so that it is about adding that information.
