### ISSUE TITLE
Issue with "Test your skills: Multimedia and embedding": (short summary here please)

### ISSUE THREAD

**Issue by Harishdev10** [mdn/content#3010]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Video_and_audio_content/Test_your_skills:_Multimedia_and_embedding

#### What information was incorrect, unhelpful, or incomplete?
I guess its my mistake or I am not sure. I am not able to add subtit
![Capture](https://user-images.githubusercontent.com/78188373/110677064-b05df500-820f-11eb-9363-3a48b250e7c9.PNG)

les.

#### Specific section or headline?
Subtitles

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/multimedia_and_embedding/video_and_audio_content/test_your_skills_colon__multimedia_and_embedding`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Video_and_audio_content/Test_your_skills:_Multimedia_and_embedding
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/multimedia_and_embedding/video_and_audio_content/test_your_skills_colon__multimedia_and_embedding/index.html
* Last commit: https://github.com/mdn/content/commit/88b8dc61828f0c111b5eda4197921dcf153f3b0f
* Document last modified: 2020-12-15T16:53:05.000Z

</details>

**Comment by Harishdev10** [comment]
I am sorry guys, this is the first time I am posting something here. Unfortunately I uploaded the image twice. Please forgive

**Comment by chrisdavidmills** [comment]
Hi @Harishdev10 ! No need to apologise. You are welcome here.

Looking at your screenshot, it looks like you've got a problem because in your `<video>` element, you are writing the `width` and `height` attributes incorrectly. The values should have quote marks around them, and no units or semi-colons, i.e.

```
<video controls autoplay loop width="320" height="240">
```

It does get a bit confusing that you need to write this information differently in HTML versus CSS.

Also, the best place to post questions and requests for assessment is our learning forum: see https://discourse.mozilla.org/c/mdn/learn/250

All the best of wishes, and good luck!

**Comment by Harishdev10** [comment]
Hi Chris,

Thank you so much. This is very helpful.
