### ISSUE TITLE
void operator: onclick returning true and undefined are the same

### ISSUE THREAD

**Issue by ruojianll** [mdn/content#30212]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/void

### What specific section or headline is this issue about?

This ensures the return value of doSomething changing from undefined to true

### What information was incorrect, unhelpful, or incomplete?

> This ensures the return value of doSomething changing from undefined to true will not change the behavior of this code.

### What did you expect to see?

This sentence is not correct to the referenced code.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/void`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/void
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/void/index.md
* Last commit: https://github.com/mdn/content/commit/4c26e8a3fb50d06963b06017f51ce19364350564
* Document last modified: 2023-08-11T08:07:46.000Z

</details>

**Comment by hamishwillee** [comment]
@Josh-Cena I think this statement is correct in that the example wouldn't have side effects whether or not you use `void`.

The reason being that the button handler discards any returned value, so  whether the method returns true or undefined is irrelevant.

The fundamental point that if you really intend to return undefined you can be explicit about it is fine, but I'm at a loss for a real example where you'd assign the value if you intended the arrow to return undefined.
Thoughts?

**Comment by Josh-Cena** [comment]
> The reason being that the button handler discards any returned value

That's not entirely true: if you return `false` from `onclick`, it acts as if `preventDefault` is called. I'm very dissatisfied with how event handlers are documented nowadays, since the only relevant information I can find is https://developer.mozilla.org/en-US/docs/Web/API/Window/error_event#cancellation (which is written by myself!) (See also https://github.com/mdn/content/issues/18354)

However, I do believe returning `true` keeps the default behavior and is thus the same as `undefined`. In this case the simplest fix is to change the text to say "from `undefined` to `false`", but then we would need to link to some explanatory text on why that's different.

**Comment by hamishwillee** [comment]
Thanks @Josh-Cena - I wasn't aware of that. I have attempted to fix this in #30229.

> I'm very dissatisfied with how event handlers are documented nowadays, since the only relevant information 

Propose a broad fix then, or at least raise an issue. - the fact this is not obvious from reference is a problem.
