### ISSUE TITLE
Issue with "Common MIME types": Missing some common types

### ISSUE THREAD

**Issue by chunkybanana** [mdn/content#3021]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types

#### What information was incorrect, unhelpful, or incomplete?

MP4 (.mp4) is quite a common video format now, and should be added to the 'Common MIME types' list. 
Also quite common are YAML (.yml), CGI(.cgi), and Apple package installers(.pkg). CD audio (.cda) is on its way out, but will still be here for a bit longer, so maybe should be added.

I've probably missed a few here, and I'm not sure whether all of these should be added. 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/basics_of_http/mime_types/common_types`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/basics_of_http/mime_types/common_types/index.html
* Last commit: https://github.com/mdn/content/commit/cbe151a06d6e5b4d1fbb46081bd16e69ef4c1630
* Document last modified: 2020-09-15T15:48:51.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can add them :+1:

**Comment by hamishwillee** [comment]
FWIW almost every single file in the current list I have explicitly chosen to download at some point - essentially they are content formats that are intended to be run by a specific kind of software (or containers for content formats). It makes sense to serve their mime types because a browser can usefully do something with that - i.e. modify how it is downloaded, play it, or pass them onto the OS to handle.

On that basis I absolutely agree with .mp4. I somewhat agree with .pkg (and you could argue for AppImage, .msi etc etc. But I don't see a place for having to care to much about yaml or .cgi files - what is a browser every going to do with these/pass them to?

**Comment by CreaTorAlexander** [comment]
@hamishwillee sounds reasonable I will remove the .yaml and .cgi entry.
