### ISSUE TITLE
Incomplete information about click event

### ISSUE THREAD

**Issue by rahulbhai9** [mdn/content#30263]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Element/click_event

### What information was incorrect, unhelpful, or incomplete?

The page mentions that the click event can be fired by mouse or similar devices. It does not mention that the click event can be also triggered by a keyboard or by touching on a touch screen. This can be missleading for people. People may think that the click event is only associated with mouse and not with keyboard or touch screen.

### What did you expect to see?

The page should mention that the click event also can be triggered via keyboard or by touching on touch screen. Here is the link from the specifications which describes activation and behaviour of this event:[Activation and behaviour of event](https://w3c.github.io/uievents/#ref-for-click%E2%91%A2)

### Do you have anything more you want to share?

If allowed I would like to contribute this change by adding the missing information.

**Comment by dipikabh** [comment]
Hello @rahulbhai9, thanks for highlighting this point. You're right; the page currently focuses on mouse interactions.

The [note in the spec](https://w3c.github.io/uievents/#event-type-click) encourages authors "to use the `click` event type when defining activation behavior for custom controls, rather than other pointing-device event types such as mousedown or mouseup, which are more device-specific." and mentions that the `click` event "can be considered a device-independent event type for element activation."

Given this, it seems reasonable to update the `click event` page.

> If allowed I would like to contribute this change by adding the missing information.

Thanks for offering to contribute! You're welcome to open a PR to add the clarifying info. Looking forward to seeing your contribution.

**Comment by rahulbhai9** [comment]
Thanks @dipikabh I have submitted a PR (https://github.com/mdn/content/pull/30671) but I am receiving some lint errors. How do I fix it?

**Comment by dipikabh** [comment]
> but I am receiving some lint errors. How do I fix it?

Looks like @sideshowbarker took care of the lint errors. But for future: you can just accept the lint error suggestions and commit the changes. 

Thanks for submitting the PR, @rahulbhai9!
