### ISSUE TITLE
metaKey changed in Firefox 118

### ISSUE THREAD

**Issue by bdenhollander** [mdn/content#30638]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/metaKey

### What specific section or headline is this issue about?

KeyboardEvent: metaKey property

### What information was incorrect, unhelpful, or incomplete?

The warning about Firefox 48 may only apply until 117 since there was a change in behaviour in Firefox 118.

### What did you expect to see?

Expected to see the JavaScript test show meta key was not pressed when holding Windows key and clicking the button in Firefox 119.

### Do you have any supporting links, references, or citations?

https://bugzilla.mozilla.org/show_bug.cgi?id=1266437

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/keyboardevent/metakey`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/metaKey
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/keyboardevent/metakey/index.md
* Last commit: https://github.com/mdn/content/commit/cbfc561e5e577975a51acceadbd7d2fec9b8e45e
* Document last modified: 2023-11-14T13:08:57.000Z

</details>

**Comment by pepelsbey** [comment]
Hey! Nice catch :) It has been [fixed in Firefox 118](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/118#apis), and the warning needs to change. I’m not sure if mentioning Firefox 48 is still relevant. I’d rather turn it into “Before Firefox 118 it used to…” Also, I don’t think it’s important enough for a warning, a simple note would be enough.

Feel free to suggest a PR with a fix if you have time. Thanks!
