### ISSUE TITLE
`/docs/Glossary` should be a single page

### ISSUE THREAD

**Issue by junaga** [mdn/content#30661]
### MDN URL

https://developer.mozilla.org/en-US/docs/Glossary

### What information was incorrect, unhelpful, or incomplete?

The glossary terms are split across multiple webpages. This is not helpful at all.

### What did you expect to see?

The content should be on a single page, with URL fragment `id` navigations.

**Comment by Josh-Cena** [comment]
In the same spirit you could have claimed that each API interface should be one page instead of each method and property on its own page. The answer is we don't want 100k-line pages—that helps no one. People who read the glossary for `Inheritance` is highly unlikely to want to read `IMSC` but now their browser is forced to load the content of 200+ glossary entries. Plus, we have a very fixed page structure—each page has its own `See also`. Merging all pages means we have a bunch of `See also` subsections which is a net minus to our established information architecture.

**Comment by bsmth** [comment]
Hi @junaga - everyone participating in this project is expected to follow our Code of Conduct. Specifically, being rude or impolite when disagreements arise will not be tolerated. Please familiarize yourself with the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) and our [Open source etiquette](https://developer.mozilla.org/en-US/docs/MDN/Community/Open_source_etiquette) guidelines in the MDN Community docs. Thank you.

**Comment by teoli2003** [comment]
Locking.
