### ISSUE TITLE
Issue with "HTMLElement: pointerdown event": Inaccurate Safari Info

### ISSUE THREAD

**Issue by timbomckay** [mdn/content#3076]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/pointerdown_event

#### What information was incorrect, unhelpful, or incomplete?

It says Safari doesn't support this event.

#### Specific section or headline?

Browser Compatibility

#### What did you expect to see?

YES

#### Did you test this? If so, how?

Created a codepen and assigned the listener to the window and then a button element, received a console log each time. Also switched the UA to iPhone and received the same log.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/htmlelement/pointerdown_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/pointerdown_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlelement/pointerdown_event/index.html
* Last commit: https://github.com/mdn/content/commit/63c69f3c933acbea9bfb24d359a7d2ffdb3c0bea
* Document last modified: 2021-02-19T19:51:22.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks @timbomckay 

@chrisdavidmills I'll take this one because I'm very interested in events :-). This will move to the BCD. 

This seems very likely https://webkit.org/blog/10247/new-webkit-features-in-safari-13-1/
There is also this bug which implies that it should be fired, but is not in some cases: https://bugs.webkit.org/show_bug.cgi?id=219188 , and pointer events level 2 are supported as well, https://webkit.org/status/#specification-pointer-events-level-2 so it would be very odd for pointer down not to work. 

Further, the info on Opera is wrong since that depends on chrome which does support pointerdown.

**Comment by hamishwillee** [comment]
Fixed by https://github.com/mdn/browser-compat-data/pull/9455

**Comment by hamishwillee** [comment]
Fixed. The PR for this is merged, and should appear live at some point.
