### ISSUE TITLE
Content bug: cookies.onChanged not reflecting not supported (but doc state differently)

### ISSUE THREAD

**Issue by khalyomede** [mdn/content#3080]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/onChanged

## Specific page section or heading?

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/onChanged#browser_compatibility

## What is the problem?

This API seems to not work on Chrome. I did not tested it on other browsers, but looking at the few information on Stackoverflow, it seems this API is deprecated.

## What did you expect to see?

The compatibility table shows the browser that supports it or not.

## Did you test this? If so, how?

By running this code in the browser (Google Chrome) console:

```
browser.cookies
```

It returns

```
Uncaught ReferenceError: browser is not defined
```

**Comment by RNabla** [comment]
Before we jump into specific javascript API let's start with WebExtensions.
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/

"JavaScript APIs for WebExtensions can be used **inside the extension's background scripts**..."

> Did you test this? If so, how? 
> By running this code in the browser (Google Chrome) console:

It will not work as you are testing from console. 

From the section Browser API differences you can read:

"Note that this is different from Google Chrome's extension system, which uses the **chrome** namespace instead of **browser**, and which uses callbacks instead of promises for asynchronous functions. "

So it should work if you would have executed code inside extension and used chrome namespace instead of browser.

Javascript API for WebExtensions exists in Firefox and Chromium based browsers; they are similar in terms of operations, however they differ in how they are implemented, e.g. API in Firefox is based on promises, where chromium based browsers are using callbacks.

So the compatiblity table is fine - there is cookies API for Chrome - https://developer.chrome.com/docs/extensions/reference/cookies/

For more info see:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Chrome_incompatibilities
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs 

If you want to target firefox/chromium browsers and use promise based API than probably polyfills are a way to go, e.g:
https://github.com/mozilla/webextension-polyfill

From my experience - I wrote simple extension for firefox using native JavaScript API and extension worked flawlessly on firefox desktop and firefox for android about one year ago. But some time later my friend (Chrome user) also wanted to use this extension so I ended up using polyfills to achieve that.

**Comment by khalyomede** [comment]
Hello @RNabla , thanks for this detailed answer!

Regarding the information you sent me, I understand this is something specific for web extensions. In my use case, I have an e-shop website, and I wanted to display a cookie banner whenever the user changes its cookie policy through his web browser (e.g. displaying "Oops, your cookies are not enabled. Your cart will not be saved from now." message when the cookies are disabled for the page).

I assume this requires to be in a web extension context, and will not work for a regular Javascript, am I right?

**Comment by caitmuenster** [comment]
Thanks so much, @RNabla! 

@khalyomede, you may want to ask for help with your particular use case on our [community forum](https://discourse.mozilla.org/c/add-ons/35), where a few more people familiar with extension development may be able to offer more support.
