### ISSUE TITLE
Information about how to use -webkit-line-clamp independent of -webkit-box-orient, and its future

### ISSUE THREAD

**Issue by tannermann** [mdn/content#30842]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp

### What specific section or headline is this issue about?

-webkit-line-clamp

### What information was incorrect, unhelpful, or incomplete?

There is no warning about `-webkit-line-clamp` being deprecated but in order to use it you must also use `-webkit-box-orient`, which is described as "[Non-standard and deprecated](https://developer.mozilla.org/en-US/docs/Web/CSS/box-orient)". What is the future of `-webkit-line-clamp`?

### What did you expect to see?

Information about the roadmap of `-webkit-line-clamp` and how it might be used independently of `-webkit-box-orient`, which is deprecated.

### Do you have any supporting links, references, or citations?

- https://developer.mozilla.org/en-US/docs/Web/CSS/box-orient
- https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp

### Do you have anything more you want to share?

I looked on caniuse.com and it has `box-orient` listed as usable only with the `-moz-` prefix but it also seems to work with the `-webkit-` prefix in Firefox.

https://caniuse.com/?search=box%20orient

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/-webkit-line-clamp`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/-webkit-line-clamp/index.md
* Last commit: https://github.com/mdn/content/commit/44cf523714745d626317192bfbe849b47144f3ab
* Document last modified: 2023-11-10T13:26:54.000Z

</details>

**Comment by tannermann** [comment]
Hi @anushatomar13, thanks for showing interest in this issue. I don't think I have permissions in this repo to assign it but maybe you can get the attention of someone who can or just work on a PR that mentions this topic. Cheers 😃

**Comment by Josh-Cena** [comment]
Here's my understanding:

- `-webkit-line-clamp` is not going anywhere. It's fully specified and will be kept for compatibility. All browsers support it and will support it when `line-clamp` becomes real.
- `box-orient` is non-standard because it's not in any specification. The feature it was originally intended for is now fully subsumed by flexbox. However, `-webkit-line-clamp` _requires_ `-webkit-box-orient: vertical; display: -webkit-box` to work, and there's no way to get rid of this behavior. You can just think of them as "side-effects" of applying `-webkit-line-clamp`.
- `-webkit-box-orient` is supported in Firefox. I think caniuse is wrong or at least misleading here, but our own compatibility table at the page bottom shows the right status.
- This is always going to be how legacy behavior works: browsers do whatever they want and now the spec tries to find the greatest common denominator that all implementations agree on.

Given all this, what do you think we can add to these pages?

**Comment by Josh-Cena** [comment]
You are right. `line-clamp` would definitely not have dependency on `-webkit-box-orient`. The spec for `-webkit-line-clamp` is just a documentation for what browsers do, with no intention for browsers to change their current behavior.

I think one or two sentences that say:

(a) `-webkit-line-clamp` require the other legacy properties to work, so you need to add them despite them being deprecated and non-standard  
(b) `line-clamp` does not require any of these legacy stuff 

Should suffice.
