### ISSUE TITLE
Animation example works in Chrome but not FF

### ISSUE THREAD

**Issue by its-all-waves** [mdn/content#30882]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog#animating_dialogs

### What information was incorrect, unhelpful, or incomplete?

You might want to test every example on this page. Make sure you test both the page's examples and the same examples launched in the "play" page. QA must have missed this article.

### What did you expect to see?

Animation.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/dialog`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/dialog/index.md
* Last commit: https://github.com/mdn/content/commit/bed59f268d5e299beb538e435f08c4f4ce685980
* Document last modified: 2023-11-20T15:37:12.000Z

</details>

**Comment by Josh-Cena** [comment]
We never promised that every example will work in every browser. It is the reader's responsibility that an example they wish to use in their project will work in every target browser. A browser not making an example work is the browser's fault, because MDN documents the spec, and if a browser faithfully implements the spec, the example will behave as intended. The reason for this is that Firefox doesn't support the [`@starting-style`](https://developer.mozilla.org/en-US/docs/Web/CSS/@starting-style) rule.

**Comment by its-all-waves** [comment]
To be clear, you're saying that you can't promise the examples in Mozilla's own docs (MDN) will work in Mozilla's own browser, Firefox (120.0.1 (64-bit))?

**Comment by Josh-Cena** [comment]
MDN is not "documentation for Firefox". We have a section for Firefox releases, but the web documentation is for the web, and as soon as one browser implements it, we document it, even if it doesn't work in Firefox yet.

**Comment by its-all-waves** [comment]
Ok... Just FYI, I believe most people would assume that if you put an interactive example on your own website, that it will function on your website. Why intentionally put a broken interactive example on your site?

**Comment by its-all-waves** [comment]
Oh, I thought the point of a live example is to show you what the documentation is attempting to communicate in words. Thanks for explaining.
