### ISSUE TITLE
Issue with "static": …

### ISSUE THREAD

**Issue by bergus** [mdn/content#309]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static

#### What information was incorrect, unhelpful, or incomplete?

Static class fields should not yet be documented without a disclaimer.

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static#Using_static_members_in_classes

#### What did you expect to see?

The same disclaimer that is in the [public class fields](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Public_class_fields) documentation:

> This page describes experimental features.
> 
> Both Public and private field declarations are an experimental feature (stage 3) proposed at TC39, the JavaScript standards committee.
> 
> Support in browsers is limited, but the feature can be used through a build step with systems like Babel. See the compat information below.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/classes/static`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/classes/static/index.html
* Report started: 2020-12-16T14:16:55.769Z

</details>

**Comment by Elchi3** [comment]
Hm, so `static` itself (not as a class field) is well supported and that's what https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static describes.

> Static class fields should not yet be documented without a disclaimer.

Right, but these are documented on https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Public_class_fields which has the banner.

**Comment by bergus** [comment]
Yes, `static` *methods* are standardised just fine, but https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static unfortunately describes all kinds of static members, both methods and "properties" (it doesn't even use the term "public field"). It doesn't even link the pages about method definitions or public class fields.
That's why we need a banner on this page as well (of course, only for static fields). Students are already confused because they read MDN but then their ES2020 tooling won't accept the syntax they've seen.

**Comment by sideshowbarker** [comment]
It seems we kept this issue open so long that the problem in the issue description managed to get resolved without us needing to do anything — because, in April:

* The Class Fields proposal [reached Stage 4 and was merged into the ES spec itself](https://github.com/tc39/proposals/blob/master/finished-proposals.md).
* Safari 14.1 shipped with full support for all features in the proposal.

So the disclaimer at the top of https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Public_class_fields is no longer accurate or necessary — because these features are no longer experimental or proposed, and because it’s no longer true that “support in browsers is limited”; instead in fact, all browser engines now have support for the features.

So I opened https://github.com/mdn/content/pull/5850 to remove the disclaimer from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Public_class_fields.

@bergus Would you agree that adding a disclaimer about static class fields to the https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static at this point is no longer necessary? If not, what wording would you suggest the disclaimer should have.

Otherwise, I think https://github.com/mdn/content/issues/309#issuecomment-755413967 points out some problems with the actual content of the `static` article that should be be fixed - so we could repurpose this issue as a request to get those content refinements made.

So @bergus it’d be great to get your comments here about what you’d like to have happen for this issue at this point.
