### ISSUE TITLE
Consider renaming Cache API's use of the word "request" to "resource" to align with fetch.

### ISSUE THREAD

**Issue by jfbrennan** [mdn/content#30974]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Cache/add

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/API/Cache/add#request

### What information was incorrect, unhelpful, or incomplete?

I'm reporting via the docs for `cache.add(request)`, but really this would apply to all uses of the name "request" in all the Cache API method docs.

There's nothing incorrect, but I think using the name "resource" instead would align with the naming used in the [fetch docs](https://developer.mozilla.org/en-US/docs/Web/API/fetch#resource). And I think that name - "resource" - is a better name because it helps communicate the nuance that your arg doesn't have to be a `Request` object, it can be a string or URL object too.

### What did you expect to see?

The name "resource", like fetch.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/cache/add`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Cache/add
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/cache/add/index.md
* Last commit: https://github.com/mdn/content/commit/1f216a70d94c3901c5767e6108a29daa48edc070
* Document last modified: 2023-04-07T06:13:50.000Z

</details>

**Comment by skyclouds2001** [comment]
Just a fact, in spec https://w3c.github.io/ServiceWorker/#dom-cache-add, the `Cache.add()` is using the name `request`

and `request` is widely used in many other methods in `Cache` interface and `CacheStorage` interface

**Comment by skyclouds2001** [comment]
For consistency reasons, it might be better to still use `request`

**Comment by jfbrennan** [comment]
>really this would apply to all uses of the name "request" in all the Cache API method docs.

**Comment by dipikabh** [comment]
Hi @jfbrennan, thank you for raising your concerns about the potential inconsistency in parameter names. We looked at the instances you pointed out and their corresponding specs.

I am quoting two of your statements here because they are pertinent to this discussion and probably also answer your question:

https://github.com/mdn/content/issues/30974#issuecomment-1856242121:
> Perhaps fetch should not use "resource" and instead use "request" like Cache docs? 

Issue description:
> And I think that name - "resource" - is a better name because it helps communicate the nuance that your arg doesn't have to be a Request object, it can be a string or URL object too.

It seems the answer to your question about whether `fetch` should use `request` as the parameter name is present in your initial description. We agree that `resource` is a better choice for `fetch` to clarify the types of arguments allowed (not just the `request` object).

Parameter names are essentially variable names and understanding their descriptions is what's important. While we do aim to align with specifications, we also would like to avoid confusion/ambiguity (specifications can lack consistency sometimes). Given this, we plan to keep the parameter name in `fetch` as `resource`.

Hope this addresses your query. I'll be closing this issue now, but please feel free to reach out if you have further feedback or questions.

**Comment by jfbrennan** [comment]
Thanks @dipikabh for the response, but please re-read the summary: "Consider renaming Cache API's use of the word "request" to "resource" to align with fetch." 

I believe `fetch` should keep the param name `resource` because that's a good name. The issue is that same exact type of param is called `request` in the Cache API docs. It should be renamed `resource` to match fetch because Cache API takes the same types as fetch does, not just a Request.

Hopefully that clarifies it: In Cache API docs rename `request` to `resource`.

**Comment by dipikabh** [comment]
Following the thread here, I somehow got the impression that there was a request to update the `fetch` parameter name. Thanks for clarifying.

The `request` parameter name for the Cache methods actually aligns with the specification, so sticking to `request` on those pages makes sense (even though `resource` is more unambiguous).

I know it looks like we're we're playing by different rules in different spots, but that's the best approach for these pages right now. I would also reiterate to focus on the parameter descriptions. This way, even if the parameter names are different across pages, the descriptions can help remove any confusion. If you're interested or if it'll help, we could make sure that the descriptions are consistent for such parameters that have the same purpose but different names.
