### ISSUE TITLE
Step 3 of Using Pyhton

### ISSUE THREAD

**Issue by sebastienbellini** [mdn/content#30978]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Tools_and_setup/set_up_a_local_testing_server

### What specific section or headline is this issue about?

Using Python

### What information was incorrect, unhelpful, or incomplete?

I may be my mistake but I dont get the part were the step 3 says "navigate to the directory that your example is inside" I have no clue as to what example is mentioned in this part ? should I already have a testing webfile that I dont know about ? did I miss something ?

### What did you expect to see?

A clear instruction as to what the exemple is

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Tools_and_setup/set_up_a_local_testing_server

### Do you have anything more you want to share?

No

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/common_questions/tools_and_setup/set_up_a_local_testing_server`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Tools_and_setup/set_up_a_local_testing_server
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/common_questions/tools_and_setup/set_up_a_local_testing_server/index.md
* Last commit: https://github.com/mdn/content/commit/bb026bcb88b7f45374d602301b7b0db5a49ff303
* Document last modified: 2023-07-03T10:12:35.000Z

</details>

**Comment by hamishwillee** [comment]
> did I miss something ?

Yes. 

If you start from the top of the page it says "Throughout most of the learning area, we tell you to just open your examples directly in a browser — this can be done by double-clicking the HTML file, dragging and dropping it into the browser window,"

The page is about how to run the learn examples.

I've made this generic in https://github.com/mdn/content/pull/31011, but I'm closing this whether or not it goes in because this is "Not a defect".

Thanks for taking the time to post though!
