### ISSUE TITLE
`hgroup` now has `role="group"`

### ISSUE THREAD

**Issue by ThePhilgrim** [mdn/content#31064]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hgroup

### What specific section or headline is this issue about?

The accessibility note below the section [Try it](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hgroup#try_it)

### What information was incorrect, unhelpful, or incomplete?

There has been a lot of work done around the `<hgroup>` tag that might warrant an update of the accessibility warnings on this MDN page. See below.

It says `<hgroup>` has been removed from the W3C HTML specification, but it seems this has been [added again](https://www.w3.org/TR/2011/WD-html5-20110405/sections.html#the-hgroup-element)

Quoted from an a11yproject [article](https://www.a11yproject.com/posts/how-to-accessible-heading-structure/#hgroup):

> Update August 1, 2022: Steve Faulkner proposed a way to introducehgroup again, which is promising, in:
> [Subheadings, subtitles, alternative titles and taglines in HTML](https://www.tpgi.com/subheadings-subtitles-alternative-titles-and-taglines-in-html/)
> 
> Until browsers add the information themselves do:
> 
> Add role="group" and aria-roledescription="Heading group" as attributes to the hgroup element.
> Add the subtitles in a paragraph (not a heading) <p aria-roledescription="subtitle">.
> Then all information about the structure and connection of the headings group is given for assistive technology in the accessibility tree.

### What did you expect to see?

A recommendation on how one can ensure their usage of `<hroup>` is accessible.

### Do you have any supporting links, references, or citations?

[W3C PR on element mapping for `<hgroup>`](https://github.com/w3c/html-aam/pull/398#issue-1218793599)
[Related PR on W3C](https://github.com/w3c/html-aam/pull/398#issuecomment-1184581607)

Topic stumbled upon from [this article](https://www.tpgi.com/subheadings-subtitles-alternative-titles-and-taglines-in-html/)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/hgroup`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hgroup
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/hgroup/index.md
* Last commit: https://github.com/mdn/content/commit/fbb5b308788bdb63e9b2a2d010f49510f48b2e03
* Document last modified: 2023-12-09T03:36:42.000Z

</details>

**Comment by dipikabh** [comment]
I looked into the reported issue and gathered the following bits. The "Note" on the [`hgroup`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hgroup) page (added via [#30856](https://github.com/mdn/content/pull/30856/files)) and in the [Heading content](https://developer.mozilla.org/en-US/docs/Web/HTML/Content_categories#heading_content) section will need to revisited in light of the changes made by this W3C [pull request](https://github.com/w3c/html-aam/pull/398/files) to improve the accessibility of the `<hgroup>` element.

Since implementation bugs on various browsers (https://github.com/w3c/html-aam/pull/398#issue-1218793599) to change `role="generic"` to `role="group"` are still in open state, we cannot document the role change yet.
We can probably remove this bit from the note though: "It was removed from the W3C HTML specification but is still part of the WHATWG specification".

**Comment by Josh-Cena** [comment]
Fixed by https://github.com/mdn/content/pull/32214. @dipikabh it seems the role change is already implemented in FF but there's no dev-doc-needed on the bug.

**Comment by dipikabh** [comment]
Thanks for the nudge on this one, @Josh-Cena. Would you like to review https://github.com/mdn/content/pull/34647?

**Comment by Josh-Cena** [comment]
Thanks for taking this up! I think this would need BCD data too, and probably keep a note about legacy behavior. Also I would defer to an HTML reviewer for the content.
