### ISSUE TITLE
What Is The Third Type Of List?

### ISSUE THREAD

**Issue by TinotendaMakuza** [mdn/content#31201]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/HTML_text_fundamentals

### What specific section or headline is this issue about?

Lists

### What information was incorrect, unhelpful, or incomplete?

Under the 'Lists' heading we are told there are 3 types of lists. Upon inspection, we are only told about two. The subheadings are also only for 2. 
It might be worthy to note that an unknown element dt and dl (EDIT:if i put them as tags they distort my text) were introduced in the final example without any explanation. that might be it.

Otherwise, great article!

### What did you expect to see?

A third type of list

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html/html_text_fundamentals`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/HTML_text_fundamentals
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/introduction_to_html/html_text_fundamentals/index.md
* Last commit: https://github.com/mdn/content/commit/8d0cbeacdc1872f7e4d966177151585c58fb879e
* Document last modified: 2023-08-02T17:32:22.000Z

</details>

**Comment by wbamberg** [comment]
Thank you for filing! Yes, it is `<dl>`, and yes it should be documented there.

> (EDIT:if i put them as tags they distort my text)

That's because the GitHub comment box accepts (some) HTML, so if you type HTML it gets interpreted as HTML not text. You can escape the HTML tag by typing "\\" before it, like this:

 \\\<dl>

... or use [code formatting](https://spec.commonmark.org/0.30/#code-spans), like this:

\`\<dl>\`
