### ISSUE TITLE
isNan for empty arrays

### ISSUE THREAD

**Issue by Janspeed** [mdn/content#31249]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

An empty object return true with isNan but an empty array returns false. I kind of think that little detail should be mentioned. If you toString and empty array you get undefined. But if you isNan undefined you get true. Still an array returns false.

### What did you expect to see?

A red flag and highlighted example of arrays.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/isnan`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/isnan/index.md
* Last commit: https://github.com/mdn/content/commit/e5f0e1070962ee4a595369218d85481542ec7ded
* Document last modified: 2023-07-30T22:50:29.000Z

</details>

**Comment by teoli2003** [comment]
There is a link called "surprising results" in the description, but I agree it is worth an extra line in the examples there, as `isNaN({}}` has one:
![Capture d’écran 2023-12-23 à 11 22 34](https://github.com/mdn/content/assets/1466293/a6459a5a-ccef-42e6-bd51-6ace4e668f6d)

Would you like to try to create a PR?

**Comment by Janspeed** [comment]
On a deadline for new year and then probably following by putting out fires. So wont have time to do it. I also just wasted a lot of time troubleshooting which lead me to this (imo issue) in isNan. I just dont really see the reason of converting an empty array to a valid number. It isnt even doing a normal .toString() before trying.
________________________________

**Comment by Josh-Cena** [comment]
> I just dont really see the reason of converting an empty array to a valid number. It isnt even doing a normal .toString() before trying.

This page says that the input is "coerced to a number" both in the return value and description section. You can understand why by reading the linked algorithm

Both objects and arrays convert to primitives by getting converted to strings, because neither one has a custom `@@toPrimitive` or `valueOf()`. `{}` becomes `"[object Object]"` and `[]` becomes `""` (read `Object.prototype.toString()` and `Array.prototype.toString()`). Then, number coercion coerces the string to a number, and `""` becomes `0` which is also mentioned in the number coercion algorithm:

> Empty or whitespace-only strings are converted to 0.

While `"[object Object]"` becomes `NaN` because it does not contain a valid number. Therefore there's nothing "surprising" here: everything is a natural corollary of how the coercion algorithm is specified.

If you cannot manage your types well and make sure you stay away from these inconsistencies, consider (a) use `Number.isNaN` instead (b) use TypeScript.

**Comment by teoli2003** [comment]
An empty array is first converted to a string, then to a `Number`

```
[] -> "" -> 0
```

So `isNaN([])` is `false` as 0 is a `Number`.

For an object, the method `[Symbol.toPrimitive]()` is used if it exists; if not, `valueOf()` is used if it exists; else, `toString()` is called (and it has a default implementation on an object).

On an empty object, the two first doesn't exist, so the default `toString()` is called and returns `[object Object]`, and `isNaN("[object Object]")` returns `true`.

Cumbersome, but that's how it has done (likely not voluntarily) and has to stay so because it will break backward compatibility. Strictly speaking, the same steps are performed on arrays and objects, but the default implementation of `toString()` is quite different.

The trick is to think about these double steps: first, convert to a string, then convert the string to whatever you need. There is no direct coercion.

Type coercion can be kinda brutal.

**Comment by BartoszKlonowski** [comment]
@teoli2003 I believe this issue should already be closed by #31289, however, it was not linked before merging (as the description is rather poor).
Let me know if my understanding is correct.
