### ISSUE TITLE
Vibrate Not causing issue

### ISSUE THREAD

**Issue by chanx** [mdn/content#31251]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/vibrate

### What specific section or headline is this issue about?

No Effect on unsupported Device

### What information was incorrect, unhelpful, or incomplete?

On Paragraph 1 there is message "If the device doesn't support vibration, this method has no effect." I found problem on iOS Safari that can cause script to halt and UI Freeze. so please include that warning.

### What did you expect to see?

Change in warning, should include iOS warning.
So must check this feature is available or not before firing this command.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/navigator/vibrate`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/vibrate
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/navigator/vibrate/index.md
* Last commit: https://github.com/mdn/content/commit/ef75c1741b450c2331204be5563ee964ad5f4c48
* Document last modified: 2023-04-07T06:16:45.000Z

</details>

**Comment by Josh-Cena** [comment]
"Device doesn't support vibration" is different from "browser doesn't support the API". You have to feature-test every API because if the method doesn't exist you will simply be calling `undefined` which is a `TypeError`. This has nothing to do with vibration API in particular—it's a general programming issue.
