### ISSUE TITLE
Consider remove `SecurePaymentConfirmationRequest` dictionary

### ISSUE THREAD

**Issue by skyclouds2001** [mdn/content#31287]
### MDN URL

'

### What information was incorrect, unhelpful, or incomplete?

added in #30439 and previously #28705 

but I wonder if this `SecurePaymentConfirmationRequest` dictionary should be kept in a separate page, because the structure seems to be only used in `PaymentRequest()` constructor

### What did you expect to see?

as above

### Do you have any supporting links, references, or citations?

the spec https://w3c.github.io/secure-payment-confirmation/

mdn content update #28705 #30439 

BCD data update https://github.com/mdn/browser-compat-data/pull/20583 and https://github.com/mdn/browser-compat-data/pull/21460

mdn task https://github.com/mdn/mdn/issues/421

**Comment by wbamberg** [comment]
Well since I suggested adding this, I'll explain why I did. https://developer.mozilla.org/en-US/docs/Web/API/PaymentRequest/PaymentRequest#parameters is already a ferociously complicated section, and adding the contents of https://developer.mozilla.org/en-US/docs/Web/API/SecurePaymentConfirmationRequest inline into it would IMO make this really hard for people to follow. So I think the docs are more usable with it split out into a separate page.

**Comment by teoli2003** [comment]
I'm not against keeping this page.

Do we have a place to list dictionaries we decided to keep? (and the one we still have to remove?) (Maybe @hamishwillee knows it)

**Comment by skyclouds2001** [comment]
I wonder if it is possible to add a new `page-type` key like `web-api-dictionary`, to separate from `web-api-interface`. CUrrently it is not easy to separate pages of dictionary from interface

**Comment by teoli2003** [comment]
Yes, we want to do this (only on dictionaries we decide to keep).

I don't remember what we need to do to add it. @wbamberg will.

**Comment by wbamberg** [comment]
We discussed this, and didn't, because we don't treat interfaces differently from dictionaries, and because we don't think user see them as different things. And sometimes the distinction can feel quite artificial: for example, `PerformanceEntry` is technically an interface because it is JSON-serializable, so it defines a `toJSON()` method as a helper for `JSON.stringify()`. But `PerformanceEntry` _feels_, to me at any rate, to be essentially just data, like a dictionary.

I'm just providing this to explain that we have considered this before, and this was the reasoning. Maybe we should change. I don't feel particularly strongly. Usually we have page types when we want to treat things differently, and in particular if we want them to have different page templates. Maybe if dictionaries never have BCD, that amounts to a big enough difference.

> I don't remember what we need to do to add it. @wbamberg will.

We add it to https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types/Page_type_key#web_api_page_types and, ideally, write a corresponding template.
