### ISSUE TITLE
Issue with "<style> in <body>": Real word vs Spec

### ISSUE THREAD

**Issue by guettli** [mdn/content#3137]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style

#### What information was incorrect, unhelpful, or incomplete?

I see a huge difference between the specification and the real world.

According to the specs `<style>` should be in the `<head>`:

> The <style> element must be included inside the `<head>` of the document. 

But just look at amazon.com. There are 11 style tags in the body.

If you ask me: I think the spec should allow the style tag everywhere.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/style`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/style/index.html
* Last commit: https://github.com/mdn/content/commit/c40f133b4ed8474730029e68a397aaebb042266b
* Document last modified: 2021-03-01T15:30:53.000Z

</details>

**Comment by rachelandrew** [comment]
Hi @guettli this isn't the place to raise an issue against the spec. MDN documents the specifications rather than informs them.

My understanding with `<style>` elements outside of the head is that browser do typically support them but they can have negative impacts on performance creating a FOUC (flash of unstyled content) etc. A quick search brought back this old issue here: https://github.com/whatwg/html/issues/1605

So I'm not sure there is anything to change on MDN right now.

**Comment by chrisdavidmills** [comment]
Yup, let's close this.
