### ISSUE TITLE
Wrong Visulation of Display Property

### ISSUE THREAD

**Issue by viktiwari12** [mdn/content#31437]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/display

### What specific section or headline is this issue about?

First section - Try it! 

### What information was incorrect, unhelpful, or incomplete?

In the display section, one of the properties is Display: block;

The corresponding visual effect is not what it should be. 
Instead of being a display block, the boxes are being displayed inline. 
![Screenshot 2024-01-01 at 12 27 38 AM](https://github.com/mdn/content/assets/59365222/b452760e-c128-40d2-88ca-bedead3a3c3d)

### What did you expect to see?

The inner boxes- one, two, three- should be displayed top to bottom, not left to right!

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/display`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/display
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/display/index.md
* Last commit: https://github.com/mdn/content/commit/b9db4e51b6f1cddba3af708643fc9804849d61c2
* Document last modified: 2023-12-26T21:19:48.000Z

</details>

**Comment by wbamberg** [comment]
The box which is getting `display` assigned is the outer box: the one with the blue border - and not the boxes with "One"/"Two"/"Three" in them.

That said, I can see how this is confusing. Perhaps the text content of the inner boxes could indicate that they are the contents of the target?

This should be transferred to https://github.com/mdn/interactive-examples, but let's leave it here for a bit since this repo gets more eyes, and maybe people will have good idea for how to make the example clearer.

**Comment by OnkarRuikar** [comment]
> That said, I can see how this is confusing. Perhaps the text content of the inner boxes could indicate that they are the contents of the target?

I've created a PR https://github.com/mdn/interactive-examples/pull/2710

> This should be transferred to https://github.com/mdn/interactive-examples, but let's leave it here for a bit since this repo gets more eyes

Would be nice if we bring example repos under `mdn/content`.
