### ISSUE TITLE
Add indication to the formal syntax of `transform:translate()` that would distinguish which numbers are for the X and Y planes.

### ISSUE THREAD

**Issue by JHunnicutt** [mdn/content#31582]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/translate

### What specific section or headline is this issue about?

Formal Syntax

### What information was incorrect, unhelpful, or incomplete?

It would be helpful to distinguish which of the two numbers is for the X plane and which one is for Y from the Formal Syntax area. This page does contain brief references to which number is for which plane, but these are easily missed if one is trying to skim the page for info.

### What did you expect to see?

`translate(<tx-length-percentage>, <ty-length-percentage>?)`

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/transform-function/translate`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/translate
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/transform-function/translate/index.md
* Last commit: https://github.com/mdn/content/commit/88e01e6f934ea5f2413cecfab1b5112cf819ba09
* Document last modified: 2023-08-23T10:21:57.000Z

</details>

**Comment by wbamberg** [comment]
Thank you for filing!

But I don't think we should do this: the formal syntax is, well, formal: its components refer to types that exist in the CSS specifications. `<length-percentage>` refers to a type in CSS (https://drafts.csswg.org/css-values/#mixed-percentages), and that's what the syntax of `translate()` is defined as (https://drafts.csswg.org/css-transforms/#funcdef-transform-translate).  but `<tx-length-percentage>` obviously isn't a type in CSS. So I don't think we should make this change.

Also, formal syntax is only about syntax: which values you can stuff into the property. It doesn't say anything about semantics, which is the distinction this issue is asking for.
