### ISSUE TITLE
`<input type="month">` - `IDL attributes` : missing `valueAsDate` and `valueAsNumer`

### ISSUE THREAD

**Issue by Malix-off** [mdn/content#31590]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/month

### What specific section or headline is this issue about?

[Technical Summary](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/month#technical_summary)

### What information was incorrect, unhelpful, or incomplete?

About `<input type="month">` : `IDL attributes` - missing `valueAsDate` and `valueAsNumer`

### What did you expect to see?

About `<input type="month">` : `IDL attributes` - missing `valueAsDate` and `valueAsNumer`

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/input/month`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/month
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/month/index.md
* Last commit: https://github.com/mdn/content/commit/e04d8d2766c468f149445c0bf438d09f9b2d188c
* Document last modified: 2023-06-13T08:10:47.000Z

</details>

**Comment by queengooborg** [comment]
@hamishwillee This was not a BCD issue.  The reporter is referring to the " row within the Technical Summary section of the page:

<img width="759" alt="Screenshot 2024-01-08 at 15 52 48" src="https://github.com/mdn/content/assets/5179191/2e6fa5cc-8870-4a67-b2d3-73e0375fb9e1">

BCD would not list these under the HTML element data because they are API attributes, not HTML element attributes, so they would not appear in the browser compatibility tables on these pages.

**Comment by Malix-off** [comment]
Indeed, sorry for not clarifying earlier, I had no idea what "BCD" meant

**Comment by hamishwillee** [comment]
Curses. Thanks all - I was confused by this. @Malix-off - would you like to add those attributes?

**Comment by Malix-off** [comment]
> Curses. Thanks all - I was confused by this. @Malix-off - would you like to add those attributes?

Yep, if you allow PRs.
I'm busy bc of exams, but will eventually open the PR for review before Thursday afternoon UTC

**Comment by Malix-off** [comment]
@hamishwillee see #31639
