### ISSUE TITLE
Documentation Issue /  Should provide more context

### ISSUE THREAD

**Issue by Saoming** [mdn/content#31666]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics/xor

### What specific section or headline is this issue about?

This is a problem since we're moving away from atomics. especially if you run the script it says Error: SharedArrayBuffer is not defined.

### What information was incorrect, unhelpful, or incomplete?

We're not using Atomics anymore... instead, we're using [^](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_XOR)

### What did you expect to see?

Explanation of why we are moving away from this and why it doesn't work.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/atomics/xor`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics/xor
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/atomics/xor/index.md
* Last commit: https://github.com/mdn/content/commit/6a0f9553932823cd0c4dcf695d4b4813474964fb
* Document last modified: 2023-04-12T16:34:04.000Z

</details>

**Comment by Josh-Cena** [comment]
I think you are missing the purpose of `Atomics`. If you don't need `SharedArrayBuffer` (because you don't even have an environment to make shared memory available), you 100% do not need `Atomics`. If you haven't discovered a use case, you don't need to read its documentation at all. `Atomics` is only meant to complement shared memory tasks, and for normal computation you should always–without nuance—use `^`. I don't know what you mean by "moving away from this"; perhaps https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer#security_requirements would provide some more context.
