### ISSUE TITLE
Incorrect information in the Try It example

### ISSUE THREAD

**Issue by swardinfo** [mdn/content#31710]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main

### What specific section or headline is this issue about?

Try it - example

### What information was incorrect, unhelpful, or incomplete?

I know I'm just being a pedant and this has nothing to do with how to use code but as someone who has to constantly remove geckos from my house in Australia, the following statement is simply not true. We have at least 8 native and 1 invasive gecko, the Asian House Gecko..

"Geckos are a group of usually small, usually nocturnal lizards. They are found on every continent except Australia."

### What did you expect to see?

"Geckos are a group of usually small, usually nocturnal lizards. They are found on every continent >>**including**<< Australia."

### Do you have any supporting links, references, or citations?

https://www.dcceew.gov.au/sites/default/files/env/pages/dc11235d-8b3b-43f7-b991-8429f477a1d4/files/27-fauna-2a-squamata-gekkonidae.pdf

### Do you have anything more you want to share?

![Newly hatched gecko in my house](https://github.com/mdn/content/assets/86252183/37748e74-d9b5-403d-ab28-5942bc79b71c)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/main`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/main/index.md
* Last commit: https://github.com/mdn/content/commit/f19d6973b0e2f5108c1d53e45ad6f18ac61e0fd2
* Document last modified: 2023-12-04T16:16:55.000Z

</details>

**Comment by Josh-Cena** [comment]
This is copied from Wikipedia, but for some reason the original article says "Antarctica" while this falsely says "Australia"!

**Comment by wbamberg** [comment]
Thanks for this excellent bug report. Note that https://github.com/mdn/interactive-examples/pull/2313 fixed the copy of this text that's used for the [`<p>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/p) example.

While we are fixing this we should also fix the tiny font that's used for the header.

This needs to be fixed in the mdn/interactive-examples repository, specifically https://github.com/mdn/interactive-examples/blob/main/live-examples/html-examples/text-content/main.html for the text and https://github.com/mdn/interactive-examples/blob/main/live-examples/html-examples/text-content/css/main.css for the CSS. But I'll leave this issue here for now, because this repo gets more people stopping by, so more chance of a fix.
