### ISSUE TITLE
Deprecated event property keyCode is used in examples, but also not explained

### ISSUE THREAD

**Issue by deviantintegral** [mdn/content#31988]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Element/keydown_event

### What specific section or headline is this issue about?

Element: keydown event

### What information was incorrect, unhelpful, or incomplete?

The example contains this line:

```
if (event.isComposing || event.keyCode === 229) {
```

However, that property is deprecated according to a different page: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode

### What did you expect to see?

1. Since the property is still returned by browsers, I expected it to be documented in the `Event properties` section.
2. I expected that property to link to https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode
3. I expected the example to either not use a deprecated property, or to show how to convert the deprecated way into the supported way.

### Do you have any supporting links, references, or citations?

This was previously reported in a bit of a different way at https://github.com/mdn/content/issues/26119 and closed.

### Do you have anything more you want to share?

This is also a problem at https://developer.mozilla.org/en-US/docs/Web/API/Element/keyup_event.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/element/keydown_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/keydown_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/keydown_event/index.md
* Last commit: https://github.com/mdn/content/commit/c9fe79713a9323e8f1492c3c5b802fc8776a5f6a
* Document last modified: 2024-01-19T11:52:59.000Z

</details>

**Comment by bsmth** [comment]
Thanks a lot for raising this one @deviantintegral. The policy for removing content is that it's been deprecated for some time (typically 2 years), so it's not likely that this property will be added to https://developer.mozilla.org/en-US/docs/Web/API/Element/keydown_event#event_properties again.

Instead, we should do 3) and replace `keyCode` with `code` in the pages you mentioned, as it's been available about 10 years and in [all browsers since 2020](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code#browser_compatibility).
