### ISSUE TITLE
Content bug: <main> description contradicts W3C Spec

### ISSUE THREAD

**Issue by sukima** [mdn/content#3210]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main

## Specific page section or heading?

Description/Summary, last sentence after Demo box.

## What is the problem?

The [MDN page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main) states:

> A document mustn't have more than one &lt;main&gt; element that doesn't have the hidden attribute specified.

In contrast to the [W3C spec](https://www.w3.org/TR/html50/grouping-content.html#the-main-element) which states:

> Authors must not include more than one main element in a document.

This has seemed to insight [some confusion](https://stackoverflow.com/a/62436456/227176) on the topic.

## What did you expect to see?

Would like to see either a citation or explanation how the interpretation includes the extension— _that doesn't have the hidden attribute specified_ —came about when the spec uses a hard stop.

## Did you test this? If so, how?

Chrome and FireFox (latest) seem to support either interpretations. I did not test other browsers.

**Comment by sideshowbarker** [comment]
> The [MDN page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main) states:
> 
> > A document mustn't have more than one &lt;main&gt; element that doesn't have the hidden attribute specified.

That‘s directly from the current HTML standard:

https://html.spec.whatwg.org/multipage/grouping-content.html#the-main-element:attr-hidden
> A document must not have more than one `main` element that does not have the `hidden` attribute specified.

So the MDN article is consistent with that.

> In contrast to the [W3C spec](https://www.w3.org/TR/html50/grouping-content.html#the-main-element) which states:
> 
> > Authors must not include more than one main element in a document.

Please be careful to never use any fork of the HTML standard other than the actual current standard at https://html.spec.whatwg.org/ 

The https://www.w3.org/TR/html50/ spec at the _\_W3C spec\__ link above is very out of date. To try to help indicate that, the document has a persistent sidebar on it that says **W3C Superseded Recommendation**, and the https://www.w3.org/TR/html50/#status-of-this-document section has these statements:

> This specification is a Superseded Recommendation. A newer specification exists that is recommended for new adoption in place of this specification.
> 
> New implementations should follow the [latest version](https://www.w3.org/TR/html/) of the HTML specification

…where that _\_latest version\__ link takes you to https://html.spec.whatwg.org/.

So I’m gonna go ahead and close this, because the text of the MDN article is consistent with the current HTML standard.

But feel free to comment here further if you think there’s more that should be done around this in MDN itself.

(I’d agree that outdated W3C fork of the HTML spec could be made to more clearly indicate to readers that it shouldn’t be used for anything — but that issue is out of scope for this issue tracker here at least.)
