### ISSUE TITLE
AMPPS no longer supports Linux

### ISSUE THREAD

**Issue by yecril23pl** [mdn/content#32347]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Forms/Sending_and_retrieving_form_data

### What specific section or headline is this issue about?

#on_the_server_side_retrieving_the_data

### What information was incorrect, unhelpful, or incomplete?

Good options for local PHP testing are [MAMP](https://www.mamp.info/en/downloads/) (Mac and Windows) and [AMPPS](https://ampps.com/downloads/) (Mac, Windows, Linux).

### What did you expect to see?

A valid way to run a PHP server on Linux

### Do you have any supporting links, references, or citations?

[Errors (963)](https://validator.w3.org/nu/?doc=https%3A%2F%2Fampps.com%2Fdownloads%2F)

### Do you have anything more you want to share?

The Firefox console advertises using the development server `{ python -m http.server; }` and the guide should show how to use forms with that (via CGI).  [Flask](https://flask.palletsprojects.com/en/3.0.x/) is much harder to use because it is an integrated application with virtual paths (at least per the example given).

Also, [server options](https://developer.mozilla.org/en-US/docs/Learn/Forms/Sending_and_retrieving_form_data#other_languages_and_frameworks) mention `PERL` and `.NET` but there are no corresponding examples in the list. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/forms/sending_and_retrieving_form_data`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/Sending_and_retrieving_form_data
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/forms/sending_and_retrieving_form_data/index.md
* Last commit: https://github.com/mdn/content/commit/447d4dee97df6e45dfcdd789bda2101b0626a661
* Document last modified: 2024-02-16T01:36:47.000Z

</details>

**Comment by Josh-Cena** [comment]
> Also, [server options](https://developer.mozilla.org/en-US/docs/Learn/Forms/Sending_and_retrieving_form_data#other_languages_and_frameworks) mention `PERL` and `.NET` but there are no corresponding examples in the list.

This list is not meant as a substitution for the reader's own research. If you really want to work in one of those languages, you need to do your own research. The list is neither comprehensive nor trying to be so—not even with the languages that are included.

I'm not sure what you are referring to with the error. The AMPPS website opens for me. Nevertheless AMPPS v4 no longer supports Linux, so we should either update the text or find an alternative. I really don't know why someone would use one of these instead of just downloading Apache itself, especially on Linux.

**Comment by Josh-Cena** [comment]
> What do you think of XAMPP / PHP Server with Docker?

Sure
