### ISSUE TITLE
Inconsistency in delineation between instance and static methods

### ISSUE THREAD

**Issue by 20jasper** [mdn/content#32402]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array

### What specific section or headline is this issue about?

Methods

### What information was incorrect, unhelpful, or incomplete?

Static and instance methods are distinguished explicitly in the docs for [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL), but [Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array) has one "methods" list, where instance methods follow the pattern of `Array.prototype.method()` and static methods `Array.method()` 

### What did you expect to see?

I personally prefer separate lists for static and instance methods, since it's easier to scan when separated and with only the method names

## Array example
![A static and instance method for Array](https://github.com/mdn/content/assets/78604367/b5ee15c2-1d4b-4a24-9a6c-b4b26dcd5324)
[Array.prototype.forEach()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach)
[Array.from()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from)

## URL example
![static and instance method lists for URL](https://github.com/mdn/content/assets/78604367/ae9cff16-bb35-4b43-91ce-a124e068cc59)
[canParse()](https://developer.mozilla.org/en-US/docs/Web/API/URL/canParse_static)
[toJSON()](https://developer.mozilla.org/en-US/docs/Web/API/URL/toJSON)

**Comment by Josh-Cena** [comment]
Hello, the sidebar is not managed by us, and none of us on the JS team is very happy with the current situation. I have a PR here: https://github.com/mdn/yari/pull/8502 but it has been stale for a few months and I don't see reasons to expect the Yari team to be active maintaining the platform for us because they have other business to tend to. In any case this is quite unactionable here so I'll close it anyway.
