### ISSUE TITLE
Mention 3n is BigInt syntax

### ISSUE THREAD

**Issue by ghost** [mdn/content#32492]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Multiplication_assignment

### What specific section or headline is this issue about?

Using multiplication assignment

### What information was incorrect, unhelpful, or incomplete?

let foo = 3n;
foo *= 2n; // 6n

### What did you expect to see?

Specifically at the last line, should be:
foo *= 2n; // 6n²

### Do you have any supporting links, references, or citations?

I mean, when you multiply a undefined variable by itself, it should square up the variable, multiplying any numbers alongside it

### Do you have anything more you want to share?

(I'm not a moron T.T)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/multiplication_assignment`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Multiplication_assignment
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/multiplication_assignment/index.md
* Last commit: https://github.com/mdn/content/commit/71cf0cb885d46d83af054ae4df350248e246f006
* Document last modified: 2023-10-13T19:34:44.000Z

</details>

**Comment by hamishwillee** [comment]
@phmfeitosa Thank you. The example is correct, but it is IMO not very good. 

You're reading `let foo = 3n;` as meaning `let foo = 3*n;`, where `n` is an undefined variable.
In JavaScript the `n` indicates that the number is a [BigInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) - so effectively this is just `3` if we were talking an ordinary number. 

Since we're multiplying a bigint by a bigint the result is a bigint. Hence the result in an `n`.

@Josh-Cena I think the BigInt syntax is rare enough that this is a pretty reasonable mistake to make - worth a line of comment? If so do you want to do that (or me)?

**Comment by hamishwillee** [comment]
All cool. I did a consistency fix in https://github.com/mdn/content/pull/32534 that fixes this - i.e. not every single case, because but making this more like similar docs.
