### ISSUE TITLE
Window.innerwidth giving wrong value

### ISSUE THREAD

**Issue by narasimha-1511** [mdn/content#32499]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/innerWidth

### What specific section or headline is this issue about?

Window.innerWidth not working properly

### What information was incorrect, unhelpful, or incomplete?

![error_honeycomg](https://github.com/mdn/content/assets/129654598/51e5d4ce-cea2-44ca-baab-98db376be872)

can you observe the width given in console it is 334 and see in the actuval it is 333

### What did you expect to see?

expected that the width displayed is 333

### Do you have any supporting links, references, or citations?

you can reproduce it any way in any website 

### Do you have anything more you want to share?

tested this issue in microsoft edge and chrome 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/window/innerwidth`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/innerWidth
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/innerwidth/index.md
* Last commit: https://github.com/mdn/content/commit/277e1432bea11473d0c638cd720130c44b26b3f4
* Document last modified: 2023-09-19T08:08:30.000Z

</details>

**Comment by srikanth-kandi** [comment]
I think this issue is website specific, can you provide the website in which you're facing the issue.

**Comment by narasimha-1511** [comment]
this happening everywhere pick a random website and check it

**Comment by narasimha-1511** [comment]
now example take this issue page and check it @srikanth-kandi

**Comment by srikanth-kandi** [comment]
> now example take this issue page and check it @srikanth-kandi

![image](https://github.com/mdn/content/assets/87417638/ac92127c-7bbc-4242-aeca-e8e596212b5c)

this check is made on Chrome Version 122.0.6261.94 (Official Build) (64-bit), Ubuntu 20.04

![image](https://github.com/mdn/content/assets/87417638/9dde9b5c-1f08-412d-a150-154434efabd0)

This check is made on Firefox 123.0 (64-bit), Ubuntu 20.04

On both, I don't see any difference @narasimha-1511.

**Comment by narasimha-1511** [comment]
Nah set the width as 333 and then check it @srikanth-kandi

**Comment by srikanth-kandi** [comment]
> Nah set the width as 333 and then check it @srikanth-kandi

![image](https://github.com/mdn/content/assets/87417638/e1225913-0546-4b31-a148-859bda188ecf)

**Comment by srikanth-kandi** [comment]
Hey @narasimha-1511,
I tried to reproduce the issue on Windows 11 and the Chromium-based browsers seem to show the wrong output when the width is set to `333`. But the `window.innerWidth` shows `334`.

Google Chrome 122.0.6261.95 (Official Build) (64-bit) (cohort: Stable), Windows 11

![image](https://github.com/mdn/content/assets/87417638/f3b9e454-5505-4cd7-b6e7-330b30cd7238)

Microsoft Edge 122.0.2365.66 (Official build) (64-bit), Windows 11

![image](https://github.com/mdn/content/assets/87417638/d60e7a35-4143-48a2-9292-aafb2abedf86)

Brave 1.63.165 Chromium: 122.0.6261.94 (Official Build) (64-bit), Windows 11

![image](https://github.com/mdn/content/assets/87417638/502f1ca5-5adb-4ada-91b3-752d4765720e)

But this issue is not coming on Firefox browser

Firefox 123.0 (64-bit), Windows 11

![image](https://github.com/mdn/content/assets/87417638/b8147f97-31af-458a-b27e-1e7f52332494)

**Comment by narasimha-1511** [comment]
yes thats the issue 🥲

**Comment by pepelsbey** [comment]
Hey! In this repository, we are documenting web platform features and APIs. As far as I understand, the `innerWidth` property is documented correctly. As far as I see, the problem is that some browsers are not rendering or emulating it correctly. In this case, you probably need to file a bug report to a browser issue tracker:

- [Safari](https://bugs.webkit.org/)
- [Chrome](https://issues.chromium.org/issues)
- [Firefox](https://bugzilla.mozilla.org/)
