### ISSUE TITLE
HTMLElement: click() method Doesn't Specify which elements have a "click"

### ISSUE THREAD

**Issue by jwalkerinterpres** [mdn/content#32567]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/click

### What specific section or headline is this issue about?

Opening

### What information was incorrect, unhelpful, or incomplete?

The second sentence starts:

>When click() is used with supported elements (such as an [`<input>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input))

... but then there's never any further explanation of what elements are supported, or even where to go looking for them.

### What did you expect to see?

The page should either specify which elements have a `click` method, or it should link to somewhere that does.

### Do you have any supporting links, references, or citations?

Unfortunately no; if I knew what elements had `click` and which didn't, I wouldn't have come to the MDN looking for it.

### Do you have anything more you want to share?

Nope

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/htmlelement/click`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/click
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlelement/click/index.md
* Last commit: https://github.com/mdn/content/commit/a3d9f61a8990ba7b53bda9748d1f26a9e9810b18
* Document last modified: 2023-04-07T00:39:15.000Z

</details>

**Comment by hamishwillee** [comment]
That's a good question, and I don't _think_ it is answered on MDN. 
AFAIK most elements support this - certainly any that can be in any way activated. The ones that can't are the ones that you can't interact with, such as `<base>`, `<bdo>`, `<br>`, `<head>`, `<html>`, `<iframe>`, `<meta>`, `<param>`, `<script>`, `<style>`, and `<title>`. Not sure about `<p>`, `li` etc.

IMO we should certainly make that kind of statement like "Most elements that can be activated" rather than saying nothing.
We should also probably update https://developer.mozilla.org/en-US/docs/Web/API/Element/click_event to make it clear that it won't fire on elements where `disabled` is set.

@wbamberg would appreciate your thoughts on this - specifically is there some rule here about documenting the things that can fire/handle an event, and also how can we canonically determine what supports a particular event?

**Comment by wbamberg** [comment]
Yeah, I saw this issue but couldn't find an answer in the spec.

> AFAIK most elements support this - certainly any that can be in any way activated. The ones that can't are the ones that you can't interact with, such as <base>, <bdo>, <br>, <head>, <html>, <iframe>, <meta>, <param>, <script>, <style>, and <title>. Not sure about <p>, li etc.

The problem is that I don't know what "can be in any way activated" means, so it feels a bit circular.

I haven't tested all of the ones in your list, but `click()` works on all the ones I have tried, e.g.:

```js
const style = document.querySelector("style");
style.addEventListener("click", () => console.log("clicked"));
style.click();
```

**Comment by hamishwillee** [comment]
Hmmm. What are our options then - making a broad statement "works on most elements" or testing all of them?

**Comment by wbamberg** [comment]
Since it works with `<head>`, `<meta>`, `<script>`, `<style>`, it's hard to imagine which elements it would _not_ work with. So I would probably replace the first 2 paras with:

> The HTMLElement.click() method simulates a mouse click on an element. When called on an element, the element's {{domxref("Element/click_event", "click")}} event is fired.

...and then wait for someone to complain :-).

**Comment by hamishwillee** [comment]
YOu're a brave man @wbamberg . Done in #32608, but with additional caveat it isn't fired on disabled elements. That is stated in the `disabled` docs, and tested using your code + setting disabled to true on an input.
