### ISSUE TITLE
[JS] Enable Intl.Segmenter by default

### ISSUE THREAD

**Issue by pepelsbey** [mdn/content#32661]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Related Gecko bugs

- [Enable Intl.Segmenter by default](https://bugzilla.mozilla.org/show_bug.cgi?id=1883914)

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [x] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by hamishwillee** [comment]
Status 

- [ ] BCD https://github.com/mdn/content/issues/32661
- [ ] Docs - NA - from what I can see (and remember) pretty much all needed work done previously
- [ ] Release note
- [ ] Experimental features removal

**Comment by Josh-Cena** [comment]
@pepelsbey It's still a feature of "ECMAScript", which is JavaScript. It's standardized by TC39, not by W3C, WHATWG, or any other web committee. It's also documented under the JS section on our website. All features related to `Intl` have been and should be JS issues.

**Comment by hamishwillee** [comment]
What he said ^^^. Essentially if it's Ecmascript standard its JS and in the javascript tree. Web APIs are not part of the JavaScript standard, but are browser/web platform specific extensions.

The interesting thing for me is how differently these are treated in engineering. As I understand it JavaScript spec stuff is implemented in a separate engine and integrated into the browser, rather than being "part of the browser". The integration is almost always done as build time flags _first_. Sometimes there is a follow on period where there is also/instead a run-time flag. The point though, is that it can appear that you have something implemented in runtime, preview, release or behind a flag, when it is not.

**Comment by Josh-Cena** [comment]
The main difference for me personally is whether I will be interested in reviewing any technical docs. ^^

**Comment by pepelsbey** [comment]
All done, thank you!
