### ISSUE TITLE
Block and dispute this issue 

### ISSUE THREAD

**Issue by WithoutAsoul187** [mdn/content#32852]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400

### What specific section or headline is this issue about?

Message error 400

### What information was incorrect, unhelpful, or incomplete?

False relocation of messaging

### What did you expect to see?

Original txt

### Do you have any supporting links, references, or citations?

No

### Do you have anything more you want to share?

N/a

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/status/400`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/status/400/index.md
* Last commit: https://github.com/mdn/content/commit/0880a90f3811475d78bc4b2c344eb4146f25f66c
* Document last modified: 2023-04-10T19:47:15.000Z

</details>

**Comment by WithoutAsoul187** [comment]
How to get past or fix server error of 404 & 400 code errors

**Comment by hamishwillee** [comment]
Closing as this is a support question, not a report of any issue about the docs.

But FWIW these status are returned by the server to indicate requests that can't be statisfied, such as 404 for a requested resource that does not exist. Returning that status is the right thing to do. It's not something to be fixed, because nothing is broken.
