### ISSUE TITLE
Missing units on Values_and_units page

### ISSUE THREAD

**Issue by brandonmcconnell** [mdn/content#32896]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units#relative_length_units

### What specific section or headline is this issue about?

Relative length units

### What information was incorrect, unhelpful, or incomplete?

The "Relative length units" table lacks the logical s/l/d units:

|  | block | inline |
|:-------|:-------|:-------|
| **small** | `svb` | `svi` |
| **large** | `lvb` | `lvi` |
| **dynamic** | `dvb` | `dvi` | 

### What did you expect to see?

The missing units present

### Do you have any supporting links, references, or citations?

Those units are present on this page: https://developer.mozilla.org/en-US/docs/Web/CSS/length.

I opened—and subsequently closed—a related CSSWG proposal for those units ([here](https://github.com/w3c/csswg-drafts/issues/10157)) when I thought they might not exist after reading the page in question.

### Do you have anything more you want to share?

I appreciate the support!

**Comment by wbamberg** [comment]
Thanks for filing!

The list in https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units#relative_length_units is not intended to be exhaustive, as the page says:

> Some of the most useful units for web development are listed in the table below.

It would be a mistake to try to make it exhaustive, because noone would remember to update it when new values are added. But it is confusing, because it's almost exhaustive, so it's easy to assume that it is intended to be.

So it would be better, actually, if this page listed _fewer_ values, and was clearer that it is not intended to be a complete list, and that to see the complete list people should visit https://developer.mozilla.org/en-US/docs/Web/CSS/length.

**Comment by dipikabh** [comment]
@wbamberg I agree. Maybe we can state the non-exhaustive nature of the table more explicitly. That is:

> Some of the most useful units for web development are listed in the table below (this is not an exhaustive list; for more details, see the [`<length>`]() page).
