### ISSUE TITLE
CSS only visually hiding

### ISSUE THREAD

**Issue by WBerndorfer** [mdn/content#32921]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

The suggested code to hide the element is:
input.style.opacity = 0;

This only hides the element visually.
A screen reader won't ignore the element.

### What did you expect to see?

Hide the element from the DOM commpletely, e.g.:
input.style.display = none;

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/CSS/opacity
https://developer.mozilla.org/en-US/docs/Web/CSS/display#display_none

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/input/file`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/file/index.md
* Last commit: https://github.com/mdn/content/commit/72ca3d725e3e56b613de3ac9727bd0d6d619c38a
* Document last modified: 2024-01-08T13:33:20.000Z

</details>

**Comment by hamishwillee** [comment]
Thank you, but I am closing as not planned/invalid.

You're not wrong about the use of opacity "in general", but this is intentional. The reason is that often the screen reader will see the visibility as hidden and not detect a change to make the input visible again, whereas setting the opacity does work. This is explicitly captured in the note:

![image](https://github.com/mdn/content/assets/5368500/3af9a8f9-e63d-4880-862a-1a013974b238)
