### ISSUE TITLE
Issue with "Express Tutorial Part 7: Deploying to production": (please mention Google Cloud Free Tier)

### ISSUE THREAD

**Issue by evil-shrike** [mdn/content#3298]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/deployment

#### What information was incorrect, unhelpful, or incomplete?

>The good news when you're starting out is that there are quite a few sites that provide computing environments for "free", albeit with some conditions. For example, Heroku provides a free but resource-limited PaaS environment "forever", while Amazon Web Services and Microsoft Azure provide free credit when you first join.
>Many providers also have a "basic" tier that provides more useful levels of computing power and fewer limitations. Digital Ocean is an example of a popular hosting provider that offers a relatively inexpensive basic computing tier (in the $5 per month lower range at time of writing).

Everything is correct but let me ask to add a mention of Google Cloud as it'd be fair to mention all three big players.

#### Specific section or headline?

"Choosing a hosting provider"

#### What did you expect to see?

>[Google Cloud provides you both](https://cloud.google.com/free): Free Tier for free-of-change usage of some services (inc. popular for [site hosting](https://cloud.google.com/solutions/web-hosting) App Engine, Cloud Run and Cloud Storage) and credits.

right after "while Amazon Web Services and Microsoft Azure provide free credit when you first join" text.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/deployment`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/deployment
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/deployment/index.html
* Last commit: https://github.com/mdn/content/commit/4b9d9a8bf3ab3db9f7b1efc89b5a91bbf459fe07
* Document last modified: 2021-03-01T12:15:15.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks, fixed by #3348

I just added it to the list like the other two rather than trying to categorise the level of support provided and the existence of a free tier. These levels can change at any time and it may be that Azure/Amazon are also more than just free credit - that is why there is a note above saying "check before choosing". 

Also FWIW to me these "free credit" options are all "not free" options - and that includes the "free tier". They are "might be free" options. But if you're starting out then you're more interested in controlling cost than having no cost.
