### ISSUE TITLE
deepFreeze fails with functions

### ISSUE THREAD

**Issue by SoftMoonWebWare** [mdn/content#32990]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze

### What specific section or headline is this issue about?

What is "shallow freeze"?

### What information was incorrect, unhelpful, or incomplete?

The example for "deepFreeze" looks at both Objects and Functions as candidates to "deepFreeze" recursively.  Functions have a "prototype" property, that in turn has a "constructor" property, which then points back to the Function.  This causes infinite recursion, and JavaScript (SpiderMonkey at least) throws an error for "too many recursions."  This example is likely to greatly confuse some (most?!) folks new to JavaScript if their Object to deepFreeze contain Function(s), because it fails out of the box, despite the preceding paragraph warning of recursion.

### What did you expect to see?

```
if (Object.deepFreeze)  console.warn("Object.deepFreeze already exists.");
else  Object.deepFreeze=function deepFreeze($O, deep=true, cursed=[])  {
	if (deep  &&  typeof deep !== 'number')  deep=Infinity;
	if (deep)  {
		cursed.push($O);
		for (const p of Object.getOwnPropertyNames($O))  {
			if ((typeof $O[p] === "function"  ||  (typeof $O[p] === "object"  &&  !($O[p] instanceof Window)))
			&&  !cursed.includes($O[p]))
				deepFreeze($O[p], deep-1, cursed);  }
		cursed.pop();  }
  return Object.freeze($O);  }
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/object/freeze`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/object/freeze/index.md
* Last commit: https://github.com/mdn/content/commit/0c2f10d728d1018f1b21c3e96267c5d586ff0ae3
* Document last modified: 2024-01-15T08:20:21.000Z

</details>

**Comment by SoftMoonWebWare** [comment]
My point was that is does not work for **ANY** use case where Functions are properties of the Object.  It is a broken code example, not a "some use" code example.  But whatever.  Make it harder for people. I see this lately (the last few years as ya'll "streamline" the content into a management system) all through this website.  Then they will buy the book, yea?

**Comment by queengooborg** [comment]
Hi @SoftMoonWebWare, please be respectful when posting comments.  Posting disrespectful comments is both disruptive to the project and hurtful to others involved in the conversation.  Please review the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) to understand what behavior is expected of all participants in this repository.

In regards to the issue being reported, it appears that the `typeof value === "function"` was added due to https://github.com/mdn/content/pull/22675#discussion_r1038650862, which states that some objects will report themselves as a function type.  One possible solution would be to use `typeof value === "function" && !(value instanceof Function)`, perhaps?  (I have not researched this thoroughly, so I could be wrong!)
