### ISSUE TITLE
Fix typo and clarify surrounding text

### ISSUE THREAD

**Issue by hobbsd** [mdn/content#33001]
I noticed this typo when searching the code for a typo ("hight") on the Curriculum landing page. When I read the surrounding text it seemed like it could be made a bit more clear:

https://github.com/mdn/content/blob/207ffcdd942030c6897003085b95c408eb169ff6/files/en-us/web/api/webgl_api/constants/index.md?plain=1#L415-L417

I'd suggest a change to something like (with the change in bold):

> Passed to `getParameter` to get the range of available widths 
> for a line. Returns **an array with two elements: the minimum width 
> value at index 0 and the maximum width value at index 1**.

**Comment by hamishwillee** [comment]
Thanks very much @hobbsd - this should be fixed by https://github.com/mdn/content/pull/33005

FYI, when you're creating issues, can you follow the template and add a URL to the actual page affected - saves me a minute or two grepping. Even better, for this kind of thing we'd welcome a PR since that provides us the exact context and your preferred fix.
