### ISSUE TITLE
SignalingChannel does not exist?

### ISSUE THREAD

**Issue by Shyaaan** [mdn/content#33004]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Perfect_negotiation

### What specific section or headline is this issue about?

Create the signaling and peer connections

### What information was incorrect, unhelpful, or incomplete?

```
const config = {
  iceServers: [{ urls: "stun:stun.mystunserver.tld" }],
};

const signaler = new SignalingChannel();
const pc = new RTCPeerConnection(config);
```
This code is incorrect, I could not find any constructor SignalingChannel, and so my code won't run. I want to know what I'm supposed to do instead.

### What did you expect to see?

A constructor that exists.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/webrtc_api/perfect_negotiation`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Perfect_negotiation
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/webrtc_api/perfect_negotiation/index.md
* Last commit: https://github.com/mdn/content/commit/4f0f7386262363103a3e9cf482bb348d8570b331
* Document last modified: 2023-02-19T08:44:25.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks, but I am closing because this is not a defect.

Please see the previous section in this same page:

> Let's take a look at an example that implements the perfect negotiation pattern. The code assumes that there's a `SignalingChannel` class defined that is used to communicate with the signaling server. Your own code, of course, can use any signaling technique you like.

So what this is saying is that the channel used for signaling is something that you have to define. The example just shows that such a class exists. There is more information about how a signalling server might work in the previous topic: https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Connectivity#signaling
