### ISSUE TITLE
Directory page order and name

### ISSUE THREAD

**Issue by zhangenming** [mdn/content#33128]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/flex

### What information was incorrect, unhelpful, or incomplete?

The current directory order is alphabetical

Want to sort in a meaningful order

### What did you expect to see?

![image](https://github.com/mdn/content/assets/21235555/5b20df3b-a7f8-4830-abba-5850bd364034)

### Do you have anything more you want to share?

~~It would be nice if the title of the article showed more information(such as constituent properties)~~

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/flex`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/flex
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/flex/index.md
* Last commit: https://github.com/mdn/content/commit/856b52f634b889084869d2ee0b8bb62c084be04d
* Document last modified: 2023-07-17T22:37:27.000Z

</details>

**Comment by hamishwillee** [comment]
I don't agree with this - to me this look like UI complexity with relatively little benefit to users, and quite a lot of work to achieve it for authors and UI design team. 

@estelle Is this something you'd like, and if so perhaps move it to Yari repo?

**Comment by zhangenming** [comment]
But alphabetical exclusion does not provide useful information and can lead to confusion
However, maintaining the meaningful order can be a big effort

**Comment by hamishwillee** [comment]
> But alphabetical order does not provide useful information and can lead to confusion

Incorrect. The useful information alphabetic order provides is where the topic will be located in the sidebar - there is no ambiguity or confusion, it will be exactly where you expect it to be. The main use of the sidebar is to locate topics and provide a guided flow.

What you're proposing is to add some information about the related properties in the sidebar. I see that as visual complexity to not much value - mostly because I think that people don't need this information when navigating via the sidebar - though they might when they are in the topic. 

If the proposal was to _nest_ "sub" properties then I might agree because that would be a logical navigation, but again it might make things harder for some users.

@estelle Owns this sidebar and might take a different view.

**Comment by zhangenming** [comment]
I'm sure you understand better than me
But let me restate my request and hope there is no mistake

![image](https://github.com/mdn/content/assets/21235555/e5837ac1-322a-427d-9377-e369b1735799)

I just think the order on the right is more useful than the one before

left order is alphabetical 
right order is meaningful

**Comment by hamishwillee** [comment]
Ah, now that's a completely different image/proposal than [your original one](https://github.com/mdn/content/assets/21235555/068285e3-7491-48c4-80ec-ea5a1623a4d8).

To me that makes sense. But let's leave with Estelle.

**Comment by zhangenming** [comment]
Yes this is an additional, half-baked idea just put here for reference

**Comment by estelle** [comment]
It should definitely remain alphabetical.
People will have different ideas of what "useful" means and how "useful" each property is. Alphabetical removes any discussion or disagreement.

That said, i do with the "end of word" character came before the "dash" in the ascii alphabet.

**Comment by hamishwillee** [comment]
I agree. 

Closing as "not planned". Thanks for the suggestions @zhangenming
