### ISSUE TITLE
More explanation on the concept  of Object Prototypes

### ISSUE THREAD

**Issue by kelvinmacharia254** [mdn/content#33154]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object_prototypes

### What specific section or headline is this issue about?

General the concept of Object Prototypes

### What information was incorrect, unhelpful, or incomplete?

General the concept of prototype was hard to grasp fully. For example the last topic on prototype and inheritance, it would be more helpful if there were examples. I am still a newbie to JavaScript and I hope my suggestions are not rudimentary

### What did you expect to see?

More examples and a little more explanation

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/objects/object_prototypes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object_prototypes
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/objects/object_prototypes/index.md
* Last commit: https://github.com/mdn/content/commit/8d0cbeacdc1872f7e4d966177151585c58fb879e
* Document last modified: 2023-08-02T17:32:22.000Z

</details>

**Comment by Josh-Cena** [comment]
Unfortunately this request is too broad to act on. I agree that this section is too short, but that's because it's explained in more detail in https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object-oriented_programming. This is only serving as a transitional paragraph. If you really want to learn about this area, read https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain
