### ISSUE TITLE
document of RTCIceCandidate's properties { url, relayProtocol}  are missing

### ISSUE THREAD

**Issue by ciyoe** [mdn/content#33228]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidate

### What specific section or headline is this issue about?

properties

### What information was incorrect, unhelpful, or incomplete?

miss  **`RTCIceCandidate.url`** and **`RTCIceCandidate.relayProtocol`** document

### What did you expect to see?

create  **`RTCIceCandidate.url`** and **`RTCIceCandidate.relayProtocol`** document

### Do you have any supporting links, references, or citations?

https://w3c.github.io/webrtc-pc/#attributes-4

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/rtcicecandidate`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidate
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/rtcicecandidate/index.md
* Last commit: https://github.com/mdn/content/commit/50ed08d7b506c19b7d073b05ea1e02a15f276878
* Document last modified: 2023-02-19T09:57:47.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks, correct, do you want to do it?

Note that the compatibility data for these properties links to the RTCIceCanidateStats ([at least for now](https://github.com/mdn/browser-compat-data/pull/22947). These properties are not implemented and should be removed, but perhaps the pages could be copied as a starting point, because they will share the same concepts.

**Comment by Josh-Cena** [comment]
Hi! I'm closing all issues that are in https://openwebdocs.github.io/web-docs-backlog/all/. These features are automatically in our backlog and don't need separate issues to track.
