### ISSUE TITLE
Bad consistency in writing guide list ?

### ISSUE THREAD

**Issue by Ptitet** [mdn/content#33323]
I think there is a consistency problem on this page : https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Howto/Markdown_in_MDN#example_code_blocks

There is a list of supported info strings for code blocks in Markdown, and for the `pug` string, there are two links to Pug and Express.js documentation. There is no link for all the other info strings, so that's a bit strange.

## What should be done according to me
Remove the links to the documentation for the pug info strings or add link to the documentations for the other items.

![image](https://github.com/mdn/content/assets/95184938/554e7870-f1a3-473c-9558-7981933be3ec)

**Comment by hamishwillee** [comment]
Thank you. Most of the code block types are pretty easy to guess, but pug is not, unless you already know Express. So yes, inconsistent, but really, does this inconsistency harm anyone? I'd be OK with removing the links, because people can search. But not really worth the effort IMO.

I'll leave open, but unless someone strongly disagrees with good reasons we should close this.

**Comment by Josh-Cena** [comment]
I agree. We made a judgment call of which languages are "well-known" and which are not.
