### ISSUE TITLE
Regular expression: n in x{n}, x{n,}, x{n,m} can be any integer in quantifier expression

### ISSUE THREAD

**Issue by jasonren0403** [mdn/content#33486]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_expressions/Quantifiers

### What specific section or headline is this issue about?

Types

### What information was incorrect, unhelpful, or incomplete?

The document says `n` in `x{n}`, `x{n,}`, and `x{n,m}` is a positive integer, but in fact the regexp compiles when `n===0`, and even when `n<0`(seems "invalid" because no one ever use like that).

```js
/a{-1}/.test('b') // false
/a{-1,}/.test('b') // false
```

### What did you expect to see?

The correct `n` range in `x{n}`, `x{n,}`, and `x{n,m}` is mentioned. The possible 'invalid' usage `n<0` may be warned.

### Do you have any supporting links, references, or citations?

[Microsoft docs](https://learn.microsoft.com/en-us/dotnet/standard/base-types/quantifiers-in-regular-expressions) hints that n could be any integer in `{n}`, `{n,}`, and `{n,m}`.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/guide/regular_expressions/quantifiers`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_expressions/Quantifiers
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/regular_expressions/quantifiers/index.md
* Last commit: https://github.com/mdn/content/commit/c6f0f106b9083984dbf597678def6561729bb459
* Document last modified: 2023-09-07T01:22:04.000Z

</details>

**Comment by MercyGraceFavorBlessing3579** [comment]
I don’t know why I can’t seems to geti inGITHUB actually my apps  is blank and every time  I want to come after reading your email it doesn’t go throug

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Jason Ren ***@***.***>
Sent: Wednesday, May 8, 2024 4:46:58 AM
To: mdn/content ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mdn/content] Regular expression: n in x{n}, x{n,}, x{n,m} can be any integer in quantifier expression (Issue #33486)


MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_expressions/Quantifiers

What specific section or headline is this issue about?

Types

What information was incorrect, unhelpful, or incomplete?

The document says n in x{n}, x{n,}, and x{n,m} is a positive integer, but in fact the regexp compiles when n===0, and even when n<0(seems "invalid" because no one ever use like that).

/a{-1}/.test('b') // false
/a{-1,}/.test('b') // false

What did you expect to see?

The correct n range in x{n}, x{n,}, and x{n,m} is mentioned. The possible 'invalid' usage n<0 may be warned.

Do you have any supporting links, references, or citations?

Microsoft docs<https://learn.microsoft.com/en-us/dotnet/standard/base-types/quantifiers-in-regular-expressions> hints that n could be any integer in {n}, {n,}, and {n,m}.

Do you have anything more you want to share?

No response

MDN metadata
Page report details

  *   Folder: en-us/web/javascript/guide/regular_expressions/quantifiers
  *   MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_expressions/Quantifiers
  *   GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/regular_expressions/quantifiers/index.md
  *   Last commit: c6f0f10<https://github.com/mdn/content/commit/c6f0f106b9083984dbf597678def6561729bb459>
  *   Document last modified: 2023-09-07T01:22:04.000Z

**Comment by MercyGraceFavorBlessing3579** [comment]
Like someone doesn't want me  to  know something or weird tings

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Josh-Cena** [comment]
`/a{-1}/` is not a valid regular expression. It's allowed because regexes without `u` or `v` use a much laxer grammar for parsing. Please try again:

```js
/a{-1,}/u // Uncaught SyntaxError: Invalid regular expression: /a{-1,}/u: Incomplete quantifier
```

What `/a{-1}/` actually means is `/a\{-1\}/`.

**Comment by Josh-Cena** [comment]
Actually "positive" is wrong. It should say "non-negative".
