### ISSUE TITLE
Issue with "Node.previousSibling": Example refers to text nodes, not element nodes

### ISSUE THREAD

**Issue by StephanieCunnane** [mdn/content#3377]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Node/previousSibling

#### What information was incorrect, unhelpful, or incomplete?
In both `console.log`s in the Example, the `previousSibling` property actually points to a text node, not the previous image element.

#### Specific section or headline?
Example

#### Did you test this? If so, how?
I tested this by saving the example as an HTML file and examining it in Chrome DevTools.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/node/previoussibling`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Node/previousSibling
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/node/previoussibling/index.html
* Last commit: https://github.com/mdn/content/commit/63c69f3c933acbea9bfb24d359a7d2ffdb3c0bea
* Document last modified: 2021-02-19T19:51:22.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it.

So yeah, the example is plain wrong — because the `img` elements in the example are on separate lines, there are actually text nodes between each of them, and so `previousSibling` returns those text nodes rather than the element nodes.

A trivial fix here would be to change the example to put all the `img` elements on the same line, with no whitespace between:

```html
<img id="b0"><img id="b1"><img id="b2">
```
…but that would be a pretty silly example.

So I think the right change here would be to completely replace the example with something more real-world.

So I think whoever fixes this should come up with a better example.

The example in the https://developer.mozilla.org/en-US/docs/Web/API/Node/nextSibling article looks much less bad — at first glance at least — so maybe another trivial fix would be to copy that example but rewrite it slightly to work with `previousSibling` rather than `nextSibling`.

**Comment by longm89** [comment]
Could I work on this ?

**Comment by chrisdavidmills** [comment]
@longm89 You certainly can; assigned! Thanks for your offer of help.

**Comment by longm89** [comment]
@chrisdavidmills Thanks a lot. 
@sideshowbarker I fixed it using your example, and I add a similar example to the one in the nextSibling that you mentioned (without the loop).
