### ISSUE TITLE
I find the content PR template confusing and intimidating

### ISSUE THREAD

**Issue by peterbe** [mdn/content#3379]
I found a problem with the content and I made a PR. Now I see this when I go to file my PR:

<img width="923" alt="Screen Shot 2021-03-22 at 3 28 42 PM" src="https://user-images.githubusercontent.com/26739/112047246-6c2df700-8b23-11eb-8dbc-5233706768fb.png">

Am I suppose to delete all of that text and write it myself??
Or, am I suppose to leave it and write my answers/explanations on a line underneath each one, like a reply??
Am I supposed to remove the text and keep the `1. - [ ] ` for each line??
What am I suppose to do with the `Checklist — To help your pull request get merged faster, please do the following:` (first) line??
What if there is no good "completable" task? For example, `Link to any other resources that you think might be useful in reviewing your PR`. What links can there possibly be for a typo fix? If it's not applicable, do I check it off or do I delete the line??

It's not clear at all what you're supposed to do. Personally, I'm pretty sure what I'd do because I'm me, but imagine this from a relative newbie to the project. So *I* don't need answers to my questions above. But I think the core content team should consider rewriting the PR GitHub template code so it's less confusing and less intimidating. Does that make sense?

**Comment by hamishwillee** [comment]
@peterbe You're such a wimp :-)

Since people don't read, perhaps less is more. How about this? 
@chrisdavidmills ?

---

Checklist — To help us understand "why" the change was needed and the main affected areas.

- - [ ] What problem does this fix?

"Replace this text with a brief overview of: what was wrong, how you fixed it, MDN URL of main affected page"

- - [ ] Fixes an existing MDN issue (replace XXXX below with an issue number, if one exists)

Fixes #XXXX

- - [ ] PR passes the automated checks after submission? (the checks are at the bottom of the PR page - add a comment on the PR if you need help fixing them)

- - [ ]  More information

"Replace this text with any other information you think might help us review the PR (e.g. links, etc.)"

**Comment by sideshowbarker** [comment]
> Since people don't read, perhaps less is more

Yeah, I think seeing if we could reduce the verbosity a bit would be a good thing

**Comment by hamishwillee** [comment]
Well really short version is below. With that information we can fix up the descriptions if needed.
----

Please provide the following information to help us review this PR:
- What was wrong/why is this fix needed?
- MDN URL of main page changed
- Issue number (if there is an associated issue)
- Anything else that could help us review this PR

**Comment by chrisdavidmills** [comment]
Pffff. PR filed ;-)

**Comment by peterbe** [comment]
People certainly read less than more. Much less.

**Comment by hamishwillee** [comment]
@peterbe Yes they do. Pleasingly, the new template appears to be being used, and properly :-)
