### ISSUE TITLE
Possibly out of date advice about cross-browser interop

### ISSUE THREAD

**Issue by nixxquality** [mdn/content#33853]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

### What specific section or headline is this issue about?

Handling browser support

### What information was incorrect, unhelpful, or incomplete?

At the end of the section it says
> At the moment, the best way to deal with dates in forms in a cross-browser way is to have the user enter the day, month, and year in separate controls, or to use a JavaScript library such as [jQuery date picker](https://jqueryui.com/datepicker/).

### What did you expect to see?

Considering most browsers have supported it since 2017 with Safari as the sole outlier, supporting it since 2021, I believe this information can now be considered out of date.
Even if 3 years since Safari sounds close, I believe that Apple users tend to keep their software more up to date than other platforms, so it's really the 2017 date you have to consider.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/input/date`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/date/index.md
* Last commit: https://github.com/mdn/content/commit/72ca3d725e3e56b613de3ac9727bd0d6d619c38a
* Document last modified: 2024-01-08T13:33:20.000Z

</details>

**Comment by wbamberg** [comment]
The page for `time` has similar compat, and similar advice: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time#handling_browser_support.

And yes, it's probably good to consider updating this advice. It's probably at least 5 years old, and in that time we've seen IE retirement as well as Safari adding support.

Probably the most conservative thing would be to keep all the stuff about problems that occur with old browsers, but update the bit you quoted from "At the moment, the best way to deal with dates in forms in a cross-browser way" to say something like "Date inputs are well supported by modern browsers, but if you need to support older browsers that don't implement them, ...".

I would love to know what @estelle and @chrisdavidmills think, since as far as I recall they wrote this back then :).

**Comment by estelle** [comment]
I removed the script for date. It is supported everywhere, and has been for a while.

The time one is a bit different. THe step attribute is not supported as defined in the spec, but otherwise supported everywhere.
