### ISSUE TITLE
Issue with "DataView": "64-bit integer values" section is outdated

### ISSUE THREAD

**Issue by CrimsonCodes0** [mdn/content#3389]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView

#### What information was incorrect, unhelpful, or incomplete?

The web page claims that 64-bit integers cannot be read via DataViews, and that such functionality needs to be shimmed instead.

#### Specific section or headline?

The section [64-bit integer values](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView#64-bit_integer_values) is outdated with the introduction of DataView#{setBigUint64, getBigUint64, setBigInt64, getBigInt64}, as they natively allow reading 64-bit integers.

Oddly enough, the page does list them at the end regardless, so the page should be updated appropriately.

#### Did you test this? If so, how?

I've used the aformentioned DataView methods in real code.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/dataview`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/dataview/index.html
* Last commit: https://github.com/mdn/content/commit/bdedc2ea216ccae188cfca73329df7f04b94104a
* Document last modified: 2020-12-21T22:03:16.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it. I think the fix here is to keep that [64-bit integer values](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView#64-bit_integer_values) section but rewrite it to instead say something like this:

> Because some browsers currently in use do not have complete support for `DataView.prototype.getBigInt64()` and `DataView.prototype.getBigUInt64()`…

…because Safari 14 actually doesn’t yet support `DataView.prototype.getBigInt64()` and  `DataView.prototype.setBigUint64()` (though Safari Technology Preview does, because the code is in the WebKit sources — just didn’t make it into Safari 14 or before) — nor do IE 11 and before and legacy Edge.

So the information in that section is still useful for anybody who wants to make sure their code works across browsers.

Anyway, I’ll write up a patch for this and raise a PR.

**Comment by sideshowbarker** [comment]
OK, I’ve opened https://github.com/mdn/content/pull/3419 for this
