### ISSUE TITLE
No instructions on using `aria-label` and `aria-labelledby` attributes for accessible naming of icon buttons.

### ISSUE THREAD

**Issue by manav-sharma69** [mdn/content#33895]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#icon_buttons

### What specific section or headline is this issue about?

Accessibility concerns

### What information was incorrect, unhelpful, or incomplete?

Incomplete information: 
1. For the accessible naming of icon buttons, why the usage of attributes like `aria-label` or `aria-labelledby` not mentioned in the article?
2. For accessible description of button's functionality, there's no content available. Whereas, one can use the `aria-describedby` attribute to add accessible description to a button (regardless of it being icon button).

### What did you expect to see?

I expected to see ways on how to add accessible names to icon buttons and ways to add accessible description to the element.

### Do you have any supporting links, references, or citations?

1. [aria-label](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label) - The first example itself is that of a `button` element using `aria-label` attribute for accessible naming.
2. "All interactive elements must have an accessible name. aria-labelledby can be used to reference another element to define its accessible name, when an element's accessible name needs to use content from elsewhere in the DOM." - [MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby)
3. The button has an accessible label. By default, the accessible name is computed from any text content inside the button element. However, it can also be provided with [aria-labelledby](https://w3c.github.io/aria/#aria-labelledby) or [aria-label](https://w3c.github.io/aria/#aria-label). - [W3](https://www.w3.org/WAI/ARIA/apg/patterns/button/)
4. If a description of the button's function is present, the button element has [aria-describedby](https://w3c.github.io/aria/#aria-describedby) set to the ID of the element containing the description. - [W3](https://www.w3.org/WAI/ARIA/apg/patterns/button/)

### Do you have anything more you want to share?

The last paragraph in [icon buttons section](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#icon_buttons) talks about leaving the text button visually apparent so that people who're unfamiliar with that button's icon can understand what that button will do.

To solve that issue, is it okay if we add `title` attribute to icon buttons? 

Something like this:

```html 
<button title="button label">❤️</button>
```
But it'll work for only those devices which have cursor.

**Comment by estelle** [comment]
The first rule of ARIA is "If you can use a native HTML element or attribute with the semantics and behavior you require already built in, instead of re-purposing an element and adding an ARIA role, state or property to make it accessible, then do so." The button element does not cover aria-label or aria-labelledby because the text in the button is the default accessible name. 

I did add a link to the accessible name which should address the issue; we don't provide ARIA alternatives for semantic elements on MDN as ARIA should only be used when the developer can't otherwise use native semantics.

That addresses the issues with the content of the page.

To answer your `title` question: no, the title attribute is not the solution for making content accessible. See https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title#accessibility_concerns.

**Comment by manav-sharma69** [comment]
Thanks a lot for the clarification!
