### ISSUE TITLE
Issue with "A re-introduction to JavaScript (JS tutorial)": contradictions about the existence of Integers

### ISSUE THREAD

**Issue by fractalcactus** [mdn/content#3391]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/A_re-introduction_to_JavaScript

#### What information was incorrect, unhelpful, or incomplete?
"There's no such thing as an integer in JavaScript" is contradicted by "You can convert a string to an integer using the built-in parseInt() function" a few paragraphs later, in the same section.

I'm confused as to how "You can convert a string to an integer" if "There's no such thing as an integer in JavaScript"

This question has also been asked on [StackOverflow](https://stackoverflow.com/questions/33773296/is-there-or-isnt-there-an-integer-type-in-javascript)

#### Specific section or headline?
Numbers

#### What did you expect to see?
I wish I could make a PR with corrections, but I'm not sure how `parseInt()` works. From the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt):
"The parseInt() function parses a string argument and returns an integer of the specified radix"

The docs are again implying that there are integers in JavaScript.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/a_re-introduction_to_javascript`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/A_re-introduction_to_JavaScript
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/a_re-introduction_to_javascript/index.html
* Last commit: https://github.com/mdn/content/commit/a5c0642a639a5855f8e1db5115f3a2c59dd21831
* Document last modified: 2021-03-16T15:02:58.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising an issue about this. I think the right fix here is to replace that *“There's no such thing as an integer in JavaScript”* statement with something less… emphatic. For one thing, since we do now have BigInt values in JavaScript, that statement is actually false.

But anyway I think the right fix here is to replace that statement with *“Anywhere you see *integer* mentioned in this article and in other MDN articles, it’s usually just shorthand for referring to Number values (`number` primitives)”* or some such.

That wording is just off the top of my head, though — I’ll write up a patch and raise a PR so we’ve got something to review and refine/iterate on as needed.

**Comment by sideshowbarker** [comment]
OK, I’ve opened https://github.com/mdn/content/pull/3420 for this
