### ISSUE TITLE
flex-initial element doesn't explicitly use flex: initial

### ISSUE THREAD

**Issue by Slapass** [mdn/content#34027]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/flex

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/CSS/flex#examples

### What information was incorrect, unhelpful, or incomplete?

I'm pretty sure in the example, under the CSS code, the #flex-initial is not set to flex initial, but the Result section says "flex: initial" has a flex value of [initial](https://developer.mozilla.org/en-US/docs/Web/CSS/flex#initial)

### What did you expect to see?

I expected "#flex-initial {
  border: 1px solid #000;
}"
to also include flex:initial, bit it doesnt. 

### Do you have anything more you want to share?

![Screen Shot 2024-06-09 at 5 18 51 PM](https://github.com/mdn/content/assets/100818373/fbc5bd37-f3ae-4879-ab3d-340c7331170b)

**Comment by hamishwillee** [comment]
Thanks @Slapass 

I think you're probably right. My guess is that either `initial` or `none` is the default value for for a flex item where no value has been specified - either would explain the observed example. 

Either way this should be explicit for the purpose of the example and I think think we should state the default. @estelle Is that reasonable?

**Comment by Ashish-CodeJourney** [comment]
Raised a PR related to same https://github.com/mdn/content/pull/34031
Check Preview here : https://pr34031.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/flex

**Comment by estelle** [comment]
The issue here is that `initial` is set twice in the example syntax at the top, and then expressly defined in the values. 

in the syntax we have:

``` css
 /* Keyword values */
flex: auto;
flex: initial;
flex: none;
```

and then have:

```css
/* Global values */
flex: inherit;
flex: initial;
flex: revert;
flex: revert-layer;
flex: unset;
```

plus in the values, we have:


> [`initial`](https://developer.mozilla.org/en-US/docs/Web/CSS/flex#initial)
> The item is sized according to its width and height properties. It shrinks to its minimum size to fit the container, but does not grow to absorb any extra free space in the flex container. This is equivalent to setting "flex: 0 1 auto".

which is the first value. We likely should:

1.  change the `#initial-flex` in the example to #default (edit required in HTML and CSS)
2. Keep the `flex: initial` out of it, as is current (no change)
3. Add text to say that the #default uses the initial value of 0 1 auto, in the explanation, not in the code.
4. Move the `initial` in the values to the end and explain that it is the default, a global value, and does not need to be explicitly declared.
