### ISSUE TITLE
The "place-items" demo is confusing and therefore appears broken

### ISSUE THREAD

**Issue by danditomaso** [mdn/content#3427]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/place-items

#### Specific section or headline?
When you modify the select box to a specific value, once the items above move to that position, and you select another option from the place-items dropdown no changes take effect in the above Result box.

#### What did you expect to see?
By selecting different options in the place-items dropdown I should see the Result's reflect those changes.

#### Did you test this? If so, how?
Tried in Private mode in Firefox didn't see any changes. 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/place-items`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/place-items
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/place-items/index.html
* Last commit: https://github.com/mdn/content/commit/f4fb4c2d90a134366c280eec6cb599825981ad5d
* Document last modified: 2021-03-15T17:55:56.000Z

</details>

**Comment by rachelandrew** [comment]
I think the issue here is that this is not a great demo. Not all values apply in all circumstances so it's really confusing.

I'll have a think about how I can make a demo that shows this in a better way. Probably have separate flex and grid demos would be the best thing.

Thanks for the report @danditomaso
