### ISSUE TITLE
outline-color: invert is still used in compatibility table

### ISSUE THREAD

**Issue by TrySound** [mdn/content#34452]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/outline-color

### What specific section or headline is this issue about?

Browser compatibility

### What information was incorrect, unhelpful, or incomplete?

invert keyword in the table should be auto

### What did you expect to see?

auto should be used instead of invert

### Do you have any supporting links, references, or citations?

https://github.com/mdn/content/pull/29798

**Comment by Josh-Cena** [comment]
It says all support is removed which is accurate because no browser supports `invert` anymore.

(For issues with the compat table, please use the "[Report problems with this compatibility data on GitHub](https://github.com/mdn/browser-compat-data/issues/new?mdn-url=https%3A%2F%2Fdeveloper.mozilla.org%2Fen-US%2Fdocs%2FWeb%2FCSS%2Foutline-color&metadata=%3C%21--+Do+not+make+changes+below+this+line+--%3E%0A%3Cdetails%3E%0A%3Csummary%3EMDN+page+report+details%3C%2Fsummary%3E%0A%0A*+Query%3A+%60css.properties.outline-color%60%0A*+Report+started%3A+2024-06-27T13%3A03%3A33.301Z%0A%0A%3C%2Fdetails%3E&title=css.properties.outline-color+-+%3CSUMMARIZE+THE+PROBLEM%3E&template=data-problem.yml)" link instead.)
