### ISSUE TITLE
[JS] GetOption reform for Intl.DisplayNames and Intl.ListFormat

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#3459]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated
3. - [x] Interactive example and data repos are updated if appropriate
4. - [x] The content has been reviewed as needed

## Features to document

1. Intl.DisplayNames and Intl.ListFormat options updates.

## Related Gecko bugs

1. - [x] [Implement GetOption reform for Intl.DisplayNames and Intl.ListFormat](https://bugzilla.mozilla.org/show_bug.cgi?id=1696881). Some updates to the options on the DisplayNames and ListFormat constructors. Not exactly sure what — some investigation needed.

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by hamishwillee** [comment]
I don't think this requires any documentation other than a release note stating that there is stricter checking that options values are actually valid objects, where previously passing a primitive like a string would fail silently.

Reasoning is below. I will see if I can get this confirmed with engineering.

This change adds stricter checking on the options that are passed to the [intl.ListFormat() constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat/ListFormat) and [Intl.DisplayNames() constructor](https://developer.mozilla.org//en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames/DisplayNames). Previously it would just try to coerce the value to an object, while now it will throw an error if something other than an object is passed. 

So, for example, previously if you were to pass a string as the option value it would fail silently, because the string would be coerced to an object, but the object wouldn't be a  meaningful. Now it will throw an error. An example of something that would fail now is the option string 'conjunction' below
```js
const formatter = new Intl.ListFormat('en', 'conjunction' );
```

Looking at the docs they already refer to the requirement for the options to be an object ("An object with some or all of the following properties:"). So for a user doing the right thing, there is no change. All the examples are correct. All the docs are correct.
-  I don't think this belongs in BCD because if you were compatible or incompatible before, you still are. It's just that now you know.
- The only place I might add something is if we had a section on exceptions.

**Comment by chrisdavidmills** [comment]
Done, so closing!
