### ISSUE TITLE
"strictly equal" confusion

### ISSUE THREAD

**Issue by John-Page** [mdn/content#34717]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Node/isSameNode

### What specific section or headline is this issue about?

Return value

### What information was incorrect, unhelpful, or incomplete?

It says " A boolean value that is true if both nodes are strictly equal"   Tis is technically correct under the definition of the === ("strictly equal") operator.   But a newbie might not make the connection and assume the node contents are being compared.       

### What did you expect to see?

Perhaps a better phrasing might be:
" Returns a boolean value of true if node and othrenode are  pointing to the same node"

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/node/issamenode`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Node/isSameNode
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/node/issamenode/index.md
* Last commit: https://github.com/mdn/content/commit/acfe8c9f1f4145f77653a2bc64a9744b001358dc
* Document last modified: 2023-07-07T07:19:19.000Z

</details>

**Comment by John-Page** [comment]
Yes you are right.  But the article is a little inconsistent.   In one
place it says "they are the same node" in the return value section it says
"strictly equal".   I think it should adhere to the "same node" wording
everywhere.    It is not wrong.  But an unnecessary trap for a newbie.
IMHO.

**Comment by Josh-Cena** [comment]
"The same" and "strictly equal" are synonyms. The intro description describes it in terms of semantics (that is, they are "the same") while the return value describes it in terms of mechanics (that is, it uses strict equality as the underlying algorithm). It's good for there to be varying terminology so you get a better picture of what exactly it does. Since the intro contains exactly this:

> is a legacy alias the [for the `===` strict equality operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Strict_equality). That is, it tests whether two nodes are the same

I think there's sufficient information that "strictly equal" and "are the same" are equivalent in this context.
