### ISSUE TITLE
keep 11 year old link?

### ISSUE THREAD

**Issue by estelle** [mdn/content#34820]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/unscopables

### What specific section or headline is this issue about?

Scoping in with statements

### What information was incorrect, unhelpful, or incomplete?

The code containing with (values) caused some websites to malfunction in Firefox when Array.prototype.values() was added ([Firefox Bug 883914](https://bugzil.la/883914)).

### What did you expect to see?

should we update the prose? That bug was fixed 11 years ago.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/symbol/unscopables`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/unscopables
* GitHub URL: https://github.com/mdn/content/blob/34817/merge/files/en-us/web/javascript/reference/global_objects/symbol/unscopables/index.md
* Last commit: https://github.com/mdn/content/commit/null
* Document last modified: 2020-11-22T21:00:46.702Z

</details>

**Comment by Josh-Cena** [comment]
This was just added in https://github.com/mdn/content/pull/34646. I insisted to add this reference to illustrate that the problem mentioned is not hypothetical and caused actual breakage. Since this behavior is exotic and people who land here are more interested in knowing the "why" than the "how" (the "how" is trivial), I think it should be kept. This entire paragraph is about history anyway.
