### ISSUE TITLE
Clarification needed: Absolute positioning behavior without specified offsets

### ISSUE THREAD

**Issue by ethanforvest** [mdn/content#34830]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/position

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/CSS/position#absolute

## Current Documentation

The MDN documentation for `position: absolute` currently states:

> The element is removed from the normal document flow, and no space is created for the element in the page layout. The element is positioned relative to its closest positioned ancestor (if any) or to the initial containing block. Its final position is determined by the values of top, right, bottom, and left.

## Observed Behavior

Through practical experimentation, I've found that when an element is set to `position: absolute` without specifying any offset properties (top, right, bottom, left), it behaves differently than the documentation suggests:

1. The element starts from its normal position in the document flow.
2. It is affected by its own margins.
3. It doesn't overlap preceding elements unless offset properties are used.

## Proposed Clarification

I suggest updating the documentation to clarify this behavior. A possible addition could be:

_However, when position: absolute is used without specifying offset properties (top, right, bottom, left), the element will start from its normal position in the document flow and will be affected by its own margins. In this case, it doesn't necessarily overlap other elements._

## Example Code

```html
<div class="relative h-20 w-20 bg-black">
  <div class="h-10 w-10 bg-red-600"></div>
  <div class="absolute mt-[10px] h-10 w-10 bg-green-600"></div>
</div>
```

In this example, the green div (absolutely positioned) appears below the red div, pushed down by its top margin, rather than overlapping it.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/position`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/position
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/position/index.md
* Last commit: https://github.com/mdn/content/commit/30e88f23503a7a18fae17c30182b93fa459a0465
* Document last modified: 2024-02-29T00:22:16.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi, this description is fully accurate.

> The element is removed from the normal document flow, and no space is created for the element in the page layout.

This is true and verifiable.

> The element is positioned relative to its closest positioned ancestor (if any) or to the initial containing block.

This is true; this is what `top` and `left`, etc. are based on: the position of its containing block.

> Its final position is determined by the values of top, right, bottom, and left.

This is also true and seems to be what your confusion comes from. You claim that:

> the element will start from its normal position in the document flow and will be affected by its own margins. In this case, it doesn't necessarily overlap other elements.

Well, since we claimed that its position is determined by top, right, bottom, and left, what are the default values of those properties? The pages for those properties will tell you that the default values are `auto`, and `auto` means (quoting `top`):

> for absolutely positioned elements, the position of the element is based on the [`bottom`](https://developer.mozilla.org/en-US/docs/Web/CSS/bottom) property, while `height: auto` is treated as a height based on the content; or if `bottom` is also `auto`, the element is positioned where it should vertically be positioned if it were a static element.

So, if both `top` and `bottom` are unspecified, the default position is indeed the starting position as if it's static. But, there's nothing special about this behavior: it's just because of the default behavior of `top` and `bottom`. You can explicitly specify `top: auto; bottom: auto` to achieve the same behavior. It's still fully accurate for the documentation to claim that the position is determined by top, right, bottom, and left.

Furthermore, I don't think the note about "overlap other elements" would be useful: no matter where you put the element, whether it overlaps with something else depends on whether there _is_ something else at that place, right? If you specify `position: absolute` without any inset properties, then this element will not have space in the page layout, and anything to the right of it in the page flow would move left and overlap with it:
