### ISSUE TITLE
The distinction between newer and older methods is incorrect

### ISSUE THREAD

**Issue by greggman** [mdn/content#35009]
https://github.com/mdn/content/blame/aa714bb37625b21b0f40db1f1ea557e773456fa2/files/en-us/web/javascript/reference/global_objects/array/index.md#L105

The document claims older methods skip unset elements, newer don't but then goes on to list some of the oldest methods such as `indexOf`, `slice`, `sort`, `splice` in the newer list.

**Comment by Josh-Cena** [comment]
We say "In general"—so it's a generalization. "Newer methods" always conflate empty slots (unless for consistency with older methods), while "older methods" are wildly inconsistent because there was no design principle back then. We already provide you with the exact list of methods that behave in each way, so I believe the current content is good enough.

**Comment by Josh-Cena** [comment]
Wait, `indexOf`, `slice`, `sort`, and `splice` are in the "Methods that have special treatment for empty slots include the following" list, which is the "old methods" list. Perhaps you are confusing the two groups?

**Comment by greggman** [comment]
![Screenshot 2024-07-23 at 17 22 24](https://github.com/user-attachments/assets/707b0e7e-efb3-42c7-8bbf-7aa1ad770197)

`join` is not a newer method AFAIK

**Comment by greggman** [comment]
I would also argue this distinction of "older" and "newer" is irrelevant trivia. No one reading MDN cares or is helped by the categories of "older" and "newer". Instead they're given trivia that only adds to their mental burden

"ignores empty slots" vs "does not ignore empty slots" would be better categories.

**Comment by Josh-Cena** [comment]
Yeah, the generalizations are not exact. The only generalization that you _may_ make is that "new -> no empty slot treatment". I don't agree to remove this though, because it is useful information about language development and how future APIs are designed.

**Comment by greggman** [comment]
It might be useful info to people developing languages but it is not useful info for people using MDN.

**Comment by Josh-Cena** [comment]
> Categories that imply "ignores empty slots" vs "does not ignore empty slots" would be better categories.

We say exactly this. These categories are not called "new methods" and "old methods", they are called "special-case empty slots" and "do not". "New" and "old" are remarks that may act as mnemonics.

**Comment by Josh-Cena** [comment]
> It might be useful info to people developing languages but it is not useful info for people using MDN.

This means you don't have to be burdened with remembering/checking this information for every method: you can remember a specific set that are "empty slot special-casing" and treat every other method as "empty slot conflating", because that's the default behavior for all future APIs. We first provide you with a consistent principle that array methods don't special-case empty slots, then and point out legacy cases where the consistency doesn't hold.
