### ISSUE TITLE
improper use of the word "lossy"

### ISSUE THREAD

**Issue by sean9999** [mdn/content#35040]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt

### What specific section or headline is this issue about?

The NOTE section under "Use with JSON"

### What information was incorrect, unhelpful, or incomplete?

The word "lossy" indicates loss of precision or fidelity. 

### What did you expect to see?

A better word in this context is "unreliable".

### Do you have any supporting links, references, or citations?

https://en.wikipedia.org/wiki/Lossy

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/bigint`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/bigint/index.md
* Last commit: https://github.com/mdn/content/commit/6e93ec8fc9e1f3bd83bf2f77e84e1a39637734f8
* Document last modified: 2024-07-13T00:55:27.000Z

</details>

**Comment by Josh-Cena** [comment]
"Lossy" is a synonym of "irreversible" in general, in other words non-bijective. It loses the precision of distinguishing between `{$bigint:1}` and `1n`, because both of them map to the same serialized representation.

Open to changing it to "irreversible" if you think it implies "compression", which it shouldn't in this context. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toJSON contains similar wordings that should be updated.
