### ISSUE TITLE
Link HTML style attribute with HTMLElement.style page

### ISSUE THREAD

**Issue by John-Page** [mdn/content#35205]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/style

### What specific section or headline is this issue about?

Return value

### What information was incorrect, unhelpful, or incomplete?

Return value is missing.    Should probably say that it returns  a a live [CSSStyleDeclaration](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration) object.   

It would also be useful to have a reference to https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/style which goes into depth about the property. 

### What did you expect to see?

A return value

### Do you have anything more you want to share?

Question:  When you respond to these and close the ticket, what happens to the suggestion? Is it discarded?

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/global_attributes/style`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/style
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/global_attributes/style/index.md
* Last commit: https://github.com/mdn/content/commit/926f83641b980fcda58914649748b0368eeca1cd
* Document last modified: 2024-07-25T21:15:52.000Z

</details>

**Comment by Josh-Cena** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/style is about how you write HTML.  https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/style is about how you read stuff in JS. They are totally different things. Agree they should be linked but there's nothing called "return value" in HTML; that's a JS thing.

> Question: When you respond to these and close the ticket, what happens to the suggestion? Is it discarded?

If an issue gets closed, it's either closed because it will not be worked on (explained by the comment), or because it's linked to a PR that resolves the issue.
