### ISSUE TITLE
Issue with "WindowOrWorkerGlobalScope.setTimeout()": parameters common errors

### ISSUE THREAD

**Issue by GhbSmwc** [mdn/content#3550]
I think it is worth noting that the arguments is **not what the user expects** and can lead to common mistake and resulting the function to be called immediately:
```
var timeoutID = scope.setTimeout(ExampleFunction(1, 2), 2000);
var timeoutID = scope.setTimeout(ExampleFunction(), 2000);
```
But in actuality, the arguments of ExampleFunction is “modified” so that the arguments are moved “one space/item to the right” so that the first item in the argument is the delay.

Source: https://stackoverflow.com/questions/20890943/javascript-settimeout-not-working

**Comment by Josh-Cena** [comment]
I don't think this should be explicitly called out. Through the many, many examples, we have clearly demonstrated that it accepts a _callback_, not a function that you call yourself. If someone doesn't understand what a callback means, they should probably learn some JS first. I understand that `setTimeout()` is so basic that beginners tend to use it before any other API, but it's not feasible for us to re-state the implications of callbacks on every page. Plus, `ExampleFunction()` may actually work, if it's a higher-order function. Because the issue has been open for so long, let's close it.
