### ISSUE TITLE
The super keyword and arrow function

### ISSUE THREAD

**Issue by woody-li** [mdn/content#35542]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/super

### What information was incorrect, unhelpful, or incomplete?

Add a new section to introduce the super and arrow function.

### What did you expect to see?

Example code:
```javascript
class Parent {
 render = () => {
  document.body.innerText = "Parent";
 };
}

class Child extends Parent {
 render = () => {
  document.body.innerText = "Child";
  super.render();
 };
}

var x = new Child();
x.render();
```

The super call will throw an error,  when the `render` function is both an arrow function in Child and Parent.
But either or both of them are normal functions; it works well.

### Do you have anything more you want to share?

I haven't found any description of the relationship between `super` and `arrow function`.
If the test result is correct, I hope to add some description to help others know it.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/super`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/super
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/super/index.md
* Last commit: https://github.com/mdn/content/commit/41cddfdaeed4a73fb8234c332150df8e54df31e9
* Document last modified: 2023-11-08T04:45:53.000Z

</details>

**Comment by Josh-Cena** [comment]
This is because you are using the `render = () =>` syntax, which does not create a property on `Parent.prototype`—rather, it directly creates an own property on each class instance. **This is a discouraged practice.** As you see here, `super.render()` will fail, because `super` seeks the property on the `CurrentClass.prototype.__proto__`, but this property does not exist there. It has little to do with arrow functions, but more to do with the use of class fields.

**Comment by Josh-Cena** [comment]
I realized we already have an example pertaining to this situation, at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/super#accessing_super_in_class_field_declaration:

> Note that instance fields are set on the instance instead of the constructor's `prototype`, so you can't use `super` to access the instance field of a superclass.
>
> ```js example-bad
> class Base {
>   baseField = 10;
> }
> 
> class Extended extends Base {
>   extendedField = super.baseField; // undefined
> }
> ```
>
> Here, `extendedField` is `undefined` instead of 10, because `baseField` is defined as an own property of the `Base` instance, instead of `Base.prototype`. `super`, in this context, only looks up properties on `Base.prototype`, because that's the [[Prototype]] of `Extended.prototype`.

Except you are wrapping the `super` in an arrow function, but that's not different because arrow functions don't create their own `super` reference.

**Comment by woody-li** [comment]
Got it. Thanks for your reply. @Josh-Cena
