### ISSUE TITLE
Issue with "Closures": (Closures are created every time a function is created)

### ISSUE THREAD

**Issue by HashBug** [mdn/content#3587]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures

#### What information was incorrect, unhelpful, or incomplete?

> "In JavaScript, closures are created every time a function is created, at function creation time."

There is no example provided to support this statement. 
How closure is created "at function creation time" is unclear.
It leads to the confusion that "Every function in JS is a closure".
If a function is called in the same scope in which it was declared, it is expected to access the state of that scope due to scope chaining. How closures play a role here?

#### Specific section or headline?
Closures
The intro paragraph

#### What did you expect to see?
An example to justify this statement must be provided.

#### Did you test this? If so, how?
Not Applicable

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/closures`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/closures/index.html
* Last commit: https://github.com/mdn/content/commit/3b80812a1d4f68e57f35fca763f50bf3e5dfe997
* Document last modified: 2021-02-19T19:57:02.000Z

</details>

**Comment by Josh-Cena** [comment]
"Closure" is a pretty implementation-level detail and does not have observable behaviors all the time. The typical illustration relies on "prolonged lifetime", i.e. a variable binding lives on within a function closure after exiting the scope it's defined in, but that doesn't mean normal functions don't create closures. Scope management is very tricky in JavaScript and engine implementers care about it a lot. It's even the reason why we can't get nice things like F#-style pipelines even when (virtually) most of the community is craving for it because implementers say it encourages the creation of too many closures.
