### ISSUE TITLE
Content suggestion: Add a page about inheritance with a list of CSS inheritable properties

### ISSUE THREAD

**Issue by rachelandrew** [mdn/content#3622]
I've been working on some content and it came up that it would be handy to have a list on MDN of inheritable CSS properties.

I could write a page on inheritance, but given we already have the info about inheritance [in the data](https://github.com/mdn/data/blob/master/css/properties.json), seems as if we could pull the list of properties with a script.

**Comment by jpmedley** [comment]
+1

**Comment by Josh-Cena** [comment]
The page is https://developer.mozilla.org/en-US/docs/Web/CSS/Inheritance. After the discussion in https://github.com/mdn/content/issues/27042, I think we are no longer interested in maintaining a list of properties because that could easily go out of sync. People could build their own reference based on webref, like in https://vallek.github.io/animatable-css/.
