### ISSUE TITLE
`content: contents` is unimplemented

### ISSUE THREAD

**Issue by LoneBoco** [mdn/content#36333]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

The draft spec says that `contents` is a valid value for the CSS `content` attribute, and the page lists it as a valid choice, but browsers don't actually support it.  I tried with at least Firefox and Edge and it is not a valid property in either.  I believe that the compatibility table should be updated to show that this attribute value does not work.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet), Firefox

### What did you expect to see?

I expected to see that browsers don't support `content: contents`.

### Did you test this? If so, how?

I tested this in Firefox and Edge (Chromium) by trying to use it.  Both browsers say that `contents` is an invalid property value and neither displays the expected results on the webpage.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/content

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.content`
* Report started: 2024-10-14T19:46:03.891Z

</details>

**Comment by Josh-Cena** [comment]
We may have another issue here. The formal syntax is pulling the definition of `<content-list>` from `css-gcpm` instead of `css-content`, so it's missing `contents`.

`content: contents` may be removed: https://github.com/w3c/csswg-drafts/issues/4632 but I don't see any progress. If there's indeed no implementation then we should remove it for now.
