### ISSUE TITLE
Missing "`TypeError`: Cannot convert `undefined` to object"

### ISSUE THREAD

**Issue by Rudxain** [mdn/content#36355]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors

### What specific section or headline is this issue about?

List of errors

### What information was incorrect, unhelpful, or incomplete?

Missing error message

### What did you expect to see?

"`TypeError`: Cannot convert `undefined` or `null` to object", which is the full message on NodeJS

### Do you have anything more you want to share?

```js
// fine
([].sort)();

(1 && [].sort)();
// Uncaught TypeError: Cannot convert undefined or null to object
//    at sort (<anonymous>)

let s = [].sort;
s();
// Uncaught TypeError: Cannot convert undefined or null to object
//    at sort (<anonymous>)
```

From what I understand, this happens because the `this` binding on `[]` is reset to `undefined`

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/errors`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/errors/index.md
* Last commit: https://github.com/mdn/content/commit/663cca3358acfd49ae11c1ca1d874ea447ba654a
* Document last modified: 2023-04-18T16:19:31.000Z

</details>

**Comment by Josh-Cena** [comment]
In Firefox the error message is "TypeError: can't convert undefined to object", so that would be what we document, but yes we are missing this. It can happen any time undefined or null is being coerced to an object. I am closing this though because we have a whole project for completing the errors reference: https://github.com/mdn/mdn/issues/505 thanks for bringing this up!
