### ISSUE TITLE
Browser compatibility section not showing.

### ISSUE THREAD

**Issue by BOUZE001** [mdn/content#36491]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/WebUSB_API

### What information was incorrect, unhelpful, or incomplete?

The browser compatibility section was previously shown, but in the last couple of weeks it disappeared 

### What did you expect to see?

Browser compatibility section with the compatibility table

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/webusb_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebUSB_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/webusb_api/index.md
* Last commit: https://github.com/mdn/content/commit/a10e3f00a346a0ec35380513f65915849d99f895
* Document last modified: 2024-10-08T19:33:59.000Z

</details>

**Comment by Josh-Cena** [comment]
There has never been a non-empty browser compat section for this page, because it is an API overview page. There used to be an empty section, which was removed 2 years ago: https://github.com/mdn/content/pull/17569 If you want to check browser compatibility for specific features, check their individual docs, such as https://developer.mozilla.org/en-US/docs/Web/API/USBDevice#browser_compatibility
