### ISSUE TITLE
[WebAPI] Implement dialog toggleevents for dialog open/close

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#36536]
## Acceptance criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes for enabled/preview features
- [x] Add/remove entry to Firefox experimental features page for preference/released features

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1876762

## Other

- [ ] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.

**Comment by hamishwillee** [comment]
I think this adds `beforetoggle` and `toggle` to `<dialog>` element matching the popover behaviour. The problem is the popover behaviour needs a bit of work - it doesn't mention the events in the docs. I also think the `<details>` is a little different than documented (it just does the `toggle`). I am confirming all of this in https://bugzilla.mozilla.org/show_bug.cgi?id=1876762#c14

Status:

- [ ] BCD - waiting on BCD team
- [ ] Docs (probably):
   - [ ] `HTMLElement.beforetoggle` and `toggle` - update to mention that `beforetoggle` is cancellable. This is important
   - [ ] Note that details should be the same `toggle` event AFAIK - not a custom one on `HTMLDetailsElement`
   - [ ] Check the popup docs and dialog docs mention the events in both element and APIs - might need to be "related events"
   - [ ] Add a live example?
- [ ] Release note
- [ ] dev-docs-complete

**Comment by keithamus** [comment]
Just to clarify here, for better visibility outside of bugzilla:

> I think this adds `beforetoggle` and `toggle` to `<dialog>` element matching the popover behaviour.

Correct.

> I also think the `<details>` is a little different than documented (it just does the `toggle`). 

This is correct also. All three will dispatch a `toggle` event using the `ToggleEvent` constructor, and have appropriate `newState` and `oldState` properties set - but only `popover` and (now) `<dialog>` elements will dispatch `beforetoggle` on show/hide. I will eventually get around to speccing/implementing `beforetoggle` for `<details>` but this is still TBD.

Also worth pointing out `beforetoggle` on show (or open if you prefer that terminology) will be _cancelable_. `beforetoggle` on _close_ is _not_ cancelable. The `toggle` event is _not cancelable_.

**Comment by hamishwillee** [comment]
Thank you @keithamus - much appreciated (one think I don't like about bugzilla is that you can't add an "acknowledged" or "thanks" without adding clutter to the discussion.

I'm working on this in https://github.com/mdn/content/pull/36606. Its taking a little longer than expected because I want to write a useful example.

**Comment by hamishwillee** [comment]
@keithamus Do you happen to know if/when these events are expected for Chromium and Safari?

**Comment by keithamus** [comment]
Flagged in Chrome 131, shipped in 132 https://chromestatus.com/roadmap.

I have a PR for Safari here: https://github.com/WebKit/WebKit/pull/23332 but it needs revisiting. I'll probably get around to it this month, but I don't know what the timelines will look like for Safari.

**Comment by keithamus** [comment]
Some potentially useful examples:

 - Make dialogs part of URL state: on `beforetoggle` where `newState` is `open`, call `replaceState()` with an anchor of the dialog name, and add the equivalent opening code for `onload`.
 - Animation fixups: add or remove classes to the `<dialog>` on `beforetoggle`/`toggle` which can help with animations.
 - Popover fixups: on `beforetoggle` find all `popover=manual` and call `.hidePopover()` on them.
 - Form fixups: on `toggle` where `newState` is `closed`, call `dialog.querySelector('form').reset()` or other state-resetting functionality to ensure when the dialog is re-opened it is set to its initial state.

**Comment by hamishwillee** [comment]
Thanks @keithamus .

1. I'm not so ambitious in my examples - the main thing I have done is added simple live examples showing how they are called, such as this one: https://pr36606.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/HTMLDialogElement#opening_a_modal_dialog
It would be good do try some of these, but not in this round.

2. I did take those suggestions and make them as examples in the [beforetoggle](https://pr36606.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/HTMLElement/beforetoggle_event) introduction

3. Most of the work has been making the events "not popover centric" and working on how to show them in the docs for the elements they are fired on - since they are inherited that makes them a bit invisible using our normal patterns.
