### ISSUE TITLE
Promise.prototype.then() method, if the parameters onFulfilled and onRejected are not functions, they should be ignored.

### ISSUE THREAD

**Issue by scrapooo** [mdn/content#36538]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then

### What specific section or headline is this issue about?

Parameters

### What information was incorrect, unhelpful, or incomplete?

![image](https://github.com/user-attachments/assets/64dfa32d-5a14-4c76-94d7-74e696284418)

![image](https://github.com/user-attachments/assets/589cfa6e-88d4-4576-a87e-ebfab710cf92)

### What did you expect to see?

The red-marked areas in the two screenshots are incorrect. According to the specifications, if onFulfilled and onRejected are not functions, they should be ignored rather than being converted to x=>x or x=>{throw new Error(x);}. The second screenshot shows the execution results, which do not match the documentation in the first screenshot.

**Image 1**
![image](https://github.com/user-attachments/assets/64dfa32d-5a14-4c76-94d7-74e696284418)

**Image 2**
![image](https://github.com/user-attachments/assets/589cfa6e-88d4-4576-a87e-ebfab710cf92)

### Do you have any supporting links, references, or citations?

https://promisesaplus.com/#the-then-method
![image](https://github.com/user-attachments/assets/5fb13d9f-8830-44ac-bc95-d4de807cae5b)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/promise/then`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/promise/then/index.md
* Last commit: https://github.com/mdn/content/commit/5c55770dc681e7855fe960cf6a725d4c7be4e95f
* Document last modified: 2024-07-18T01:34:38.000Z

</details>

**Comment by Josh-Cena** [comment]
I don't think the current doc is saying anything different from what you are saying. "The parameter is ignored" means passing any value must be equivalent to passing `undefined` or not passing this value at all. This means `Promise.resolve(x).then()` is equivalent to `Promise.resolve(x).then(1)`, and since the default values of `onFulfilled` and `onRejected` are just `(x) => x` and `(x) => { throw x; }`, anything you pass is effectively ignored and converted to the default value. Check out the spec: https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-newpromisereactionjob
