### ISSUE TITLE
Features that shipped in stable Firefox are included

### ISSUE THREAD

**Issue by o-t-w** [mdn/content#36742]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features

### What information was incorrect, unhelpful, or incomplete?

This page lists many features that have shipped in the stable version of Firefox, which makes it confusing. COLRv1 fonts is one example. backdrop-filter is another. 

### What did you expect to see?

This page should only list experimental features.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/firefox/experimental_features`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/firefox/experimental_features/index.md
* Last commit: https://github.com/mdn/content/commit/1f8e00821b6a18996dd58f32c7adedfe8902bdae
* Document last modified: 2024-10-29T11:21:35.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks @o-t-w 

@Rumyra @bsmth This is a valid point. I grepped on the preferences and then searched on their values in the source - quite a lot of things are out of date. I'm adding this to a release project so we can start tidying it up. It isn't as simple as fixing this doc - there might be errors in the compatibility data too.

For the list below:
- `FALSE` - data is correct in doc (feature still experimental)
- `TRUE` - data is incorrect in doc as this is released. Check BCD. Remove.
- `NOTPRESENT` - pref not present, so is _probably true_. But might not be. Check BCD and work out from there.
- NIGHTLY - data should be in expr features, but lets check bcd and that it says nightly

The list:

- [ ] FALSE layout.forms.input-type-search.enabled
- [ ] FALSE layout.forms.reveal-password-button.enabled
- [ ] NOTPRESENT layout.css.control-characters.enabled or ?? layout.css.control-characters.visible
- [ ] FALSE layout.css.initial-let
- [ ] FALSE layout.forms.input-type-search.enabled
- [ ] FALSE layout.forms.reveal-password-button.enabled
- [ ] NOTPRESENT layout.css.control-characters.enabled or ?? layout.css.control-characters.visible
- [ ] FALSE layout.css.initial-letter.enabled
- [ ] TRUE layout.css.relative-color-syntax.enabled
- [ ] NOTPRESENT layout.css.aspect-ratio-number.enabled
- [ ] TRUE layout.css.backdrop-filter.enabledter.enabled
- [ ] TRUE layout.css.relative-color-syntax.enabled
- [ ] NOTPRESENT layout.css.aspect-ratio-number.enabled
- [ ] TRUE layout.css.backdrop-filter.enabled
- [ ] FALSE layout.css.fit-content-function.enabled
- [ ] FALSE layout.css.scroll-driven-animations.enabled
- [ ] FALSE layout.css.at-scope.enabled
- [ ] TRUE layout.css.font-tech.enabled
- [ ] NIGHTLY layout.css.font-variant-emoji.enabled
- [ ] TRUE layout.css.page-orientation.enabled
- [ ] FALSE layout.css.prefers-reduced-transparency.enabled
- [ ] FALSE layout.css.inverted-colors.enabled
- [ ] FALSE layout.css.scroll-driven-animations.enabled
- [ ] TRUE layout.css.zoom.enabled
- [ ] TRUE layout.css.text-wrap-balance.enabled, ? layout.css.text-wrap-balance.limit, TRUE layout.css.text-wrap-balance-after-clamp.enabled
- [ ] TRUE layout.css.prefixes.transforms
- [ ] FALSE layout.css.prefixes.transitions
- [ ] NOT NIGHTLY ???? layout.css.h1-in-section-ua-styles.enabled
- [ ] NIGHTLY layout.css.basic-shape-shape.enabled
- [ ] TRUE layout.css.starting-style-at-rules.enabled
- [ ] CHECK - depends on version/not sure what means false: layout.css.letter-spacing.model
- [ ] TRUE layout.css.relative-color-syntax.enabled
- [ ] FALSE layout.css.anchor-positioning.enabled
- [ ] NOTPRESENT dom.svg.pathSeg.enabled
- [ ] FALSE javascript.options.experimental.promise_try
- [ ] FALSE javascript.options.experimental.json_parse_with_source
- [ ] NIGHTLY dom.cookieStore.enabled
- [ ] FALSE dom.fetchKeepalive.enabled
- [ ] FALSE dom.closewatcher.enabled
- [ ] NOTPRESENT canvas.hitregions.enabled
- [ ] NIGHTLY dom.webgpu.enabled
- [ ] FALSE dom.reporting.enabled
- [ ] FALSE media.mediasource.experimental.enabled
- [ ] CHECK 1: Normal. image.avif.compliance_strictness
- [ ] TRUE gfx.font_rendering.colr_v1.enabled
- [ ] NIGHTLY dom.customHighlightAPI.enabled
- [ ] TRUE dom.serviceWorkers.navigationPreload.enabled
- [ ] FALSE dom.vr.enabled
- [ ] NIGHTLY dom.shadowdom.selection_across_boundary.enabled
- [ ] CHECK TRUE except andorid  media.setsinkid.enabled
- [ ] FALSE media.track.enabled
- [ ] NIGHTLY/EARLY RELESE layout.css.convertFromNode.enable
- [ ] NIGHTLY layout.css.getBoxQuads.enabled
- [ ] FALSE dom.payments.request.enabled and
- [ ] FALSE (Early beta windows, otherwise false) dom.webshare.enabled
- [ ] NIGHTLY dom.screenorientation.allow-lock
- [ ] Check - True XP_WIN, Nighty otherwise - NIGHTLY/XPWIN:  dom.webnotifications.requireinteraction.enabled
- [ ] FALSE security.mixed_content.block_object_subrequest
- [ ] NIGHTLY IS TRUE security.insecure_connection_text.enabled for normal browsing mode;  security.insecure_connection_text.pbmode.enabled for private browsing mode
- [ ] FALSE dom.security.featurePolicy.header.enabled
- [ ] TRUE permissions.media.query.enabled
- [ ] NOTPRESENT privacy.clearsitedata.cache.enabled
- [ ] CHECK dsable android, "normal" other.:  dom.origin-trials.private-attribution.state 
- [ ] FALSE image.jxl.enabled
- [ ] FALSE network.cookie.sameSite.laxByDefault
- [ ] TRUE network.cors_preflight.authorization_covered_by_wildcard
- [ ] TRUE devtools.webconsole.input.context
- [ ] NOTPRESENT devtools.netmonitor.features.serverSentEvents
- [ ] NOTPRESENT devtools.inspector.ruleview.inline-compatibility-warning.enabled
- [ ] TRUE apz.allow_zooming and (on Windows) TRUE apz.windows.use_direct_manipulation

**Comment by bsmth** [comment]
Thanks, all. I had a look for anything in your NOTPRESENT column, and can't find much information in source / bugzilla, so I think most of these have been removed or supported a long time ago. The `layout.css.control-characters.visible` preference, I believe is [the correct variant](https://searchfox.org/mozilla-central/source/modules/libpref/init/StaticPrefList.yaml#9270).

Exception looks like SSE, I don't see the pref at all, but there's a bug here tracking it: https://bugzilla.mozilla.org/show_bug.cgi?id=1405706

**Comment by hamishwillee** [comment]
All done. Just waiting for the last parts to be  reviewed.

**Comment by hamishwillee** [comment]
This should all now be up to date. Thanks for reporting @o-t-w
