### ISSUE TITLE
Window `updateCommands()` method wrong

### ISSUE THREAD

**Issue by T34-active** [mdn/content#36974]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/updateCommands

### What information was incorrect, unhelpful, or incomplete?

Updates the state of commands of the current chrome window (UI).
Does this sentence need to be changed to
"Updates the state of commands of the current FireFox window (UI)."
Because Chrome no longer supports this method.

### What did you expect to see?

need update content.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/window/updatecommands`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/updateCommands
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/updatecommands/index.md
* Last commit: https://github.com/mdn/content/commit/20c51db7895b1b6f41d4fa90e71830f4b6678eea
* Document last modified: 2024-09-05T05:42:29.000Z

</details>

**Comment by wbamberg** [comment]
This uses "chrome" in the old meaning of "chrome window", meaning the window that implements the browser UI (address bars, back/forward buttons etc) in [XUL](https://en.wikipedia.org/wiki/XUL). So it's technically correct, _however_ although this function still apparently exists I don't think this documentation is usable and I wouldn't be surprised if the function isn't usable either, since AFAIK Firefox doesn't use XUL any more either. See also https://www-archive.mozilla.org/editor/editor_commands.

So I would vote to delete this page!
