### ISSUE TITLE
padding-inline-start is said to correspond to padding-top in English

### ISSUE THREAD

**Issue by Nallebeorn** [mdn/content#37082]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/padding-inline-start

### What specific section or headline is this issue about?

Values

### What information was incorrect, unhelpful, or incomplete?

All the logical padding properties are said to correspond to `padding-top` in English, which is of course not true.

### What did you expect to see?

`padding-inline-start` corresponds to `padding-left`. `padding-inline-end` corresponds to `padding-right`, and `padding-block-end` to `padding-bottom`.

### Do you have any supporting links, references, or citations?

MDN itself ;) https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_logical_properties_and_values/Margins_borders_padding

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/padding-inline-start`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/padding-inline-start
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/padding-inline-start/index.md
* Last commit: https://github.com/mdn/content/commit/4c978094f227c40bd49a1d71fd494884c6fbeea1
* Document last modified: 2024-03-11T15:56:31.000Z

</details>

**Comment by OnkarRuikar** [comment]
I think the author used "corresponds to" to convey that these properties behave (in terms of accepted values and applicable target elements) similarly to the `padding-top` property. [[ref](https://drafts.csswg.org/css-logical/#padding-properties)]\
However, due to the added extra information in the statement, the statement sounds wrong.

To avoid confusion, the statements must use corresponding top/right/bottom/left properties instead of `padding-top`.

**Comment by wbamberg** [comment]
I don't see where in https://developer.mozilla.org/en-US/docs/Web/CSS/padding-inline-end, https://developer.mozilla.org/en-US/docs/Web/CSS/padding-block-end, or https://developer.mozilla.org/en-US/docs/Web/CSS/padding-block-start it says that the properties _correspond to_ padding-top, can you show me?

These pages do say that the properties _take the same values as_ padding-top, which is correct per spec: https://drafts.csswg.org/css-logical/#padding-properties.

> ## What did you expect to see?
>
> padding-inline-start corresponds to padding-left. padding-inline-end corresponds to padding-right, and padding-block-end to padding-bottom.

That would be wrong as a general statement, because what they correspond to depends on [writing-mode](https://developer.mozilla.org/en-US/docs/Web/CSS/writing-mode), [direction](https://developer.mozilla.org/en-US/docs/Web/CSS/direction), and [text-orientation](https://developer.mozilla.org/en-US/docs/Web/CSS/text-orientation), as the page says.

**Comment by Nallebeorn** [comment]
> I don't see where in https://developer.mozilla.org/en-US/docs/Web/CSS/padding-inline-end, https://developer.mozilla.org/en-US/docs/Web/CSS/padding-block-end, or https://developer.mozilla.org/en-US/docs/Web/CSS/padding-block-start it says that the properties _correspond to_ padding-top, can you show me?
> 
> These pages do say that the properties _take the same values as_ padding-top, which is correct per spec: https://drafts.csswg.org/css-logical/#padding-properties.
> 
> > ## What did you expect to see?
> > padding-inline-start corresponds to padding-left. padding-inline-end corresponds to padding-right, and padding-block-end to padding-bottom.
> 
> That would be wrong as a general statement, because what they correspond to depends on [writing-mode](https://developer.mozilla.org/en-US/docs/Web/CSS/writing-mode), [direction](https://developer.mozilla.org/en-US/docs/Web/CSS/direction), and [text-orientation](https://developer.mozilla.org/en-US/docs/Web/CSS/text-orientation), as the page says.

Sorry, only the `inline-start` page says this ("En English, a left-to-right top-to-bottom language, the padding-inline-start property for this paragraph of text corresponds to the padding-top property"). When checking the other pages to see if they had the same problem, I somehow mistook the sentence about taking the same _values_ as padding-top (which is correct) as saying the same thing. My bad.

It would make sense for all four pages to have the same description structure of course. Personally, I think giving a concrete example of the corresponding physical property for a specific language like the description for `inline-start` does is a good aid for understanding the use of it, and English is the most reasonable example when that's the language the page is written in.
