### ISSUE TITLE
Issue with "Debug scrollable overflow": Page describes feature that either does not exist or is broken

### ISSUE THREAD

**Issue by jtiscione** [mdn/content#3723]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Debug_Scrollable_Overflow

#### What information was incorrect, unhelpful, or incomplete?

Page describes a feature that either does not exist or is broken.

#### Specific section or headline?

"You can toggle the scroll badge to highlight elements causing an overflow, expanding nodes as needed to make the nodes visible"

#### What did you expect to see?

Some sort of reaction when I click on the badge- toggling, highlighting, anything.

#### Did you test this? If so, how?

Tried it on a page with a component somewhere that is triggering scrolling. The badge ignores mouse clicks entirely. Double-clicking doesn't do anything either.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/page_inspector/how_to/debug_scrollable_overflow`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Debug_Scrollable_Overflow
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/page_inspector/how_to/debug_scrollable_overflow/index.html
* Last commit: https://github.com/mdn/content/commit/05b71a290b2ab444b23e0f35f619d93203c7e2d8
* Document last modified: 2021-02-02T16:31:29.000Z

</details>

**Comment by ddbeck** [comment]
Hi, I'm closing this issue because [Firefox DevTools User Docs](https://firefox-source-docs.mozilla.org/devtools-user/index.html#firefox-devtools-user-docs) have moved off of MDN (see https://github.com/mdn/content/pull/14140 for details on content moved). If this issue is still applicable to the relocated documentation, please see the Firefox Source Docs site for details on raising bugs and contributing. Thanks for your understanding!
