### ISSUE TITLE
Use of "Declare" instead of "Define" in explaining the code

### ISSUE THREAD

**Issue by alirezatc** [mdn/content#37351]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Async_JS/Introducing

### What specific section or headline is this issue about?

Synchronous programming

### What information was incorrect, unhelpful, or incomplete?

Declares a string called name.
Declares another string called greeting, which uses name.

### What did you expect to see?

Defines a string called name.
Defines another string called greeting, which uses name.

### Do you have anything more you want to share?

A variable declaration is when you specify a type and an identifier but have not yet assigned a value to the variable. A variable definition is when you assign a value to a variable, typically with the assignment operator =. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn_web_development/extensions/async_js/introducing`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Async_JS/Introducing
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn_web_development/extensions/async_js/introducing/index.md
* Last commit: https://github.com/mdn/content/commit/5b20f5f4265f988f80f513db0e4b35c7e0cd70dc
* Document last modified: 2024-12-19T15:37:45.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi there, thanks for your suggestion about terminology preciseness. While I agree there's a subtle difference between declaration and definition, "definition" is not a term precisely defined on MDN. "Declaration" and "initialization" are, but only in the context of talking about hoisting and separate declaration and initialization. For constant variables, there's no difference between any of these terms since one always implies the other.ore practically, even if we fix this sporadic case, it is impossible for us to fix all of them and more importantly enforce it as a rule in the future, so in general we give such freedom of terminology to each writer's discretion and do not emphasize on individual word choices. This is similar to our established decision that we will not make a formal differentiation between "parameter" and "argument".
