### ISSUE TITLE
Issue with "Conditional (ternary) operator": (short summary here please)

### ISSUE THREAD

**Issue by DaleLacey** [mdn/content#3775]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator

#### What information was incorrect, unhelpful, or incomplete?

The statement that the "[ternary] operator is frequently used as a shortcut for the if statement"

#### What did you expect to see?
The "[ternary] operator is frequently used as a shortcut for an if/else structure"

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/conditional_operator`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/conditional_operator/index.html
* Last commit: https://github.com/mdn/content/commit/3b80812a1d4f68e57f35fca763f50bf3e5dfe997
* Document last modified: 2021-02-19T19:57:02.000Z

</details>

**Comment by CreaTorAlexander** [comment]
Hello @DaleLacey, thanks for coming up with this. I would say that it is correct because we are talking about the *if statement*. In my opinion this is the name of it, the else part is used in the *if statement* to specify a new condition to test if the condition before is false.

In the [referenced article](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/if...else) it is also called the if statement 

> The if statement executes a statement if a specified condition is truthy. If the condition is falsy, another statement can be executed.

**Comment by sideshowbarker** [comment]
Opened #11099 with a refinement.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
