### ISSUE TITLE
Issue with "Hit regions and accessibility": Hit regions are deprecated

### ISSUE THREAD

**Issue by ovikk13** [mdn/content#3780]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Hit_regions_and_accessibility

#### What information was incorrect, unhelpful, or incomplete?
"Hit regions" are described as experimental, but looking at [documentation for addHitRegion](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/addHitRegion) it is marked as deprecated.

Also the referenced [code pen](https://codepen.io/peterj35/pen/PEdLKx) does not work in Chrome version 89.0.4389.114 or Firefox version 87.0.

#### Specific section or headline?
The section describing "Hit regions".

#### What did you expect to see?
This section should either be marked as deprecated, rephrased or removed.

#### Did you test this? If so, how?
Codepen tested in Firefox 87 and Chrome 89.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/canvas_api/tutorial/hit_regions_and_accessibility`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Hit_regions_and_accessibility
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/canvas_api/tutorial/hit_regions_and_accessibility/index.html
* Last commit: https://github.com/mdn/content/commit/63c69f3c933acbea9bfb24d359a7d2ffdb3c0bea
* Document last modified: 2021-02-19T19:51:22.000Z

</details>

**Comment by ScriptAutomate** [comment]
Here is where a broken link can be found for `Hit regions and accessibility`:
- [Canvas API Tutorial](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial)

Here is the dead link:
- [Hit regions and accessibility](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Hit_regions_and_accessibility)

Here it is on the internet archive:
- [Internet archive of MDN: Hit regions and accessibility](https://web.archive.org/web/20210512193630/https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Hit_regions_and_accessibility)

Is this section meant to no longer exist in the MDN docs? For example, I searched and found this ref:
https://github.com/mdn/content/blob/fea5d0b94a2bf00495b2f075731fd93ef837fb4d/files/en-us/mozilla/firefox/releases/39/index.html#L66

I'm following up since I have a broken link to these docs in our reference docs, and wasn't sure what to update it to.

**Comment by teoli2003** [comment]
Thanks. I opened a PR to get this fixed.

**Comment by teoli2003** [comment]
And another one to remove the broken link in MDN Web docs.
