### ISSUE TITLE
Issue with "Web Audio playbackRate explained": (Note: pitch of the audio track does not change, for video only)

### ISSUE THREAD

**Issue by mattgilbertnet** [mdn/content#3783]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery/WebAudio_playbackRate_explained

#### What information was incorrect, unhelpful, or incomplete?

One of the notes says "The pitch of the audio track does not change when playBackRate is altered." This is true for video elements, like [the example provided](https://jsbin.com/UGIxoJis/1/edit?html,output). However, it's not true for audio elements, like [this example](https://mdn.github.io/webaudio-examples/decode-audio-data/).

Ideally, links to examples of both types would be provided, along with a more detailed note.

#### Specific section or headline?
Notes

#### What did you expect to see?
The pitch of the audio track changes when playBackRate is altered for audio elements, but not for video elements.

#### Did you test this? If so, how?
I compared the relationship between pitch and playback rate with these two examples:
- https://jsbin.com/UGIxoJis/1/edit?html,output
- https://mdn.github.io/webaudio-examples/decode-audio-data/

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/guide/audio_and_video_delivery/webaudio_playbackrate_explained`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery/WebAudio_playbackRate_explained
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/guide/audio_and_video_delivery/webaudio_playbackrate_explained/index.html
* Last commit: https://github.com/mdn/content/commit/603be04cb59a2eff5c2eda7f330a190e12fc2810
* Document last modified: 2020-12-30T11:38:24.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can update this 👍

**Comment by mattgilbertnet** [comment]
It's possible that this is dependent on the audio format of the video file, but I'm not sure.

**Comment by wbamberg** [comment]
I think this is not correct.

The spec is clear that the `<audio>`and `<video>` elements should (by default) preserve the pitch when `playbackRate` is changed: https://html.spec.whatwg.org/multipage/media.html#dom-media-playbackrate . There's no suggestion that it should be different for audio and for video, or that the format should make a difference.

I think what's happening with the example quoted: https://mdn.github.io/webaudio-examples/decode-audio-data/ is that this example isn't using the [`HTMLMediaElement`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/) interface (which is the relevant interface described in https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery/WebAudio_playbackRate_explained). It's using the [`AudioBufferSourceNode`](AudioBufferSourceNode) interface, which says nothing about pitch preserving.

If I use the same audio file in an `<audio>` element, I can adjust `playbackRate` and preserve pitch: https://codepen.io/willbamberg/pen/JjMRbbQ?editors=1111.

One real issue is that https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/playbackRate says:

> The pitch of the audio is corrected by default and is the same for every speed. Some browsers implement the non-standard [HTMLMediaElement.preservesPitch]() property to control this.

It looks like `preservesPitch()` is now standard (not supported in Firefox, but it is in Chrome) and probably deserves a page. (More info: https://bugzilla.mozilla.org/show_bug.cgi?id=1652950).

Maybe we should file a separate issue for that though?

**Comment by wbamberg** [comment]
It turns out that we have BCD for `preservesPitch`, which makes things easier: https://github.com/mdn/browser-compat-data/blob/2a845c8742b274407cad0011cfd836dddd04061d/api/HTMLMediaElement.json#L2664.

**Comment by wbamberg** [comment]
> It looks like `preservesPitch()` is now standard (not supported in Firefox, but it is in Chrome) and probably deserves a page. (More info: https://bugzilla.mozilla.org/show_bug.cgi?id=1652950).
> 
> Maybe we should file a separate issue for that though?

I filed https://github.com/mdn/content/pull/14183 to add this.
