### ISSUE TITLE
Issue with "String.prototype.matchAll()": using const instead of var

### ISSUE THREAD

**Issue by similg** [mdn/content#3798]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/matchAll

#### What information was incorrect, unhelpful, or incomplete?
for (const match of matches)

#### Specific section or headline?
"match" will vary and cannot be declared as const

#### What did you expect to see?
let

#### Did you test this? If so, how?
tested in the console

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/string/matchall`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/matchAll
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/string/matchall/index.html
* Last commit: https://github.com/mdn/content/commit/3e7b6ed203995b2a8b25e0e77754ffc80d08c3e5
* Document last modified: 2021-03-19T03:44:26.000Z

</details>

**Comment by sideshowbarker** [comment]
> "match" will vary and cannot be declared as const

That’s actually not correct.

To be clear for the record here, the following code is fine:
```js
for (const match of matches) {
  console.log(`Found ${match[0]} start=${match.index} end=${match.index + match[0].length}.`);
}
```
The reason is: `for (const match of matches)` results in a separate new block scope for every iteration, and so a new `match` variable gets created for each iteration — a different `match` variable than any that were created in previous iterations.

So while it’s also possible to write it with `for (let match of matches)` instead, it doesn’t matter.

See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of#iterating_over_an_jsxrefarray

And see https://tc39.es/ecma262/#sec-for-in-and-for-of-statements, which has this production:

> _ForDeclaration_[Yield, Await] :
> &nbsp;&nbsp;_LetOrConst_ _ForBinding_[?Yield, ?Await]

Note the _LetOrConst_ there.
