### ISSUE TITLE
Remove empty space before end p tag

### ISSUE THREAD

**Issue by hamishwillee** [mdn/content#386]
Minor thing that might be done is to search/replace on any whitespace before `</p>`.
It will affect a lot of pages, so perhaps as part of some other big tidy

**Comment by chrisdavidmills** [comment]
Ths is the kind of fix that maybe @nschonni would like to jump on.

**Comment by nschonni** [comment]
Might be something for the "fixable flaws". Since indentation can be context sensitive. I think there was a previous discussion around figuring out tooling.

**Comment by peterbe** [comment]
If it's bound to reoccur, let's make it a flaw. Like, for example, people picking image attachments that aren't sufficiently compressed. It'll happen again. Sooner or later. Writing some big search-and-replace or scripts that do tens or even up to a hundred pages per PR, would always be quicker. 

Today, writing a new flaw is a bit involved. You need the code that finds them, the code that displays them in the Toolbar UI, and (possibly) the code that can automatically fix them. 
It's a shame it's so involved and it would be cool if it could be as easy as downloading or preff'ing on a plugin and it just slots in. We'll maybe get there. 

The other big piece to think about with flaws is that a lot of times you don't want to be so "binary". There are many "flaws" that are unfortunately so complicated that it's impossible to have 100% confidence that it's a flaw. For example, spelling flaws would be tricky because it's not unrealistic that certain words are "wrong deliberately" or simply words that are too technical for any cspell (or alike) to be aware of yet. 

So let's keep in mind; when flaws becomes v2.0, what do we want most/first: plugin architecture or the ability to elevate warnings?

**Comment by himanshugarg** [comment]
Is this still an issue after the markdown?

**Comment by hamishwillee** [comment]
I'm going to close this. There are separate issues tracking the addition of markdown linters - they will cover this case.
