### ISSUE TITLE
Issue with "Introduction to the server side": (Just a general comment on the organization of the references)

### ISSUE THREAD

**Issue by justdomdev** [mdn/content#3871]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/First_steps/Introduction

I find the content arrangement of the MDN docs confusing. At least there should be one master table for it's contents for us not to get confused as where we are already in the process of learning new information.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/first_steps/introduction`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/First_steps/Introduction
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/first_steps/introduction/index.html
* Last commit: https://github.com/mdn/content/commit/d58e4ec242ece685a791bf055b1a19b2772bc6e4
* Document last modified: 2021-03-28T11:07:55.000Z

</details>

**Comment by chrisdavidmills** [comment]
@justdomdev Thank you for the feedback. Unfortunately organizing a site as huge as MDN into a single sidebar or table is very challenging, and would probably end up being more confusing rather than less.

Instead, we elected to have different sidebars for each major section of MDN. The sidebar you see on the page you've linked contains all of the content available inside the /Learn/ document tree.

I wonder if a bit of rearrangement might make for a easier learning experience, and for example a table that shows you where you are in the journey a bit more effectively.

If you've got any specific examples of what you'd like to see done better, or are able to express specific bits of content that leave you with confusion (and what that confusion is), that'd be really interesting and helpful.

Thanks again.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/3871#issuecomment-814016561
