### ISSUE TITLE
Issue with "<input>: The Input (Form Input) element": broken link (see correct version)

### ISSUE THREAD

**Issue by Dorin-David** [mdn/content#3933]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input

#### What information was incorrect, unhelpful, or incomplete?
A link that should point to a local path is broken

#### Specific section or headline?
**"Individual attributes"**, under **type**
In the source code, the error is at the line **727**

#### What did you expect to see?

The correct path should be **#input_types**, NOT  #<input>_types
I wanted to open a PR but I'm not familiar with the markup you use in the repositories, so I've just opened an issue. 

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/input`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/index.html
* Last commit: https://github.com/mdn/content/commit/690965e33f6663ef450e6ed9edd9a7e7f73f96c5
* Document last modified: 2021-03-27T00:58:07.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened https://github.com/mdn/content/pull/3935 with a fix.

> I wanted to open a PR but I'm not familiar with the markup you use in the repositories, so I've just opened an issue.

Yeah the `{{…}}` macro stuff is arcane. But (for future reference), any time you run into broken links that seem to be caused by one of those `{{…}}` macros in the source, it is always fine to just replace it with a normal HTML `<a>` anchor element — like I did here:

```diff
- <p>Permitted values are listed in {{anch("&lt;input&gt; types", "<code>&lt;input&gt;</code> types")}} above.</p>
+ <p>Permitted values are listed in <a href="#input_types">Input types</a> above.</p>
```
In fact, that’s preferable — because we’re actually trying move away as much as we can from using those `{{…}}` macros.

**Comment by Dorin-David** [comment]
Great! Thanks for the tip Michael. I was actually wondering what kind of sorcery was that. Next time I will replace it with a normal link.
