### ISSUE TITLE
Content bug: Comparison to undefined

### ISSUE THREAD

**Issue by wbt** [mdn/content#3977]
## What page(s) did you find the problem on?
Various Javascript examples

## What is the problem?
Comparison to undefined can sometimes lead to unexpected results.
See https://eslint.org/docs/rules/no-undefined for details.

## What did you expect to see?
In code examples, use `if( typeof x === 'undefined')` instead of `if( x === undefined)`
PR #3943 is an example of fixing this on one page, but a more thorough review over the whole docs base could be useful.

MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript

**Comment by CreaTorAlexander** [comment]
I can work on this issue 👍

**Comment by Josh-Cena** [comment]
My take on this: I would gladly review someone's work on this, but I won't recommend anyone to spend much time replacing `x === undefined` with `typeof x === "undefined"`.

The code examples on MDN are self-contained: they don't assume the existence of other code, and especially don't assume that it's placed under a child scope of _part_ of a bigger code. Therefore, shadowing global names would be extremely uncommon. Ever since ES5, it's not possible to rewrite `globalThis.undefined` either, making the `undefined` value virtually impossible to be spoofed. The security value of avoiding `undefined` has declined over time, and `no-undefined`'s doc is also recommending alternatives:

> As an alternative, you can use the [no-global-assign](https://eslint.org/docs/latest/rules/no-global-assign) and [no-shadow-restricted-names](https://eslint.org/docs/latest/rules/no-shadow-restricted-names) rules to prevent undefined from being shadowed or assigned a different value. This ensures that undefined will always hold its original, expected value.

The two rules here are far more popular (and also enabled by `eslint-config-airbnb`) than `no-undefined`. `no-undefined` IMO is an obsolete rule today.

OTOH, replacing `undefined` with `typeof` does not either improve or subtract readability—it may be slightly harder for new learners to comprehend, and it may be longer to type, but I won't stop people from doing such changes. I just would like to point out the low ROI in doing so.

**Comment by sideshowbarker** [comment]
I agree with https://github.com/mdn/content/issues/3977#issuecomment-1177257263 — and given that this issue has been open for more than a year without anybody picking up work on it, it seems likely it would just continue remain open for much longer without any activity.

Therefore, I’m making a judgement call and going ahead and closing this. If it turns out anybody feels strongly otherwise, it could be re-opened.
