### ISSUE TITLE
Issue with "flex-basis": (short summary here please)

### ISSUE THREAD

**Issue by msilen** [mdn/content#4062]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/flex-basis

#### What information was incorrect, unhelpful, or incomplete?
In the first **"CSS Demo: flex-basis"** it is unclear to which elements flex-basis is applied. Only the property was displayed, not the whole rule. I assumed first that the rule is applied to all items (item-one, item-two, item-three), and was confused why `flex-basis: 200px` made only first item grow 200px wide, and other element to shrink.

#### Specific section or headline?
CSS Demo: flex-basis

#### What did you expect to see?
instead of ` flex-basis: 200px;` 
`.item-one { flex-basis: 200px }`

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/flex-basis`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/flex-basis
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/flex-basis/index.html
* Last commit: https://github.com/mdn/content/commit/f4fb4c2d90a134366c280eec6cb599825981ad5d
* Document last modified: 2021-03-15T17:55:56.000Z

</details>

**Comment by rachelandrew** [comment]
The rule is applied to all items. I think the issue here is we can only see `flex-basis` and not the other properties which demonstrate that the items have `flex-shrink: 1`. The suggested fix of showing the selector wouldn't help in this case.

I think it might be worth updating the interactive example to show the grow and shrink properties even though they won't change, and also adding an explanation of what is going on.

**Comment by rachelandrew** [comment]
Actually I was slightly wrong on this, I'd forgotten how these examples work. The rule is just applied to the first item, however all of the items are changing because of the flex-grow and flex-shrink properties, so it's a confusing demo. I'll see if I can make it a bit less so, but hopefully the explanation will also help.

I'm just making a PR which explains the demo. I think that entire page could do with some better examples, along with the other `flex-` properties.
