### ISSUE TITLE
Issue with "Box-shadow generator": please document it

### ISSUE THREAD

**Issue by David263** [mdn/content#4206]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Background_and_Borders/Box-shadow_generator

#### What information was incorrect, unhelpful, or incomplete?
As a newcomer to the box-shadow property, I think a paragraph of instructions on using this tool would be useful. I was not able to generate a simple gray shadow by experimenting with this tool, nor to turn off shadowing (which I believe is done with a value of 'none').

#### Specific section or headline?
No.

#### What did you expect to see?
Instructions.

#### Did you test this? If so, how?
Played around with this a bit, but nothing made sense to me. Looks like a useful tool, so it should be worth someone knowledgeable writing some instructions for using it. Not clear how many separate shadows this tool can generate.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/css_background_and_borders/box-shadow_generator`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Background_and_Borders/Box-shadow_generator
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_background_and_borders/box-shadow_generator/index.html
* Last commit: https://github.com/mdn/content/commit/451b978b8862839b5b10da37dfdd26e57ab7511d
* Document last modified: 2021-02-08T19:03:37.000Z

</details>

**Comment by wbamberg** [comment]
Yes, I agree with you. I think it's a nice tool but it's not obvious how to use it.

There are six main areas of the tool:

1. a row of buttons along the top. Left to right, these enable you to:
    * +: add a new box shadow
    * ↑: change the order of your shadows, by moving the currently selected shadow one place earlier
    * ↓: change the order of your shadows, by moving the currently selected shadow one place later
    * switch between the element, a :before pseudo-element, and an :after pseudo-element. All of these can have their own set of box shadows, so kind of represent separate contexts for the tool.

2. a column on the left hand side, that initially just has a box labelled "element" at the top. This lists all the shadows you're currently applying to the element, in the order in which you're applying them. It also lets you switch to a different shadow if you want to edit its properties. If you click the ":before" or ":after" buttons, then this column will list shadows for the :before or :after pseudo-elements, instead of the shadows for the element.

3. a box to the right of (2), which shows you what the element and its shadows (and any pseudo-elements and their shadows) will look like

4. a box at the bottom-left, which lets you set colors for the element or shadows.

5. a box to the left of this color box, which lets you set other CSS values

6. a box at the bottom-right, which shows you the CSS being generated. 

When you open the tool first, there's just an element: no shadows. That's the element you're going to be applying shadows to. When this element is selected (as it is, when you first load the page) the controls in boxes 4 and 5 control styles for that element - color, size, and position.

To add a box shadow you need to click the "+" button at the top-left. This adds a shadow, and lists it in column (2). Now you can set the properties of the new shadow using boxes 4 and 5. Note that box 5 now contains different things - rather than setting size and position, we're able to set box-shadow attributes like blur and radius.

To add another shadow, click "+" again. Now any settings you create in boxes 4 and 5 will apply to this new shadow. You can change the order in which these two shadows are applied using the  ↑ and ↓ buttons in (1). You can select the first shadow again by clicking it in column (2). If you want to update the element's own styles, you can select it by clicking the button labelled "element" in (1).

******

Do you think something like that would be helpful?

**Comment by David263** [comment]
@wbamberg Yes, this is a great start!

But it is still confusing for me, because you started the instructions by describing each control in the form, which is fine as a reminder once I know what the tool does and how to use it.

What I think would be most useful is starting with a step-by-step tutorial for creating a simple shadow (your instructions above, modified a bit, will then be great for modifying that starting point).

Something like this:

1. Create an example element by ...

2. Create a shadow in the standard location (lower right, which assumes a light source to the upper left) by ...

3. Change its color and other properties by ...

4. Finish by selecting the code shown at the lower right and copying and pasting into your CSS file.

Also, it would be good to explain exactly what :before and :after do, since it isn't obvious and would be convenient if explained here. Also, it would be good to give an example of why one would need many shadows for one element, as that isn't obvious to me either (are shadows used for purposes other than showing shadows from a light source? Does each shadow have its own properties?). Also, what are these pseudo-elements that you mention (I'm not sure what they are)?

**Comment by wbamberg** [comment]
> @wbamberg Yes, this is a great start!
> 
> But it is still confusing for me, because you started the instructions by describing each control in the form, which is fine as a reminder once I know what the tool does and how to use it.
> 
> What I think would be most useful is starting with a step-by-step tutorial for creating a simple shadow (your instructions above, modified a bit, will then be great for modifying that starting point).

The thing about that is that you have to refer to bits of the UI in order to write those instructions, and it gets messy when you try to introduce those referents inline, in the tutorial. It's clearer (IMO) to describe the bits of the UI first, then refer to them in the instructions. (that's why camera manuals always have the picture of all the bits first, then the instructions refer to it) 

> Also, it would be good to explain exactly what :before and :after do, since it isn't obvious and would be convenient if explained here. Also, it would be good to give an example of why one would need many shadows for one element, as that isn't obvious to me either (are shadows used for purposes other than showing shadows from a light source? Does each shadow have its own properties?). Also, what are these pseudo-elements that you mention (I'm not sure what they are)?

I don't think this should describe what `:before`, `:after`, or pseudo-elements in general are, or any other stuff that's just CSS documentation. I would expect the instructions to link to our docs for that (e.g. [:before](https://developer.mozilla.org/en-US/docs/Web/CSS/::before) ).

**Comment by wbamberg** [comment]
Fixed by https://github.com/mdn/content/pull/4634 . Thanks for filing, David! In the end I scrapped all the stuff describing the bits of the UI.

**Comment by teoli2003** [comment]
@wbamberg Great explanation! I think we should close this issue, shouldn't we?

**Comment by wbamberg** [comment]
Sure, let's do that :)
