### ISSUE TITLE
Handling 33 CSS articles with broken live samples due to https://mdn.mozillademos.org URLs

### ISSUE THREAD

**Issue by sideshowbarker** [mdn/content#4209]
mdn.mozillademos.org URL responses are actually 302 redirects to media.prod.mdn.mozit.cloud URLs, and those 302s have no Access-Control-Allow-Origin header, so browsers refuse to follow the redirects.

That problem breaks all live samples we have that reference mdn.mozillademos.org URLs in CSS stylesheet source.

For some user reports about those problems, #340, #2115, #3518, and #4203.

So far the problem has been getting dealt with case-by-case, by moving the resources to the interactive-examples repo. But looking at the existing CSS article sources, it seems due to that problem, we still have 33 articles with broken live samples:

```
$ rg -l "\(.*https://mdn.mozillademos.org" files/en-us/web/css/
```

- [x] [files/en-us/web/css/mask-origin/index.html](https://developer.mozilla.org/en-us/docs/web/css/mask-origin)
- [x] [files/en-us/web/css/-moz-image-rect/index.html](https://developer.mozilla.org/en-us/docs/web/css/-moz-image-rect)
- [x] [files/en-us/web/css/mask-repeat/index.html](https://developer.mozilla.org/en-us/docs/web/css/mask-repeat)
- [x] [files/en-us/web/css/image()/index.html](https://developer.mozilla.org/en-us/docs/web/css/image())
- [x] [files/en-us/web/css/@font-face/index.html](https://developer.mozilla.org/en-us/docs/web/css/@font-face)
- [x] [files/en-us/web/css/font-style/index.html](https://developer.mozilla.org/en-us/docs/web/css/font-style)
- [x] [files/en-us/web/css/mask-size/index.html](https://developer.mozilla.org/en-us/docs/web/css/mask-size)
- [x] [files/en-us/web/css/border-image/index.html](https://developer.mozilla.org/en-us/docs/web/css/border-image)
- [x] [files/en-us/web/css/mask-composite/index.html](https://developer.mozilla.org/en-us/docs/web/css/mask-composite)
- [x] [files/en-us/web/css/text-combine-upright/index.html](https://developer.mozilla.org/en-us/docs/web/css/text-combine-upright)
- [x] [files/en-us/web/css/background-position/index.html](https://developer.mozilla.org/en-us/docs/web/css/background-position)
- [x] [files/en-us/web/css/background-attachment/index.html](https://developer.mozilla.org/en-us/docs/web/css/background-attachment)
- [x] [files/en-us/web/css/mask-border/index.html](https://developer.mozilla.org/en-us/docs/web/css/mask-border)
- [x] [files/en-us/web/css/blend-mode/index.html](https://developer.mozilla.org/en-us/docs/web/css/blend-mode)
- [x] [files/en-us/web/css/border-image-repeat/index.html](https://developer.mozilla.org/en-us/docs/web/css/border-image-repeat)
- [x] [files/en-us/web/css/font-weight/index.html](https://developer.mozilla.org/en-us/docs/web/css/font-weight)
- [x] [files/en-us/web/css/border-image-width/index.html](https://developer.mozilla.org/en-us/docs/web/css/border-image-width)
- [x] [files/en-us/web/css/css_colors/color_picker_tool/index.html](https://developer.mozilla.org/en-us/docs/web/css/css_colors/color_picker_tool)
- [x] [files/en-us/web/css/background-image/index.html](https://developer.mozilla.org/en-us/docs/web/css/background-image)
- [x] [files/en-us/web/css/content/index.html](https://developer.mozilla.org/en-us/docs/web/css/content)
- [x] [files/en-us/web/css/css_backgrounds_and_borders/using_multiple_backgrounds/index.html](https://developer.mozilla.org/en-us/docs/web/css/css_backgrounds_and_borders/using_multiple_backgrounds)
- [x] [files/en-us/web/css/font-stretch/index.html](https://developer.mozilla.org/en-us/docs/web/css/font-stretch)
- [x] [files/en-us/web/css/list-style-position/index.html](https://developer.mozilla.org/en-us/docs/web/css/list-style-position)
- [x] [files/en-us/web/css/css_images/using_css_gradients/index.html](https://developer.mozilla.org/en-us/docs/web/css/css_images/using_css_gradients)
- [x] [files/en-us/web/css/css_background_and_borders/border-radius_generator/index.html](https://developer.mozilla.org/en-us/docs/web/css/css_background_and_borders/border-radius_generator)
- [x] [files/en-us/web/css/css_background_and_borders/border-image_generator/index.html](https://developer.mozilla.org/en-us/docs/web/css/css_background_and_borders/border-image_generator)
- [x] [files/en-us/web/css/css_background_and_borders/box-shadow_generator/index.html](https://developer.mozilla.org/en-us/docs/web/css/css_background_and_borders/box-shadow_generator)
- [x] [files/en-us/web/css/background-blend-mode/index.html](https://developer.mozilla.org/en-us/docs/web/css/background-blend-mode)
- [x] [files/en-us/web/css/cross-fade()/index.html](https://developer.mozilla.org/en-us/docs/web/css/cross-fade())
- [x] [files/en-us/web/css/list-style-image/index.html](https://developer.mozilla.org/en-us/docs/web/css/list-style-image)
- [x] [files/en-us/web/css/background-repeat/index.html](https://developer.mozilla.org/en-us/docs/web/css/background-repeat)
- [x] [files/en-us/web/css/background/index.html](https://developer.mozilla.org/en-us/docs/web/css/background)

So, this purpose of this issue is to record which articles still have the problem — and to suggest we might want to consider whether there’s some way we could do a batch fix for them (scripting it or something), rather than case-by-case.

**Comment by rachelandrew** [comment]
I could just rattle through and move them to the css-examples repo, it doesn't actually take me too long as I have a template for converting them. Thanks for identifying them all.

**Comment by rachelandrew** [comment]
Masking examples PR: https://github.com/mdn/content/pull/4252

**Comment by wbamberg** [comment]
I'm not necessarily a fan of moving examples to css-examples just to get around this issue. For me the value of live samples is that there's only one copy of the code, so there's no possibility for the code and output to get out of sync. So anywhere that the code is actually shown in the page ought to be a live sample, all other things being equal.

If live samples are broken because of this issue it seems to me that we should fix the issue. @peterbe , are you aware of this problem?

Otherwise we might as well just deprecate live samples entirely.

**Comment by rachelandrew** [comment]
I'm of the opposite opinion to be honest, having these things elsewhere means we can re-use them. I often write a guide to some CSS feature then re-use a single example in the docs rather than repeat the stuff everywhere. I'd much prefer all of the CSS examples be in css-examples.

**Comment by rachelandrew** [comment]
One of the things I intend to do is tidy up that repo, and add a list of everything that's in there to the Readme.

**Comment by peterbe** [comment]
> I'm not necessarily a fan of moving examples to css-examples just to get around this issue. For me the value of live samples is that there's only one copy of the code, so there's no possibility for the code and output to get out of sync. So anywhere that the code is actually shown in the page ought to be a live sample, all other things being equal.
> 
> If live samples are broken because of this issue it seems to me that we should fix the issue. @peterbe , are you aware of this problem?
> 
> Otherwise we might as well just deprecate live samples entirely.

I'm not entirely sure what's going on here. 
But @escattone and I have been tinkering with this too. 
E.g. 

- https://github.com/mdn/content/pull/5636/files
- https://github.com/mdn/content/pull/5635/files
- https://github.com/mdn/content/pull/5310/files
- https://github.com/mdn/content/pull/5266/files
- https://github.com/mdn/content/pull/5257/files
- https://github.com/mdn/content/pull/4973/files
- https://github.com/mdn/content/pull/4974/files

I even have a Python script that can carefully suggest edits and all the necessary image downloads. 
I remember seeing there are about 100 documents that mentioned mdn.mozillademos.org where it could probably be replaced with local images. 

It was only last week that we added the ability to put an image adjacent to the `index.html` without it being mentioned in a `<img src=...>`. 

It's the weekend and I just stumbled in here because I had left my Gmail open. So perhaps I'm answering the wrong question.

**Comment by peterbe** [comment]
Once https://github.com/mdn/content/pull/5763 lands I think that's going to take care of a bunch of the URLs mentioned in the top of this issue.

**Comment by peterbe** [comment]
What I don't understand yet is "articles with **broken** live samples" (emphasis mine). 
Switching from `https://mdn.mozillademos.org/files/12345/foo.png` to `./foo.png` is ultimately just optimization. 
It moves us away from a portion of Kuma we don't want to have to maintain. And it makes the content bit nicer to work with because you have the file available with the content which makes it easier to update in case you wanted to change the file attachment. 

But what's "broken"?  Are we getting errors?

I'm now going to hop over to https://github.com/mdn/content/issues/5606 which I could see is a problem since font files are potentially different to image files.

**Comment by sideshowbarker** [comment]
> What I don't understand yet is "articles with **broken** live samples" (emphasis mine).
> Switching from `https://mdn.mozillademos.org/files/12345/foo.png` to `./foo.png` is ultimately just optimization.
> But what's "broken"? Are we getting errors?

There’s one case that I’m not sure is relevant to this particular issue but I’ll got ahead and mention here anyway — and that’s what to do about live samples with code that references resources with https://mdn.mozillademos.org/files/12345/foo.png` URLs.

The problem with that case is, it can’t be fixed by moving the resource into the mdn/content repo — and the reason that won’t fix is that the live samples are delivered in an iframe from a different location.

For that case, it’s unclear to me how we can fix it.

But again like I said, I’m not sure whether that problem case is relevant to this particular issue.

**Comment by peterbe** [comment]
> There’s one set of cases I’m not sure are relevant to this particular issue but I’ll go ahead and mention here anyway — and that’s what to do about live samples with code that references resources with `https://mdn.mozillademos.org/` URLs.
> 
> The problem with those cases is, they can’t be fixed by moving the resources into the mdn/content repo — and the reason that won’t fix them is that the live samples are delivered in an iframe from a different location.
> 
> So for those cases, we can’t use relative URLs to reference those resources — we need somewhere else to put them, and need to use absolute URLs.
> 
> And so for those cases, it’s unclear to me how we can fix them.

I think I have failed to demonstrate something. 
It *used* to be that you couldn't put relative URLs (e.g. `foo.png` instead of `https://mdn.mozillademos.org/files/123/foo.png` ) into the live samples. E.g. `<pre class="brush: css">`.
But it got fixed. About 2-3 weeks ago. 

What happens now is that suppose you have this at the source:
```
/somefolder
 > /index.html
 > /screenshot.png
```
and in the `index.html` you have a live sample like this (in that `index.html` file):
```html
<pre class="brush: css">
element { background-image: url(screenshot.png) }
</pre>
```

When this gets built what happens is that you end up with this in the built files:
```
/somefolder
 > /index.html
 > /screenshot.png
 > /_sample.Some-ID.html
```
And this `_sample.Some-ID.html` file is embedded as an `iframe` but it's now at the same level as the regular `index.html`. 

A great example of this is: https://pr5763.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/list-style-position
Which is part of https://github.com/mdn/content/pull/5763
The live sample picks up, from the `<pre class="brush:css">` this: `list-style-image: url("starsolid.gif");`
[And if you view the URL of the iframe](https://pr5763.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/list-style-position/_sample_.Setting_list_item_position.html) you'll see that the image reference just works. 

The current problem is that there's still bunch of these to clean up. https://github.com/mdn/content/pull/5763 is just one of many to come. After that one, there [roughly 70 more docs like this](https://gist.github.com/peterbe/6d23bb256db8e6f6ec1543ee8cfcb44f).

**Comment by sideshowbarker** [comment]
> It _used_ to be that you couldn't put relative URLs (e.g. `foo.png` instead of `https://mdn.mozillademos.org/files/123/foo.png` ) into the live samples. E.g. `<pre class="brush: css">`.
> But it got fixed. About 2-3 weeks ago.
> 
> What happens now is that suppose you have this at the source:
> 
> ```
> /somefolder
>  > /index.html
>  > /screenshot.png
> ```
> 
> and in the `index.html` you have a live sample like this (in that `index.html` file):
> 
> ```
> <pre class="brush: css">
> element { background-image: url(screenshot.png) }
> </pre>
> ```

🎉 Hit diggity dog — I just tried it in https://github.com/mdn/content/pull/5878 and it worked like charm

Thanks much for putting that mechanism into place — that’s gonna make things way easier

**Comment by wbamberg** [comment]
It looks like none of these use https://mdn.mozillademos.org URLs any more, due to a mixture of Peter's PRs to move the content locally (thanks Peter!) and various examples being relocated as GitHub pages. The only exception seems to be https://developer.mozilla.org/en-US/docs/web/css/content#examples - I'll file a PR for this and maybe we can close this old issue.

**Comment by wbamberg** [comment]
Oh, I'm wrong, the example for `content` works too, it's just not supported in Firefox.
