### ISSUE TITLE
Issue with "typeof": (short summary here please)

### ISSUE THREAD

**Issue by s-kust** [mdn/content#4244]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof

#### Specific section or headline?

Real-world usage

#### What did you expect to see?

More detailed explanation, usage samples needed

It is not clear how the `type(obj, fullClass)` function works, what does it do

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/typeof`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/typeof/index.html
* Last commit: https://github.com/mdn/content/commit/3b80812a1d4f68e57f35fca763f50bf3e5dfe997
* Document last modified: 2021-02-19T19:57:02.000Z

</details>

**Comment by jadjoubran** [comment]
@sideshowbarker happy to take this one, I think we should do one of the following options:
A. Rename it to showFullClass + default it to false (default parameter) + update the code so that it only works for objects, it doesn't make sense to show `[object Number]` for `type(42, true)`
B. Remove `fullClass` altogether and keep the `if (obj === null)` check
