### ISSUE TITLE
Web IDL snippets on some pages

### ISSUE THREAD

**Issue by foolip** [mdn/content#4292]
https://heycam.github.io/webidl/ is for browser implementers, but snippets of that syntax is included on some MDN pages.

Here are the ones I could find:
https://developer.mozilla.org/en-US/docs/Web/API/BluetoothAdvertisingData#interface
https://developer.mozilla.org/en-US/docs/Web/API/BluetoothDevice#interface
https://developer.mozilla.org/en-US/docs/Web/API/BluetoothRemoteGATTCharacteristic#interface
https://developer.mozilla.org/en-US/docs/Web/API/BluetoothRemoteGATTDescriptor#interface
https://developer.mozilla.org/en-US/docs/Web/API/BluetoothRemoteGATTServer#interface
https://developer.mozilla.org/en-US/docs/Web/API/BluetoothRemoteGATTService#interface
https://developer.mozilla.org/en-US/docs/Web/API/CSSGroupingRule#syntax
https://developer.mozilla.org/en-US/docs/Web/API/Microdata_DOM_API#htmlpropertiescollection

Searching for "webidl" and "web idl" case-insensitively might reveal more.

**Comment by sideshowbarker** [comment]
I think beyond the ones in the issue description, the only additional ones are likely these two:

* https://developer.mozilla.org/en-US/docs/Web/API/Bluetooth
* https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API

---

Details:

> Searching for "webidl" and "web idl" case-insensitively might reveal more.

That produces a lot of false positives — catching a lot more articles than just those that have actual WebIDL blocks/syntax.

Trying instead with `rg -l "^\s*readonly attribute"` gives:

```
files/en-us/web/api/bluetoothremotegattdescriptor/index.html
files/en-us/web/api/bluetoothremotegattcharacteristic/index.html
files/en-us/web/api/bluetoothdevice/index.html
files/en-us/web/api/bluetoothremotegattservice/index.html
files/en-us/web/api/bluetooth/index.html
files/en-us/web/api/microdata_dom_api/index.html
files/en-us/web/api/bluetoothremotegattserver/index.html
files/en-us/web/api/cssgroupingrule/index.html
files/en-us/web/api/bluetoothadvertisingdata/index.html
files/en-us/mdn/contribute/howto/write_an_api_reference/information_contained_in_a_webidl_file/index.html
files/en-us/mozilla/developer_guide/interface_development_guide/idl_interface_rules/index.html
files/en-us/mozilla/developer_guide/interface_development_guide/commenting_idl_for_better_documentation/index.html
```
We can ignore the last three, since those articles are actually about writing WebIDL — but that finds the same set listed in the issue description — plus one more, https://developer.mozilla.org/en-US/docs/Web/API/Bluetooth

Trying further with something a bit more complicated, `rg -l "^\s*(<pre [^>]+>\s*)?interface\s+[^\{]+\{\s*$"`, gives:
```
files/en-us/web/api/bluetoothdevice/index.html
files/en-us/web/api/mssitemodeevent/index.html
files/en-us/web/api/bluetoothremotegattservice/index.html
files/en-us/web/api/bluetooth/index.html
files/en-us/web/api/microdata_dom_api/index.html
files/en-us/web/api/bluetoothremotegattserver/index.html
files/en-us/web/api/msmanipulationevent/index.html
files/en-us/web/api/msmanipulationevent/initmsmanipulationevent/index.html
files/en-us/web/api/bluetoothadvertisingdata/index.html
files/en-us/web/api/bluetoothremotegattdescriptor/index.html
files/en-us/web/api/webvtt_api/index.html
files/en-us/mdn/contribute/howto/write_an_api_reference/information_contained_in_a_webidl_file/index.html
files/en-us/mozilla/developer_guide/interface_development_guide/idl_interface_rules/index.html
files/en-us/mozilla/developer_guide/interface_development_guide/commenting_idl_for_better_documentation/index.html
```
So that catches a few more. But those oddball `msmanipulationevent` articles aren’t worth making an changes to — they should really just be archived. And the `microdata_dom_api` article should be archived too.

But https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API seems like a good find.

**Comment by foolip** [comment]
Thanks @sideshowbarker!

With that list of pages, this seems to me like suitable "good first issue", if this repo has such a label.

**Comment by Blakelist7** [comment]
@sideshowbarker, Could you please elaborate on the problem?
