### ISSUE TITLE
[Other] WebDriver firefoxOptions activities/intents

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#4315]
## Acceptance criteria

1. - [ ] The listed features are documented sufficiently on MDN
2. - [ ] BCD is updated
3. - [ ] Interactive example and data repos are updated if appropriate
4. - [ ] The content has been reviewed as needed

## Features to document

1.  WebDriver firefoxOptions activities/intents

## Related Gecko bugs

1. - [ ] [Add a set of default activities and intents for GeckoView based applications](https://bugzilla.mozilla.org/show_bug.cgi?id=1700290). Some new activities/intents to add to the [firefoxOptions](https://developer.mozilla.org/en-US/docs/Web/WebDriver/Capabilities/firefoxOptions) page. Might be good to ask @whimboo (Henrik Skupin) if he could help out with this.

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by whimboo** [comment]
@chrisdavidmills I've set the `dev-doc-needed` flag when I thought that we would add this information on MDN. But then we actually decided against that and now have this default set compiled into geckodriver itself.

Do you think it would still helpful for users to see these defaults on MDN?

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills I've set the `dev-doc-needed` flag when I thought that we would add this information on MDN. But then we actually decided against that and now have this default set compiled into geckodriver itself.
> 
> Do you think it would still helpful for users to see these defaults on MDN?

I'm happy with whatever you think is useful for WebDriver users. My main thought is that it might be useful for people to know what the defaults are, and then be given the alternative options, so they can change them if they want something else. But I don't know a great deal about WebDriver.

**Comment by hamishwillee** [comment]
FWIW I think it is important to have one canonical source for information. So if everything is documented somewhere in webdriver itself then all you would have on MDN would be an overview of what you can do/what it is for, and then instructions on how to get any other information you need. What isn't clear is whether you're just documenting part of what is needed elsewhere or everything.

If it is everything, can we get what is on MDN removed?

**Comment by hamishwillee** [comment]
@whimboo @chrisdavidmills So is there a resolution on what we do with this? (just looking at unassigned items to see which I should take). 

As per https://github.com/mdn/content/issues/4315#issuecomment-826594183 it isn't clear to me what the docs story is for web driver.

**Comment by chrisdavidmills** [comment]
@whimboo can you clarify for us — are the WebDriver docs on MDN helpful, or should we just provide a single overview page and link to the in tree docs? I'm happy either way, but if it would be better to just link to the in tree docs, we should probably close this issue, and open a new issue for cleaning up what is on MDN. Thanks!

**Comment by whimboo** [comment]
Hey and sorry for the delay with my response. So this issue has been actually extended to all topics regarding WebDriver, compared to the initial creation for just the Android activities and intents.

Let me start with the Android topic. Originally we wanted to show a list of default `androidActivity`, and `androidIntentArguments` on MDN so that users can correctly start Firefox (including Nightly, debug builds, Klar/Focus,...) on Android. But as we finally agreed on all the defaults are now part of geckodriver itself. It means that consumers of geckodriver don't have to specify any of these capabilities by default. As such [what we already have on MDN regarding Android](https://developer.mozilla.org/en-US/docs/Web/WebDriver/Capabilities/firefoxOptions#android) should be totally sufficient. 

Regarding the overall approach to document WebDriver commands we should definitely add more content to MDN. While the [WebDriver specification](https://w3c.github.io/webdriver/) itself is targeted to those who actually implement the browser specific drivers (geckodriver, chromedriver, safaridriver, edgedriver,...), the documentation on MDN should give a resource for clients using these drivers. So topics like which commands are available, what is their HTTP end-point, which HTTP method and payload do they need, and what's the response. But all this should be moved to a new issue for further discussion.

As such should we close this issue, and create a new one for the general WebDriver documentation on MDN?

**Comment by chrisdavidmills** [comment]
> As such should we close this issue, and create a new one for the general WebDriver documentation on MDN?

Makes perfect sense, thanks for the clarification, and yes, I agree entirely. I'll close this and create a new opportunity assessment issue for the general WebDriver work
