### ISSUE TITLE
Issue with "ARIA: alert role": Unknown in spec table

### ISSUE THREAD

**Issue by Ryuno-Ki** [mdn/content#4320]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Alert_Role

#### What information was incorrect, unhelpful, or incomplete?

The link to WAI ARIA Practices for Alert role is broken.

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Alert_Role#specifications

#### What did you expect to see?

No `about:unknown#alert`. But a link to https://www.w3.org/TR/wai-aria-practices-1.1/#alert

#### Did you test this? If so, how?

https://github.com/mdn/content/blob/a6967c4403e2f5a456d68d2ada23d6ce3aa5ec20/files/en-us/web/accessibility/aria/roles/alert_role/index.html#L49-L64

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/accessibility/aria/roles/alert_role`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Alert_Role
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/accessibility/aria/roles/alert_role/index.html
* Last commit: https://github.com/mdn/content/commit/1e8c048d86584064ca418a214063cb965fab3e71
* Document last modified: 2021-03-23T09:11:33.000Z

</details>

**Comment by Ryuno-Ki** [comment]
Ping @peterbe In case the macro cannot resolve it, is there a better way than to display an `about:` link?
(If so, please break out into separate issue).

**Comment by peterbe** [comment]
I know way too little about Specification tables. @Elchi3 knows a LOT. Plus I happen to know that he's working on a complete rewrite of how they work. Both in terms of the rendering/building process in Yari but also about the content itself. Florian? What say you have `about:...` hyperlinks? Can you make sense of this issue?

**Comment by Elchi3** [comment]
Yes, we are indeed redoing all of the Specification section because as this issue nicely demonstrate the current way of doing things is ... complicated. :)

`{{SpecName("ARIA Authoring Practices","#alert","Alert")}}` is trying to look up a spec called "ARIA Authoring Practices" in https://github.com/mdn/yari/blob/main/kumascript/macros/SpecData.json but in there you only have "ARIA Authoring Practices **1.1**" and "ARIA Authoring Practices **1.2**".

So, I guess the call should be `{{SpecName("ARIA Authoring Practices 1.2","#alert","Alert")}}`. 

In the future I hope this will be a matter of calling `{{SpecficationTable}}` if we have a front-matter for the bcd query. However, the accessibility docs aren't in the first iteration for that. Will try to get there, though :)

**Comment by Ryuno-Ki** [comment]
Would it make sense to submit a PR that adds the version numbers to the call of the macro to remedy the issue at hand?
Or would it be more beneficial to leave it as-is to have a page to test the new macro against?

**Comment by Elchi3** [comment]
> Would it make sense to submit a PR that adds the version numbers to the call of the macro to remedy the issue at hand?

Yes, this makes sense. I don't know how quickly we will roll out the new spec approach. I might test it first with JS docs (given we want to convert these to markdown first) and then expand further. So, yes, PR welcome to add the version numbers to the current macro call.

**Comment by Ryuno-Ki** [comment]
Alright. Filled #4425 with a fix.
