### ISSUE TITLE
Issue with "If-None-Match": note that Apache reverse proxies will append "-gzip" suffix to well-formed ETag headers when gzip-encoding content, but they do not remove them from If-None-Match headers

### ISSUE THREAD

**Issue by robrwo** [mdn/content#4343]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match

#### What information was incorrect, unhelpful, or incomplete?

Apache reverse proxies will append "-gzip" suffix to well-formed `ETag` headers when gzip-encoding content, but they do not remove them from `If-None-Match` headers.  See https://bz.apache.org/bugzilla/show_bug.cgi?id=39727

There are good reasons for this, since gzip-encoding the content will affect how range requests can be used.  But server software that compares If-None-Match headers in requests with ETags may need to account for this.

#### Specific section or headline?

Unsure.

#### What did you expect to see?

It should be mentioned somewhere.

#### Did you test this? If so, how?

I came across this while working on server code.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/headers/if-none-match`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/if-none-match/index.html
* Last commit: https://github.com/mdn/content/commit/f6f11d2a249520f01bad93d7c4a5e5cdf6ed914a
* Document last modified: 2021-02-19T19:33:30.000Z

</details>

**Comment by mnot** [comment]
Probably most appropriate at https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation if it's mentioned.

**Comment by sideshowbarker** [comment]
> Probably most appropriate at [developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation) if it's mentioned.

@mnot — Can you elaborate on why that’d be the most-appropriate place to mention this? Since that article as currently written doesn’t mention the `If-None-Match` or `ETag` headers at all — nor explicitly mention anything about gzip — I’m not sure how we could fit this into that article without it looking like non sequitur to people reading it…

**Comment by mnot** [comment]
It's a conneg-related issue, because Apache isn't handling ETags correctly for negotiated content with `mod_deflate` -- i.e., it's an interoperability problem with conditional requests that's triggered by use of conneg. 

You could also mention it at https://developer.mozilla.org/en-US/docs/Web/HTTP/Conditional_requests but it'd be less useful there

**Comment by robrwo** [comment]
I don't see it as being relevant for Content_negotiation. ETags are used for conditional requests, not content negotiation. Nothing in the content negotiation page mentions conditional requests or ETags.
