### ISSUE TITLE
Content bug: Outdated image for Responsive Design Button

### ISSUE THREAD

**Issue by Jobtye** [mdn/content#4424]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Tools

## Specific page section or heading?

![Capture](https://user-images.githubusercontent.com/82216675/115914595-73258d80-a472-11eb-9878-5dfdc4607fce.PNG)

## What is the problem?

Responsive Design Mode button is out of date in the article. 

## What did you expect to see?

![Capture2](https://user-images.githubusercontent.com/82216675/115914731-a1a36880-a472-11eb-8c1b-4443d73a80dd.PNG)

**Comment by ddbeck** [comment]
Hi, I'm closing this issue because [Firefox DevTools User Docs](https://firefox-source-docs.mozilla.org/devtools-user/index.html#firefox-devtools-user-docs) have moved off of MDN (see https://github.com/mdn/content/pull/14140 for details on content moved). If this issue is still applicable to the relocated documentation, please see the Firefox Source Docs site for details on raising bugs and contributing. Thanks for your understanding!
