### ISSUE TITLE
Issue with "Storage Inspector": storage type Extension Storage is missing from the opening list

### ISSUE THREAD

**Issue by grahamperrin** [mdn/content#4434]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Storage_Inspector

#### What information was incorrect, unhelpful, or incomplete?

One of six storage types is not listed. 

#### Specific section or headline?

https://github.com/mdn/content/blob/main/files/en-us/tools/storage_inspector/index.html#L19

#### What did you expect to see?

> * _Extension Storage …_ 

– as the third of six bullet points (in alphabetical order). 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/storage_inspector`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Storage_Inspector
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/storage_inspector/index.html
* Last commit: https://github.com/mdn/content/commit/e0a36d636574e8b25492026c064e39762bc36716
* Document last modified: 2021-02-10T18:03:04.000Z

</details>

**Comment by ddbeck** [comment]
Hi, I'm closing this issue because [Firefox DevTools User Docs](https://firefox-source-docs.mozilla.org/devtools-user/index.html#firefox-devtools-user-docs) have moved off of MDN (see https://github.com/mdn/content/pull/14140 for details on content moved). If this issue is still applicable to the relocated documentation, please see the Firefox Source Docs site for details on raising bugs and contributing. Thanks for your understanding!
