### ISSUE TITLE
Issue with "MediaStreamTrack": (short summary here please)

### ISSUE THREAD

**Issue by frontendDevNat** [mdn/content#4511]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack

#### What information was incorrect, unhelpful, or incomplete?
Note: You can implement standard "mute" functionality by setting enabled to false, and unmute the media by setting it back to true again.

#### Specific section or headline?
MediaStreamTrack.muted

#### What did you expect to see?
Note: You can implement standard "unmute" functionality by setting muted to false, and mute the media by setting it back to true again.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/mediastreamtrack`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/mediastreamtrack/index.html
* Last commit: https://github.com/mdn/content/commit/dc9089417852530f233c345bd6821d6e06f11b1e
* Document last modified: 2020-12-18T10:05:08.000Z

</details>

**Comment by dontcallmedom** [comment]
I don't think the document is wrong - as the [spec explains](https://w3c.github.io/mediacapture-main/getusermedia.html#track-enabled), `enabled` is indeed what a developer would use to mute a track, `muted` reflects the read-only user-agent state of the track.

It may be useful to repeat the note that "The muted property refers to a condition in which there's no media because of a technical issue" that already appears under `enabled` under `muted` too.

**Comment by teoli2003** [comment]
Yes, the document is correct (as @dontcallmedom pointed out, `muted` is read-only and cannot be set).

The note is duplicated now, so I think we can close this.
