### ISSUE TITLE
Issue with "JavaScript": (short summary here please)

### ISSUE THREAD

**Issue by LadislavSzolik** [mdn/content#4567]
MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/JavaScript

#### What information was incorrect, unhelpful, or incomplete?
The following web site is not existing anymore: 
https://ejohn.org/apps/learn/

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Glossary/JavaScript#learning_javascript 

#### What did you expect to see?
the page from John 

#### Did you test this? If so, how?
I reopened it, also the domain only, still does not work.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/glossary/javascript`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/JavaScript
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/javascript/index.html
* Last commit: https://github.com/mdn/content/commit/5fb569eddc18081727c03bb97cdb4c67f084804c
* Document last modified: 2021-04-24T03:00:55.000Z

</details>

**Comment by Ryuno-Ki** [comment]
I tried to pull up an old version in the Wayback Machine at archive.org, but even going back to 2015, I can only see 503 or 504 errors.
I'm afraid, it will be hard to restore the link. Perhaps @jeresig has ported its content? (New domain at https://johnresig.com/ )

Otherwise, we should delete this line:

https://github.com/mdn/content/blob/95d888ea5c6202662c709880e47596f1d3466c52/files/en-us/glossary/javascript/index.html#L40

**Comment by LadislavSzolik** [comment]
I thought I raise it to keep the page up to date and yes, delete if the content does not exist. 👍

**Comment by Ryuno-Ki** [comment]
You did good.

I'd like to wait for John to react and otherwise go and delete the link by the end of the week.
Would be great if we could update the link instead of throwing it away!

**Comment by Ryuno-Ki** [comment]
@LadislavSzolik Filled #4684 with a removal of the link.

**Comment by hamishwillee** [comment]
I added a note to the PR. Link is probably https://johnresig.com/apps/learn/ . Just not sure how useful it really is.
