### ISSUE TITLE
Content suggestion: InputDeviceInfo, MediaDeviceKind, MediaTrackCapabilities, NavigatorUserMedia, NavigatorUserMediaError

### ISSUE THREAD

**Issue by Ryuno-Ki** [mdn/content#4570]
## What is the new suggestion?

It looks like, there are some missing documents:

- /en-US/docs/Web/API/InputDeviceInfo does not exist
- /en-US/docs/Web/API/MediaDeviceKind does not exist
- /en-US/docs/Web/API/MediaTrackCapabilities does not exist
- /en-US/docs/Web/API/NavigatorUserMedia does not exist
- /en-US/docs/Web/API/NavigatorUserMediaError does not exist

## Why is it important or useful?

It would help not confusing first-time contributors submitting fixes.

## Other supporting information

This came up in https://github.com/mdn/content/pull/4535#issuecomment-827898057

**Comment by hamishwillee** [comment]
FWIW I have no problem with creating lists of things we need, but you could point at many many many other cases. I'm not sure creating this one in particular helps. 

I think that the right solution for being less confusing to first time users is letting them know that the missing flaws are an opportunity, and not necessarily injected by their change. Comment on this here https://github.com/mdn/content/pull/4535#issuecomment-829793236

**Comment by Ryuno-Ki** [comment]
@peterbe Is it possible to update the text shown by the PR companion?
If so, where would I need to open an issue to track this? (Namely, to encourage people to help write documents for broken internal links).

My understanding from #1712 etc. was, that having issues with unwritten documents were the way to go to keep track on what's needed.
Yes, we have topic owners. Yes, we need more hands to get those documents written.
But exposing the open issues is one way to attract help.
If we have an outline of how we want our documents to be structured, even better. If I recall correctly, it is currently „copy an existing page and swap out the relevant parts”.

**Comment by hamishwillee** [comment]
@Ryuno-Ki FYI @peterbe is working on a method to highlight new URLs added to PR. I think it useful to have info on links you inject **separate** from pre-existing links. Perhaps in different sections. 

Peter, for context there is the suggestion that all the flaw links are "scary" for new users, in particular those links they did not create. I am opposed to the idea of deleting "desired links". They should be visible (red) if missing, and it would be great if we could provide a hint that we would like them fixed and point to https://developer.mozilla.org/en-US/docs/MDN/Structures for guidance on how.

**Comment by peterbe** [comment]
The broken links are scary. It's a problem. But not a huge problem. It can hopefully encourage contributors to help tighten up links. 
I too prefer the red links over no links at all. From a user point-of-view it's more interesting to know that a certain method/property *exists* rather than saying nothing. Because sometimes the method/property's name is helpful in its own. E.g. `myStream.close()`. I'd love to know that there's a `.close()` method that I can use!
We have a tool-tip on these that isn't horrible. 
<img width="692" alt="Screen Shot 2021-05-03 at 3 55 47 PM" src="https://user-images.githubusercontent.com/26739/116926126-08b9dd80-ac28-11eb-8118-3a5253537a89.png">


I mentioned elsewhere that I figured out a way to compute which *external link URLs*  was introduced in the PR. That's orthogonal to the broken links flaws. 

I think we should close this issue and if the writers feel compelled, "explode" this issue into one about each individual page that we don't have yet. 

But one interesting thing we *could* discuss, in Yari, is ways to make it easier for people to 1) say they really need/want that missing page, 2) new tools to make it easier to create new pages. 
For example, for the links that are broken because we don't have them, we could link to a page about contributing to MDN instead.

**Comment by Ryuno-Ki** [comment]
You could „vote” (:+1:) on issues about creating pages.
I'm fine with closing this issue. At least, it's „discoverable” via search now.

**Comment by hamishwillee** [comment]
Sounds like we're good to close this, so I will.

> But one interesting thing we could discuss, in Yari, is ways to make it easier for people to 1) say they really need/want that missing page, 2) new tools to make it easier to create new pages.
For example, for the links that are broken because we don't have them, we could link to a page about contributing to MDN instead.

Without any supporting data, my feeling is that you can better infer the most needed pages from the most popular APIs by view hits - and that even if people used this feature it wouldn't tell us any more than the occasional issue we get here "where is doc for API whatever".

I slightly like the idea of linking to contributing doc. If we did this probably a section of the existing contributing doc that knows you got here from a broken API link. Even better, a link takes you to a template you can copy that is appropriate for the type of broken link.

**Comment by hamishwillee** [comment]
PS @peterbe Is it only _macro_ generated broken links that get tagged in red, or all internal links?

**Comment by peterbe** [comment]
> PS @peterbe Is it only _macro_ generated broken links that get tagged in red, or all internal links?

Macro only.

**Comment by hamishwillee** [comment]
@peterbe 

>> PS @peterbe Is it only macro generated broken links that get tagged in red, or all internal links?

> Macro only. 

Can we get it for all internal broken links? My understanding is that we're discouraged from using macros going forward and having the red link is always a useful hint.

**Comment by peterbe** [comment]
> Can we get it for all internal broken links? My understanding is that we're discouraged from using macros going forward and having the red link is always a useful hint.

No because it's impossible to distinguish between if it's a typo or something that should work. 
A lot of KS macros do things like looping over all properties or methods and can only assume that a page will exist. 

Ideally, all flaws should be resolved. Writers should address every broken link. Either correct it or remove the link. 
But the "red links" can be useful in places like the sidebar where we know, in advance, what all Web API properties are before we've had a chance to write about them all. 

But we can iterate on all of this. Perhaps @jpmedley has some insights regarding JS and web APIs where there are "manual (broken) links" in the content itself.

**Comment by hamishwillee** [comment]
> Ideally, all flaws should be resolved. Writers should address every broken link. Either correct it or remove the link.
But the "red links" can be useful in places like the sidebar where we know, in advance, what all Web API properties are before we've had a chance to write about them all.

What you're saying makes me think I should always be using the macro for links to API items.

FWIW As a reader I prefer **all** broken links to be red/highlighted in some way. Why? Well because then I don't waste my time clicking them. And if I'm an editor, I might see that red link while reading and do a fix on a doc I would not otherwise have bothered with. 

In any case, thanks - good to know.

**Comment by peterbe** [comment]
Semi-side-note; if you use `jsxref()` for example, you'll get the link automatically corrected for the locale. 
If you instead typed `<a href="/en-US/docs/Foo/bar">` a potential translator might miss that and now they accidentally link to the English content. And `jsxref()` uses `web.smartLink()` which makes sure it tries the current locale first and able to automatically fall back on en-US at build-time. 
So yeah, in some ways, KS macros are better for hyper links. 

However, It does make me think, perhaps typing `<a href="/en-US/docs/Foo/bar">...</a>`  should be considered a flaw and that ``<a href="/docs/Foo/bar">...</a>` is the correct. That way, the content becomes locale agnostic.

**Comment by hamishwillee** [comment]
> However, It does make me think, perhaps typing <a href="/en-US/docs/Foo/bar">...</a> should be considered a flaw and that ``...` is the correct. That way, the content becomes locale agnostic.

Well, if you can tell that it's a flaw then you can tell it is a valid JS link. At that point you can make it red whether or not it is **marked up** as a KS macro. Ha!

But yes, what we need here is canonical direction about whether we should use xref macros or not. Then there should be flaw checking for whatever the non-supported option is. @chrisdavidmills Do you have any broader view on whether we should use xref macros or not? [FWIW I strongly think we should even though they are kumascript and non-standard markdown. Just too useful to lose]

**Comment by Ryuno-Ki** [comment]
I don't want to interrupt, but this conversation will be **really** hard to find later on.
Could we move that to a discussion or at least to a new issue?

**Comment by hamishwillee** [comment]
Good point. Cross posted to https://github.com/mdn/yari/issues/3799
