### ISSUE TITLE
Content suggestion: Flexbox gap

### ISSUE THREAD

**Issue by Ryuno-Ki** [mdn/content#4573]
## What is the new suggestion?

Our Flexbox pages seem not to refer to the `gap` property:
https://developer.mozilla.org/en-US/docs/Glossary/Flexbox (neither on the Flex container page).
`gap` seem to be associated with CSS Grid only.

## Why is it important or useful?

It's interesting, as it would avoid applying workarounds as described in
https://www.falldowngoboone.com/blog/the-curious-case-of-flexbox-gap-and-safari/ or
https://ishadeed.com/article/flexbox-gap/

## Other supporting information

According to https://twitter.com/jensimmons/status/1387121082176577544 Flexbox Gap is now available in Safari.
https://caniuse.com/flexbox-gap is already updated.

**Comment by rachelandrew** [comment]
It's mentioned on the `gap` pages https://developer.mozilla.org/en-US/docs/Web/CSS/gap#flex_layout which imo is the right place for it to be mentioned as it isn't a flexbox specific property.

A big PR (https://github.com/mdn/browser-compat-data/pull/10129#discussion_r621883867) has been made to update BCD with a load of new features, otherwise I'd have made a PR for gap in flexbox. 

I'll probably add a section to one of the guides about gaps now it's available cross browser, I tend to add stuff to guides that will work well in Firefox/Chrome/Safari rather than pepper them with "not in x browser" messages, as they get out of date super quick.

**Comment by Ryuno-Ki** [comment]
Thank you.
