### ISSUE TITLE
Issue with "ArrayBuffer": base64 reference material missing on linked page

### ISSUE THREAD

**Issue by mark-at-tusksoft** [mdn/content#4577]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer

#### What information was incorrect, unhelpful, or incomplete?
```
You can also get an array buffer from existing data, for example [from a Base64 string](https://developer.mozilla.org/en-US/docs/Glossary/Base64#appendix_to_solution_1_decode_a_base64_string_to_uint8array_or_arraybuffer)
```
The link hash route does not appear to exist on the target page.

#### What did you expect to see?
The section of the article actually demonstrating base64 conversion to an arraybuffer.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/arraybuffer`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/arraybuffer/index.html
* Last commit: https://github.com/mdn/content/commit/dc9089417852530f233c345bd6821d6e06f11b1e
* Document last modified: 2020-12-18T10:05:08.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this. I’ve opened https://github.com/mdn/content/pull/4588 with a change that just drops the fragment part from the link URL — because we don’t currently have any content in MDN that demonstrates base64 conversion to an ArrayBuffer, so we have nothing to link to for that.

If you think MDN *should* (again) have that content, please open a separate issue for that.
