### ISSUE TITLE
Issue with "background-clip": Non-working example on third-party website

### ISSUE THREAD

**Issue by SteeveDroz** [mdn/content#4709]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/background-clip

#### What information was incorrect, unhelpful, or incomplete?

A link points to a non-working example. 

#### Specific section or headline?

In "Browser compatibility", if you display the additionnal informations about the partial support for webkit-based browsers, there is a link to [https://webkit.org/blog/164/background-clip-text/](https://webkit.org/blog/164/background-clip-text/). The example on that page doesn't work because of an image that doesn't exist anymore.

#### What did you expect to see?

An example that MDN can fix if there is a problem, on CodePen or directly in the page, for instance.

#### Did you test this? If so, how?

1. I clicked the link.
2. I saw the example that didn't work.
3. I tried to display the image.
4. I met my old friend the 404 HTTP status code.

#### Additional information

This is also a problem on the same pages in different languages.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/background-clip`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/background-clip
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/background-clip/index.html
* Last commit: https://github.com/mdn/content/commit/f4fb4c2d90a134366c280eec6cb599825981ad5d
* Document last modified: 2021-03-15T17:55:56.000Z

</details>

**Comment by hardikshah197** [comment]
@rachelandrew Should I take up this issue? if no one is working on it...

**Comment by sideshowbarker** [comment]
@hardikshah197 I believe this report is about a missing image at https://webkit.org/blog/164/background-clip-text/, which isn’t within our power to fix.

@SteeveDroz I suggest reporting that problem to the maintainers of the WebKit blog. There’s nothing that can be fixed in MDN about this. The relevant text from MDN is this:

> According to the [WebKit blog](https://webkit.org/blog/164/background-clip-text/), text decorations or shadows are not included in the clipping. 

…so we’re not suggesting to readers that they go to the blog and expect to find working examples; instead at MDN, we’re just stating a fact: That blog posting states that text decorations or shadows are not included in the clipping.

So I’m going ahead and closing this since there’s nothing that can be done from the MDN side to resolve it.
