### ISSUE TITLE
Issue with "Book detail page": …

### ISSUE THREAD

**Issue by okuninoshi** [mdn/content#475]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Book_detail_page

#### What information was incorrect, unhelpful, or incomplete?

h1 #{title}: #{book.title}
each val in book_instances
#### Specific section or headline?

View

#### What did you expect to see?

h1 title: #{book.title} 
each val in book_instance (without s )

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/displaying_data/book_detail_page`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Book_detail_page
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/server-side/express_nodejs/displaying_data/book_detail_page/index.html
* Report started: 2020-12-19T19:13:51.421Z

</details>

**Comment by sideshowbarker** [comment]
Are you certain this change is correct? I haven’t read through the code well enough to actually understand it, but I see this:

```js
res.render('book_detail', { title: results.book.title, book: results.book, book_instances: results.book_instance } );
```
So that seems to be adding a `book_instances` key to a `book_detail` object, with the value set from `results.book_instance`.

And then that `/views/book_detail.pug` thing consumes that `book_detail` object and does something with that `book_instances` value which was set earlier. Right?

Or I could be mistaken; the above is just what I noticed from a quick look through the code snippets.

**Comment by hamishwillee** [comment]
@okuninoshi Thanks for posting, but @sideshowbarker is correct. I am therefore closing.
