### ISSUE TITLE
Issue with "line-height": no mention of rem

### ISSUE THREAD

**Issue by Johnrobmiller** [mdn/content#4819]
You guys never mention rem in this page, which is very misleading.  It made me think that you couldn't use rem for line-height.

MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/line-height

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/line-height`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/line-height
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/line-height/index.html
* Last commit: https://github.com/mdn/content/commit/f4fb4c2d90a134366c280eec6cb599825981ad5d
* Document last modified: 2021-03-15T17:55:56.000Z

</details>

**Comment by rachelandrew** [comment]
It says that it accepts a `<length>` which links to the page detailing all possible options for length including rem. There are a large number, we can't mention all of them on every page that accepts the length data type - which is why we link to the page that does list them all.

So I don't think a change is needed here.

**Comment by Johnrobmiller** [comment]
Ah, I was not being clear in my initial post.  In the CSS-Demo (not the whole page), there is no mention of REM, and this is why it is misleading.

**Comment by rachelandrew** [comment]
in the demo there are lots of possible length values missing, we couldn't have a demo of them all :) that's why we link to the data type. If you are looking at any of the property pages you should find a section that says Values. This should link to the page for the data type or types that are valid. If `<length>` is valid then any valid length can be used.

More info here: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units

**Comment by Rumyra** [comment]
I don't think any updates are needed here - @rachelandrew 's explanation makes sense. Closing issue 👍
