### ISSUE TITLE
Issue with "Creating our first Vue component": (short summary here please)

### ISSUE THREAD

**Issue by xja** [mdn/content#4823]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Vue_first_component

#### What information was incorrect, unhelpful, or incomplete?
the following same code appears in all language version
> `<input type="checkbox" id="todo-item" checked="false" />`

#### Specific section or headline?
[Creating a ToDoItem component](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Vue_first_component#creating_a_todoitem_component)

#### What did you expect to see?
CHECKED: 
`<input type="checkbox" id="todo-item" checked="checked" />`
or
`<input type="checkbox" id="todo-item" checked />`
UNCHECKED:
`<input type="checkbox" id="todo-item" />`

#### Did you test this? If so, how?
if i use `checked="false"`, the checkbox will be checked by default.
[forms - What's the proper value for a checked attribute of an HTML checkbox? - Stack Overflow](https://stackoverflow.com/questions/7851868/whats-the-proper-value-for-a-checked-attribute-of-an-html-checkbox)
[Boolean attributes - HTML Standard](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attribute)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/tools_and_testing/client-side_javascript_frameworks/vue_first_component`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Vue_first_component
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/vue_first_component/index.html
* Last commit: https://github.com/mdn/content/commit/11857b7d4b212319b2c9c998a85a71ca4e71f8ec
* Document last modified: 2021-04-09T13:58:05.000Z

</details>

**Comment by mcalexster** [comment]
To explain better, the 'checked' attribute in a checkbox is 'A Boolean attribute indicating whether or not this checkbox is checked by default (when the page loads).' <-- from [`<input type="checkbox">` - Additional attributes - checked](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/checkbox#attr-checked).  So a boolean is being used in the tutorial as an assignable attribute:
`<input type="checkbox" id="todo-item" checked="false" />`

However the result is counterintuitive as the displayed checkbox shows as checked.

This can be fixed by changing 'checked="false"' in the tutorial to: 'indeterminate', which is the other boolean attribute used by checkbox, and is arguably a better default (initial) value for a checkbox from a UX perspective.  Making that change will require changing one graphic (which currently shows an incorrect outcome) and one subsequent code listing.
