### ISSUE TITLE
Issue with "Interact with the clipboard": Document.execCommand() is deprecated

### ISSUE THREAD

**Issue by colideum** [mdn/content#4864]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard

#### What information was incorrect, unhelpful, or incomplete?
Document.execCommand() is deprecated, so You should provide new, proper solution

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/interact_with_the_clipboard`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/interact_with_the_clipboard/index.html
* Last commit: https://github.com/mdn/content/commit/1a67de1fdcaef5b725e1a591f512034dcb7c5a63
* Document last modified: 2021-05-07T12:19:01.000Z

</details>

**Comment by mireille-raad** [comment]
Would it be useful to:
- just remove the section on exec command
- only keep  the section on "Using the Clipboard API"?

I think it is more dangerous to keep depreciated stuff... not everyone will bother and go check.

---
As for the `navigator.clipboard.writeText`, it seems that now it is fully supported.

There is a warning text:

<img width="1029" alt="Screen Shot 2021-07-28 at 11 18 55 PM" src="https://user-images.githubusercontent.com/521705/127426372-2d7f0f18-4d55-4d27-97c9-f82366d7a608.png">

However on the link:
https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText

Here is the browser compatibility:

<img width="1060" alt="Screen Shot 2021-07-28 at 11 17 37 PM" src="https://user-images.githubusercontent.com/521705/127426207-e939373e-c4b0-4e1e-bd67-73e765f9646b.png">

Should the above note be in place? or is it no longer valid since there is browser support?

**Comment by rebloor** [comment]
Current status described in more detail in "Improvements to the working with the clipboard guide" [#9344](https://github.com/mdn/content/pull/9344). Other documentation changes would be dependent on updates to the navigator.clipboard method in Firefox.
