### ISSUE TITLE
Issue with "Document.cookie": In examples #5, #6 shouldn't it be "ES2015" instead of "ES2016" ?

### ISSUE THREAD

**Issue by ddziara** [mdn/content#4912]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/document/cookie`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/document/cookie/index.html
* Last commit: https://github.com/mdn/content/commit/a17729448812bfa611c2f393d5c2b1d509e2b089
* Document last modified: 2021-04-09T17:25:26.000Z

</details>

**Comment by Blakelist7** [comment]
@ddziara I think we refer ES2016 as ES7, ES2015 as ES6 and ES5 for 2009 one
so you might be right. Let's ask @hamishwillee about it.

**Comment by hamishwillee** [comment]
MDN uses official names (so  ES2015 for ES6, and ES2016 as ES7). 

But the question was whether this should be  "ES2015" instead of "ES2016". 
Depends why you think it should be ES2015? If it is because of the use of arrow functions and startsWith then you'd be right. 

However perhaps there is something else about this example which makes it ES2016. I don't know, but I'm not sufficiently expert to be sure. Which is why I didn't assign to me :-)

**Comment by Blakelist7** [comment]
Yeah I was assuming it to be ES2015 because of arrow functions. I'll do some more research on it .

**Comment by peterbe** [comment]
> Yeah I was assuming it to be "ES2015" because of arrow functions. I'll do some more research on it .
> @peterbe could you take time to explain why is it ES2016 and not ES2015?
> Thanks in advance

I can't speak to that. It's a content issue. 

However, I see that there are flaws in the live samples in that it assumes that `.find()` always returns something.

**Comment by Blakelist7** [comment]
@ddziara Refer this https://www.codementor.io/@adroitcoder/includes-vs-indexof-in-javascript-ivxhatb3y

**Comment by Blakelist7** [comment]
> > Yeah I was assuming it to be "ES2015" because of arrow functions. I'll do some more research on it .
> > @peterbe could you take time to explain why is it ES2016 and not ES2015?
> > Thanks in advance
> 
> I can't speak to that. It's a content issue.
> 
> However, I see that there are flaws in the live samples in that it assumes that `.find()` always returns something.

As per my knowledge it returns undefined if no value satisfies the condition.

**Comment by hamishwillee** [comment]
So use of ES2016 is correct for  [example 6](https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie#example_6_check_that_a_cookie_has_a_specific_value) because it uses includes, as @Blakelist7 refers to in https://github.com/mdn/content/issues/4912#issuecomment-845745687

I wonder if to avoid this coming up again we should add a note? e.g. `//ES2016` to `//ES2016 (uses includes() introduced in ES2016)`

[example 5](https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie#example_5_check_a_cookie_existence) might still be ES2015 - I don't see anything there introduced later.

**Comment by Blakelist7** [comment]
Thanks @hamishwillee for looking into the issue. Adding a note is a great idea. 
Yes, in <a href="https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie#example_5_check_a_cookie_existence">example 5</a> it should be ES2015 instead of ES2016.

**Comment by Blakelist7** [comment]
@ddziara we can close this issue. As this example has been removed as per #5031.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/4912#issuecomment-853848981
