### ISSUE TITLE
Content bug: Feature Policy in Experimental features in Firefox

### ISSUE THREAD

**Issue by jpmedley** [mdn/content#4924]
## What page(s) did you find the problem on?

Recently, the `Feature-Policy` header was renamed `Permissions-Policy`. While updating MDN reference pages, I found a Firefox page that references `Feature-Policy` as an experimental feature. Since I do not know anything about Firefox's development processes or the norms for documenting new and experimental feature, I thought it best to ask someone from Firefox to handle this. 

## Specific page section or heading?

I'm guessing there are more pages, so I'm presenting this as a list and will update it if I find more pages.

- [ ] [Experimental Features](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features)
- [x] [References scattered through release notes](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/releases)

Related to #1831 .

**Comment by hamishwillee** [comment]
[Experimental features in Firefox](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features) lists features that are experimentally implemented _in Firefox_. What this means is that the feature is hidden behind a preference/not enabled by default on Firefox - and so is "experimentally supported by Firefox". 

When I look at the section there is no implication that the `Feature Policy` header itself is experimental - just the support in Firefox. Would it help if this page was named _Firefox Experimental Features_? (and I could perhaps add an explicit note to capture the fact that features listed may not be more fully implemented in other browsers?)

Not sure what we could do about "scattered" references in the release notes. To my mind these would be low priority because no one looks at an older release note and assumes that this is a reflection of current status of a feature. They would check the appropriate page and see it is not listed as experimental.

@chrisdavidmills As an aside here, the experimental features doc introduction overly-reference "Nightly" but actually these features are potentially present in releases etc. OK if I reword?

**Comment by chrisdavidmills** [comment]
> Would it help if this page was named Firefox Experimental Features?

I don't really see how this is so different from the current title — Experimental features in Firefox.

> As an aside here, the experimental features doc introduction overly-reference "Nightly" but actually these features are potentially present in releases etc. OK if I reword?

Yes, I do agree with this. Many of the experimental features are enabled by default in Nightly, some are enabled by default right up to beta, most of them are available in release, but behind a flag. It would be great to make the intro reflect this better.

**Comment by jpmedley** [comment]
>Not sure what we could do about "scattered" references in the release notes. To my mind these would be low priority because no one looks at an older release note and assumes that this is a reflection of current status of a feature. 

That makes sense. I'm just doing due diligence. If they should be left alone, it should be by conscious choice not neglect.

**Comment by hamishwillee** [comment]
@chrisdavidmills  I read "Firefox Experimental Features" as experimental feature _of_ or _belonging to_ Firefox, while "Experimental features in Firefox" could be interpreted as "experimental features in the web" that are implemented in Firefox. You're right that the difference is subtle, and perhaps I am wrong :-). 

Firefox page fixed up in https://github.com/mdn/content/pull/5042

**Comment by Josh-Cena** [comment]
Is there anything else that could be done here (now that `Feature-Policy` doesn't even exist)?

**Comment by hamishwillee** [comment]
Nope.
