### ISSUE TITLE
Issue with "Array": Documentation seems unclear and maybe contradicting itself

### ISSUE THREAD

**Issue by elidoran** [mdn/content#4968]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array

#### Specific section or headline?

The second paragraph of "Description" section says "Arrays cannot use strings as element indexes (as in an associative array) but must use integers."

The bottom of the "Accessing array elements" section says "But it's also possible to quote the array indexes as well (e.g., years['2'] instead of years[2]), although it's not necessary."

Right after that one, it says "The 2 in years[2] is coerced into a string by the JavaScript engine through an implicit toString conversion."

So, first it says ~"no strings, must be ints", then says ~"it's okay to use a string it's just not necessary."  Then it says ~"if you use ints they are coerced into strings anyway." Seems inconsistent/unclear, to me.

I'm not confused with how to use Arrays in JavaScript, but I'm confused by this documentation's explanation.

And, saying the string coercion is "an implicit toString conversion" as an explanation of why '2' and '02' will not be the same result is unclear. I think it's saying an explicit toString conversion is a an actual conversion similar to `Number('02') which would be the same result even with multiple zeroes were in the string's front. Perhaps "implicit" is the right word for the not-really-converting-to-a-number, but, it doesn't seem so to me. I think the point they were trying to make is it's not really coercing the string to a number so that's a "gotcha" to look out for. 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/index.html
* Last commit: https://github.com/mdn/content/commit/13360cbad46b4ce6457f80492d73d2efd252e8a9
* Document last modified: 2021-05-05T10:31:52.000Z

</details>

**Comment by robinvandernoord** [comment]
I am confused. maybe @barryvdh can help??? he is a god after all.
I'm not completely sure though, since this does of course involve javascript and not PHP/laravel, however I am convinced our Lord and Saviour Barry knows his fair share of javascript as well!
Anyway, how are you all doing? I am fine thank you for asking.
Just had a long weekend but back to work now on the Tuesday eh? At least it's not monday ya know? That would suck of course. Only one more day (Thursday - yes I have a mini weekend tomorrow) and then it's weekend again.
Not that that is stopping me from drinking on the other days of course, it's like I always say: life is a party and you must drink yourself to sleep to enjoy it! Don't need fun to have alcohol am I right Barry? Or should I say mr php GOD that is fine too if you prefer :)
Have a great day and I hope to hear from you soon, because I really don't understand why `['some': 'array']` is illegal but `([])['some'] = 'array'` is not. Hence the drinking of course. Wait no that was to party never mind. I'm getting off track.
Additionally am I of the opinion that Carthage (not my child) should be destroyed (no offense though).

With kind regards,
Your biggest Fan,
Robert from the North

**Comment by robinvandernoord** [comment]
@VictorZwart test

**Comment by wbamberg** [comment]
Yes, agreed!

I wonder what value is added by any of ["Accessing array elements'](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array#accessing_array_elements) from "There is nothing special ..." onwards. What would be lost if we just deleted it?
