### ISSUE TITLE
Issue with "<xsl:import>": add compatibility issues

### ISSUE THREAD

**Issue by chchch** [mdn/content#5056]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/XSLT/Element/import

#### What information was incorrect, unhelpful, or incomplete?

<xsl:import> doesn't with work XSLTProcessor() on WebKit browsers. It fails silently, making it difficult to debug.

#### What did you expect to see?

Polyfill for WebKit browsers:

```
// loads every stylesheet specified by <xsl:import>, and deletes the <xsl:import> line
// xsltsheet is an XSLT stylesheet document that has been loaded previously

for(const x of xsltsheet.querySelectorAll('import')) {
    const resp = await fetch(x.getAttribute('href'));`
    const i = (new DOMParser()).parseFromString(await resp.text(), 'text/xml');
    while(i.documentElement.firstChild)
        x.before(i.documentElement.firstChild);
    x.remove();
}
```

#### Did you test this? If so, how?

In Safari and GNOME Web.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/xslt/element/import`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/XSLT/Element/import
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/xslt/element/import/index.html
* Last commit: https://github.com/mdn/content/commit/f4d1f3ae79b27852d8e211d3a6132144fc3196e3
* Document last modified: 2020-12-18T22:58:01.000Z

</details>

**Comment by Josh-Cena** [comment]
This issue has been open for more than 3 years and the XSLT reference has received zero maintenance. In addition, we don't maintain XSLT compat data at all anymore (https://github.com/mdn/browser-compat-data/issues/9826) so instead of having sporadic compatibility notes that are unmaintainable and basically unverifiable since we don't have the infrastructure, it's better that we call the XSLT docs frozen.
