### ISSUE TITLE
Issue with "Loading and running WebAssembly code": What is importObject?

### ISSUE THREAD

**Issue by parsarahimi** [mdn/content#5083]
Can someone explain what is importObject? I have some rough idea like how it's to do with linking functions and stuff but can't you just automate this? Earlier I also compiled a wasm from AssemblyScript, sometimes it just works without importObject, other times when the function I use takes in Arrays it starts giving the error  "Imports argument must be present and must be an object"

**Comment by sideshowbarker** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/instantiate#syntax states:

> <em>importObject</em> <span class="badge inline optional">Optional</span>
> An object containing the values to be imported into the newly-created <code>Instance</code>, such as functions or <a href="/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Memory"><code>WebAssembly.Memory</code></a> objects.  There must be one matching property for each declared import of the compiled module or else a <a href="/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/LinkError"><code>WebAssembly.LinkError</code></a> is thrown.

So I’m going to close this, since we do have the `importObject` parameter documented. But if any of that is unclear or incomplete, and you can describe what’s not clear to you, or what’s missing, then we can revisit this issue.

Otherwise, this seems more like a question that you might consider asking at site such as Stack Overflow.
