### ISSUE TITLE
Issue with "Date.prototype.toLocaleString()": missing documentation for "options"

### ISSUE THREAD

**Issue by Amunak** [mdn/content#5144]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString

#### What information was incorrect, unhelpful, or incomplete?
The documentation is woefully incomplete, especially for the "options" argument of `Date.ToLocaleString`. There is no list of arguments or possible values. Not even something as basic as the `style` argument which decides how the whole thing will render. Instead there is a "Using Options" section which hints at the possibilities and shows some (in my opinion ineffectively as one giant example script), but doesn't even list all the option names.

#### What did you expect to see?
A table/list of options, possible values and explanations. Like with, say, [`Intl.NumberFormat` parameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat#parameters).

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/date/tolocalestring`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/date/tolocalestring/index.html
* Last commit: https://github.com/mdn/content/commit/13360cbad46b4ce6457f80492d73d2efd252e8a9
* Document last modified: 2021-05-05T10:31:52.000Z

</details>

**Comment by himanshugarg** [comment]
Newbie comment, the page also notes "See the Intl.DateTimeFormat() constructor for details on these parameters and how to use them.". The referenced provides a detailed listing of options.

**Comment by Amunak** [comment]
That might be my blindness, but that's in my opinion the single most important part of that whole documentation page, and it's very easy to miss.

At the very least I would repeat it again in the "Using Options" section, and ideally it should be more prominent.

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/5908 with a fix that hopefully gives the existing note more prominence, and that also adds the same note to the **Using locales** and **Using options** sections.

**Comment by Amunak** [comment]
Thank you for looking into this, looks great, I'm sure it'll prevent some confusion for at least a few people. :)

**Comment by sideshowbarker** [comment]
To whoever works on this, see comment at https://github.com/mdn/content/pull/5908#pullrequestreview-683420053

**Comment by Josh-Cena** [comment]
While working on this, I noticed we have https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString completely duplicated from /en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat (introduced in https://github.com/mdn/content/pull/16295) — I have to say I don't like it at all as it makes future maintenance much harder. Should we also remove that duplication, and point all `toLocaleString` methods to their `Intl` counterparts? They are summarized in https://tc39.es/ecma402/#locale-sensitive-functions quite cleanly.

**Comment by wbamberg** [comment]
Sigh. We don't really have a good solution here. I think this is a place where the needs of readers and the needs of maintainers are opposed. If we have the parameters only in one place and link to them, we get issues like https://github.com/mdn/content/issues/11174, where people are unable to find them. If we duplicate them then as you say we have a maintenance problem (which is why we didn't do it in the first place).

Not duplicating them is made worse because it's extremely unconventional on MDN - we pretty much always list all arguments. So it's very surprising for people when we don't.

A third option is to define the things in one place and have a macro duplicate them. We used to do this in a rather chaotic way but stopped, because it created other problems (primarily that the source content would be updated in such a way that it didn't make sense in its destination contexts) and because it made the platform code a lot more complicated.

On balance I think it would be better to live with the duplication here: this is a fairly isolated case on MDN and duplicating it is likely to be better for readers. But I don't feel that strongly about it.

**Comment by Josh-Cena** [comment]
Would it be better if we use a more organized `dl` form, as you mentioned in https://github.com/mdn/content/pull/5908#pullrequestreview-683420053? I think it becomes much more visible that there _is_ an argument called "options" just that it's explained elsewhere.

**Comment by wbamberg** [comment]
Yes, that sounds like a good plan to me!
