### ISSUE TITLE
Issue with "repeating-linear-gradient()": (No longer working in FireFox)

### ISSUE THREAD

**Issue by WebWizzards** [mdn/content#5201]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/repeating-linear-gradient()

#### What information was incorrect, unhelpful, or incomplete?
ALL repeating-linear-gradient are no longer working in FireFox 88.0.1 (64-bit), my website has the follwing code which no longer renders! Please fix..

.css {
background:
 linear-gradient(45deg, hsla(28, 91%, 43%, 1) 0%, hsla(28, 91%, 43%, 0) 70%),
 linear-gradient(135deg, hsla(256, 91%, 42%, 1) 10%, hsla(256, 91%, 42%, 0) 80%),
 linear-gradient(225deg, hsla(96, 93%, 44%, 1) 10%, hsla(96, 93%, 44%, 0) 80%),
 linear-gradient(315deg, hsla(274, 96%, 41%, 1) 100%, hsla(274, 96%, 41%, 0) 70%);linear-gradient(45deg, hsla(28, 91%, 43%, 1) 0%, hsla(28, 91%, 43%, 0) 70%),
}

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/repeating-linear-gradient()`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/repeating-linear-gradient()
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/repeating-linear-gradient()/index.html
* Last commit: https://github.com/mdn/content/commit/775066d2fc8d1561d5da61983d137c1297899315
* Document last modified: 2021-05-08T09:57:47.000Z

</details>

**Comment by rachelandrew** [comment]
Hi @WebWizzards this isn't the best place to raise issues with browsers, however I pasted your gradient into a CodePen and it renders identically in Firefox and Chrome https://codepen.io/rachelandrew/pen/59d647236a755722fdf3c5f6ea9718b9

Perhaps there is something else on your page causing the issue.

This repo is for issues with the MDN documentation, do for example if there was some incorrect code in one of our examples. I don't think this is the case here, so I'll close this issue. Please re-open if you believe your problem is related to our docs in some way.
