### ISSUE TITLE
Issue with "Web performance resources": resource hints hyperlink is invalid

### ISSUE THREAD

**Issue by FaresAhmedb** [mdn/content#5263]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Performance/Web_Performance_Basics

#### What information was incorrect, unhelpful, or incomplete?
The hyperlink to `resource hints` is invalid in #best_practices:

- Using <a href="/en-US/docs/Web/Performance/Controlling_resource_delivery_with_resource_hints">resource hints</a> such as `rel=preconnect`, `rel=dns-prefetch`, `rel=prefetch`, and \
`rel=preload`

#### Specific section or headline?
The *#best_practices* section
https://developer.mozilla.org/en-US/docs/Learn/Performance/Web_Performance_Basics#best_practices

#### What did you expect to see?
A valid hyperlink to `resource hints`

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/performance/web_performance_basics`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Performance/Web_Performance_Basics
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/performance/web_performance_basics/index.html
* Last commit: https://github.com/mdn/content/commit/3af43c1dcfb9be19c73cf3fdd1178db9c74aa064
* Document last modified: 2021-04-27T01:03:07.000Z

</details>

**Comment by hamishwillee** [comment]
@FaresAhmedb A broken link means that the page does not exist - it may not have been written, it might reflect a page that has been deleted but the link has not been cleaned up, or the page might exist, but the link to it is incorrect. We're working on making this more clear by having ALL broken links in red, and a note on the 404 not found page.

In this case the link is a "wanted page" - a page that the author of this page thought would be useful but has not yet written. 
You can write it yourself, or someone may get to it eventually. 

I have actually removed the broken link in #5267 and instead linked to the rel= pages for each of the cases listed. Further down I fixed a link that was broken due to a type. This is my general approach when I encounter any broken link - search for the link text and for the link URL. Often this finds me enough information in other pages.
