### ISSUE TITLE
Navigator.vibrate()

### ISSUE THREAD

**Issue by SteinPanyu** [mdn/content#5277]
Hello, 
Navigator.vibrate() only allows me to set the duration and interval.

How can I customize the intensity of vibration?

Thanks!

**Comment by teoli2003** [comment]
Hi, SteinPanyu!

If I read the [specification](https://w3c.github.io/vibration/) correctly, there is no way to set up the intensity of the vibration.

This means that the MDN documentation is correct. If you would like such feature to be added, you should open an issue with the specification (follow the link above).

I propose to close the issue here.

Thanks again for asking!
