### ISSUE TITLE
Issue with "CSP: script-src": (short summary here please)

### ISSUE THREAD

**Issue by jf** [mdn/content#5286]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src (*and* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src-elem)

#### What information was incorrect, unhelpful, or incomplete?

in both pages, the explanation for the `'unsafe-inline'` source mentions "inline <style> elements". But given that these directives (`script-src`, and `script-src-elem`) are about specifying sources for *JavaScript*, surely this means that "inline <style> elements" are excluded?

#### Specific section or headline?

section explaining `'unsafe-inline'`

#### What did you expect to see?

An explanation that is relevant to the directive, and that does not mention inline <style> elements at all.

ALSO:
- is `'unsafe-inline'` even valid for `script-src-elem`, given that "The HTTP Content-Security-Policy (CSP) script-src-elem directive *specifies valid sources for JavaScript <script> elements, __but not inline script event handlers like onclick__.*" ?
- when is support for `script-src-elem` coming to Firefox?

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/headers/content-security-policy/script-src`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/content-security-policy/script-src/index.html
* Last commit: https://github.com/mdn/content/commit/8d4fd702d9668604cb2788da5bd9fc9b796ec30a
* Document last modified: 2021-03-17T20:27:56.000Z

</details>

**Comment by sideshowbarker** [comment]
To whoever works on this:

The root cause of this is that the source of both https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#sources and https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src-elem#sources is transcluded from https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/default-src#sources using the `page()` macro mechanism described in https://developer.mozilla.org/en-US/docs/MDN/Structures/Macros/Other#transclusion.

That is, it’s the same root cause as https://github.com/mdn/content/issues/2460.

So a possible solution is to remove that `page()` macro call, and replace it with actual content in the source of the https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src and https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src-elem articles themselves.

The downside of that is that we end up duplicating quite a bit of content.

**Comment by teoli2003** [comment]
I hate the page macro, so I went for copying an adapted text in the three pages:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src-elem
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src-attr
