### ISSUE TITLE
Create tracking issues for "TODO:" items in articles

### ISSUE THREAD

**Issue by nschonni** [mdn/content#538]
There are a few non-placeholder ones in https://github.com/mdn/content/search?q=TODO%3A, but maybe the few that are should be spun up as issues and the placeholders removed

**Comment by peterbe** [comment]
That's interesting! I think you're referring to KS macro usage like `{{TODO("Needs a description")}}` for example, right?

I would argue this is bad. It's a hangover from the Wiki days when you couldn't have a draft. If you didn't have all the information when you're writing, your only choice was to publish the Wiki revision so you didn't lose what you already have in action. With GitHub PRs you can create genuine drafts. 
I think usage of the `TODO` macro should be considered a flaw. But also, there's currently no good way of "blocking" a PR just because it has flaws.

But we have the "Flaws Dashboard" (although it needs some improvements) but that was you should be able to spot all pages that have that macro and then you can deal with them one at a time.

**Comment by nschonni** [comment]
Didn't realize there was a tag, it was actually after coming across:

https://github.com/mdn/content/blob/a7859ac7637e3b98936de20199682b680ec84b42/files/en-us/games/techniques/tilemaps/square_tilemaps_implementation_colon__scrolling_maps/index.html#L42

But I can see my GitHub search result is pulling in a bunch of other stuff

**Comment by nschonni** [comment]
Found another related type of these if you search for `class="comment"`
