### ISSUE TITLE
[JavaScript] Private fields and private methods are now enabled

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#5386]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated - track in https://github.com/mdn/browser-compat-data/pull/10854 (also in https://github.com/mdn/browser-compat-data/pull/11042)
3. - [x] Interactive example and data repos are updated if appropriate - NA
4. - [x] The content has been reviewed as needed

## Features to document

1. Private fields are enabled
2. Private methods are enabled
One issue for both as I'm sure this affects similar pages - probably best to tackle together

## Related Gecko bugs
1. - [x] [Flip pref for private fields](https://bugzilla.mozilla.org/show_bug.cgi?id=1708235). 
2. - [x] [Flip pref for private methods](https://bugzilla.mozilla.org/show_bug.cgi?id=1708236)

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by Blakelist7** [comment]
@Rumyra Please correct me if I am doing in the wrong direction.
In this issue we have to add docs about Private fields and Private methods, right? Also if I am pointing in the right direction let me know where I can find more info about this issue.

**Comment by Rumyra** [comment]
Hi @Blakelist7 :) I'm yet to review what's required - I'll update this issue for you once I have 👍

**Comment by Rumyra** [comment]
We should concentrate on the class reference pages - there's a lot of pages that need updating with private field/methods on MDN. Here's a list

### Pages that need a review & updated information

Fields:

- [ ] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes
- [ ] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields

Methods:

- [ ] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes - new section needed

### New pages needed

- [ ] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_methods

Leaving here for ref https://tc39.es/proposal-class-fields/unified.html

**Comment by meyerweb** [comment]
So in #5690, it came up that maybe instead of having one page that covers both fields and methods, there should be separate pages.  This issue seems to assume that structure.  Is there an editorial reason for that?  I’m asking not to push back, as I nearly split the page myself and so am quite open to the idea.  I more want clarity/a working out of best practices here before I clean up #5690 and submit it for final merge.

**Comment by hamishwillee** [comment]
> So in #5690, it came up that maybe instead of having one page that covers both fields and methods, there should be separate pages. This issue seems to assume that structure. Is there an editorial reason for that? I’m asking not to push back, as I nearly split the page myself and so am quite open to the idea. I more want clarity/a working out of best practices here before I clean up #5690 and submit it for final merge.

@meyerweb No idea about editorial process. But IMO it is only a good idea to have separate pages when it is clearly a bad idea. i.e. you separate pages when things are clearly separate ideas/concepts that share no information or common thinking, or because you have something so monolithic you can't see the wood for the trees, or for discoverability via search etc. To my mind these concepts go together and I personally would not split them. Or at least I would look at the finished doc and think "could someone find this by search", "is this too intimidating for the reader" etc. 

I'm pretty sure you can do what you like and then we can argue as a post process.

**Comment by hamishwillee** [comment]
@Rumyra I assigned this to me on an old non-updated tab, so did not see all this chit chat. I'm putting my hand up to own this but happy for you to punt it over to someone else. 

If this belongs to me then my steps would be BCD. Then I'd wait on #5690. After that goes in this is pretty easy because mostly it is just removing mentions of the preference.

My interest is because I started thinking about https://github.com/mdn/content/issues/5380 , which provides an easy way to check whether a private instance variable exists. That would update both docs. I'm actually wondering if you'd like to do the work on that @meyerweb because you're clearly much better at Javascript docs than I am :-) ?

**Comment by Rumyra** [comment]
@meyerweb Pretty much what @hamishwillee said

> IMO it is only a good idea to have separate pages when it is clearly a bad idea to have a single page. i.e. you separate pages when things are clearly separate ideas/concepts that share no information or common thinking, or because you have something so monolithic you can't see the wood for the trees, or for discoverability via search etc

I err on the side they should be separate pages, but also this shouldn't be a blocker to getting the amazing work you've done merged - also what Hamish said

> I'm pretty sure you can do what you like and then we can split this later if it becomes unmanagable.

Yes we can absolutely do this, unless of course you want to and it's not difficult

@hamishwillee Thank you 🙏  yes there is the little bits for a release project that would still need to be done (BCD, notes etc...) so I am _extremely_ happy for you to take this on... it's outside the scope of Eric's PR and here I was merely reviewing what needed to be done content wise as it was quite a few pages 👍

**Comment by hamishwillee** [comment]
Release tracking:
- [ ] Docs updates: To review after https://github.com/mdn/content/pull/5690 goes in. Should mostly be removing anything that talks about how to enable the preference
- [ ] [BCD](https://github.com/mdn/browser-compat-data/pull/10854)
- [ ] Remove from [Experimental Features](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features#private_class_fields)
- [ ] Release note
- [ ] dev-doc-complete updates for the two gecko cases above.

**Comment by Rumyra** [comment]
Thanks @hamishwillee - looks super 🙌
