### ISSUE TITLE
Issue with "content_security_policy": Another MDN entry says filesystem urls are deprecated and not supported

### ISSUE THREAD

**Issue by MikuChan03** [mdn/content#5429]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_security_policy

#### What information was incorrect, unhelpful, or incomplete?
"The only permitted schemes for sources are: blob:, filesystem:, moz-extension:, https:, and wss:"

#### Specific section or headline?
No such thing.

#### What did you expect to see?
According to the compatibility table on
https://developer.mozilla.org/en-US/docs/Web/API/FileSystemEntry/toURL#browser_compatibility
firefox has stopped supporting the generation of "filesystem://" urls, so if webextensions still support them,
I would expect to see how they would be created.

#### Did you test this? If so, how?
I read it.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/manifest.json/content_security_policy`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_security_policy
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/manifest.json/content_security_policy/index.html
* Last commit: https://github.com/mdn/content/commit/fe24b58830a1e3bee3e9531dcc626d0a0789a9b4
* Document last modified: 2021-05-26T07:24:04.000Z

</details>

**Comment by MikuChan03** [comment]
What?

**Comment by MikuChan03** [comment]
Should I submit a pull request, simply removing the filesystem url from the list? What's the holdup?

**Comment by hamishwillee** [comment]
I wouldn't remove it from the list because irrespective of what Firefox does, other browsers support this option in their manifest list and they might support filesystem URLS. To remove this you'd need to show it wasn't supported anywhere.

Further, I can't see where it says that Firefox has stopped supporting filesystem URLs in https://developer.mozilla.org/en-US/docs/Web/API/FileSystemEntry/toURL#browser_compatibility

With respect to hold up, the team is pretty busy, the inflow very large, and weekends are often respected. We do our best.

**Comment by MikuChan03** [comment]
Sorry, I was being too confrontational. Alright then, since other browsers might still support this, should I close the issue?
As for your question, I would assume that if the creation of filesystem urls has a "no" in the table, than it would follow that the infrastracture to support them could be removed, but I don't know that for sure.

**Comment by hamishwillee** [comment]
No worries, it's a valid question and attempt to improve the docs. I will close this. 


> I would assume that if the creation of filesystem urls has a "no" in the table, than it would follow that the infrastructure to support them could be removed, but I don't know that for sure.

But my first take was that when it said "schemes for sources are: blob:, filesystem:," that didn't necessarily mean that `FileSystemEntry.toURL()` was the only way to support a fileystem URL in the context of content security policies. But I didn't do proper/full research on this because (as discussed) if some browsers support the filesystem URLs we can't act on this. Upshot you might right :-)
