### ISSUE TITLE
Issue with "Regular expressions": Minor Typo

### ISSUE THREAD

**Issue by patrickkon** [mdn/content#5435]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions

#### What information was incorrect, unhelpful, or incomplete?
Refer below.

#### Specific section or headline?
`/a\*b/ and new RegExp("a\\*b") create the same expression`

#### What did you expect to see?
`/a\*b/ and new RegExp("a\*b") create the same expression`

#### Did you test this? If so, how?
No.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/guide/regular_expressions`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/regular_expressions/index.html
* Last commit: https://github.com/mdn/content/commit/847e7038dcb20f60efca5e04da1495799335ce3a
* Document last modified: 2021-05-11T04:28:05.000Z

</details>

**Comment by spikecodes** [comment]
Thanks for this contribution! I believe the use of two backslashes is intentional.

The `new RegExp()` constructor accepts a string literal and the backslash is an escape in string literals. Therefore, you need two backslashes (as used by the current implementation): one for escaping the asterisk in the regular expression and one in the string literal for escaping the first backslash.

This can be demonstrated in a JavaScript console:
```js
"a*b".replace(/a\*b/, "x"); // Returns "x"
"a*b".replace(new RegExp("a\\*b"), "x"); // Returns "x"

"a*b".replace(new RegExp("a\*b"), "x"); // Returns "a*x"
```

**Comment by teoli2003** [comment]
I confirm what @spikecodes said: in a string "", \ is the escape character, and must be escaped itself.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/5435#issuecomment-850768441
