### ISSUE TITLE
Issue with "eval()": (short summary here please)

### ISSUE THREAD

**Issue by rolivo3** [mdn/content#5508]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval

#### What information was incorrect, unhelpful, or incomplete?
Hello, I think this article is a bit harmful for the mental health of the developers, to say that "eval" is bad is something painful and does not let me sleep. Could you write something that is less judgmental and more productive?
for example:

"eval is a powerful function and therefore has its own risks, use it if you know what it does or have no alternative"

There are several articles in mdn that need to be less judicious, I could write them if you allow me.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/eval`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/eval/index.html
* Last commit: https://github.com/mdn/content/commit/13360cbad46b4ce6457f80492d73d2efd252e8a9
* Document last modified: 2021-05-05T10:31:52.000Z

</details>

**Comment by sideshowbarker** [comment]
The admonitions in the `eval()` article are consistent with consensus `eval()` in the wider community, and so are intentionally strongly worded in order to strongly and clearly warn developers to avoid using `eval()`.

Wording like what the `eval()` article has isn’t just intended for experienced developers — instead, it’s intended primarily for less-experienced developers who may not yet learned enough on their own to confidently make their own judgements about things like when and when not to use `eval()`.

So just telling less-experienced developers *“use it if you know what it does or have no alternative”* isn’t a sufficiently strong enough statement to convey the risks clearly to developers.

Therefore, I’m going to go ahead and close out this issue. If you have a concrete proposal for alternative language for the article, please consider creating a pull request.
