### ISSUE TITLE
Issue with "Object.prototype.__proto__": (short summary here please)

### ISSUE THREAD

**Issue by rolivo3** [mdn/content#5509]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/proto

#### What information was incorrect, unhelpful, or incomplete?
Hello, this information is not true, __proto__ is not deprecated and you can see it in the specification https://github.com/tc39/ecma262/pull/2125

#### What did you expect to see?
The text makes extreme judgments and is harmful to the mental health of the developers (it does not let me sleep), it should be replaced by:

__proto__ is a functionality that is maintained for compatibility reasons, use it if you know what it does or have no other alternatives, always prefer to use the functionalities of the object "Object".

Remove the note about performance as it is not endorsed by any source.

Thanks

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/object/proto`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/proto
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/object/proto/index.html
* Last commit: https://github.com/mdn/content/commit/13360cbad46b4ce6457f80492d73d2efd252e8a9
* Document last modified: 2021-05-05T10:31:52.000Z

</details>

**Comment by sideshowbarker** [comment]
Per the TC39 2020-09-21 meeting notes at https://github.com/tc39/notes/blob/master/meetings/2020-09/sept-21.md#conclusionresolution-1:
> The proto accessor will be optional and marked as discouraged.

And confirmed through discussion on the TC39 Matrix channel at https://bakkot.github.io/matrix-logs/TC39_General/2021-05-31#L0.

So, given that, it does not seem incorrect and inappropriate for MDN to also mark `Object.prototype.__proto__` as deprecated. And the rest of the language in the notes seems consistent with how elaborations about discouraged features should be worded in order to provide developers with sufficient information. So I’m going to go ahead and close out this issue.

As far as the note about performance, if you have evidence that the statements in that note aren’t accurate, please raise a separate issue for that.
