### ISSUE TITLE
Links to /Special:Tags

### ISSUE THREAD

**Issue by nschonni** [mdn/content#551]
There are around 4 of these left over from the wiki migration. Not sure what they should redirect to

**Comment by Ryuno-Ki** [comment]
I did some research:

https://github.com/mdn/content/blob/d54141e8f5fac3effe8ed12fcde9369617e655ba/files/en-us/mozilla/developer_guide/interface_development_guide/index.html#L29

https://github.com/mdn/content/blob/d54141e8f5fac3effe8ed12fcde9369617e655ba/files/en-us/mozilla/developer_guide/build_instructions/index.html#L110

https://github.com/mdn/content/blob/d54141e8f5fac3effe8ed12fcde9369617e655ba/files/en-us/mozilla/firefox/releases/12/index.html#L72

are the places I could find.

In MediaWiki (I assume it's legacy code), a Special: Tags page would like so:
https://www.mediawiki.org/wiki/Special:Tags

Thus, I'd suggest to remove the links (unless we find a better target to point to).

**Comment by hamishwillee** [comment]
Essentially these point to mediawiki tags. MDN still has tags, they just aren't referenced with the same URL. So the "easy fix" would be to replace these links with whatever we use to link to a list of all topics with a particular tag in the current docs system ..... Which is?

I think we can close two of the issues either way. I still think being able to link to lists of tags is useful - otherwise why have them?

**Comment by hamishwillee** [comment]
This should be closed by https://github.com/mdn/content/pull/1966

**Comment by Rumyra** [comment]
👍 thanks @hamishwillee
