### ISSUE TITLE
Issue with "Introduction to events": explaining how inline event handlers are processed

### ISSUE THREAD

**Issue by TCookz** [mdn/content#5578]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events

#### What information was incorrect, unhelpful, or incomplete?
There used to be a paragraph explaining how inline event handlers are processed, something like this
"When the event handler is specified as an HTML attribute, the specified code is wrapped into a function with the following parameters ..."

This has been removed.

#### Specific section or headline?
Inline event handlers — don't use these

#### What did you expect to see?
The information that was previously available.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/building_blocks/events`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/building_blocks/events/index.html
* Last commit: https://github.com/mdn/content/commit/954c37630ae820baa8ea211c8cc50d7ee74d4708
* Document last modified: 2021-05-20T09:17:35.000Z

</details>

**Comment by sideshowbarker** [comment]
I agree with https://github.com/mdn/content/issues/5578#issuecomment-854288743 — and given that this issue has been open for more than a year without anybody picking it up and creating a PR, it seems likely it would just continue to remain open for much longer without any activity.

Therefore, I’m making a judgement call and going ahead and closing it. If it turns out that anybody feels strongly otherwise, it could be re-opened.
