### ISSUE TITLE
Replace useful color style in tables without losing the semantic

### ISSUE THREAD

**Issue by teoli2003** [mdn/content#5728]
While working on #5438, I found two problematic pages I don't have an easy solution to remove the style attributes.

These are 
https://developer.mozilla.org/en-US/docs/web/api/keyboardevent/code/code_values
and
https://developer.mozilla.org/en-US/docs/web/api/keyboardevent/keycode

In these two pages we use style attributes to colorize the background of some table cell, indicating a kind of warning/difference.
<img width="1370" alt="Screen Shot 2021-06-06 at 13 14 04" src="https://user-images.githubusercontent.com/1466293/120922386-210a9580-c6c9-11eb-9d78-e35a53352b24.png">

@wbamberg , @perterbe, what do you think should we do?

**Comment by wbamberg** [comment]
Some options, in order of the amount of work involved, least to most:

(1) Keep the styles: since these are all in tables that are [incompatible with GFM](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Markdown_in_MDN#tables), they will stay as HTML anyway, so we don't have to remove the styles.

(2) Remove the styles: I think the styles aren't necessary or even terribly useful here, and it would be no big loss to remove them.

(3) Redesign the tables to obviate the need for these styles. For example for https://developer.mozilla.org/en-US/docs/web/api/keyboardevent/code/code_values we could have:
* a big table for codes that are the same in both browsers, that doesn't duplicate them
* smaller tables for code that are present in each and not the other
* a table for code that are present in both but different

That might be more readable and clearer too. https://developer.mozilla.org/en-US/docs/web/api/keyboardevent/keycode is I think barely usable, with a giant complex table that breaks the page layout.

I think, from the point of view of Markdown, any of these would be fine. (1) is the least work, obviously, and (3) is the most. But (3) probably gives the best result. Maybe choose (1) for this project and file an issue to improve the design of these pages, as a separate activity?

**Comment by sideshowbarker** [comment]
Something we did in https://github.com/mdn/content/pull/4151 was to replace the background colors with color emoji — specifically, ✅ U+2705 WHITE HEAVY CHECK MARK and ❌ U+274C CROSS MARK — as can be seen for in the **Sameness comparison** table in the [**A model for understanding equality comparisons?** section](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness#a_model_for_understanding_equality_comparisons) of the **Equality comparisons and sameness** article.

Maybe something similar would work here.

**Comment by teoli2003** [comment]
I like the idea: definitively worth a try. It will not get rid of the HTML table in Markdown, but will improve accessibility as information coded through color only is not good for everyone).

**Comment by teoli2003** [comment]
I tried to apply it to https://developer.mozilla.org/en-US/docs/web/api/keyboardevent/code/code_values .
Not perfect, but I think it is much better. Feedback welcome in PR #5825.

**Comment by sideshowbarker** [comment]
>  Not perfect, but I think it is much better.

Very cool — I think it works well for those tables.

> Feedback welcome in PR #5825.

I just now provided some feedback in the form of a commit that attempts to ensure the “caution” symbols get displayed a color emoji :)
