### ISSUE TITLE
wrong Singapore currency symbol

### ISSUE THREAD

**Issue by roni6chabra** [mdn/content#575]
Hi,
when I try to get the Singapore currency as here
`Intl.NumberFormat("en-SG", { style: 'currency', currency: "SGD", currencyDisplay: "symbol" }).format(Number(599))`

I get the wrong currency symbol $ but it supposes to be S$
can you please fix it?

**Comment by SphinxKnight** [comment]
It looks that this is more an issue to be filed against browser engines rather than the documentation from this repo.

I found this one for Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=995026 and could not find any related issue (as far as I searched) for Firefox on https://bugzilla.mozilla.org/

**Comment by longlho** [comment]
`$` is correct bc u specified your locale is `en-SG` (English in Singapore). Singaporean calls USD `US$` and their currency just `$`, the same way American calls USD as just `$`. See https://unpkg.com/browse/cldr-numbers-full@38.1.0-BETA4/main/en-SG/currencies.json (search for `SGD`).

This can be closed.
