### ISSUE TITLE
Issue with "String.prototype.indexOf()": ( written code ('Blue Whale'.indexOf('Bloe')) should return -1 instead of 0)

### ISSUE THREAD

**Issue by MadeWilliam** [mdn/content#5809]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/indexOf

#### What information was incorrect, unhelpful, or incomplete?
on below code, ('Blue Whale'.indexOf('Bloe')) should return -1 instead of 0

'Blue Whale'.indexOf('Blue') !== -1  // true
'Blue Whale'.indexOf('Bloe') !== -1  // false
~('Blue Whale'.indexOf('Bloe')) // 0, which is falsy  

#### Specific section or headline?
Checking occurrences

#### What did you expect to see?
Change Bloe to Blue

~('Blue Whale'.indexOf('Blue')) // 0, which is falsy  

#### Did you test this? If so, how?
using browser console by testing below code returned -1
console.log('Blue Whale'.indexOf('Bloe'))

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/string/indexof`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/indexOf
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/string/indexof/index.html
* Last commit: https://github.com/mdn/content/commit/13360cbad46b4ce6457f80492d73d2efd252e8a9
* Document last modified: 2021-05-05T10:31:52.000Z

</details>

**Comment by sideshowbarker** [comment]
The example isn’t testing that `'Blue Whale'.indexOf('Blue') == true`, right?

Instead the example is testing that `'Blue Whale'.indexOf('Blue') !== -1`, which _is_ true because `0 !== -1`, right?

**Comment by sideshowbarker** [comment]
Thanks for reporting this.

> using browser console by testing below code returned -1
> console.log('Blue Whale'.indexOf('Bloe'))

Well, the correct way to use `console.log` to test that example is actually this:

```js
console.log(~('Blue Whale'.indexOf('Bloe')))
```

But anyway, I guess that part of the existing example in the docs is not good, because there’s really no point in doing `~(…)` — using the [bitwise NOT](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_NOT) operator to invert the whole expression.

What I mean is, both of the following are falsy:

```js
~('Blue Whale'.indexOf('Bloe')) //  0, which is falsy
~('Blue Whale'.indexOf('Blue')) // -1, which is falsy also
```

So I can’t see any value in using the bitwise NOT operator in this case — because if you wanted to invert the tests in the examples, you could just use `=== -1` instead of `!== -1`.

Given all that, I opened https://github.com/mdn/content/pull/5812 with a fix that just completely drops that part of the example.
