### ISSUE TITLE
Content bug: JSON syntax formatting: Web page differs from source

### ISSUE THREAD

**Issue by MarcelWaldvogel** [mdn/content#5911]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON

## Specific page section or heading?

[Full JSON syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON#full_json_syntax)

## What is the problem?

The section does not match the source code on GitHub

## What did you expect to see?

[The definition of `ExponentPart`](https://github.com/mdn/content/blame/main/files/en-us/web/javascript/reference/global_objects/json/index.html#L78) says that the lower case `e` as an introductory character of the exponent notation should be highlighted the same as an upper case `E`, using `<strong>`. However, the lower case `e` is rendered in the base format (not surrounded by any tags), while the upper case `E` is represented as `<span class="token constant">E</span>`, and thus showing up in red.

If you think this is nit-picking, feel free to just close the issue. I am opening the issue as it might be the symptom of a more wide-spread problem.

## Did you test this? If so, how?

Looked at the web page source code, while creating PR #5909.

**Comment by wbamberg** [comment]
Thanks for filing! This is expected: the platform strips out any internal markup inside code blocks, which I believe is related to the way it does syntax highlighting.

**Comment by MarcelWaldvogel** [comment]
It only strips part of the internal markup, e.g., it stripped it from `<strong>e</strong>`, but *not* from `<strong>E</strong>` (the difference is the capitalization of the enclosed text). In fact, the `E` version was translated to the `<span>` construct described above.

If that page is the only one causing this discrepancy, it probably will be "solved" by PR #6104 (this no longer requires markup in code blocks, but for different reasons).

**Comment by wbamberg** [comment]
Sorry, my answer here was incomplete.

The red highlighting for `E` isn't because of the `<strong>` tags, it's because the `pre` block has `class="brush: js"` set on it. This means MDN will try to apply JavaScript code syntax highlighting (and as part of the prep for that it strips out all internal markup).

Because the content isn't actually JS, it ends up looking like a mess. You can see this by removing `class="brush: js"` from the `pre`. It will then get rendered like this:

<img width="598" alt="Screen Shot 2021-06-22 at 1 45 36 PM" src="https://user-images.githubusercontent.com/432915/123014772-c8e7ba80-d37b-11eb-9aba-669a9f1d7e3a.png">

> If that page is the only one causing this discrepancy, it probably will be "solved" by PR #6104 (this no longer requires markup in code blocks, but for different reasons).

Yes, that PR should fix this, because it's removing the class attribute that incorrectly identifies this as a JS code block.
