### ISSUE TITLE
CORS Issue when using the API in a Vue component

### ISSUE THREAD

**Issue by Oktogazh** [mdn/content#5953]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Using_Web_Audio_API

#### What information was incorrect, unhelpful, or incomplete?
I had problems trying to implement the instructions in a Vue component. It turned out that I had to add the `crossorigin="anonymous"` to be able to hear the sound. One should to add a comment concerning this potential issue, although it only occurred in a Vue component, not when using vanilla JS in a script tag.

#### Specific section or headline?
When introducing the `AudioContext.destination` object.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/web_audio_api/using_web_audio_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Using_Web_Audio_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/web_audio_api/using_web_audio_api/index.html
* Last commit: https://github.com/mdn/content/commit/8a4814c74237b4e955121c28a935703142af6f8d
* Document last modified: 2021-06-06T07:20:28.000Z

</details>

thanks for your tutorials!

**Comment by Josh-Cena** [comment]
This issue is quite old, but it's unactionable without some more information.

CORS has nothing to do with Vue or not, but more with how your app is served. @Oktogazh could you give us a way to reproduce it? Are you serving your Vue app through a dev server (a port on localhost)? Are you serving your vanilla JS through `file://`?
