### ISSUE TITLE
”BigInt values are unsuitable for use in cryptography” claim

### ISSUE THREAD

**Issue by DNiebel** [mdn/content#6006]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#usage_recommendations

## Specific page section or heading?

Cryptography

## What is the problem?

The following is stated here:
> The operations supported on BigInt values are not constant-time. BigInt values are therefore [unsuitable for use in cryptography](https://www.chosenplaintext.ca/articles/beginners-guide-constant-time-cryptography.html).

The above claims a significant link between cryptography and constant-time. This link seems tenuous. to me Furthermore, the inputKey checking described in the article, any attack can be foiled by hashing the inputKey and the correctKey with a randomly chosen salt before checking for equality.

## What did you expect to see?

BigInt objects and methods can be used in cryptography and allow JS code to be almost as efficient as compiled code.

**Comment by sideshowbarker** [comment]
@twiss, any insight on this one?

**Comment by twiss** [comment]
Hey :wave: Constant-timing is very important in cryptography. The linked article gives only one example of this, but there are many others. As a more relevant example to BigInt, when implementing RSA, big numbers are required for the computations, but care needs to be taken to implement it in constant-time, in order to avoid leaking information about the private key. For this reason, if possible, it's preferable to use Web Crypto, or a dedicated library, perhaps in ct-wasm (once that becomes a thing), for any cryptography.

If you're doing something very specific, and you know what you're doing, then it's sometimes possible to avoid these issues, but I think in those cases it's up to the developer to justify why constant-timing is not required in that particular case. So I would leave the text as-is - also purely because it's useful information (the fact that the implementations are not constant-time, and the nod to cryptography for context).

**Comment by DNiebel** [comment]
I know that there are many pitfalls in cryptography and in particular to RSA and that may to some extent include not-constant-time implementations. But this is not a significant enough aspect to warrant the original text. I happen to have implemented an RSA-based Crypto-system back in the 1990s with PGP. And I am aware that key generation is a time-consuming process.

One may be able to obscure a poor implementation behind constant-time and so generate a false sense of security. I am convinced that constant-time can at best only partially obscure vulnerabilities in a cryptographical application. I would therefore think that the original text is misleading and would prefer my suggestion to be used, maybe with the following addendum:

"A general word of caution applies: to make a cryptographical application secure and not just obscure requires deep knowledge and great care."

**Comment by twiss** [comment]
Constant-timeness is not something that is used to hide vulnerabilities, rather, the absence of constant-timeness is something that itself can cause vulnerabilities. It is not always a matter of being careful, in some cases it is just impossible to make things secure in the absence of constant-time operations. See [this article](https://www.bearssl.org/constanttime.html), for example. So IMO, the current text is warranted.

**Comment by DNiebel** [comment]
I have studied [the article](https://www.bearssl.org/constanttime.html) you are referring to. In the first few paragraphs the author sets out the circumstances where an attack based on timings can be practical. But he also states that he is not aware of any real case where such timing attacks have been carried out, let alone led to a cryptographic system being compromised. Given 

> the state of the security of many systems is such that typical attackers have easier, faster ways in

What the author says certainly does not support the claim made in the current text and I would still maintain that my suggestion should be used.

**Comment by twiss** [comment]
> But he also states that he is not aware of any real case where such timing attacks have been carried out

Cryptographers usually don't like to sit around and wait so long until fixing a security issue. The [paper](https://crypto.stanford.edu/~dabo/abstracts/ssl-timing.html) that the article links to presents evidence that the attacks are feasible, that should be enough. At the risk of sounding facetious, could you find me a single cryptographer that believes the opposite claim, i.e. that "non-constant-time BigInts are suitable for use in cryptography"?

**Comment by DNiebel** [comment]
There is, perhaps, a way out, acceptable to both sides, of the impasse that has arisen by qualifying the original claim something like this:

> The operations supported on BigInt values are not constant-time. JavaScript BigInts are therefore [poorly suited to Cyptographic network server implementations](https://www.bearssl.org/constanttime.html).

**Comment by twiss** [comment]
While the linked paper focuses on timing attacks across a network, local timing attacks are _easier_, not harder. I could go and dig up more papers but again, not to be rude, but I have already presented a fair amount of evidence, so please do so yourself, and/or please present some evidence for your side of the debate :)

**Comment by DNiebel** [comment]
As an example, _BigInts_ within embedded JavaScript in html pages could be used in the hashing of client-side passwords:
- Client:      Password -> hash1 -> hash1+Salt(Date) -> hash2
- Network: Transmit hash2+Salt
- Server:     hash1+Salt -> hash2?

I have studied some further relevant pages on the web and now think that it would be more helpful for readers of the usage recommendations to see something like this under the Cryptography heading:
> The operations supported on BigInt values are not constant-time. Cryptography based on JavaScript BigInts would, in certain contexts, therefore be open to [timing attacks](https://en.wikipedia.org/wiki/Timing_attack).

**Comment by sideshowbarker** [comment]
I’m going ahead and closng this — Based on the information in the comments in this issue, it seems appropriate for MDN to be warning developers about avoiding the use of BigInt values in cryptography.

People who have expertise with using BigInt values in cryptography and who want to go ahead and use BigInt values in cryptography anyway can choose to ignore the warning.

But the target readers are people who have expertise with using BigInt values in cryptography — instead the target audience is developers who are looking for guidance on how to develop content using the web platform. And for that reason it’s appropriate for us to err on the side of caution — to help developers looking to MDN for guidance avoid possible footguns.

But the fact this issue is closed doesn’t prevent further discussion from taking place here in comments. If more discussion does take place, and it leads to new information that warrants re-considering this, then the issue could be revisited.

**Comment by DNiebel** [comment]
I completely understand what the target audience is and I would include myself in the target audience. On the whole, I am very impressed with MDN and the quality of its documentation. 

This claim in my view, however, sticks out like a sore thumb in that it is phrased in a patronising manner and the linked article presents a poor example of a footgun. I am grateful for the experience gained from the discussion.

Please consider the following:
> The operations supported on BigInt values are not constant-time, thus open to [timing attacks](https://en.wikipedia.org/wiki/Timing_attack).  JavaScript BigInts are therefore not well-suited for use in Cryptography.

**Comment by sideshowbarker** [comment]
> Please consider the following:
> 
> > The operations supported on BigInt values are not constant-time, thus open to [timing attacks](https://en.wikipedia.org/wiki/Timing_attack).  JavaScript BigInts are therefore not well-suited for use in Cryptography.

That looks acceptable to me, so I’ve opened https://github.com/mdn/content/pull/6107 for making that proposed change.

**Comment by DNiebel** [comment]
Thanks a lot.

**Comment by sideshowbarker** [comment]
@DNiebel Thank you — I learned a lot personally from this discussion, and we ended up with a change to MDN that seems to be a good improvement (for the reasons you outlined in https://github.com/mdn/content/issues/6006#issuecomment-863948687) over what MDN had previously.
