### ISSUE TITLE
Examples on Cookie page not working, throwing console errors.

### ISSUE THREAD

**Issue by its4zahoor** [mdn/content#628]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie

Details: 
- Example # 1 : Clicking the "Show cookie value" button shows an alert, but it is either an empty string or not visible on dark background
- Example # 2 : Clicking the "Show cookie value" button doesn't do anything and a console error is seen.

![image](https://user-images.githubusercontent.com/24554084/103093250-8e46d480-461b-11eb-81e6-d08578fe1f52.png)

**Comment by zahoor-rafay** [comment]
## Update: 
On my local clone, it works as expected thus I was unable to find and fix the issue.

**Comment by chrisdavidmills** [comment]
These examples are no longer working because of new browser security policies around samesite behavior. To prove this, you can right-click on the examples, select to open the iframe in a new tab, and then try them there — they work fine.

A quick way to fix this would be to transfer these examples over to GitHub and just link to them, rather than having them embeded in the page.

The longer but better fix would be to update the headers the content is served with to allow for the embedding.

**Comment by wbamberg** [comment]
Looks like this was fixed by https://github.com/mdn/content/pull/5031 .
