### ISSUE TITLE
Issue with "HTML attribute reference": (several pages can't be found)

### ISSUE THREAD

**Issue by ConsciousClay** [mdn/content#6316]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes

#### What information was incorrect, unhelpful, or incomplete?
Several attributes have broken links

#### Specific section or headline?
Attribute list

#### What did you expect to see?
Working links

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/attributes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/attributes/index.html
* Last commit: https://github.com/mdn/content/commit/eeeb5f684eb86fcba8acb5f38ada6329e5a445a2
* Document last modified: 2021-06-07T13:17:59.000Z

</details>

**Comment by sideshowbarker** [comment]
I think this might be a duplicate.

@mdn/core-dev would it be possible to special-case this article with some magic that un-hyperlinks the the attribute names that don’t have their own articles? I mean, could Yari just automatically make them into plain text?

**Comment by teoli2003** [comment]
Another possibility is to change the link on this page by:
- Removing the link on the first column if there is no HTML/Attributes/xyz page   (I'm not convinced that these pages are useful, except for global attributes, but that's another discussion)
- Make the link to the elements, in the second column, a deeplink to the attribute (#attr-xyz)

**Comment by FarazzShaikh** [comment]
I investigated and found that Yari is adding the class `page-not-created` to the links to make them Red and to show the special cursor.

One option is to set the [`pointer-events`](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events) CSS attribute to `none`. This is a simple change within [this SCSS file](https://github.com/mdn/yari/blob/f26e3b32e9d1a0b35496fddc0753f6004b897f94/client/src/document/index.scss). will make the link "un-clickable" but will also not let the user highlight or copy the text.

If we'd like to preserve pointer events then we can change Kumascript here:

https://github.com/mdn/yari/blob/e627600ec9ea8e21884bc67e3fb44398a81dc160/kumascript/src/api/web.js#L166

to create a `<p>` tag instead of an `<a>` tag.

@sideshowbarker I can open an issue and a PR in Yari about this depending on your suggestion. Do you maintain Yari as well>

**Comment by sideshowbarker** [comment]
@FarazzShaikh @mdn/core-dev are the maintainers of Yari. So I guess let’s wait for them to weigh on the question of issue vs PR.

**Comment by rachelandrew** [comment]
Tracked in https://github.com/mdn/content/issues/1712 this is frequently raised.

**Comment by FarazzShaikh** [comment]
As I understand it, #1712 is about adding pages that are missing. The changes I described would prevent 404s by not letting the reader click on them. 

As the articles are added, the links that exist will automatically become clickable and active.  

Correct me if I’m wrong 😓

**Comment by peterbe** [comment]
It was a deliberate design to only highlight links that *will* 404. @hamishwillee Do you remember the logic choices we made there?
There was a whole discussion with @wbamberg and @schalkneethling about the accessibility concerns of having links that aren't links and how changing it from `<a href="WILL FAIL">TEXT</a>` to `<a class="page-not-created">TEXT</a>` was a bad idea because it's no longer a link. 

Another thing that came out of that was https://github.com/mdn/yari/pull/3966 but in the midst of making that it was decided that no changes can be made that have a UX effect so someone would need to triage that for approval and inclusion in the next quarterly goal planning.

**Comment by hamishwillee** [comment]
With respect to why they are links and not plain text, I **think** the main reason came down to ARIA. We want the links to still behave as links for someone using a screen reader. The best way to do that was to keep them as links. As @peterbe says, we'd quite like that 404 to provide helpful information for readers. 

FWIW I am happy with the current behaviour. Why would making these unclickable would be better? NO, don't answer here, create a discussion for that.

**Comment by hamishwillee** [comment]
With respect to this actual issue, I think we're heading off track. This issue reports a bunch of missing pages. Yes there are - there are thousands of missing links in the docs. Unless we're prepared to take an issue for every single one of those and track them to completion then we should just close this. I don't think we are. I think what will happen is that someone will address those as part of some HTML refresh project. Until then this is clutter.

**Comment by rachelandrew** [comment]
I think we close this as we have a tracker for adding these if anyone wants to add them, in #1712

**Comment by FarazzShaikh** [comment]
That makes sense. Can close

**Comment by teoli2003** [comment]
Closing per [comment](https://github.com/mdn/content/issues/6316#issuecomment-882396593)
