### ISSUE TITLE
Issue with "notifications.create()": buttons not supported in FF but not indicated on the page

### ISSUE THREAD

**Issue by opto** [mdn/content#6350]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/notifications/create

#### What information was incorrect, unhelpful, or incomplete?

error console: Error: Type error for parameter options (Property "buttons" is unsupported by Firefox) for notifications.create

I just saw that the notificationOptions page tells no for FF, still, it feels a bit strange to give an example on a MDN page that is not working in FF, without a notice.
We are not on an explicit docu page of chrome - so it would be friendly to advice of restrictions in FF.

(in TB 78.11)

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/notifications/create`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/notifications/create
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/notifications/create/index.html
* Last commit: https://github.com/mdn/content/commit/eb5d682cbe5664b933e793ff6434fb252686f3c3
* Document last modified: 2021-05-31T17:26:19.000Z

</details>

**Comment by sideshowbarker** [comment]
Since the example is in fact in a Mozilla/Add-ons/WebExtensions article, it does seem kind for the example to use features that aren’t actually supported in Firefox.

And to be clear, what’s not supported in Firefox is the `buttons` member of https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/notifications/NotificationOptions.

So I guess whoever works on this would want to replace that example with one that works as expected in Firefox.

**Comment by Rob--W** [comment]
Let's resolve this by simplifying the example, to remove the use of `onButtonClicked` and `buttons`. Neither are supported in Firefox.

`notifications.onClicked` is supported.
