### ISSUE TITLE
Issue with "console", how does number formatting work? Number formatting doesn't work on Chrome.

### ISSUE THREAD

**Issue by stevenr4** [mdn/content#6614]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Console

#### What information was incorrect, unhelpful, or incomplete?
The section "Using string substitutions" mentions that %i and %d allow number formatting, and gives a single example, but this example does not fully explain how this is used. In addition to that, in my testing, it appears that Chrome ignores the formatting and prints out the number with %i, %d, and %f.

#### Specific section or headline?
Under "Using string substitutions" and under "Browser Compatibility"

#### What did you expect to see?
I expected to see either a description, or a link to a page with a description, on how one may use the number formatting. It isn't quite straightforward from what is written here. In addition to this, I expected to see Browser Compatibility make some mention that the formatting is ignored on Chrome.

#### Did you test this? If so, how?
I tested out number formatting, and (at least on chrome) the logging (log, info, warn, and error) appears to ignore number formatting. The "Browser Compatibility" section has no mention of this substitution string formatting issue.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/console`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Console
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/console/index.html
* Last commit: https://github.com/mdn/content/commit/cbca1200cf311812cd61fab50a4d0ff67f759fd1
* Document last modified: 2021-06-28T01:25:18.000Z

</details>

**Comment by zacnomore** [comment]
IMO, the styling section should be split out to detail usage and compatibility more thoroughly. It seems to be based on C++'s `printf` formatting specifiers but that's not mentioned here and the instructions are, I feel, unclear on how to use them.

I believe this is the basis for format specifiers: 
`%[flags][width][.precision][length]specifier `
https://www.cplusplus.com/reference/cstdio/printf/



> The properties usable along with the %c syntax are as follows (at least, in Firefox — they may differ in other browsers):

It would be fantastic if we could learn here what is cross-compatible, even just a basic list of known working style properties and options.

**Comment by himanshugarg** [comment]
@zacnomore by cross-compatible, do you mean across C++ and Firefox? I ask because the substitutions are not supported on other browsers according to the bcd table.

**Comment by zacnomore** [comment]
I mean between the browsers, I was under the impression that these were expected to be supported in others. 

I found chrome to support all but the `%f` option
![image](https://user-images.githubusercontent.com/5839548/133609097-acfd9fa8-a879-443c-8570-c5c8f57c6ea8.png)
![image](https://user-images.githubusercontent.com/5839548/133609638-4d610ff6-c9f3-4af6-a644-575ec982c8b7.png)


I was able to test the `%i` integer formatting in safari and found that to be working as well.

**Comment by wbamberg** [comment]
I agree that we should improve this page especially wrt cross-browser compatibility. I think a big part of the problem is that different browsers implemented different features here and the specification came later and doesn't cover a lot of them. Also this page started out very Firefox-centric and still is to a large extent.

>  in my testing, it appears that Chrome ignores the formatting and prints out the number with %i, %d, and %f.

Yes, I see this too.

```
console.log("Foo %.4d", 1)

Foo 0001 // Firefox
Foo 1    // Chrome
Foo 1   // Safari
```

```
console.log("Foo %.4f", 1.1)

Foo 1.1000 // Firefox
Foo 1.1    // Chrome
Foo 1.1000 // Safari
```

We should indicate this in the BCD for the page. Also number formatting appears to be nonstandard: https://console.spec.whatwg.org/#formatter .

>  It seems to be based on C++'s printf formatting specifiers but that's not mentioned here and the instructions are, I feel, unclear on how to use them.
>
> I believe this is the basis for format specifiers:
>
> %[flags][width][.precision][length]specifier
> https://www.cplusplus.com/reference/cstdio/printf/

It looks like it's just the `precision` part of that, isn't it? So the `printf` equivalent of the examples above is:

```
printf ("Foo %.4d\n", 1);
printf ("Foo %.4f\n", 1.1);
```

> It would be fantastic if we could learn here what is cross-compatible, even just a basic list of known working style properties and options.

Mainly that Chrome doesn't support precision at all, and Safari only supports it for floats.

> I ask because the substitutions are not supported on other browsers according to the bcd table.

Can you point me to where that is? The BCD table for `console` is very confusing because it squashes together all the methods, so you get "Substitution strings" appearing multiple times, with no real indication that a given occurrence is attached to the previous row. But I don't see anything about number formatting here.

**Comment by BridgeAR** [comment]
The [whatwg console spec](https://console.spec.whatwg.org/#formatter) does not contain any part about precision.
It should IMO therefore not be documented / included in the docs. The expected behavior should be to not understand precision.
Browsers can of course deviate from it and that could be documented as a note that some browsers even implemented more than the spec or behave differently.
