### ISSUE TITLE
[webAPI] Visual Viewport API

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#6713]
## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [ ] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

- Enable the Visual Viewport API on desktop

## Related Gecko bugs

- [Enable the Visual Viewport API on desktop](https://bugzilla.mozilla.org/show_bug.cgi?id=1551302). Looks like this has been documented, but checking would be a good, plus draft being removed - also bcd.

**Comment by hamishwillee** [comment]
In summary this feature was enabled in FF63 behind the pref `dom.visualviewport.enabled`. In FF68 it was fully enabled for android, and this update enables it for FF91 desktop (actually all platforms). It looks like it is pretty well documented on scan:
- https://developer.mozilla.org/en-US/docs/Web/API/Visual_Viewport_API
- https://developer.mozilla.org/en-US/docs/Web/API/VisualViewport
- all the sub pages.

The obvious changes required are
- needs to be removed from experimental pages
- BCD update
- Release note
- Remove draft heading from https://developer.mozilla.org/en-US/docs/Web/API/Visual_Viewport_API
- Remove "experimental" from all the other pages.
- Probably needs a quick review of spec vs docs to make sure there were no late changes.

@rachelandrew You self assigned, but since that was a while ago and you look pretty busy I'm going to at least start the BCD. Let me know if you want to do the rest or me to, or whatever.
