### ISSUE TITLE
[JS] Document Object.hasOwn

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#6717]
## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

- Document Object.hasOwn

## Related Gecko bugs

- [Implement the Object.hasOwn proposal](https://bugzilla.mozilla.org/show_bug.cgi?id=1711872). From what I can tell this is Object.hasOwnProperty which is documented - but worth a thorough check.

**Comment by hamishwillee** [comment]
Review
- This is not [Object.prototype.hasOwnProperty()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty) (which is hence inherited, as `Object.hasOwnProperty()`). It is a convenient mechanism that does the same thing but which further cannot be screwed up 
in the same way as that method in a variety of ways. These ways are discussed in https://github.com/tc39/proposal-accessible-object-hasownproperty and in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty
- Not in BCD - hasOwnProperty is present
- Does not appear to be in MDN

**Comment by jamiebuilds** [comment]
For some more detail:

- This method is slightly different from `hasOwnProperty`, it validates its inputs in order, where `hasOwnProperty` checks the property first
- `hasOwnProperty` is unreliable because you can't call it directly on objects like `Object.create(null)` so people end up calling `Object.prototype.hasOwnProperty.call(object, property)`
- `hasOwn`'s main goal is to provide the same functionality without the developer having to learn about prototypes, `.call()`, etc

Happy to answer any questions, I'm the author of the proposal

**Comment by hamishwillee** [comment]
Hi @jamiebuilds, Thanks very much. Your [spec](https://github.com/tc39/proposal-accessible-object-hasownproperty#implementations) explains this well. I hope to start creating a page for this next week and would love your review when it is done.

**Comment by Rumyra** [comment]
Thanks both! Apologies my first pass of the bug wasn't interpreted correctly 🤷🏻‍♀️

**Comment by hamishwillee** [comment]
FYI, this will ship in FF92. This is not clear from the bug report - hopefully this can be [made more obvious in future](https://bugzilla.mozilla.org/show_bug.cgi?id=1721149).

I will continue the docs for the feature as it is now since it is fresh in my mind. But updates to BCD and a new release note will be required for FF92.

**Comment by Rumyra** [comment]
Just FYI @hamishwillee you can add to experimental feature release notes and still update BCD with whatever pref is needed for this feature (I've assumed there is one)

**Comment by codehag** [comment]
@Rumyra There is no pref, it was just enabled on nightly as a lightweight way of testing. This is detailed in the [intent to prototype](https://groups.google.com/a/mozilla.org/g/firefox-dev/c/UjVKYf8Fnao/m/tFfKb4VbAgAJ) -- if there are any questions, let me know. Here is an example of what that looks like in BCD: https://github.com/mdn/browser-compat-data/blob/63abc6a05f55d923348f5cfe7d6ce39dfd824382/api/PaymentDetailsUpdate.json#L19

**Comment by hamishwillee** [comment]
@Rumyra So I updated BCD in line with suggestion ^^^ - let's see what BCD guys say. I had planned NOT to add a release note because this is only in nightly. That is still my plan. If you think we need it let me know - otherwise I think we add it in the shipping build - probably 92.

**Comment by hamishwillee** [comment]
All the work done on this now. Just needs some PRs merged.
