### ISSUE TITLE
[webAPI] window.clientinformation as window.navigator

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#6721]
## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

- Implement window.clientInformation as an alias of window.navigator

## Related Gecko bugs

- [Implement window.clientInformation as an alias of window.navigator](https://bugzilla.mozilla.org/show_bug.cgi?id=1717072). Seems to be something Chrome & Safari have and we now have - might need a bit of research to define what is needed docs wise

**Comment by hamishwillee** [comment]
FF91 adds `window.clientInformation` is an alias of `Window.navigator` (it has a pref, but this is set true by default, so not "guarded"). 

This was previously in Chrome  (and others using same engine) and Safari, at least as far back as Feb 2017. However it wasn't added into the spec until around June 2021 and was added as a "legacy alias". In other words, we're adding for compatibility because it is used too much to remove (just as the spec did), but we don't particularly want people to use this.

- [ ] BCD - Query how to mark this up in BCD: https://github.com/mdn/browser-compat-data/pull/11690
- [ ] Docs - https://github.com/mdn/content/pull/7180
- [ ] dev-doc-complete
