### ISSUE TITLE
Issue with "Functions": Person example under Arrow functions intended be Person class instead of Person function?

### ISSUE THREAD

**Issue by ajstoneham** [mdn/content#6816]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions

#### What information was incorrect, unhelpful, or incomplete?
Under Arrow Functions sections, there is an example given with Person()
should Person be a function or a class?

#### Specific section or headline?
/docs/Web/JavaScript/Guide/Functions#no_separate_this

#### What did you expect to see?
class instead of function for Person

#### Did you test this? If so, how?
No I did not test, I am pretty sure it works both as a function and a class, but it seems to be written as if Person were a object

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/guide/functions`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/functions/index.html
* Last commit: https://github.com/mdn/content/commit/3fbd2466d85fe7bf14ac849ff897f9684f8e426c
* Document last modified: 2021-07-08T07:17:50.000Z

</details>

**Comment by ajstoneham** [comment]
If it should be class, I do not mind to fork and make a pr with the change, just was not sure.

**Comment by sideshowbarker** [comment]
The `Person` in that code example definitely should not be a class. If it were changed to being a class, that’d alter the entire point of the example.

Since in JavaScript objects don’t need to be defined by a class but instead can be instantiated based on prototype inheritance, what the example is showing is an object whose constructor is named `Person()` —  and calling the `Person()` constructor instantiates an `Object` with an `age` property (whose value automatically increases each second by 1).

So there are classes at all involved here, and the example as currently written is completely correct.

Given that, I’m going ahead and closing this issue — but you still comment further, and if there’s something I’ve misunderstood and you have information that warrants re-opening this, then it can still be revisited.

**Comment by ajstoneham** [comment]
understood, thankyou.

**Comment by ajstoneham** [comment]
I guess in my mind, I see a function as doing something and a class instance as being something.... so when there is a function person, I naturally assumed an instance of person vs doing person.  No worries, thanks for clarifying.

**Comment by ajstoneham** [comment]
Awesome content by the way, super helpful stuff.

**Comment by sideshowbarker** [comment]
> I guess in my mind, I see a function as doing something and a class instance as being something.... so when there is a function person, I naturally assumed an instance of person vs doing person. No worries, thanks for clarifying.

Yeah, I guess JavaScript is exceptional in this regard, in that it’s classless by default — and so runs counter to expectations if we come to it from having worked with class-based languages. To me at least, having come to JavaScript from other such languages, there a lot of idiosyncrasies in JavaScript that give me pause. I guess to somebody who’s instead come to programming by way of learning JavaScript, it all seems natural.
