### ISSUE TITLE
Content suggestion: Why not use React?

### ISSUE THREAD

**Issue by Coder-Manthan** [mdn/content#6907]
## What is the new suggestion?
I think that MDN Web Docs uses HTML, CSS and JS for Front-End instead can't MDN Web Docs use React.

## Why is it important or useful?
`1. How many pages are likely to be needed? -> There are so many pages in MDN Web Docs and all of them will be needed to convert to React`
`2. How much time do you think this work should take? A few hours? A week? A month?
-> It could take an month or 6 months based on participation`
`3.Does it address critical needs in the web industry?
-> Not really but React is very much used in web industry`
`4.Is the work an operational necessity, i.e. is not having it a security risk?
-> I was just thinking about it and it is not necessary to switch`
`5.Does the content help make the web more ethical?
-> Yes, React is very secure`

## Other supporting information

[React Website](https://reactjs.org/)
[React Docs](https://reactjs.org/docs/getting-started.html)

**Comment by sideshowbarker** [comment]
This scope of this issue tracker is limited to the actual content of MDN articles, and that doesn’t include proposals for changes to the software system which serves the content. So I’m going ahead and closing this because this isn’t an actionable issue for this tracker.

You might be interested in taking a look at https://hacks.mozilla.org/2020/10/mdn-web-docs-evolves-lowdown-on-the-upcoming-new-platform/ to get some details about the MDN frontend architecture and its design choices.
