### ISSUE TITLE
Issue with "Basics of HTTP": duplicative with root HTTP page

### ISSUE THREAD

**Issue by mnot** [mdn/content#6955]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP

#### What information was incorrect, unhelpful, or incomplete?

This page duplicates a lot of the links in https://developer.mozilla.org/en-US/docs/Web/HTTP -- can its content be consolidated there? happy to do a PR.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/basics_of_http`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/basics_of_http/index.html
* Last commit: https://github.com/mdn/content/commit/4062cfb18880e12a6f892d794114c9c2f062a290
* Document last modified: 2021-04-19T04:01:15.000Z

</details>

**Comment by teoli2003** [comment]
Hi, @mnot.

We plan to update/extend the whole HTTP area in the next two months (writing a bit about HTTP/2 & HTTP/3 so that web devs can have a grasp of it). The first action will be to list actions and the updated structure. This will definitively be in it, but I propose that we have an agreed structure before starting writing PRs. But any comment/problems are already (and always) more than welcome.
