### ISSUE TITLE
Issue with "What software do I need to build a website?": Page is very outdated

### ISSUE THREAD

**Issue by underdoggum** [mdn/content#7048]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_software_do_I_need

#### What information was incorrect, unhelpful, or incomplete?
 - Link for "modern.ie" gives "Warning: Potential Security Risk Ahead" on Firefox
 - Link for "browsershots.org" gives deprecated website (not updated since 2015 maybe?). Using their feature gives "500 -Internal Server Error"

#### Specific section or headline?
"Dig Deeper": "Browsing Websites"

#### What did you expect to see?
working links

#### Did you test this? If so, how?
by using it

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/common_questions/what_software_do_i_need`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_software_do_I_need
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/common_questions/what_software_do_i_need/index.html
* Last commit: https://github.com/mdn/content/commit/75c1271189903b4d96433a34a8174175dd089ef2
* Document last modified: 2021-04-28T14:08:28.000Z

</details>

**Comment by rachelandrew** [comment]
That page definitely looks like it could do with a rewrite! Thanks for raising the issue.

**Comment by NegiAkash890** [comment]
Hi @rachelandrew . Can I help here. Please let me know where should I start ?

**Comment by sideshowbarker** [comment]
We should consider deleting the entire https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_software_do_I_need page all and internal links to it. It’s basically always going to be out of date — and even if updates are made to it, will still continue to get further and further out of date after that.

**Comment by hamishwillee** [comment]
@sideshowbarker Where would you stop? A few links further on in in common questions there is  https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Available_text_editors 

That was a bit devils advocate. I wouldn't delete the page - I think it is worth identifying that you need a text editor or IDE, browser etc.
But  it is not the place of MDN to provide lists of anything that you can get a more up to date listing of using a web search. At most we should suggest something like VS Code for the IDE with some disclaimer that it is a popular cross platform alternative, but there are many, many more.

Thoughts?

**Comment by sideshowbarker** [comment]
> @sideshowbarker Where would you stop?

Well if it were up to me, I wouldn’t stop — there’s a whole lot more stuff that I’d yank.

In general with some issues that we get in, my point of view when I go and take a look at the page that’s being reported on is: I have zero interest in trying to maintain the content of this page, and I can’t personally justify spending any time at all on it. And when I feel like that, I also feel like I shouldn’t expect anybody else to have to spend time on it — and thus, I feel like we’d be better off without anybody getting stuck with having to continue to maintain the page.

To frame it in other terms, there are opportunity costs to everything we have to spend time on. And when somebody has to spend time on what seems to me at least like a relatively low-value part of the site, that’s time that gets taken away from working on updates to other more-valuable parts of the site — and/or time that gets taken away from working on a resolution to any of the several hundred other open issues we have.

With the Learn tree in particular, there are some parts of it that are relatively more valuable and then there are some parts which at best are a “nice to have” but otherwise are not a necessary part of the overall goal/scope we have of documenting the web platform’s feature set.

And this particular page seems like a “nice to have” — but one for which the continued costs of maintaining it outweigh its potential benefits to readers.

**Comment by hamishwillee** [comment]
@sideshowbarker Nothing I can argue with there, but even agreeing the chunks to delete feels like more effort than it is worth. I could fix this specific case by cutting it back to bare bones.

**Comment by Josh-Cena** [comment]
We talked about this issue in the writers meeting and the outcome is https://github.com/openwebdocs/project/issues/207
