### ISSUE TITLE
Issue with "Common MIME types": Missing Media Type for Python .py

### ISSUE THREAD

**Issue by mrkprdo** [mdn/content#7107]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types

#### What information was incorrect, unhelpful, or incomplete?
missing media type for python files (.py)

#### What did you expect to see?
Should we have standard common media types cross platform

#### Did you test this? If so, how?
Mac uses text/x-python-script
Windows uses text/x-python
Built an app that uploads python files

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/basics_of_http/mime_types/common_types`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/basics_of_http/mime_types/common_types/index.html
* Last commit: https://github.com/mdn/content/commit/13963ff487e978879d1ba95fb09495ed9c6c47bb
* Document last modified: 2021-05-21T03:41:06.000Z

</details>

**Comment by sideshowbarker** [comment]
There is no standard media type for Python files in https://www.iana.org/assignments/media-types/media-types.xhtml.

And I can’t otherwise find any authoritative reference anywhere which states what media type to use for Python files.

And https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types also lacks media-type info for may other programming-language source files — for example, `.pl`, `.rb`, `.h`, `.c`. `.cc`, `.rs`, `.go`, `.cs`, and on and on — it’s not just `.py` that didn’t get included there.

And I don’t think anybody would consider it necessary to try to exhaustively list in MDN all the media types for the source files for all the most-common programming languages.

And so it’s not clear what value there’d be in trying to add a media type for just `.py` to the https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types list, and not for all other common programming languages too.

Given all that, I don’t think we should try to anything for this to the https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types list.

**Comment by mrkprdo** [comment]
Thanks for the input. Yeah, you are right it, [this]( https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types) has nothing to do with missing media types.

Since there is no standard at the moment, platforms can use each of their own versions of media type. *sigh

**Comment by sideshowbarker** [comment]
> Since there is no standard at the moment, platforms can use each of their own versions of media type. *sigh

Yeah, I’m a bit surprised that there’s no standard media type registered for it. I can’t see why the Python maintainers wouldn’t have registered it long ago. But maybe there’s something I’m misunderstanding about what the value would be in having a standard media type for it…

**Comment by Ryuno-Ki** [comment]
If you want me to I can ask, since I have some ties into the Python community.
