### ISSUE TITLE
Issue with "MediaDevices": (short summary here please)

### ISSUE THREAD

**Issue by nicolasguasca1** [mdn/content#7125]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices

#### What information was incorrect, unhelpful, or incomplete?
The example used in this page throws an exception avoiding the written exceptions expected when an error occurs.

#### Specific section or headline?

I get the following on the console: Uncaught (in promise) TypeError: Cannot read property 'innerHTML' of null
    at errorMsg

#### What did you expect to see?

The set of error defined from the catch:

```
if (error.name === "ConstraintNotSatisfiedError") {
          errorMsg(
            "The resolution " +
              constraints.video.width.exact +
              "x" +
              constraints.video.height.exact +
              " px is not supported by your device."
          );
        } else if (error.name === "PermissionDeniedError") {
          errorMsg(
            "Permissions have not been granted to use your camera and " +
              "microphone, you need to allow the page access to your devices in " +
              "order for the demo to work."
          );
        }
        errorMsg("getUserMedia error: " + error.name, error);
      });
```

#### Did you test this? If so, how?

I tried to run a different message with an else in the case the error the catch was looking was not found but the exception persists. I understand it has to do with the innerHTML not being defined. What I don't understand is why is it -null-...

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/mediadevices`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/mediadevices/index.html
* Last commit: https://github.com/mdn/content/commit/51a70c224f882429168119989ea19ac3aeb60a02
* Document last modified: 2021-06-14T11:27:10.000Z

</details>

**Comment by sideshowbarker** [comment]
Can you describe exactly how you ran that code? For example, did you put it into the devtools console and run it?

If so — if you ran it that way — then the error described in the question is exactly what would be expected to happen.

I say that because the thing is, the code has the following assignments:

```js
var video = document.querySelector('video');
var errorElement = document.querySelector('#errorMsg');
```

…so it’s expecting to be run within a document that has a `video` element and some element with an `id=errorMsg` attribute.

But the example doesn’t include such a document — so that `video` variable ends up being null, and that `errorElement` variable ends up being null.

And so when the code later does `errorElement.innerHTML += '<p>' + msg + '</p>'` that causes the browser to throw, because `errorElement` is null, and so has no `innerHTML` property.

**Comment by nicolasguasca1** [comment]
Hey! Thanks for the reply! I indeed forgot to mention that I created an HTML document with the code suggested in MDN as <script> . I was missing a <div> to display with the #errorMsg attribute as you mentioned. Here is what I am getting now: 

DOMException: Permission denied

I assume the other errors (ConstraintNotSatisfiedError, PermissionDeniedError) were not reached by the browser.

**Comment by sideshowbarker** [comment]
The code in the MDN article works as expected as far as I can see. To get further help with troubleshooting how to get it to run in your local environment, a site like Stack Overflow is probably a better place to ask.
