### ISSUE TITLE
Content bug: Whatever happened to Web/HTML/Using_the_application_cache

### ISSUE THREAD

**Issue by peterbe** [mdn/content#7158]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache is now 404ing. 

## What is the problem?

This is the PR that deleted it https://github.com/mdn/content/pull/4016 (by @SphinxKnight )
Then I think there was an attempt to archive it here: https://github.com/mdn/archived-content/pull/12 but it got closed. 

I know it's and old technique but perhaps [people are still interested to read it](https://github.com/mdn/yari/issues/4011#issuecomment-884616315). 

Also, there a lot of links to it still that are now all broken:

```
files/en-us/web/security/secure_contexts/features_restricted_to_secure_contexts/index.html:1
files/en-us/web/html/element/html/manifest/index.html:1
files/en-us/web/html/element/html/index.html:1
files/en-us/web/api/sharedworkerglobalscope/index.html:1
files/en-us/web/api/sharedworkerglobalscope/applicationcache/index.html:1
files/en-us/web/api/window/applicationcache/index.html:1
files/en-us/web/api/storage_api/index.html:1
files/en-us/web/api/indexeddb_api/browser_storage_limits_and_eviction_criteria/index.html:1
files/en-us/web/api/service_worker_api/using_service_workers/index.html:1
files/en-us/web/http/headers/clear-site-data/index.html:1
files/en-us/mozilla/firefox/releases/84/index.html:1
files/en-us/mozilla/firefox/releases/3/index.html:1
files/en-us/mozilla/firefox/releases/44/index.html:1
files/en-us/mozilla/firefox/releases/3.5/index.html:1
```

## What did you expect to see?

Either have it back but mentioned as a very deprecated technique. Or perhaps a redirect it in the mdn/archived-content repo.

**Comment by peterbe** [comment]
Example: 
<img width="1159" alt="Screen Shot 2021-07-22 at 10 11 17 AM" src="https://user-images.githubusercontent.com/26739/126653591-582028e0-3b8f-4d6d-b130-738f48a80359.png">

**Comment by ZeddYu** [comment]
I don't think it is a good choice to delete the page straightforward. Perhaps we could use a directory dedicated to these deprecated pages.

**Comment by peterbe** [comment]
> I don't think it is a good choice to delete the page straightforward. Perhaps we could use a directory dedicated to these deprecated pages.

I agree. I think it was a mistake and everyone most likely agrees that we should avoid 404s as much as we can.

**Comment by hamishwillee** [comment]
It is at the point of "deletion" - it went through a long deprecation process and is now not supported by any current browser. The right way to clean this up is to delete the references.

Of course this is a bit messy when attributes that are used by the feature have not been cleaned up. In this case perhaps they should be.

**Comment by ZeddYu** [comment]
> It is at the point of "deletion" - it went through a long deprecation process and is now not supported by any current browser. The right way to clean this up is to delete the references.
> 
> Of course this is a bit messy when attributes that are used by the feature have not been cleaned up. In this case perhaps they should be.

No. I don't think so. Althouth AppCache is deprecated, Chrome still supports this feature at this moment. At least on Chrome v92.0.4515.107 for Mac (x86_64) it still works.

Is it necessary to delete it? I think the answer is no. In my opinion, keeping these deprecated pages in the internet history is a better choice. This can give people a better understanding of the history of web development and how web develops.

**Comment by hamishwillee** [comment]
@ZeddYu Fair enough. I misremembered it had having been deleted as "not used anywhere".  But in  [FF84 when this was removed from firefox](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/84) I linked to that doc. 

Upshot, sorry, yes, I agree. This should be added back, possibly archived. On the other hand, let's see if @SphinxKnight has a justification.

**Comment by SphinxKnight** [comment]
Well, my first intent was to archive it and not simply delete it. I had filed https://github.com/mdn/archived-content/pull/12 as a tandem with https://github.com/mdn/content/pull/4016

I still think it would be best archived if possible but if it's not possible, I don't have a strong opinion again reviving those (quite the contrary after the discussion here).

**Comment by peterbe** [comment]
What's potentially confusing and problematic is the notion of "archived" has changed meaning over time. In the Wiki it meant it got a striking orange/red background to alert the reader that you're reading legacy documentation. 
In the Yari era, "archived" means "it's going to be deleted in a matter of time".
And now, as of mid-July 2021, the concept of "archived" is gone. At least in the sense that it's not longer published and hosted by developer.mozilla.org. 

I still think it makes sense, if someone has the time and energy, to take a snapshot of the doc, right before deleting it from mdn/content and put it into mdn/archived-content. Just because it's easier to browse that way than to have to go though the `git rm` history logs of git.

**Comment by ZeddYu** [comment]
> What's potentially confusing and problematic is the notion of "archived" has changed meaning over time. In the Wiki it meant it got a striking orange/red background to alert the reader that you're reading legacy documentation.
> In the Yari era, "archived" means "it's going to be deleted in a matter of time".
> And now, as of mid-July 2021, the concept of "archived" is gone. At least in the sense that it's not longer published and hosted by developer.mozilla.org.
> 
> I still think it makes sense, if someone has the time and energy, to take a snapshot of the doc, right before deleting it from mdn/content and put it into mdn/archived-content. Just because it's easier to browse that way than to have to go though the `git rm` history logs of git.

I couldn't agree more

**Comment by hamishwillee** [comment]
@peterbe Can you point me to the place where it was discussed what archived now means? I've clearly missed a discussion.

Specifically, I thought that stuff got moved to archived and the archived was built but never maintained.

**Comment by peterbe** [comment]
> @peterbe Can you point me to the place where it was discussed what archived now means? I've clearly missed a discussion.
> 
> Specifically, I thought that stuff got moved to archived and the archived was built but never maintained.

There is no one particular specific place. It's much too big and spread as a topic. @Rumyra will blog about it. 

Originally, the Kuma wiki had the concept of "archived" content. It was content that automatically got a striped red/orange border around it. Content that content leads basically didn't want in MDN. When we switched to Yari we decided to dump the wiki documents into 3 repos: mdn/content, mdn/translated-content, and mdn/archived-content. 
The plan was to build the mdn/archived-content once or twice but not bother with PRs and to set a date when we can stop hosting it altogether. I did most of the tech for this but it was Chris who drove the energy of getting rid of it.

**Comment by hamishwillee** [comment]
Thanks, I saw much of the conversation - just missed the bit around "stop hosting it altogether". Links to archive really need to be better highlighted so that they can be tidied up before this removal happens.

**Comment by sideshowbarker** [comment]
Let me provide a dissenting opinion here. Application Cache is bad. Very bad. Nobody should be using it, and we should not be doing anything to help people use it. It is no longer part of the HTML spec, and has not been for a relatively long time now. It may seem that we are somehow doing developers a service by keeping the docs for it around, but in fact by doing so, we are doing a disservice to developers.

Among the reasons for not retaining docs for Application Cache is that it simply does not work in the way that anyone would expect. And it has *never* worked. It was fundamentally flawed design from the very beginning. The only thing it could ever be useful for was toy applications. Anyone using it for real-world applications in production is doing harm to their users.

Given that, any documentation about Application Cache in MDN or elsewhere has always been a fiction — because in practice it could never be made to work in the way developers expected to (except maybe for the most trivial use cases — but, seriously, not even well for those cases).

In the community of implementors and specification authors, there is universal agreement that we need to expunge Application Cache. We otherwise risk having developers write new code using it. And the problem with that is, any browser engine that still ships Application Cache is at liberty to completely remove their Application Cache support at any time, with no new warnings. There have been clear warnings to developers everywhere, literally for years. There has for many years been a vastly superior mechanism — Service Worker — for doing anything that Application Cache was ever specified to try to do.

It is actively harmful to the developer community to continue keeping documentation about Application Cache in MDN.

With respect, the proper course of action for dealing with all the broken links is to expunge them — not to restore the docs for Application Cache.

I don’t mean to offend anyone who has a different opinion about this, but an opinion that we should keep documentation for Application Cache very much runs counter to the prevailing agreement in the wider developer community. Let’s please not make the mistake of restoring the docs for Application Cache. Those docs are already now right where they properly belong — in obscurity.

**Comment by ZeddYu** [comment]
Of course. Nobody should use it again. But I want to learn something about the AppCache. It is also the history of the service worker.

Assume that when someone uses service worker related documentation, perhaps he is also interested in appcache since it is the predecessor of the service worker. But when they try to look for docs of appcache, he finds that all of it has disappeared. Even there is no archived contents. It is really wired, isn't it? It feels like the Internet is missing a piece of untold history and he doesn't know why.

Let the "archived" be the "archived" as the wiki says.
> In the Wiki it meant it got a striking orange/red background to alert the reader that you're reading legacy documentation.

**Comment by hamishwillee** [comment]
I lean towards @sideshowbarker point of view. It is not the job of MDN to provide a history lesson. 

I don't object to having the archive exist, but IMO it should be completely separate and no links to it should exist from MDN. Mostly because while these links exist they will never be properly cleaned up. If you need that archive, it might be worth taking a snapshot via the wayback machine.

**Comment by ZeddYu** [comment]
Up to you guys.

I'm just stating the fact that I happened to need to review AppCache related content and found it didn't work as usual. Only renders for like a second and then the page goes blank for me. Then it turn out that it is something wrong with the web cache. The page has also been removed after the issue was fixed.

**Comment by peterbe** [comment]
> Of course. Nobody should use it again. But I want to learn something about the AppCache. It is also the history of the service worker.
> 
> Assume that when someone uses service worker related documentation, perhaps he is also interested in appcache since it is the predecessor of the service worker. But when they try to look for docs of appcache, he finds that all of it has disappeared. Even there is no archived contents. It is really wired, isn't it? It feels like the Internet is missing a piece of untold history and he doesn't know why.
> 
> Let the "archived" be the "archived" as the wiki says.
> 
> > In the Wiki it meant it got a striking orange/red background to alert the reader that you're reading legacy documentation.

We totally understand what you mean. It's not an argument. But do you have any cool ideas about how we could keep displaying legacy web APIs in a fashion that makes it absolutely clear to anybody that they should NOT be using it. 
A couple of years ago, we used to have this red/orange border around the content. 

You can see it here: https://web.archive.org/web/20191006030927/https://developer.mozilla.org/en-US/docs/Archive/Mozilla/XUL
Screenshot too:
<img width="1474" alt="Screen Shot 2021-07-27 at 11 01 01 AM" src="https://user-images.githubusercontent.com/26739/127177878-629a2f8b-63ba-4bfd-b8ae-e10c98470d11.png">

It was an OK solution but not great. In particular, it lacked a loud verbal explanation. If you'd stumble into that page from a harmless google search, how are you supposed to know what that red/orange border means?

Adjacent to that, what do you think about the red notecard on a page like this: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blink
It's decently loud to catch your attention. But what if you're linked down away from the notecard. For example, [to an anchor within the page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blink#css_polyfill). Then the reader might miss the warning. 

It's basically a matter of UX and how humans might perceive it. 
Deleting the "bad content" is definitely a good idea too as @sideshowbarker pointed out above. But perhaps there are other areas similar to this where MDN can improve. ...all for the benefit of not wasting time for web devs learning.

**Comment by Ryuno-Ki** [comment]
FWIW, I recall, that the proposed course was to keep the page, clear the content and put a text in it, that this technology should no longer be used.
Deleting it altogether is news to me (but I'm looking at 1,5k unread notifications for mdn/content, so likely missed something).

**Comment by hamishwillee** [comment]
So is the summary of this "that page is gone and is not coming back"? If so, "someone" should go through and clean up the links.

@peterbe with respect to best way to make it clear that a page is deprecated, as you say that is a UX thing. Perhaps escalate to @HerminaC since she can put that into the "product issues to resolve" pile?

FWIW  I've seen several solutions to this - e.g. floating page status indicator icons. Personally I like the whole page to have a red tinge, but I'm aware that red is not always culturally considered a warning indicator. I'm not so concerned that people don't get text telling them that the page is archived/deprecated or whatever - if you also add an archived banner, they will work it out pretty quick.

**Comment by peterbe** [comment]
> So is the summary of this "that page is gone and is not coming back"? If so, "someone" should go through and clean up the links.

Yep. It's not coming back so we should avoid linking to it. 

> that is a UX thing. 

I think you should escalate it to @Rumyra who is trying to collate all the contribution workflow feature requests from the content folks to the dev folks. Once she has it all triaged, she'll try to figure out someone to help work on it.
