### ISSUE TITLE
Issue with "<datalist>: The HTML Data List element": No arrow and list is not available unless double click

### ISSUE THREAD

**Issue by seckincann** [mdn/content#7159]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist

#### What information was incorrect, unhelpful, or incomplete?
When you hover there is no arrow like other browsers. When you click nothing happens, you need to double click to see list elements.

#### What did you expect to see?
There should be an arrow when mouse hover. List should be shown when single clicked.
![image](https://user-images.githubusercontent.com/19951293/126665209-fd9164d4-0205-4839-b647-d4ac9e7b91cc.png)
![image](https://user-images.githubusercontent.com/19951293/126665273-50227792-bb36-4f56-a001-670193fcd03c.png)

#### Did you test this? If so, how?
Try with the official sample: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/datalist`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/datalist/index.html
* Last commit: https://github.com/mdn/content/commit/8d28de329fc4f723ad4362f0f703e46c4fa9e32d
* Document last modified: 2021-06-02T17:52:41.000Z

</details>

**Comment by sideshowbarker** [comment]
The https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist article doesn’t attempt to describe requirements for how the datalist information is presented. There certainly is not any requirement to do anything on hover, and showing the list on double-click is a perfectly acceptable way to display the datalist.

So I’m going ahead and closing this, since there’s nothing in the MDN article that needs changing.
