### ISSUE TITLE
Question with "Assertions": Is it guaranteed safe to use lookbehind expressions with variable length?

### ISSUE THREAD

**Issue by GhbSmwc** [mdn/content#7210]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Assertions

#### What information was incorrect, unhelpful, or incomplete?
Not sure if lookbehind with variable length is safe to use, some regex engines like the one notepad++ is using doesn't even work at all and uses `\K` instead.

I read this article here: https://stackoverflow.com/questions/11640447/variable-length-lookbehind-assertion-alternatives-for-regular-expressions

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/guide/regular_expressions/assertions`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Assertions
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/regular_expressions/assertions/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by sideshowbarker** [comment]
The article isn’t attempting to document regex behavior in general, or to concern itself with any limitations in support for regex features in non-JavaScript tools.

Instead the article is documenting behavior that JavaScript engines are required to implement in order to conform to the ECMAScript spec.

So I’m going ahead and closing this, because there’s no change needed to make the article align with the requirements in the ECMAScript spec.
