### ISSUE TITLE
Issue with "Lexical grammar": yield is not a reserverd keyword in not strict mode

### ISSUE THREAD

**Issue by Austaras** [mdn/content#7225]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar

#### Specific section or headline?
Keywords > Reserved keywords as of ECMAScript 2015

#### What did you expect to see?
`yield` is not listed in reserverd keyword

#### Did you test this? If so, how?
```js
function yield() {}
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/lexical_grammar`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/lexical_grammar/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by sideshowbarker** [comment]
`yield` is in fact defined by the ES spec as a reserved word:

https://tc39.es/ecma262/multipage/ecmascript-language-lexical-grammar.html#prod-ReservedWord
> * _ReservedWord_ :: one of
>   `await break case catch class const continue debugger default delete do else enum export extends false finally for function if import in instanceof new null return super switch this throw true try typeof var void while with yield`

See https://tc39.es/ecma262/multipage/ecmascript-language-lexical-grammar.html#sec-keywords-and-reserved-words:

> This specification uses a combination of grammatical productions and <emu-xref href="#early-error" id="_ref_4556"><a href="error-handling-and-language-extensions.html#early-error">early error</a></emu-xref> rules to specify which names are valid identifiers and which are reserved words. All tokens in the <emu-nt id="_ref_14362"><a href="ecmascript-language-lexical-grammar.html#prod-ReservedWord">ReservedWord</a></emu-nt> list below, except for <code>await</code> and <code>yield</code>, are unconditionally reserved. Exceptions for <code>await</code> and <code>yield</code> are specified in <emu-xref href="#sec-identifiers" id="_ref_366"><a href="ecmascript-language-expressions.html#sec-identifiers">13.1</a></emu-xref>, using parameterized syntactic productions.

So, being defined as a reserved word does not prevent `yield` from also being used as an identifier (a variable name or function name). That’s because at https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#sec-identifiers the ES spec special-cases both `yield` and `await`.

So we still need to keep `yield` in the list of reserved words in MDN.

That said, if you’d be willing to write up a pull request with a change which adds text explaining the being a reserved word doesn’t prevent `yield` from being used as an identifier, I think such a change would be a good addition to the docs.
