### ISSUE TITLE
Issue with "Date and time formats used in HTML": in datetimepickker time not working on safari 

### ISSUE THREAD

**Issue by bhautiksavaj007** [mdn/content#7379]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Date_and_time_formats

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/date_and_time_formats`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Date_and_time_formats
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/date_and_time_formats/index.html
* Last commit: https://github.com/mdn/content/commit/8d642a73750cb3ace88c4f92b6676dd627912f8a
* Document last modified: 2021-06-08T12:54:28.000Z

</details>

**Comment by sideshowbarker** [comment]
Since the https://developer.mozilla.org/en-US/docs/Web/HTML/Date_and_time_formats article itself doesn’t mention anything about a datetime picker, there’s nothing actionable for this issue, so I’m going ahead and closing it.

And in general the mdn/content repo is not the best place to raise issues about browser compatibility — instead the recommended place is https://github.com/mdn/browser-compat-data
