### ISSUE TITLE
Issue with "Writing WebSocket client applications": (dead link)

### ISSUE THREAD

**Issue by nss-ysasaki** [mdn/content#7412]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_client_applications

#### What information was incorrect, unhelpful, or incomplete?
A link labeled "try out the example for yourself" (in the second Note section from the top) is dead.

#### Specific section or headline?
See above.

#### What did you expect to see?
Probably https://webrtc-from-chat.glitch.me/. Linked as "WebSocket chat" example in [another MDN page](https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Signaling_and_video_calling).

#### Did you test this? If so, how?
Uh, no, maybe?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/websockets_api/writing_websocket_client_applications`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_client_applications
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/websockets_api/writing_websocket_client_applications/index.html
* Last commit: https://github.com/mdn/content/commit/ba4a07195d8f8f4941e7ae06118b8405f9cac9cf
* Document last modified: 2021-04-10T23:58:36.000Z

</details>

**Comment by meowmeowmeowcat** [comment]
Thanks! I've opened PR #7413 for this.

**Comment by meowmeowmeowcat** [comment]
@wbamberg Is it possible for us to put the sample code on Glitch?

**Comment by wbamberg** [comment]
Hey @meowmeowmeowcat !

There's a rather sad discussion about this in https://github.com/mdn/content/discussions/5772. I'd be happy to hear more good ideas for a way forward. I would have liked to have made more progress on this but just haven't had time.

Yes, Glitch is a possibility, and is mentioned in the discussion. I think there are a few questions that would need to be answered:

* is Glitch the best option for this?
* should we have an MDN org account rather than random user accounts? (yes)
* should we pay for a full account? (yes)

In general I'm in favour of doing something relatively quick and easy here (rather. than, say, building our own solution again) even if it's not ideal.

**Comment by meowmeowmeowcat** [comment]
Hi @wbamberg ! 

I think the best way to solve this problem is to remove the link directly (or mark it as "broken") , until we have our own solution again.
