### ISSUE TITLE
Question on Tag omission for <p> tags

### ISSUE THREAD

**Issue by tannerdolby** [mdn/content#7420]
On https://developer.mozilla.org/en-US/docs/Web/HTML/Element/p 

It states in the "Tag omission" section:

<img width="796" alt="Screen Shot 2021-07-25 at 3 42 30 PM" src="https://user-images.githubusercontent.com/48612525/126915661-5421f5ac-ae56-40da-8d51-10097cd1243e.png">

Since `<p>` elements can only have permitted content of [phrasing content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#phrasing_content), why are non-phrasing content elements mentioned as the "next" element within Tag omission? Shouldn't paragraph elements only having phrasing content and not flow content like `<nav>` or other content types? 

cc @schalkneethling

**Comment by sideshowbarker** [comment]
That tag-omission language is taken straight from the HTML spec. So if you have suggestions about how that language could be improved to avoid possible confusion, the best place to raise an issue would be at https://github.com/whatwg/html/issues/new.

But anyway, I’ll go and try to respond a bit here about it.

> Since `<p>` elements can only have permitted content of [phrasing content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#phrasing_content), why are non-phrasing content elements mentioned as the "next" element within Tag omission? Shouldn't paragraph elements only having phrasing content and not flow content like `<nav>` or other content types?

Notice that language is about the *end* tag — so it’s not talking about what elements are within the `p` element but instead what elements *follow* the `p` element.

So I’m going ahead and closing the issue here. If some change is eventually made to the HTML for this, then we could update MDN to reflect that change.

**Comment by tannerdolby** [comment]
> Notice that language is about the end tag — so it’s not talking about what elements are within the p element but instead what elements follow the p element.

Yeah I guess it would be more clear to say the "adjacent" or sibling element so people (myself) included know its the next "sibling" element and don't assume the options can be a nested element as they aren't permitted content. The current language is OK, just my thoughts. Thanks for the response @sideshowbarker !

**Comment by Ryuno-Ki** [comment]
Heads up, a text node is not an element, but will likely also count to „phrasing content”.

**Comment by tannerdolby** [comment]
> Heads up, a text node is not an element, but will likely also count to „phrasing content”.

Agreed, a text node is considered "phrasing content", which is the permitted content for `<p>` tags.
