### ISSUE TITLE
Rhino Documentation is missing.

### ISSUE THREAD

**Issue by theweezar** [mdn/content#7444]
![image](https://user-images.githubusercontent.com/38401606/127613115-544bf988-8e00-4aa3-81be-04fc6162a7e1.png)

**Comment by sideshowbarker** [comment]
Did you find a link to https://developer.mozilla.org/en-us/Mozilla/Projects/Rhino/Documentation at some other site?

MDN itself no longer has any link to the article — the article was intentionally removed quite some time ago.

So there’s nothing that can be fixed here as far as MDN itself goes — there’s no plan to restore that page.

The only thing that should be fixed is, if there are other sites which are linking to that old URL, I guess it should be reported to that site so that they can remove the old link.

**Comment by teoli2003** [comment]
This is at least linked from there: https://github.com/mozilla/rhino

cc/ @Rumyra that surely can help in getting these updated.

**Comment by Rumyra** [comment]
I'll look into updating that readme to remove mdn links 👍 thanks both!

**Comment by Rumyra** [comment]
Closing this issue in favour of one raised on the rhino repository https://github.com/mozilla/rhino/issues/1009

If there are any other links to these docs that are missed, let me know, can always re-open 👍
