### ISSUE TITLE
Broken links and missing anchors

### ISSUE THREAD

**Issue by hamishwillee** [mdn/content#753]
Lists of broken link/anchor issues can be found here:
- https://gist.github.com/hamishwillee/f455ac42da19cb005482f23a78fe1c12 ([htmltest](https://github.com/wjdp/htmltest) output - links, anchors, etc.)
- https://gist.github.com/hamishwillee/4305d00308333e6407929b019f796521 ([BLC output](https://matthewsetter.com/writing-tools/npm-broken-link-checker/) - 404 links only)

Spot check shows that some, possibly all, of these are correct. There are a lot. We should look at whether some of these can be addressed by the toolchain.

**Comment by chrisdavidmills** [comment]
@peterbe just an FYI; not really expecting an immediate solution to this, but just highlighting thius in case it is useful.

**Comment by peterbe** [comment]
I'm not sure what the "question" is here but we have a flaw checker that checks the pathname and the anchors. We don't yet have a solution for checking external links. 

One thing that irks me about the fixable flaws is that it's weird to do massive PRs that span lots and lots of files. The PR review burden is just too weird. "Here. Please check these 89 files". And doing one page at a time with fixable flaws is also a bit distracting. 

We need to dig ourselves out of that. Perhaps we set aside the time to do some massive fixable flaw fixes in large trees, without review, and once we've cleaned almost all of them up, we can thinking about it something that you do only when you're in the business of working on a particular page. 

Which reminds me, I still want to enable flaw checking in PRs. I.e. If there's a flaw in the pages you touched, you better go back to and fix it. The reason we can't do that at the moment is because how we pick which flaws to check is too naive and the chances are too big that you might get blamed for a flaw you didn't even introduce yourself. 

CC'ing @escattone for his feelings too.

**Comment by nschonni** [comment]
Came across https://github.com/mdn/yari/issues/653 when looking for something else

**Comment by hamishwillee** [comment]
As Chris says above, this is not a question. This is a list of known broken external links (i.e. content we could try fix). Of course I'd rather wait until you have https://github.com/mdn/yari/issues/653 in place, because a flaw checker will make finding/fixing these in pages easier.

**Comment by Rumyra** [comment]
How relevant is this bug now we have the flaw checker @hamishwillee ? I think a list of all broken links could be useful...

**Comment by hamishwillee** [comment]
@Rumyra As we're not going to have a project to look at the links and fix them, then this issue is not helpful. So I'll close it.

The TLDR is ....

The flaw checker catches broken internal links and highlights http links that should be https. It highlights but does not check external links. So we're improving the quality of our internal but not external links over time. 

If we like this incremental fix strategy then we should add external link checks to the flaw checker. I think there is a stalled link bug to get that in somewhere.
