### ISSUE TITLE
Issue with "Bounce off the walls": (Not loading the code example/iframe at bottom)

### ISSUE THREAD

**Issue by SquidQid** [mdn/content#7571]
![iframerror](https://user-images.githubusercontent.com/58965884/128121361-ef9d33a5-54a2-4010-be10-4838f4678fb2.PNG)
MDN URL: https://developer.mozilla.org/en-US/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript/Bounce_off_the_walls

#### What information was incorrect, unhelpful, or incomplete?
Not loading the code example/iframe at bottom of page due to security error it seems. Thanks!
Forgive me if this has been addressed already. I could not find an open issue but I am new.

#### Did you test this? If so, how? Yes. Multiple browsers. 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/games/tutorials/2d_breakout_game_pure_javascript/bounce_off_the_walls`
* MDN URL: https://developer.mozilla.org/en-US/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript/Bounce_off_the_walls
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/games/tutorials/2d_breakout_game_pure_javascript/bounce_off_the_walls/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by NegiAkash890** [comment]
Thanks! Working on this .

**Comment by NegiAkash890** [comment]
Currently :

![image](https://user-images.githubusercontent.com/55234838/128453581-771da7ff-b569-44ef-a2af-ca3ac258149b.png)

Now ( After Editing ) : 

![image](https://user-images.githubusercontent.com/55234838/128453474-bfed58d5-7173-4c26-9b60-3265bbabf908.png)


Hi @sideshowbarker , I used the inspector and the problem is probably because of the `iframe` .Doubles quotes are missing at the end of the `url` of `iframe` . I am not able to find how should I fix this issue or do we have any specific repo from where these `iframe` are being used.

This is the line that needs to be fixed and it uses `JSFiddleEmbed` and I have no idea how should or where this resource is ?

https://github.com/mdn/content/blob/6ff2f916e4caac210219bd314e5f4e38ce8cc2bd/files/en-us/games/tutorials/2d_breakout_game_pure_javascript/bounce_off_the_walls/index.html#L98

**Comment by sideshowbarker** [comment]
> This is the line that needs to be fixed and it uses `JSFiddleEmbed` and I have no idea how should or where this resource is ?
> 
> https://github.com/mdn/content/blob/6ff2f916e4caac210219bd314e5f4e38ce8cc2bd/files/en-us/games/tutorials/2d_breakout_game_pure_javascript/bounce_off_the_walls/index.html#L98

See https://github.com/mdn/yari/pull/4428 — the sources for all the macros used in MDN articles live in files in https://github.com/mdn/yari/tree/main/kumascript/macros with the same file basename as the macro name. So the source for the `JSFiddleEmbed` macro is at https://github.com/mdn/yari/blob/main/kumascript/macros/JSFiddleEmbed.ejs.

And for local testing, the place where copies of the macros get put in your local environment is in the `node_modules/@mdn/yari/kumascript/macros/` subdirectory. So if you change your local copy of the `JSFiddleEmbed.ejs` there, your local Yari will pick up that change.
