### ISSUE TITLE
Issue with "Window.orientation": Is it really Deprecated?

### ISSUE THREAD

**Issue by masammut** [mdn/content#7624]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/orientation

#### What information was incorrect, unhelpful, or incomplete?

Feature is marked as "Deprecated" but no such reference could be found in the linked Specification: https://compat.spec.whatwg.org/#dfn-window-orientation-angle

This issue is to confirm if this feature is actually deprecated and either:
- provide a link to the Specification detailing the deprecation, or
- remove the "Deprecated" state

Same for: https://developer.mozilla.org/en-US/docs/Web/API/Window/orientationchange_event

#### Specific section or headline?

The "Deprecated" state is displayed at the following locations:
 - top section (underneath title), 
 - browser compatibility row, and
 - underneath the browser compatibility table

#### What did you expect to see?

Either the Deprecated state removed or a link to the Specification showing the "Deprecated" state.

#### Did you test this? If so, how?

No.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/window/orientation`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/orientation
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/orientation/index.html
* Last commit: https://github.com/mdn/content/commit/efe8c7a74cd437cfcfc84213d467bfb6726c5ab4
* Document last modified: 2021-08-03T18:08:46.000Z

</details>

**Comment by hamishwillee** [comment]
It is almost certainly deprecated 
- the compatibility data testing is fairly rigorous and that data matches the page.
- there are now alternatives like the screen and device orientation APIs
- This only works on mobile OS.

Further, we don't necessarily state in docs why things are deprecated (though I wish we did, as an audit trail would often be useful)

Note also that the meaning of deprecated on MDN does not necessarily imply "not in spec" or "on the path for removal from spec". Sometimes it is a recommendation that the API not be used for other reasons. 

@foolip I can't find a canonical statement in BCD as to why this was deprecated. Do you happen to know, or know who would know?

**Comment by sideshowbarker** [comment]
See the discussion at https://matrixlogs.bakkot.com/WHATWG/2021-08-05#L36 (miketayl_r there is the editor of the Compat spec)

The nature of the Compat spec is that pretty much everything in the entire spec should be considered discouraged/deprecated. If that *weren’t* the case, the features defined there would instead be defined in some other spec.

To put it in other terms, the features in the Compat spec are there mainly for implementors — the purpose being to document behavior for features that fall into the category *“Here is stuff that some browsers over time ended up adding support for but that we don’t think merit being properly defined in the specifications where they otherwise normally would/should be defined.”*

**Comment by hamishwillee** [comment]
Thanks, I will close this then.
