### ISSUE TITLE
Issue with "Django Tutorial Part 6: Generic list and detail vi…": Link to code doesnt exist

### ISSUE THREAD

**Issue by terry45** [mdn/content#7633]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Generic_views

I want to check the challenges for writing the views for Author detail. The github link doesnt provide the code, only screenshots of the tutorial

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/django/generic_views`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Generic_views
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/django/generic_views/index.html
* Last commit: https://github.com/mdn/content/commit/16f66c643c9aa67a7839925d261f8c2775f0305b
* Document last modified: 2021-05-14T07:57:34.000Z

</details>

**Comment by hamishwillee** [comment]
You can check them from the link provided in the very first topic about the local library https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Tutorial_local_library_website#i'm_stuck_where_can_i_get_the_source

This won't necessarily "exactly" match the challenge, because the tutorial gets extended at various points. However it should be close. 

Feel free to add a PR to link to the relevant views/code in this specific document IF they are the same. 

Closing as "solved" :-)
