### ISSUE TITLE
Content bug: ariaDescription specification table, incorrectly titled 

### ISSUE THREAD

**Issue by gwyneplaine** [mdn/content#7651]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/API/Element/ariaDescription

## Specific page section or heading?

Specification table

## What is the problem?

Specification table links out to ARIA 1.3, but the link text is 'Accessible Rich Internet Applications (WAI-ARIA) 1.2 (WAI-ARIA 1.2)' 

There's no mention of `aria-description` attribute in the WAI ARIA 1.2 spec, I believe this is a 1.3 inclusion.

## What did you expect to see?

a) The specification table should read 
> Accessible Rich Internet Applications (WAI-ARIA) 1.3 (WAI-ARIA 1.3)

b) or is completely dropped as per https://github.com/mdn/content/pull/2720 

After a cursory review of the README and the repo, it wasn't immediately clear to me how to submit a fix for expected result a. Happy to create a PR for expected result b (or a if someone can clarify how to do this) 

Thank you very much for your time 🙏

**Comment by dontcallmedom** [comment]
thanks for reporting this issue @gwyneplaine! I don't think the spec information should be dropped (your (b) above); and thanks for offering to provide a fix - unfortunately, fixing the bug isn't entirely straightforward since this has dependencies to automated data collection processes used to maintain information on specifications.

tagging @Elchi3 since this relates to the integration of spec information into MDN content - I'm guessing we would need to display a version-less title of the spec to avoid this issue (since in practice we're not tracking the data on a versioned basis); [browser-specs](https://github.com/w3c/browser-specs/blob/main/index.json) doesn't expose such a title at the moment, but I think it could without too much trouble.

**Comment by Elchi3** [comment]
Yes, so BCD always uses the latest available specification as the spec_url which is often a version-less "nightly" in browser-specs. Having a title for these would be great. Currently, it just looks at any title that is there and so it finds the one for 1.2. I wonder when would browser-specs title this spec as 1.3? (why not now?)

**Comment by dontcallmedom** [comment]
by default, browser-specs takes the title from another spec database (specref), which relies on data published in w3.org/TR - since ARIA 1.3 hasn't reached that stage yet, browser-specs gets confused (which is probably worth discussing as well) - I'll raise issues in browser-specs on both aspects.

**Comment by estelle** [comment]
The specification has been updated and does link to the spec
