### ISSUE TITLE
Content bug: DOM standards

### ISSUE THREAD

**Issue by Nurou** [mdn/content#7684]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Introduction

## Specific page section or heading?

https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Introduction#what_is_the_dom

## What is the problem?

The article mentions two different DOM standards: W3C DOM and WHATWG DOM, and provides links for both. However, both links point to the same (WHATWG) standard. W3C DOM seems to have retired, so the information here needs an update?

## What did you expect to see?

N/A

## Did you test this? If so, how?

N/A

**Comment by teoli2003** [comment]
Yes, thank you for the report. I'll update this: I will rephrase the paragraph as things have changed (for the better) since it was written; I'll add a specification table at the end of the document. Nowadays, Web developers don't need to understand the arcane of concurrent specifications and browser-maker politics to use the DOMü
