### ISSUE TITLE
Issue with "How CSS works": (short summary here please)

### ISSUE THREAD

**Issue by laroDudley012** [mdn/content#7715]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/How_CSS_works

#### What information was incorrect, unhelpful, or incomplete?
"The updated output is as follows:"
There was no output
#### Specific section or headline?
Applying CSS to the DOM

#### What did you expect to see?
DOM with added <span>

#### Did you test this? If so, how?
Ran the HTML document.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/first_steps/how_css_works`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/How_CSS_works
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/first_steps/how_css_works/index.html
* Last commit: https://github.com/mdn/content/commit/5e74f6f95b2fb3481b76c26644e997ce181ee9b5
* Document last modified: 2021-07-23T09:54:18.000Z

</details>

**Comment by sideshowbarker** [comment]
To be clear: In the https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/How_CSS_works#applying_css_to_the_dom section, at the end, in the box that’s preceded by *“The updated output is as follows:”*, you don’t see any text reading *“Let's use: Cascading Style Sheets”*, like this:

<img width="427" alt="image" src="https://user-images.githubusercontent.com/194984/128666267-d5205ee1-5071-46ab-92e0-911d9bfe7354.png">

If so, what browser are you using?

Does the same problem happen if you try in a different browser?

What happens when you try in a incognito/private window?

What happens when you disable all extensions/add-ons and try?

**Comment by laroDudley012** [comment]
Add Blocker Ultimate was the culprit.

**Comment by teoli2003** [comment]
Thank yoo for coming back!

Closing this per your comment.

Feel free to reopen the issue if I have misunderstood you.
