### ISSUE TITLE
Issue with "break-inside": (add missing specs)

### ISSUE THREAD

**Issue by ConsciousClay** [mdn/content#7717]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/break-inside

#### What information was incorrect, unhelpful, or incomplete?
![image](https://user-images.githubusercontent.com/51193876/128646122-739b410d-5087-4378-88eb-0ed0b8901892.png)

#### Specific section or headline?
Specifications

#### What did you expect to see?
Aren't [these ](https://drafts.csswg.org/css-break-3/)the specs?

https://drafts.csswg.org/css-break-3/

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/break-inside`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/break-inside
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/break-inside/index.html
* Last commit: https://github.com/mdn/content/commit/bec20b2d3ce234c858d8e02b15c960bced8f0882
* Document last modified: 2021-07-03T23:18:48.000Z

</details>

**Comment by hamishwillee** [comment]
@rachelandrew This is happening because there is [no top level spec](https://github.com/mdn/browser-compat-data/blob/main/css/properties/break-inside.json) in `css.properties.break-inside`. There are however (duplicate) specs in `css.properties.break-inside.multicol_context` and `css.properties.break-inside.paged_context`. There is the same problem in `break-after` etc

I was going to just copy the earliest versions at the higher level for BCD along with the spec. But given the spec section just duplicates perhaps best to explicitly specify one of the section? e.g. `{{Specifications("css.properties.break-inside.multicol_context")}}`

**Comment by rachelandrew** [comment]
This is similar to the alignment keywords, as the fragmentation properties are supported in the context of other things. The fragmented contexts we currently have are pages and multicol (the other one is Regions, but we don't talk about Regions). The alignment properties also aren't showing spec data right now. https://developer.mozilla.org/en-US/docs/Web/CSS/align-self

In terms of the spec, there is a Fragmentation spec, which specifies how fragmentation works in all of the things.

However, our BCD data then has the support listed as it is in each of the different things that use fragmentation. If we change the browser-compat yaml to just one of the contexts, for example to `multicol_context` then we lose the information about support in paged media.

**Comment by hamishwillee** [comment]
Thank what's the solution? There is nothing to stop us explicitly listing both contexts - though I guess if more contexts are added we'd have to go back to the page. Might be better to do that for now rather than leave this empty?
