### ISSUE TITLE
[Dropped] [webAPI] Web Share update

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#7749]
**EDITED: Note, DROPPED from release**. 
**I'm still doing the work, but this is not delivering a release feature**

[Enable Web Share by default on Windows Nightly](https://bugzilla.mozilla.org/show_bug.cgi?id=1641280) This title is a bit misleading - seems windows doesn't support copy action potentially causing a never-resolved promise. See https://bugzilla.mozilla.org/show_bug.cgi?id=1641280#c2

## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [ ] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

- Check docs and possibly provide a note

## Related Gecko bugs

- [Enable Web Share by default on Windows Nightly](https://bugzilla.mozilla.org/show_bug.cgi?id=1641280)

**Comment by jpmedley** [comment]
Here are documents previously completed, listed for MDN staff review:

- [ ] https://developer.mozilla.org/en-US/docs/Web/API/Navigator (method additions)
- [ ] https://developer.mozilla.org/en-US/docs/Web/API/Navigator/canShare
- [ ] https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share

**Comment by hamishwillee** [comment]
Thanks @jpmedley for pointing those out. Nice to get a head start.

Status review:
- The docs are a little out of date with respect to the spec. They omit
   - requirement for the web-share permission (and that is not cross linked from the web-share doc).
   - a bunch of possible exceptions from the API
   - need for transient activation.
 - These could be improved with a live example.   
 - Sharing on FF appears to be protected behind pref `dom.webshare.enabled` (except from FF92, where it is enabled on Windows Nightly)
   - This pref is not document in [Experimental features](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features)
   - BCD indicates that it is partially supported on FF android. Does not mention the pref
 - navigator.canShare() is rubbish. Because it has so little implementation you have to test for its existence before you can check whether it can share. You might as well just try share and then catch the result.

As I understand previously the spec expected the share API to resolve a promise with information about successful share of the target. Because Windows can't provide this information, the spec was changed such that the promise resolves successfully with `undefined` at the point that the OS has been sent all the data (i.e. not necessarily actually shared). This change is now "standard"/in the spec so if you enable web sharing this is what you'll get on all platforms.

But, the bug fix itself really only impacts Nightly builds on Windows - for other builds the default for `dom.webshare.enabled` is still `false`. So there are no releases notes to follow, but there may be:
- Experimental pages updates
- BCD updates. 
- Docs updates.

**Comment by hamishwillee** [comment]
Tracking (incomplete)

- [ ] Docs: [Navigator.canShare()](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/canShare) - updates for web-share permission etc - https://github.com/mdn/content/pull/8255
- [ ] BCD [Navigator.canShare()](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/canShare#browser_compatibility)
   - This incorrect for the chromium variants - should match Chrome for desktop at least in Opera and Edge. Not sure about the other variants 
- [ ]  Docs: [Navigator.share()](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share) 
   - update for web share
   - add info on transient usage
   - better example - ideally a live example
- [ ] BCD: [Navigator.share()](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share#browser_compatibility)    
   - Update chromium variants
   - Update FF92 variant for windows nightly and info about pref `dom.webshare.enabled`
   - Not sure yet if should add web-share subfeature on the methods to indicate when that applies. Probably not.
 - [ ] Docs: [web-share](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/web-share) permission policy - add info linking to affected APIs canShare, share.
 - [ ] BCD [web-share](https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API#browser_compatibility) add permission as sub feature.
 - [ ] Doc: [Experimental features](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features) - add info on `dom.webshare.enabled`

**Comment by jpmedley** [comment]
Here's an article on the [receiving side (web share target)](https://web.dev/web-share-target/) of web sharing. I've opened a ticket to [make sure this is up to date](https://github.com/GoogleChrome/web.dev/issues/6037).

**Comment by Rumyra** [comment]
I'm tidying up the project & closing with the notion that BCD will happen 👍

**Comment by jpmedley** [comment]
Here's the open ticket: #8887

**Comment by hamishwillee** [comment]
> Here's the open ticket: #8887

@Rumyra FYI this is for the Share target API, which allows you to specify a web target that might be used by the Web Share API. It was out of scope for the Firefox updates since it isn't supported by Firefox. 

Joe has posted this so we can track it. It wouldn't fall to me normally as it isn't yet supported by FF and I do Web API stuff as overflow. However if you can't find bandwidth or someone to own it, you can drop it on me as a "todo when you have time".

**Comment by jpmedley** [comment]
I can do it.
