### ISSUE TITLE
Issue with "CSS pixel": It's completely irrelevant; also problem with “Device pixel”

### ISSUE THREAD

**Issue by fregante** [mdn/content#7806]
MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/CSS_pixel

#### What information was incorrect, unhelpful, or incomplete?

A pixel is a digital measurement; inches, arms, visibility have absolutely nothing to do with pixels.

#### Specific section or headline?

All of it.

#### What did you expect to see?

I don't know, what even is a "CSS" pixel? This should probably just be merged into the "Device pixel" entry and explain the difference between a physical pixel (the literal dot on the screen), the device pixel (what the GPU renders), and the logical pixel (what the OS choses to map the device pixel to). Maybe also add a note mentioning browser zoom as an additional pixel mapping/scaling mechanism.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/glossary/css_pixel`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/CSS_pixel
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/css_pixel/index.html
* Last commit: https://github.com/mdn/content/commit/0d4eedf8edfaf4354eca4cb85ca2d7e634d9467c
* Document last modified: 2021-03-16T11:53:05.000Z

</details>

**Comment by fregante** [comment]
The "Device pixel" article is also similarly wrong:

> This physical pixel is also called a "device pixel".

Example:
- 3200 physical pixels-wide display
- The GPU is set to paint a 2000 pixels-wide image
- The OS says that it's a 2x resolution, so as a developer I get "1000px @2x"
- The browser receives "1000px" as a default
- The user sets a 200% zoom, so the website sees 500px

1 CSS pixel has 4 values:

- 1 CSS pixel
- 2 OS pixels
- 4 GPU pixels
- 6.4 physical pixels

**Comment by hamishwillee** [comment]
The terms "CSS pixel", "Device Pixel" etc. have defined meanings in the domain. A CSS pixel is 1/96px inches (for historical reasons).  I completely agree this is confusing and irritating terminology, but as they are used in specs and as part of the vocabulary of the web they aren't going to change.

Upshot, you can't remove this. However if you would like to take a shot at creating a better set of documents that explains the relationships between the different units to map between CSS, device and image pixels, that would be excellent.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/7806#issuecomment-896357937

**Comment by fregante** [comment]
If you agree that it's an irritating terminology, why support it? MDN doesn't have to include every historical artifact from the spec, it can just *not* include it and talk about units and what they mean instead. This page should just not exist as it's not beneficial to anyone.

**Comment by fregante** [comment]
💙

**Comment by sideshowbarker** [comment]
Reopening this, because as noted in https://github.com/mdn/content/issues/7806#issuecomment-896230872, the “Device pixel” glossary entry also needs fixing.

**Comment by sideshowbarker** [comment]
About the “Device pixel” glossary entry: I spent some time trying to come up rewrite to replace the current incorrect one — but in the end came around to deciding it’s just not worth the effort.

So I opened https://github.com/mdn/content/pull/7836 with a change that just deletes the entry glossary entry.

And we’re not losing anything by deleting it, because as far as I could find, there are no current MDN articles which reference/link to that glossary entry. So it’s not clear how any current MDN reader would now normally ever come across that glossary entry anyway.

Along with that, there’s the fact that the CSS specs themselves don’t attempt to explicitly state anything about what a “device pixel” — despite the fact that there are multiple CSS specs which use that term. So those specs leave it up to the reader to understand what’s meant by that term. And if the CSS specs themselves don’t attempt to define the term, that suggests that at MDN also we maybe shouldn’t be trying to define it.

To paraphrase something that @fregante wrote in an earlier comment here: It’s not necessary for us to attempt to define in the MDN glossary every possible term related to the web platform. It’s fine (and arguably often better, in a case such as this one) to not try to include definitions for some terms.

**Comment by Ryuno-Ki** [comment]
> Along with that, there’s the fact that the CSS specs themselves don’t attempt to explicitly state anything about what a “device pixel” is — despite the fact that there are multiple CSS specs which use that term.

That would have let me to open an issue with a CSS WG to ask, whether it is a deliberate choice.

> So it’s not clear how any current MDN reader would now normally ever come across that glossary entry anyway.

Search.

I had some occasions, where I had to map px to pt in order to generate a PDF on the fly.

But I guess, it's too late by now.
