### ISSUE TITLE
Issue with "Inspecting server-sent events": Non-working feature

### ISSUE THREAD

**Issue by benfrancis** [mdn/content#7855]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/Inspecting_server-sent_events

#### What information was incorrect, unhelpful, or incomplete?

The feature this page describes doesn't appear to actually work (tested in Firefox 90.0.2).

See open bugs:
* https://bugzilla.mozilla.org/show_bug.cgi?id=1405706
* https://bugzilla.mozilla.org/show_bug.cgi?id=1236219

#### Specific section or headline?

Whole page.

#### What did you expect to see?

The feature working as described, e.g. using the test page https://delirious-adjustment.glitch.me/

#### Did you test this? If so, how?

Tested with https://delirious-adjustment.glitch.me/ and my own Server-Sent Events application which works as expected using curl and Chromium.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/network_monitor/inspecting_server-sent_events`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/Inspecting_server-sent_events
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/network_monitor/inspecting_server-sent_events/index.html
* Last commit: https://github.com/mdn/content/commit/0ea5ea66ca3ff5f0c02583c1f3606b3b7d4aee40
* Document last modified: 2021-02-02T16:28:31.000Z

</details>

**Comment by ddbeck** [comment]
Hi, I'm closing this issue because [Firefox DevTools User Docs](https://firefox-source-docs.mozilla.org/devtools-user/index.html#firefox-devtools-user-docs) have moved off of MDN (see https://github.com/mdn/content/pull/14140 for details on content moved). If this issue is still applicable to the relocated documentation, please see the Firefox Source Docs site for details on raising bugs and contributing. Thanks for your understanding!
