### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/content#787]
Can I use all the HTML that i want in all the .HTML files?

I'm not talking about the `pre` but the "document".

https://github.com/mdn/content/pull/734

**Comment by rachelandrew** [comment]
@mattiapontonio In general you should follow the existing conventions as that will assist in keeping pages consistent. I've edited an awful lot of pages and I rarely feel the need to get too inventive. However we are new to working completely in HTML on MDN, so there may be things that would be useful to add.

The folk reviewing PRs are very experienced with MDN, so if you feel there is some HTML that you need to use in order to represent something, I'd flag it up when making the pull request and get their opinion.

**Comment by mattiapontonio** [comment]
@rachelandrew thanks.

**Comment by mattiapontonio** [comment]
The fact is that in this case I am not starting from an editorial need, I start from a development need and I need content ... (and only content because what I expect is in this no workaround code).

**Comment by chrisdavidmills** [comment]
I second what Rachel is saying here, but I'd also like to add that changes we make to the HTML source should be simple, and not seek to add new structures of design features. Adding significant new HTML features:

1. Will make the content much harder to review
2. Will make the site inconsistent
3. Will break the site styling
4. Will make it much harder to move the content to markdown when we start to go down that route.

If there is a new HTML structure that you want to add on a page, you should start by filing a GitHub issue that explains what you want to add and why. What are the uses cases, why doesn't the existing markup choice suit your needs? Etc.

Closing this now.
