### ISSUE TITLE
Strange Code in Mozilla MDN's "Getting started with HTML" page

### ISSUE THREAD

**Issue by Lindana900** [mdn/content#7883]
I open the document at the url 

> https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Getting_started#active_learning_adding_attributes_to_an_element

At the paragraph before the "Whitespace in HTML" section, there is the Live Output with gray background as shown in the image below
![Getting started with HTML - Learn web development MDN-01](https://user-images.githubusercontent.com/88884929/129347175-dcacaa4b-fb5e-4216-aac7-d1c0c21a84c2.png)

When I click the "Show solution" button the content, instead of showing the html code, is change to the image below
![Getting started with HTML - Learn web development MDN-02](https://user-images.githubusercontent.com/88884929/129347359-471c3bb4-6205-44f0-9f81-5bd0c3f14829.png)

When I check to source using the View Source command the paragraph contain the **iframe** code with its src attribute point to the url:
`https://yari-demos.prod.mdn.mozit.cloud/en-US/docs/Learn/HTML/Introduction_to_HTML/Getting_started/_sample_.Playable_code3.html`

I copied the url to the new browser's tab and Go, the page show Live Output as shown in the first image.
I clicked the "Show solution" button and the page show the content in the second image.

Is this correct?

**Comment by sideshowbarker** [comment]
Thanks for reporting this. The cause of the problem you ran into is the height of the **Live output** iframe for this example is too small — so what happens is, that big image gets inserted before the **Editable code** area, and so the **Editable code** area then gets pushed down into part of the bottom part of the iframe and is only visible if you scroll the iframe contents down past image.

So I’ve opened #7884 with a fix that increases the height of the iframe so that the **Editable code**  area doesn’t disappear but instead remains visible without you needing to scroll the iframe contents to discover it.

**Comment by Lindana900** [comment]
You fix it so quick!

**Comment by sideshowbarker** [comment]
> You fix it so quick!

Well the fix hasn’t actually been merged yet :) But it should be merged soon. Thanks again very much for having taken time to report this!
