### ISSUE TITLE
Issue with "autofocus": missing spec and compatibility data

### ISSUE THREAD

**Issue by somebody1234** [mdn/content#7887]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus

#### What information was incorrect, unhelpful, or incomplete?
"Specifications" and "Browser compatibility" sections are both not found
The spec url is here, I believe? [HTML Standard (HTML) #the-autofocus-attribute](https://html.spec.whatwg.org/multipage/interaction.html#the-autofocus-attribute)
[caniuse](https://caniuse.com/autofocus) has browser compatibility data, however i'm not 100% sure it refers to generic autofocus and not `<input>`-specific autofocus?

#### Specific section or headline?
Specifications
Browser compatibility

#### What did you expect to see?
The mentioned sections with appropriate data

#### Did you test this? If so, how?
I guess? By going to the page?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/global_attributes/autofocus`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/global_attributes/autofocus/index.html
* Last commit: https://github.com/mdn/content/commit/f2d61c0bd78628f28b78344c11082c1e6605628f
* Document last modified: 2021-06-08T01:45:12.000Z

</details>

**Comment by AnilSeervi** [comment]
I've opened a PR in mdn/browser-compat-data#11997 to fix this issue

**Comment by teoli2003** [comment]
Thanks, @AnilSeervi for the PR, but it will not fix this issue.

The issue was already fixed by mdn/browser-compat-data#11680. What happens is that the fix was done 5 days ago only and there has not yet been a new version of the bcd package generated, then deployed on MDN. The fix will appear only when both these actions will have been done, likely near the end of the month. (There is a longer delay than the usual weekly release, as a new major release of bcd is being generated.)

I will close this issue, feel free to reopen it if the fix is not live by September 1st, 2021.
