### ISSUE TITLE
fetch() return type error?

### ISSUE THREAD

**Issue by GlennNZ** [mdn/content#7907]
On the docs page about [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch)
it says (with emphasis mine):

"The simplest use of fetch() takes one argument — the path to the resource you want to fetch — and **returns a promise containing the response** (a Response object)."

But given that a [Response.json()](https://developer.mozilla.org/en-US/docs/Web/API/Response) return a Promise, should this wording be 

"...and **returns a response containing the promise**" ?

The initial paragraph had be thinking fetch was returning a Promise object.

**Comment by sideshowbarker** [comment]
Thanks for raising this.

> The initial paragraph had be thinking fetch was returning a Promise object.

The `fetch()` method does in fact return a promise.

> But given that a [Response.json()](https://developer.mozilla.org/en-US/docs/Web/API/Response) return a Promise

It’s not an either/or — because both calls return a promise.

> should this wording be
> 
> "...and **returns a response containing the promise**" ?

That’d be wrong — because both the `fetch()` method and the `json()` method of the `Response` object return promises.

That’s why the example first uses `.then()` to resolve the promise returned by the `fetch()` call to get `response` (a `Response` object), next calls `json()` from that `response`, and finally uses another `.then()` to resolve the promise returned by that `json()` call, to ultimately get `data` (the JSON data).

All that said, I think the current wording for this in the “Using Fetch” article isn’t as clear and precise as it could be — for one thing, we usually don’t write about promises “containing” anything (because it’s not accurate), but instead write about what promises “resolve with”.

So I’ve opened #7910 with a fix that I think helps to make those paragraphs of the “Using Fetch” article more clear, and more precise.
