### ISSUE TITLE
page missing from migration Using_the_application_cache

### ISSUE THREAD

**Issue by bulk88** [mdn/content#8213]
## What page(s) did you find the problem on?

https://developer.kaiostech.com/docs/getting-started/main-concepts/caching

which uses older Gecko engines, still supports Application Cache and links to MDN at

https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache

## What is the problem?

Content used to exist, see

https://web.archive.org/web/20190306044822/https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache

## What did you expect to see?

The page that has been there for many years and is linked from many places online. MDN needs to cover ALL web technologies, not just the LATEST weekly release of the big 3, with no reference how to write PORTABLE, BACKWARDS COMPATIBLE, web sites, or debug previously written PRODUCTION web sites.

**Comment by sideshowbarker** [comment]
> The page that has been there for many years and is linked from many places online. MDN needs to cover ALL web technologies, not just the LATEST weekly release of the big 3, with no reference how to write PORTABLE, BACKWARDS COMPATIBLE, web sites, or debug previously written PRODUCTION web sites.

While that wouldn’t be an absolutely unreasonable policy to have, it’s not the actual policy that MDN uses. By the policy that MDN actually uses, the “Using the application cache” article was intentionally deleted.

So I’m going ahead and closing this — because by policy the “Using the application cache” article will not be restored.

Sites like https://developer.kaiostech.com/docs/getting-started/main-concepts/caching have the option of doing something like updating their links to the archive.org URL cited in the issue description.
