### ISSUE TITLE
Contextual identity information in cookies API

### ISSUE THREAD

**Issue by rebloor** [mdn/content#8267]
Documentation of the cookies API does not include information about contextual identities. For example, cookies.CookieStore only talks about there being different stores for private vs. non-private windows.

(Consider combining with  [Bug 1750589](https://bugzilla.mozilla.org/show_bug.cgi?id=1750589) More documentation for developers about cookieStoreId field of proxy.RequestDetails.)

**Comment by Rob--W** [comment]
The `cookieStoreId` concept originated from Chrome, where it was used to distinguish between incognito and non-incognito mode (aka private browsing and non-private browsing mode in Firefox).

When the contextual identities feature (possibly more well-known as "container tabs") was introduced, this concept was expanded to also include containers.

Later on, this `cookieStoreId` property was added to other extension APIs where the distinction between container tabs was relevant.

The article at https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Work_with_contextual_identities can be improved, to serve as the canonical location for `cookieStoreId` documentation (and be referenced by all MDN articles that mention `cookieStoreId`).

- "APIs for working with contextual identities" can have another enumeration of all APIs that support `cookieStoreId`
- "Permissions" can be expanded to explain that the use of `cookieStoreId` requires the `"cookies"` permission if that API allows the modification of cookies. For example, in the `tabs.query` API, `cookieStoreId` does not require the `"cookies"` API since reading the property doesn't affect the integrity of cookies in containers. Using `tabs.create` on the other hand does, because it allows the creation of cookies in a specific container. This relaxed permission requirement was introduced in https://bugzilla.mozilla.org/show_bug.cgi?id=1662329 (see bug for more context).

**Comment by rebloor** [comment]
Thanks @Rob--W

**Comment by Rob--W** [comment]
Update the links in the `downloads` documentation when there is a canonical place for `cookieStoreId` documentation, see https://github.com/mdn/content/pull/8106#pullrequestreview-744412976

**Comment by Rob--W** [comment]
There is an introduction to containers at https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/contextualIdentities, but it does not mention `cookieStoreId` or https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Work_with_contextual_identities . Could you fix that too?
