### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by SnyMaster** [mdn/content#8387]
Bad link https://ajf.me/websocket/#libs (A more extensive list of frameworks and libraries here) on page https://ajf.me/websocket/#libs in chapter "Tools".

**Comment by himanshugarg** [comment]
Thanks @SnyMaster for reporting. Could you please add a link to the page that has this bad link? I [couldn't locate](https://www.google.com/search?channel=fs&client=ubuntu&q=ajf.me+site%3Adeveloper.mozilla.org) this link

**Comment by SnyMaster** [comment]
Hi! A link to the page that has this bad link is https://developer.mozilla.org/ru/docs/Web/API/WebSockets_API#tools.
The title of this bad link is "A more extensive list of frameworks and libraries here".
Thanks!

**Comment by sideshowbarker** [comment]
The problem link exists only in the Russian-localized article at https://developer.mozilla.org/ru/docs/Web/API/WebSockets_API#tools.

So I need to go ahead and close this, because we’re not currently making any updates to the Russian-localized content.

https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ documents the MDN course of action with regard to translations, which is that the set of locales for which changes can be made is the following:

* Simplified Chinese (zh-CN)
* Traditional Chinese (zh-TW)
* French (fr)
* Japanese (ja)

All locales other than those are frozen unless/until someone submits a proposal for maintaining them going forward, “including evidence of an active team willing to be responsible for the work associated with that locale”.

If/when someone comes forward with such a proposal and evidence, we can revisit this issue.
