### ISSUE TITLE
Issue with "Silly story generator": …

### ISSUE THREAD

**Issue by coderAndProgrammer** [mdn/content#856]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Silly_story_generator

#### What information was incorrect, unhelpful, or incomplete?
Instructions asked the user to do what wasn't taught in the module. The "Silly Story Generator" was supposed to be an assessment of what should have been learned from the module.

#### Specific section or headline?
For example, the instructions asking the user to manipulate the html.

#### What did you expect to see?
I expected to only be assessed concerning what was taught.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/silly_story_generator`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Silly_story_generator
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/javascript/first_steps/silly_story_generator/index.html
* Report started: 2021-01-02T15:28:31.816Z

</details>

**Comment by chrisdavidmills** [comment]
The only thing the example asks you to do concerning your HTML is to add a `<script>` element to apply the JS to the HTML.

And that's covered at https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_is_JavaScript#How_do_you_add_JavaScript_to_your_page.

I'm closing this now, but feel free to respond if you have any further questions.

**Comment by coderAndProgrammer** [comment]
So are you saying that a beginner user like me should finish the "Silly
Story generator" without manipulating the html?

Although it may not have been explicitly instructed for this example, it is
necessary to know how to manipulate html with js in order to complete the
project.

**Comment by chrisdavidmills** [comment]
Thing is, it's difficult to write any kind of client-side JavaScript example that does anything much, without manipulating HTML in any way. Unless you get into a load of complex API stuff like Web Audio or WebGL, which would be way too complex for beginners.

In this example, I tried very hard to make it so that the parts that the reader actually has to write for themselves are covered in the module — all the string manipulation and math stuff, etc.

The only gray area, IMO, is the bit where it asks you to call an existing function. But the actual HTML manipulation stuff is pretty much written for you.

Do you think there is anything we could add to make this easier to swallow?
