### ISSUE TITLE
[JS] Intl.NumberFormat updates

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#8617]
## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

Check through `Intl.NumberFormat` v3 and make sure docs are up to date

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1648137

MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript

**Comment by teoli2003** [comment]
@rumyra, @hamishwillee Do you know if this has landed? In other words, should bcd be updated to mark Gecko as supporting this since 93, or is it behind a flag?

(I'm trying to get #17848 solved)

**Comment by hamishwillee** [comment]
@teoli2003 This has landed in nightly only (which you can see here: https://searchfox.org/mozilla-central/source/js/src/builtin/intl/NumberFormat.js#640). 
- This seems to be more common than using a flag for JS-specific updates.
- This is at stage 3. There is no shipping bug yet as far as I can see.

So yes, BCD should be updated to indicate this is supported in "tech preview". I'll try take care of that (now I know about it) once I have cleared the release stuff for this month. I will add a note to your issue. THanks for keeping us posted!

@Rumyra I've added this issue to our release project. Technically it's not much of an omission because this has not shipped, but these issues should be in our backlog at least. I think the best way to manage this is to do a sweep on the old issues with fixed and dev-doc-needed and make sure the work has been done or there is a corresponding issue in our backlog. Do you want to sort that, or should I put that on "my" backlog (or some other action?).

**Comment by teoli2003** [comment]
Thank you, I've created mdn/browser-compat-data#16840 to get the bcd fixed.

**Comment by hamishwillee** [comment]
- [ ] BCD
- [ ] Docs
  - [ ] #18258
  - [ ] ?
- [ ] dev-doc-complete

**Comment by hamishwillee** [comment]
All done!

**Comment by Rumyra** [comment]
Great! Thanks @hamishwillee \o/
