### ISSUE TITLE
[Web API] `device-pixel-content-box` for ResizeObserver

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#8622]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

At a quick pass it seems `device-pixel-content-box` is now an option for `ResizeObserverBoxOptions` see: https://drafts.csswg.org/resize-observer/#resize-observer-interface which I think is what this bug is referencing. Resize Observer API docs should be checked against spec and updates made

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1587973

**Comment by rachelandrew** [comment]
The docs already include this as a possible value.

**Comment by rachelandrew** [comment]
I'm not sure what to do with regard to BCD. The value is one of three values that are accepted as part of the options for ResizeObserver.Observe. In the spec it's an enum: https://drafts.csswg.org/resize-observer/#resize-observer-interface

Chrome added this value in 84 https://web.dev/device-pixel-content-box/

Do we want to add a note to the observe property? Or add this as a separate thing, and if so should that be on ResizeObserver itself or the observe property? cc: @ddbeck

**Comment by ddbeck** [comment]
@rachelandrew For BCD, here's what I'd suggest:

- Create a new subfeature, `api.ResizeObserver.observe.options_box_parameter` (following [the parameter guidelines here](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines.md#parameters-and-parameter-object-features)).
- Since it looks like the `options` parameter has been there since the beginning, copy the data from the parent feature.
- Lastly, for Chrome (and its derivatives), add a note along the lines of "Before version 84, the <code>device-pixel-content-box</code> value is not supported."

**Comment by Rumyra** [comment]
Thanks @rachelandrew
