### ISSUE TITLE
Missing Thunderbird localization page

### ISSUE THREAD

**Issue by Parodper** [mdn/content#8646]
The link [Thunderbird Localization](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Thunderbird/Thunderbird_Localization) from [Get Involved, section *Translation*](https://www.thunderbird.net/en-US/get-involved/#translation) is broken. From where is the current Thunderbird localization managed from?

**Comment by sideshowbarker** [comment]
https://web.archive.org/web/20210601123644/https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Thunderbird/Thunderbird_Localization

**Comment by Parodper** [comment]
Thanks. Is there any reason this page was deleted?

**Comment by sideshowbarker** [comment]
> Thanks. Is there any reason this page was deleted?

The entire https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Thunderbird tree was deleted — so it’s not just that there was anything in particular about the Localization page.

I was not involved in the discussions that led to the decision to delete the Thunderbird-related docs from MDN, but I can imagine some of the reasons were probably:

* The current scope of MDN is to provide docs for web-platform features, regardless of which product/browser people use for accessing the web — and so that scope does not include documenting specific products such as Thunderbird.
* Thunderbird is, anyway, an e-mail client — not a web browser — and so even as a product that’s always  made it somewhat out of step with the vast majority of the rest of the MDN content
* I think nobody had been maintaining the Thunderbird-related MDN docs for quite a long time

**Comment by Parodper** [comment]
I guess this issue can be closed then. Thanks for the info. I'll try to raise the issue with the current Thunderbird's Get Involved page maintainers.
