### ISSUE TITLE
[FF92] [HTTP] Enabling HTTPS RR on release

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#8683]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

Worth checking the http learning sections & glossary

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1721132

## Other

For ref: https://emilymstark.com/2020/10/24/strict-transport-security-vs-https-resource-records-the-showdown.html

**Comment by hamishwillee** [comment]
This actually delivered in FF92. However it isn't completely clear what delivered since the proposed release note sounds different than what was published. There is no documentation on HTTPS RR.

I think we should add an MDN release note to FF92 on this. Maybe also a glossary entry on HTTPS RR with links to spec.. Not clear to me then what engineering think is needed. Have asked here: https://bugzilla.mozilla.org/show_bug.cgi?id=1721132

**Comment by Rumyra** [comment]
Thanks so much @hamishwillee - really appreciate the investigation. I saw a note on FF92 but it didn't come up when bug searching for that project (another thing that highlights the project process needs a good overhaul).

I'm totally on board with a release note to FF92 & glossary page and am also interested in the response for more info.

**Comment by hamishwillee** [comment]
@Rumyra You're most welcome. More fun doing this than the tracking the project :-)

All done in https://github.com/mdn/content/pull/8897 - Release note and glossary

Kershaw Chang is going to write a blog at some point, which we might link, but this is all that should be needed for now.

**Comment by Rumyra** [comment]
Brill! Thanks @hamishwillee
