### ISSUE TITLE
Content suggestion: Adding Bootstrap tutorial

### ISSUE THREAD

**Issue by ghost** [mdn/content#8748]
## What is the new suggestion?

I want you to add Bootstrap full tutorial. I want to learn this CSS and JS framework from your website.

## Why is it important or useful?

Nowadays people are using Bootstrap, I also use it. They have their documentation, but their words are too hard for me to understand. I want it to learn from your documentation. I think it may take 100+ pages and 1/2 months to write. In my opinion, if you add bootstrap to your documentation, it will be very much useful for the web developers, Because, you have challenges, real practice and much more details about any topic but the official bootstrap documentation has not.  Thank you.

**Comment by Un-index** [comment]
While it may be beneficial to have a resource for learning Bootstrap at mdn, there are **several** that already exist: 

https://bfy.tw/Rdsd

if the main reason you want this to happen is because you don't understand the wording in bootstrap's docs and might, for e.g want some more explanation of their components' usage etc., have you tried any existing tutorials/resources for learning to work with Bootstrap?

**Comment by sideshowbarker** [comment]
Closing for lack of response
