### ISSUE TITLE
Issue with "Add to Home screen": mention that a 192x192 PNG file is required in the manifest

### ISSUE THREAD

**Issue by Screwtapello** [mdn/content#8986]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Add_to_home_screen

#### What information was incorrect, unhelpful, or incomplete?

The description of the manifest suggests an "icons" key is required, but does not describe any limitations on the number, size, or type of icons required. It turns out, there are some!

#### Specific section or headline?

The heading "How do you make an app A2HS-ready?", inside the sub-heading "Manifest"

#### What did you expect to see?

Something along the lines of:

> A collection of icons that the browser can use to represent this application. Different browsers on different platforms may prefer different icons in different contexts, but at minimum you must provide a PNG file of exactly 192x192px.

#### Did you test this? If so, how?

The MDN docs imply (by omission) that any icon will do. This is false, since my first attempt (a 128px SVG icon) did not work.

The Chrome DevTools' "Lighthouse" validator says:

> Manifest does not contain a suitable icon - PNG, SVG or WebP format of at least 144px is required, the sizes attribute must be set, and the purpose attribute, if set, must include "any".

...so I resized my SVG icon to 256px (greater than 144px!), but this did not work.

[The Google docs](https://web.dev/install-criteria/#criteria) suggest that a 192px and a 512px image are required. This is blatantly false, since the MDN example works in Chrome with only a 192px image, but I tried doubling my SVG again up to 512px, still no success.

I scaled the SVG back down to 192px, but that didn't help either.

It was only when I rendered my icon to PNG that I got prompted to install my website as an app in (Linux) Chrome and (Android) Firefox.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/progressive_web_apps/add_to_home_screen`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Add_to_home_screen
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/progressive_web_apps/add_to_home_screen/index.html
* Last commit: https://github.com/mdn/content/commit/4a23c30c528fa31a276b2f0448b650556e42fdf1
* Document last modified: 2021-03-17T03:44:53.000Z

</details>

**Comment by captainbrosset** [comment]
I think this should now be closed. The PWA docs have been updated quite heavily since this issue got posted.
The page the reporter mentioned now redirects to https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Guides/Making_PWAs_installable which, I think, does a better job at introducing why icons are important and then links out to the reference docs about the icons manifest.

There's also a new How-To page specifically about icons here: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/How_to/Define_app_icons

I'll go ahead and close this. Feel free to re-open if you don't agree.
