### ISSUE TITLE
Issue with "Digest header field": no browser support

### ISSUE THREAD

**Issue by reschke** [mdn/content#9139]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Digest

#### What information was incorrect, unhelpful, or incomplete?

The claim that this field has any browser support.

AFAIU, there is none (FWIW, this field has nothing to do with HTTP Digest Authentication)

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/headers/digest`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Digest
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/digest/index.md
* Last commit: https://github.com/mdn/content/commit/c892de11438fef20b9219cad29bbcc763e43119f
* Document last modified: 2021-09-15T04:46:01.000Z

</details>

**Comment by digi-booster** [comment]
[Global support 49.34%.](https://caniuse.com/mdn-http_headers_digest)

**Comment by reschke** [comment]
Yes, it is.

What does the test test?

**Comment by cyclaero** [comment]
Obviously, you both are talking about different subjects.

@Julian Reschke, of course virtually all browsers support Digest Authentication as layed out in the obsoleted RFC2617.
@digi-booster, except Opera and now the upcomming FF93, no browser supports the current RFC7616 beyound MD5.

It is easy to solve the documentation issue, by replacing the simple Term "Full support" with "Full support of RFC2617" and add another Term "Support of RFC7616" and a second row in the comaptibilty list. Note, on how I suggest to forget the attibute "Full" here. To my knowledge FF93 and Opera shall be green (perhaps a tad lighter) in the second row and all the others shall be dark red. The list must be verified before publication, but it would be worth the effort, since it is still sort of a unique selling point of the upcomming Firefox.

Obervations:
I took part in the discussion about this enhancement on bugzilla, see:
https://bugzilla.mozilla.org/show_bug.cgi?id=472823#c9
https://bugzilla.mozilla.org/show_bug.cgi?id=472823#c14

Julian Reschke seems to be a comittee member of the IETF for the relevant RFCs. Since he started to vote in, I think it might be great opportunity to ask him everything you always wanted to know about Digests, but were afraid to ask.

Anyway, please do my a favour. Whatever comes out of the upcomming discussion, please let FF93 go with the new implementation. Otherwise, I am afraid to wait another 5 years for the highly welcome feature. My own proprieatary device control servers support this already since 2016. And in order  to better understand, why this is important, please read my comment #14 on said bugzilla thread.

**Comment by reschke** [comment]
@cyclaero - this documentation issue is not about "HTTP Digest Authentication", it is about the "Digest" header field, which has nothing to do with HTTP Authentication.

**Comment by cyclaero** [comment]
OK, now I see. Then why does this come up in the bugzilla about SHA256 Digest Authentication?

I am interessted in HTTP Digest Authentication according to RFC7616. Let's keep this issues separated.

**Comment by reschke** [comment]
> OK, now I see. Then why does this come up in the bugzilla about SHA256 Digest Authentication?

Because of https://bugzilla.mozilla.org/show_bug.cgi?id=472823#c53

**Comment by hamishwillee** [comment]
@reschke So this is really a question for browser compatibility data. Looking at the git blame I found this: https://github.com/mdn/browser-compat-data/pull/4600

>  wasn't sure what to put for this, as browsers don't really have anything to do to support `Digest` or `Want-Digest`, as far as I can tell.
>
> That is, the spec doesn't say when browsers should include `Want-Digest`, or what they should do when they receive `Digest`. It seems to be a thing for the application.
>
> There's some discussion about this issue in https://discourse.mozilla.org/t/bcd-and-want-digest-digest-http-headers/43340.
>
> So I have just used true here, since all browsers have to do to support it is include any request headers they are asked to include, and expose any response headers the server sends them.

So that answers why this indicate support. It would certainly be useful to have a note that makes it clear what supported means. Thoughts?

**Comment by reschke** [comment]
I think this is extremely misleading.

Browsers aren't doing anything with these header fields.

**Comment by hamishwillee** [comment]
@reschke It is, but I don't _think_ there is a way around that in BCD currently - you can tag as `null` meaning "unknown" and `false` meaning "not supported" but I don't think you can tag as "not applicable". I guess the best you could do right now is tag one of those and then add a note against each one to indicate "Not applicable". 

I've asked the experts https://github.com/mdn/browser-compat-data/issues/12533

**Comment by sideshowbarker** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Digest#browser_compatibility no longer incorrectly shows any browser support for the `Digest` header — so I’m going ahead and closing this.

@reschke If I’ve misunderstood and there’s more that needs to be done here, this can be re-opened.
