### ISSUE TITLE
Issue with "Array": Arrays cannot use strings as element indexes?

### ISSUE THREAD

**Issue by joekingTheThird3** [mdn/content#9437]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array

#### Specific section or headline?
Description
Arrays cannot use strings as element indexes (as in an associative array) but must use integers.

#### What did you expect to see?
Not sure. I think I am confusing the low level implementation and my intuitive usage.
It seems like I can use a string index to access an item in the array.

#### Did you test this? If so, how?
arr=["a","b","c","d",]
arr[0]
arr["0"]
arr["1"]="neg"
arr[1]

/* further issue */
the line ' for your particular use, you might consider using typed arrays'
can you link to  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays on phrase 'typed arrays'?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/index.md
* Last commit: https://github.com/mdn/content/commit/9e7347af24ffb941643d365fe36c05c3bd21b633
* Document last modified: 2021-09-03T15:24:53.000Z

</details>

**Comment by ddbeck** [comment]
@joekingTheThird3 Thanks for opening this issue. I think you've chanced upon a broader language "feature" of JavaScript.  It may appear that you've used a string to index an array, when JavaScript has coerced the string to an integer. In some cases, such as this one, it's somewhat surprising behavior. It's not mentioned specifically here, since you'd encounter it in many places in the language (such as doing something like `Math.abs("-365")` which returns `365`). Plus, it's a rather confusing practice—I don't recommend it.

I hope this clears things up. Since I don't think there's any content changes needed here, I'm going to close the issue. Thank you again!
