### ISSUE TITLE
Content bug: "Edit on GitHub" link is broken

### ISSUE THREAD

**Issue by AdrianSkar** [mdn/content#9674]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Async_await
## Specific page section or heading?

Footer:
![image](https://user-images.githubusercontent.com/12052430/136588300-19b31fca-5839-41f5-87b1-40afd1cc5019.png)

## What is the problem?
The link leads [here ](https://github.com/mdn/content/edit/main/files/en-us/learn/javascript/asynchronous/async_await/index.html) instead of [here](https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/asynchronous/async_await/index.md).

## What did you expect to see?
https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/asynchronous/async_await/index.md

## Did you test this? If so, how?

Access links from different devices and browsers

**Comment by wbamberg** [comment]
Thanks for filing!

Most likely this is because there's a delay between the files in GitHub changing and MDN re-deploying.

The Markdown conversion for Learn only landed 10 hours ago (https://github.com/mdn/content/pull/9632) and it could take a day or maybe even two before the site is redeployed. So in the meantime the deployed pages are linking to a page that was renamed.

Please try again tomorrow or the next day, and see if this error goes away.

**Comment by AnilSeervi** [comment]
They've been restored now. This issue can be closed :)
