### ISSUE TITLE
Issue with "Document: drop event": Mention that drop won't fire unless you preventDefault in dragover

### ISSUE THREAD

**Issue by voracity** [mdn/content#9796]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/drop_event

It might be useful to mention that drop won't fire until you preventDefault in dragover, because it's worse than unintuitive.

**Comment by srcengine** [comment]
How about a pointer?  To: [https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API#define_a_drop_zone](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API#define_a_drop_zone)

**Comment by postmeback** [comment]
Can I contribute over here ?

**Comment by queengooborg** [comment]
> Can I contribute over here ?

@postmeback, you do not need to request permission to contribute to an issue, _especially_ if it has the "help wanted" tag.  As long as you are down to perform the research to confirm the issue is accurate and write a pull request to resolve it (or write a comment explaining how you have confirmed it is invalid), you are more than welcome to work on any issue that needs assistance!

**Comment by postmeback** [comment]
The previous comment was done in my early days of open source contribution, where I saw many _first-timer_ ask for permission. I know that I don't need anyone's permission. But I consider it as a good gesture, also it helps me to know if somebody already working on it or not.

**Comment by queengooborg** [comment]
We see many users request assignment or otherwise comment on an issue to say that they'd like to/will work on something.  Truthfully, though, only a small handful actually follow through and submit a pull request, so we find that such comments are unhelpful.  Additionally, on issues that are _this_ old, if someone hasn't already worked on it, there's a 99% chance nobody is working on it yet.  :)
