### ISSUE TITLE
Issue with "CSP: block-all-mixed-content": Deprecated without explanation or suggested replacement.

### ISSUE THREAD

**Issue by collinanderson** [mdn/content#9889]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/block-all-mixed-content

#### What information was incorrect, unhelpful, or incomplete?
`block-all-mixed-content` is marked as deprecated, however, there's no explication as to why it's deprecated and no suggestion of a replacement.

#### What did you expect to see?
I expected to either see a suggested replacement, or at least an explication of why `block-all-mixed-content` should not be used in the future.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/headers/content-security-policy/block-all-mixed-content`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/block-all-mixed-content
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/content-security-policy/block-all-mixed-content/index.md
* Last commit: https://github.com/mdn/content/commit/46234997b6257b619423a11ce31154afa336143f
* Document last modified: 2021-08-13T16:17:49.000Z

</details>

**Comment by hamishwillee** [comment]
This was removed because it is obsolete. There is no replacement - it is simply not needed. From the spec: https://w3c.github.io/webappsec-mixed-content/#obsolescences :

> An earlier version of this specification defined the `block-all-mixed-content` CSP directive. It is now obsolete, because all mixed content is now blocked if it can’t be autoupgraded.

I am hesitant to add a note because MDN has no policy on what you do about reasons and alternatives (and yes, it has come up a number of times). I have added discussion in https://github.com/mdn/content/discussions/5549#discussioncomment-1499176
